### ISSUE TITLE
Duplicate global key when navigating between 2 screens that have formKey

### ISSUE THREAD

**Issue by xEyad** [jonataslaw/getx#1000]
**Describe the bug**
basically i have 2 screens each with their own controllers and every one of the controllers contains a GlobalKey<FormState> that is used by their respective view (both of them have their own Form widget that uses the controller's key)
this happens when you navigate back and forth from one widget to another

**Reproduction code**

example:

```dart
void main() => runApp(sandbox());


dynamic sandbox()
{
  return GetMaterialApp(
        title: 'Getx issue',
        debugShowCheckedModeBanner: false,
        home: Screen1()); 
}



class Screen1Ctrl extends GetxController {
  var _formKey = GlobalKey<FormState>();

}

class Screen1 extends GetView<Screen1Ctrl>
{
  Screen1()
  {
    Get.put(Screen1Ctrl());
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: 
      Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Form(
            key: controller._formKey,
            child: TextFormField(decoration: InputDecoration(labelText: 'screen 1 input'),),),
        RaisedButton(child: Text("go to screen2"),onPressed: ()=>Get.to(Screen2()))
      ],)
    ,),
    );
  }
}
class Screen2Ctrl extends GetxController {
  var _formKey = GlobalKey<FormState>();

}

class Screen2 extends GetView<Screen2Ctrl>
{
  Screen2()
  {
    Get.put(Screen2Ctrl());
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: 
      Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Form(
            key: controller._formKey,
            child: TextFormField(decoration: InputDecoration(labelText: 'screen 2 input'),),),
        RaisedButton(child: Text("go to screen1"),onPressed: ()=>Get.to(Screen1()))
      ],)
    ,),
    );
  }
}

```

**To Reproduce**
1. Click on 'go to screen 1'
2. Click on 'go to screen 2'

**Expected behavior**
that every screen has it's formKeys separated

**Flutter Version:**
1.22.5 stable channel

**Getx Version:**
^3.22.2

**Describe on which device you found the bug:**
ex: emulator android

**Comment by eduardoflorence** [comment]
On `Screen2`, when you did `Get.to(Screen1())` Flutter's navigation stack now has Screen1 twice and that is why the duplication error occurs. Change to Get.back():
```dart
Form(
  key: controller._formKey,
  child: TextFormField(decoration: InputDecoration(labelText: 'screen 2 input'),),
),
RaisedButton(child: Text("go to screen1"), onPressed: () => Get.back())
```

**Comment by xEyad** [comment]
> On `Screen2`, when you did `Get.to(Screen1())` Flutter's navigation stack now has Screen1 twice and that is why the duplication error occurs. Change to Get.back():
> 
> ```dart
> Form(
>   key: controller._formKey,
>   child: TextFormField(decoration: InputDecoration(labelText: 'screen 2 input'),),
> ),
> RaisedButton(child: Text("go to screen1"), onPressed: () => Get.back())
> ```

2 points.
first, i thought that Get main featureis that it doesn't duplicateroutes when they are alreadyiin the stack.

Second,i can't depend in back because my real use case scenario is that the user can do something like this: 
Uaer go to the screens in an order eoughly like this...
screen 1 
Screen 2
Screen 3
Screen 1.   <---- problematic

**Comment by eduardoflorence** [comment]
GetX does not duplicate the controllers associated with the routes, but the routes can be duplicated if you do not pop.  This is a feature of Flutter and not Getx.

**Comment by jonataslaw** [comment]
You cannot have stacked screens using the same globalkey.
Get.to(Widget()) you are literally stacking the widget you use inside the to stack.

If you need more than one controller because you are going to stack two equal routes, use Get.create + GetWidget. If you want to go back to the first one, you should pop up the page.

**Comment by phuongphally** [comment]
I resolve form duplicate key by remove final keyword likes 

from 

```
  final formTitle = GlobalKey<FormBuilderState>();
  final formPrice = GlobalKey<FormBuilderState>();
  final formShipping = GlobalKey<FormBuilderState>();
  final formPromotion = GlobalKey<FormBuilderState>();

```
or 

```
 var formTitle = GlobalKey<FormBuilderState>().obs;
 var formPrice = GlobalKey<FormBuilderState>().obs;
 var formShipping = GlobalKey<FormBuilderState>().obs;
 var formPromotion = GlobalKey<FormBuilderState>().obs;

```


to 



```
  GlobalKey<FormBuilderState> formTitle = GlobalKey<FormBuilderState>();
  GlobalKey<FormBuilderState> formPrice = GlobalKey<FormBuilderState>();
  GlobalKey<FormBuilderState> formShipping = GlobalKey<FormBuilderState>();
  GlobalKey<FormBuilderState> formPromotion = GlobalKey<FormBuilderState>();

```

**Comment by ardeshir-33033** [comment]
> > On `Screen2`, when you did `Get.to(Screen1())` Flutter's navigation stack now has Screen1 twice and that is why the duplication error occurs. Change to Get.back():
> > ```dart
> > Form(
> >   key: controller._formKey,
> >   child: TextFormField(decoration: InputDecoration(labelText: 'screen 2 input'),),
> > ),
> > RaisedButton(child: Text("go to screen1"), onPressed: () => Get.back())
> > ```
> 
> 2 points.
> first, i thought that Get main feature is that it doesn't duplicate routes when they are already in the stack. (that's the reason i use Get in the first place)
> 
> Second,i can't depend on Get.back() because my real use case scenario is that the user can do something like this:
> Uaer go to the screens in an order roughly like this...
> screen 1
> Screen 2
> Screen 3
> Screen 1. <---- problematic

did you found any solution to this?

**Comment by fy5220** [comment]
> > > On `Screen2`, when you did `Get.to(Screen1())` Flutter's navigation stack now has Screen1 twice and that is why the duplication error occurs. Change to Get.back():
> > > ```dart
> > > Form(
> > >   key: controller._formKey,
> > >   child: TextFormField(decoration: InputDecoration(labelText: 'screen 2 input'),),
> > > ),
> > > RaisedButton(child: Text("go to screen1"), onPressed: () => Get.back())
> > > ```
> > 
> > 
> > 2 points.
> > first, i thought that Get main feature is that it doesn't duplicate routes when they are already in the stack. (that's the reason i use Get in the first place)
> > Second,i can't depend on Get.back() because my real use case scenario is that the user can do something like this:
> > Uaer go to the screens in an order roughly like this...
> > screen 1
> > Screen 2
> > Screen 3
> > Screen 1. <---- problematic
> 
> did you find any solution to this?

did you find any solution to this?

**Comment by kauemurakami** [comment]
Same problem.

**Comment by kevin4dhd** [comment]
any solution? :(

**Comment by yxlwfds** [comment]
同样的问题,有官方指导版本吗
