### ISSUE TITLE
Persistent Bottom Nav Bar and other Widgets that are not a part of the items in BottomNavigationBar

### ISSUE THREAD

**Issue by ljx0520** [jonataslaw/getx#1009]
When we use Go.toNamed to navigate routes, how do we keep the widgets (for example, bottom nav bar) that are not a part of the items of BottomNavigationBar in the new page? I know if we use materialpageroute, it can be implemented by 'Navigator' widget. 

Thanks in advanced.

**Comment by ljx0520** [comment]
solved it via Navigator using Ge.nestedkey, thanks for https://github.com/jonataslaw/getx/issues/799#issuecomment-730719165

**Comment by edoliantesRJ** [comment]
> solved it via Navigator using Get.nestedkey, thanks for https://github.com/jonataslaw/getx/issues/799#issuecomment-730719165

Samole code?
