### ISSUE TITLE
Support only rebuild row in ListView?

### ISSUE THREAD

**Issue by suyana** [jonataslaw/getx#1010]
I see the documentation,i feel it's support only rebuild change widget,but i test,it's always rebuild listview.

I write a page used setStatus() and test,i'm found use getx and use setStatus() rebuild count is equal.

there is my setStatus code:
`class List1DemoPage extends StatefulWidget {
  @override
  _List1DemoPageState createState() => _List1DemoPageState();
}

class _List1DemoPageState extends State<List1DemoPage> {
  var data = <SelectedItem>[new SelectedItem(DateTime.now().toString())];
  void btn1() {
    setState(() {
      data.insert(0, new SelectedItem(DateTime.now().toString()));
    });
  }

  void selectRow(bool value, int index) {
    setState(() {
      data[index].fselected = value;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: WidgetFactory.getAppBar('List1'),
        body: (Column(
          children: [
            RaisedButton(
              onPressed: btn1,
              child: Text('add'),
            ),
            Expanded(
                child: ListView.builder(
                    itemCount: data.length,
                    itemBuilder: (context, index) => (Card(
                            child: Row(
                          children: [
                            Checkbox(value: data[index].fselected, onChanged: (v) => selectRow(v, index)),
                            Column(children: [
                              Text(data[index].fbarcode),
                            ])
                          ],
                        )))))
          ],
        )));
  }
}`

there is my GetX code:
`class HomeController extends GetxController {
  final data = <SelectedItem>[new SelectedItem(DateTime.now().toString())].obs;

  void btn1() {
    data.insert(0, new SelectedItem(DateTime.now().toString()));
  }

  void selectRow(bool value, int index) {
    var todo = data[index];
    todo.fselected = value;
    data[index] = todo;
  }
}

class List2DemoPage extends GetView<HomeController> {
  @override
  Widget build(BuildContext context) {
    HomeController c = Get.put<HomeController>(HomeController());
    return Scaffold(
        appBar: WidgetFactory.getAppBar('List2 - GetX'),
        body: Column(
          children: [
            RaisedButton(
              onPressed: c.btn1,
              child: Text('add'),
            ),
            Expanded(
                child: Obx(() => ListView.builder(
                      itemBuilder: (context, index) {
                        return Card(
                            child: Row(
                          children: [
                            Checkbox(value: c.data[index].fselected, onChanged: (v) => c.selectRow(v, index)),
                            Column(children: [Text(c.data[index].fbarcode)])
                          ],
                        ));
                      },
                      itemCount: c.data.length,
                    )))
          ],
        ));
  }
}`

when app running,two page rebuild count is equal (both add row or checkbox changed)

version:
Flutter 1.25.0
get: ^3.24.0

**Comment by jonataslaw** [comment]
You are using setState and StatefulWidget.
setState Will rebuild ALL widget
