### ISSUE TITLE
Send data to previous screen Get.back()

### ISSUE THREAD

**Issue by rupamking1** [jonataslaw/getx#1015]
not option to Send data to the previous screen using Get.back()

**Comment by rupamking1** [comment]
no option to call a function when POP or Push pages (.to / .back)
plsease fix it or make it.

**Comment by eduardoflorence** [comment]
To navigate to the next route, and receive or update data as soon as you return from it:

var data = await Get.to(Payment());

on other screen, send a data for previous route:

Get.back(result: 'success');
And use it:

ex:

if(data == 'success') madeAnything();

**Comment by jonataslaw** [comment]
Please, read the docs

**Comment by rupamking1** [comment]
Thank you & I will read your docs.

**Comment by infazA** [comment]
It was not in document, I checked it and could not find it.
