### ISSUE TITLE
[GetConnect] using get() method response is not giving ("Not Found Error"). 

### ISSUE THREAD

**Issue by vinayakyengandul** [jonataslaw/getx#1022]
- Describe the bug
   used get() method for API response is passing all inputs fir it (url, query, header).

- Example of get() method with query :- 

      class DataProvider extends GetConnect {
          @override
          void onInit() {
          }

          Future<Response> responseData() async {
            return get('https://api.digitransit.fi/graphiql/finland',
                query: _convertStringToMap(classquery.Query),
                headers: {'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJCNzUtVWlTT0dOVzNleGhhTkttQjVqVGx6UVkxNUtkenRGRjFDV0xScXpJIn0.eyJleHAiOjE2MTEwNjIwOTUsImlhdCI6MTYxMTAyNjA5NSwianRpIjoiOWFiNTQ3M2MtNmRhZC00MDZjLTg0MTItZTdlOTAwOGRhNjE3IiwiaXNzIjoiaHR0cDovLzQ5LjI0OC4xNC4yMzc6ODA4Mi9hdXRoL3JlYWxtcy9DdXN0b21lci1Qb3J0YWwiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiZjlhMzU5NDktMjJmZi00YzZlLTgyN2EtMTU0Y2I2MWViNGVlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZGVtb2NsaWVudDEiLCJzZXNzaW9uX3N0YXRlIjoiMTU0N2RmOWEtNjZiZC00NjE3LTkzZmUtMDc4MTAwYWFlYjgyIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZGF0YWJhc2UiOiJwb2NrZXRtYXN0ZXIiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm91c2VyX3JpZCI6IiM2OjMiLCJuYW1lIjoiZGluZXNoIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZGluZXNoIiwiZ2l2ZW5fbmFtZSI6ImRpbmVzaCIsInJpZCI6IiMyMjoxIiwiZW1haWwiOiJkaW5lc2hAZ3JleXRyaXguY29tIn0.UJwrsHC95V3_Jnm3AzRaglE69n-g-cYwOaQ_0NKismUfOuY2iqL56fkYOKkm709Ltoo3oDJAchIHKkjvTnloBFzv_49_Bc-_Q75vj_undxBlDFeDTFQ1MhVh53SJ_ViLx4Cw_XXPFN7LB24Y9DWPLYymycqPAUY9CxTUaQDETWUAXpSp1CUEEmdGmYijeo9UO2bQzSFy17dOtdRvzb2yjXTYNBeY0S_vPDqrhnLW4FC5m8PQqCd6jNI8XaO2lRKnBvXz6RdzKlKR5-_tbbEEivk-Adk0BB78xIqrWZEqt_j_4QKg-eR7Zj9ReE0qQf53-xc0HFL0qEktqX-mHyKfbQ'}
            );
          }
          Map<String, dynamic> _convertStringToMap( String product )
          {
            Map<String, dynamic> map = {};
            map['query'] = product;
            return map;
          }
        }

      class classquery {
          static const Query = '''query{
          agencies{
            name
          }
        }
        ''';
        
        }

- Error Description in logs:
     hasError >>> XMLHttpRequest error.

- Flutter Version

      Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
      Framework • revision 198df796aa (3 months ago) • 2020-10-15 12:04:33 -0700
      Engine • revision 1d12d82d9c
      Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)

- GetX version

      get: ^3.24.0

**Comment by jonataslaw** [comment]
Please note that you are trying to query graphql using a GET http method.
I recommend that you read about GraphQL so that you know how it works.
