### ISSUE TITLE
code never enters to onready method in controller

### ISSUE THREAD

**Issue by halkportal970** [jonataslaw/getx#1023]
After upgrade from 3.11.1 to  3.24.0 code never enters to onReady methods in my page controllers.
Is it a bug? Am I using wrong?
```
class MyController extends GetxController {

      @override
      void onInit() {
      print("entered onInit");
    }

      @override
      void onReady() {
      print("entered onReady");
    }

}
```

**Comment by eduardoflorence** [comment]
See an example here: https://gist.github.com/eduardoflorence/69277755dd4947f751fe7aac58e157ef

**Comment by halkportal970** [comment]
Thanks @eduardoflorence , but why onInit and onReady wants super.onInit(); and super.onReady(); at the and of the method? When I create page from terminal with "get create page:testPage " there is no super, on  controllers onInit and onReady methods.

**Comment by eduardoflorence** [comment]
This is mandatory for the controller's lifecycle

**Comment by jonataslaw** [comment]
Relationed to https://github.com/jonataslaw/get_cli/pull/50
