### ISSUE TITLE
Get.back() on Get.defaultDialog not working.

### ISSUE THREAD

**Issue by farsuller** [jonataslaw/getx#1024]
Upon using Get.defaultDialog in actions I added a Raised Button widget on the onPressed I put there the Get.back(), which the expected result is the dialog will close, but it doesn't.

**Comment by eduardoflorence** [comment]
Show your code, please.

**Comment by farsuller** [comment]
Hello @eduardoflorence sorry for late response heres the portion of the code.
`Get.defaultDialog(title: 'Login Failure',
          radius: 5.0,
          middleText: result,
          actions: [
            RaisedButton(
              onPressed: ()=>Get.back(),
              child: Text("OK",
                style: TextStyle(color: Colors.white),
              ),
              color: Colors.black,)
          ],
          );`

**Comment by farsuller** [comment]
Here's the another set of code, `RaisedButton(onPressed: (){
                        Get.defaultDialog(title: 'Login Failure',
                          radius: 5.0,
                          middleText: "result",
                          actions: [
                            RaisedButton(
                              onPressed: (){
                                print("test");
                                Get.back();
                                },
                              child: Text("OK",
                                style: TextStyle(color: Colors.white),
                              ),
                              color: Colors.black,)
                          ],
                        );
                      }),`

**Comment by vinayakyengandul** [comment]
Same Issue found for me.

version : get: ^3.24.0

**Comment by eduardoflorence** [comment]
Hi @farsuller and @vinayakyengandul, I did the test now and it is working normally. Here is the test code:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(home: HomePage()));
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('HOME')),
      body: Center(
        child: RaisedButton(
          child: Text('Open Dialog'),
          onPressed: () => Get.defaultDialog(
            title: 'Login Failure',
            radius: 5.0,
            middleText: "result",
            actions: [
              RaisedButton(
                onPressed: () {
                  print("test");
                  Get.back();
                },
                child: Text(
                  "OK",
                  style: TextStyle(color: Colors.white),
                ),
                color: Colors.black,
              )
            ],
          ),
        ),
      ),
    );
  }
}
```
