### ISSUE TITLE
Can't delete GetxService with force: true

### ISSUE THREAD

**Issue by Apollo108** [jonataslaw/getx#1026]
**Screenshots**
![image](https://user-images.githubusercontent.com/16933202/105167611-99f5c000-5b21-11eb-84b0-aa0d03a102c0.png)
![image](https://user-images.githubusercontent.com/16933202/105167978-20aa9d00-5b22-11eb-9122-fdb4e1f52fcd.png)
![image](https://user-images.githubusercontent.com/16933202/105169061-a713ae80-5b23-11eb-930f-c1218c41860a.png)

Why service doesn't get deleted, despite logs are saying it did?
As seen from the screenshot, I can access it afterwards. Thank you in advance!

**Expected behavior**
Error, when trying to access deleted service with Get.find()

**Flutter Version:**
1.22.5

**Getx Version:**
3.24.0

**Comment by eduardoflorence** [comment]
Only Get.reset().
https://github.com/jonataslaw/getx#getxservice

**Comment by Apollo108** [comment]
But Get.reset() will destroy everything, and I need to do that selectively. Is there any option for that purpose?

**Comment by eduardoflorence** [comment]
Exactly, if you use GetxController you can do the selective Delete

**Comment by Apollo108** [comment]
Just attempted to do this - the result is exactly the same as for GetxService...

**Comment by Apollo108** [comment]
@jonataslaw I'm sorry, but can I expect any answer from you, or anybody? Thank you in advance)

**Comment by eduardoflorence** [comment]
@Apollo108, replace 
```
static FakeService to = Get.find();
```
with
```
static FakeService get to => Get.find();
```

**Comment by Apollo108** [comment]
You just saved my day, good sir! Omg, a GetxService gets deleted too! Thank you very much, I think your response deserves to be carved in the tables of documentation to this awesome library!)
