### ISSUE TITLE
Full state widget with instance scope state

### ISSUE THREAD

**Issue by te8uekm12** [jonataslaw/getx#1029]
Hi.
In my application I need full state widget with instance scope state (controller). I found it's possible with using GetWidget class but It needs small change.

In GetWidget class we have final variable tag witch is assigned to null.

```

abstract class GetWidget<S extends GetLifeCycleBase> extends GetWidgetCache {
  const GetWidget({Key key}) : super(key: key);

  @protected
  final String tag = null;
...
}

```

With that implementation it's impossible to have state full widget with state assigned to it's instance. But if you change code like I did below 
```
abstract class GetWidget<S extends GetLifeCycleBase> extends GetWidgetCache {
  const GetWidget({Key key, this.tag}) : super(key: key);

  @protected
  final String tag;
...
}

```

it is possible to implement it that way. 
Could we add this to the GetX library?

Regards,

**Comment by jonataslaw** [comment]
This would make it mandatory to overwrite the tag, and this is not wanted.
It is optional to provide a tag, so in that case we will not be able to change the implementation.

**Comment by te8uekm12** [comment]
Sorry for question but how can I provide value in sub class for final variable when it's not listed in optional constructor parameter list?
