### ISSUE TITLE
I think the routing interceptor capability is needed

### ISSUE THREAD

**Issue by miaosun009** [jonataslaw/getx#1034]
At present, the routing middleware cannot implement the routing interception function.

When jump to a route, use the interceptor to make some conditional judgments, and based on the results, you want to decide whether to go to the route page. The interceptor needs to support async

```
getPages: [
        GetPage(name: '/', page: () => MyHomePage()),
        GetPage(
            name: '/second',
            page: () => Second(),
            interceptors:[
                interceptor
                ...
            ]
        ),
      ],

Futrue<bool> interceptor() async{
    if(...){
         ///...
        return true;
    }
    return fasle;
}
```

middleware is executed almost simultaneously

There is such a demand:
B page needs to meet the login status (login page) and another verification condition (check page) to arrive
When jumping from page a to page B, first redirect to the login page. After successful login, judge another check condition. If the condition is not met, redirect to (check page). If the condition is met, jump to page B

This kind of requirement can't be realized with middleware

**Comment by jonataslaw** [comment]
This is not possible with Flutter, and it never will be. When a user clicks to go to another page, they must immediately be redirected to it. Inserting an asynchronous method that can take seconds in the server's response will make the application appear to hang.
This is a Flutter design issue, and we are in full agreement. Forget asynchronous after navigate, insert this asynchronous event prior to navigator event and preferably notifying the user that something is running.
That said, this feature request violates basic Flutter principles, and design, so it will never be implemented.
Just an addendum, we could make a workaround to work that way, but that would totally break the Flutter web, because the moment the URL is typed, the page would have to be opened immediately. So I think you better rethink the structure of your application better, because anything that works in that sense will be a complete gambling.

In any architecture you use, you can do something like this:

```dart
void openYourRoute() async {
  showLoading();
  final canNavigate = await yourAsyncFetch();
  dismissLoading();
  canNavigate? navigateToOtherRoute() : showError();
}
```

**Comment by qcks** [comment]
Before using GetX, I intercepted routes.
```
Route onGenerateRoute(RouteSettings settings) {
    .....
    var route;
    if (!isLoging)
       return LoginRoute;
    return route;
  }
```
onGenerateRoute: (getPages != null ? generator : onGenerateRoute),//GetX

What does PageRedirect do? How do I use it?

Please open the "generator" method, there will be many people who need to modify it.

GetPage ->middlewares  is not convenient

**Comment by troncomputers** [comment]
`GetMiddleware` is useless then. I can't even check logged user because all storage management libraries are asynchronous.
Can't do that:
```dart
Future<RouteSettings?> redirect(String? route) async {}
```
Not working because the value is returning after redirect
```dart
  @override
  RouteSettings? redirect(String? route) {
    var auth = Get.put(AuthService());
    auth.isAuthenticated().then((value) {
      print(value); // RETURNS "FALSE" HERE
      return value ? null : RouteSettings(name: '/login');
    });
  }
```
How am I supposed to do that?

**Comment by ericaig** [comment]
> `GetMiddleware` is useless then. I can't even check logged user because all storage management libraries are asynchronous.
> Can't do that:
> 
> ```dart
> Future<RouteSettings?> redirect(String? route) async {}
> ```
> 
> Not working because the value is returning after redirect
> 
> ```dart
>   @override
>   RouteSettings? redirect(String? route) {
>     var auth = Get.put(AuthService());
>     auth.isAuthenticated().then((value) {
>       print(value); // RETURNS "FALSE" HERE
>       return value ? null : RouteSettings(name: '/login');
>     });
>   }
> ```
> 
> How am I supposed to do that?

I'm facing the same issue and there just doesn't seem to be an easy way past it. Middleware should be the solution but it needs to support `Future`

**Comment by tony123S** [comment]
I need to add Middleware in splashscreen, if authToken is null, redirect to loginPage, otherwise redirect to MainPage.

My `isLogin` method is returned Future. Please how can I fix it?

**Middleware**
```

class GlobalMiddleware extends GetMiddleware {
  final con = Get.find<LoginPageController>();
  @override
  RouteSettings? redirect(String? route) {
    var value = con.isLoginIn();

    return value == true
        ? RouteSettings(
            name: "/mainPage",
          )
        : RouteSettings(name: "/login");
  }
}
```
**LoginPageController**

```
isLoginIn() async {
    var user = await MySharedPreferences().getUser();
    if (user.auth_token != null) {
      return true;
    } else {
      return false;
    }
  }
```

**Comment by ledjoncili** [comment]
on your main method in main.dart file make sure to wait until Keycloak is initialized.

Add the following lines:
  keycloakService.keycloakEventsStream.listen((event) {

    if (event.type == KeycloakEventType.onReady) {
      runApp(MyApp());
    } 
  });
