### ISSUE TITLE
mainButton: requires a FlatButton, which has been depecrated. 

### ISSUE THREAD

**Issue by godfreycomputing** [jonataslaw/getx#1035]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
The mainButton property of Get.snackbar() requires a FlatButton.  FlatButton has been depracated and needs to use the new TextButton.

**Reproduction code

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Riverpod Tutorial'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Get.snackbar(
              'Title',
              'Message',
              snackPosition: SnackPosition.BOTTOM,
              mainButton: TextButton.icon(
                onPressed: () {},
                icon: Icon(Icons.cancel),
                label: Text('Push Me'),
              ),
            );
          },
          child: Text('Push Me'),
        ),
      ),
    );
  }
}

**To Reproduce**
1. No actions required.  Error on Build Time.

**Expected behavior**
No Build Errors.

**Flutter Version:**
Flutter 1.26.0-12.0.pre • channel dev

**Getx Version:**
Get 3.24.0

**Comment by godfreycomputing** [comment]
In version 1.24, when they release null safety to production, they are going to deprecate them.  I have downloaded the version mentioned (flutter dev channel) and it's showing  a depreciation warning for FlatButton and RaisedButton.  I just switched the types in the get snackbar to to TextButton, I've made it work now, but it will cause problems later on.

**Comment by jonataslaw** [comment]
I will research if the new widgets have a common ancestor with the old ones to maintain compatibility using a higher inherited class.
If not, this change will only be available in GetX 4.0

**Comment by godfreycomputing** [comment]
Looks like there is no common ancestor.  Original buttons come from StatelessWidget and MaterialButton.  New buttons come from StatefulWidget and ButtonStyleButton (My guess is because, you can read the button's state through a MaterialState property).  So, we will have to wait until GetX 4.0.

**Comment by godfreycomputing** [comment]
Flutter 2.0 has deprecated this button, which was released yesterday.  I don't expect an immediate update, but it should be soon.

**Comment by eduardoflorence** [comment]
> Flutter 2.0 has deprecated this button, which was released yesterday. I don't expect an immediate update, but it should be soon.

GetX null safety:
https://pub.dev/packages/get/versions/4.0.0-nullsafety.2
