### ISSUE TITLE
How to pass data from GetView to GetxController?

### ISSUE THREAD

**Issue by pqtrong17** [jonataslaw/getx#1041]
I wanna pass data from a class extends GetView (ex: String, int or event a Widget in contructor of class) to a class extends GetxController. How to make it?

**Comment by jonataslaw** [comment]
Just as you would with a StatelessWidget. GetView is a StatelessWidget, there is no difference.

**Comment by pqtrong17** [comment]
> Just as you would with a StatelessWidget. GetView is a StatelessWidget, there is no difference.

Thanks for response. But I mean how to get a parameter at GetView from Controller?

**Comment by pqtrong17** [comment]
Ex: At HomePage extends GetView have a parameter `int age` in contructor. And how to get parameter `age` from Controller?

**Comment by daveMcelf** [comment]
I think it should work the other way round. Your Controller should handle all the data and logic, not your View. Instead of passing data via constructor to `HomePage`, you should pass it via `HomeController` constructor instead.

**Comment by pqtrong17** [comment]
> I think it should work the other way round. Your Controller should handle all the data and logic, not your View. Instead of passing data via constructor to `HomePage`, you should pass it via `HomeController` constructor instead.

I understand that data and logic should handle at Controller. But, if I wanna pass data between two screens, I have must pass it to constructor of GetView. I tried using `argument` of `Get.to` but its null when I print `Get.argument` at second times.

**Comment by daveMcelf** [comment]
Can you show your code when you pass and get your arguments?

**Comment by pqtrong17** [comment]
@daveMcelf 
My depart:
```
class _HomePage extends GetView<_HomeController> {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      body: GetBuilder<_HomeController>(
        builder: (value) => Center(
          child: InkWell(
              onTap: () => Get.to(_Detail(), arguments: 54),
              child: Text("PUSH ARGUMENT")),
        ),
      ),
    );
  }
}
```

and my arrive:
```
class _Detail extends GetView<_DetailController> {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      body: GetBuilder<_HomeController>(
        builder: (value) => Center(
          child: InkWell(
              onTap: () => controller.onGetArgument(),
              child: Text("GET ARGUMENT")),
        ),
      ),
    );
  }

}
```

This is my controller:
```
class _DetailController extends GetxController {
  int age;
  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    onGetArgument();
  }

  void onGetArgument(){
    age = Get.arguments();
    update();
  }
}
```

**Comment by daveMcelf** [comment]
I think you may confuse some part about GetX here.
- First, when using `GetView`, you need to use `Get.put(Controller())` somewhere or just use binding. without that, you cant connect the the controller.
- `Get.arguments` is a get method, not a function. You can access with just `Get.arguments`
- `Get.arguments` should only be used in Controller onInit function, or outside of your build method in View.

**Comment by daveMcelf** [comment]
The fastest way to fix your problem is to change your DetailPage & Controller to this:
```
class _Detail extends GetView<_DetailController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GetBuilder<_DetailController>(
        init: _DetailController(),
        builder: (value) => Center(
          child: InkWell(
            onTap: () => controller.onGetArgument(),
            child: Text("GET ARGUMENT"),
          ),
        ),
      ),
    );
  }
}

class _DetailController extends GetxController {
  int age;
  @override
  void onInit() {
    age = Get.arguments;
    super.onInit();
    // update();
  }

  void onGetArgument() {
    print(age);
  }
}
```

**Comment by pqtrong17** [comment]
> The fastest way to fix your problem is to change your DetailPage & Controller to this:
> 
> ```
> class _Detail extends GetView<_DetailController> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: GetBuilder<_DetailController>(
>         init: _DetailController(),
>         builder: (value) => Center(
>           child: InkWell(
>             onTap: () => controller.onGetArgument(),
>             child: Text("GET ARGUMENT"),
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class _DetailController extends GetxController {
>   int age;
>   @override
>   void onInit() {
>     age = Get.arguments;
>     super.onInit();
>     // update();
>   }
> 
>   void onGetArgument() {
>     print(age);
>   }
> }
> ```

That means is `Get.arguments` is just working one time and we should put it to `onInit` ?

**Comment by pqtrong17** [comment]
Thanks for response, bro.

**Comment by daveMcelf** [comment]
@pqtrong17 You should be able to access `Get.arguments` as many time as you want.

**Comment by pqtrong17** [comment]
> @pqtrong17 You should be able to access `Get.arguments` as many time as you want.

Tks for good support.
