### ISSUE TITLE
AutomaticKeepAliveClientMixin for GetView?

### ISSUE THREAD

**Issue by pqtrong17** [jonataslaw/getx#1042]
I tried `with AutomaticKeepAliveClientMixin` but get an error.
```
AutomaticKeepAliveClientMixin<StatefulWidget>' can't be mixed onto 'GetView<MyController>' because 'GetView<MyController>' doesn't implement 'State<StatefulWidget>'.
```
What replace it? Thanks...

**Comment by eduardoflorence** [comment]
GetView is a StatelessWidget and AutomaticKeepAliveClientMixin can be used only with StatefulWidget

**Comment by jonataslaw** [comment]
I will reopen and move to discussions, because I think about implement this resource on future
