### ISSUE TITLE
Can't use Sliver in Obx/GetBuilder/GetX

### ISSUE THREAD

**Issue by philippbeck** [jonataslaw/getx#1045]
It's not possible to use Sliver Widgets with Get. 
There's always the same error that a RenderBox is expected but it received a child of type RenderSliver...

For example:
A RenderStack expected a child of type RenderBox but received a child of type RenderSliverList.

It's the same problem for Obx, GetBuilder and GetX.

Is there a solution yet?

**Comment by daveMcelf** [comment]
You should put a reproductible code, so that we can test it out.
