### ISSUE TITLE
"getPages:" in "GetMaterialApp" throws error "the getter 'page' was called on null" if "home:" is not specified.

### ISSUE THREAD

**Issue by FabioPagano** [jonataslaw/getx#1047]
"getPages:" in "GetMaterialApp" throws error "the getter 'page' was called on null" if "home:" is not specified.

**Reproduction code

```dart
return GetMaterialApp(
getPages: [
        GetPage(name: '/confirmInitialMessageScreen', page: () => ConfirmInitialMessageScreen()),
],
// home: MyHomePage(title: 'Flutter Demo Home Page'),)
```

**To Reproduce**
In GetMaterialApp add "getPages:" with some data and comment "home:".
Error is thrown "the getter 'page' was called on null".

**Flutter Version:**
1.22.5

**Getx Version:**
3.24.0

**Describe on which device you found the bug:**
Android emulator

Screenshot of the error:
![20210201](https://user-images.githubusercontent.com/42641096/106401541-f5c71f80-6424-11eb-9cab-ef4d0cd80c14.png)

**Comment by daveMcelf** [comment]
if you comment out `home`, you need to put a `initialRoute` for `GetMaterialApp` to know which page should be built when it first start. 
```
return GetMaterialApp(
      getPages: [
              GetPage(name: '/confirmInitialMessageScreen', page: () => ConfirmInitialMessageScreen()),
              GetPage(name: '/home', page: () => HomePage()),
      ],
      initialRoute: '/home'
)
```

**Comment by jonataslaw** [comment]
@daveMcelf is alright.
You need initialRoute using named routes on lastest release
