### ISSUE TITLE
I wrote a plugin for getx

### ISSUE THREAD

**Issue by CNAD666** [jonataslaw/getx#1049]
Hello，Dear author

I wrote a plugin for getx，I think this plugin can reduce some repetitive work for everyone

Hope you can make some suggestions for this plugin

**plugin**：https://github.com/CNAD666/getx_template

**Comment by jonataslaw** [comment]
Thanks! Nice work and nice post on https://juejin.cn/post/6924104248275763208 
If you want, you can insert the link of your plugin and your article in readme.md-cn through a PR

**Comment by CNAD666** [comment]
> Thanks! Nice work and nice post on https://juejin.cn/post/6924104248275763208
> If you want, you can insert the link of your plugin and your article in readme.md-cn through a PR

I have submitted a PR and hope to pass！
