### ISSUE TITLE
assign complete custom class update not working

### ISSUE THREAD

**Issue by Hwan-seok** [jonataslaw/getx#1050]
**Describe the bug**

The documentation said when we want to update custom class reactively, you should use CUSTOM_CLASS.update(callback)

But it does not work when assign completed instance to `User` on callback 

**Reproduction code**

### It works(update user)
```dart
user.update( (user) { // this parameter is the class itself that you want to update
    user.name = 'Jonny';
    user.age = 18;
});
```

### It does not works(not updates user)
 ```dart
final newUser = User(name: 'Jonny', age: 18);
user.update( (user) { // this parameter is the class itself that you want to update
    user = newUser;
});
```

**Expected behavior**
The user instance update

**Flutter Version:**
1.22.5 stable

**Getx Version:**
3.24.0

**Describe on which device you found the bug:**
Iphone 6 - IOS

**Comment by eduardoflorence** [comment]
To update the instance and not just one of its properties, replace:
```dart
final newUser = User(name: 'Jonny', age: 18);
user.update( (user) { // this parameter is the class itself that you want to update
   user = newUser;
});
```
With:
```dart
final newUser = User(name: 'Jonny', age: 18);
user(newUser);
```

**Comment by Hwan-seok** [comment]
You're right, Thx!
Forgive my ignorance
