### ISSUE TITLE
TickerProviderStateMixin does not compatible in GetxController

### ISSUE THREAD

**Issue by Rohit-ChauhanRC** [jonataslaw/getx#1051]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by daveMcelf** [comment]
i'm not sure if this what you mean but, instead of `TickerProviderStateMixin`, GetX use `SingleGetTickerProviderMixin` that work the same way as `TickerProviderStateMixin`. 
```
class YourController extends GetxController with SingleGetTickerProviderMixin {}
```
Btw, later when you open an issue, please provide more info on your problem so that it's easier to solve the problem

**Comment by Rohit-ChauhanRC** [comment]
Thanks

**Comment by zzterrozz** [comment]
Why is `SingleGetTickerProviderMixin` deprecated? What is the replacement?

**Comment by jabeed-ahmed** [comment]
> Why is `SingleGetTickerProviderMixin` deprecated? What is the replacement?

Used like SingleTickerProviderMixin but only with Get Controllers. Simplifies AnimationController creation inside GetxController.
GetSingleTickerProviderStateMixin Please use this
