### ISSUE TITLE
Generate navigation stack when using nested routes

### ISSUE THREAD

**Issue by JaconsMorais** [jonataslaw/getx#1054]
Hi all.
Could be usefull if Get create the navigation stack when user access one nested route directlly.

Using the docs example, if I create three pages, 'home', 'products' and 'eletronics', like this:
```
GetPage(
      name: '/home',
      page: () => HomeView(),
      binding: HomeBinding(),
      children: [
        GetPage(
            name: '/products',
            page: () => ProductsView(),
            binding: ProductsBinding(),
            children: [
              GetPage(
                 name: '/electronics',
                 page: () => ElectronicsView(),
                 binding: ElectronicsBinding(),
              ),
            ],
          ),
      ], 
  );
```

if the user navigate to '.../home/products/eletronics', the navigation stack will be empty and back button will not be visible, so could be usefull if Get sets the navigation stack, but, without building them. just place on navigation stack so the user can back to parent page.

**Comment by jonataslaw** [comment]
With Navigator 1.0, we have no control over the Stack.
With the migration to Navigator 2.0 on GetX 4 this will be possible

**Comment by JaconsMorais** [comment]
Ok, I will wait for GetX 4.0, thanks.

**Comment by FallenRiteMonk** [comment]
How would this be done in GetX 4? I could not find any documentation
