### ISSUE TITLE
Get.changeTheme feature was deprecated after v1.13.2.

### ISSUE THREAD

**Issue by DarkMarksDoe** [jonataslaw/getx#1060]
**Description**
Deprecated code, changing Theme of app using a floatingActionButton from Scaffold. Only Get.changeTheme shows the error, Get.isDarkMode works fine.

**Reproduction code**
```dart
floatingActionButton: FloatingActionButton(
  child: Icon(Icons.add),
    onPressed: () {
      Get.changeTheme(
        Get.isDarkMode ? ThemeData.light() : ThemeData.dark());
      _.increment();
    },
),
```
**Current Message**
'Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead. See https://flutter.dev/go/remove-fab-accent-theme-dependency. This feature was deprecated after v1.13.2.'

**To Reproduce**
1. Clic the floatingActionButton '...'
2. Clic on Debug Console
3. See error

**Expected behavior**
Some code is deprecated.

**Flutter Version:**
Flutter 1.22.6 ° Chanel Stable

**Getx Version:**
3.24.0

**Describe on which device you found the bug:**
- Moto x4 - Android (8.1.0)
- Android Emulator - Android (9.0)

**Minimal reproduce code**
Checked only on Android devices

**Comment by jonataslaw** [comment]
`'Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead`

Read the warning, it's FloatingActionButton relationed, not GetX.

**Comment by DarkMarksDoe** [comment]
I saw the Issue #146
Thanks for the answer, greeting for Mexico, land of tacos 🌮

**Comment by jonataslaw** [comment]
Sure!
Off: Me encantan los tacos mexicanos, la cocina mexicana es maravillosa.

**Comment by DarkMarksDoe** [comment]
Off: No sabía que hablar español, que interesante, y sí, es una tradición muy grande nuestra comida, y algo de miedo con extranjeros probando comidas picosas
