### ISSUE TITLE
Memory leaks in the mixin NotifyManager.

### ISSUE THREAD

**Issue by damphat** [jonataslaw/getx#1061]
The `NotifyManager` keeps adding more listener.

**And the `_subscriptions` list keeps growing every time the widget rebuilds.**

![image](https://user-images.githubusercontent.com/677382/107153589-ec97fe80-69a0-11eb-9769-655ea8dd6948.png)

**Reproduction code

```dart
void main() => runApp(MaterialApp(home: Home()));

class Home extends StatelessWidget {
  final count = 0.obs;
  @override
  Widget build(context) => Scaffold(
      appBar: AppBar(title: Text("counter")),
      body: Center(
        child: Obx(() => Text("$count")),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => count.value++,
      ));
}
```

**Flutter Version:**
Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5d36f2e7f5 (3 weeks ago) • 2021-01-14 15:57:49 -0800
Engine • revision 7a8f8ca02c
Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)

**Getx Version:**
3.24

**Comment by jonataslaw** [comment]
But that is exactly what should happen. I don't think you understand how a variable subscription works yet.
Subscriptions is the list of items that will be closed and removed from the GetX/Obx/Controller.
Her items will be removed in due course, there is no memory leak here.

**Comment by damphat** [comment]
**When the controller updates million times (like stock app) The UI will be slow down.**

![image](https://user-images.githubusercontent.com/677382/107156371-81eebf00-69b0-11eb-9635-8146261863e3.png)

**Comment by jonataslaw** [comment]
> **When the controller updates million times (like stock app) The UI will be slow down.**
> 
> ![image](https://user-images.githubusercontent.com/677382/107156371-81eebf00-69b0-11eb-9635-8146261863e3.png)

Thanks for point this, it's a bug introduced on 3.16

**Comment by jonataslaw** [comment]
I fix it on https://github.com/jonataslaw/getx/commit/ae0df647c4f7843b587599c7c2702b02cd5d0b6c
