### ISSUE TITLE
Get.backUntil()

### ISSUE THREAD

**Issue by subzero911** [jonataslaw/getx#1071]
Please add some Navigator.PopUntil() analogue. I use it rather often. Say, if we have pages chain like Home->Login->OtpCode->OkScreen, and we want to pop until the Home page (preserving the possible stack behind the home page).
I checked the dedicated navigation https://github.com/jonataslaw/getx/blob/master/documentation/en_US/route_management.md#route-management
and didn't find the same method.
Get.offAll is not the same, it drops all the navigation stack.
Note: PopUntil can be a dangerous operation, because if you pop until the screen which doesn't exist in the stack, it will pop forever and you will fall into "nowhere" (not even into unknownScreen, but into black emptiness). You will probably want to avoid this behaviour.

**Comment by jonataslaw** [comment]
try `Get.until((route) => route.isFirst);`

And it seems that some documentation commit accidentally removed a block of code that mentioned this method, because in version 2 I documented it.
See if it works for you
