### ISSUE TITLE
lazyPut doesn't not work as expected

### ISSUE THREAD

**Issue by subzero911** [jonataslaw/getx#1087]
Look at the following code:
![image](https://user-images.githubusercontent.com/12999702/108332449-dd0a8800-71e0-11eb-93de-112156f5e339.png)
SecondScreenBindings is tied to SecondScreen only.
I enter SecondScreen -- Controller is spawned.
I exit back to FirstScreen -- Controller is disposed.
I enter SecondScreen again -- Controller is spawned again! Why?
I declared `fenix: false` and supposed the Controller should have died forever.

**Comment by jonataslaw** [comment]
You are using Bindings, this is what it does.
fenix: true is only useful when dependency injection is declared in a single file, when injecting a Binding on a route you are saying: I want you to make these dependencies available when I enter that route, and remove them when I leave them. If I enter this route again, make this dependency available again.
