### ISSUE TITLE
JsonSerializable support

### ISSUE THREAD

**Issue by subzero911** [jonataslaw/getx#1090]
Currently JsonSerializable is not supported. It means I have to write tedious serialization code (fromJson and toJson) by myself for every model.
I know you don't like code generation, but it's inevitable. JsonSerializable is the most popular serialization package and it uses code generation.

The following types should be supported:

- All primitive Rx types: RxInt, RxDouble, RxNum, RxBool, RxString, etc.
- Generic Rx<T>
- Collections: RxList, RxMap, RxSet

As a reference, you could took:
https://pub.dev/packages/json_serializable_mobx

**Comment by jonataslaw** [comment]
With VSCode extensions, get_cli, which already generates models with these methods, makes it unnecessary to use this feature, besides the use case being very restricted. I believe that less than 1% of users would use this (this package sent has 4 likes, which shows that even in mobx, that its users are accustomed to generators, it is not popular).
In this way, I am closing this resource request, as there is no interest on my part to implement, if anyone wants to venture into it, they will have my support.

**Comment by subzero911** [comment]
@jonataslaw I examined get_cli and see that it can only generate a model from Json.
How about adding an option for creating fromJson/toJson methods on existing model class (from its fields)?
