### ISSUE TITLE
Question: How to get currently selected translation (Language) in my App?

### ISSUE THREAD

**Issue by rmControls** [jonataslaw/getx#1098]
Hello,

How to get currently active translation or Language in my app using Getx...??

I know we can set Locale like below using Getx... But How do I get the locale which we already set in another page for this app.....
```
var locale = Locale('en', 'US');
Get.updateLocale(locale);
```

I saw that to get device Locale we have to use it... but not sure how to get my active locale set in my app...

```
return GetMaterialApp(
    locale: Get.deviceLocale,
);
```

**Comment by eduardoflorence** [comment]
```dart
Get.locale
```
