### ISSUE TITLE
Controller has been marked as permanent, SmartManagement is not authorized to delete it

### ISSUE THREAD

**Issue by pqtrong17** [jonataslaw/getx#1106]
I have been created `Binding` class:
```
class _Binding extends Bindings {
  @override
  void dependencies() {
    // TODO: implement dependencies
    Get.lazyPut<LoginController>(() => LoginController(), fenix: true);
  }
}
```
then called it:
```
runApp(GetMaterialApp(
      // home: isLogged ? MainHomePage() :IntroPage(),
      home: LoginPage(),     
      initialBinding: _Binding(),
    ));
```
 And when I call `offAll`:
```
Get.offAll(MainHomePage());
```
I get an error:
```
[GETX] "LoginController" has been marked as permanent, SmartManagement is not authorized to delete it.
```

 Please, help me! Tks

**Comment by ghprod** [comment]
Please add reproduce code. Also I think you don't need `fenix` in this case.

**Comment by eduardoflorence** [comment]
Update GetX, this problem has already been resolved in the newest version

**Comment by nemoryoliver** [comment]
> Update GetX, this problem has already been resolved in the newest version

I'm using GetX 3.26.0 but still getting the error as well

**Comment by jonataslaw** [comment]
Update GetX, It's not occurs on last version.
Closing it
