### ISSUE TITLE
Possible getX route bug

### ISSUE THREAD

**Issue by delay** [jonataslaw/getx#1121]
**Describe the bug**
I am trying to make a drawer which a user can changes routes when user selects a new tab. It works the first time I select a tab.  However after I select another tab it doesn't change the route again.  Below is minimum reproducible.  (In the actual app I am passing a GetxController with a tag so it will repopulate the view with the new controller.)

**Reproduction code**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      home: WebUI(),
    );
  }
}

class WebUI extends StatelessWidget {
  WebUI({Key key, this.tab}) : super(key: key);
  final tab;

  @override
  Widget build(BuildContext context) {
    var tabText = 'default';
    if (tab != null) {
      tabText = tab;
    }
    print('from WebUI: ' + tab.toString());
    return Scaffold(
      appBar: AppBar(),
      drawer: Drawer(child: TabsUI()),
      body: Center(
        child: Text(tabText),
      ),
    );
  }
}

class TabsUI extends StatelessWidget {
  final tabs = ["tab 1", "tab 2", "tab 3"];
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
        itemCount: tabs.length,
        itemBuilder: (context, index) {
          final tab = tabs[index];
          return Card(
            child: ListTile(
              onTap: () => {
                print('from TabsUI: ' + tab),
                Get.off(WebUI(tab: tab)),
                Scaffold.of(context).openEndDrawer()
              },
              title: new Text(tab),
            ),
          );
        });
  }
}

```

**To Reproduce**
1.  open drawer
2. click a tab
3. everything works and tab changes view as expected.
4. now click another tab and notice the view does not change.

**Expected behavior**
I expect it to change the view every time I select a new tab in the drawer. 

**Flutter Version:**
1.26.0-17.8.pre
**Getx Version:**
3.25.4

**Describe on which device you found the bug:**
iOS simulator

Is the route being cached by getX? If so, is there a way I can force a refresh?

**Comment by delay** [comment]
I ended up doing this in a different way by just putting everything in the controller and not using routes at all.  So you can close this out but I still think it might be a bug or maybe I misunderstood something...

**Comment by jonataslaw** [comment]
Did you try preventDuplicates: false when navigating to the next page?
If you try to open a current page, GetX blocks opening the route again to prevent accidental clicks (but we will improve the way this is done), disabling preventDuplicates will allow you to go to a route like currenteRoute.

**Comment by eduardoflorence** [comment]
```dart
Get.off(WebUI(tab: tab), preventDuplicates: false)
```
