### ISSUE TITLE
How to clear all value of controllers in GetX

### ISSUE THREAD

**Issue by minhpalmy** [jonataslaw/getx#1139]
I used Getx for state management. And App have feature Logout, I want reset all value of controllers after logout Success. I tried Reset but not ok for my case. Please !

**Comment by ghprod** [comment]
Please use the appropriate channel for such a question :+1: 

Btw it depends on your structure of code. For me, I just need to clear `GetStorage` and call `FirebaseAuth.signOut()`

**Comment by minhpalmy** [comment]
> Please use the appropriate channel for such a question 👍
> 
> Btw it depends on your structure of code. For me, I just need to clear `GetStorage` and call `FirebaseAuth.signOut()`

Thank you so much. I'm newbie. i'm so sorry

**Comment by jonataslaw** [comment]
You can made also
```dart
Get.reload<Controller>();
Get.reloadAll() ;
```
