### ISSUE TITLE
Support null safety | Flutter 2.0 and Dart 2.12 upgrade

### ISSUE THREAD

**Issue by Edorin9** [jonataslaw/getx#1146]
<img width="725" alt="Screen Shot 2021-03-04 at 2 59 09 PM" src="https://user-images.githubusercontent.com/14562922/109923740-305cfa00-7cfa-11eb-8915-e3adce09d147.png">

**Comment by mjablecnik** [comment]
Yes this is an important issue because [provider](https://pub.dev/packages/provider) or [flutter_bloc](https://pub.dev/packages/flutter_bloc) already provide their versions for sound null safety right now..

**Comment by jlubeck** [comment]
There is already an issue for this here: https://github.com/jonataslaw/getx/issues/858
You should probably close this one and follow the other (and give thumbs up over there)
