### ISSUE TITLE
multiple variable are not updated in get: ^3.25.4 , i am using three variables inside Get Builder. first time they are updated , but next time only one variable is update , other 2 are not updated.

### ISSUE THREAD

**Issue by sadaqatkarimi** [jonataslaw/getx#1147]
String a,b,c;

void updateABC(){
a=1;
b=2;
c=3;
update();
}

first time they are updated but next time only one variable is update and other 2 are not updated.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.26.0-17.8.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-PK)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (4 available)

**Comment by ghprod** [comment]
Please post reproduce code

**Comment by sadaqatkarimi** [comment]
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:sales_snap/controllers/home_controller.dart';
import 'package:sales_snap/utils/routes/routes.dart';
import 'package:sales_snap/views/pages/items_details_page.dart';
import 'package:sales_snap/views/widgets/appBar.dart';
import 'package:sales_snap/views/widgets/snakbar.dart';
import 'package:webview_flutter/webview_flutter.dart';

class HomePage extends StatelessWidget {
  final Routes _routes = Routes();

  WebViewController webViewcontroller;
  final formKey = GlobalKey<FormState>();
  final _homeController = Get.put(HomeController());
  @override
  Widget build(BuildContext context) {
    final bodyStyle = Theme.of(context).textTheme.bodyText2;
    final lable = Theme.of(context).textTheme.headline1;
    return GetBuilder<HomeController>(builder: (homecontroller) {
      return Scaffold(
        appBar: appBar(context, 'Sales Snap'),
        body: SingleChildScrollView(
          child: Container(
            padding: EdgeInsets.only(left: 12, right: 12, top: 12),
            child: Stack(
              children: [
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Form(
                          key: formKey,
                          child: Expanded(
                            flex: 5,
                            child: Container(
                              height: 44,
                              child: TextFormField(
                                controller:
                                    homecontroller.textEditingController,
                                validator: (value) {
                                  if (value.isEmpty) {
                                    return 'Url is Empty';
                                  }
                                  return null;
                                },
                                decoration: InputDecoration(
                                  hintText: 'Enter URL of Product',
                                ),
                              ),
                            ),
                          ),
                        ),
                        SizedBox(
                          width: 12,
                        ),
                        MaterialButton(
                          shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  color: Theme.of(context).primaryColor),
                              borderRadius: BorderRadius.circular(22)),
                          height: 40,
                          color: Colors.green,
                          child: Text('Go'),
                          onPressed: () async {
                            FocusScope.of(context).unfocus();
                            if (formKey.currentState.validate()) {
                              homecontroller.fetch();
                            }
                          },
                        )
                      ],
                    ),
                    SizedBox(
                      height: 12,
                    ),
                    homecontroller.enable
                        ? productWidget(homecontroller, lable, context)
                        : getRecentSave(bodyStyle),
                    SizedBox(
                      height: 12,
                    ),
                  ],
                ),
                homecontroller.showProgress
                    ? Positioned(
                        top: 50,
                        left: Get.width / 2 - 50,
                        child: progressBar(),
                      )
                    : SizedBox()
              ],
            ),
          ),
        ),
        floatingActionButton: homecontroller.enable
            ? Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  ElevatedButton.icon(
                    style: ButtonStyle(
                        shape: MaterialStateProperty.all(
                      RoundedRectangleBorder(
                          side:
                              BorderSide(color: Theme.of(context).primaryColor),
                          borderRadius: BorderRadius.circular(22)),
                    )),
                    onPressed: () {
                      homecontroller.saveProduct();
                    },
                    icon: Icon(Icons.save_alt),
                    label: Text("Save"),
                  ),
                  SizedBox(
                    width: 12,
                  ),
                  ElevatedButton.icon(
                    style: ButtonStyle(
                        shape: MaterialStateProperty.all(
                      RoundedRectangleBorder(
                          side:
                              BorderSide(color: Theme.of(context).primaryColor),
                          borderRadius: BorderRadius.circular(22)),
                    )),
                    onPressed: () {
                      if (formKey.currentState.validate())
                        _routes.to(
                            context,
                            ItemDetailsPage(
                              url: homecontroller.textEditingController.text,
                            ));
                    },
                    icon: Icon(Icons.public),
                    label: Text("WebSite"),
                  ),
                ],
              )
            : Container(),
      );
    });
  }

  Column productWidget(
      HomeController homecontroller, TextStyle lable, BuildContext context) {
    return Column(
      children: [
        Column(
          children: homecontroller.imageUrls
              .map(
                (image) => Image.network(image),
              )
              .toList(),
        ),
        SizedBox(
          height: 16,
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            Text(
              homecontroller.price.toString(),
              style: TextStyle(
                fontSize: 24,
              ),
            ),
            SizedBox(
              width: 20,
            ),
          ],
        ),
        SizedBox(
          height: 16,
        ),
        Text(homecontroller.title[0],
            style:
                lable.copyWith(height: 1.5, wordSpacing: 1, letterSpacing: 1)),
        SizedBox(
          height: 16,
        )
      ],
    );
  }

  Widget getRecentSave(TextStyle bodyStyle) {
    // print('------------------');
    //print(_homeController.saveList.length);
    return _homeController.saveList.length == 0
        ? Container(
            padding: EdgeInsets.only(top: 30),
            child: Center(
              child: Text('You have not save any product.'),
            ))
        : Container(
            height: Get.height,
            width: Get.width,
            child: GridView.builder(
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 2,
                  childAspectRatio: 0.85,
                  crossAxisSpacing: 10,
                  mainAxisSpacing: 5),
              itemBuilder: (BuildContext context, int index) {
                return Container(
                  child: Card(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Image.network(
                          _homeController.saveList[index].imgUrl,
                          height: 100,
                        ),
                        SizedBox(
                          height: 6,
                        ),
                        Text(
                          _homeController.saveList[index].title,
                          style: bodyStyle.copyWith(fontSize: 14),
                          maxLines: 2,
                        ),
                        SizedBox(
                          height: 6,
                        ),
                        Text(
                          _homeController.saveList[index].price,
                          style: bodyStyle.copyWith(color: Colors.red),
                        )
                      ],
                    ),
                  ),
                );
              },
              itemCount: _homeController.saveList.length,
            ),
          );
  }
}

// ElevatedButton.icon(
//   onPressed: () {
//     print(" 🚀 debuging at line 106");
//     webViewcontroller.evaluateJavascript('''
//         window.SNAP.postMessage(document.querySelectorAll("*[class*=\'price\']")[0].innerText);
//         window.SNAP.postMessage(document.querySelectorAll(".pdp img")[0].getAttribute('srcset').split('w,')[0]);
//         ''');
//   },
//   icon: Text("🚀 "),
//   label: Text("Load"),
// ),
// Expanded(
//   child: WebView(
//     gestureNavigationEnabled: true,
//     javascriptMode: JavascriptMode.unrestricted,
//     javascriptChannels: [
//       JavascriptChannel(
//           name: 'SNAP',
//           onMessageReceived: (message) {
//             print('-------in snap---------------');
//             print(message.message);
//           })
//     ].toSet(),
//     onPageFinished: (url) {
//       print(" 🚀 debuging at line 106");
//       webViewcontroller.evaluateJavascript(
//           'window.SNAP.postMessage(document.querySelectorAll("*[class*=\'price\']")[0].innerText);');
//     },
//     onWebViewCreated: (WebViewController _webViewController) {
//       webViewcontroller = _webViewController;
//     },
//     initialUrl:
//         'https://shop.lululemon.com/p/mens-jackets-and-outerwear/Expeditionist-Anorak/_/prod10370103?color=0001',
//   ),
// ),

**Comment by sadaqatkarimi** [comment]
import 'dart:async';

import 'package:background_fetch/background_fetch.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:get/get.dart';
import 'package:html/dom.dart';

import 'package:html/parser.dart';
import 'package:sales_snap/controllers/saved_item_controller.dart';
import 'package:sales_snap/models/web_details.dart';
import 'package:http/http.dart' as http;
import 'package:sales_snap/repositories/database_helper.dart';
import 'package:sales_snap/repositories/firestore_methods.dart';
import 'package:sales_snap/utils/extract/extract.dart';

var img =
    'https://cdn.shopify.com/s/files/1/1083/6796/products/product-image-187878776_400x.jpg?v=1569388351';
String url =
    'https://shop.lululemon.com/p/mens-jackets-and-outerwear/Expeditionist-Anorak/_/prod10370103?color=0001';

void backgroundFetchHeadlessTask(HeadlessTask task) async {
  // var taskId = task.taskId;
  final controller = Get.put(HomeController());

  controller.comparePrice();

  // var timeout = task.timeout;
  // HomeController _controller = HomeController();
  // if (timeout) {
  //   BackgroundFetch.finish(taskId);
  //   return;
  // }

  // if (taskId == 'flutter_background_fetch') {
  //   BackgroundFetch.scheduleTask(TaskConfig(
  //       taskId: "com.transistorsoft.customtask",
  //       delay: 5000,
  //       periodic: false,
  //       forceAlarmManager: false,
  //       stopOnTerminate: false,
  //       enableHeadless: true));
  // }
  //BackgroundFetch.finish(taskId);
}

////////////CONTROLLER START/////////////////////////////////////////////////////////////
class HomeController extends GetxController {
  TextEditingController textEditingController;

  FlutterLocalNotificationsPlugin fltrNotification;

  SavedController _savedController = Get.put(SavedController());

  DatabaseHelper _helper = DatabaseHelper();

  FireStoreMethod _fireStoreMethod = FireStoreMethod();

  List<String> imageUrls = [];

  String title = '';

  String price = '';

  static String priceHtmlTag = '';

  bool enable = false;

  bool showProgress = false;

  List<WebDetails> list = [];

  List<WebDetails> saveList = [];

  var doubleRE = RegExp(r"-?(?:\d*\.)?\d+(?:[eE][+-]?\d+)?");

  @override
  void onInit() {
    initNotifications();

    initPlatformState();
    getSavedList();
    BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

    textEditingController = TextEditingController();
    // textEditingController.text = url;
    super.onInit();
  }

  @override
  void onClose() {
    textEditingController.dispose();
    super.onClose();
  }

  void getSavedList() async {
    saveList = await _helper.getWebDetails();

    update();
  }

  void enableValue(bool val) {
    enable = val;

    update();
  }

  void showProgrss(val) {
    showProgress = val;
    update();
  }

  Future<void> fetch() async {
    enableValue(true);
    //showProgrss(true);
    try {
      final response = await http.get(Uri.parse(textEditingController.text));

      if (response.statusCode == 200) {
        Map<String, dynamic> priceMap = {};
        this.refresh();

        title = getTitle(response.body)[0];
        priceMap = getPrice(response.body);
        imageUrls = getImage(response.body);

        price = "${priceMap['currency']} ${priceMap['amount']}";

        showProgrss(false);
      } else {
        snakBar(response.statusCode);
        enableValue(false);
        showProgrss(false);
      }
    } catch (e) {
      snakBar(e);
      enableValue(false);
      showProgrss(false);
      update();
      print('----Error-----');
      print(e.toString());
    }
  }

  saveProduct() {
    if (title.isNotEmpty && price.isNotEmpty ||
        HomeController.priceHtmlTag.isNotEmpty ||
        textEditingController.text.isNotEmpty) {
      showProgrss(true);
      var p =
          doubleRE.allMatches(price).map((m) => double.parse(m[0])).toList();
      WebDetails savedProduct = WebDetails(
          title: title,
          imgUrl: imageUrls[0] ?? img,
          priceHtmlTag: HomeController.priceHtmlTag,
          priceNumber: p.elementAt(0).toString(),
          price: price,
          webUrl: textEditingController.text);

      _fireStoreMethod.saveItems(savedProduct).then((value) {
        _helper.setWebDetails(savedProduct).then((i) {
          _savedController.getSavedList();
          snakBar('Save Sucessfully');
          showProgrss(false);
        });
      });
    } else {
      snakBar('Product Details are Empty');
    }
  }

  deleteProduct(index) {
    _helper.delete(index).then((value) {
      print('----------delete');
      print(value);
      _savedController.getSavedList();
    });
  }

  void snakBar(s) {
    Get.showSnackbar(GetBar(
      message: s,
      duration: Duration(seconds: 3),
    ));
  }

  Future<void> comparePrice() async {
    List<WebDetails> _list = await _helper.getWebDetails();

    _list.forEach((element) async {
      final response = await http.Client().get(Uri.parse(element.webUrl));

      var newPricePareval;
      var oldParseValue;

      String oldPrice = element.priceNumber;

      if (response.statusCode == 200) {
        try {
          Document document = parse(response.body);

          String newPrice =
              document.querySelectorAll(element.priceHtmlTag)[0].toString();
          try {
            if (oldPrice.isNum) {
              oldParseValue = double.parse(oldPrice);
            } else {
              oldParseValue = doubleRE
                  .allMatches(oldPrice)
                  .map((m) => double.parse(m[0]))
                  .toList();
            }
          } catch (e) {
            snakBar(e);
          }

          try {
            if (newPrice.isNum) {
              newPricePareval = double.parse(newPrice);
            } else {
              newPricePareval = doubleRE
                  .allMatches(newPrice)
                  .map((m) => double.parse(m[0]))
                  .toList();
            }
            if (newPricePareval < oldParseValue) {
              _showNotification();
            }
          } catch (e) {
            snakBar(e);
          }
        } catch (e) {
          print('----Error-----');
          print(e.toString());
        }
      }
    });
  }

  void initNotifications() {
    var androidInitilize = AndroidInitializationSettings('ic_launcher');
    var iOSinitilize = IOSInitializationSettings();
    var initilizationsSettings =
        InitializationSettings(android: androidInitilize, iOS: iOSinitilize);
    fltrNotification = FlutterLocalNotificationsPlugin();
    fltrNotification.initialize(
      initilizationsSettings,
    );
  }

  Future _showNotification() async {
    var androidDetails = AndroidNotificationDetails(
        "Channel ID", "Desi programmer", "This is my channel",
        importance: Importance.max);
    var iSODetails = IOSNotificationDetails();
    var generalNotificationDetails =
        NotificationDetails(android: androidDetails, iOS: iSODetails);

    await fltrNotification.show(
        0, "Task", "You created a Task", generalNotificationDetails,
        payload: "Task");
  }

  Future<void> initPlatformState() async {
    // Load persisted fetch events from SharedPreferences

    // Configure BackgroundFetch.
    try {
      int status = await BackgroundFetch.configure(
          BackgroundFetchConfig(
            minimumFetchInterval: 15,
            forceAlarmManager: false,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresStorageNotLow: false,
            requiresDeviceIdle: false,
            requiredNetworkType: NetworkType.NONE,
          ),
          _onBackgroundFetch,
          _onBackgroundFetchTimeout);
      print('=============init cinfig sucess======');

      // Schedule a "one-shot" custom-task in 10000ms.
      // These are fairly reliable on Android (particularly with forceAlarmManager) but not iOS,
      // where device must be powered (and delay will be throttled by the OS).
      BackgroundFetch.scheduleTask(TaskConfig(
          taskId: "com.transistorsoft.customtask",
          delay: 10000,
          periodic: false,
          forceAlarmManager: true,
          stopOnTerminate: false,
          enableHeadless: true));
    } catch (e) {}
  }

  void _onBackgroundFetch(String taskId) async {
    print("111111111111111[BackgroundFetch] Event received: $taskId");
    _showNotification();
    if (taskId == "flutter_background_fetch") {
      _showNotification();
      print('-----------background fetch=-------');
      // Schedule a one-shot task when fetch event received (for testing).
      /*
      BackgroundFetch.scheduleTask(TaskConfig(
          taskId: "com.transistorsoft.customtask",
          delay: 5000,
          periodic: false,
          forceAlarmManager: true,
          stopOnTerminate: false,
          enableHeadless: true,
          requiresNetworkConnectivity: true,
          requiresCharging: true
      ));
       */
    }
    // IMPORTANT:  You must signal completion of your fetch task or the OS can punish your app
    // for taking too long in the background.
    BackgroundFetch.finish(taskId);
  }

  /// This event fires shortly before your task is about to timeout.  You must finish any outstanding work and call BackgroundFetch.finish(taskId).
  void _onBackgroundFetchTimeout(String taskId) {
    print("2222222222222[BackgroundFetch] TIMEOUT: $taskId");
    BackgroundFetch.finish(taskId);
  }

  void _onClickEnable(enabled) {
    if (enabled) {
      BackgroundFetch.start().then((int status) {
        print('bbbbb[BackgroundFetch] start success: $status');
      }).catchError((e) {
        print('bbbbb[BackgroundFetch] start FAILURE: $e');
      });
    } else {
      BackgroundFetch.stop().then((int status) {
        print('bbbbb[BackgroundFetch] stop success: $status');
      });
    }
  }

  // saveToFirestore(WebDetails webDetails) {
  //   _fireStoreMethod.saveItems(webDetails).then((e) {});
  // }

}

// if (url.substring(8, index) == item.webUrl) {
//   print(document.getElementsByClassName('price-1SDQy price')[0].text);
//   String title =
//       document.querySelector('.pdp-title div[itemprop="name"]').text;
//   String price =
//       document.getElementsByClassName('price-1SDQy price')[0].text;

//   print('-------------------');

//   print(price.replaceAll(RegExp('[^0-9]'), ''));

//   updatePage(price: price, title: title, desc: 'desc');

//   int p = int.parse(price.replaceAll(RegExp('[^0-9]'), ''));

//   savedProduct = WebDetails(
//     title: title,
//     priceHtmlTag: price,
//     desc: descR,
//     imgUrl: img,
//     priceNumber: p.toString(),
//     webUrl: url.substring(8, index),
//   );
// // }
//         Document document = parse(response.body);

//         String newPrice =
//             document.querySelectorAll('*[class*="price"]')[0].text;

//         print('-----------new price------------------');
//         print(newPrice);
//         int index = newPrice.indexOf('class="');
//         int lasindex = newPrice.indexOf('\">');
//         String s = newPrice.substring(index, lasindex);
//         print(document.getElementsByClassName(s));

**Comment by sadaqatkarimi** [comment]
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:get/get.dart';
import 'package:universal_html/html.dart' as element;
import 'package:universal_html/parsing.dart';

import 'package:sales_snap/models/web_details.dart';
import 'package:http/http.dart' as http;
import 'package:sales_snap/repositories/database_helper.dart';

class HomeController extends GetxController {
  TextEditingController textEditingController;

  FlutterLocalNotificationsPlugin fltrNotification;

  DatabaseHelper _helper = DatabaseHelper();

  List<String> imageUrls = [];

  String title = '';

  String price = '';

  static String priceHtmlTag = '';

  bool enable = false;

  bool showProgress = false;

  List<WebDetails> saveList;

  @override
  void onInit() {
    getSavedList();

    textEditingController = TextEditingController();

    super.onInit();
  }

  @override
  void onClose() {
    textEditingController.dispose();
    super.onClose();
  }

  void getSavedList() async {
    saveList = await _helper.getWebDetails();

    update();
  }

  void enableValue(bool val) {
    enable = val;

    update();
  }

  void showProgrss(val) {
    showProgress = val;
    update();
  }

  Future<void> fetch() async {
    enableValue(true);
    //showProgrss(true);
    try {
      final response = await http.get(Uri.parse(textEditingController.text));

      if (response.statusCode == 200) {
        Map<String, dynamic> priceMap = {};
        this.refresh();

        title = getTitle(response.body)[0];
        priceMap = getPrice(response.body);
        imageUrls = getImage(response.body);

        price = "${priceMap['currency']} ${priceMap['amount']}";

        showProgrss(false);
      } else {
        snakBar(response.statusCode);
        enableValue(false);
        showProgrss(false);
      }
    } catch (e) {
      snakBar(e);
      enableValue(false);
      showProgrss(false);
      update();
      print('----Error-----');
      print(e.toString());
    }
  }

  void snakBar(s) {
    Get.showSnackbar(GetBar(
      message: s,
      duration: Duration(seconds: 3),
    ));
  }
}

const productAttributeMap = {
  "price": [
    ":price:amount",
    ":price:currency",
    "priceCurrency",
    "product-price",
    "price",
    "product-main ProductPriceBlock__Price",
    "priceblock_dealprice",
    "PriceBlock",
    "current-price",
    "product-price",
    "priceblock",
    "product-price",
    "ProductPrice",
    "PriceBlock",
    "dealprice",
    "__Price",
    "-price",
    "price--",
    "price__",
    "-price",
    "Price",
    "price",
  ],
  "title": [
//meta tag
    ":title",
    "title",
    "description",
    ":description",

/////item prop
    "name",
    "pdp_h1",

    //class
    "product-name",
    "product-description__name",
    "__name",
    "title",
    "Title"
        "item-name",
    "pdp-title",
    "product-name",
    "product_name",
    "produit_title",
    "product__title",
    "font-primary",
    "short-title",
    "page-title",
    "productName_title",
    "productName",
    "BrandTitle",
    "productBrandTitle",
    "pl-Heading",
    "pdp__heading",
    "title--",
    "page-title",
    "pl-Heading",
    "product-single__title",
    "page-title",
    "product-title",
    "product__title",
    "product-page__title",
    "__title",
    "productName_title",
    "product_title",
    "productName_title",
    "productHeading",
    "product-description",
    "pinfo__heading",
    "listing-page-title",
    "lblProductName",
    "lblProduct",
    "productTitle",
    "itemTitle",
    "title",
    "hero-info-title",
  ],
  "image": [
    //meta tag
    ":image:",
    "image_src",
    {"parent": ".ProductImagery", "child": "img"},
    {"parent": ".image", "child": "img"},
    {"parent": ".product-image", "child": "img"},
    {"parent": ".product-gallery", "child": "img"},
    "popup-img",
    "product-image",
    "item active",
    "imgTagWrapper",
    "__image",
    "b-product_images-main_image",
    "swiper-zoom-container",
    "-image",
    "ProductImages-imgLink",
    "pdp-slider",
    "product-image",
    "ProductImage-",
    "product__image"
        "product-image",
    "productImages-",
    "slick-slide",
    "zoomImgMask",
    " ls-is-cached lazyloaded",
    "product-image-zoom",
    "productpage-image",
    "productImageCarousel_image",
    "athenaProductImageCarousel_image",
    "productBrandTitle",
    "js-big-image",
    "product-gallery-image",
    "image-wrapper",
    "s7staticimage",
    "ProductImage",
    "sticker",
    "pl-FluidImage-image",
    "img-wrap",
    "zoomImg",
    "ShotView",
    "product-carousel-image",
    "main-image",
    "productImageCarousel_image",
    "image_item",
    "SGBOXU1_image",

    "slick-slide",
    "slick-slide slick-current slick-active",
    "pimages",
    //id
    "imgProduct",
    "FeaturedImage",
    "imgTagWrapperId",
    "amp-originalImage",
//data-test
    "image",
  ]
};

const filters = [
  "property",
  "class",
  "itemprop",
  "item-prop",
  "id",
  "data-test-element",
  "data-test-id"
];
List<String> dataSet = [];
setData(_data) {
  dataSet.add(_data);
}

Map<String, dynamic> getPrice(String domData) {
  final htmlDocument = parseHtmlDocument(domData);

  productAttributeMap['price'].forEach((attrValue) {
    filters.forEach((filter) {
      // print('[$filter*="$attrValue"]');

      var _data = htmlDocument.querySelectorAll('[$filter*="$attrValue"]');

      _data.forEach((element.Element element) {
        if (filter.contains("prop")) {
          if (element.attributes['content'] != null) {
            if (element.attributes['content'].trim().isNotEmpty) {
              HomeController.priceHtmlTag = '[$filter*="$attrValue"]';
              print(
                  '==Price==========${element.attributes['content'].replaceAll(" ", "")}');
              setData(element.attributes['content'].replaceAll(" ", ""));
            }
          }
        } else if (element.innerText != null) {
          if (element.innerText.trim().isNotEmpty) {
            HomeController.priceHtmlTag = '[$filter*="$attrValue"]';
            print('==Price==========${element.innerText.replaceAll(" ", "")}');
            setData(element.innerText.replaceAll(" ", ""));
          }
        }
      });
    });
  });
  print('=======price lenght===== ${titleSet.length}');
  var currentCurrency = "";
  var s = ["USD", "\$", "£", "PKR"];

  dataSet.forEach((sign) {
    s.forEach((currency) {
      if (currentCurrency.isEmpty) {
        if (sign.contains(currency)) {
          currentCurrency = currency;
        }
      }
    });
  });

  dataSet = dataSet.toSet().toList();
  var newDataSet = [];
  dataSet.forEach((e) {
    if (e != currentCurrency) {
      newDataSet.add(e);
    }
  });

  return {"currency": currentCurrency, "amount": newDataSet[0]};
}

List<String> titleSet = [];
setTitle(_data) {
  titleSet.add(_data);
}

List<String> getTitle(String domData) {
  final htmlDocument = parseHtmlDocument(domData);

  productAttributeMap['title'].forEach((attrValue) {
    filters.forEach((filter) {
      // print('[$filter*="$attrValue"]');

      var _data = htmlDocument.querySelectorAll('[$filter*="$attrValue"]');

      _data.forEach((element.Element element) {
        if (filter.contains("prop")) {
          if (element.attributes['content'] != null) {
            if (element.attributes['content'].trim().isNotEmpty) {
              print(
                  '------Title  data 2-------- ${element.attributes['content'].replaceAll(" ", "")}');
              setTitle(element.attributes['content'].replaceAll(" ", ""));
            }
          }
        } else if (element.innerText != null) {
          if (element.innerText.trim().isNotEmpty) {
            print(
                '------Title data 2-------- ${element.innerText.replaceAll(" ", "")}');
            setTitle(element.innerText.replaceAll(" ", ""));
          }
        }
      });
    });
  });
  print('=======Title lenght===== ${titleSet.length}');
  return titleSet.toSet().toList();
}

List<String> imageSet = [];
setImage(_data) {
  imageSet.add(_data);
}

List<String> getImage(String domData) {
  imageSet = [];
  final htmlDocument = parseHtmlDocument(domData);

  productAttributeMap['image'].forEach((dynamic attrValue) {
    filters.forEach((filter) {
      var _data;
      if (attrValue.runtimeType.toString().contains("Map")) {
        _data = htmlDocument
            .querySelectorAll("${attrValue['parent']} ${attrValue['child']}");
      } else {
        _data = htmlDocument.querySelectorAll('[$filter*="$attrValue"]');

        _data.forEach((element.Element element) {
          if (filter.contains("prop")) {
            if (element.attributes['content'] != null) {
              if (element.attributes['content'].trim().isNotEmpty) {
                String prop = element.attributes['content'].replaceAll(" ", "");

                if (prop.contains('http')) {
                  print('------image up date-------- $prop');
                  setImage(prop);
                }
              }
            }
          } else if (element.innerText != null) {
            if (element.innerText.trim().isNotEmpty) {
              String data = element.innerText.replaceAll(" ", "");

              if (data.contains('http')) {
                print('=======imge data======== $data');
                setImage(data);
              }
            }
          }
        });
      }
    });
  });
  print('=======image lenght===== ${imageSet.length}');

  return imageSet.toSet().toList();
}

**Comment by sadaqatkarimi** [comment]
first time all three variables are updated , but in second execution imgUrl variable is updated but other two variable price and title are not updated

**Comment by sadaqatkarimi** [comment]
packages i used

  cupertino_icons: ^1.0.0
  get: ^3.25.4
  # tesseract_ocr: ^0.3.1
  # receive_sharing_intent: ^1.4.3
  # system_alert_window: ^0.4.2+2
  # native_screenshot: ^0.0.5
  google_fonts: ^1.1.2
  get_storage: ^1.4.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  google_sign_in: ^4.5.9
  webview_flutter: ^1.0.7
  html: ^0.14.0+4
  http: ^0.12.2
  sqflite: ^1.3.2+3
  background_fetch: ^0.7.0
  flutter_local_notifications: ^4.0.1
  universal_html: ^1.2.4
  regexed_validator: ^1.0.4

**Comment by ghprod** [comment]
Hi

Can you post a minimalism reproduce code which we can copy paste to our IDE and run it?

Also please put your code with three backticks to wrap it as code

**Comment by sadaqatkarimi** [comment]
> minimalism reproduce c

ok

**Comment by sadaqatkarimi** [comment]
Hello
i submit the whole minimal code to this repo  https://github.com/sadaqatkarimi/minimal_code 

Please use paste this link https://shop.lululemon.com/p/men-shorts/Interritus-Short/_/prod9960724?color=45421 in text field and click Go button.

then use this link https://shop.lululemon.com/p/mens-jackets-and-outerwear/Expeditionist-Anorak/_/prod10370103?color=0001 in thext field and click Go button price and titl are not updated.

**Comment by ghprod** [comment]
```dart
class ThirdController extends GetxController {
  static ThirdController get to => Get.find();

  int counter = 0;
  int counter2 = 0;

  void increment() {
    counter++;
    counter2++;
    update(); // use update() to update counter variable on UI when increment be called
  }
}

class ThirdScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GetBuilder<ThirdController>(
        init: ThirdController(),
        builder: (_) => Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                '${_.counter}',
              ),
              Text(
                '${_.counter2}',
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          ThirdController.to.increment();
        },
        child: Text('+'),
      ),
    );
  }
}
```

Everything works


https://user-images.githubusercontent.com/1922652/110069171-d87dcc00-7da9-11eb-9d29-b20cbb495ac5.mp4

**Comment by sadaqatkarimi** [comment]
error resolve thank you.
