### ISSUE TITLE
Pages get reinstantiated with current child page arguments on hot reload

### ISSUE THREAD

**Issue by psrcek** [jonataslaw/getx#1153]
**Describe the bug**
When navigating to a sub page and then performing a hot reload all the parent pages get reinstantiated with the arguments of the current page.

**Reproduction code**

<details>
    <summary>Code (click to expand)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'GetX navigation bug',
      home: TestPage1(),
    );
  }
}

abstract class TestPage extends StatelessWidget {
  final int args;

  TestPage() : args = Get.arguments;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('GetX navigation bug'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.skip_next),
        onPressed: next,
      ),
      body: Center(
        child: Text('$args'),
      ),
    );
  }

  void next();
}

class TestPage1 extends TestPage {
  next() {
    Get.to(() => TestPage2(), arguments: 1);
  }
}

class TestPage2 extends TestPage {
  next() {
    Get.to(() => TestPage3(), arguments: 2);
  }
}

class TestPage3 extends TestPage {
  next() {
    Get.to(() => TestPage4(), arguments: 'Now hot reload the app');
  }
}

class TestPage4 extends StatelessWidget {
  final String args;

  TestPage4() : args = Get.arguments;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('GetX navigation bug'),
      ),
      body: Center(
        child: Text('$args'),
      ),
    );
  }
}
```
</details>

**To Reproduce**
1. Click the FAB 3 times
2. **HOT** reload the app (bug does **NOT** happen on full restart)

**Expected behavior**
I expected hot reloads to work with GetX.

**Flutter Version:**
`1.22.5` or `2.0.0`

**Getx Version:**
`3.26.0`

**Describe on which device you found the bug:**
Any device / emulator.

**Comment by ghprod** [comment]
Maybe try splitting each page with own dedicated class instead of extending from abstract

Also your reproduce code thrown error

```
[GETX] GOING TO ROUTE /TestPage3

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'int' is not a subtype of type 'String'

```

**Comment by psrcek** [comment]
The abstraction doesn't matter. Does the same either way. It was just to make the reproduction code smaller.

And yeah, that's my point, that is the error... In no logical way should that ever occur because TestPage3 is only ever navigated to with an int in the arguments. `Get.to(() => TestPage3(), arguments: 2)`

**Comment by psrcek** [comment]
> Also your reproduce code thrown error

Isn't that the point of reproduction code...

**Comment by ghprod** [comment]
> > Also your reproduce code thrown error
> 
> Isn't that the point of reproduction code...

Sorry didn't think that's was the error you mean :+1:

**Comment by Bestfastfire** [comment]
I have passed by something similar, I resolved this issue running app in terminal with the tag `--track-widget-creation`, ex:

`flutter run <platform> --track-widget-creation`

To hot reload is just type `r`

**Comment by psrcek** [comment]
@Bestfastfire The bug still occurs for me when using that launch argument.

**Comment by psrcek** [comment]
That doesn't actually work. Press the back button after hot reloading. You'll see that all the pages get the last data and not their own arguments.

**Comment by eduardoflorence** [comment]
@psrcek I did the solution below.
Working with `Get.arguments` in the view is dangerous due to the way the flutter manages your navigation and the rebuild of widgets. When I pop from page2 to page1, the build of page1 is not performed and the value of Get.arguments is updated by the route where the hot reload was made and not when accessing the page.
In the solution below, I use a controller for each page. This controller inherits from a base controller. The business rule then becomes the controller.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'GetX navigation bug',
      home: TestPage1(),
    );
  }
}

abstract class TestPage extends StatelessWidget {
  final dynamic? args = null;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('GetX navigation bug'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.skip_next),
        onPressed: next,
      ),
      body: Center(
        child: Text('$args'),
      ),
    );
  }

  void next();
}

abstract class ControllerBase extends GetxController {
  final dynamic? args = Get.arguments;
}

class TestPage1 extends TestPage {
  @override
  final dynamic? args = Get.put(Controller1()).args;

  next() {
    Get.to(() => TestPage2(), arguments: 1);
  }
}

class Controller1 extends ControllerBase {}

class TestPage2 extends TestPage {
  @override
  final dynamic? args = Get.put(Controller2()).args;

  next() {
    Get.to(() => TestPage3(), arguments: 2);
  }
}

class Controller2 extends ControllerBase {}

class TestPage3 extends TestPage {
  @override
  final dynamic? args = Get.put(Controller3()).args;

  next() {
    Get.to(() => TestPage4(), arguments: 'Now hot reload the app');
  }
}

class Controller3 extends ControllerBase {}

class TestPage4 extends StatelessWidget {
  final dynamic? args = Get.put(Controller4()).args;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('GetX navigation bug'),
      ),
      body: Center(
        child: Text('$args'),
      ),
    );
  }
}

class Controller4 extends ControllerBase {}
```

**Comment by nemoryoliver** [comment]
> @psrcek I did the solution below.
> Working with `Get.arguments` in the view is dangerous due to the way the flutter manages your navigation and the rebuild of widgets. When I pop from page2 to page1, the build of page1 is not performed and the value of Get.arguments is updated by the route where the hot reload was made and not when accessing the page.
> In the solution below, I use a controller for each page. This controller inherits from a base controller. The business rule then becomes the controller.
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:get/get.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return GetMaterialApp(
>       title: 'GetX navigation bug',
>       home: TestPage1(),
>     );
>   }
> }
> 
> abstract class TestPage extends StatelessWidget {
>   final dynamic? args = null;
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('GetX navigation bug'),
>       ),
>       floatingActionButton: FloatingActionButton(
>         child: Icon(Icons.skip_next),
>         onPressed: next,
>       ),
>       body: Center(
>         child: Text('$args'),
>       ),
>     );
>   }
> 
>   void next();
> }
> 
> abstract class ControllerBase extends GetxController {
>   final dynamic? args = Get.arguments;
> }
> 
> class TestPage1 extends TestPage {
>   @override
>   final dynamic? args = Get.put(Controller1()).args;
> 
>   next() {
>     Get.to(() => TestPage2(), arguments: 1);
>   }
> }
> 
> class Controller1 extends ControllerBase {}
> 
> class TestPage2 extends TestPage {
>   @override
>   final dynamic? args = Get.put(Controller2()).args;
> 
>   next() {
>     Get.to(() => TestPage3(), arguments: 2);
>   }
> }
> 
> class Controller2 extends ControllerBase {}
> 
> class TestPage3 extends TestPage {
>   @override
>   final dynamic? args = Get.put(Controller3()).args;
> 
>   next() {
>     Get.to(() => TestPage4(), arguments: 'Now hot reload the app');
>   }
> }
> 
> class Controller3 extends ControllerBase {}
> 
> class TestPage4 extends StatelessWidget {
>   final dynamic? args = Get.put(Controller4()).args;
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('GetX navigation bug'),
>       ),
>       body: Center(
>         child: Text('$args'),
>       ),
>     );
>   }
> }
> 
> class Controller4 extends ControllerBase {}
> ```

solved for me! always use Get.arguments on the controller. thanks
