### ISSUE TITLE
<T> static error

### ISSUE THREAD

**Issue by rupamking1** [jonataslaw/getx#1155]
<img width="257" alt="Screenshot_1" src="https://user-images.githubusercontent.com/57300218/110139902-8bc1e180-7df9-11eb-9114-8d5df94979ff.png">

error-
Static members can't reference type parameters of the class.
Try removing the reference to the type parameter, or making the member an instance member.dart(type_parameter_referenced_by_static)

Sorry for my previous mistake, please tell me why the warning happens?

**Comment by jonataslaw** [comment]
In dart, generic types cannot be referred to from a getter, change "to" and "go" to to<T>()=> and go<T>()=> and remove the "get" identifier to try to do what you want, just remember that you will have to use controller.to ().
