### ISSUE TITLE
Get.put<T> has it possible to return null ?

### ISSUE THREAD

**Issue by weiwill** [jonataslaw/getx#1156]
`get: ^4.0.0-nullsafety.2`

`final UserController controller = Get.put(UserController())!`

when use `Get.put`, must add "!", Is it possible to omit?

and 

`final Rx<String> title = Rx<String>('Hello Word!');`

I've given the default value, If I want to use title value, must to add "!" or "?", Is it possible to omit?

**Comment by weiwill** [comment]
and `Get.find()` maybe return null 
Why current is `throw '"$S" not found. You need to call "Get.put($S())" or "Get.lazyPut(()=>$S())"';`
If it changes to this, is it better?
`S? find<S>({String? tag}) => GetInstance().find<S>(tag: tag)`  ?

**Comment by jonataslaw** [comment]
Use RxString rather Rx<String> 

If Get.find be nullable, will be mandatory to use "!"

I'll transform put on non nullable

**Comment by weiwill** [comment]
when update nullsafety, `GetInstance().find<S>(tag: tag)` return S? is will it be better for throw exception ?
