### ISSUE TITLE
What's the correct way to deal with navigating to same route

### ISSUE THREAD

**Issue by lvyandev** [jonataslaw/getx#1163]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**

I have a named page called `OrganizationPage` which uses simple Listview to display the organizations founded by organizationId.
Each item may have sub organizations.

It's somehow like `country - province - city - streets` relationships.
So tap on item will open a same page but different id to request data.

However `Get.toNamed<void>(
      Routes.ORGANIZATION,
      preventDuplicates: false,
      arguments: organization.orgId,
    );` will use the same controller as first page, it gets no arguments in sub pages,  and shows nothing different.

And when I close the sub pages and reopen, it complains `"OrganizationController" not found. You need to call "Get.put(OrganizationController())" or "Get.lazyPut(()=>OrganizationController())".
`

Although the error disappears when I set `Get.put(OrganizationController(repository: Get.find()), permanent: true);`.
It is still the same controller in every sub page.

What should I do?
**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
static final routes = [
    GetPage(
      name: Routes.ORGANIZATION,
      page: () => HomeView(),
      binding: OrganizationBindings(),
    ),
  ];

// --------------------Bindings-----------------------//
class OrganizationBindings extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<IOrganizationProvider>(() => OrganizationProvider());
    Get.lazyPut<IOrganizationRepository>(
        () => OrganizationRepository(provider: Get.find()));
    Get.lazyPut(() => OrganizationController(repository: Get.find()));
  }
}

// --------------------Controller-----------------------//
class OrganizationController extends GetxController {
  OrganizationController({this.repository});

  final IOrganizationRepository repository;

  RxList<OrganizationBean> organizations = <OrganizationBean>[].obs;

  int orgId = 0;

  @override
  Future<void> onInit() async {
    super.onInit();

    final dynamic arguments = Get.arguments;

    if (ObjectUtils.isNotEmpty(arguments)) {
      orgId = arguments as int;
    }
    
    final List<OrganizationBean> list =
        await repository.getOrganizations(orgId);

    organizations.assignAll(list);
  }

  void onNextLevelTap(OrganizationBean organization) {
    Get.toNamed<void>(
      Routes.ORGANIZATION,
      preventDuplicates: false,
      arguments: organization.orgId,
    );
  }
```

**Expected behavior**

**Screenshots**

**Flutter Version:**
Flutter version 1.22.6

**Getx Version:**
get: ^3.25.6

**Describe on which device you found the bug:**
ex: Moto z2 - Android.

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by eduardoflorence** [comment]
Use `Get.create` instead of `Get.lazyPut`;

**Comment by lvyandev** [comment]
It is strange after use `Get.create`.
The instances created with no stop only if I stop using `RxList<OrganizationBean> organizations = <OrganizationBean>[].obs;`

**Comment by lvyandev** [comment]
I changed 
`RxList<OrganizationBean> organizations = <OrganizationBean>[].obs;` 
to 
`StateMixin<List<OrganizationBean>>`

Now the page is working properly, Thank you very much for your help 😁
