### ISSUE TITLE
Error GetConnect addRequestModifier

### ISSUE THREAD

**Issue by msgridin** [jonataslaw/getx#1168]
**Describe the bug**
Couldn't infer type parameter 'T'. Tried to infer 'Object?' for 'T' which doesn't work: Parameter 'interceptor' declared as 'FutureOr<Request<T>> Function(Request<T?>)' but argument is 'Request<Object?> Function(Request<Object?>)'. Consider passing explicit type argument(s) to the generic.

**Reproduction code**
```dart
import 'package:get/get.dart';

class HomeProvider extends GetConnect {
  @override
  void onInit() {
    // It's will attach 'apikey' property on header from all requests
    httpClient.addRequestModifier((request) {
      request.headers['apikey'] = '12345678';
      return request;
    });
  }
}
```

**To Reproduce**
1. run the demo

**Expected behavior**
There should be no error.

**Screenshots**
<img width="886" alt="Screenshot 2021-03-09 at 10 15 56" src="https://user-images.githubusercontent.com/42412433/110439713-73cfb380-80c0-11eb-91c2-e48d4ecfea83.png">

**Flutter Version:**
Flutter 2.0.1 • channel stable

**Getx Version:**
4.0.0-nullsafety.0

**Describe on which device you found the bug:**
All devices

**Comment by djade007** [comment]
Try to add the type to the request variable
httpClient.addRequestModifier((**Request** request) async {
     // Your code here
}

**Comment by khuntia** [comment]
> httpClient.addRequestModifier((**Request** request) async {

Hi @jonataslaw Please update the documentation of getx in pub dev,  changing it to this or the other solution. It will help others not do this mistake, thanks!! and great job :) !!

**Comment by jacsdev** [comment]
hey guys!!! i want to say thanks to all the team of getx!!! it's an amazing tool!! i just love it
