### ISSUE TITLE
[Get] the improper use of a GetX has been detected. I have this error, but not have this situation.

### ISSUE THREAD

**Issue by Bes79** [jonataslaw/getx#1175]
Full text error:
  [Get] the improper use of a GetX has been detected. 
main.dart.js?v=1.1.16:5271       You should only use GetX or Obx for the specific widget that will be updated.
main.dart.js?v=1.1.16:5271       If you are seeing this error, you probably did not insert any observable variables into GetX/Obx 
main.dart.js?v=1.1.16:5271       or insert them outside the scope that GetX considers suitable for an update 
main.dart.js?v=1.1.16:5271       (example: GetX => HeavyWidget => variableObservable).
main.dart.js?v=1.1.16:5271       If you need to update a parent widget and a child widget, wrap each one in an Obx/GetX.

Is any way to debug this error? And detect - in that Obx component this error?

**Comment by jonataslaw** [comment]
The error provides the exact line where you are using Obx / Getx in a wrong or unnecessary way.
If you're looking for help, join our community channels, github is designed to describe bugs and feature requests.
