### ISSUE TITLE
Make the RxList value nullable

### ISSUE THREAD

**Issue by psrcek** [jonataslaw/getx#1179]
**Describe the bug**
`RxList`'s value cannot be set to null in the latest version because of null safety. Is this supposed to be the case? What is the alternative other than keeping track of the state yourself? Keep in mind there are cases where `[]` could mean something completely different than `null`.

**Reproduction code**

Previously you could do:

```dart
final l = RxList<T>();
l.value = null;
```

And now that isn't possible because the RxList class has no nil() method and the data type is `List` and not `List?`.

**Expected behavior**
I would expect my old code to be migratable to a null safe equivalent.

**Flutter Version:**
`2.0.1`

**Getx Version:**
`4.0.0-nullsafety.2`

**Describe on which device you found the bug:**
Device independant.

**Comment by psrcek** [comment]
While migrating to null safety I realized that this applies to all Rx types like `RxInt` and `RxBool` etc. Are `Rx<List<T>>` and `Rx<int?>` etc. the correct replacements?

**Comment by jonataslaw** [comment]
List, Map and set nullable: `RxList<T?>` `RxMap<T?, S?> ` `RxSet<T?>`
Other nullables:
Rx<bool?>, Rx<String?>, Rx<int?>, Rx<CustomClass?>
