### ISSUE TITLE
Controller not disposed when calling Get.toNamed()

### ISSUE THREAD

**Issue by Ley87** [jonataslaw/getx#1181]
**Describe the bug**
Hi, I recently found out that there is probably a bug when switching to a new page.
The Controller is not disposed after calling "Get.toNamed()".

Possible duplicate of #1157? But here it is with id.

And also possible duplicate of  #831? But here with GetView and Bindings.

**Reproduction code**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(
    initialRoute: '/page1',
    getPages: [
      GetPage(
        name: '/page1',
        page: () => Page1(),
      ),
      GetPage(
        name: '/page2',
        page: () => Page2(),
      ),
    ],
  ));
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Get.put(Page1Controller());
    return Material(
      child: Center(
        child: RaisedButton(
          onPressed: () => Get.toNamed('/page2'),
          child: Text('Page2'),
        ),
      ),
    );
  }
}

class Page1Controller extends GetxController {}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Get.put(Page2Controller());
    return Material(
      child: Center(
        child: RaisedButton(
          onPressed: () => Get.toNamed('/page1'),
          child: Text('Page1'),
        ),
      ),
    );
  }
}

class Page2Controller extends GetxController {}
```

**Current behavior**
[GETX] Instance "Page1Controller" has been created
[GETX] Instance "Page1Controller" has been initialized
[GETX] GOING TO ROUTE /page2
[GETX] Instance "Page2Controller" has been created
[GETX] Instance "Page2Controller" has been initialized

**Expected behavior**
[GETX] Instance "Page1Controller" has been created
[GETX] Instance "Page1Controller" has been initialized
[GETX] "Page1Controller" onDelete() called
[GETX] "Page1Controller" deleted from memory
[GETX] GOING TO ROUTE /page2
[GETX] Instance "Page2Controller" has been created
[GETX] Instance "Page2Controller" has been initialized

**Flutter Version:**
1.22.6

**Getx Version:**
3.26.0

**Describe on which device you found the bug:**
Huawei P20 Pro - Android 10

**Comment by wangxinnong** [comment]
Why do you expect Controller1 to be disposed?
Controller is bond to the related route, it will get disposed when the route popped.

In your case  /page2 is `pushed` upon /page1, Controller1 won't be disposed because /page1 is still there.
When you pop /page2, Page2Controller will be disposed.
If you replace /page1 with /page2 by calling `Get.offNamed`, Page1Controller will be disposed.

**Comment by Ley87** [comment]
@wangxinnong Thank you very much for clarification. 
Looks like there was a misunderstanding from my side how routes are working.
