### ISSUE TITLE
check if a GetX Contrtoller has put before or not

### ISSUE THREAD

**Issue by Bunny1376** [jonataslaw/getx#1182]
hi thank you for this great package!
I need some thing like this:
if(SamlpeContrtollrer put before)
find it
else
put it

**Comment by jonataslaw** [comment]
Get.putOrFind();  made this
You too can to use: Get.isRegistered<Controller>() or Get.prepared<Controller>() (for lazy dependencys) to check if the dependency is registered or prepared. 

Since this is a question and has been answered, I am closing this.

**Comment by Bunny1376** [comment]
I want to access this condition : SamlpeContrtollrer put before

**Comment by aktxyz** [comment]
I love putOrFind() ... but would love it even more if it were findOrPut() !!!

mainly because it tries to find, and if not present, then puts

**Comment by bh1270** [comment]
> 
Get.isRegistered by tag
 is always false,why???

**Comment by kennenfromchina** [comment]
> > 
> 
> Get.isRegistered by tag is always false,why???

same issue
