### ISSUE TITLE
Calling update() in GetxController with GetResponsiveView doesn't change anything

### ISSUE THREAD

**Issue by Andreigr0** [jonataslaw/getx#1184]
Is it on purpose or is it a bug? I mean do I have to use a `GetBuilder`/`Getx`/`MixinBuilder` wrapper in order to update the state like so:
<details>
<summary>Example</summary>

```dart
GetPage(
      name: '/posts/:id',
      page: () => PostDetailsPage(),
      binding: PostDetailsBinding(),
)

class PostDetailsBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(
      () => PostDetailsPageController(repository: Get.find()),
      tag: Get.parameters['id'],
    );
  }
}

class PostDetailsPageController extends GetxController with StateMixin {
  final PostsRepository repository;

  PostDetailsPageController({required this.repository});

  Rx<PostModel?> post = Rx();

  @override
  Future<void> onInit() async {
    super.onInit();
    await load();
  }

  Future<void> load() async {
    final params = Get.parameters;
    change(null, status: RxStatus.loading());
    await 500.milliseconds.delay();
    post = await repository.getDetails(int.parse(params['id'] ?? '1'));
    change(null, status: RxStatus.success());
    update();
  }
}

class PostDetailsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<PostDetailsPageController>(
      builder: (_) => _PostDetailsPage(),
      tag: Get.parameters['id'],
    );
  }
}

class _PostDetailsPage extends GetResponsiveView<PostDetailsPageController> {
  @override
  bool get alwaysUseBuilder => false;

  @override
  String? get tag => Get.parameters['id'];

  PostModel? get post => controller.post.value;

  @override
  Widget? phone() {
    return Scaffold(
      appBar: AppBar(
        title: Text('Post #${post?.id}'),
      ),
      body: controller.obx(
        (state) => Column(
          children: [
            if (post != null) ...[
              Text(post!.title),
            ],
            if (post?.description != null) Text(post!.description!),
            ElevatedButton(
              onPressed: () {
                logger.d('Controller post ${post?.id}');
                controller.update();
              },
              child: Text('Update'),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget? tablet() {
    return Scaffold(
      appBar: AppBar(
        title: Text('Tablet post #${post?.id}'),
      ),
      body: controller.obx(
        (state) => Column(
          children: [
            Text('loaded on tablet'),
            ElevatedButton(
              onPressed: () {
                controller.load();
                logger.d('Update ${post?.id}');
                controller.update();
              },
              child: Text('Load'),
            ),
             ElevatedButton(
              onPressed: () {
                logger.d('Update ${post?.id++}');
                controller.update();
              },
              child: Text('Increment'),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget? desktop() {
    return Scaffold(
      appBar: AppBar(
        title: Text('Desktop post #${post?.id}'),
      ),
      body: controller.obx((state) => Text('Loaded on Desktop')),
    );
  }
}
```

</details>

`flutter: 2.0.1 stable`
`get: ^4.0.0-nullsafety.2`

**Comment by jonataslaw** [comment]
```dart
 @override
  Future<void> onInit() async {
    super.onInit();
    await load();
  }
```
onInit cannot be a Future.

```dart
controller.load();
logger.d('Update ${post?.id}');
controller.update();
```

You MUST NOT update a state from the view.

```dart
 Future<void> load() async {
    final params = Get.parameters;
    change(null, status: RxStatus.loading());
    await 500.milliseconds.delay();
    post = await repository.getDetails(int.parse(params['id'] ?? '1'));
    change(null, status: RxStatus.success());
    update();
  }
```

change and update doesn't make any sense.

**Comment by Andreigr0** [comment]
> onInit cannot be a Future.

Hmm for some reason it always worked🤔

> You MUST NOT update a state from the view

What do you mean? I should not call `update()` such as:

```dart
// Controller
void increment() {
    post.value?.id++;
    update();
  }

// View
ElevatedButton(
  onPressed: controller.increment,
  child: Text('Increment'),
)
```
> change and update doesn't make any sense.

`change()` updates state because it uses another widget under the hood, but if I try to use the same code but without `GetBuilder` id remains `null` in `AppBar`

**Comment by eduardoflorence** [comment]
**Replace:** 
```dart
change(null, status: RxStatus.success());
update();
```
**With:**
```dart
change(post, status: RxStatus.success());
```

**Comment by Andreigr0** [comment]
@eduardoflorence `increment()` won't work this way anyway
I expected to see updates without using `controller.obx((state) => SomeWidget())` because it's just the same builder, but it doesn't update anything else. So I thought of is it necessary to wrap `GetResponsiveView` with `GetxBuilder` or not

P.S. I realised that I haven't provide some classes because they seemed to me too obvious. Or maybe I should share complete project source code?

**Comment by jonataslaw** [comment]
> > onInit cannot be a Future.
> 
> Hmm for some reason it always worked🤔

Yes, it works, but you are changing the type of an inherited method which means that your project will break at one time or another, or onInit can be called after the build if the dart understands that this is a Future.microtask. You are going through a dangerous zone, I would not do that.

> 
> > You MUST NOT update a state from the view
> 
> What do you mean? I should not call `update()` such as:
> 
> ```dart
> // Controller
> void increment() {
>     post.value?.id++;
>     update();
>   }
> 
> // View
> ElevatedButton(
>   onPressed: controller.increment,
>   child: Text('Increment'),
> )
> ```
> 

Yeah, it's the right way


> > change and update doesn't make any sense.
> 
> `change()` updates state because it uses another widget under the hood, but if I try to use the same code but without `GetBuilder` id remains `null` in `AppBar`


Okay, I'm going to try your clearer now.
You have only one controller, you are triggering two simultaneous build events. As the dart event loop works, it is not possible to build between one line and another of the same instruction. If you used reactive programming, that would not be a problem, but in the mechanical update, you are responsible for calling rebuild at the correct time.
I would recommend you to change GetBuilder for controller.obx (contrary to what you are doing) or use Obx/.obs in the variable you want to change. If you really want to work the way you are working, you should schedule an update() after the controller.obx build, something like:

change (null, status: RxStatus.success());
SchedulerBinding.instance.addPostFrameCallback ((_) => update ());

But it's very hacky
Note that you are looking to practically reconstruct an entire screen 2 times, I would tell you to completely rethink what you are doing, and if you want to continue with GetBuilder, use at least 2 controllers for what you intend to do.

**Comment by Andreigr0** [comment]
> You are going through a dangerous zone, I would not do that.

And if I move those exact lines to `Future<void> onReady()` instead of `void onInit()`, would it be correct?

 
> I would recommend you to change GetBuilder for controller.obx (contrary to what you are doing) or use Obx/.obs in the variable you want to change

So I should either put `Scaffold` in `controller.obx` like so
```dart
controller.obx(
  (state) => Scaffold(
    appBar: AppBar(
      title: Text('Tablet post #${post?.id}'),
    ),
    body: Column(
      children: [
        Text('loaded on tablet'),
        ElevatedButton(
          onPressed: () {
            controller.load();
            logger.d('Update ${post?.id}');
            controller.update();
          },
          child: Text('Load'),
        ),
        ElevatedButton(
          onPressed: controller.increment,
          child: Text('Increment'),
        ),
      ],
    ),
  ),
);
```

or wrap `GetResponsiveView` as I used, but do not use `controller.obx` in it, right?
