### ISSUE TITLE
GetSocket has no way to set Headers

### ISSUE THREAD

**Issue by khuntia** [jonataslaw/getx#1186]
Under the basewebsocket, for getsocket, we only have provision to pass the url of the socket,
not additional headers. This makes it restrictive as I cant pass authentication headers or other oauth 
headers when connecting to the backend. Please add provision for passing headers as well

//this is how it is right now
socket = WebSocket(url); 

//Rather we do WebSocket(url, Map headers)

**Comment by jonataslaw** [comment]
GetConnect is multiplatform, it is not possible to set headers on the web, I do not know if we should provide this only for the desktop, but we can do this, so I am moving this to discussions
