### ISSUE TITLE
Expected a value of type 'bool?', but got one of type 'RxBool'

### ISSUE THREAD

**Issue by spacekestrel** [jonataslaw/getx#1187]
Most basic test example
```
class TestController extends GetxController {
  dynamic testBool = true.obs;
  test() {
    testBool = false;
    update();
  }
}
```
```
class TestPage extends StatelessWidget {
  const TestPage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
      final TestController controler = Get.put(TestController());
    return Container(
    child: Obx(()=> controler.testBool ? Text('true'): Text('false')),
    );
  }
}
```

**Comment by jonataslaw** [comment]
It looks like you're still a little confused about state management.
First, there is no reason to use `update()`, if you are using .obs, read the documentation again to understand the difference between the two methods.
Second, you are trying to insert an object into the property of a bool, which is obviously going to give an error. You should use `testBool.isTrue` to obtain the bool.
As this is not a valid issue, I am closing.

**Comment by spacekestrel** [comment]
Thanks for clarification, but to be onest, it's hard to find that info in the docs. They seems to be sufficient, but i feel like it's lacking some crucial information.

**Comment by joerush18** [comment]
How can i use this statement ? is there anything we can listen to a bool variable.
dynamic isAuth = true.obs;
