### ISSUE TITLE
How to Show image after using camera using getx flutter?

### ISSUE THREAD

**Issue by xp664221812** [jonataslaw/getx#1191]
`class SetAvatarLogic extends GetxController {
final state = SetAvatarState();

 Rx<File> selectedFile;

  RxString path = "assets/tab_session_pressed.png".obs;

Future getImage(bool isTakingPhoto) async {
Navigator.pop(Get.context);
var image = await ImagePicker.pickImage(
source: isTakingPhoto ? ImageSource.camera : ImageSource.gallery);
if (image != null) {
selectedFile = File(image.path).obs;
}
return image;
}
}

class SetAvatarPageextends StatelessWidget {
final SetAvatarLogic logic = Get.put(SetAvatarLogic());
..........
//it does't update the image after I select the picture,please help me!!!!
child:Obx(() {
                    return Image(
                        image: logic.selectedFile == null
                            ? AssetImage(logic.path.value)
                            : FileImage(logic.selectedFile.value));
                  }),
..........

**Comment by mattermoran** [comment]
you should not assign a new value to selectedFile but rather to `.value` on it. Should do something like this:
```dart
class SetAvatarLogic extends GetxController {
  final state = SetAvatarState();
  
  final selectedFile = Rx<File>(); // CHANGE HERE
  
  RxString path = "assets/tab_session_pressed.png".obs;
  
  Future getImage(bool isTakingPhoto) async {
    Navigator.pop(Get.context);
    var image = await ImagePicker.pickImage(source: isTakingPhoto ? ImageSource.camera : ImageSource.gallery);
    if (image != null) {
      selectedFile.value = File(image.path); // CHANGE HERE
    }
    return image;
  }
}
```

**Comment by jonataslaw** [comment]
@mattermoran is right.
I don't know if I've documented this yet, but the use of reactive endings for variables could prevent common mistakes like this
