### ISSUE TITLE
unable to get dependency when used in `compute` function provided by flutter

### ISSUE THREAD

**Issue by yeliulee** [jonataslaw/getx#1196]
## Description

I've injected some dependencies(controllers, services and etc) before running the app.
But it crashed with the below error:
(assuming that the dependency is "SettingService" and it has been injected)
```log
flutter: "SettingService" not found. You need to call "Get.put(SettingService())" or "Get.lazyPut(()=>SettingService())
```

## Reproduction code

example:

```dart
class SomeService extends GetxService {
  String demoField = "this is a demo";
  // ...etc
}

void main() {
  // inject dependency
  Get.put<SomeService>(SomeService());
  // this is not the point , ignore that.
  runApp(GetMaterialApp(
    initialRoute: '/home',
    getPages: [
      GetPage(name: '/home', page: () => Container()),
    ],
  ));
}

// demo func running in compute
Future<void> deleteUser(int uid) {
   var service = Get.find<SomeService>();

  // etc ...
}

// it will throw error when running in compute
await compute(deleteUser, 121231);
```

It always got crashed whenever i find dependency in those functions running in the `compute`

## Question

Is the Getx Dependency Injection not compitable with `compute` ? 
or is there a plan to support it ?

**Comment by jonataslaw** [comment]
Isolates cannot access anything other than the arguments sent to him. Not even global or static variables are shared by isolates, so neither get, nor any injection of dependencies, or even dart code written by you will work that way. Send the data you need by arguments, this is the only way to do this.

**Comment by yeliulee** [comment]
thanks, i'll close it

**Comment by jonataslaw** [comment]
ok

**Comment by zl910627** [comment]
hi @jonataslaw 
`compute` has an argument named `message`, but I still can't send any instance of `GetxController` / `GetxService` via on that.
Please take a look below.
I am using
* Getx 3
* Flutter 1.26

![image](https://user-images.githubusercontent.com/53897531/116216903-b423e780-a77b-11eb-83d5-cd52579f294f.png)
![image](https://user-images.githubusercontent.com/53897531/116217057-df0e3b80-a77b-11eb-8cce-9607483ea60d.png)

**Comment by zl910627** [comment]
I don't know why this issues happen.
How could `compute` decide `GetxService` to be closure?

**Comment by sulthanalihsan** [comment]
halo sorry for comment to this closed issue, but i'm still curious about how you handle this case @yeliulee ?, what did you do to solve this case? can you explain shortly? thankyou very much
