### ISSUE TITLE
Using Get.create() leads to an error when trying to call Get.find()

### ISSUE THREAD

**Issue by ProfesorUA** [jonataslaw/getx#1197]
On version get 4.0.0-nullsafety.2 when I'm trying to use Get.find I'm getting the following error: 
```
The following _CastError was thrown building Obx(dirty, state: _ObxState#d32ed):
type '_InternalFinalCallback<void>' is not a subtype of type 'Function' in type cast

The relevant error-causing widget was: 
  Obx file:///Users/olegpryshlyak/getx_cast_test/lib/main.dart:50:13
When the exception was thrown, this was the stack: 
#0      GetInstance._startController (package:get/get_instance/src/get_instance.dart:292:56)
#1      GetInstance._initDependencies (package:get/get_instance/src/get_instance.dart:239:11)
#2      GetInstance.find (package:get/get_instance/src/get_instance.dart:327:17)
#3      GetView.controller (package:get/get_state_manager/src/simple/get_view.dart:38:37)
#4      MyHomePage.build.<anonymous closure> (package:getx_cast_test/main.dart:52:20)
...
```
But the same code works fine when I'm using get 3.26.0 version.

Sample project: 
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class AppBindings extends Bindings {
  @override
  void dependencies() {
    Get.create(() => Controller());
  }
}

class Controller extends GetxController {
  final RxInt counter = 0.obs;
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      getPages: [
        GetPage(name: 'home', page: () => MyHomePage(), binding: AppBindings()),
      ],
      initialRoute: 'home',
    );
  }
}

class MyHomePage extends StatelessWidget {
  final Controller controller = Get.find();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("test"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Obx(
              () => Text(
                '${controller.counter.value}',
                style: Theme.of(context).textTheme.headline4,
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          controller.counter.value += 1;
          print(controller.counter.value);
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by andoutica** [comment]
I got same issue here.
`/// Internal callback that starts the cycle of this controller.
  **final onDelete = _InternalFinalCallback<void>();**`

`
  /// Initializes the controller
  S? _startController<S>({String? tag}) {
    final key = _getKey(S, tag);
    final i = _singl[key]!.getDependency() as S?;
    if (i is GetLifeCycleBase) {
      i.onStart();
      if (tag == null) {
        Get.log('Instance "$S" has been initialized');
      } else {
        Get.log('Instance "$S" with tag "$tag" has been initialized');
      }
      if (!_singl[key]!.isSingleton!) {
        _routesByCreate[Get.reference] ??= HashSet<Function>();
        _routesByCreate[Get.reference]!.add(**i.onDelete as Function**);
      }
    }
    return i;
  }`

onDelete is a  _InternalFinalCallback type  and it cannot cast to Function

**Comment by andoutica** [comment]
any updates for this issue? or I have to back to version 3.26.0 and run with no-sound-null-safety :(

**Comment by jonataslaw** [comment]
Change 

```dart
class MyHomePage extends StatelessWidget {
  final Controller controller = Get.find();
```

to 

```
class MyHomePage extends GetWidget<Controller> {
 // final Controller controller = Get.find(); take it out
```

**Comment by sysint64** [comment]
You also could use `Get.put` instead of `Get.create`

**Comment by wirelessjeano** [comment]
I was having the same issue as originally reported by @ProfesorUA. I have just upgrade from 4.0.0-nullsafety.2 to 4.1.1. 

I am now getting the following error:

`══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown building PlatformsTable(dirty):
Expected a value of type 'DynamicTableController', but got one of type 'Null'

The relevant error-causing widget was:
  PlatformsTable
  file:///Users/x/Projects/widget/widget_ui/lib/common/app/widget_app.dart:30:51

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 84:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 442:10  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart 635:14     as_C
packages/get/get_state_manager/src/simple/get_view.dart 56:46                     get controller
packages/widget_ui/controls/dynamic_table/views/dynamic_table.dart 19:16          new
packages/widget_ui/pages/platforms/views/platforms_table.dart 35:12               build
packages/get/get_state_manager/src/simple/get_view.dart 103:12                    build
packages/get/get_state_manager/src/simple/get_widget_cache.dart 29:27             build
packages/flutter/src/widgets/framework.dart 4495:15                               performRebuild
packages/get/get_state_manager/src/simple/get_widget_cache.dart 35:11             performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                                rebuild
packages/flutter/src/widgets/framework.dart 4474:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                                mount
packages/get/get_state_manager/src/simple/get_widget_cache.dart 25:11             mount
packages/flutter/src/widgets/framework.dart 3541:13                               inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                               updateChild
packages/flutter/src/widgets/framework.dart 4520:16                               performRebuild
` 
My code:

`
class DynamicTableBinding implements Bindings {
  @override
  void dependencies() {
    Get.put<DynamicTableService>(DynamicTableService());
    
    Get.create(()=>DynamicTableController());
  }
}
`

`
class DynamicTable extends GetWidget<DynamicTableController> {
`

I need to use Get.create for my specific use case.

**Comment by andoutica** [comment]
> Change
> 
> ```dart
> class MyHomePage extends StatelessWidget {
>   final Controller controller = Get.find();
> ```
> 
> to
> 
> ```dart
> class MyHomePage extends GetWidget<Controller> {
>  // final Controller controller = Get.find(); take it out
> ```

That's exactly what I implemented, but the issue was about cast '_InternalFinalCallback' to 'Function' property

**Comment by andoutica** [comment]
I just updated to Getx v4.0.0, as I can see you fixed this issues, 
I think we can close this issue now. 
<img width="614" alt="Screen Shot 2021-03-28 at 10 18 12 PM" src="https://user-images.githubusercontent.com/7821844/112757349-b4618380-9013-11eb-80a9-3b50df448912.png">
