### ISSUE TITLE
FullLifeCycleController have no didChangeMetrics, how can i know when the window size is changed

### ISSUE THREAD

**Issue by songzhen0207** [jonataslaw/getx#1201]
![image](https://user-images.githubusercontent.com/41300322/111401685-b6b70a00-8704-11eb-8e84-283e83235426.png)

**Comment by jonataslaw** [comment]
```dart
class Foo extends FullLifeCycleController{
  @override
    void didChangeMetrics() {
      // TODO: implement didChangeMetrics
      super.didChangeMetrics();
    }
}
```

I tested it and the code works perfectly.
You will know that it will be there when you learn object inheritance.

Since this is an issue without describing a bug or a feature request, I am closing this.
