### ISSUE TITLE
Back from sub page

### ISSUE THREAD

**Issue by anchao-lu** [jonataslaw/getx#1205]
When returning from Subpage, there is always a mask flash. Is it configurable, or is it a bug

https://user-images.githubusercontent.com/54097292/111445337-47faa080-8746-11eb-9ac1-13a7d9b4b093.mov

**Comment by jonataslaw** [comment]
I couldn't understand your question, could it be a little clearer?

**Comment by Katekko** [comment]
> I couldn't understand your question, could it be a little clearer?

I guess he is trying to say every time he back from any subpage the page blink for a moment, because its rendering. I guess he needs to change the animation from navigation

**Comment by anchao-lu** [comment]
> > I couldn't understand your question, could it be a little clearer?
> 
> I guess he is trying to say every time he back from any subpage the page blink for a moment, because its rendering. I guess he needs to change the animation from navigation

Yep. But this is the example of this package, no changes have been made. just run the example, then I got this blink

**Comment by Katekko** [comment]
> > > I couldn't understand your question, could it be a little clearer?
> > 
> > 
> > I guess he is trying to say every time he back from any subpage the page blink for a moment, because its rendering. I guess he needs to change the animation from navigation
> 
> Yep. But this is the example of this package, no changes have been made. just run the example, then I got this blink

Try to change the animation of navigation to fade

**Comment by anchao-lu** [comment]
> > > > I couldn't understand your question, could it be a little clearer?
> > > 
> > > 
> > > I guess he is trying to say every time he back from any subpage the page blink for a moment, because its rendering. I guess he needs to change the animation from navigation
> > 
> > 
> > Yep. But this is the example of this package, no changes have been made. just run the example, then I got this blink
> 
> Try to change the animation of navigation to fade you will see that stop blink, because this "blink" is normal, depends how your screen is structure and which animation you are using

Thank you.!
I set the defaultTransition property, then the "blink" stopped.
```dart
@override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      enableLog: true,
      defaultTransition: Transition.rightToLeftWithFade,
      logWriterCallback: Logger.write,
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
      locale: TranslationService.locale,
      fallbackLocale: TranslationService.fallbackLocale,
      translations: TranslationService(),
    );
  }
```
However, I think the default transition should look like the default for each platform. Otherwise, it's a bit of a hassle to set the defaultTransition specifically in order to achieve the platform default.

And, sorry for poor English

**Comment by jonataslaw** [comment]
This is the normal effect, caused by the blur that remains active in the last frame of the transition.
