### ISSUE TITLE
Fail to use the ever work

### ISSUE THREAD

**Issue by Katekko** [jonataslaw/getx#1207]
The argument type 'RxString' can't be assigned to the parameter type 'RxInterface<String>'.
But when you use other type like int, don't appear any error.

![image](https://user-images.githubusercontent.com/13632735/111522950-85a4fc80-8739-11eb-81d0-2af10c7969db.png)
![image](https://user-images.githubusercontent.com/13632735/111523004-9190be80-8739-11eb-9933-a172124e5eaf.png)

You can reproduce with this piece of code:
```Dart
  test('ever', () async {
    final count = ''.obs;
    var result = '';
    ever<String>(count, (value) {
      result = value;
    });
    count.value = '1';
    expect('1', result);
  });
```

Get version: `get: ^4.0.0-nullsafety.2`

Flutter doctor:
```Shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by jonataslaw** [comment]
Fixed on https://github.com/jonataslaw/getx/commit/3c1a1206e0999c218f42c1d3ec67f7d18b4d0c90
