### ISSUE TITLE
"PeopleController" not found. You need to call "Get.put(PeopleController())" or "Get.lazyPut(()=>PeopleController())"

### ISSUE THREAD

**Issue by lzdtech** [jonataslaw/getx#1208]
Using the bottom navigation bar, the page calls the value in getxcontroller to report an error

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following message was thrown building PeopleView(dirty):
"PeopleController" not found. You need to call "Get.put(PeopleController())" or "Get.lazyPut(()=>PeopleController())"

The relevant error-causing widget was: 
  PeopleView file:///E:/AndroidStudioProjects/clsgoat/lib/app/modules/nav/controllers/nav_controller.dart:25:5
When the exception was thrown, this was the stack: 
#0      GetInstance.find (package:get/get_instance/src/get_instance.dart:338:7)
#1      GetView.controller (package:get/get_state_manager/src/simple/get_view.dart:38:37)
#2      PeopleView.build (package:clsgoat/app/modules/people/views/people_view.dart:17:11)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4701:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 6 of 908 libraries in 331ms.

**Comment by sheriffyusuf** [comment]
Please share the controller and the files that make use of the controller. That way we can help you.
