### ISSUE TITLE
DISPOSE PAGE WHEN CALLING NEW ROUTE

### ISSUE THREAD

**Issue by lucasolivierx1** [jonataslaw/getx#1210]
Hello!!

I'm have a little problem, i have a dashboard web, and i'm using 
`get: ^4.0.0-nullsafety.2`

i have some pages with CRUD, and i have the structure: 

on Left, Navigation panel, with all pages of my application. The nav panel always show to user in every screen.

when i go to eg.: Category page, i load all categories using GetX how?

OnInit > loadCategories()

but when i go to other page using `Get.toNamed('/otherRoute')` the CategoryController dont dispose. 

because this my Categories list dont refresh because OnInit dont trigger again.

to solve this issue, i implements on RoutingCallBack on GetMaterialApp, 

``    return GetMaterialApp(

        debugShowCheckedModeBanner: false,

        initialRoute: WebRoutes.kHome,

        defaultTransition: Transition.noTransition,

        theme: ThemeData(

          unselectedWidgetColor: Colors.white,

          accentColor: config!.theme!.colorPrimary,

          accentColorBrightness: Brightness.light,
        ),

        getPages: WebRoutes.pages,

        routingCallback: (routing) {

          if (routing!.current == WebRoutes.kCategories) {

            Get.delete<CategoriesPresenter>();

          }

        });
``

but this is not clean, sounds a work around.

request: 

Can GetX dispose prior route when calling Get.toNamed? or is there another way to resolve this? 

Eg of screen and log print  attached: 
![DASHEXEMPLE](https://user-images.githubusercontent.com/61213009/111626192-79b64a80-87cc-11eb-97ef-41462a753fa3.png)

![log](https://user-images.githubusercontent.com/61213009/111626204-7d49d180-87cc-11eb-9f64-91452b983537.png)

Thks so much!

**Comment by moreirawebmaster** [comment]
Também tenho o mesmo problema, preciso executar o onInit  ou onReady novamente.

**Comment by jonataslaw** [comment]
Call Get.toNamed isn't dispose your controller, but Get.offNamed so.
