### ISSUE TITLE
Controller not found but defined in bindings

### ISSUE THREAD

**Issue by thomasthiebaud** [jonataslaw/getx#1215]
I'm trying to use bindings with this minimal example but I can't get it work

```
GetMaterialApp(
  initialBinding: RootBindings(),
  home: RootView(),
)


class RootBindings extends Bindings {
  @override
  void dependencies() {
    Get.put(FirebaseService().init());
    Get.put(AuthController());
    Get.put(RootController());
  }
}

class RootController extends GetxController {
  static RootController get to => Get.find();
}

class RootView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<RootController>(
      builder: (controller) {
        final user = AuthController.to.user;
        print(user);
        return Container();
      },
    );
  }
}
```

but I get this error 

```
"AuthController" not found. You need to call "Get.put(AuthController())" or "Get.lazyPut(()=>AuthController())"
```

My understanding of bindings is that `AuthController` should be injected and accessible in my `RootView`. Is it possible to have multiple controllers in the bindings?
I guess I'm doing something wrong, but I can't find it

**Comment by sheriffyusuf** [comment]
Please can you share the content of your AuthController file.

**Comment by sheriffyusuf** [comment]
I recreated this scenario on a project. But didn't get any problem. I think all you needed to do was a hot restart.

**Comment by thomasthiebaud** [comment]
It seems that your right, I'll close that issue
