### ISSUE TITLE
Init some public Controllers

### ISSUE THREAD

**Issue by anggaaryas** [jonataslaw/getx#1225]
**Is your feature request related to a problem? Please describe.**
This idea is usefull when you want to initial some public controller in `GetMaterialApp`. Althought you can init manually before call `runapp()` . but it look not nice.

**Describe the solution you'd like**
Maybe we can use `Controllers: ` parameter inside `GetMaterialApp` .  for example:
`
GetMaterialApp(
     controllers: [
          CartController(),
          SomethingController()
     ],
     home: HomeScreen(),
);
`

**Comment by ghprod** [comment]
You can use `initialBinding` for that :+1:

**Comment by anggaaryas** [comment]
is `initialBinding` have other function than init controllers? why the name is "binding" , not "controller"?

**Comment by ghprod** [comment]
Basically, you can put all initial dependency with this, Ex controller or service, etc.
