### ISSUE TITLE
Variável no GetService não muda o estado globalmente!

### ISSUE THREAD

**Issue by astrO1** [jonataslaw/getx#1226]
Primeiramente obrigado por esse package incrível. Voltando ao problema não sei se estou fazendo da maneira correta mais pela lógica que estou tentando utilizar acredito que era para funcionar.

Possuo uma tela de produto aonde o carrinho é uma Widget e o Conteúdo da mesma é uma outra Widget o problema é que no meu carrinho existe um número de quantidade de itens no mesmo, quando eu adiciono o produto que eu quero gostaria que houve uma alteração de estado e muda-se a quantidade de itens para a nova quantidade.

Os valores do meu carrinho eu criei um GetService chamado CartService para poder acessar globalmente os dados do meu carrinho, segue a classe:

```
class CartService extends GetxService  {

  final cartItems = new CartItems().obs;

  addToCartItems(Cart cart) {
    cartItems.value.carts.add(cart);
    cartItems.value.totalQty += cart.quantity;
    cartItems.value.totalValue += cart.total;
    cartItems.value.userId = userRepo.currentUser.value.id;
  }

  addCart(Cart cart) async {
    addToCartItems(cart);
    SharedPreferences prefs = await SharedPreferences.getInstance();
    final cartItemsTemp = cartItems.toJson();
    final cartEncoded = json.encode(cartItemsTemp);
    await prefs.setString('cartItems', cartEncoded);
  }

}
```

Se vocês perceberam meu cartItems é um Rx e na minha Widget que é o carrinho eu possuo este campo aqui 
```

          Container(
            child: Obx (() => Text(
              _con.cartService.cartItems.value.totalQty.toInt().toString(),
              textAlign: TextAlign.center,
              style: Theme.of(context).textTheme.caption.merge(
                    TextStyle(color: Theme.of(context).primaryColor, fontSize: 9),
                  ),
            ),),
            padding: EdgeInsets.all(0),
            decoration: BoxDecoration(color: this.labelColor, borderRadius: BorderRadius.all(Radius.circular(10))),
            constraints: BoxConstraints(minWidth: 15, maxWidth: 15, minHeight: 15, maxHeight: 15),
          ),
```

Essa variavel _con é meu controller criado com o GetController:
```

class CartController extends GetxController {

  CartService cartService = Get.put(CartService());

  RxString testeObx = "30".obs;

  List<Cart> carts = <Cart>[];
  double taxAmount = 0.0;
  int cartCount = 0;
  double subTotal = 0.0;
  double total = 0.0;
  OverlayEntry loader;
  GlobalKey<ScaffoldState> scaffoldKey;

  dynamic location = "Retirada";

  CartController() {
    this.scaffoldKey = new GlobalKey<ScaffoldState>();
    new Timer(const Duration(milliseconds: 10000), () async {
        testeObx.value = cartService.cartItems.value.totalQty.toInt().toString();
    });
    // loader = Helper.overlayLoader(context);
  }
```
 
Existe a classe do FoodController que por ela eu adiciono o produto ao carrinho, chamando o método:

```
  addToCartItems(Cart cart) {
    cartItems.value.carts.add(cart);
    cartItems.value.totalQty += cart.quantity;
    cartItems.value.totalValue += cart.total;
    cartItems.value.userId = userRepo.currentUser.value.id;
  }
```

Porque não muda o estado? Já que o GetService é global eu estou correto? Uma solução que eu pensei foi usar um rxDart com um subject e enviar um evento para forçar a mudança na variavel em um outro Widget, seria essa forma a solução?

**Comment by jonataslaw** [comment]
Você está mudando uma variável não observável dentro de um objeto, portanto, não tem como o estado mudar. 
Veja a documentação sobre classes reativas. Um fix rápido para seu problema seria adicionar no final do metodo que você usa: `cartItems.refresh(),` ou usar ` cartItems.update((newDarItems){ // alterar seu objeto aqui})`;
