### ISSUE TITLE
get null data on refresh the flutter web

### ISSUE THREAD

**Issue by jayeshindianic** [jonataslaw/getx#1230]
`Get.arguments`
is working fine in mobile device but when i run that project in flutter web first time is working fine, but when i reload the page Get.argument is giving null data. 

example:
` Get.offNamed('/home', arguments: [userData, isFreshInfo]);`

```dart
 @override
  void onInit() {
 List<dynamic> data = Get.arguments;
 userData.value = data[0];
if (data[1] == false) {
      updateData();
    }
 super.onInit();
  }
```

Version of Get
`get: ^3.26.0`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (1 available)
```

• No issues found!

![Screenshot 2021-03-23 at 5 04 14 PM](https://user-images.githubusercontent.com/79701614/112140406-f9dc1600-8bf9-11eb-9ee0-285034938000.png)

**Comment by jonataslaw** [comment]
Flutter web has not hot reload, only hot restart, so it's the expected behaviour

**Comment by keremcankabadayi** [comment]
Any workaround of this? @jonataslaw
