### ISSUE TITLE
Get.width not give the current width size in flutter web .

### ISSUE THREAD

**Issue by SamerOrfali** [jonataslaw/getx#1231]
**Describe the bug**

Get.width not give the current width size in flutter web but MediaQuery.of(context).size.widrg Working

**Expected behavior**

Fix it please we don't want to use context !

**Flutter Version:**

Flutter 2.0.3

**Getx Version:**

get: ^3.26.0

**Describe on which device you found the bug:**

flutter web

**Comment by jonataslaw** [comment]
Duplicate of https://github.com/jonataslaw/getx/issues/786#issuecomment-725856139 (look at Eduardo's comment)
