### ISSUE TITLE
Getx 4.0 Null-safety Problem

### ISSUE THREAD

**Issue by knnkrt** [jonataslaw/getx#1238]
The problem is when using .obs, requestModel.value can't be used without ! operator. If I don't, I can use it without ! operator. And if I use .obs and use ! operator, it's giving an error like this.

![image](https://user-images.githubusercontent.com/32898380/112674028-7d09a000-8e76-11eb-87c9-c57578ea15eb.png)
![image](https://user-images.githubusercontent.com/32898380/112674342-da9dec80-8e76-11eb-8546-0d0bd55bcd48.png)
![image](https://user-images.githubusercontent.com/32898380/112674536-1a64d400-8e77-11eb-9119-f14c07f0cc5c.png)
![image](https://user-images.githubusercontent.com/32898380/112675470-403ea880-8e78-11eb-8672-0bb7836128cb.png)

value property is always causing a problem.

EDIT!!!

For RxBool;

Removing ? from <bool?> solving the problem.

![image](https://user-images.githubusercontent.com/32898380/112676679-c7405080-8e79-11eb-85b7-db440c83a572.png)

For Rx;

Removing ? from <T?> solving the problem.

![image](https://user-images.githubusercontent.com/32898380/112676751-e0490180-8e79-11eb-96d4-8bc0b72af6bd.png)

**Comment by jonataslaw** [comment]
Use Getx stable 4.0

**Comment by knnkrt** [comment]
> Use Getx stable 4.0

it's Getx 4.0.3. It was no problem with pre-release.

**Comment by knnkrt** [comment]
Solved with Getx 4.1.1 thank you. But Rx's "isTrue" is still problem. isFalse is working.

**Comment by jonataslaw** [comment]
The code presented does not match the stable version, and I tested it and there is no problem with isTrue, therefore, closing it.
