### ISSUE TITLE
OnInit não executa sempre

### ISSUE THREAD

**Issue by astrO1** [jonataslaw/getx#1248]
Antes estava usando o StatefulWrapper anteriormente ao conhece essa lib e para funções que gostaria de usar assim que a página fosse acessada era o initState() que executava todas as vezes.

Quando eu utilizo o seu life cycle, mas o onInit() que no caso iria substituir ele não executa sempre, eu tive que criar uma Statefull ao invés da Stateless só para usar o initState.

Está faltando algo?

**Comment by jonataslaw** [comment]
onInit não é o mesmo que initState. 
onInit é chamado quando o controlador é inserido na memória. Se você usar outro GetBuilder com o mesmo controller, ele não irá ser disparado.
Procure os canais da comunidade (telegram e Discord sempre tem muitos usuários ativos) para tirar suas dúvidas. O github é para apenas descrição de bugs ou feature request.
