### ISSUE TITLE
[GetConnect] Unhandled Exception: Bad state: Stream has already been listened to

### ISSUE THREAD

**Issue by rakeshlanjewar** [jonataslaw/getx#1260]
The issue is same as #930.

I have Migrated the whole app from dio to getConnect but the file upload part is throwing the error,
I have tried to investigate it. But not able to find the issue and.

Also this is the show stopper for many users.

**Flutter Version:**
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

**Getx Version:**
  get: ^4.1.1

**Describe on which device you found the bug:**
ex: Android emulator (android version 11) x86 arm

**Minimal reproduce code**
1) First i tried this, same issue

```dart
FormData formdata = FormData({
      'order_id': order.id,
      'trip_id': currentTripId,
      'credit_note': jsonEncode(order.creditNoteList),
      'delivery_img': order.image == null
          ? null
          : MultipartFile(File(order.image).readAsBytesSync(),
              filename: "delivery_img"),
       'sign_img': order.signature == null
          ? null
           : MultipartFile(File(order.signature).readAsBytesSync(),
               filename:"sign_img"),
    });
```

2) Also tried this 

```dart
    FormData formdata = FormData({
      'order_id': order.id,
      'trip_id': currentTripId,
      'credit_note': jsonEncode(order.creditNoteList),
    });

    if (order.image != null) {
      File orderImage = File(order.image);
      formdata.files.add(MapEntry('delivery_img',
          MultipartFile(orderImage.readAsBytesSync(), filename: basename(orderImage.path))));
    }

    if (order.signature != null) {
      File orderImage = File(order.signature);
      formdata.files.add(MapEntry('sign_img',
          MultipartFile(orderImage.readAsBytesSync(), filename: basename(orderImage.path))));
    }

   Response response = await remoteService.orderComplete(formdata);
```

and the ordercomplete method looks like this.

```dart
 Future<Response> orderComplete(FormData formdata) async {
    return await post(
      ApiEndPoints.orderComplete,
      formdata,
    );
  }

```

**Comment by saravananmnm** [comment]
@rakeshlanjewar try this approach.

` Future<String?> awsImageUpload(
      String? orderId, String? statusId, File? file) async {
    var image = MultipartFile(file!.readAsBytesSync(),
        filename:
            '${orderId}_${(statusId == StringConstant.POD) ? 'POD' : 'POB'}_${DateFormat('dd-MM-yyyy').format(DateTime.now())}.png');
    var data = FormData({'file': image});
    if (!Get.isRegistered<ApiProvider>()) {
      Get.lazyPut(() => ApiProvider());
    }
    var res =
        await Get.find<ApiProvider>().imageUploadV2(orderId, statusId, data);
    if (res.hasError) {
      if (res.statusCode == 401) {
        var data = await exceptionHandler!.getAuthenticationToken();
        print(res.toString());
      }
    }
    return (res.body);
  }`
