### ISSUE TITLE
Migration to 4.1.2 : Get.Connect / httpClient.addRequestModifier

### ISSUE THREAD

**Issue by buffalus** [jonataslaw/getx#1276]
Hi,

Before migration to 4.12, I have no problem to use the following code:

```dart
class ProductProvider extends GetConnect {
  @override
  void onInit() {
    httpClient.baseUrl = BASEURL; //  BASEURL from helper.dart
    httpClient.maxAuthRetries = 3;

    httpClient.addRequestModifier((request) async {
      final box = GetStorage();
      final token = await box.read('token');
      token != null ? request.headers['Authorization'] = 'Bearer ' + token : Get.toNamed("/login");
      return request;
    });
  }
......
}
```
After migration, Flutter Analyzer show error as below:

Tried to infer 'Object?' for 'T' which doesn't work:
  Parameter 'interceptor' declared as     'FutureOr<Request<T>> Function(Request<T?>)'
                          but argument is 'Request<Object?> Function(Request<Object?>)'.

Consider passing explicit type argument(s) to the generic.

Please help to solve the bug. Thanks!

**Comment by eduardoflorence** [comment]
Do this:
`httpClient.addRequestModifier<void>((request) async {`

**Comment by buffalus** [comment]
> Do this:
> `httpClient.addRequestModifier<void>((request) async {`

Your suggestion works !
Thanks a lot !!!
