### ISSUE TITLE
Rxn,ever user filed,When set to null, however, there is no callback, and OBX is not triggered. The documentation says that the nil method is undefined

### ISSUE THREAD

**Issue by zhangruiyu** [jonataslaw/getx#1285]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
Rxn,ever user filed,When set to null, however, there is no callback, and OBX is not triggered. The documentation says that the nil method is undefined

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
  static Rxn<LocalUser?> user = Rxn<LocalUser?>();

  static init() {
    var localUser = _getLoginModel();
    user(localUser);
    ever(user, (LocalUser? updateUser) {
      _saveLoginModel(updateUser);
    });
  }
  
  static void logout() {
    // user(null);
    user.nil();
  }
```

**To Reproduce**
1. call logout()

**Expected behavior**
ever not callback

**Flutter Version:**
flutter 2.0.3

**Getx Version:**
get: ^4.1.3

**Describe on which device you found the bug:**
all

**Comment by eduardoflorence** [comment]
Hi @zhangruiyu,
Replace:
`user.nil();` 
with:
`user.trigger(null);`

**Comment by zhangruiyu** [comment]
> Hi @zhangruiyu,
> Replace:
> `user.nil();`
> with:
> `user.trigger(null);`

Wow, thank you very much

**Comment by mrnusa** [comment]
Hi, 

and what about with RxList? 
"The method 'trigger' isn't defined for the type 'RxList'."

thanks
