### ISSUE TITLE
GetMaterialApp Global font style issue on real device 

### ISSUE THREAD

**Issue by amrelgendy0** [jonataslaw/getx#1291]
GetMaterialApp(
       locale: Locale('ar'),
      theme: ThemeData(fontFamily: 'Somar'), //bug is here
      getPages: AppPages.routes,
    ),
when i test my project on real ios device i found the font style is back to default and i make flutter clean and clean xcode and change font but the same bug when i downgrade get to ver to  get 4.1.1 the problem solved

**Comment by eduardoflorence** [comment]
Hi @amrelgendy0, try:
```
GetMaterialApp(
  locale: Locale('ar'),
  theme: ThemeData(fontFamily: 'Somar'),
  darkTheme: ThemeData(fontFamily: 'Somar')
  getPages: AppPages.routes,
),
```
