### ISSUE TITLE
Controller transfer problem

### ISSUE THREAD

**Issue by is-idea** [jonataslaw/getx#1297]
![image](https://user-images.githubusercontent.com/33053444/113845016-a5bf5d00-97c7-11eb-93c0-ce3ff8e4b920.png)
![image](https://user-images.githubusercontent.com/33053444/113845063-b1ab1f00-97c7-11eb-917f-19b3c6c3b838.png)

As shown.I try to take out the count in controller2 and assign it to the controller.but in the end there is no effect, and there is no error message.

If I want to achieve such an effect, what should I do?

**Comment by eduardoflorence** [comment]
Try:
`controller.count.value = controller2.count.value;`

**Comment by is-idea** [comment]
> 尝试：
> `controller.count.value = controller2.count.value;`

Thank you very much, this solved my problem
