### ISSUE TITLE
Just like `GetBuilderState` and `GetxController`, what's the name convention?

### ISSUE THREAD

**Issue by ColorFuzzy** [jonataslaw/getx#1300]
I wonder why
- Why not just use `GetMmm` or `GetxMmm` name format?
- Is there some name conventions?

Thanks very much!

**Comment by jonataslaw** [comment]
the "x" refers to resources that support the observable paradigm.

GetBuilder = you need the update()
GetX = You don't need it.

Get.toNamed = is navigation, there is nothing observable.

GetxController = can be used for both.

GetView = not observable
GetWidget = not observable.

RxInt = observable int
