### ISSUE TITLE
How to declare observable variable where there is no default constructor in class? 

### ISSUE THREAD

**Issue by MPVIRANIDEVELOPER** [jonataslaw/getx#1313]
I am declaring an observable variable for class Offerings and Package, which belongs from the purchase_flutter package and did not contain the default constructor, so how can I assign ".obs " please someone help.

**Comment by eduardoflorence** [comment]
final offerings = Rx<Offerings>();

**Comment by MPVIRANIDEVELOPER** [comment]
The issue is because of the null safety version of this package because my project is not compatible with null safety so I migrate to null safety and the problem is solved.
