### ISSUE TITLE
Null check operator used on a null value 

### ISSUE THREAD

**Issue by SdxCoder** [jonataslaw/getx#1314]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
The bug appears when trying to use Get for opening BottomSheet, snacker etc. This happens when
auto_route package is used for route_management. For that we need to wrap the top most `GetMaterialApp()` with `GetMaterialApp.router()`. And then we can pass `Get.key` in routerDelegate. When this is done, on opening BottomSheet, Get throws error 
```
Unhandled Exception: Null check operator used on a null value
```
 
This is because framework is unable to find the `Get.key`.

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
 return GetMaterialApp.router(
      routerDelegate: appRouter
          .delegate(navigatorKey: Get.key, initialRoutes: [SplashViewRoute()]),
      routeInformationParser: appRouter.defaultRouteParser(),
      smartManagement: SmartManagement.full,
      enableLog: true,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme(),
    );
```

**To Reproduce**
1. Use `auto_route` https://pub.dev/packages/auto_route  package and do the initial setup for that.
2. Pass `Get.key` in router delegate as show in code below
```
 return GetMaterialApp.router(
      routerDelegate: appRouter
          .delegate(navigatorKey: Get.key, initialRoutes: [SplashViewRoute()]),
```
3. Now open bottom sheet with Get
```
Get.bottomSheet(Container(height:100));
```
4. And see debug log.

**Expected behavior**
It should open bottom sheet without exception `Null check operator used on a null value`

**Screenshots**

**Flutter Version:**
```
Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale
    en-PK)
```

**Getx Version:**
```
get: ^4.1.4
```

**Describe on which device you found the bug:**
 Honor 9x lite

**Minimal reproduce code**

Import library auto_route
```
auto_route: ^1.0.2
auto_route_generator: ^1.0.2
build_runner: ^1.12.2
```
Then create a file `router.dart`
```
@MaterialAutoRouter(
  routes: <AutoRoute>[
    AutoRoute(page: SplashView, initial: true),
    AutoRoute(page: LoginView),
  ],
)
class $AppRouter {}

final appRouter = AppRouter();
```

Then run, to generate route
```
flutter packages pub run build_runner build
```

Then in `main.dart`
```
void main() => runApp(MaterialApp(home: Home()));

 return GetMaterialApp.router(
      routerDelegate: appRouter
          .delegate(navigatorKey: Get.key, initialRoutes: [SplashViewRoute()]),
      routeInformationParser: appRouter.defaultRouteParser(),
      smartManagement: SmartManagement.full,
      enableLog: true,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme(),
    );
```

Then, make a single button and try to open bottom sheet with get
```
 RaisedButtonCustom(
                btnText: "Open Bottom sheet",
                onPressed: () {
            
                  Get.bottomSheet(Container(height:100));
                },
              )
```

**Comment by sqrg** [comment]
Where you able to find a fix?

**Comment by SdxCoder** [comment]
Nops.

**Comment by diipak-singh** [comment]
Facing the same issue, App is crashing and the dart console says "Null check operator used on a null value" in GetMaterialApp()

GetMaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          primarySwatch: Colors.blue,
          //accentColor: Colors.grey,
          textTheme: GoogleFonts.muliTextTheme(
            Theme.of(context).textTheme,
          ),
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: HomeScreen(),
      )

**Comment by sqrg** [comment]
In my case, the problem was that I was not adding the navigatorKey to the MaterialApp.

```navigatorKey: StackedService.navigatorKey,```

```
MaterialApp(
          title: 'Example Project',
          theme: theme,
          darkTheme: darkTheme,
          themeMode: themeMode,
          navigatorKey: StackedService.navigatorKey,
          onGenerateRoute: StackedRouter().onGenerateRoute,
          initialRoute: 'home',
        ),
```

**Comment by hktom** [comment]
I was facing the same problem, I have solved that by adding a GlobalKey in my GetMaterialApp.
 return GetMaterialApp(
                theme: lightTheme(),
                initialRoute: '/',
                getPages: pages(),
                key:  _scaffoldkey,
              );

**Comment by TFSThiagoBR98** [comment]
If you are using AutoRouter you can use:

```dart
return GetMaterialApp.router(
  onReady: () {
    Get.rootController.key = _appRouter.navigatorKey;
  },
  routerDelegate: _appRouter.delegate(),
  routeInformationParser: _appRouter.defaultRouteParser(),
  ...
);
```

**Comment by SdxCoder** [comment]
> If you are using AutoRouter you can use:
> 
> ```dart
> return GetMaterialApp.router(
>   onReady: () {
>     Get.rootController.key = _appRouter.navigatorKey;
>   },
>   routerDelegate: _appRouter.delegate(),
>   routeInformationParser: _appRouter.defaultRouteParser(),
>   ...
> );
> ```
> 
> Edit: You can also do: `final _appRouter = AppRouter(Get.key);`

Finally, thanks a lot this is the solution which works folks.
