### ISSUE TITLE
controller.update() makes Get.argument equals null

### ISSUE THREAD

**Issue by Drolegc** [jonataslaw/getx#1324]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
When I pass an argument to another page (SecondPage extends GetView) I can read it with Get.arguments['post_id'], but when I make controller.update(), it makes Get.arguments to null, and then I get an error. 

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```
class FirstPage extends Stateless {

  Widget build(BuildContext context){
  return Scaffold( 
    body: Center(
      child:FlatButton(
        child:Text("Go to second"),
        onPressed:(){ 
          Get.toNamed("/second",arguments:{"post_id":1})
          }
      )
    )
  )
  }
}

class SecondPage extends GetView<PostController> {

  Widget build(BuildContext context){
    return Scaffold(
    	body: Center(
          child: FlatButton(
            child:Text("${Get.arguments['post_id']}"),
            onPressed:(){
            	controller.update();
            }
        )
    )
}
```

**To Reproduce**
1. Go to SecondPage
2. Click on the flat button 

**Expected behavior**
A null error

**Getx Version:**
3.15

**Comment by tonyhart7** [comment]
yeah its happen when you hot reload too
Get.argument is return null

**Comment by jonataslaw** [comment]
Get.arguments need be on onInit/inisState and be stored a variable
