### ISSUE TITLE
Refused to set unsafe header "user-agent" When using GetConnect on the web

### ISSUE THREAD

**Issue by omzer** [jonataslaw/getx#1329]
**Bug description**
An error is printed on the web console per each request made via the GetConnect.

![image](https://user-images.githubusercontent.com/23129313/115151554-04ad8d80-a076-11eb-82cf-0090d154f997.png)

**Minimal reproduction code**

```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() => runApp(MaterialApp(home: Home()));

class API extends GetConnect {
  Future<Response<dynamic>> test() {
    return get('https://jsonplaceholder.typicode.com/todos/1');
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () => API().test().then(
              (value) => print('success ${value.body}'),
            ),
      ),
    );
  }
}

```

**To Reproduce**
1. Add get library to your yaml (I'm on the current latest 4.1.4).
2. Create a GET request using GetConnect.
3. Run on the web.
4. Pay attention to the web console once you make the request.

**Expected behavior**
Clear logs, no errors.

**Flutter Version:**
2.0.4 stable

**Getx Version:**
4.1.4

P.S: Couldn't reproduce the issue on [similar library](https://pub.dev/packages/http), only on GetConnect.

Thank you in advance!

**Comment by eduardoflorence** [comment]
You can ignore this warning. It's a Chrome issue, as it works on Firefox. GetConnect defines a user-agent and it should be allowed according to the current http specifications.
Source: https://bugs.chromium.org/p/chromium/issues/detail?id=571722

**Comment by omzer** [comment]
@eduardoflorence Thanks for the fast response.
Is there's a way to get rid of that error? the more I have requests the more the console gets messy and it's harder to debug.

I understand it's not a GetConnect issue, but if so, why other libraries don't have it?

**Comment by eduardoflorence** [comment]
In other libraries, a default user-agent is not defined, which is why you don't see the problem happening. The user-agent header is important for your API to know which source the request is coming from and to return responses differently or to block the request.
If you really want to remove the user-agent, in your class that extends GetConnect, do this:
```dart
  @override
  void onInit () {
    httpClient.addRequestModifier<void>((request) {
      request.headers.remove('user-agent');
      return request;
    });
    super.onInit();
  } 
```

**Comment by omzer** [comment]
Thanks for explaining, really appreciate the help! :) 
I think we can close the issue now.
