### ISSUE TITLE
SnackBar bug

### ISSUE THREAD

**Issue by Pelmeshka102** [jonataslaw/getx#1340]
Hello, after upgrading to null-safety, you have to use snackbars differently. Before that, I put null everywhere because I only need the messageText field, now I can't do that.
Before:
```dart
Get.snackbar(
    null,
    null,
    borderRadius: 6.0,
    messageText: Text('promo_code_copied'.tr,
        style:
            appTheme.textTheme.caption4Semibold14.copyWith(color: appTheme.lighterWhite, fontWeight: FontWeight.w700)),
    backgroundColor: appTheme.darkLighterColor,
    snackPosition: SnackPosition.BOTTOM,
    margin: const EdgeInsets.only(left: 92, right: 93, top: 0, bottom: 20),
    snackStyle: SnackStyle.FLOATING,
  );
}
```
After
```dart
Get.snackbar(
    '',
    '',
    borderRadius: 6.0,
    messageText: Text('promo_code_copied'.tr,
        style:
            appTheme.textTheme.caption4Semibold14.copyWith(color: appTheme.lighterWhite, fontWeight: FontWeight.w700)),
    backgroundColor: appTheme.darkLighterColor,
    snackPosition: SnackPosition.BOTTOM,
    margin: const EdgeInsets.only(left: 92, right: 93, top: 0, bottom: 20),
    snackStyle: SnackStyle.FLOATING,
  );
}
```
Now, due to the fact that I do not use null, there is gives me additional space
![Screenshot_1618889721](https://user-images.githubusercontent.com/16879415/115334095-2e6cce80-a1b4-11eb-969c-2f78086ebd7d.png)
How can I fix that and use only one messageText line with TextStyle and don't use title ?

**Comment by DarkHeros09** [comment]
Hi 👋
Please use Get.rawSnackbar instead.
I believe you should get the desired behavior.

**Comment by Pelmeshka102** [comment]
@DarkHeros09 , thanks, it helped me
