### ISSUE TITLE
GetConnect timeout issue

### ISSUE THREAD

**Issue by thealteria** [jonataslaw/getx#1343]
Even after giving the httpClient.timeout in GetConnect, the api request still keep processing and getting the data. It's not getting cancelled or closed after the timeout. Also there's no way to cancel the httpClient request after the timeout.

**Comment by jasonlaw** [comment]
Same issue here

**Comment by jasonlaw** [comment]
#1730

**Comment by thealteria** [comment]
Wow thanks @jasonlaw!
