### ISSUE TITLE
how can I save my page state

### ISSUE THREAD

**Issue by SinoMiles** [jonataslaw/getx#1350]
I hava a download page.this will show download task and progress.
if i use Get.back() to leave this page.(I hope download task will contine in download page)
I wanna save this page state.and next time to open download page .will display the task and progress
how can i do this?any help!!!

**Comment by yasinarik** [comment]
Make it permanent. To do so:

`Get.put(YourControllerClass(), permanent: true);` . This way, the controller is created once and stays in the memory.
