### ISSUE TITLE
Controller does not dispose when BottomSheet modal closes

### ISSUE THREAD

**Issue by dangduoc** [jonataslaw/getx#1351]
I got a widget that binds to a controller. I show BottomSheet with that widget, the onInit() got called.
but when I closed the bottomsheet, the controller was still remained, the onClose() method did not be triggered at all.
And so when I re-open the bottomsheet again, the onInit() method wouldn't be called, because the controller did not re-create a new one for me, every state was stayed the same.

**Comment by woogi-kang** [comment]
same issue here

**Comment by furkankurt** [comment]
Same here...

**Comment by talksik** [comment]
sa,e
