### ISSUE TITLE
Flutter Localisation is not stable after after kill or destroy app

### ISSUE THREAD

**Issue by panchalAlpit** [jonataslaw/getx#1356]
I have used the Get package for localization and it's working fine. but if I destroy(kill, close) the app and open again so that time by default local language is set.

Example:- Open app-> language(English)-> change language(arabic)->it working -> close(destroy, kil) app-> again open the -> by default set language(English).

above is the flow of the process.

  GetMaterialApp(
        locale: Get.locale,
        translations: LLLanguages(),
        navigatorKey:Get.key,
        debugShowCheckedModeBanner:false,
        theme:LLTheme.light,
        darkTheme: LLTheme.dark,
        themeMode: ThemeService().theme,
        home:LLSplashScreen(),
      )

Get.updateLocale(Locale('ar','DZ'));
Thanks in advance

**Comment by hhstore** [comment]
- i think this is a bug. 
- but i find a solution. 
- my env: `flutter 2.2.1` + `get: ^4.1.4`
- Hope it solves your problem

```dart
Get.updateLocale(Locale('ar','DZ'));

/// fix locales refresh:
Get.reset();

```

**Comment by panchalAlpit** [comment]
I have used the share preference for this.

**Comment by anypwx** [comment]
> I have used the share preference for this.

bug disable also,  I trying it

**Comment by hhstore** [comment]
> > I have used the share preference for this.
> 
> bug disable also, I trying it

you can try my solution. just add `Get.reset();` after calling `Get.updateLocale(Locale('ar','DZ'));`.

```

Get.updateLocale(Locale('ar','DZ'));

/// fix locales refresh:
Get.reset();


```

**Comment by anypwx** [comment]
> > > I have used the share preference for this.
> > 
> > 
> > bug disable also, I trying it
> 
> you can try my solution. just add `Get.reset();` after calling `Get.updateLocale(Locale('ar','DZ'));`.
> 
> ```dart
> Get.updateLocale(Locale('ar','DZ'));
> 
> /// fix locales refresh:
> Get.reset();
> ```

I think this is not a very perfect solution, even though you have already solved it

**Comment by akshaydepfz** [comment]
> I have used the share preference for this.

show the code

**Comment by prasaddd77** [comment]
> I have used the share preference for this.

Can you share some steps on how to do that? Or the code if that's possible?
