### ISSUE TITLE
Deleting controller from memory when closing bottom sheet

### ISSUE THREAD

**Issue by rasouliali1379** [jonataslaw/getx#1357]
Hello,
I don't know this is a bug or feature request but it worth to ask.
I created a bottom sheet and defined a controller for it .

` final _controller = Get.put(BottomSheetController());`

and I'm calling it from a parent page like this 

`Get.bottomSheet(BottomSheet(),
          isScrollControlled: true);`

when I close the bottom sheet controller doesn't get deleted .
It gets deleted when I close the parent page . 

What should I do?

**Comment by hosseinhadi** [comment]
I am also just now encountered with this bug. Is there any fix or workaround?

**Comment by yasinarik** [comment]
I have the same bug. Using `get: ^4.1.4`.  Also, sometimes, even though I don't set `permanent: true` for a controller, it isn't deleted from the memory after navigating back from a regular route (not a bottom sheet).

**Comment by roipeker** [comment]
Clone of #1351. Please follow the other issue

**Comment by scnchlls** [comment]
> I have the same bug. Using `get: ^4.1.4`. Also, sometimes, even though I don't set `permanent: true` for a controller, it isn't deleted from the memory after navigating back from a regular route (not a bottom sheet).

You might be able to try

`          onTap:() async {
            await Get.bottomSheet(Text('bottom'));
            Get.delete<your controller>();
            //continue
          }`
