### ISSUE TITLE
Getting error:  Couldn't infer type parameter 'T'.

### ISSUE THREAD

**Issue by Gopalkrishanbairagi** [jonataslaw/getx#1365]
Getting Couldn't infer type parameter 'T'.
for httpClient.addAuthenticator and httpClient.addRequestModifier

**Comment by antonioJASR** [comment]
Try adding the type annotation in the first parameter inside the callback `(Request request) {}`, like this:

```dart
httpClient.addRequestModifier((Request request) {
  // Your awesome code here
  return request;
});
```

**Comment by Gopalkrishanbairagi** [comment]
Working this way, thank you :)

**Comment by developer-caleb** [comment]
> Try adding the type annotation in the first parameter inside the callback `(Request request) {}`, like this:
> 
> ```dart
> httpClient.addRequestModifier((Request request) {
>   // Your awesome code here
>   return request;
> });
> ```

you save my life. I love you!

**Comment by iamnomana** [comment]
> Try adding the type annotation in the first parameter inside the callback `(Request request) {}`, like this:
> 
> ```dart
> httpClient.addRequestModifier((Request request) {
>   // Your awesome code here
>   return request;
> });
> ```

You're the best brother🫱🏼‍🫲🏽
