### ISSUE TITLE
Snackbar not working

### ISSUE THREAD

**Issue by sujithsa007** [jonataslaw/getx#1375]
**Describe the bug**
Get.snackbar is not working

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:
 ElevatedButton(
                    child: Text('Click Me'),
                    onPressed: () {
                      Get.snackbar(
                          'User 123',
                          'Successfully created',
                          snackPosition: SnackPosition.BOTTOM
                      );
                    },
                  ),

**To Reproduce**
Please the elevated button in any part of UI and click the button

**Expected behavior**
Snapshot with message

**Screenshots**
NA

**Flutter Version:**
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (6 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

**Getx Version:**
 get: ^4.1.4

**Describe on which device you found the bug:**
POCO F1/Android 10 /MIUI 12.0.3 stable

**Minimal reproduce code**

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() => runApp(SnapshotSample());

class SnapshotSample extends StatelessWidget {

  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child:  ElevatedButton(
          child: Text('Click Me'),
          onPressed: () {
            Get.snackbar(
                'User 123',
                'Successfully created',
                snackPosition: SnackPosition.BOTTOM
            );
          },
        ),
      ),
    );
  }
}

**Comment by jonataslaw** [comment]
Snackbar will only work with GetMaterialApp

**Comment by sujithsa007** [comment]
Using getMaterialApp itself.

Still not working

Please check the full code here

https://github.com/sujithsa007/work_break_app

**Comment by sujithsa007** [comment]
Kindly avoid last email. It was my mistake

**Comment by sujithsa007** [comment]
It worked
*--*


*Thanks and RegardsSujith S A+917293535335*
