### ISSUE TITLE
Getx not work with PreferredSizeWidget

### ISSUE THREAD

**Issue by nakvanna** [jonataslaw/getx#1379]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by roipeker** [comment]
Closing the ticket for being unclear. If you wanna reopen, Please describe the issue and show some sample code to reproduce the bug.

**Comment by nakvanna** [comment]
I just wanna to use reactive variable in PreferredSizeWidget by user Obx().

**Comment by roipeker** [comment]
What's the issue? Use `Obx` inside your `Appbar` replacement.

**Comment by nakvanna** [comment]
yes thank you

**Comment by jonataslaw** [comment]
Create a class and extends PreferredSizeWidget, and within the build use Obx as you want

**Comment by nakvanna** [comment]
I will try it. Thank you
