### ISSUE TITLE
Navigation on state change

### ISSUE THREAD

**Issue by geovin89** [jonataslaw/getx#1386]
I am looking for an example or 'how to' on navigating to a new screen/perform an action on an observable state change. Both Obx and GetBuilder expects a widget in return but what I want is more like a BlocListener in Bloc library. Is it not possible in GetX?

**Comment by jonataslaw** [comment]
https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#workers

**Comment by geovin89** [comment]
Thanks a lot for responding. This is quite interesting, even though I did read about workers I never really thought it can be used as a replacement for listeners.

Just to make sure I understood you correctly; The workers (initialized in the controller) can be used for navigation since Get.to() does not really rely on the context.

**Comment by roipeker** [comment]
Yes, just make sure you dispose/close your resources overriding `GetxController.onClose()`.

Closing this issue as it's actually a question. Please use then other communication channels (Telegram/Discord) for further help.
