### ISSUE TITLE
Unhandled Exception: type 'GetDialogRoute<dynamic>' is not a subtype of type 'GetPageRoute<dynamic>' in type cast

### ISSUE THREAD

**Issue by papakay** [jonataslaw/getx#1394]
**Describe the bug**

I'm getting this error 
```Unhandled Exception: type 'GetDialogRoute<dynamic>' is not a subtype of type 'GetPageRoute<dynamic>' in type cast```
when i use this:
```dart
Get.offUntil(GetPageRoute(page: () => OrdersDetailsView()), (route) => (route as GetPageRoute).routeName == '/home');
```

**Flutter Version:**
2.0.5

**Getx Version:**
4.1.4

**Comment by papakay** [comment]
I noticed this issue happens when i have `Get.dialog()` before `Get.offUnitl()`.

I had this
```dart
Get.dialog()l
// Run a function and once it's successfully completed, i do the following.
Get.back();
Get.offUntil(GetPageRoute(page: () => OrdersDetailsView()), (route) => (route as GetPageRoute).routeName == '/home');
```

**Comment by jonataslaw** [comment]
You can exclude dialogs, snackbars, and bottomsheets from offUntil:
```dart
Get.offUntil(GetPageRoute(page: () => OrdersDetailsView()), (route) => route is GetPageRoute && route.routeName == '/home');
```

**Comment by papakay** [comment]
Thank you so much. It works great!
