### ISSUE TITLE
Static variables and typing

### ISSUE THREAD

**Issue by Hekhy** [jonataslaw/getx#1397]
Hello,
what I would like to propose is not a change as such of the package, but a change in the way of using it.
I have recently been testing the package and it works great, I love it, but in general I hate having to create new instances of my controller whenever I want to use a variable.obs.
This hatred is not towards this package but in general in all flutter, I do not like to be creating instances in each file although sometimes it is necessary, and as I always hate it I usually use static variables that make it easier for me to use the variables globally without having than always be creating those instances.
That is why I wanted to suggest this change in the way of using it or that it be added as one more option to use for the package in the tutorial, since static variables are very powerful in that sense and more than one may like this option and decide like this by the use of the package (for example to my xD).

In addition, I would also like it to be explained that in the creation of the variables.obs it is not necessary to create it with the syntax of the tutorial so that there is no error by putting Int, that is:
var count = 0.obs;
but it can be created as follows:
RxInt count = 0.obs;

In this way, the strict Dart typing is still maintained, which is so useful and continues to specify that it is an Int but with the use of GetX, which I think is wonderful.

In this [link](https://github.com/Hekhy/CounterGetXApp) I leave my github repository where I create the counter application using the method I mentioned above and I add the options to add, subtract and set the counter to 0, there are a few more lines but I simply wanted to demonstrate what I mention.

For the rest, this package has left me amazed with how good it is and how easy it is to implement, I was using bloc and provider and although they are very powerful it is a lot of trouble compared to getx what you have to do to start it and with getx is infinitely easier.

Thanks for creating this package, greetings!

**Comment by ahmednfwela** [comment]
using static variables in a GetXController is actually bad, since static variables are not disposed when the controller is removed from memory.

In general, you have 2 cases of reusing a variable

1. Share it with other classes (using GetXService)
2. Repeat it for every instance of a class (using mixins)

for example if I have an application with 5 views, each has its "separate" counter
mixin CounterMixin {
  final counter = 0.obs;
}

```dart
class CounterController1 extends GetXController with CounterMixin   {
// other members here ...
}
class CounterController2 extends GetXController with CounterMixin   {
// other members here ...
}
```

But, if I have an application with 5 views, each "sharing" the same counter
```dart
class CounterService extends GetXService {
  final counter = 0.obs;
  // other members here ...
}
```

**Comment by Hekhy** [comment]
Hello @ahmednfwela,
Thanks for the examples, I did not know about the static variables and also I never thought about the mixin for this, not even knowing it before, what a head I have. Regarding the examples, the first one has served me very well, but the second one I do not quite understand how to apply it, if you could give an example, even with the test project that I had put in, I would appreciate it.
If you are busy there is no problem, the other example has worked for me too. Thanks again.

**Comment by ahmednfwela** [comment]
Think of the second scenario as having a "UserService" that stores info about the current logged in user.

In this case, each view will "share" the same user (rather than have a user for each view)

```dart
class UserService extends GetXService {
  final userInfo = Rxn<UserModel>();
}
```

**Comment by Hekhy** [comment]
Okay, now I understand, thank you.
I see that you have a lot of knowledge and since I am I would like to ask you if there is any way to do a double mixin, that is, I have tried this first:

```
class Variables {
  final RxInt counter = 0.obs;
}

class Variables2 {
  final RxInt counter2 = 0.obs;
}

class MyApp extends StatelessWidget with Variables with Variables2 {
// ....
}
```
crazy, yeah haha, it gave errors everywhere, but it was the easy test, then I tried this:

```
class Variables {
  final RxInt counter = 0.obs;
}

class Variables2 with Variables{
  final RxInt counter2 = 0.obs;
}

class MyApp extends StatelessWidget with Variables2 {
// ...
}
```

And this if it worked but when I tried to do the mixin with another class it gave me this error: 

![yerterty](https://user-images.githubusercontent.com/70041483/118649247-962e2d80-b7e3-11eb-9fa6-d3d95b444499.jpg)

I don't know if it has to do with putting it in a class extended by StatelessWidget.

Apparently I can't double mixin this way, but is there a way to do it correctly?

**Comment by ahmednfwela** [comment]
mixins need to be declared as mixins
e.g.
```dart
mixin Variables {
  final RxInt counter = 0.obs;
}

mixin Variables2 {
  final RxInt counter2 = 0.obs;
}

class MyApp extends StatelessWidget with Variables, Variables2 {
// ....
}
```

or 

```dart
mixin Variables {
  final RxInt counter = 0.obs;
}

mixin Variables2 on Variables {
  final RxInt counter2 = 0.obs;
}

class MyApp extends StatelessWidget with Variables2 {
// ...
}
```

**Comment by ahmednfwela** [comment]
Also here is the documentation on mixins : https://dart.dev/guides/language/language-tour#adding-features-to-a-class-mixins

**Comment by Hekhy** [comment]
Well, thanks, now if I understood everything, although in the link I saw that it says that unless you want to use the mixin as a normal class declare it with the keyword "mixin" instead of "class" and do not put a constructor, like this that my problem was not to put the commas to be able to put more mixins.
Thanks again for your good explanation.

**Comment by jonataslaw** [comment]
Hi, thanks for your time for trying to build something new with Getx.
I agree with @ahmednfwela on the use of static variables within controllers. This can be dangerous because it prevents them from being disposed of properly.
Using mixins are a great way to respect DRY principles. You can also use inheritance to avoid repetition of code.
Well, I'm closing this, but if it's not enough, feel free to open other questions like this in the discussions tab.

**Comment by Hekhy** [comment]
Hello @jonataslaw,
I totally agree with respecting the DRY principles,
This is mainly why I created the question, because I don't like having to be creating so many instances of my classes, so thanks to both of you for the help and the clarification.
And without a doubt I will open other questions in order to help me improve or to help me again.
Thanks again and best regards.
