### ISSUE TITLE
1 positional argument(s) expected, but 0 found.

### ISSUE THREAD

**Issue by amitgeed** [jonataslaw/getx#1403]
`final selectedUserType = Rx<User>();`

1 positional argument(s) expected, but 0 found.
Try adding the missing arguments.

**Comment by hosseinhadi** [comment]
Try using final `selectedUserType = Rxn<User>();` when you are not intended to initialize an `Rx<>` typewith a value. The `Rxn` is the nullable form of `Rx` type.

**Comment by amitgeed** [comment]
> Try using final `final selectedUserType = Rxn<User>();` when you are not intended to initialize an `Rx<>` typewith a value. The `Rxn` is the nullable form of `Rx` type.

Working Fine
Thank You
