### ISSUE TITLE
GetX Controller doesn't get created

### ISSUE THREAD

**Issue by chamikapeiris** [jonataslaw/getx#1414]
I have a list view with search functionality. When an item clicked, it will create a screen with a controller. I faced this bug when I filter something from the list and click the item, again and again, after some time it stopped creating the controller for the clicked item. What could be the cause? There were no errors in the code.

**I could not see,**
```
[GETX] Instance "{Name}Controller" has been created
[GETX] Instance "{Name}Controller" has been initialized
```
but this shows,

`[GETX] GOING TO ROUTE /() => {ScreenName}`

**Flutter Version:**
2.0.1 and 2.0.6

**Getx Version:**
4.1.4

**Comment by MohsenHaydari** [comment]
if your controller call any nullable value or any errror in init , you get some infromation like `[GETX] GOING TO ROUTE /() => {ScreenName}` and currect rout not opening, if your controller initialized by any clicked and deleted after closing page, u must use tag in `Get.put(tag:'tag')` and before any push to item page checked latest controller item with `Get.isRegistered<classType>(tag: 'tag')` and if exists deleted by `Get.delete<classType>(tag: 'tag',force: true)`, Now you can check which of the items has a problem

**Comment by chamikapeiris** [comment]
There

**Comment by chamikapeiris** [comment]
> if your controller call any nullable value 
It's ok to have nullable values in the controller right?

**Comment by chamikapeiris** [comment]
Hey there, my error is not resolved yet. I think this happens when I use the search option. When I go to a filtered item, after some time, when I click another item on the list, It will not initialize the controller. What am I doing wrong? No errors I can find though.

**TextField**
```
TextField(
              controller: _controller,
              decoration: InputDecoration(
                fillColor: kLightGreyColor,
                filled: true,
                prefixIcon: Icon(Icons.search),
                suffixIcon: IconButton(
                  onPressed: () {
                    _controller.clear();
                    homeController.query('');
                  },
                  icon: Icon(Icons.clear),
                ),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(kCornerRadius),
                ),
                labelText: 'What are you looking for?',
              ),
              onChanged: homeController.onSearchTextChanged,
            ),
```
**List**
```
Obx(
                () => homeController.isLoading()
                    ? Center(child: CircularProgressIndicator())
                    : ListView.builder(
                        itemCount: homeController.query.isEmpty
                            ? homeController.courseList.length
                            : homeController.searchList.length,
                        itemBuilder: (BuildContext context, int index) {
                          return CourseCard(
                              result: homeController.query.isEmpty
                                  ? homeController.courseList[index]
                                  : homeController.searchList[index],
                              homeController: homeController);
                        },
                      ),
              ),
```
**Controller**
```
RxBool isLoading = true.obs;
List<CoursesResult> courseList = <CoursesResult>[].obs;
List<CoursesResult> searchList = <CoursesResult>[].obs;

onSearchTextChanged(String text) async {
    query.value = text;

    if (text.isEmpty) return;

    searchList.clear();

    courseList.forEach((course) {
      if (course.name.toLowerCase().contains(text) ||
          course.name.contains(text)) searchList.add(course);
    });
  }
```
