### ISSUE TITLE
GetConnect chinese garbled

### ISSUE THREAD

**Issue by Victor-XHH** [jonataslaw/getx#1422]
I try to use get4.1.4 GetConnect, the Chinese characters obtained from the api are garbled, how to set it in the defaultDecoder? Is it useful?

**Comment by roipeker** [comment]
You might try to decode the `Response.bodyBytes` with utf8
The defaultDecoder is just a callback to transform the expected output in `Response.body` to a specific Type.

**Comment by jonataslaw** [comment]
fixed on https://github.com/jonataslaw/getx/pull/1424
