### ISSUE TITLE
request url replace ?

### ISSUE THREAD

**Issue by liseipi** [jonataslaw/getx#1428]
```
httpClient.addRequestModifier((request) async {
      var url = request.url;
      if (url.path.indexOf(":productID") != -1) {
        url.path.replaceAll(":productID", "123456");
        print(url);
      }
     //request.url = url;     // Will report an error
      return request;
    });
```

**Comment by liseipi** [comment]
This does not replace

**Comment by KevinZhang19870314** [comment]
`replaceAll` will **return** the replaced new string, actually your code will not modify the request.url at all.

**Comment by liseipi** [comment]
> `replaceAll` will **return** the replaced new string, actually your code will not modify the request.url at all.

request.url = url;   Will report an error

**Comment by KevinZhang19870314** [comment]
After digging into the GetX source code, I think there is no way to handler your requirement, from the code the `url` is a final property,
```
class Request<T> {
  /// Headers attach to this [Request]
  final Map<String, String> headers;

  /// The [Uri] from request
  final Uri url;
```

Also, your return statement is useless, since the code is just use the request refreence, not use the return part.
  ```
Future<Response<T>> _performRequest<T>(
    HandlerExecute<T> handler, {
    bool authenticate = false,
    int requestNumber = 1,
    Map<String, String>? headers,
  }) async {
    try {
      var request = await handler();

      headers?.forEach((key, value) {
        request.headers[key] = value;
      });

      if (authenticate) await _modifier.authenticator!(request);
      await _modifier.modifyRequest(request);

      var response = await _httpClient.send<T>(request);
```

A workaround is do it in your request business logic part.

**Comment by liseipi** [comment]
Thanks for your answer  @KevinZhang19870314

**Comment by jonataslaw** [comment]
Thanks for reporting this, and thanks @KevinZhang19870314 for commenting on this.

I think there are two things missing from the current code from that issue.

1- use the returned instance

```dart
 final newRequest =  await _modifier.modifyRequest(request);

 var response = await _httpClient.send<T>(newRequest);
```

2- Add copyWith method in response to facilitate the creation of objects with properties inherited from the previous object.


If nobody offers a pull request with these changes, I will do it this weekend, where GetX will have a new great update

**Comment by liseipi** [comment]
@KevinZhang19870314 
我还没有弄懂在 request 中使用copyWith 达到替换url 的功能
能否修改我的例子达到我的需要目的
```
 httpClient.addRequestModifier<dynamic>((request) async {
      var requestUrl = request.url;
      var urlString = requestUrl.toString();
      var query = requestUrl.queryParameters;
      query.forEach((key, value) {
        if (urlString.indexOf(key) != -1) {
          urlString.replaceAll(':$key', value.toString());
          (request.url.path).replaceAll(':$key', value.toString());
        }
      });
      var uri = Uri.parse(urlString);
      print(uri);
     // 这是我替换到需要uri
    // request.url = uri; // 这样是不行
   // 我大概明白上明说的copyWith 方式，没清楚如何改写
      
      // request.headers['Authorization'] = 'bearer 12345678';
      return request;
    });
```

**Comment by KevinZhang19870314** [comment]
@liseipi 现在还改不了，我提交了pr，作者合了但是还没有release新版本，你如果现在要改的话看我提的pr然后fork一下代码，用git url的方式引入getx库。
