### ISSUE TITLE
Web app crashes when I try to navigate

### ISSUE THREAD

**Issue by iMrLopez** [jonataslaw/getx#1442]
**Describe the bug**
Cannot navigate when initial route should be generated with params. I am trying to do this in local (web)

**Reproduction code

`http://localhost:51370/MyId123?param=123
`I have my pages as this:

```
  static final List<GetPage> pages = [
    GetPage(
      name: '/',
      binding: HomeBinding(),
      page: () => HomePage(),
    ),
    GetPage(
      name: '/:id',
      binding: HomeBinding(),
      page: () => HomePage(),
    ),
  ];
```
but it keeps throwing this:

```
╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞
The following message was thrown:
Could not navigate to initial route.
The requested route name was: "/MyId123?param=123"

There was no corresponding route in the app, and therefore the initial route specified will be
ignored and "/" will be used instead.
my main looks as this:
```

```
return GetMaterialApp (
  getPages: AppPages.pages
);
```

**To Reproduce**
1. Create the app
2. Hit the url in the browser

**Expected behavior**
Navigation should work as it says in the docs

**Screenshots**

**Flutter Version:**
```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-CR)
    • Flutter version 2.0.6
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
````
**Getx Version:**
`  get: ^4.1.4`

**Describe on which device you found the bug:**
Web

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jonataslaw** [comment]
The error is self explanatory, please provide a valid initial route. Slash cannot receive parameters.

**Comment by iMrLopez** [comment]
@jonataslaw this happens even if I do this:
```
  static final List<GetPage> pages = [
    GetPage(
      name: '/m/',
      page: () => SplashPage(),
    ),
    GetPage(
      name: '/m/:id',
      binding: HomeBinding(),
      page: () => HomePage(),
    ),
  ];
  ```
  ```
  ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞
The following message was thrown:
Could not navigate to initial route.
The requested route name was: "/m/123?params=123"
There was no corresponding route in the app, and therefore the initial route specified will be
ignored and "/" will be used instead.
```

the docs [here](https://github.com/jonataslaw/getx/blob/master/documentation/en_US/route_management.md) say it is possible

**Comment by jonataslaw** [comment]
123 is not a path, you need to study url patterns to understand what is wrong.

But just for you to understand in your case, what you should do, you should do something like this to work:

```dart
GetPage(
      name: '/m',
      binding: HomeBinding(),
      page: () => HomePage(),
    ),
```
`Get.toNamed('/m?id=123&params=123')`

**Comment by iMrLopez** [comment]
So this is not possible?

```
      GetPage(
        name: '/profile/',
        page: () => MyProfile(),
      ),
       //You can define a different page for routes with arguments, and another without arguments, but for that you must use the slash '/' on the route that will not receive arguments as above.
       GetPage(
        name: '/profile/:user',
        page: () => UserProfile(),
      ),
 ````

**Comment by iMrLopez** [comment]
@jonataslaw something is happening whenever I activate the url_strategy in flutter.... Have a look at #1170
