### ISSUE TITLE
Is the package ready for Navigator 2.0 ?

### ISSUE THREAD

**Issue by iMrLopez** [jonataslaw/getx#1443]
Is the package ready for navigator 2.0 ? Seems like this could be a breaking change

related to:

#1442

**Comment by jonataslaw** [comment]
Navigator 2 is not a breaking change, and you can use it normally with GetX.
Your previous issue has nothing to do with Navigator 2.0, but with the wrong url pattern.
Read the docs and URL patterns to learn how to build query parameters and what you can and cannot do.
