### ISSUE TITLE
How do we get the cookie from response?

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#1444]
The Response's header is in datatype of Map<String, String>. While the response cookie could be redundant.

![image](https://user-images.githubusercontent.com/107820/118746816-7c482580-b88b-11eb-85e0-7f15261c2a1b.png)

In this case, how does the GetConnect store the cookies? How do we get the cookies out from response?

**Comment by jasonlaw** [comment]
After some debug, I found there is no "set-cookie" data in the response header, tested with Postman and confirm the cookie is returned from the api.

Any help?

**Comment by jasonlaw** [comment]
Maybe this is due to my cookies are httpOnly. Anyway, just found out for flutter web we don't need to extract the cookies for next request by ourselves, the browser can handle this. Closing this issue for now.

**Comment by renittobb** [comment]
But what if I'm getting the cookie on the response headers and I want to extract that data? here I want to get the value of csurftoken from the response header set-cookie.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/106244321/184880397-85d4dca4-a0d2-4481-8c3e-affb3657bb81.png">
