### ISSUE TITLE
Some Links are not working in document

### ISSUE THREAD

**Issue by bhanuka96** [jonataslaw/getx#1448]
Some links are not working

example:
https://www.appwithflutter.com/flutter-routing-using-get-package/
**Flutter Routing with Animation using Get Package - by App With Flutter.**

**Comment by roipeker** [comment]
> Some links are not working
> 
> 
> 
> example:
> 
> https://www.appwithflutter.com/flutter-routing-using-get-package/
> 
> **Flutter Routing with Animation using Get Package - by App With Flutter.**

Can you be more specific to what links you are referring to? 
Please, reopen the issue if it's relevant to the GitHub docs.
