### ISSUE TITLE
How can I get pageList

### ISSUE THREAD

**Issue by jy6c9w08** [jonataslaw/getx#1453]
I open a lot of new pages, how do I know how many pages are opened.
For example, I am now on the homepage.Then, I open two new pages in a row, how can I get the pageList length is 3?
Thanks everyone.

**Comment by zhaoce** [comment]
Unless you maintain the pages yourself

**Comment by jonataslaw** [comment]
This will be possible in the next update, in fact the master update already allows this.
This weekend we will have a big update

**Comment by jy6c9w08** [comment]
@jonataslaw  Thanks for your reply.Maby I used an older version.
I try to expose private variables in NavatorState _history，It solved my problem.
`List<_RouteEntry> get history => _history;`
