### ISSUE TITLE
GetStreamTransformation.distinct prev and next are identical when using Rx<T>.update

### ISSUE THREAD

**Issue by steven-spiel** [jonataslaw/getx#1469]
Using distinct the GetStreamTransformation, the params `prev` and `next` are always the same.

example:

```dart
import 'package:get/get.dart';

class Bar {
  String? val1;

  @override
  String toString() => val1 ?? '';
}

class Foo {
  Foo() {
    // also tried bar.subject.stream
    bar.stream.distinct((Bar? prev, Bar? next) {
      print('$prev == $next');

      return prev == next;
    }).listen((_) {});

    bar.update((Bar? b) => b?.val1 = 'something');
    bar.update((Bar? b) => b?.val1 = 'something new');
  }

  final Rx<Bar> bar = Bar().obs;
}
```

What's printed to the console is 

```
something new == something new
```

Note that I tested this code out with `RxString`, updating it with `string.value = 'foo'`, and it worked as expected. The `prev` and `next` values were indeed different.

**Flutter Version:**
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-arm, locale en-US)
```

**Getx Version:**
`4.1.4`

**Describe on which device you found the bug:**
iPhone

**Comment by jonataslaw** [comment]
The object is the same, you are changing the property. If you want to change the object, make the variables 'final', and use copyWith, or else directly compare the changed property.

 print('${prev.val1} == ${next. val1}');

**Comment by steven-spiel** [comment]
That did it. Thank you!
