### ISSUE TITLE
The document should make an example for map data

### ISSUE THREAD

**Issue by ExiaGo** [jonataslaw/getx#1471]
I want to observe a map, but I have a problem like this:
`flutter: [UNHANDLE ERROR] type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'RxMap<String, dynamic>'`

Here my resolvent:
```
var theMap = <String, dynamic>{}.obs;
onInit() {
  theMap = RxMap<String, dynamic>.from(data['key']);
}

```
Thanks for your reading.

**Comment by jonataslaw** [comment]
Read the docs.
you must use the Map/List as `final`, and use `assignAll` to sign a new map for the observable

**Comment by ExiaGo** [comment]
@jonataslaw Thanks !

**Comment by alexboulay** [comment]
@jonataslaw I read the entire docs, quite heavy, I might have missed something but it seems like the only way I can update my `Map<String, List<SomeObject>>` and make it reactive is to "recreate" with assignAll instead of calling the `add`. Am I missing something :) ?

Thank you.

**Comment by marko-mlinarevic** [comment]
For me assignAll doesn't work at all. still remains default

**Comment by rizzi37** [comment]
> For me assignAll doesn't work at all. still remains default value, list works but object doesnt

maybe your obj is no frozen

**Comment by jianghaihui** [comment]
I  have a map like this
```
 map<String,dynamic>  food=map<String,dynamic>();
food["name"]="bread";
food["price"]=12.5;
food["from"]="UK";
...
```
this map have more than 200 keys.

when the key: `price`  changed,    how to notice some Widget  to change
