### ISSUE TITLE
Rx variable not update when typing

### ISSUE THREAD

**Issue by dalton5** [jonataslaw/getx#1479]
Hi,

I use a PwdValidator class to show to the user the password requirements. 

My class is as below:

`class PwdValidator {
  bool minChars = false;
  bool nbChar = false;
  bool upperChar = false;
}`

Then I have my GetxController which initialize the PwdValidator.

Rx<PwdValidator> validators = PwdValidator().obs;

Then in my UI widget I have this row:

        `Row(mainAxisAlignment: MainAxisAlignment.start  ,children: [
          Obx(()=> Visibility(child: Icon(Icons.error, color: MyTheme.PrimaryColor),visible: controller.validators.value.minChars)), ],),`

I also have my form which is as below:

          `TextFieldForm(L.Localize('Your password'),
          controller: controller.pwdController,
          keyBoard: TextInputType.text,
          onSaved: (value) {
          controller.input.value.password = value!;
          },
          validator: (value) => 
          ValidatorController.checkPassword(value!, controller.validators),
          
          ),`

And finally my validator function. It's called on everytyping. But the validators value are refreshed only once I type on the validation button keyboard.

      `if (res == null) {
          if (GetUtils.isLengthLessThan(value, 6)) {
            validators.value.minChars = false;
            error = true;
          } else {
            validators.value.minChars = true;
          }`

It works well when I validate on the keyboard with the green validate button of the keyboard.

![image](https://user-images.githubusercontent.com/8339768/119689997-9bc1ee00-be49-11eb-8bf1-d04a0199e50a.png)

But I would like to get it to be changed during my typing.

How can I do it?

**Comment by KevinZhang19870314** [comment]
I think you also need to add `onChanged` callback to TextFormField widget, thus will listen the every typing of keyboard.

**Comment by dalton5** [comment]
I did it but I still have the same issue. DO you know how is it possible?

**Comment by jonataslaw** [comment]
A custom class is only updated using the update method, or by transforming it into an internally reactive class. Read the documentation on Model reactive classes

ex:

`validators.update((validator)=> validator.minChars = false)`
