### ISSUE TITLE
GetConnect , I want use 3 defaultDecoder

### ISSUE THREAD

**Issue by babakoto** [jonataslaw/getx#1480]
httpClient.defaultDecoder =(data)=> User.fromJson(data);
   httpClient.defaultDecoder =(data)=> Store.fromJson(data);
  httpClient.defaultDecoder = (data)=>List<Store>.from(data.map((model)=> Store.fromJson(model)));

Error :
**type '(dynamic) => List<Store>' is not a subtype of type '((dynamic) => User?)?' in type cast**

I can't use multiple defaultDecoder in provider ?

**Comment by KevinZhang19870314** [comment]
defaultDecoder is a unique global things, if you want to use multiple decoder, please pass the `Decoder<T>? decoder` to every http request.

**Comment by babakoto** [comment]
thanks .

Solution: 

 ```
 Future<Response<List<Store>?>> findAll() {
     Decoder<List<Store>> decoder = (data)=>List<Store>.from(data.map((model)=> Store.fromJson(model)));
    return get("/store",decoder: decoder);
  }
```
