### ISSUE TITLE
Repeatedly open the details page ?

### ISSUE THREAD

**Issue by liseipi** [jonataslaw/getx#1481]
in the app
Repeatedly open the details page

start :

"/splash" -> "/index" -> "/details/:productID" -> "/details/:productID" -> "/details/:productID"

When you open details multiple times, the page content will not be updated

Is there any relevant code to view?

**Comment by KevinZhang19870314** [comment]
I am guessing you are using the single GetxController for detail page, so when you navigate to detail page, init method will not be called again, thus page data/content will not be updated.

So you need to either tag your GetxController per detail page, or dispose previous detail page and rebuild it again to open it.

**Comment by liseipi** [comment]
@KevinZhang19870314  So you need to either tag your GetxController per detail page.

Is there a demonstration code to see?

**Comment by KevinZhang19870314** [comment]
@liseipi I have created a [minimal sample](https://github.com/KevinZhang19870314/flutter_getx_boilerplate/blob/issue-1481/lib/modules/issue_1481/issue_1481_binding.dart) for your reference, you can run this project at branch `issue_1481`, and go below steps.

1. Go to Discover tab, click discover button at the center screen;
2. A Issue 1481 screen will be navigate to, you can see the number in center of screen;
3. And click 'Navigate to issue_1481 again' button, you will go into this page again;
4. Instead you will see the number changed, but still in same page;

So what am I saying is, once you specific the tag for the controller, you will get a new controller instance for the same opened page, therefore the `onInit` method will be executed again and deal with you data business logic and see the data changes.

```
import 'package:flutter_getx_boilerplate/modules/issue_1481/tag_utils.dart';
import 'package:get/get.dart';

import 'issue_1481_controller.dart';

class Issue1481Binding implements Bindings {
  @override
  void dependencies() {
    var _controller = Issue1481Controller();
    var tag = _controller.tag;
    TagUtils().tags.add(tag);
    print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>bindings$tag');
    Get.lazyPut<Issue1481Controller>(
      () => Issue1481Controller(),
      tag: tag,
      // fenix: true,
    );
  }
}
```

**Comment by liseipi** [comment]
Thank you very much @KevinZhang19870314  , 💯

**Comment by roipeker** [comment]
I would advise to rely on local Controllers using `GetBuilder<YourController>(init:YourController(urlParam), builder:(controller)=>_Screen(controller)`

**Comment by liseipi** [comment]
@roipeker , use tag way, Can be `onInit` again .

Do you have better code to demonstrate?

**Comment by roipeker** [comment]
@liseipi check [here](https://gist.github.com/roipeker/6b08e9f7e2d8b83ecbf399cbe039ca09)

**Comment by roipeker** [comment]
As a quick note, In common GetX architecture the relation between views and controllers should be 1:1, by "view" I mean Page/Screen/Route. (A TabView or PageView might have several views with its own local controllers for example). 

In your case if you rely on the url params to use as "tag" for the GetInstance DI, you will face the issue if Navigator.push() uses the same `productid` multiple times in the navigation stack, creating new Instances of your View widget, which logically should have it's own Controller attached to control it. This is why the "local" Controller approach seems more logical than a random number to inject the controller as a global instance. At least until we figure some simpler and clearer API in dependency injection and route management to deal with this type of cases.

Remember that GetxControllers (and its lifecycles methods) is just the Getx way to express a State in a Statefulwidget.

**Comment by liseipi** [comment]
Sample 2 (local controller) , very useful . @roipeker  , Thank you very much !

**Comment by roipeker** [comment]
If you think something is missing please reopen the issue.
