### ISSUE TITLE
Android project evoke flutter report an error(Null check operator used on a null value. See also:https://....).

### ISSUE THREAD

**Issue by JuneCheng** [jonataslaw/getx#1493]
I created a flutter_ Module, the module can run independently, and IOS project evoke the module can display the page normally, but Android project evoke will report an error(Null check operator used on a null value. See also:https://....). After many tests, after I removed getPages in GetMaterialApp, the home page can be displayed normally, but I can't use named route.I don't know how to fix it.

This is my demo download address.
[https://github.com/JuneCheng/android_flutter_getX](https://github.com/JuneCheng/android_flutter_getX)

get version:get: ^4.1.4
dart version:2.7.0

main.dart code
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:my_flutter/route_config.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      getPages: RouteConfig.getPages,
      home: Container(
        color: Colors.purple,
        child: Center(
          child: GestureDetector(
            onTap: () {
              Get.toNamed(RouteConfig.demo);
            },
            child: Text(
              'Jump to Demo Page',
              style: TextStyle(fontSize: 20.0, color: Colors.red),
            ),
          ),
        ),
      ),
    );
  }
}
```

route_config.dart code
```
import 'package:get/get.dart';

import 'views/demo/demo_view.dart';

class RouteConfig {
  /// 首页
  static final String main = '/';

  static final String demo = '/demo';

  /// 别名映射页面
  static final List<GetPage> getPages = [
    GetPage(name: demo, page: () => DemoPage()),
  ];
}
```

<img src="https://user-images.githubusercontent.com/36223198/119970371-36edcb80-bfe2-11eb-8334-7dd6cda506d4.jpg" width="250" />
<img src="https://user-images.githubusercontent.com/36223198/119969958-cba3f980-bfe1-11eb-9bb1-6126c2b8b762.jpg" width="250" />

**Comment by fuadreza** [comment]
Can you tell me what is the solution for this? Thanks

**Comment by JuneCheng** [comment]
> Can you tell me what is the solution for this? Thanks

I made a mistake when jumping to the flutter.
Please assign InitialRoute as '/' .
If you assign InitialRoute as  a nonexistent routeName,it will report this error.

**Comment by fuadreza** [comment]
I'm sorry, but how is that possible? I already adding `initialRoute: '/'` in my `GetMaterialApp` but I still got the error

**Comment by JuneCheng** [comment]
`
private FlutterEngine createFlutterEngine() {
        // 实例化FlutterEngine对象
        FlutterEngine flutterEngine = new FlutterEngine(this);
        // 设置初始路由
        flutterEngine.getNavigationChannel().setInitialRoute("/");
        // 开始执行dart代码来pre-warm FlutterEngine
        flutterEngine.getDartExecutor().executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        );
        // 缓存FlutterEngine
        FlutterEngineCache.getInstance().put("my_engine_id", flutterEngine);
        return flutterEngine;
    }
`
assign InitialRoute as '/' in android project，not initialRoute in your flutter project
