### ISSUE TITLE
Question: How to specify the height of Getx BottomSheet??

### ISSUE THREAD

**Issue by rmControls** [jonataslaw/getx#1494]
Its a question not a bug...

How to make Getx BottomSheet to have 70% of screen size?

I tried adding Container() as child with height  parameter and it did't worked....

Please suggest...

**Comment by jonataslaw** [comment]
Please do not use this field for questions.

**Comment by HaoLC** [comment]
> Sorry I will not do it again.... but can you answer to my question...?

Hope it can help you.
<img width="555" alt="Screen Shot 2021-06-04 at 16 51 22" src="https://user-images.githubusercontent.com/26896377/120783814-99e8e080-c555-11eb-8a80-0e75bf450678.png">

**Comment by rmControls** [comment]
Yup that worked... 

I was missing with isScrollControlled: true parameter....

Thank you very for the help...
