### ISSUE TITLE
Controller with custom init

### ISSUE THREAD

**Issue by Urkman** [jonataslaw/getx#1505]
**Describe the bug**
When I use a custom init on a GetXController, the onInit and other functions are not called...

**Reproduction code
Here is some controller code:
```dart
class Controller extends GetxController {
  var object = Object().obs;

  Controller({
    required this.object,
  }) : super();

@override
  void onInit() {
    print("not called");
    super.onInit();
  }
}
```

And here I call the custom init:
```dart
var ctl = Controller(object: object.obs);
```

**Expected behavior**
That the "on..." functions are called

**Flutter Version:**
2.2.1

**Getx Version:**
4.1.4

**Describe on which device you found the bug:**
iOS and Android

**Comment by jonataslaw** [comment]
Initially, without using Get.put/Get.lazyPut etc, onInit will not be called.
Second, dart inheritance works perfectly
