### ISSUE TITLE
Getx can't find async global dependency in InitialBinding

### ISSUE THREAD

**Issue by fhfuih** [jonataslaw/getx#1509]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
So I have an ApiProvider dependency injected to the app. I also have another dependency which is a specific API fetch response that should be injected as a global dependency. I tried to construct both in `initialBinding`, and use them in a view. While the ApiProvider is fine, flutter complained that the latter is not found on red screen. Sometimes the error flashed for one second and disappears at the next build routine. I wonder what is wrong with my code, or is it some issue in GetX? (Although I may have used the library the wrong way, at least I could not find relevant information on the documentation)

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

https://gist.github.com/fhfuih/8ab5a4539844cdb6dc0c0e77fe479396

**To Reproduce**
1. In `InitialBinding.dependencies`, `put` an ApiProvider, followed by a `putAsync` of the return value of an async method in the ApiProvider.
2. Build/hot-rebuild the app

**Expected behavior**
No exception

**Flutter Version:**
2.2.0

**Getx Version:**
4.1.4

**Describe on which device you found the bug:**
android (1+7pro) & web (chromium edge)

**Comment by fhfuih** [comment]
Also, a quick off-topic question: are these independent (and all correct) approaches to inject global dependencies?
1. `put` the dependency anywhere with `permanent: true`
2. `put` the dependency in `initialBinding` (regardless of the `permanent` parameter)
3. declare the dependency as `extends GetxService` or `with GetxServiceMixin` and `put` it anywhere  (regardless of the `permanent` parameter)
4. `put` the dependency in main before `runApp`. (Like the `initServices()` code example in doc)

**Comment by fhfuih** [comment]
I managed to overcome the issue using (4) in my previous comment, i.e.,
```dart
Future<void> initServices() async {
  Get.put...
  await Get.putAsync...
}
void main() async {
  await initServices();
  runApp...
}
```
(Although new issue arises because I tried to load asset JSON files in my mock ApiProvider, and loading assets before building any widgets returns null because (maybe) no BuildContext is presented yet. But that should be another irrelevant issue.)
Alright I still wonder why InitialBinding does not work in this case. If it is my issue, could you please add some more clarifications on the documentations, as I couldn't find any related information there? Thanks!

**Comment by KevinZhang19870314** [comment]
For putAsync the [doc](https://github.com/jonataslaw/getx/blob/master/documentation/en_US/dependency_management.md#getputasync) saild: 

> If you want to register an asynchronous instance, you can use Get.putAsync

which means that returned instance must be asynchronous, not the method you called is async/await, so I think this is why throw error when you call `final data = Get.find<InitialData>();`

```
  Future<InitialData> getInitialData() async {
    await 2.delay();
    return InitialData();  // the return part must be asynchronous
  }
```

**Comment by fhfuih** [comment]
> For putAsync the [doc](https://github.com/jonataslaw/getx/blob/master/documentation/en_US/dependency_management.md#getputasync) saild:
> 
> > If you want to register an asynchronous instance, you can use Get.putAsync
> 
> which means that returned instance must be asynchronous, not the method you called is async/await, so I think this is why throw error when you call `final data = Get.find<InitialData>();`
> 
> ```
>   Future<InitialData> getInitialData() async {
>     await 2.delay();
>     return InitialData();  // the return part must be asynchronous
>   }
> ```

Thanks @KevinZhang19870314 for the reply. But I don't think that's the reason. Because
1. I succeeded in injecting dependencies this way:
```dart
Future<void> initServices() async {
  Get.put<ApiProvider>(ApiProvider());
  await Get.putAsync<InitialData>(() => Get.find<ApiProvider>().getInitialData());
}
void main() async {
  await initServices();
  runApp(MyApp());
}
```
in which this line `Get.putAsync<InitialData>(() => Get.find<ApiProvider>().getInitialData())` is intact *except that I `await`ed*.
2. It is equivalent that "my function is async" and the return value is asynchronous (i.e. `Future`). Plus, the signature of `putAsync` is `Future<S> putAsync<S>(Future<S> Function() builder, {...})`. So indeed, the return type is a `Future` of concrete data type. (And also it is a valid [Dart syntax](https://dart.dev/codelabs/async-await#working-with-futures-async-and-await) to declare `async` in function signature and return a concrete data object. Dart will automatically wrap it in `Future` like JavaScript. The return type `Future<InitialData>` says everything, or otherwise I would fail the compilation ;))

I guess the problem may be that the *InitialBinding approach does not wait for `putAsync`s to complete*. Even if I modify the gist above to let `dependencies()` be `async`
```dart
Future<void> dependencies() async {
    Get.put<ApiProvider>(ApiProvider());
    await Get.putAsync<InitialData>(() => Get.find<ApiProvider>().getInitialData()); // added await here
  }
```
The problem persists. By simple logging `Get.putAsync(...).then((value) => print(...))`, in my console the `print` results is *after the exception*. 

In fact, the documented examples on `Bindings` happened to not use any `putAsync`s. I guess this part need further clarification or async supports.

**Comment by jonataslaw** [comment]
Flutter from runApp starts building the app synchronously. It is not possible to start an instance asynchronously in initialBinding, because it will be placed at the end of the dart event loop (unless you use a SplashScreen).

**Comment by fhfuih** [comment]
> Flutter from runApp starts building the app synchronously. It is not possible to start an instance asynchronously in initialBinding, because it will be placed at the end of the dart event loop (unless you use a SplashScreen).

I see... Maybe I can look into the SplashScreen then. After all we're going to handle potential API issues.
