### ISSUE TITLE
BindingsBuilder.put()     This method is executed many times

### ISSUE THREAD

**Issue by DizzyYang** [jonataslaw/getx#1513]
Flutter SDK 2.2.1

get: 4.1.4

BindingsBuilder.put()
This method is executed many times
Entering or exiting HTTP has been increasing and changing

         GetPage(
           name: login,
           page: () => LoginPage(),
           binding: BindingsBuilder<LoginLogic>.put(
             (){
               print("double put - LoginLogic");
               return LoginLogic();
             },
           ),
           transition: Transition.fade,
         )

         class LoginLogic extends GetxController {
           final HttpTool _http = Get.put(
             HttpTool(),
             tag: "-${Tool.getUUId()}",
           );
         }

         static String getUUId() {
             return Uuid().v1().replaceAll("-", "");
         }

[GETX] REPLACE ROUTE /
[GETX] NEW ROUTE /login
[GETX] Instance "HttpTool" has been created with tag "-54a0dd00c50c11eba12b8105d51a53ce"
[GETX] Instance "HttpTool" with tag "-54a0dd00c50c11eba12b8105d51a53ce" has been initialized
[GETX] Instance "LoginLogic" has been created
[GETX] Instance "LoginLogic" has been initialized
[GETX] Instance "HttpTool" has been created with tag "-54c13640c50c11eba12b8105d51a53ce"
[GETX] Instance "HttpTool" with tag "-54c13640c50c11eba12b8105d51a53ce" has been initialized

@jasonlaw 
Check the above log to add repeatedly

**Comment by DizzyYang** [comment]
BindingsBuilder.put

This method is executed twice

**Comment by DizzyYang** [comment]
@jonataslaw

**Comment by KevinZhang19870314** [comment]
If `BindingsBuilder.put()` executed many times, why didn't see the log `print("double put - LoginLogic");`?

**Comment by DizzyYang** [comment]
[GETX] REPLACE ROUTE /
[GETX] NEW ROUTE /login
[GETX] Instance "HttpTool" has been created with tag "-54a0dd00c50c11eba12b8105d51a53ce"
[GETX] Instance "HttpTool" with tag "-54a0dd00c50c11eba12b8105d51a53ce" has been initialized
[GETX] Instance "LoginLogic" has been created
[GETX] Instance "LoginLogic" has been initialized
[GETX] Instance "HttpTool" has been created with tag "-54c13640c50c11eba12b8105d51a53ce"
[GETX] Instance "HttpTool" with tag "-54c13640c50c11eba12b8105d51a53ce" has been initialized



Httptool is created repeatedly

**Comment by DizzyYang** [comment]
[getx_examples.zip](https://github.com/jonataslaw/getx/files/6601986/getx_examples.zip)

@jonataslaw @KevinZhang19870314
