### ISSUE TITLE
example_nav2 on web. Navigator.onGenerateRoute was null

### ISSUE THREAD

**Issue by gorkemsari** [jonataslaw/getx#1514]
I have downloaded and run your example_nav2 application on Chrome. So trying it for web.

- Switched to Profile or Products page on Bottom nav bar.
- Refreshed the page (or copy and paste the url to another window) and got below error.
- Refreshing on Home page it is not giving the error.

![image](https://user-images.githubusercontent.com/29121464/120634999-9b8ea780-c474-11eb-85c3-b0485e8cd073.png)

How to solve this problem? Thanks.

**Comment by gorkemsari** [comment]
One more issue about same example

- App started on Home page on Chrome
- Go to Profile (click on bottom nav)
- Go to Products (click on bottom nav)
- Back to Profile by clicking browser's Back button (Profile page is empty, **error1**)
- Back to Home by clicking browser's Back button (Home page is filled)
- Click to browser's forward button (Profile page is still empty)
- Click to browser's forward button (Products page has error, **error2**)
- Click to browser's back button (Profile page has error, **error2**)

**error1:**
![image](https://user-images.githubusercontent.com/29121464/120654007-eebf2500-c489-11eb-972c-96f2544a252b.png)

**error2:**
![image](https://user-images.githubusercontent.com/29121464/120653541-70fb1980-c489-11eb-8938-17506772d92e.png)

**error3:**
![image](https://user-images.githubusercontent.com/29121464/120653810-ba4b6900-c489-11eb-980d-a036bfe7972a.png)

**Comment by ahmednfwela** [comment]
Clone this repo instead of the current one https://github.com/Bdaya-Dev/getx

**Comment by gorkemsari** [comment]
> Clone this repo instead of the current one https://github.com/Bdaya-Dev/getx

Thank you. I have noticed your pr after opening this issue. Im checking it right now.

**Comment by gorkemsari** [comment]
@ahmednfwela 
Seems that browser navigation problem solved. Thank you.

Home or Settings own views not loaded when I select one of them on drawer. Page not changed, only route url updated on AppBar.title. 

if I refresh the page, it lost AppBar.title also.

**Comment by ahmednfwela** [comment]
All of these problems are fixed now in the new PR

**Comment by gorkemsari** [comment]
> All of these problems are fixed now in the new PR

Thank you for your help. It looks very nice.
