### ISSUE TITLE
Get.mediaquery causes constant objects of getxcontroller to be created repeatedly

### ISSUE THREAD

**Issue by DizzyYang** [jonataslaw/getx#1519]
**Flutter SDK 2.2.1**

**Getx 4.1.4**

Get.mediaquery causes constant objects of getxcontroller to be created repeatedly

[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized
[GETX] GOING TO ROUTE /
[GETX] Instance "LaunchLogic" has been created
[GETX] Instance "LaunchLogic" has been initialized
[GETX] GOING TO ROUTE /problem
[GETX] Instance "HttpTool" has been created with tag "-Problem-2ce1dc60c68d11ebbede834a0a5b8ef8"
[GETX] Instance "HttpTool" with tag "-Problem-2ce1dc60c68d11ebbede834a0a5b8ef8" has been initialized
[GETX] Instance "ProblemLogic" has been created
[GETX] Instance "ProblemLogic" has been initialized
[GETX] Instance "HttpTool" has been created with tag "-Problem-2d07b3e0c68d11ebbede834a0a5b8ef8"
[GETX] Instance "HttpTool" with tag "-Problem-2d07b3e0c68d11ebbede834a0a5b8ef8" has been initialized

Looking at the log, you can see that httptool is created repeatedly

I created an example to see the usage and log.

Is it the wrong way I use it?

[getx_examples.zip](https://github.com/jonataslaw/getx/files/6603723/getx_examples.zip)

**Comment by KevinZhang19870314** [comment]
See the `TODO` comment of the code.

routes.dart
```
    GetPage(
      name: problem,
      page: () => ProblemPage(),
      binding: BindingsBuilder.put(
        // TODO: bindings will be called many times during this page's lifecycle
        () => ProblemLogic(),
      ),
    ),
```

problem.dart
```
class ProblemLogic extends GetxController {
  static ProblemLogic get logic => Get.find();
  // TODO: Each time bindings being called, it will put a new HttpTool in getHttp method
  final HttpTool _http = HttpTool.getHttp("Problem");
```

http_tool.dart
```
class HttpTool {
  static HttpTool getHttp(String begin) {
    // TODO: So here to avoid the issue you described, I just
    // make a temp solution here:
    // just put one without tag, and thus it will not created repeatly,
    // so if you want to put with tag, try to re-structure your code here,
   // and Get.find() the tagged one accordingly.
    HttpTool _httpTool;
    try {
      _httpTool = Get.find();
    } catch (e) {
      _httpTool = Get.put(
        HttpTool(),
        // tag: "-$begin-${Tool.getUUId()}",
      );
    }

    return _httpTool;
  }
```

**Comment by DizzyYang** [comment]
I should know what you mean.

Because most of my pages use httptool. So if I want to use tag, I need to change it to a constant value instead of UUID. Is that what you mean?

**Comment by DizzyYang** [comment]
@KevinZhang19870314 

Do you know why get.mediaquery causes the object of getxcontroller to be created repeatedly?

Is there a solution to the conflict?

**Comment by DizzyYang** [comment]
Waiting for reply...

The document has the same usage scenario!

[https://github.com/jonataslaw/getx/blob/master/documentation/en_US/dependency_management.md#getput](url)

### Get.lazyPut
It is possible to lazyLoad a dependency so that it will be instantiated only when is used. Very useful for computational expensive classes or if you want to instantiate several classes in just one place (like in a Bindings class) and you know you will not gonna use that class at that time.

```dart
/// ApiMock will only be called when someone uses Get.find<ApiMock> for the first time
Get.lazyPut<ApiMock>(() => ApiMock());

Get.lazyPut<FirebaseAuth>(
  () {
    // ... some logic if needed
    return FirebaseAuth();
  },
  tag: Math.random().toString(),
  fenix: true
)

Get.lazyPut<Controller>( () => Controller() )
```

**Comment by DizzyYang** [comment]
This problem has been fixed.
