### ISSUE TITLE
[QUESTION] I got this positional argument expected, and I don't know the solution and why..

### ISSUE THREAD

**Issue by digohebat** [jonataslaw/getx#1524]
So this is the first time I use getX to actually pass a data to a new screen, But I always got this.. anyone knows why?
![Screenshot_6](https://user-images.githubusercontent.com/61861426/121184505-5c56c100-c88f-11eb-8acd-89f90b9762c6.png)

This is my code from the second screen that I want to navigate to

`import 'package:flutter/material.dart';
import 'package:get/get.dart';

class PageDetails extends StatefulWidget {
  const PageDetails(Future? future, { Key? key }) : super(key: key);
  

  @override
  _PageDetailsState createState() => _PageDetailsState();
}

class _PageDetailsState extends State<PageDetails> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(child: Column(
          children: <Widget>[
          ],
        )),
      ),
    );
  }
}`

**Comment by jonataslaw** [comment]
Initially, this is not the place to ask questions. Search the community channels to solve your doubts.
Also, in your code is it clear that you need to receive the mandatory parameter `Future? future`

**Comment by jefrisingh** [comment]
Hi @digohebat 

If the parameters are inside the curly braces { } then those are optional parameters either it can be passed or not unless it marked as 'required', all other direct parameters must be passed to it, in your case it's 'Future?' eventhough you marked it nullable you must pass null or value to the function as the argument, Anyhow it's nullable, you can simply move next to 'Key?' parameter inside the curly braces.

:+1:
