### ISSUE TITLE
Snackbar without title

### ISSUE THREAD

**Issue by naumanahmed19** [jonataslaw/getx#1530]
I was using the snack bar without a title after updating to get 4.1.4 I am getting an error. is there are way to null a title as I don't want to display
example:

```dart

    Get.snackbar(title ?? null, message ?? '',
        borderRadius: 3,
        icon: _icon,
        backgroundColor: Colors.black.withOpacity(0.9),
        colorText: Colors.white,
        barBlur: 0.9,
        margin: EdgeInsets.all(5));
```

````
ERROR:flutter/lib/ui/ui_dart_state.cc(213)] Unhandled Exception: 'package:flutter/src/widgets/text.dart': Failed assertion: line 378 pos 10: 'data != null': A non-null String must be provided to a Text widget.
````

**Comment by hy450** [comment]
Get.snackbar('', '',
      backgroundColor: Colors.transparent,
      snackPosition: SnackPosition.BOTTOM,
      titleText: Container(),
      messageText: Center(
          child: Container(
              padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 30),
              decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(20),
                  color: Colors.black87),
              child: Text(
                message,
                style: TextStyle(color: Colors.white),
              ))),
      margin: const EdgeInsets.all(30));

**Comment by naumanahmed19** [comment]
@hy450 thanks
