### ISSUE TITLE
List.clear(),  The controller was not destroyed

### ISSUE THREAD

**Issue by jy6c9w08** [jonataslaw/getx#1534]
Hello everyone,  I have a List,  some image class in it ,and every image have unique ImageController with different tag,
now,I try clear the List, use List.clear(),but the log is not printed controller deleted. so how can I use clear List to deleted the image controller.

```dart
     final illustList = Rx<List<Illust>>([]);
getList().then((value) {
      print("clear List");
      illustList.value.clear();
    }
```

**Terminal**
```
[GETX] Instance "ImageController" with tag "90446323" has been initialized
[GETX] Instance "ImageController" has been created with tag "90453028"
[GETX] Instance "ImageController" with tag "90453028" has been initialized
[GETX] OPEN BOTTOMSHEET: 204838205
[GETX] CLOSE BOTTOMSHEET: 204838205
flutter: clear List
```

**Comment by jonataslaw** [comment]
You can not to use .value with lists.
Read the docs, please

**Comment by jy6c9w08** [comment]
Thanks your reply,I read the docs,I knew the controller will delete when it unused, but i am sure when the list clear,some controller in it will not used anymore.Could you tell me how to delete them(I try use Get.delete,but there many same Controller with different tag,it's not wise).
