### ISSUE TITLE
Nav2 example with login

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#1537]
Hi @ahmednfwela , thanks for your amazing work on the new navigation 2.0. 
I am new to it and wonder how to implement the login and autologin with the framework. Furthermore, it would be great to have a guard gateway to redirect any pages to login page if not authenticated.
Could you showcase that in your nav2 example?
Thank you very much, really appreciate it.

**Comment by ahmednfwela** [comment]
hi @jasonlaw ,I was actually planning on doing that since that use case is very common in production apps
I just need abit of time to study the best way to implement it

**Comment by jasonlaw** [comment]
@ahmednfwela many thanks and looking forward to it.
