### ISSUE TITLE
net::ERR_CERT_AUTHORITY_INVALID Error

### ISSUE THREAD

**Issue by pavane90** [jonataslaw/getx#1543]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
When getting the https server, an error occurs net::ERR_CERT_AUTHORITY_INVALID.

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
...
  @override
  void onInit() {
    httpClient.addRequestModifier<void>((request) {
      request.headers.remove('user-agent');
      return request;
    });

    httpClient.maxRedirects = 3;
    httpClient.timeout = Duration(seconds: 5);
    super.onInit();
  }
...

String url = apiUrl; //https://....

    final Response = await get(url, headers: {
      'Authorization': 'Bearer $token',
      'Accept': 'application/json',
    });

    if (Response.statusCode == 200) {
      ......        
      }
      return _response;
    } else {
      return Future.error(Response);
    }
```

**To Reproduce**
1. I want to connect to the https server.
2. If I specify url and get it, response is null and the browser console displays net::ERR_CERT_AUTHORITY_INVALID.

**Expected behavior**
The response contains data and the status code must be 200.

**Screenshots**
![error](https://user-images.githubusercontent.com/42838956/122007327-ca046f00-cdf2-11eb-9e8d-ffe5e07f3b76.png)

**Flutter Version:**
2.2.0

**Getx Version:**
4.1.4

**Describe on which device you found the bug:**
ex: Chrome (Windows)

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by pavane90** [comment]
If I connect to the same server use Postman, I can get the data normally.
However, an error occurs when using GetConnect.

I'm going to write this [article](https://github.com/jonataslaw/getx/issues/1383#issuecomment-830685527) but the issue was not resolved.

**Comment by pavane90** [comment]
I think this problem has nothing to do with getx. (or not resolvable at getx or flutter level)

It seems to be a problem when developing in a localhost environment. 
https://stackoverflow.com/questions/46349459/chrome-neterr-cert-authority-invalid-error-on-self-signing-certificate-at-loca
https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate
I haven't solved this problem yet, but I'd appreciate it if you could let me know if you know anything.

**Comment by Victor-XHH** [comment]
I think it’s your certificate problem, you can try to remove the certificate and use http directly to see if it is normal

**Comment by jonataslaw** [comment]
remove the 's' letter of your url. 
use `http://`
If you are using localhost
