### ISSUE TITLE
How to obs an enum ? 

### ISSUE THREAD

**Issue by std-c** [jonataslaw/getx#1549]
I try to obs an enum variable but it's seem impossible.

```
enum Status { In, Out }

class AuthController extends GetxController {
  final status = Status.In.obs;
}
```

**Comment by KevinZhang19870314** [comment]
There is no extension for `enum` in GetX, in your case enum variable is just itself, its immutable.

**Comment by jonataslaw** [comment]
> I try to obs an enum variable but it's seem impossible.
> 
> ```
> enum Status { In, Out }
> 
> class AuthController extends GetxController {
>   final status = Status.In.obs;
> }
> ```

Why no?

**Comment by jonataslaw** [comment]
You can look at an enum, just as you wrote it.
As this is not a real issue, I am closing this this
