### ISSUE TITLE
Get.testMode is not working

### ISSUE THREAD

**Issue by arthurpiccoli** [jonataslaw/getx#1554]
**Describe the bug**
When navigating using Get contextless navigation or trying to call Get.context within a test scenario where only the business logic is being tested without a running MaterialApp, instead of this call being ignored and returning null a `Null check operator used on a null value` exception is thrown.

**Reproduction code**
```dart
class FooController extends GetxController {
  navigate() => Get.toNamed('/bar');
}

main() {
  test("Foo Test", () {
    Get.testMode = true;
    final controller = FooController();
    controller.navigate();
  });
}
```
```
Null check operator used on a null value
GlobalKey._currentElement package:flutter/…/widgets/framework.dart:152
GlobalKey.currentContext package:flutter/…/widgets/framework.dart:158
GetNavigation.global package:get/…/src/extension_navigation.dart:1035
GetNavigation.toNamed package:get/…/src/extension_navigation.dart:565
FooController.navigate test/foo_test.dart:11
main.<fn> test/foo_test.dart:18
✖ Foo Test

```
**To Reproduce**
Any time where Get tries to retrieve a context in a scenario where it should be null results in an exception.
This occurs because Get calls a GlobalKey currentContext. The following code shows the framework side of the code:
```dart
BuildContext? get currentContext => _currentElement;
Element? get _currentElement => WidgetsBinding.instance!.buildOwner!._globalKeyRegistry[this];
```

Since WidgetsBinding.instance is null on this case and is being called with a ! operator, a `Null check operator used on a null value` exception is throw. Maybe this is a expected behavior from the Flutter framework and GetX should adapt to it or maybe it's a bug within the framework and the code should look like this:
```dart
BuildContext? get currentContext => _currentElement;
Element? get _currentElement => WidgetsBinding.instance?.buildOwner?._globalKeyRegistry[this];
```

Anyway since this check exists within GetX:
```dart
if (_key.currentContext == null && !testMode) {
      throw """You are trying to use contextless navigation without
      a GetMaterialApp or Get.key.
      If you are testing your app, you can use:
      [Get.testMode = true], or if you are running your app on
      a physical device or emulator, you must exchange your [MaterialApp]
      for a [GetMaterialApp].
      """;
}
```
And ```_key.currentContext == null```will result in an exception instead of a bool, some sort of fix must be done.

**Flutter Version:**
2.2.2

**GetX Version:**
4.1.4

**Comment by arthurpiccoli** [comment]
In order to `Get.testMode` to work, `TestWidgetsFlutterBinding.ensureInitialized()` must be called prior to tests in Flutter 2.2+, so this test should look like this:
```
main() {
  test("Foo Test", () {
    TestWidgetsFlutterBinding.ensureInitialized();
    Get.testMode = true;
    final controller = FooController();
    controller.navigate();
  });
}
```

**Comment by geofferyj** [comment]
How to do this in version 5, both Get.testMode = true and GetTestMode.active=true, doesn't work for navigation, Get.toNamed("someRoute/") fails with GetRoot is not part of the three
