### ISSUE TITLE
Controller is not found when opening GetView with custom binding and tag

### ISSUE THREAD

**Issue by jpChan015** [jonataslaw/getx#1564]
**Describe the bug**
Controller is not found when opening GetView with custom binding and tag even the controller was initialized

```dart
[GETX] GOING TO ROUTE /DetailsScreen
[GETX] Instance "DetailsScreenController" has been created with tag "130"
[GETX] Instance "DetailsScreenController" with tag "130" has been initialized
"Get.lazyPut(()=>DetailsScreenController())"
```

**Error**
```dart
The following message was thrown building Obx(dirty, state: _ObxState#42d72):
"DetailsScreenController" not found. You need to call "Get.put(DetailsScreenController())" or "Get.lazyPut(()=>DetailsScreenController())"
```

**Reproduction code**

**Binding**

```dart
class DetailsPageBinding implements Bindings {
  final String tag;
  @override
  void dependencies() {
    Get.put(DetailsScreenController(), tag: this.tag);
  }

  DetailsPageBinding({this.tag});
}
```

**Opening of GetView**

```dart
Get.to(DetailsScreen(), binding: DetailsPageBinding(tag: '${uniqueTag}'));
```

**GetView**

```dart
class DetailsScreen extends GetView<DetailsScreenController> {

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: _buildAppBar(),
      body: Container(),
    );
  }
}
```

**Flutter Version:**
Flutter 2.0.6 

**Getx Version:**
4.1.4

**Describe on which device you found the bug:**
iPhone X

**Comment by danbo** [comment]
Try the following
```
// pass tag used in the binding's get.put to the details screen
Get.to(DetailsScreen(uniqueTag), binding: DetailsPageBinding(tag: '${uniqueTag}'));
```

```
class DetailsScreen extends GetView<DetailsScreenController> {
  
  late final String uniqueTag; 
  
  // override the default null tag field in the DetailsScreen with the newly passed one:
  String? get tag => this.uniqueTag;

  DetailsScreen(String uniqueTag){
    this.uniqueTag = uniqueTag;
  }

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: _buildAppBar(),
      body: Container(),
    );
  }
}
```

The DetailsScreen uniqueTag parameter could be named but you get the idea.

**Comment by vantruong3289** [comment]
Hi , it is not issue. when you send tag to Controller but GetView not find by tag.How  GetView find Controlle by tag

**Comment by danbo** [comment]
> Hi , it is not issue. when you send tag to Controller but GetView not find by tag.How GetView find Controlle by tag

It is not found because by default any class extending GetView will have a null tag. So, if you put a controller with a tag, and then the view internally calls find(), because the view's defined tag is null, it calls find without a tag and won't find your controller.

The key is to override the tag in your view / screen so it is not null. 

**String? get tag => this.uniqueTag;**

This way, the internal find uses the tag and finds your controller. If you want to a non-constant tag / different instances of same controller, you'll need to pass the tag in when creating the view that will use that controller.

**Comment by VVoodyHong** [comment]
@danbo  Thank you for helpful comment

**Comment by VVoodyHong** [comment]
@danbo Thank you for your helpful comment
