### ISSUE TITLE
How to support Chinese language with scriptCode  Hans and  Hant.

### ISSUE THREAD

**Issue by weishirongzhen** [jonataslaw/getx#1571]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
Chinese has Chinese simplified and  Chinese traditional  map to zh_Hans_CN and zh_Hant_CN.
How Can I provider keys for above language and change Locale with Get.updateLocale()?

**Reproduction code
```
class TranslationService extends Translations {

 static final fallbackLocale = Locale('en');

  @override
  Map<String, Map<String, String>> get keys => {
        'zh': zh,
        'zh_Hans': zh_Hans,
        'zh_Hant': zh_Hant,
        'en': en,
        'ja': ja,
      };
}

const Map<String, String> zh_Hans = {"love": "爱"};
const Map<String, String> zh = {"love": "爱"};
const Map<String, String> zh_Hant = {"love": "愛"};
const Map<String, String> en = {"love": "love"};
const Map<String, String> ja = {"love": "愛する"};
```

supportedLocales  = [
Locale('zh'),
Locale.fromSubtags(languageCode: 'zh',scriptCode: 'Hans'),
Locale.fromSubtags(languageCode: 'zh',scriptCode: 'Hant'),
Locale('en'),
Locale('ja),
]

when I call Get.updateLocale(supportedLocales[i]);  only en,ja,zh is working, how  I can specific  zh_Hans  and  zh_Hant?

**Comment by KevinZhang19870314** [comment]
Please refer to below links to correct your paramters in `Locale` and `Locale.fromSubtags`.

```
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
```

```
  /// Creates a new Locale object.
  ///
  /// The keyword arguments specify the subtags of the Locale.
  ///
  /// The subtag values are _case sensitive_ and must be valid subtags according
  /// to CLDR supplemental data:
  /// [language](https://github.com/unicode-org/cldr/blob/master/common/validity/language.xml),
  /// [script](https://github.com/unicode-org/cldr/blob/master/common/validity/script.xml) and
  /// [region](https://github.com/unicode-org/cldr/blob/master/common/validity/region.xml) for
  /// each of languageCode, scriptCode and countryCode respectively.
```

**Comment by weishirongzhen** [comment]
> Please refer to below links to correct your paramters in `Locale` and `Locale.fromSubtags`.
> 
> ```
> https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
> ```
> 
> ```
>   /// Creates a new Locale object.
>   ///
>   /// The keyword arguments specify the subtags of the Locale.
>   ///
>   /// The subtag values are _case sensitive_ and must be valid subtags according
>   /// to CLDR supplemental data:
>   /// [language](https://github.com/unicode-org/cldr/blob/master/common/validity/language.xml),
>   /// [script](https://github.com/unicode-org/cldr/blob/master/common/validity/script.xml) and
>   /// [region](https://github.com/unicode-org/cldr/blob/master/common/validity/region.xml) for
>   /// each of languageCode, scriptCode and countryCode respectively.
> ```

zh_Hans_CN and zh_Hant_CN were get from device, looks like "get" not support  languageCode_scriptCode_countyCode format,  I change to languageCode_countyCode  it works well, So I migrate get to flutter intl to do it.

**Comment by weishirongzhen** [comment]
Found relevant code here,  ` "${Get.locale!.languageCode}_${Get.locale!.countryCode}") ` could you please add scriptCode support? right now I can made my extension on String to solved it, but official support would be great.
```
String get tr {
    // Returns the key if locale is null.
    if (Get.locale?.languageCode == null) return this;

    // Checks whether the language code and country code are present, and
    // whether the key is also present.
    if (Get.translations.containsKey(
            "${Get.locale!.languageCode}_${Get.locale!.countryCode}") &&
        Get.translations[
                "${Get.locale!.languageCode}_${Get.locale!.countryCode}"]!
            .containsKey(this)) {
      return Get.translations[
          "${Get.locale!.languageCode}_${Get.locale!.countryCode}"]![this]!;

      // Checks if there is a callback language in the absence of the specific
      // country, and if it contains that key.
    } else if (Get.translations.containsKey(Get.locale!.languageCode) &&
        Get.translations[Get.locale!.languageCode]!.containsKey(this)) {
      return Get.translations[Get.locale!.languageCode]![this]!;
      // If there is no corresponding language or corresponding key, return
      // the key.
    } else if (Get.fallbackLocale != null) {
      final fallback = Get.fallbackLocale!;
      final key = "${fallback.languageCode}_${fallback.countryCode}";

      if (Get.translations.containsKey(key) &&
          Get.translations[key]!.containsKey(this)) {
        return Get.translations[key]![this]!;
      }
      if (Get.translations.containsKey(fallback.languageCode) &&
          Get.translations[fallback.languageCode]!.containsKey(this)) {
        return Get.translations[fallback.languageCode]![this]!;
      }
      return this;
    } else {
      return this;
    }
  }
```
