### ISSUE TITLE
Missing Get.arguments and Get.parameters when keyboard show.

### ISSUE THREAD

**Issue by Auramel** [jonataslaw/getx#1578]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
Hello everybody, I have some problems with named routes arguments. So, for example I have pages Partner and PartnerForm.

Routes:
**Partner** /partners/view/:id
**PartnerForm** /partners/update

At first, I am on Partner page, then, I clicked on dropdownmenu and go to PartnerForm page. PartnerForm page has many textfields. When I click on TextField flutter rebuild my app and missing Get.arguments and Get.parameters on previous pages. What can I do to fix this?

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

**Routes.**
```dart
GetPage(
        name: '/partner/view/:id',
        page: () => PartnerScreen.factory(),
        binding: PartnerBindings(),
      ),
      GetPage(
        name: '/partner/statuses',
        page: () => PartnerStatusesScreen.factory(),
        binding: PartnerStatusesBindings(),
      ),
      GetPage(
        name: '/partner/update',
        page: () => PartnerFormScreen.factory('Изменение контрагента'),
        binding: PartnerFormBindigns(),
      ),
      GetPage(
        name: '/partner/create',
        page: () => PartnerFormScreen.factory('Новый контрагент'),
        binding: PartnerFormBindigns(),
      ),
```

**Bindings**
```dart
class PartnerBindings extends Bindings {
  @override
  void dependencies() {
    final String tag = Get.parameters['id'];

    Get.lazyPut<PartnerController>(() => PartnerController(Get.find(tag: tag)), tag: tag);
    Get.lazyPut<PartnerViewModel>(() => PartnerViewModel(), tag: tag);

    Get.lazyPut<PartnerApi>(() => PartnerApi());
    Get.lazyPut<PartnerQuery>(() => PartnerQuery());
  }
}
```

**Partner screen**
```dart
class PartnerScreen extends MVCWidget<PartnerController, PartnerViewModel> {
  PartnerScreen({
    @required PartnerController controller, 
    @required PartnerViewModel viewModel,
  }): super(
    controller: controller,
    viewModel: viewModel,
  );

  factory PartnerScreen.factory() {
    final String tag = Get.parameters['id'];

    return PartnerScreen(
      controller: Get.find(tag: tag),
      viewModel: Get.find(tag: tag),
    );
  }

  Widget build(_) { // }
}
```

**To Reproduce**
1. Open Partner page
2. Click dropdown menu
3. Select "update" item
4. Click on textfield.

**Flutter Version:**
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale ru_RU.UTF-8)
    • Flutter version 2.2.2 at /home/auramel/snap/flutter/common/flutter
    • Framework revision d79295af24 (2 недели назад), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

**Getx Version:**
get: ^4.1.4

**Describe on which device you found the bug:**
ex: Mi 9 SE

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by Auramel** [comment]
Sorry, I'm stupid - problem was in Get.context. I'm using precacheImage in my ViewModel with context from Get.context, so flutter rebuild my app. Close, please, that issue.

**Comment by Auramel** [comment]
@jonataslaw

**Comment by jonataslaw** [comment]
Thanks! Closing
