### ISSUE TITLE
RTL language, direction change to RTL but translated text not updated unless make it default locale

### ISSUE THREAD

**Issue by modekano** [jonataslaw/getx#1585]
**Describe the bug**
The app configured with two language English and Arabic, when change language to Arabic the widget direction change to RTL but the text of Arabic not load, when make default locale  to Arabic the text of Arabic loaded but when change language to English and change it back to Arabic the text of Arabic does not loaded. unless close and open the app again.

**Reproduction code
```dart
 runApp(GetMaterialApp(
    translations: Messages(),
    locale: Locale('ar', 'SA'),
    fallbackLocale: Locale('en', 'US'),
    localizationsDelegates: [
      GlobalMaterialLocalizations.delegate, // uses `flutter_localizations`
      GlobalWidgetsLocalizations.delegate,
      GlobalCupertinoLocalizations.delegate,
    ],
    supportedLocales: <Locale>[Locale('en', 'US'), Locale('ar')],
```

**function used to change the locale**
```dart
class LanguageController extends GetxController {
  LanguagesList languagesList;
  @override
  void onInit() {
    languagesList = new LanguagesList();
    super.onInit();
  }
  var selectedLanguage = Get.locale.languageCode.obs;
  set changeLanguage(String lang) {
    Locale locale = new Locale(lang);
    Get.updateLocale(locale);
    selectedLanguage.value = lang;
  }
}

```

**Expected behavior**
when change to Arabic language UI should change to RTL and load  Arabic text translation.

**Screenshots**

**Flutter Version:**
flutter 2.2

**Getx Version:**
get: ^4.1.4

**Describe on which device you found the bug:**
Huawei S9 Android 9

**Comment by modekano** [comment]
what you mean?

**Comment by yixiaco** [comment]
The localeResolutionCallback attribute can monitor changes in the system language environment

**Comment by modekano** [comment]
I add **localeResolutionCallback** to GetMaterialApp but still same behavior, text not updated but direction change to RTL

```dart
runApp(GetMaterialApp(
    // locale: Get.deviceLocale,
    translations: Messages(),
    locale: Locale('ar'), // Get.devicelocale
    fallbackLocale: Locale('en', 'US'),
    localizationsDelegates: [
      GlobalMaterialLocalizations.delegate, // uses `flutter_localizations`
      GlobalWidgetsLocalizations.delegate,
      GlobalCupertinoLocalizations.delegate,
    ],
    supportedLocales: <Locale>[Locale('en', 'US'), Locale('ar')],
    localeResolutionCallback: (
      Locale locale,
      Iterable<Locale> supportedLocales,
    ) {
      return locale;
    },
```

**Comment by modekano** [comment]
You can close this issue, it working now, the solution is to add:
```dart
localeResolutionCallback: (
      Locale locale,
      Iterable<Locale> supportedLocales,
    ) {
      return locale;
    }, 
```

my problem was after adding localeResolutionCallback I remove country code from messages Map 

```dart
'ar': {
```
```dart
'ar_SA': {
```
this is not match with Locale('ar'),
Thanks

**Comment by panchalAlpit** [comment]
@modekano How to fix this issue, I'm getting some error.
