### ISSUE TITLE
Pass argument with getx on flutter

### ISSUE THREAD

**Issue by tazik561** [jonataslaw/getx#1590]
I am using getx to navigate between pages. I want to send my dummy string  to new page : This is my method :

       Future<dynamic> navigateWithTransition(Widget page,
          {dynamic arguments}) {
        return Get.to(() => page,
            arguments: arguments);
      }

Now I pass my argument to new page like this:

    _navigatorService.navigateWithTransition(
      const PersonalInfoDegreePage(),
      arguments: "test",
    );

But in PersonalInfoDegreePage page

    class PersonalInfoDegreePage extends StatelessWidget {
      const PersonalInfoDegreePage({Key key}) : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        log.info(Get.arguments);
        return Scaffold(

I got  Get.arguments equal **null**. What is my wrong?

    $ flutter doctor
    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_US.UTF-8)
    [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [✓] Chrome - develop for the web
    [✓] Android Studio
    [✓] VS Code (version 1.57.1)
    [✓] Connected device (2 available)
    
    • No issues found!

I am using `get: ^3.26.0`

**Comment by jonataslaw** [comment]
Arguments e Parameters NEED be on initState or onInit
