### ISSUE TITLE
[Get] the improper use of a GetX has been detected. Error

### ISSUE THREAD

**Issue by regenin** [jonataslaw/getx#1596]
Getx works fine and has no issues, but Obx structures fail when I send the data to the other page. I am getting the data on the other page without using obx, but it gives an error when it is obx.  I'm trying to learn getx sorry in advance if i'm wrong.

Home page: 

```
class HomePage extends StatelessWidget {
  final AllCoinController allCoinController = Get.put(AllCoinController());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Obx(
        () => ListView.builder(
          scrollDirection: Axis.vertical,
          itemCount: allCoinController.coinList.length,
          itemBuilder: (context, index) {
            var coin = allCoinController.coinList[index];
            return Padding(
              padding: const EdgeInsets.all(8.0),
              child: GestureDetector(
                onTap: () {
                  Get.to(CoinContent(
                    coin: coin,
                  ));
                },
```

Other Page:

```
class CoinContent extends StatelessWidget {
  final coin;

  CoinContent({@required this.coin});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text(coin.name),
      ),
      body: Obx(
        () => SafeArea(
          child: Center(
            child: Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text(
                    coin.name,
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text(
                    coin.currentPrice.toString(),
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 20,
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: SizedBox(
                    width: 50,
                    height: 50,
                    child: Image.network(coin.image),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by jefrisingh** [comment]
Obx can be used only with Rx(Type) variables in controller, in your other page you are not listening anything form the controller , But in the first page you are getting the value from controller inside obx, this is the reason no error on first page and error on second page, Obx will be used only if you want to listen the data change on a Rx variable in controller, or else you will get this error, To be simple you careated obx listener but you don't mention what to be listened. Just remove obx on second page or try to listen some Rx variable from the controller.

**Comment by regenin** [comment]
> Obx can be used only with Rx(Type) variables in controller, in your other page you are not listening anything form the controller , But in the first page you are getting the value from controller inside obx, this is the reason no error on first page and error on second page, Obx will be used only if you want to listen the data change on a Rx variable in controller, or else you will get this error, To be simple you careated obx listener but you don't mention what to be listened. Just remove obx on second page or try to listen some Rx variable from the controller.

I'm sending the data in the index to the other page with this :  var coin = allCoinController.coinList[index];  i already created a controller for page one. If I want to use the same controller, I can't get [index] and there is a problem. How do you think I can fix this.

**Comment by jefrisingh** [comment]
Instead of sending coin send index to next page,then the second page call the below line of code
`AllCoinController allCoinController = Get.find<AllCoinController>();`
now you have the same controller, and use the index to get the coin, please check the doc's , it's very basic functionality of Getx. you could have lot more from getx by reading the doc's

**Comment by regenin** [comment]
> Instead of sending coin send index to next page,then the second page call the below line of code
> `AllCoinController allCoinController = Get.find<AllCoinController>();`
> now you have the same controller, and use the index to get the coin, please check the doc's , it's very basic functionality of Getx. you could have lot more from getx by reading the doc's

Thank you very much for the help but I was tried this and it was didn't work. It doesn't automatically detect values ​​after using the getx controller. Example: 

```
Text(allCoinController
                            .coinList[index].currentPrice
                            .toString()),
```

"currentPrice" Automatically found without using getx but not showing up after using getx controller, i had to write it myself is this normal?

I mean when I do it as you suggested on the second page, an error like this appears.
```
Text(
                    //coin.currentPrice.toString(),
                    allCoinController.coinList.currentPrice.toString(),
```
error: The getter 'currentPrice' isn't defined for the type 'RxList<dynamic>'. (undefined_getter at [coin_finder] lib\coinContent.dart:35)

But I think it's a bug that I defined on the controller.

```
import 'dart:async';
import 'package:coin_finder/models/btc_eth_bnb_model.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;

class AllCoinController extends GetxController {
  var coinList = [].obs;

  final url = Uri.parse(
      "url value");

  Future callAllCoins() async {
    try {
      final response = await http.get(url);

      if (response.statusCode == 200) {
        List<dynamic> values = [];
        values = allCoinsFromJson(response.body);
        coinList.assignAll(values);

        if (values.length > 0) {
          for (int i = 0; i < values.length; i++) {
            if (values[i] != null) {
              coinList.add(values[i]);
            }
          }
        }
        return coinList;
      } else {
        print(response.statusCode);
      }
    } catch (e) {
      print(e.toString());
    }
  }

  @override
  void onInit() {
    callAllCoins();
    Timer.periodic(Duration(minutes: 5), (timer) => callAllCoins());
    super.onInit();
  }
}

```
Model:

```
import 'dart:convert';

List<AllCoins> allCoinsFromJson(String str) =>
    List<AllCoins>.from(json.decode(str).map((x) => AllCoins.fromJson(x)));

String allCoinsToJson(List<AllCoins> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class AllCoins {
  AllCoins({
    required this.symbol,
    required this.name,
    required this.image,
    required this.currentPrice,
  });

  String symbol;
  String name;
  String image;
  num currentPrice;

  factory AllCoins.fromJson(Map<String, dynamic> json) => AllCoins(
        symbol: json["symbol"],
        name: json["name"],
        image: json["image"],
        currentPrice: json["current_price"],
      );

```

I've been searching for days but couldn't find a solution.

**Comment by jefrisingh** [comment]
```
Text(
                    //coin.currentPrice.toString(),
                    allCoinController.coinList.currentPrice.toString(),
```

cointList is a List, to access currentPrice you need to pass index for the coing, try bellow one


```
class HomePage extends StatelessWidget {
  final AllCoinController allCoinController = Get.put(AllCoinController());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Obx(
        () => ListView.builder(
          scrollDirection: Axis.vertical,
          itemCount: allCoinController.coinList.length,
          itemBuilder: (context, index) {
            var coin = allCoinController.coinList[index];
            return Padding(
              padding: const EdgeInsets.all(8.0),
              child: GestureDetector(
                onTap: () {
                  Get.to(CoinContent(
                    index: index,
                  ));
                },
```

Other page:

```
class CoinContent extends StatelessWidget {
  final int index;
  final AllCoinController allCoinController = Get.find<AllCoinController>();

  CoinContent({@required this.index});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title:  Obx(() => Text(allCoinController.coinList[index].name)),
      ),
      body: Obx(
        () => SafeArea(
          child: Center(
            child: Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text(
                    allCoinController.coinList[index].name,
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text(
                    allCoinController.coinList[index].currentPrice.toString(),
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 20,
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: SizedBox(
                    width: 50,
                    height: 50,
                    child: Image.network(allCoinController.coinList[index].image),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by regenin** [comment]
> ```
> Text(
>                     //coin.currentPrice.toString(),
>                     allCoinController.coinList.currentPrice.toString(),
> ```
> 
> cointList is a List, to access currentPrice you need to pass index for the coing, try bellow one
> 
> ```
> class HomePage extends StatelessWidget {
>   final AllCoinController allCoinController = Get.put(AllCoinController());
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Obx(
>         () => ListView.builder(
>           scrollDirection: Axis.vertical,
>           itemCount: allCoinController.coinList.length,
>           itemBuilder: (context, index) {
>             var coin = allCoinController.coinList[index];
>             return Padding(
>               padding: const EdgeInsets.all(8.0),
>               child: GestureDetector(
>                 onTap: () {
>                   Get.to(CoinContent(
>                     index: index,
>                   ));
>                 },
> ```
> 
> Other page:
> 
> ```
> class CoinContent extends StatelessWidget {
>   final int index;
>   final AllCoinController allCoinController = Get.find<AllCoinController>();
> 
>   CoinContent({@required this.index});
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         centerTitle: true,
>         title:  Obx(() => Text(allCoinController.coinList[index].name)),
>       ),
>       body: Obx(
>         () => SafeArea(
>           child: Center(
>             child: Column(
>               children: [
>                 Padding(
>                   padding: const EdgeInsets.all(8.0),
>                   child: Text(
>                     allCoinController.coinList[index].name,
>                   ),
>                 ),
>                 Padding(
>                   padding: const EdgeInsets.all(8.0),
>                   child: Text(
>                     allCoinController.coinList[index].currentPrice.toString(),
>                     style: TextStyle(
>                       fontWeight: FontWeight.bold,
>                       fontSize: 20,
>                     ),
>                   ),
>                 ),
>                 Padding(
>                   padding: const EdgeInsets.all(8.0),
>                   child: SizedBox(
>                     width: 50,
>                     height: 50,
>                     child: Image.network(allCoinController.coinList[index].image),
>                   ),
>                 ),
>               ],
>             ),
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```

Thank you for your help. I'm trying to get used to Getx, if you have a video tutorial about getx, please send me. Thanks again.
