### ISSUE TITLE
How to use Navigation for a part of screen

### ISSUE THREAD

**Issue by Jamalianpour** [jonataslaw/getx#1598]
Hello, I want to navigate just one part of my screen.
I know I can use Navigator widget for default flutter navigation system but how can I do this with GetX?

**Comment by steven-spiel** [comment]
Use the `GetNavigator` widget and give it a key with an int id (`key: Get.nestedKey(1)`). Then when you need to navigate within that navigator, `Get.to(() => YourWidget(), id: 1)`

**Comment by jonataslaw** [comment]
To use GetNavigator as suggested by @steven-spiel or use GetRouterOutlet (check nav2 example)
