### ISSUE TITLE
Unwanted space carried by Obx

### ISSUE THREAD

**Issue by lalitjarwal** [jonataslaw/getx#1600]
```dart
Column(
children:[
OtherChild(),
Obx(
            () => controller.dropdownValue.value == 'Other'
                ? TextFormField(
                    decoration: decoration.copyWith(hintText: 'Account Name'),
                  )
                : Container(),
          ),
OtherChild(),
])
```
I am using this structure . As shown TextFormField appear on screen conditionally but Obx carries some space when TextFormField is hidden.

Note : I have latest version of Get.

**Comment by abinvp** [comment]
It doesn't look like an issue with GetX. I think your column is enforcing some constraints on the container. You can try two things.

1. Replace `Container()` with a SizedBox()
2. Set the `mainAxisSize` of column to `MainAxisSize.min`

```dart
Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        OtherChild(),
        Obx(
          () => controller.dropdownValue.value == 'Other'
              ? TextFormField(
                  decoration: decoration.copyWith(hintText: 'Account Name'),
                )
              : SizedBox(),
        ),
        OtherChild(),
      ],
    );

**Comment by lalitjarwal** [comment]
Ya I got it somehow the problem is with column.

**Comment by lalitjarwal** [comment]
Ya I got it somehow the problem is with column.

**Comment by lalitjarwal** [comment]
Closing because not an issue with GetX
