### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by prasoonallflit** [jonataslaw/getx#1601]
../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-3.3.0/lib/src/get_main.dart:389:43: Error: No named parameter with the name 'shadowThemeOnly'.
      theme: Theme.of(key.currentContext, shadowThemeOnly: true),
                                          ^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/theme.dart:106:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {

**Comment by jonataslaw** [comment]
You are using a legacy version, update your dependencies
