### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by Azzeccagarbugli** [jonataslaw/getx#1602]
Hi, I was using the new navigator system developer by @ahmednfwela and I was not having any issue until today.

Indeed this morning when I ran the `flutter pub get packages` command I got the following issue:

```
Restarted application in 108ms.
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized
GetInformationParser: route location: /
[GETX] GOING TO ROUTE /
[GETX] Instance "NavigationController" has been created
[GETX] Instance "NavigationController" has been initialized
Root RouterOutlet: ======GetNavConfig=====
currentTreeBranch: [GetPage<dynamic>("/", [<'/'>], null)]
currentPage: GetPage<dynamic>("/", [<'/'>], null)
======GetNavConfig=====

════════ Exception caught by widget library ══════════════════
The following assertion was thrown:
The Navigator.pages must not be empty to use the Navigator.pages API

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 909:28       get current
packages/flutter/src/widgets/navigator.dart 3563:33                      <fn>
packages/flutter/src/widgets/navigator.dart 3579:14                      didUpdateWidget
packages/flutter/src/widgets/framework.dart 4761:57                      update
packages/flutter/src/widgets/framework.dart 3350:14                      updateChild
...
════════════════════════════════════════════════════════════
```

I can't really understand what's going on and above all I'm not able to fix the problem at all. The code is really similar to the one showed in the [navigation_example_v2](https://github.com/jonataslaw/getx/tree/master/example_nav2).

I don't know if any of the PRs merged broke something under the hood.

In the `pubspec.yaml` the dependency is installed using `git`:

```
get:
    git: https://github.com/jonataslaw/getx.git
```

Maybe @ahmednfwela could better understand this.

Thanks in advance 🙏🏻

**Comment by ahmednfwela** [comment]
Does it work with the get version from here? https://github.com/Bdaya-Dev/getx

**Comment by Azzeccagarbugli** [comment]
> Does it work with the get version from here? https://github.com/Bdaya-Dev/getx

I just tried that but unfortunately didn't work, I really have no clue about what's going on

**Comment by ahmednfwela** [comment]
Then can you give me a minimal reproduction of the error ?

**Comment by Azzeccagarbugli** [comment]
I'm working on this to give you a minimal repository to check out the error, sorry for the delay!

**Comment by Azzeccagarbugli** [comment]
> Then can you give me a minimal reproduction of the error ?

I just made public the [repository](https://github.com/Azzeccagarbugli/getx_navigation), is not so minimal but you can easily reproduce the issue!

**Comment by Azzeccagarbugli** [comment]
@ahmednfwela do you have any idea?

**Comment by ahmednfwela** [comment]
yes, I think I know the issue
try putting GetMaterialApp directly to runApp

**Comment by Azzeccagarbugli** [comment]
> yes, I think I know the issue

Well, nice I guess!

> try putting GetMaterialApp directly to runApp

I tried in the following way:

```dart
runApp(GetMaterialApp(
    home: MyAngelEvo(),
));
```

But that's what I get, I just cant' understand 

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [LabeledGlobalKey<NavigatorState>#bb4e5] was used by multiple widgets. The parents of those widgets were:
- Builder
- Directionality(textDirection: ltr)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
packages/flutter/src/widgets/framework.dart 2778:13                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
packages/flutter/src/widgets/framework.dart 2778:13                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
packages/flutter/src/widgets/framework.dart 2725:19                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Multiple widgets used the same GlobalKey.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget library ════════════════════════════════════
The following assertion was thrown:
The Navigator.pages must not be empty to use the Navigator.pages API

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 909:28       get current
packages/flutter/src/widgets/navigator.dart 3563:33                      <fn>
packages/flutter/src/widgets/navigator.dart 3579:14                      didUpdateWidget
packages/flutter/src/widgets/framework.dart 4761:57                      update
packages/flutter/src/widgets/framework.dart 3350:14                      updateChild
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widget library ════════════════════════════════════
The Navigator.pages must not be empty to use the Navigator.pages API
════════════════════════════════════════════════════════════════════════════════
2
[GETX] CLOSE TO ROUTE /

════════ Exception caught by widgets library ═══════════════════════════════════
Multiple widgets used the same GlobalKey.
════════════════════════════════════════════════════════════════════════════════

```

**Comment by Azzeccagarbugli** [comment]
@ahmednfwela I have been trying to isolate even more the issue and I create a new branch on the repository which takes even more inspiration from the `navigation_example_v2` but I got another strange error:

```
[GETX] GOING TO ROUTE /home/products
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/window.dart:130:13
false
"Receives old navigator update in a router application. This can happen if you use non-router versions of MaterialApp/CupertinoApp/WidgetsApp together with the router versions of them."
    at Object.throw_ [as throw] (http://localhost:53133/dart_sdk.js:5041:11)
    at Object.assertFailed (http://localhost:53133/dart_sdk.js:4980:15)
    at _engine.EngineSingletonFlutterWindow.new.handleNavigationMessage (http://localhost:53133/dart_sdk.js:172766:32)
    at handleNavigationMessage.next (<anonymous>)
    at runBody (http://localhost:53133/dart_sdk.js:37422:34)

```

At this point I can't really understand why each time I get a new issue from the navigator. And above all I can't explain to myself why this was working so smooth just a week ago 🥲

**Comment by jasonlaw** [comment]
Hi @ahmednfwela ,

When I do this, the first page always route to homeView, even those the isAuthenticated  = false.

~~~dart
 runApp(
    GetMaterialApp.router(
      title: 'Application',
      getPages: Routes.routes,
      routeInformationParser: GetInformationParser(
        initialRoute:
            App.identity.isAuthenticated ? Routes.homeView : Routes.loginView,
      ),
      routerDelegate: GetDelegate(
        backButtonPopMode: PopMode.History,
        preventDuplicateHandlingMode:
            PreventDuplicateHandlingMode.PopUntilOriginalRoute,
      ),
      builder: AppUtils.responsive,
    ),
  );
~~~

Could this be related to the problem as well?
FYI, my homeView = "/".

Thanks.

**Comment by ahmednfwela** [comment]
the initial route should always be constant, and you can introduce route guards by overriding get delegate

**Comment by jasonlaw** [comment]
Thanks for the prompt reply, do you mind give me some example code?
Thank you very much.

**Comment by Azzeccagarbugli** [comment]
> Hi @ahmednfwela ,
> 
> When I do this, the first page always route to homeView, even those the isAuthenticated = false.
> 
> ```dart
>  runApp(
>     GetMaterialApp.router(
>       title: 'Application',
>       getPages: Routes.routes,
>       routeInformationParser: GetInformationParser(
>         initialRoute:
>             App.identity.isAuthenticated ? Routes.homeView : Routes.loginView,
>       ),
>       routerDelegate: GetDelegate(
>         backButtonPopMode: PopMode.History,
>         preventDuplicateHandlingMode:
>             PreventDuplicateHandlingMode.PopUntilOriginalRoute,
>       ),
>       builder: AppUtils.responsive,
>     ),
>   );
> ```
> 
> Could this be related to the problem as well?
> FYI, my homeView = "/".
> 
> Thanks.

I think that this was another kind of issue. Maybe you should open a new one, and for sure the title of this one isn't particularly clear, my bad

**Comment by jasonlaw** [comment]
> > Hi @ahmednfwela ,
> > When I do this, the first page always route to homeView, even those the isAuthenticated = false.
> > ```dart
> >  runApp(
> >     GetMaterialApp.router(
> >       title: 'Application',
> >       getPages: Routes.routes,
> >       routeInformationParser: GetInformationParser(
> >         initialRoute:
> >             App.identity.isAuthenticated ? Routes.homeView : Routes.loginView,
> >       ),
> >       routerDelegate: GetDelegate(
> >         backButtonPopMode: PopMode.History,
> >         preventDuplicateHandlingMode:
> >             PreventDuplicateHandlingMode.PopUntilOriginalRoute,
> >       ),
> >       builder: AppUtils.responsive,
> >     ),
> >   );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could this be related to the problem as well?
> > FYI, my homeView = "/".
> > Thanks.
> 
> I think that this was another kind of issue. Maybe you should open a new one, and for sure the title of this one isn't particularly clear, my bad

sure no problem. thanks.

**Comment by Azzeccagarbugli** [comment]
> @ahmednfwela I have been trying to isolate even more the issue and I create a new branch on the repository which takes even more inspiration from the `navigation_example_v2` but I got another strange error:
> 
> ```
> [GETX] GOING TO ROUTE /home/products
> Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/window.dart:130:13
> false
> "Receives old navigator update in a router application. This can happen if you use non-router versions of MaterialApp/CupertinoApp/WidgetsApp together with the router versions of them."
>     at Object.throw_ [as throw] (http://localhost:53133/dart_sdk.js:5041:11)
>     at Object.assertFailed (http://localhost:53133/dart_sdk.js:4980:15)
>     at _engine.EngineSingletonFlutterWindow.new.handleNavigationMessage (http://localhost:53133/dart_sdk.js:172766:32)
>     at handleNavigationMessage.next (<anonymous>)
>     at runBody (http://localhost:53133/dart_sdk.js:37422:34)
> ```
> 
> At this point I can't really understand why each time I get a new issue from the navigator. And above all I can't explain to myself why this was working so smooth just a week ago 🥲

@ahmednfwela I moved, as you suggested the `GetMaterialApp.router` in the `runApp`, but when I move to a page to the other this error _(the one that I linked above)_ appears and Flutter throws an exception on this point: 

<img width="654" alt="Screenshot 2021-07-09 at 14 29 28" src="https://user-images.githubusercontent.com/16477661/125077986-137a6e00-e0c2-11eb-95ef-90f7551bc94b.png">

**Comment by ahmednfwela** [comment]
I believe this is due to having `reportsRouteUpdateToEngine: true` in the GetNavigator, instead it should false for ALL navigators except the one in the GetDelegate
This was because of the change in this commit: https://github.com/jonataslaw/getx/commit/22ae643cc5298f74d5de367bf1927dd85877a488
```dart
/// Whether this navigator should report route update message back to the
  /// engine when the top-most route changes.
  ///
  /// If the property is set to true, this navigator automatically sends the
  /// route update message to the engine when it detects top-most route changes.
  /// The messages are used by the web engine to update the browser URL bar.
  ///
  /// If the property is set to true when the [Navigator] is first created,
  /// single-entry history mode is requested using
  /// [SystemNavigator.selectSingleEntryHistory]. This means this property
  /// should not be used at the same time as [PlatformRouteInformationProvider]
  /// is used with a [Router] (including when used with [MaterialApp.router],
  /// for example).
  ///
  /// If there are multiple navigators in the widget tree, at most one of them
  /// can set this property to true (typically, the top-most one created from
  /// the [WidgetsApp]). Otherwise, the web engine may receive multiple route
  /// update messages from different navigators and fail to update the URL
  /// bar.
  ///
  /// Defaults to false.
  final bool reportsRouteUpdateToEngine;
```

**Comment by ahmednfwela** [comment]
@jonataslaw maybe we can add it as a parameter in the `GetNavigator`'s constructor and make it false by default
