### ISSUE TITLE
Using Get.to with normal route has bug on passing parameter

### ISSUE THREAD

**Issue by broccolism** [jonataslaw/getx#1607]
**Describe the bug** and **Screenshots**
I made a starter app using `Get.to()` and normal route (not named route).
It has a bug when I write the code without arrow function like `Get.to(ThirdPage())`,
but it works when I write the code with arrow function like `Get.to(() => ThirdPage())`.

Below is what happened using code `Get.to(ThirdPage())`, instead of `Get.to(() => ThirdPage())`.

https://user-images.githubusercontent.com/45515332/124577129-ed698980-de87-11eb-917e-321435293711.mov

I know it shows a warning to use `Get.to(() => ThirdPage())` instead of `Get.to(ThirdPage())` like below screen shot, but I wanna know if this is intended or not. Cause I think this looks quite weird.
![image](https://user-images.githubusercontent.com/45515332/124577523-4e915d00-de88-11eb-98b4-4ce8e3b28194.png)

Thanks.

**Reproduction code

```dart

class FirstPage extends StatelessWidget {
  final controller = StringController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            "Page1",
            style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold),
          ),
          ElevatedButton(
            onPressed: () async {
              String result = await Get.to(SecondPage());
              controller.change(result);
            },
            child: Text(
              "Move to Page2",
              style: TextStyle(fontSize: 20),
            ),
          ),
          Obx(
            () => Text(
              controller.str.value.length > 0
                  ? "Got ${controller.str.value} from Page2"
                  : "Got nothing.",
              style: TextStyle(fontSize: 20),
            ),
          ),
          Container(height: 30),
          ElevatedButton(
            onPressed: () {
              Get.to(ThirdPage(), arguments: controller.str.value);
            },
            child: Text(
              "Move to Page3",
              style: TextStyle(fontSize: 20),
            ),
          ),
        ],
      )),
    );
  }
}

```

**Expected behavior**
I think it should show what I got from input field (in the 2nd page),
in the 3rd page at **_the first time I enter there._**

**Flutter Version:**
Flutter 2.2.3 • channel stable

**Getx Version:**
4.1.4

**Describe on which device you found the bug:**
iPhone 12 Pro Max (ios emulator)

**Comment by jonataslaw** [comment]
When you use arrow functions, you postpone widget creation until the appropriate time. It is for this reason (and others like discarding controllers) that we recommend using Get.to(()=> unless you are sure you do not have asynchronous activities.
This will be changed for dialogs and BottomSheets as well, everyone will be recommended to use arrow functions, and in a later version this will be the default.

**Comment by broccolism** [comment]
@jonataslaw 
Greate! I got it.
Then, should we change some parts of documentations with example code using `Get.to(...)` instead of `Get.to(() => ...)` ?

**Comment by jonataslaw** [comment]
Perhaps we will update the documentation in the future, or just a disclaimer about expected behavior for each type of use.
So closing this.
