### ISSUE TITLE
Unable to make the basic flutter widget_test working with GetX

### ISSUE THREAD

**Issue by evaisse** [jonataslaw/getx#1609]
Hello, 

I have a basic counter demo application, from the demo flutter application, and the demo GetX counter application.
I just add a 3 pages step navigation to test the routing

The whole tiny app is tested trough a widget test :
https://github.com/evaisse/demo-flutter-app-widget-tester/blob/master/test/widget_test.dart

I did **succeed to test it with a "classic" flutter approach**, statefullwidgets, setSate & Navigator.
But **failed to test it with GetX**...

You can see the builds here, or simply test if from the repo : https://github.com/evaisse/demo-flutter-app-widget-tester

There is a build which is working fine here (using classic setState NavigationV1 flutter) on branch `feature/base-widget-tests` :  🆗   https://travis-ci.com/github/evaisse/demo-flutter-app-widget-tester/builds/232043075

And the same app with GetX here, with the same test, where the build is failing at the very first expectation on the branch `feature/getx-widget-tests` : ⚠️  https://travis-ci.com/github/evaisse/demo-flutter-app-widget-tester/builds/232042972

https://github.com/evaisse/demo-flutter-app-widget-tester/blob/feature/base-widget-tests/test/widget_test.dart#L20

Seems like with GetX I miss something from the beginning, the main differences between the 2 implementation : 
- usage of GetX .toNamed() routing system
- usage of Stateless widgets with GetX Controller & observer.

I did not found any real documentation hints about testing in the GetX world, did I missed it ?

**Comment by jonataslaw** [comment]
Remove home property of GetMaterialApp, and use initialRoute.

**Comment by evaisse** [comment]
Hello Jonny, even with this, it does not pass the first expectation : 
https://travis-ci.com/github/evaisse/demo-flutter-app-widget-tester/builds/232130534
https://github.com/evaisse/demo-flutter-app-widget-tester/commit/47c8f9df028e4eedc58d6f62d12e006d82bf6cd4

What's the difference between `home` and `initialRoute` for GetX ?

**Comment by jonataslaw** [comment]
You are confusing named routes with unnamed routes. You cannot use "home" on named routes.
Check how to test widgets on routes here:

https://github.com/jonataslaw/getx/blob/master/test/navigation/get_main_test.dart#L18
