### ISSUE TITLE
[Nav2] Switching initial route

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#1618]
Hi @ahmednfwela ,

For switching initial route as following:
~~~dart
 runApp(
    GetMaterialApp.router(
      title: 'Application',
      getPages: Routes.routes,
      routeInformationParser: GetInformationParser(
        initialRoute:
            App.identity.isAuthenticated ? Routes.homeView : Routes.loginView,
      ),
      routerDelegate: GetDelegate(
        backButtonPopMode: PopMode.History,
        preventDuplicateHandlingMode:
            PreventDuplicateHandlingMode.PopUntilOriginalRoute,
      ),
      builder: AppUtils.responsive,
    ),
  );
~~~

Referring to your suggestion before:
`the initial route should always be constant, and you can introduce route guards by overriding get delegate`

Sorry I am not too clear how to implement that, could you please provide me some example code? Maybe best is to have that example as part of the Nav2 example. 

Thank you very much.

**Comment by jonataslaw** [comment]
One suggestion, if that won't complicate your architecture: use Middlewares to control the flow of routes.
onPageCalled or onPageRedirect do this. I find it much easier to add a Middleware to the home that always redirects to Login if the user is not logged in. But this only works well if you use named routes, and Bindings, otherwise you can try something generic

**Comment by ahmednfwela** [comment]
The best approach I have found is to override `GetDelegate.pushHistory`, by first checking if the user is allowed to go to the 
route in the parameter, if yes, we call `super.pushHistory`, if not, we can completely stop the navigation, or pass a different route to `super.pushHistory` (e.g. login route)

**Comment by ahmednfwela** [comment]
I was thinking of standardizing this by adding a new special middleware specific to the GetDelegate, similar to Angular's RouteGuards

**Comment by jasonlaw** [comment]
Hi @ahmednfwela , thank you very much for the clarification. Btw, the specific middleware idea sound really nice, after all this is the reason we are using the framework, to simplify the work. Thanks again.

**Comment by ahmednfwela** [comment]
also I still haven't forgotten about https://github.com/jonataslaw/getx/issues/1537
I have just been a little busy but I will start working on it soon
