### ISSUE TITLE
How to manually assign values to a future?

### ISSUE THREAD

**Issue by mrgithub** [jonataslaw/getx#1626]
If I have a variable as the following then how do I add/insert values manually?:

final myVar = Future.value(<String?>[null, null, null]).obs

I want to be able to set a value e.g.        myVar.value[0] = "hello"; //this doesn't work

**Comment by steven-spiel** [comment]
This is not specific to `getx` and stackoverflow may be your best bet. Paste a link to the question and I might be able to help you there. Please add more details, though. What is your use case? What do you expect to happen once you set `myVar.value[0]`?

**Comment by jonataslaw** [comment]
With GetX you have observables and you don't need to work with futures directly. Maybe using append with StateMixin is something you might be looking for.
Try help in community chats.
