### ISSUE TITLE
Stream to Obs conversion

### ISSUE THREAD

**Issue by Rubywai** [jonataslaw/getx#1634]
Firebase and some libraries are usually use stream.
GetX use reactive pattern for obs.
So, I think we should have a  function of stream to obs conversion easily.

**Comment by steven-spiel** [comment]
You can use `.bindStream`! 

If you have a stream like `Stream<User> userStream`, you could do something like:

```dart
final Rx<User?> user = Rx<User?>(null).bindStream(userStream);
```

**Comment by jonataslaw** [comment]
Thanks @steven-spiel  

And yeah, you could to use bindStream

```dart
final count = 0.obs;

void onInit(){
  count.bindStream(yourFirebaseStream);
  super.onInit();
}
```

**Comment by Rubywai** [comment]
Thank you very much
