### ISSUE TITLE
为什么 get的国际化在BottomNavigationBarItem中不起作用？

### ISSUE THREAD

**Issue by fbenpao** [jonataslaw/getx#1636]

**Comment by fbenpao** [comment]
Why does the text in the bottom navigation bar not work when I use getx internationalization

**Comment by fbenpao** [comment]
Why does the text in the bottom navigation bar not work when I use getx internationalization

**Comment by mokai** [comment]
看看BottomNavigationBarItem的初始化是不是写在initState中了
