### ISSUE TITLE
Controller don’t close  when the keyboard appear

### ISSUE THREAD

**Issue by AutoJiang** [jonataslaw/getx#1638]
Controller don’t close  when the keyboard appear
Step:
1. Get.to() into a page witch has a AppBar.
2. The page has a TextField and the TextEditingController is in the controller.
3. Then tap the TextField, the keyboard appears.
4. Input some words.
5. Tap back button or Get.back().   
6. Go to the page again.
You will see value is still here. means  the  contronler  was not closed.

I found the problem in this code.

Get Version : 4.1.4
Line 116  in  default_route.dart file

Get.reference = reference;

Two things are about to happen when  Get.back():
1. The keyboard will disappear
2. The page will pop

buildPage() will be executed some time when the keyboard disappears, and Get.reference current is not correct.

it cause  this
if (Get.reference != reference) { // false
  GetInstance().removeDependencyByRoute("$reference");
}
 Missed an opportunity to be removed

I think “Get.reference = reference” should not be executabled many time.

And I just do this changes

var firstBuild = true;
@override
Widget buildPage(
  BuildContext context,
  Animation<double> animation,
  Animation<double> secondaryAnimation,
) {
  //   Get.reference = settings.name ?? routeName;
  if(isFirstBuild){
    Get.reference = reference;
    isFirstBuild = false;
  }
  …
}

The problem is solved

But I think you have a more elegant way

**Comment by CoderXiaoming** [comment]
Interim solution, delete the following from the project:
Get.context
Get.width
Get.height
Get.size
...

@AutoJiang

**Comment by jonataslaw** [comment]
Fixed on lastest version
