### ISSUE TITLE
RouterOutlet Modular similar on GETX

### ISSUE THREAD

**Issue by MarcoGolin** [jonataslaw/getx#1639]
I need a similar behavior of the Modular RouterOutlet in Getx, I want to use flutter's navigation rails, and load the modules only when needed

Preciso de um comportamento similar do RouterOutlet do Modular no Getx, quero usar o navigation rails do flutter, e carregar os modulos somente cuando preciso

**Comment by ahmednfwela** [comment]
Hi @MarcoGolin, can you further explain exactly what you want ?

**Comment by jonataslaw** [comment]
Check the nav2 example in this repo

**Comment by MarcoGolin** [comment]
> Check the nav2 example in this repo


thank you, that's what I was looking for
