### ISSUE TITLE
Observable of class instance doesn't trigger listeners when instance properties change

### ISSUE THREAD

**Issue by giann** [jonataslaw/getx#1648]
This part of the documentation suggests that it's possible to observe the changes of a object instance properties:

> or you can convert the entire class to be an observable
> ```dart
> class User {
>   User({String name, int age});
>   var name;
>   var age;
> }
> 
> // when instantianting:
> final user = User(name: "Camila", age: 18).obs;
> ```

But with this test it seems only a change of the object instance itself triggers something:
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:get/get.dart';

class A {
  int a = 1;
  String b = 'hello';
  List<int> c = [1,2,3];
}

void main() {
  test('observable of object', () {
    var a = A();
    var o = a.obs;

    ever(o, (value) => print('change occured: ${value != null ? (value as A).a : null}'));

    o.value.a = 10; // Doesn't trigger
    o.value = A(); // Triggers
  });
}
```

Is this intended? If so we should maybe update [the documentation](https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md) to reflect this.

**Comment by jonataslaw** [comment]
Well that's expected behavior.
Dart, like other languages, uses the same object to sign a different property, unless you use copyWith.
I'll see if this can be made clearer, but I don't believe common sense leads to that conclusion.
As it was a question, I'm closing this
