### ISSUE TITLE
Documentation or example for GetRouterOutlet since 4.2.0 was released.

### ISSUE THREAD

**Issue by KevinZhang19870314** [jonataslaw/getx#1651]
Hi first conguralations for the release of GetX 4.2.0!

And I see the GetRouterOutlet was added in 4.2.0 changelog, but I can't see the document or example about GetRouterOutlet, am i missing it? If not, please help to doc it, thanks in advance!

**Comment by ahmednfwela** [comment]
there is an example in `example_nav2` directory, also I am working on a medium article to explain the new navigation system.

**Comment by ahmednfwela** [comment]
duplicate of https://github.com/jonataslaw/getx/issues/1643

**Comment by jonataslaw** [comment]
Thanks @ahmednfwela
