### ISSUE TITLE
How to close a specific dialog?

### ISSUE THREAD

**Issue by SuporteSysrs01** [jonataslaw/getx#1657]
Is there a way to close a specific dialog in my stack?

I have a function that opens a loading dialog, which is undismissable. While that function is running, some other dialogs may open. Is there any way I can specifically close that first "loading" dialog? Using `Get.back()` doesn't work as I need those extra dialogs to stay open but only close that first one.

I tried looking in the documentation and couldn't find anything. I thought the "name" parameter in `Get.dialog` could help but also didn't find a way to close it that way.

Thanks!

**Comment by SuporteSysrs01** [comment]
I don't know if this is the right approach but I was able to resolve the issue by creating a route and using `Get.removeRoute` to remove the specific dialog.

```dart
final route = GetDialogRoute(
  pageBuilder: (_, __, ___) => MyLoadingDialog(),
  barrierDismissible: false,
);
Navigator.of(Get.context).push(route);

...

Get.removeRoute(route);
```

With this I was able to push 3 dialogs and only 'pop' the first 2 while keeping the one on top.

**Comment by NoldyNayoan** [comment]
[SuporteSysrs01](https://github.com/SuporteSysrs01)
YES! This is the solution for multiple Loading Dialog that can be closed simply by specifying the route generated by GetDialogRoute. 
This kind of solution should be included in the official documentation of GetX Route Management. Because Loading dialog is one of the ingredients of a good application.
Thanks SuporteSysrs0

**Comment by DonnyDevIT** [comment]
Thanks, helped a lot.
i agree, should be included in docs

**Comment by emirhankolver** [comment]
Hey there!   

I squashed this problem by giving our dialog a custom name. Now you can open a whole bunch of different dialogs at once and close them one by one.  

Here's the magic:

```dart
static showProgressDialog({String name = "progress-dialog"}) {
  Get.dialog(
    const Center(...),
    routeSettings: const RouteSettings(
      name: name,
    ),
  );
}

void hideProgress() {
  Navigator.of(Get.context!).popUntil((route) =>
      route.settings.name != "progress-dialog");
}
```

**Comment by emirhankolver** [comment]
Hey there!   

I squashed this problem by giving our dialog a custom name. Now you can open a whole bunch of different dialogs at once and close them one by one.  

Here's the magic:

```dart
static showProgressDialog({String name = "progress-dialog"}) {
  Get.dialog(
    const Center(...),
    routeSettings: const RouteSettings(
      name: name,
    ),
  );
}

static hideProgressDialog({String name = "progress-dialog"}) {
  if (Get.context != null) {
    Navigator.of(Get.context!).popUntil((route) {
      return route.settings.name != name;
    });
  }
}
```
