### ISSUE TITLE
not able to find GetxService after updating to 4.2.3 

### ISSUE THREAD

**Issue by rmControls** [jonataslaw/getx#1660]
Hello,

After upgrading Getx package I am unable to find GetxService. 
I initialized GetXService like this in my main function.
```dart
Get.lazyPut<AppService>(()=>AppService());
```

somehow it finds it in my first screen... 
on second screen I have controller which tries to find it and I am getting error..

```dart
Class SecondController extends GetxController{
final AppService _service = Get.find();  //getting error at runtime here
}
```

error message....
`"AppService" not found. You need to call "Get.put(AppService())" or "Get.lazyPut(()=>AppService())"`

Also I checked the log in terminal, it does close all the services and delete it from memory....

 seems like it is a bug with latest version....

**Comment by jonataslaw** [comment]
GetxService is working properly.
https://github.com/jonataslaw/getx/blob/master/test/instance/get_instance_test.dart#L117

This is a problem with your code.
If you believe this is an issue, open one with the problem reproduction code

**Comment by ahmednfwela** [comment]
change your code to this:
```dart
Class SecondController extends GetxController{
AppService get _service => Get.find();  //getting error at runtime here
}
```
