### ISSUE TITLE
"Null check operator used on a null value"  after updating to 4.2.3

### ISSUE THREAD

**Issue by devchenli** [jonataslaw/getx#1661]
**"Null check operator used on a null value"  after updating to 4.2.3**

```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building Directionality(textDirection: ltr):
Null check operator used on a null value

The relevant error-causing widget was: 
  Directionality ......flutter/.pub-cache/hosted/pub.dartlang.org/get-4.2.3/lib/get_navigation/src/root/get_material_app.dart:308:24
When the exception was thrown, this was the stack: 
#0      PageRedirect.page (package:get/get_navigation/src/routes/route_middleware.dart:196:50)
#1      GetMaterialApp.generator (package:get/get_navigation/src/root/get_material_app.dart:198:73)
#2      _WidgetsAppState._onGenerateRoute (package:flutter/src/widgets/app.dart:1221:37)
#3      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:4155:46)
#4      Navigator.defaultGenerateInitialRoutes (package:flutter/src/widgets/navigator.dart:2835:28)
...
====================================================================================================
```

source code position :
```
......
 builder: (context, child) {
                return Directionality(
                  textDirection: textDirection ??
                      (rtlLanguages.contains(Get.locale?.languageCode)
                          ? TextDirection.rtl
                          : TextDirection.ltr),
                  child: builder == null ? child! : builder!(context, child),
                );
......
```

**Flutter Version:**
Channel stable, 2.2.3

**Getx Version:**
v4.2.3

**Describe on which device you found the bug:**
Any Phone

**Comment by jonataslaw** [comment]
Please, provide a reproduce code

**Comment by slorop41314** [comment]
Also got this issue @jonataslaw  in version 4.3.0. 

Run on iphone 11 simulator and directly got this error

**Comment by wilz05** [comment]
Same here getting error after migrating from   version 4.1.4 to 4.3.0.

```
The following assertion was thrown building Directionality(textDirection: ltr):
A GlobalKey was used multiple times inside one widget's child list.

The offending GlobalKey was: [LabeledGlobalKey<NavigatorState>#1feae Key Created by default]
The parent of the widgets with that key was: Directionality
  textDirection: ltr
The first child to get instantiated with that key became: Navigator-[LabeledGlobalKey<NavigatorState>#1feae Key Created by default]
  dirty
  dependencies: [UnmanagedRestorationScope]
  state: NavigatorState#9719b(lifecycle state: initialized)
The second child that was to be instantiated with that key was: Directionality
  textDirection: ltr
A GlobalKey can only be specified on one widget at a time in the widget tree.
The relevant error-causing widget was: 
```

**Comment by azhansy** [comment]
> Same here getting error after migrating from version 4.1.4 to 4.3.0.
> 
> ```
> The following assertion was thrown building Directionality(textDirection: ltr):
> A GlobalKey was used multiple times inside one widget's child list.
> 
> The offending GlobalKey was: [LabeledGlobalKey<NavigatorState>#1feae Key Created by default]
> The parent of the widgets with that key was: Directionality
>   textDirection: ltr
> The first child to get instantiated with that key became: Navigator-[LabeledGlobalKey<NavigatorState>#1feae Key Created by default]
>   dirty
>   dependencies: [UnmanagedRestorationScope]
>   state: NavigatorState#9719b(lifecycle state: initialized)
> The second child that was to be instantiated with that key was: Directionality
>   textDirection: ltr
> A GlobalKey can only be specified on one widget at a time in the widget tree.
> The relevant error-causing widget was: 
> ```
> 
> If you remove
> **GetMaterialApp( initialRoute option it works fine**

      child: GetMaterialApp(
        debugShowCheckedModeBanner: false,
        getPages: AppPages.routes,
      ),
--------------------------------
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Directionality(textDirection: ltr):
A GlobalKey was used multiple times inside one widget's child list.

The offending GlobalKey was: [LabeledGlobalKey<NavigatorState>#2577f Key Created by default]
The parent of the widgets with that key was: Directionality
  textDirection: ltr
The first child to get instantiated with that key became: Navigator-[LabeledGlobalKey<NavigatorState>#2577f Key Created by default]
  dirty
  dependencies: [UnmanagedRestorationScope]
  state: NavigatorState#31e67(lifecycle state: initialized)
The second child that was to be instantiated with that key was: Directionality
  textDirection: ltr
A GlobalKey can only be specified on one widget at a time in the widget tree.
The relevant error-causing widget was: 
  Directionality file:///Users/shu/.pub-cache/hosted/pub.dartlang.org/get-4.3.0/lib/get_navigation/src/root/get_material_app.dart:217:12
When the exception was thrown, this was the stack: 
#0      Element._retakeInactiveElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:3548:11)
#1      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3562:8)
#2      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3593:33)
#3      Element.updateChild (package:flutter/src/widgets/framework.dart:3360:20)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)

**Comment by azhansy** [comment]
> > Same here getting error after migrating from version 4.1.4 to 4.3.0.
> > ```
> > The following assertion was thrown building Directionality(textDirection: ltr):
> > A GlobalKey was used multiple times inside one widget's child list.
> > 
> > The offending GlobalKey was: [LabeledGlobalKey<NavigatorState>#1feae Key Created by default]
> > The parent of the widgets with that key was: Directionality
> >   textDirection: ltr
> > The first child to get instantiated with that key became: Navigator-[LabeledGlobalKey<NavigatorState>#1feae Key Created by default]
> >   dirty
> >   dependencies: [UnmanagedRestorationScope]
> >   state: NavigatorState#9719b(lifecycle state: initialized)
> > The second child that was to be instantiated with that key was: Directionality
> >   textDirection: ltr
> > A GlobalKey can only be specified on one widget at a time in the widget tree.
> > The relevant error-causing widget was: 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you remove
> > **GetMaterialApp( initialRoute option it works fine**
> 
> ```
>   child: GetMaterialApp(
>     debugShowCheckedModeBanner: false,
>     getPages: AppPages.routes,
>   ),
> ```
> 
> ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
> The following assertion was thrown building Directionality(textDirection: ltr):
> A GlobalKey was used multiple times inside one widget's child list.
> 
> The offending GlobalKey was: [LabeledGlobalKey#2577f Key Created by default]
> The parent of the widgets with that key was: Directionality
> textDirection: ltr
> The first child to get instantiated with that key became: Navigator-[LabeledGlobalKey#2577f Key Created by default]
> dirty
> dependencies: [UnmanagedRestorationScope]
> state: NavigatorState#31e67(lifecycle state: initialized)
> The second child that was to be instantiated with that key was: Directionality
> textDirection: ltr
> A GlobalKey can only be specified on one widget at a time in the widget tree.
> The relevant error-causing widget was:
> Directionality file:///Users/shu/.pub-cache/hosted/pub.dartlang.org/get-4.3.0/lib/get_navigation/src/root/get_material_app.dart:217:12
> When the exception was thrown, this was the stack:
> #0 Element._retakeInactiveElement. (package:flutter/src/widgets/framework.dart:3548:11)
> #1 Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3562:8)
> #2 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3593:33)
> #3 Element.updateChild (package:flutter/src/widgets/framework.dart:3360:20)
> #4 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)

get: ^4.3.0

**Comment by devchenli** [comment]
I have solved the problem ,please check your routes name ,it should begin with "/".
For example ,  static const INITIAL = '/';  static const HOME = '/home'; ...
Don't write like this : static const HOME = 'home'

**Comment by slorop41314** [comment]
@devchenli is it a temporary solutions? or its a must to use / in the route name?

**Comment by jonataslaw** [comment]
No, this is not optional. This is how you MUST use it. There are already a ton of issues where I explain about this

**Comment by azhansy** [comment]
> I have solved this problem , please check your routes name , it should begin with "/".
> For example , static const HOME = '/home'; static const DETAIL = '/detail'; ...
> Don't write like this : static const HOME = 'home';static const DETAIL = 'detail'; ...
> That's all.

Thank you very much!
I solved this problem:
1: Routes name should begin with "/";
2:GetMaterialApp-> home, must set value;

**Comment by ishakii** [comment]
i have encountered this problem when upgrading flutter sdk to 2.8.0. And solved with supply a unknownRoute for GetMaterialApp.
`        unknownRoute: GetPage(
          name: SplashScreen.routeName,
          page: () => SplashScreen(),
        ),`

**Comment by FaizanAhmad127** [comment]
I may sound dumb but in my case, I didn't set up the GetPage for splashScreen.

`
class AppPages {
  static const INITIAL = Routes.splashScreen;
  static final routes=[
//forgot this getpage
    GetPage(
      name: Routes.splashScreen,
      page: () => const SplashScreen(),
    ),
    GetPage(
        name: Routes.preSignInScreen,
        page: () => const PreSignInScreen(),
        binding: PreSignInBinding(),
       // middlewares: [AuthMiddleware()]
    ),
  ];
}`
