### ISSUE TITLE
How to Detect to remove route and controller on memory?

### ISSUE THREAD

**Issue by XOneto9** [jonataslaw/getx#1672]
Hi guys.

I need to know when to detect to remove the route and controller on the memory.
In my case, Simply The app has two routes as A and B. A route(instance page) include a logout button.
After pushing the logout button then go to Logout Complete page with Get.offAllNamed('/logoutCompletePage') api.

when going to route on `logoutCompletePage`, I should remove data on local DB with Hive.
The problem is the route and controller are late to delete on the memory then removing Hive.

That is making an error related to Hive because of still exists on the memory route and controller but, Hive data is null because of removal first.

So. I want to know if I use Get.offAllNamed API then should I get a callback when calling onDelete() function?

*With logout button
```
class Logout extends StatefulWidget {
  const Logout({Key? key}) : super(key: key);

  @override
  _LogoutState createState() => _LogoutState();
}

class _LogoutState extends State<Logout> {
    final logoutController = Get.put(LogoutController());
    //* will make error
   final box = Hive.box('userdata');
   final user = box.get('user');

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Container(
        width: 140,
        height: 40,
        margin: EdgeInsets.only(bottom: 20),
        child: TextButton(
          style: ButtonStyle(),
          onPressed: () {
            Get.offAllNamed('/LogoutComplete');
          },
          child: Text(
            'Logout,
          ),
        ),
      ),
    );
  }
}
```

*Complete Page
```
class CompleteLogout extends StatefulWidget {
  @override
  _CompleteLogoutState createState() => _CompleteLogoutState();
}

class _CompleteLogoutState extends State<CompleteLogout> {
  final appController = Get.put(AppController());

  @override
  initState() {
    super.initState();
    //* still exsist Logout route and controller
    _delayToLogout();
  }


   //* to remove data on Hive
  _delayToLogout() {
    //* this is my solution to use delay
    Future.delayed(Duration(milliseconds: 1000), () {
      final box = Hive.box('userdata');
      box.deleteAll(['user', 'tokens']);
    });
    //* finish remove then still alive Logout route and controller will be error of Hive data on Logout Page
  }

  @override
  dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```
 
the temporary solution is using a delay function until after remove route and controller on memory then remove Hive data.

does any better idea have?
Please let me know what is it thanks!

**Comment by jonataslaw** [comment]
You are using GetX, with a StatefulWidget, inserting Hive in your UI (the view should only receive data, right?), using dispose, but you want onDelete which is part of the controllers lifecycle.
I don't quite understand your problem, but it seems to me that there will be some sync problem here.
I suggest you remove everything that is not a widget from your class (including the hive, do a getter for the variable in your controller and access it). And use the lifecycle of controllers.

**Comment by XOneto9** [comment]
@jonataslaw 
H, I'm sorry to not clearly explain.

1. I'm using Getx with Hive
2. The hive is to store user data on localDevise to not remove when close app for auto login
3. Now using statefulWidget. Actually the widget is not important to me between stateless and statefulwidget. The reason to use statefulwidget on example is that using initState to work some action before call build Widget.

4. More clearly my situation,
In good process,
When go to CompleteLogout route with Get.offAllNamed('CompleteLogout'), I want to first call to remove controllers and previous routes as automatically Getx works.
And then I will call remove Hive data.
But In bad process,
If first call remove hive data, the existed controller and route on the memory. Then They don't find hive data because of removed. that make error.

Controller is not immediately delete on memory.

So I want to know callback after delete controller and route.

**Comment by nivisi** [comment]
@XOneto9 the idea of GetX is to put all the business logic (opening boxes, getting a user — _are also the business logic_) to controllers. Widget, regardless stateful or stateless, are only for displaying the UI. They should not contain any logic, but only presentation.

Regarding `initState`: you can (and should) do some work in the `Controller`. Although it is a sync method, you can use a `StateMixin`, changing the state of your controller and handling it in the UI (widgets). The example can be found [here](https://github.com/jonataslaw/getx#statemixin).

---

Regarding your question. If I understand your needs correctly, you should:
- Move the box and the user to the controller;
- For the user provide a getter, so widget could access it to display the name for example;
- In `onInit`, open the box and get the user;
- In `onDelete`, clear the needed data and close the box.

Thus the data will be deleted when the controller gets deleted.

**Comment by XOneto9** [comment]
@nivisi 
Oh.. guys
Thanks

After work today, I will apply your options.
Thanks!

**Comment by XOneto9** [comment]
I re-write code like as advised method from @nivisi 
So, it is solved and smoothly logic. Then This issue close!
