### ISSUE TITLE
Getx created stackoverflow error

### ISSUE THREAD

**Issue by tonyhart7** [jonataslaw/getx#1674]
Getx create infinity loop of getx controller while Init app 
Iam using GetPage with Binding Builder its all fine until Iam implement Function that can delete Value of List 
then suddenly stackoverflow error in my screen and Getx has create infinity loop around it 
at First Iam expexted this is my code bug so I deleted the app and do workaround about turn out the error is still there 
after clean install, flutter clean and delete all related files to related my app (new install) the error still persist 

this is My BindingBuilder Code 
~~~
 GetPage(
      name: home,
      page: () => Home(),
      binding: BindingsBuilder(() {
        Get.lazyPut<BalanceExpenseController>(() => BalanceExpenseController());
        Get.lazyPut<WalletController>(() => WalletController());
        Get.lazyPut<BudgetController>(() => BudgetController());
        Get.lazyPut<PlannedBillController>(() => PlannedBillController());
      })),

log error :
[GETX] Instance "BalanceExpenseController" has been created
[GETX] Instance "WalletController" has been created
[GETX] Instance "BalanceExpenseController" has been created
[GETX] Instance "WalletController" has been created
[GETX] Instance "BalanceExpenseController" has been created
[GETX] Instance "WalletController" has been created
[GETX] Instance "BalanceExpenseController" has been created
[GETX] Instance "WalletController" has been created
[GETX] Instance "BalanceExpenseController" has been created
[GETX] Instance "WalletController" has been created
[GETX] Instance "BalanceExpenseController" has been created
[GETX] Instance "WalletController" has been created
[GETX] Instance "BalanceExpenseController" has been created
~~~

To Reproduce this Bug
(in my case) 
1. Iam implement Function that delete a Linked List in My App 
2. turn out error come (expected) but its stackoverflow that create infinity getxController
3. trying to reproduce the Bug but after Clean Install Error is still Persist after delete all List Related value (see no 1) 

Flutter Version: 
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git

Getx Version: 
get: ^4.2.4 (latest)
get: ^4.1.4 

Device: 
Pixel 4 Android 11 Android Studio 
Flutter Web version Edge chromium
after created stackoverflow Basically Any New install produce stackoverflow 

attached code: 
~~~
GetPage: 
GetPage(
      name: home,
      page: () => Home(),
      binding: BindingsBuilder(() {
        Get.lazyPut<BalanceExpenseController>(() => BalanceExpenseController());
        Get.lazyPut<WalletController>(() => WalletController());
        Get.lazyPut<BudgetController>(() => BudgetController());
        Get.lazyPut<PlannedBillController>(() => PlannedBillController());
      })),

Function that Created Stackoverflow (not sure why)
void deleteWallet(String nameWallet) {
    int existWalletID =
        walletList.indexWhere((e) => e.walletName == nameWallet);
    if (existWalletID >= 0) {
      walletList.removeAt(existWalletID);
      localWallet.deleteAt(existWalletID);
      txCntrl.fillSelectedWallet();
      update();
    } else {
      update();
    }
  }
~~~

**Comment by tonyhart7** [comment]
Iam remove Binding builder and use Normal binding approach and stackoverflow still occur 
~~~
GetPage(
    name: home,
    page: () => Home(),
    binding: HomeBinding(),
  ),

class HomeBinding implements Bindings {
  @override
  void dependencies() {
    Get.lazyPut<BalanceExpenseController>(() => BalanceExpenseController());
    Get.lazyPut<WalletController>(() => WalletController());
    Get.lazyPut<BudgetController>(() => BudgetController());
    Get.lazyPut<PlannedBillController>(() => PlannedBillController());
  }
}
~~~

**Comment by jonataslaw** [comment]
I think you are using GetWidget somewhere

**Comment by tonyhart7** [comment]
> I think you are using GetWidget somewhere

I do not use GetWidget and and not Implement that 
Hell even If iam using getwidget why that create infinity loop of controller

but I will check that in my code if IAM ACIDENTALLY IMPORT getwidget thanks

**Comment by tonyhart7** [comment]
> I think you are using GetWidget somewhere

I checked all my files and var import that i do not use Getwidget 
oh yeah I think this because of lazyput and offnamed function conflict 
because I try to close dialog with Get.offAndtoNamed to Home screen after delete object

I read at this https://github.com/jonataslaw/getx/blob/master/documentation/en_US/dependency_management.md

First, let's of the fenix of Get.lazyPut and the permanent of the other methods.
~~~
The fundamental difference between permanent and fenix is how you want to store your instances.

Reinforcing: by default, GetX deletes instances when they are not in use. It means that: If screen 1 has controller 1 and screen 2 has controller 2 and you remove the first route from stack, (like if you use Get.off() or Get.offNamed()) the controller 1 lost its use so it will be erased.

But if you want to opt for using permanent:true, then the controller will not be lost in this transition - which is very useful for services that you want to keep alive throughout the entire application.

fenix in the other hand is for services that you don't worry in losing between screen changes, but when you need that service, you expect that it is alive. So basically, it will dispose the unused controller/service/class, but when you need it, it will "recreate from the ashes" a new instance.
~~~

after dispose controller from page and I navigate to newScreen(home at this point) 
Controller got dispose and call again instantly but I do not know why is got loop (dnt understand getxLazyput with offnamed work tho)

Please see this issue because my development got halt :(

**Comment by tonyhart7** [comment]
OK iam narrow down my search that found the issue FINALLY yeah
its Because Iam using controller inside controller 
you know Iam need perform computational stuff in another controller (like linked list but its linked controller, LMAO)

see code: 
~~~~
class BalanceExpenseController extends GetxController {
  final WalletController walletCntrl = Get.find();
~~~

so my Balance Controller call wallet controller that (have not been wakeup) when Init
and when balance controller fail to call it created wallet controller and same goes with wallet controller 
combine this with behaviour Lazy.put this create not intentionally infinity loop of Controller calling each other

my hotfix for this to put at initial Binding and remove Get.find for 1 Controller but I know this will happen to problem in the future because I need acces data for my bulk of controller

~~~
return ScreenUtilInit(
      designSize: Size(360, 690),
      builder: () => GetMaterialApp(
        initialBinding: MainBinding(),
~~~

**Comment by jonataslaw** [comment]
Try to use getters

Rather this:
final WalletController walletCntrl = Get.find();

Use this: 
WalletController get walletCntrl => Get.find();

**Comment by tonyhart7** [comment]
> Try to use getters
> 
> Rather this:
> final WalletController walletCntrl = Get.find();
> 
> Use this:
> WalletController get walletCntrl => Get.find();


Thank you for mention this 
yep its working using Getter at least for now (hope it never happen again)
I will close this issue
