### ISSUE TITLE
GetConnect : Unhandled Exception: type 'Null' is not a subtype of type 'Response<dynamic>'

### ISSUE THREAD

**Issue by justkost** [jonataslaw/getx#1686]
After upgrading to version 4.2.5 from 4.1.4, i got this error: _Unhandled Exception: type 'Null' is not a subtype of type 'Response<dynamic>'_

flutter 2.2.3
dart 2.13.4

![image](https://user-images.githubusercontent.com/18269060/126881915-af9f691e-7017-4b7a-ad4d-2fcd65c6f69f.png)

**Comment by panalgin** [comment]
I'm having the same issue and it started after this change on get_connect dd5aaee
The only solution I could apply was forcefully downgrading to 4.1.4 version by putting 
`get: 4.1.4` in pubspec.yaml, as somehow the ide (vscode) kept the cached 4.2.4 always in play.

also don't forget to do a `flutter clean` and `flutter pub get` after changing the version

**Comment by jonataslaw** [comment]
you need return response as you return request

**Comment by panalgin** [comment]
> you need return response as you return request

The below code works in 4.1.4 but not in 4.2.4, 

```dart
return post(path, dto.toJson(), contentType: "application/json", decoder: TokenModel.fromMap);```

Error: Unhandled Exception: type 'Null' is not a subtype of type 'Response<TokenModel>'

**Comment by justkost** [comment]
It works correctly, thank you @jonataslaw 

![image](https://user-images.githubusercontent.com/18269060/126896595-3cf60ad5-9c74-4d35-b6b7-432ec5b0ac88.png)

**Comment by panalgin** [comment]
Please do not close this, the above "decoder" functionality simply does not work thanks to the new patch and it gives the same error you opened this issue for.
