### ISSUE TITLE
All children of TabBarView/PageView/IndexedStack initialized at same time when starting app

### ISSUE THREAD

**Issue by ka28740093** [jonataslaw/getx#1690]
**Describe the bug**
1. Well, I'm new in flutter. I try to build a BottomNavigationBar. 
2. First I try to use routes, use `Get.offNamed()` when clicking bottom button, it works, but each route reload every time.
3. Then I try to use `TabBarView`, that's fine, but all pages load at same time when start app.
4. And then I try `TabBarView`, as same as `TabBarView`.
5. At last I try `PageView`, as same as above.

** solutions**

use `PageView.build` instead.

**Comment by Pluto1219** [comment]
> **Describe the bug**
> 
> 1. Well, I'm new in flutter. I try to build a BottomNavigationBar.
> 2. First I try to use routes, use `Get.offNamed()` when clicking bottom button, it works, but each route reload every time.
> 3. Then I try to use `TabBarView`, that's fine, but all pages load at same time when start app.
> 4. And then I try `TabBarView`, as same as `TabBarView`.
> 5. At last I try `PageView`, as same as above.
> 
> ** solutions**
> 
> use `PageView.builder` instead.
好兄弟， PageView.builder能解决所有页面同时加载的问题吗？

**Comment by Pluto1219** [comment]
> **描述错误**
> 
> 1. 好吧，我是颤振的新手。我尝试构建一个BottomNavigationBar。
> 2. 首先我尝试使用路由，`Get.offNamed()`单击底部按钮时使用，它可以工作，但每次都会重新加载每个路由。
> 3. 然后我尝试使用`TabBarView`，这很好，但是在启动应用程序时所有页面同时加载。
> 4. 然后我尝试`TabBarView`，与`TabBarView`.
> 5. 最后我尝试`PageView`，和上面一样。
> 
> ** 解决方案**
> 
> 使用`PageView.builder`来代替。



好兄弟，PageView.builder能解决所有页面同时加载的问题吗？
