### ISSUE TITLE
controller not call onClose when call Get.offNamedUntil()

### ISSUE THREAD

**Issue by Mocaris** [jonataslaw/getx#1697]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
When calling 
```
Get. OffNamedUntil (approutes.sub_parking_order_detail, (route) => route.settings.name == approutes.main,
arguments: info.orderSn);
``` 
controller deleted from memory,
but controller is not called onClose().

**Reproduction code
```

 Get.offNamedUntil(AppRoutes.SUB_PARKING_ORDER_DETAIL, (route) => route.settings.name == AppRoutes.MAIN,
              arguments: info.orderSn);

```
**Flutter Version:**
2.0

**Getx Version:**
4.3.0

**Describe on which device you found the bug:**
ex: Moto z2 - Android.

**Minimal reproduce code**
 Get.offNamedUntil(AppRoutes.SUB_PARKING_ORDER_DETAIL, (route) => route.settings.name == AppRoutes.MAIN,
              arguments: info.orderSn);

**Comment by jonataslaw** [comment]
Please put a reproduce code or the issue will close (reproduce code is an example, like the default Flutter project, where it demonstrates the error, where we can copy, paste into the IDE and check if the problem exists)
