### ISSUE TITLE
type 'Request<dynamic>' is not a subtype of type 'Request<ResponseData>'

### ISSUE THREAD

**Issue by geekcarl** [jonataslaw/getx#1702]
**Describe the bug**
a bug with use GetConnect:

error message is :
`type 'Request<dynamic>' is not a subtype of type 'Request<ResponseData>' in type cast`

**Reproduction code

```dart
  @override
  void onInit() {
    super.onInit();
    httpClient.baseUrl = appBaseUrl;
    httpClient.addRequestModifier<dynamic>(
        (request) => request..headers['content-type'] = 'application/json');

    httpClient.addRequestModifier<dynamic>((request) async {
      return request.copyWith();
    });
}
```
**Expected behavior**
I can normal send request.
I suggest that Request must not bind with response type<T> , so i can build Request myself;

**Flutter Version:**
Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H524 darwin-x64,
    locale zh-Hans-CN)

**Getx Version:**
  get: ^4.3.0

**Comment by jasonlaw** [comment]
Hi @geekcarl ,

This is what I am doing and it is working fine, maybe you can give it a try.
Notes the <void> vs <dynamic>.

~~~dart
 client.httpClient.addRequestModifier<void>((request) async {
      request.headers.addAll({
        if (App.useLocalTimezoneInHttp)
          "timezoneoffset": "${DateTime.now().timeZoneOffset.inHours}",
        if (Get.locale != null)
          "languagecode":
              "${Get.locale!.languageCode}_${Get.locale!.countryCode}",
        if (App.settings.apiKey().isNotNullOrEmpty)
          "appkey": App.settings.apiKey(),
      });

      await _cookie.loadForRequest(request);
      return request;
    });
~~~
