### ISSUE TITLE
Get.theme Does not change/Update whenever the system theme type changes  in iOS 

### ISSUE THREAD

**Issue by wilz05** [jonataslaw/getx#1703]
Whenever we change the system theme mode (dark to light or light to dark mode). app doesn't refresh the widget when app focused from iOS device settings page to app page. 

In app main page 

GetMaterialApp(
      initialRoute: SplashPageImage.PageID,
      defaultTransition: Transition.native,
      enableLog: true,
      locale: Locale("ar"),
      getPages: [........ my pages....  ],
      theme: myThemeLight,
      themeMode: ThemeMode.system,
      darkTheme: myThemeDark,
      home: SplashPageImage(),
    );

Whenever I use below code with Theme.of(context) theme gets updated without any issues 
```

 leadingBtn: IconButton(
            icon: Icon(Icons.search),
            color: Theme.of(context).iconTheme.color,
            iconSize: 32,
            onPressed: () {
              print("pressed left in homepage");
            },
          )
```

but when I use below code with Get.theme.iconTheme.color  it doesn't update anything. I need to goto some other page or refresh the app to get the theme color changed.

```
 leadingBtn: IconButton(
            icon: Icon(Icons.search),
            color: Get.theme.iconTheme.color,
            iconSize: 32,
            onPressed: () {
              print("pressed left in homepage");
            },
          )
```

 

**Flutter Version:**
 Flutter 2.2.2   Dart 2.13.3

**Getx Version:**
Getx 4.1.4

**Describe on which device you found the bug:**
iOS XS Max

**Comment by eduardoflorence** [comment]
Try replace `Get.theme.iconTheme.color` with `context.theme.iconTheme.color` 
GetX has extensions for context and one of them is the theme.

**Comment by 21pages** [comment]
same problem

**Comment by abel3ri** [comment]
any updates?

**Comment by emredurgunlu** [comment]
same problem

**Comment by Mashi-91** [comment]
context also not working....

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Demo',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      home: Home(),
    );
  }
}


class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext val) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              height: 40,
              width: 40,
              color: Get.context!.theme.tabBarTheme.dividerColor,
              child: Text('Tap'),
            ),
            // SizedBox(height: 40),
            // Container(
            //   height: 40,
            //   width: 40,
            //   color: Theme.of(val).tabBarTheme.dividerColor,
            //   child: Text('Tap'),
            // )
          ],
        ),
      ),
    );
  }
}

**Comment by abel3ri** [comment]
> Get.context also not working.... On Android version; get: ^4.6.6
> 
> ```
>   class MyApp extends StatelessWidget {
>     const MyApp({super.key});
>   
>     @override
>     Widget build(BuildContext context) {
>       return GetMaterialApp(
>         debugShowCheckedModeBanner: false,
>         title: 'Demo',
>         theme: AppTheme.lightTheme,
>         darkTheme: AppTheme.darkTheme,
>         themeMode: ThemeMode.system,
>         home: Home(),
>       );
>     }
>   }
>   
>   
>   class Home extends StatelessWidget {
>     const Home({super.key});
>   
>     @override
>     Widget build(BuildContext context) {
>       return Scaffold(
>         body: Center(
>           child: Column(
>             mainAxisAlignment: MainAxisAlignment.center,
>             children: [
>               Container(
>                 height: 40,
>                 width: 40,
>                 color:  context.theme.tabBarTheme.dividerColor,
>                 child: Text('Tap'),
>               ),
>               // SizedBox(height: 40),
>               // Container(
>               //   height: 40,
>               //   width: 40,
>               //   color: Theme.of(context).tabBarTheme.dividerColor,
>               //   child: Text('Tap'),
>               // )
>             ],
>           ),
>         ),
>       );
>     }
>   }
> ```

// GetX adds extension on BuildContext so you just have to use the context, no need of using Get.context
