### ISSUE TITLE
GetMaterialApp cannot allows override routes on widget testing

### ISSUE THREAD

**Issue by darwin-morocho** [jonataslaw/getx#1715]
GetX version: 4.3.0

Problem: I am writing multiples widget testing at the same file and I've created a reusable function to create a GetMaterialApp
```dart
Widget getTestMaterialApp({String? initialRoute, List<GetPage>? routes}) {
  return GetMaterialApp(
    initialRoute: initialRoute ?? AppPages.INITIAL,
    getPages: routes ?? AppPages.routes,
  );
}
```
I want to use the `routes` parameter override the pages generated by `get cli` like this
```dart
testWidgets(
    'SplashView > biometric UI',
    (tester) async {
      await tester.pumpWidget(
        getTestMaterialApp(
          initialRoute: Routes.SPLASH,
          routes: [
            ...AppPages.routes.where(
              (_) => _.name == Routes.SPLASH,
            ),
            GetPage(
              name: Routes.HOME,
              page: () => const Text("home"),
            ),
          ],
        ),
      );
    },
  );
```

The above code works fine if I only have one widget testing but If I have multiples tests like
```dart

void main() {
  setUp(() async {
    await setUpTestDependencies();
  });
  testWidgets(
    'test 1',
    (tester) async {
      await tester.pumpWidget(
        getTestMaterialApp(
          initialRoute: Routes.SPLASH,
        ),
      );
    },
  );
  testWidgets(
    'test 2',
    (tester) async {
      await tester.pumpWidget(
        getTestMaterialApp(
          initialRoute: Routes.SPLASH,
          routes: [
            ...AppPages.routes.where(
              (_) => _.name == Routes.SPLASH,
            ),
            GetPage(
              name: Routes.HOME,
              page: () => const Text("home"),
            ),
          ],
        ),
      );
    },
  );
}
```

The second test create a GetMaterialApp but it is using the routes of the first test.

**Comment by jonataslaw** [comment]
Try to use  tearDown(Get.reset);

**Comment by darwin-morocho** [comment]
> Try to use tearDown(Get.reset);

I am using Get.reset() in the setUpTestDependencies function

**Comment by jonataslaw** [comment]
Are you on version 4.3.4?
I changed the imports in this version which may have fixed a possible bug where Get.reset reset only dependencies, or just routes, or just internationalization. He currently deletes everything.

Try to update to latest version

**Comment by darwin-morocho** [comment]
> Are you on version 4.3.4?
> I changed the imports in this version which may have fixed a possible bug where Get.reset reset only dependencies, or just routes, or just internationalization. He currently deletes everything.
> 
> Try to update to latest version

I will check it

**Comment by jonataslaw** [comment]
Sorry, I closed it by mistake.

**Comment by jonataslaw** [comment]
@darwin-morocho Did this work for you?

**Comment by darwin-morocho** [comment]
> @darwin-morocho Did this work for you?

yes now it is working
