### ISSUE TITLE
Navigate to Nested Page (lower level) not working in Getx Navigation 2.0 

### ISSUE THREAD

**Issue by tonyhart7** [jonataslaw/getx#1719]
Iam trying to navigate to lower page via 
~~~
Get.rootDelegate.toNamed(Routes.LAST_EXPENSE_DETAIL);
~~~

this is my Routes 

~~~
static const LAST_EXPENSE_DETAIL = _Paths.HOME + _Paths.SPEND_SCREEN + _Paths.LAST_EXPENSE_DETAIL; 
static const BUDGET_FINISHED = _Paths.HOME +  _Paths.SPEND_SCREEN +  _Paths.BUDGET_DETAIL + _Paths.BUDGET_FINISHED; // this not work too
~~~

Iam trying to access from spend screen but its force me to Home
nothing show error or Log like like nothing happen it cant allow me to access that page 
is there I something missing like Key or HomeDelegate (?)

**Comment by jonataslaw** [comment]
This works, and that's exactly what's done here:
https://github.com/jonataslaw/getx/blob/master/example_nav2/lib/app/modules/home/views/home_view.dart
Try looking for help or support on the community channels, there is the right place to ask questions. This space is reserved for reporting bugs with valid reproduce codes.
