### ISSUE TITLE
Unable to bindstream from firestore .snapshot().listen

### ISSUE THREAD

**Issue by CSharper63** [jonataslaw/getx#1721]
### Discussed in https://github.com/jonataslaw/getx/discussions/1712

<div type='discussions-op-text'>

<sup>Originally posted by **CSharper63** July 30, 2021</sup>
Hi guys, 

The app : Manage movie and who is currently watching the movie.

I'm facing of a problem. I try since 2 days to bind a stream from firestore query using a Rx<List<UserModel>> but I m unable to populate my list. I already test every lines of the following requests everything is working fine. Something goes wrong when try ```.bindstream()```.

My code : 
My database.dart (file to interact with firestore)

```
Future<Stream<List<UserModel>>> viewersStream(String movieId) async {
    List<String> viewersIds = [];
    List<UserModel> viewers = [];

    await _firestore
        .collection(MOVIES_COLLECTION)
        .doc(movieId)
        .collection(VIEWERS_COLLECTION)
        .get()
        .then((value) {
      value.docs.forEach((element) {
        viewersIds.add(element.id);
      });

      return _firestore
          .collection(USERS_COLLECTION)
          .where(FieldPath.documentId, whereIn: viewersIds)
          .snapshots()
          .listen((event) {
        event.docChanges.forEach((element) {
          print("try adding to return list user: " + element.doc.id); // works
          viewers.add(UserModel.fromDocumentSnapshot(
              documentSnapshot: element.doc));
          print("user add to return list user: " + element.doc.id); // works
        });
        return viewers;
      });
    });
  }
```

then my movie_controller.dart :

```
void fetchingViewers(String movieId) async {
    if (movieId != null || movieId != "") {
      print("fetching viewers for movie " + movieId);
      _participants.bindStream(await Database().viewersStream(movieId));
      print("fetched viewers for movie " + movieId);
    }
  }
```

call stack error:
![image](https://user-images.githubusercontent.com/47356381/127656852-37bbecd9-2902-4968-9863-581fb0434979.png)
I hope someone could help me. </div>

I created an issue with this problem because I can't find any information about this problem anywhere. I already tried in async/sync mode, nothing works. So hope any getx developer could help me to understand how bindstream method works.

**Comment by rus0n** [comment]
hi,
I am a first time in this in github. however i can recommend you use only Stream to update the UserModel every time it is modified in the database, or only Future to update it only once, when the application is started for example, but not both. I have many Streams in my app that i'm developing, so i will write you a example to use bindStream correctly,I hope it helps you and everything works.

`
class MovieController extends GetxController {
  // this is the controller of the user that you can update in the pages of the app

  var movieId =
      ''.obs; //wait the user update the movie that want, i guess. From the UI
  
  List<String> viewersIds = [];
  RxList<UserModel> viewers =
      RxList(); // here it would have been the first error of your coude

  // when the controller start
  void onInit() {
    ever(movieId, getvierwersIds()); //ever change in movieId, the callback gonna be getvierwersIds

    viewers.bindStream(viewerStream());
    super.onInit();
  }

  getvierwersIds() async {
    await FirebaseFirestore.instance
        .collection(MOVIES_COLLECTION)
        .doc(movieId.value) //from get the real value of the observer
        .collection(VIEWERS_COLLECTION)
        .get()
        .then((value) {
      return value.docs.forEach((element) {
        viewersIds.add(element.id);
      });
    });
  }

  Stream<List<UserModel>> viewerStream() {
    // Stream that feach UserModel
    if (movieId.value.isNotEmpty) {
      //check null value
      return FirebaseFirestore.instance
          .collection(USERS_COLLECTION)
          .where(FieldPath.documentId, whereIn: viewersIds)
          .snapshots()
          .map((event) =>
              event.docs.map((e) => UserModel.fromFireStore(e)).toList());
    } else {
      return Stream.empty();
    }
  }
}

//i guess this is when the user tap or pressed the movie that want or something like that, so onTap() => movieId.value = 'value'
`
its an example that you can adapt. In UserModel one example to this code is:

`
class UserModel {
  String? userId;
  String? email;

  UserModel({this.userId, this.email});
  factory UserModel.fromFireStore(DocumentSnapshot data) {
    return UserModel(userId: data.get('userId'), email: data.get('email'));
  }
}
` 

i do it in this way, sorry if i have some mistakes, I am Spanish.
 Any question or doubt I will try to help so everyone learns.

**Comment by CSharper63** [comment]
Thank you very much for you anwser I will test this code and get back to you asap. 🙏🙏🙏

**Comment by CSharper63** [comment]
Hello, I tried what you provide me. It seems to work. I just have several questions. How to create a setter with RxString like movieId. I tried to set the value but always throw an error :
On tap event I try the following code to fetch my viewers stream :
``` 
Get.find<MovieController >().setCurrentMovieId = THE ID I PROVIDE;
``` 
```
 ════════ Exception caught by gesture ═══════════════════════════════════════════
The method 'call' was called on null.
Receiver: null
Tried calling: call("tzovkhW6IOgLp337Ujtv")
════════════════════════════════════════════════════════════════════════════════
```
My second question is can you explain me why in my first code version where I got my problem I can't return a list from stream in .then() from the first query ? I can't understand how to use bindStream properly.

Thanks you for your support !!!!!! @rus0n

**Comment by CSharper63** [comment]
What must I do to fetch my stream on document change ? Like using snapshot().listen ? I have trouble understanding how to use the future and store data in real time.

**Comment by rus0n** [comment]
Hello, 
It's two ways to set a variable, that depends how you initialize. For example:

Firstly, If you have to initialize with a value it's like:
```
var movieId = 'value'.obs //the last term means that it is a variable that is in observed mode
```

If you want that the variable doesn't need initialize, it's like:
```
var movieId = Rx<String>() ;

```
To set a value in the observer variable you only have to put:

```
movieId. value='value'; //you can put it in the UI or in the MovieController, don't need a setter. 
```

Stream means that the value updates when it's a new value , in this case a new value in the database. Firstly, don't need listen, snapshot() shot when this happen. In my code you can see that I only put snapshot that after I put a map to convert it, in this map I get the documents of the databases that the values updated or new values, then I get another map of this documents to fetch the Model. 

Future is only to call it onces and fetch one time, don't shot when the values were updated or new values from database. 

If you want I can show you an example of my app or a video that how the data update in realtime synchronized with the database. It's works really good. 

See you,  i hope it was helpfully @CSharper63

**Comment by rus0n** [comment]
Hello, 
It's two ways to set a variable, that depends how you initialize. For example:

Firstly, If you have to initialize with a value it's like:
```
var movieId = 'value'.obs //the last term means that it is a variable that is in observed mode
```

If you want that the variable doesn't need initialize, it's like:
```
var movieId = Rx<String>() ;

```
To set a value in the observer variable you only have to put:

```
movieId. value='value'; //you can put it in the UI or in the MovieController, don't need a setter. 
```

Stream means that the value updates when it's a new value , in this case a new value in the database. Firstly, don't need listen, snapshot() shot when this happen. In my code you can see that I only put snapshot that after I put a map to convert it, in this map I get the documents of the databases that the values updated or new values, then I get another map of this documents to fetch the Model. 

Future is only to call it onces and fetch one time, don't shot when the values were updated or new values from database. 

If you want I can show you an example of my app or a video that how the data update in realtime synchronized with the database. It's works really good. 

See you,  i hope it was helpfully @CSharper63

**Comment by CSharper63** [comment]
Thank you I think an example video could be good to understand concept. 
For my obs I think I understand how does it work. But I made my project in MVC so I want to use the controller in view to set the value of movie Id each time in to. My problem is each call in my setter to change my RxString is call on null. I can't understand why
My call in my view :
```
Get.find<MovieController>().setCurrentMovieId = movie.id;
```
In my controller : 
```
RxString partyId = RxString('no_movie'); // already try to use like var movieId = 'no_movie'.obs;
set setCurrentMovieId(String value) {
    try {
      this.movieId.value = value;
    } catch (e) {
      print(e);
    }
  }
```
But everytime I call the setter it's null so I can't use the ```ever function``` to update automatically the stream.
error : 
```
I/flutter (19261): NoSuchMethodError: The method 'call' was called on null.
I/flutter (19261): Receiver: null
I/flutter (19261): Tried calling: call("29bzrYUImjIeyGn45WSZ")
```
Thank you for your time !

**Comment by rus0n** [comment]
To set or get the value of movieId in the statelessWidget first after the build(context). (There are many options) but I will put the classic option, you have to put

```
final controller = Get.put(MovieController());

```
When I have to use the movieId, the setter is 
```
controller.movieId.value = 'value';

```
The getter

```
controller.movieId.value

```

For you I think the best option in the MovieController is

```
var movieId = Rx<String>();
```

When I stay at home at night I will try to send you a video.

**Comment by CSharper63** [comment]
Thank you if you want I have telegram : @CSharper63 !
