### ISSUE TITLE
Rx<T> vs BehaviorSubject

### ISSUE THREAD

**Issue by steven-spiel** [jonataslaw/getx#1724]
There is a key difference between how getx observables and `BehaviorSubject`s listen to streams. When listening to `BehaviorSubject`, the current value gets emitted, but getx waits until the next value. Take this code for example:

```dart
void main() {
  // create variables
  final RxInt observable = 0.obs;
  final BehaviorSubject<int> behavior = BehaviorSubject<int>.seeded(0);

  // add listeners
  observable.listen((int val) => print("observable: $val"));
  behavior.listen((int val) => print("behavior: $val"));

  // update values
  observable.value = 1;
  behavior.add(1);
}
```

Running the above code outputs:

```
observable: 1
behavior: 0
behavior: 1
```

I would expect the observable to emit `0` and then `1` just like the BehaviorSubject did. 

Would you ever consider emitting the current value on listen? 

In the meantime, I'm using an extension:

```dart
extension RxExtensions<T> on Rx<T> {
  StreamSubscription<T> listenWithInitialValue(
    void Function(T event)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) {
    final StreamSubscription<T> subscription = subject.stream.listen(
      onData,
      onError: onError,
      onDone: onDone,
      cancelOnError: cancelOnError,
    );

    refresh();

    return subscription;
  }
}
```

**Getx Version:**
`4.3.4`

**Comment by jonataslaw** [comment]
I think the main difference here is that while in BehaviourSubject you need an initial value to listen to it on listen, with an Rx you can access the initial value directly by `.value`.
Using BehaviourSubject we have the reconstruction of a widget to set its initial value, while in GetX we don't.
I think that each one has its application, and I don't see any advantage in copying the behavior of BehaviorSubject, on the contrary, it would bring an unnecessary reconstruction in the widget tree.

**Comment by steven-spiel** [comment]
Makes sense. Thanks for the clarification!
