### ISSUE TITLE
Error Navigate to other children of GetPage 

### ISSUE THREAD

**Issue by dragongesa** [jonataslaw/getx#1728]
**Describe the bug**
i have route like this
- manage user
- - new user
- - registered user
- - saved user
- - details user
in the app pages i have GetPage contains that 4 children. when i am in the "/manage user/new user" then get.to("/manage user/details user") its return error `child == _child : is not true`

**Reproduction code

in my app_pages.dart

```dart
GetPage(
        name: _Paths.MANAGE_USER,
        page: () => ManageUserView(),
        binding: ManageUserBinding(),
        children: [
          GetPage(
            name: _Paths.REGISTERED_USER,
            page: () => RegisteredUserView(),
            binding: RegisteredUserBinding(),
          ),
          GetPage(
            name: _Paths.NEW_USER,
            page: () => NewUserView(),
            binding: NewUserBinding(),
          ),
          GetPage(
            name: _Paths.SAVED_USER,
            page: () => SavedUserView(),
            binding: SavedUserBinding(),
          ),
          GetPage(
            name: _Paths.DETAILS_USER,
            page: () => DetailsUserView(),
            binding: DetailsUserBinding(),
          ),
        ]),
```

```dart
final http.Response response =
          await FarmerRegisterRepository.upload(data, onSend);
      if (response.statusCode! >= 200 && response.statusCode! < 300) {
        if (response.data["status"] == "success") {
           //the error will show up when below executed
           //MANAGE_USER = "/manage-user" DETAILS_USER = "/details-user"
          Get.toNamed(Routes.MANAGE_USER + Routes.DETAILS_USER);
          //  /manage-user/new-user ==> /manage-user/details-user
        }
      }
```

**To Reproduce**
the new-user page contains form (to register user)
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKeys detected in widget tree.

The following GlobalKeys were specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The keys were:
- [GlobalKey#c247d]
  [LabeledGlobalKey<OverlayState>#d5ee0]
This was determined by noticing that after widgets with the above global keys were moved out of their respective previous parents, those previous parents never updated during this frame, meaning that they either did not update at all or updated before the widgets were moved, in either case implying that they still think that they should have a child with those global keys.
The specific parents that did not update after having one or more children forcibly removed due to GlobalKey reparenting are:
- IgnorePointer(ignoring: false, renderObject: RenderIgnorePointer#0f539 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE DETACHED)
  UnmanagedRestorationScope
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2939:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2964:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:879:19)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:330:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#10     _invoke (dart:ui/hooks.dart:164:10)
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#12     _drawFrame (dart:ui/hooks.dart:127:31)
(elided 3 frames from dart:async)
====================================================================================================

```
**Expected behavior**
I test to change the route to other route like Routes.SETTINGS and its no problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/58933926/128346754-55cc7e94-d665-4907-a963-62d3f78d4b76.png)

**Flutter Version:**
LATEST

**Getx Version:**
4.3.4

**Describe on which device you found the bug:**
Redmi 8

**Minimal reproduce code**

**Comment by eduardoflorence** [comment]
This does not appear to be a GetX related error. Check the Widget Form's GlobalKey. If the route is called a second time and is still in Flutter's navigation stack, the GlobalKey will repeat and the error occurs.

**Comment by jonataslaw** [comment]
> **Describe the bug**
> i have route like this
> 
> * manage user
> * * new user
> * * registered user
> * * saved user
> * * details user
>     in the app pages i have GetPage contains that 4 children. when i am in the "/manage user/new user" then get.to("/manage user/details user") its return error `child == _child : is not true`
> 
> **Reproduction code
> 
> in my app_pages.dart
> 
> ```dart
> GetPage(
>         name: _Paths.MANAGE_USER,
>         page: () => ManageUserView(),
>         binding: ManageUserBinding(),
>         children: [
>           GetPage(
>             name: _Paths.REGISTERED_USER,
>             page: () => RegisteredUserView(),
>             binding: RegisteredUserBinding(),
>           ),
>           GetPage(
>             name: _Paths.NEW_USER,
>             page: () => NewUserView(),
>             binding: NewUserBinding(),
>           ),
>           GetPage(
>             name: _Paths.SAVED_USER,
>             page: () => SavedUserView(),
>             binding: SavedUserBinding(),
>           ),
>           GetPage(
>             name: _Paths.DETAILS_USER,
>             page: () => DetailsUserView(),
>             binding: DetailsUserBinding(),
>           ),
>         ]),
> ```
> 
> ```dart
> final http.Response response =
>           await FarmerRegisterRepository.upload(data, onSend);
>       if (response.statusCode! >= 200 && response.statusCode! < 300) {
>         if (response.data["status"] == "success") {
>            //the error will show up when below executed
>            //MANAGE_USER = "/manage-user" DETAILS_USER = "/details-user"
>           Get.toNamed(Routes.MANAGE_USER + Routes.DETAILS_USER);
>           //  /manage-user/new-user ==> /manage-user/details-user
>         }
>       }
> ```
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> the new-user page contains form (to register user)
> 4. See error
> 
> ```
> ======== Exception caught by widgets library =======================================================
> The following assertion was thrown while finalizing the widget tree:
> Duplicate GlobalKeys detected in widget tree.
> 
> The following GlobalKeys were specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The keys were:
> - [GlobalKey#c247d]
>   [LabeledGlobalKey<OverlayState>#d5ee0]
> This was determined by noticing that after widgets with the above global keys were moved out of their respective previous parents, those previous parents never updated during this frame, meaning that they either did not update at all or updated before the widgets were moved, in either case implying that they still think that they should have a child with those global keys.
> The specific parents that did not update after having one or more children forcibly removed due to GlobalKey reparenting are:
> - IgnorePointer(ignoring: false, renderObject: RenderIgnorePointer#0f539 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE DETACHED)
>   UnmanagedRestorationScope
> A GlobalKey can only be specified on one widget at a time in the widget tree.
> When the exception was thrown, this was the stack: 
> #0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2939:15)
> #1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2964:8)
> #2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:879:19)
> #3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:330:5)
> #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
> #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
> #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
> #10     _invoke (dart:ui/hooks.dart:164:10)
> #11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
> #12     _drawFrame (dart:ui/hooks.dart:127:31)
> (elided 3 frames from dart:async)
> ====================================================================================================
> ```
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> I test to change the route to other route like Routes.SETTINGS and its no problem.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/58933926/128346754-55cc7e94-d665-4907-a963-62d3f78d4b76.png)
> 
> **Flutter Version:**
> LATEST
> 
> **Getx Version:**
> 4.3.4
> 
> **Describe on which device you found the bug:**
> Redmi 8
> 
> **Minimal reproduce code**

1- you can not add empty spaces on route name
2- you can not to use Get.to to namedRoutes (use Get.toNamed)
