### ISSUE TITLE
Navigation error 

### ISSUE THREAD

**Issue by shubham-150** [jonataslaw/getx#1729]
The relevant error-causing widget was: 
  Directionality file:///Users//Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.3.4/lib/get_navigation/src/root/get_material_app.dart:217:12
When the exception was thrown, this was the stack: 
#0      PageRedirect.page (package:get/get_navigation/src/routes/route_middleware.dart:199:50)
#1      GetMaterialApp.initialRoutesGenerate (package:get/get_navigation/src/root/get_material_app.dart:212:9)
#2      _WidgetsAppState.build.<anonymous closure> (package:flutter/src/widgets/app.dart:1533:51)
#3      NavigatorState.restoreState (package:flutter/src/widgets/navigator.dart:3439:41)
#4      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:984:5)
...
====================================================================================================

and the error is from the get_material_app.dart widget :
Widget defaultBuilder(BuildContext context, Widget? child) {
    return Directionality(
      textDirection: textDirection ??
          (rtlLanguages.contains(Get.locale?.languageCode)
              ? TextDirection.rtl
              : TextDirection.ltr),
      child: builder == null
          ? (child ?? Material())
          : builder!(context, child ?? Material()),
    );
  }

**Comment by eduardoflorence** [comment]
Hi @shubham-150, you did not respect the template for creating an issue. It is necessary to provide a minimum code for us to reproduce the error just by copying and pasting it into our IDE. It is also necessary to provide your environment (version of Flutter and GetX). Please do this otherwise we will have to close this issue.

**Comment by shubham-150** [comment]
On debugging  debugger take to this file:
Initially I am Gettin a error call null check used on a null value.
![flutter_01](https://user-images.githubusercontent.com/86223005/128357568-d04dfb88-0e61-496e-87aa-6de8a9616344.png)



GetMaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: splash,
      defaultTransition: Transition.fade,
      getPages: NavRouter.generateRoute,
      title: AppStrings.appName,
      theme: ThemeData(
        textSelectionTheme: TextSelectionThemeData(
          cursorColor: AppColors.primaryColor,
        ),

        fontFamily: 'Roboto',
        primaryColor: AppColors.primaryColor,
        // textTheme: GoogleFonts.redHatDisplayTextTheme(),
        //    primarySwatch: AppColors.primaryColor,
        splashColor: Colors.transparent,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
    );
    Flutter:2.2.3
    Get: 4.3.4

**Comment by shubham-150** [comment]
Also Router is
class NavRouter {
  static final generateRoute = [
    GetPage(
      name: splash,
      page: () => Splash(),
    ),];}
const String splash = 'splash';

**Comment by jonataslaw** [comment]
const String splash = '/splash';

**Comment by shubham-150** [comment]
this solves the problem
