### ISSUE TITLE
A bug with dialog

### ISSUE THREAD

**Issue by Asuraxxx** [jonataslaw/getx#1757]
In the main page, routing name '/', if we open a dialog, and in that dialog open and pop a page, we can not enter that page again, as it is considered a duplicate page. If we print Get.routing.current, it is now set to be  the page we just poped and Get.routing.previous is set to be the dialog. Aren't they supposed to be '/' (current) and the page we poped (previous)? 

My quick fix is to manually set Get.routing.current = '/' and Get.routing.previous=(the page just poped).  This looks like the same bug as #1751.

**Comment by jonataslaw** [comment]
Fixed on get 4.3.7
