### ISSUE TITLE
Initial route as the first page in Flutter web before any other page

### ISSUE THREAD

**Issue by ivanh12** [jonataslaw/getx#1761]
**Describe the bug**
I want to have my initialRoute as the first page whenever a user tried to access another page. As for now, I have 2 pages MainHomePage() and TransactionDetailPage(). 
When I try to access TransactionDetailPage directly by typing http://localhost:64289/transaction/1 in my web browser URL, it doesn't push my MainHomePage screen first (It doesn't have a back button on the AppBar of TransactionDetailPage).
What I want to achieve is whenever a user tried to access any of my pages (directly by URL), I want the initialRoute page as the first page so there's always a back button to pop the current screen to my home page.

**main.dart**
```Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter test',
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      getPages: [
        GetPage(
           name: '/',
           page: () => MainHomePage(),
        ),
        GetPage(
           name: '/transaction/:id',
           page: () => TransactionDetailPage(),
        ),
      ],
    );
  }
```

**Flutter Version:**
Flutter 2.2.1

**Getx Version:**
get: ^4.3.6

**Comment by jonataslaw** [comment]
Open a `feature request` (not issue) with its correct form, and we can see if this will be possible in the future.

**Comment by ivanh12** [comment]
Didn't know this is not a feature yet, Thanks!
