### ISSUE TITLE
Get Package Not work

### ISSUE THREAD

**Issue by arupnaskarbkp** [jonataslaw/getx#1762]
Update Get package new version than all project code show the error. not import 'package:get/get.dart'.
How to fix ??
![image](https://user-images.githubusercontent.com/40661263/129242444-2cc7de3e-959d-4be3-82f9-9e7f2d419b1b.png)
![image](https://user-images.githubusercontent.com/40661263/129242504-54b4cb3d-6eac-459d-b6e3-1a57a80b9c17.png)

**Comment by jonataslaw** [comment]
flutter pub get

**Comment by arupnaskarbkp** [comment]
Every time flutter pub get ...but not work

**Comment by jonataslaw** [comment]
please, put this on terminal and paste here:
flutter doctor -v

**Comment by arupnaskarbkp** [comment]
![16287912667815942887182613033040](https://user-images.githubusercontent.com/40661263/129246091-4123dbf2-8d2b-44b8-b38b-301ea3663af2.jpg)

**Comment by arupnaskarbkp** [comment]
I add git url direct than properly work get package ...
But get 4.3.7 add...than not work

**Comment by arupnaskarbkp** [comment]
Finally solve this issue

**Comment by jonataslaw** [comment]
What was your problem?

**Comment by arupnaskarbkp** [comment]
I don't know...but 2 hours later .. open my project than run flutter pub get than solve issue
