### ISSUE TITLE
Nav2 `toNamed` deletes the history making back button skip previous routes

### ISSUE THREAD

**Issue by WangHansen** [jonataslaw/getx#1767]
**Describe the bug**
Nav2 `Get.rootDelegate.toNamed` seems to remove the routing history

**Reproduction code

I have the route setup as follows:
```dart
abstract class Routes {
  Routes._();

  static const AUTH = _Paths.AUTH;
  // /auth/phone
  static const AUTH_PHONE_SIGNIN = _Paths.AUTH + _Paths.AUTH_PHONE_LOGIN;
  // /auth/phoneVerification
  static const AUTH_PHONE_VERIFY = _Paths.AUTH + _Paths.AUTH_PHONE_VEIFY;
}

abstract class _Paths {
  static const String AUTH = '/auth';
  static const String AUTH_PHONE_LOGIN = '/phone';
  static const String AUTH_PHONE_VEIFY = '/phoneVerification';
}

static final routes = [
    GetPage(
        name: '/',
        page: () => RootView(),
        binding: RootBinding(),
        participatesInRootNavigator: true,
        preventDuplicates: true,
        children: [
          // Auth related
          GetPage(
              name: _Paths.AUTH,
              page: () => LoginView(),
              binding: LoginBinding(),
              children: [
                GetPage(
                    name: _Paths.AUTH_PHONE_LOGIN,
                    page: () => PhoneSignInView(),
                    binding: PhoneAuthBinding()),
                GetPage(
                    name: _Paths.AUTH_PHONE_VEIFY,
                    page: () => PhoneVerificationView(),
                    binding: PhoneAuthBinding())
              ]),
  ];

class RootView extends GetView<RootController> {
  @override
  Widget build(BuildContext context) {
    return GetRouterOutlet.builder(
      builder: (context, delegate, current) {
        final title = current?.location;
        return Scaffold(
          resizeToAvoidBottomInset: false,
          appBar: AppBar(
            title: Text(title ?? ''),
            centerTitle: true,
          ),
          body: GetRouterOutlet(
            initialRoute: Routes.AUTH,
          ),
        );
      },
    );
  }
}
```

`LoginView` contains a button when clicked will navigate to `PhoneSignInView` which asks users for their phone numbers. After verify user's phone number, it navigates to `PhoneVerificationView` by `Get.rootDelegate.toNamed(Routes.AUTH_PHONE_VERIFY);` 
However, when I press the back button offered by `AppBar` on the `PhoneVerificationView`, it doesn't go back the `PhoneSignInView`, instead it goes straight back to `LoginView`

**To Reproduce**
1. Go to `PhoneSignInView`
2. Navigate to `PhoneVerificationView` with `Get.rootDelegate.toNamed(Routes.AUTH_PHONE_VERIFY);` 
3. Press back button with `AppBar`

**Expected behavior**
Expect it to go back to `PhoneSignInView`

**Screenshots**

https://user-images.githubusercontent.com/15679461/129310394-2482ff99-4db7-428c-b81c-032141a267a3.mp4

**Flutter Version:**
Latest

**Getx Version:**
4.3.5

**Describe on which device you found the bug:**
Mi 9 Android 11

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jonataslaw** [comment]
Please, insert a reproduce code

**Comment by WangHansen** [comment]
@jonataslaw here: https://github.com/WangHansen/getx_test. I tried to repro from my code but the nested route just stopped working all together. Maybe you can take a look at that as well

**Comment by jonataslaw** [comment]
are you using the last version?

**Comment by WangHansen** [comment]
> are you using the last version?

Oh, I didn't realize there was a new version today. Let me try the latest version and get back to you! Thanks for the hard work!

**Comment by WangHansen** [comment]
> are you using the last version?

Yes, I am on 4.3.8 for the repro codebase

**Comment by WangHansen** [comment]
Same code with 4.3.7:

https://user-images.githubusercontent.com/15679461/129408141-56103179-a0b1-4889-aa81-ad7eb601bb72.mp4

When upgraded to 4.3.8, navigation stops working:


https://user-images.githubusercontent.com/15679461/129408186-cbd4cb7f-4e4e-4b73-af8c-7c915fc37844.mp4

**Comment by ahmednfwela** [comment]
@jonataslaw Please roll back this, it's causing too many issues https://github.com/jonataslaw/getx/blob/master/lib/get_navigation/src/nav2/router_outlet.dart#L93
@WangHansen you need to override the logic for the back button in the app bar to call `Get.rootDelegate.popRoute`, since the default one calls the root navigator pop

**Comment by WangHansen** [comment]
> @jonataslaw Please roll back this, it's causing too many issues https://github.com/jonataslaw/getx/blob/master/lib/get_navigation/src/nav2/router_outlet.dart#L93
> @WangHansen you need to override the logic for the back button in the app bar to call `Get.rootDelegate.popRoute`, since the default one calls the root navigator pop

@ahmednfwela Thanks for letting me know, however, `Get.rootDelegate.popRoute` behave exactly the same as the system supplied back button where both pages are poped. Do I need to supply any params?

**Comment by ahmednfwela** [comment]
@WangHansen the pop mode needs to be set to history

**Comment by WangHansen** [comment]
> @WangHansen the pop mode needs to be set to history

Thanks, it works now for the back button. But if I swipe right on screen (system back), it still behaves the old way. Is there some setting I can change for system level? Also, I am not quite sure if I understand the history mode very well. Can you point me to some docs that I can read through, thank!

**Comment by ahmednfwela** [comment]
For now the new navigation system is still incomplete with some things to solve, so it's not fully documented yet.
The system back should work normally though
