### ISSUE TITLE
GetRouterOutlet sobrescreve a page raiz com a chamada

### ISSUE THREAD

**Issue by kauemurakami** [jonataslaw/getx#1776]
Tive um problema com o comportamento do GetRouterOutlet, não em sua implementação em sí tendo como base o exemplo disponível [nav_example2](https://github.com/jonataslaw/getx/blob/master/example_nav2/lib/app/modules/home/views/home_view.dart).

Antes de mais nada um vídeo curto do resultado.
[VIDEO CURTO DO RESULTADO](https://drive.google.com/file/d/1lMBJkHb2oCmeo5hCB2uy8Q9yAnSFWm-q/view?usp=sharing)

Resumindo, ele não está reconstruindo parcialmente a tela, mas sobrescrevendo-a com a page chamada em questão.

Código de reprodução
**main.dart**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get/get_navigation/src/root/get_material_app.dart';
import 'package:getx_pattern_site/app/modules/dashboard/binding.dart';
import 'package:getx_pattern_site/routes/pages.dart';
import 'package:url_strategy/url_strategy.dart';

void main() {
  setPathUrlStrategy();
  runApp(GetMaterialApp.router(
    debugShowCheckedModeBanner: false,
    //initialBinding: DashboardBinding(),
    getPages: AppPages.pages,
    /*initialBinding: BindingsBuilder(
        () {
          Get.put(AuthService());
        },
      ),*/
    routeInformationParser: GetInformationParser(
      initialRoute: Routes.DASHBOARD,
    ),
    routerDelegate: GetDelegate(
      backButtonPopMode: PopMode.History,
      preventDuplicateHandlingMode: PreventDuplicateHandlingMode.ReorderRoutes,
    ),
  ));
}

```
Página dashboard, onde no exemplo seria a home, a dashboard é minha raiz para navegar para as outras páginas.
Não as incluirei na reprodução por serem paginas simples ( Scaffold, safe area e texto)
**dashboard.dart**
```dart
class DashboardPage extends GetView<DashboardController> {
  @override
  Widget build(BuildContext context) {
    return GetRouterOutlet.builder(
      builder: (context, delegate, currentRoute) {
        //This router outlet handles the appbar and the bottom navigation bar
        var currentLocation = currentRoute?.location!;
        var index = 0;
        if (currentLocation?.startsWith(Routes.INTRO) == true) {
          index = 1;
        }
        if (currentLocation?.startsWith(Routes.GET_START) == true) {
          index = 2;
        }
        return Scaffold(
          body: GetRouterOutlet(
            //anchorRoute: Routes.DASHBOARD,
            initialRoute: Routes.HOME,
            //anchorRoute: Routes.DASHBOARD,
            key: Get.nestedKey(Routes.DASHBOARD),
          ),
          bottomNavigationBar: BottomNavigationBar(
            currentIndex: index,
            onTap: (value) {
              switch (value) {
                case 0:
                  delegate.toNamed(Routes.HOME);
                  break;
                case 1:
                  delegate.toNamed(Routes.INTRO);
                  break;
                case 2:
                  delegate.toNamed(Routes.GET_START);
                  break;
                default:
              }
            },
            items: [
              // _Paths.HOME + [Empty]
              BottomNavigationBarItem(
                icon: Icon(
                  Icons.home,
                  color: index == 0 ? Colors.black : Colors.grey,
                ),
                label: 'Home',
              ),
              // _Paths.HOME + Routes.PROFILE
              BottomNavigationBarItem(
                icon: Icon(
                  Icons.account_box_rounded,
                  color: index == 1 ? Colors.black : Colors.grey,
                ),
                label: 'Intro',
              ),
              BottomNavigationBarItem(
                icon: Icon(
                  Icons.account_box_rounded,
                  color: index == 2 ? Colors.black : Colors.grey,
                ),
                label: 'Começando',
              ),
            ],
          ),
        );
      },
    );
  }
}

``` 
**To Reproduce**
1. flutter run
2. Click no botão do "menu" esquerdo.

**Flutter Version:**
latest
**Getx Version:**
latest

**Describe on which device you found the bug:**
ex: RedmiNote 8 pro e Chrome

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jonataslaw** [comment]
Marcou a rota como rootNavigatior no GetPages?

**Comment by kauemurakami** [comment]
Não me atentei nas alterações no arquivo pages, vacilo meu.
Mas pra fecharmos o caso rootNavigator seria o       ```participatesInRootNavigator: true,```
Como a primeira rota do seu arquivo exemplo?
```dart GetPage(
      name: '/',
      page: () => RootView(),
      binding: RootBinding(),
      participatesInRootNavigator: true,
      preventDuplicates: true,
      children: [
        GetPage(
          middlewares: [
            //only enter this route when not authed
            EnsureNotAuthedMiddleware(),
          ],
          name: _Paths.LOGIN,
          page: () => LoginView(),
          binding: LoginBinding(),
        ),```

Ja agradeço a atenção como sempre !! Vou lançar alguns exemplos com isso pra te prevenir de mais dúvidas como essa rsrsr.
 <3

**Comment by jonataslaw** [comment]
Isso, inserir isso na página pai permite que as páginas filhas sejam abertas dentro dela

**Comment by kauemurakami** [comment]
Não criaram ainda algum exemplo apenas de uma nav semples? ATÉ HOJE, não consegui reproduzir NADA, sempre tem algum bug.
O que mais me deixou assustado foi duplicar o bottom navigator e vi que até hoje ainda existem muitas issues sobre isso, tentei várias vezes tentar criar um exemplo para reprodução, mas nenhum sucesso, caso tenha alguma outra aplicação disso disponível, gostaria de tentar rever melhor isso.

**Comment by kauemurakami** [comment]
@jonataslaw
Não criaram ainda algum exemplo apenas de uma nav simples? ATÉ HOJE, não consegui reproduzir NADA, sempre tem algum bug.
O que mais me deixou assustado foi duplicar o bottom navigator e vi que até hoje ainda existem muitas issues sobre isso, tentei várias vezes tentar criar um exemplo para reprodução, mas nenhum sucesso, caso tenha alguma outra aplicação disso disponível, gostaria de tentar rever melhor isso.
