### ISSUE TITLE
GetConnect - HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:359))

### ISSUE THREAD

**Issue by HenryDeveloper** [jonataslaw/getx#1780]
I have a problem, when I try to make a post from a class that extends GetConnect, it returns the following exception:

HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate (handshake.cc:359))

The code is the next:

```dart
class AuthenticationService extends GetConnect {
  late final SharedPreferences prefs;
  @override
  Future onInit() async {
    httpClient.baseUrl = "https://192.168.156.1412:45455/api"; // I'm doing the tests in a local url for example: 192.168.x.x:{port}/api
    httpClient.timeout = Duration(seconds: 20); // tests duration
    prefs = await SharedPreferences.getInstance();
  }

  Future<bool> login(LoginDTO login) async {
    var response = await post<LoginDTO>("/login", login);
    if (response.hasError) return false;

    var user = response.body;
    var validUser = user!.isEmpty();

    if (validUser) {
      await prefs.setString("token", user.token);
    }

    return validUser;
  }
}
```
1. Press click to login
2. The call arrives at the service where it sent a request to log in (local server - debug mode)
3. and when the request is sent it returns that error

**Expected behavior**
what is expected is that the information of the user who is logging in will return.

**Flutter Version:**
Enter the version of the Flutter you are using
![image](https://user-images.githubusercontent.com/11890226/129811052-26b9f169-9951-4383-8137-4368158c1a47.png)

**Getx Version:**
get: 4.3.5

**Describe on which device you found the bug:**
Pixel 3 API 30 - android emulator

**Some solutions that I have used but have not worked for me:**
https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req

Just a clarification, before I was using Dio and it worked correctly, but I don't want to use it anymore, since GetX has everything that is necessary to avoid using other external http libraries.

And thank the team, since GetX is a wonderful library, I personally come from Provider and Mobx and none of them convince me, but GetX is different, the team behind all this is great!

Thanks in advance.

**Comment by jasonlaw** [comment]
Have you tried set the  allowAutoSignedCert to true?

**Comment by HenryDeveloper** [comment]
Hello @jasonlaw,

to be honest no, let me try it and let you know.

thanks for your fast reply :D

**Comment by HenryDeveloper** [comment]
Thanks a million @jasonlaw!!! Works as expected once the allowAutoSignedCert property is set to true.

Here I leave the code in case someone else is helpful:
```dart
class AuthenticationService extends GetConnect {
  late final SharedPreferences prefs;
  @override
  Future onInit() async {
    allowAutoSignedCert = true;
    httpClient.baseUrl = "https://192.168.156.1412:45455/api"; // I'm doing the tests in a local url for example: 192.168.x.x:{port}/api
    httpClient.timeout = Duration(seconds: 20); // tests duration
    prefs = await SharedPreferences.getInstance();
  }

  Future<bool> login(LoginDTO login) async {
    var response = await post<LoginDTO>("/login", login.toJson());
    if (response.hasError) return false;

    var user = response.body;
    var validUser = user!.isEmpty();

    if (validUser) {
      await prefs.setString("token", user.token);
    }

    return validUser;
  }
}
```

Again, thank you very much GetX team!

**Comment by HenryDeveloper** [comment]
Hello @jasonlaw, I have another problem, not so related to the main title, but within the same method that I shared, when the call returns the user's information I get the following error:

![image](https://user-images.githubusercontent.com/11890226/129818705-a6a23385-345e-46f2-9d84-002df2e1be20.png)

I understand that it is something related to the deserialization of the object, but I understand, according to the documentation the deserialization is done automatically, the normal thing would be to have 2 methods:
-one to serialize 
-and the other to deserialize

For example:
```dart
class LoginDTO {
  String id;
  String firstname;
  String lastname;
  String email;
  String username;
  String password;
  String token;

  LoginDTO(
      {this.id = '',
      this.firstname = '',
      this.lastname = '',
      this.email = '',
      this.username = '',
      this.password = '',
      this.token = ''});

  bool isEmpty() {
    return id == '' &&
        firstname == '' &&
        lastname == '' &&
        email == '' &&
        password == '' &&
        token == '';
  }

  // LoginDTO.fromJson(Map<String, dynamic> json) {
  //   id = json['id'];
  //   firstname = json['firstname'];
  //   lastname = json['lastname'];
  //   email = json['email'];
  //   username = json['username'];
  //   password = json['password'];
  //   token = json['token'];
  // }

  Map<String, dynamic> toJson() {
    var data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['firstname'] = this.firstname;
    data['lastname'] = this.lastname;
    data['email'] = this.email;
    data['username'] = this.username;
    data['password'] = this.password;
    data['token'] = this.token;

    return data;
  }
}
```
but I understand that this is not necessary in GetX or I don't know if I am misinterpreting how getX works here.

I don't know if we can see this problem here or would I have to open another issue?

Thanks in advance

**Comment by HenryDeveloper** [comment]
Closing issue since it's solved
