### ISSUE TITLE
Nav2 - GetRouterOutlet has grey color on its left side.

### ISSUE THREAD

**Issue by gorkemsari** [jonataslaw/getx#1782]
**Describe the bug**
GetRouterOutlet has grey color on its left side. If I add some padding or widgets (like NavigationRail) on left of GetRouterOutlet, it gives grey color variant on it.

**Reproduction code**
I have added padding to GetRouterOutlet part on code to reproduce it on nav2 example.

example_nav2:
app/modules/root/views/root_view.dart

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../../routes/app_pages.dart';
import '../controllers/root_controller.dart';
import 'drawer.dart';

class RootView extends GetView<RootController> {
  @override
  Widget build(BuildContext context) {
    return GetRouterOutlet.builder(
      builder: (context, delegate, current) {
        final title = current?.location;
        return Scaffold(
          drawer: DrawerWidget(),
          appBar: AppBar(
            title: Text(title ?? ''),
            centerTitle: true,
          ),
          body: Container(
            padding: EdgeInsets.only(left: 200.0, right: 200.0, top: 200.0, bottom: 200.0),
            child: GetRouterOutlet(
              initialRoute: Routes.HOME,
              // anchorRoute: '/',
              // filterPages: (afterAnchor) {
              //   return afterAnchor.take(1);
              // },
            ),
          ),
        );
      },
    );
  }
}
```

**To Reproduce**
1. Add padding or some widgets to left of GetRouterOutlet

**Expected behavior**
There shouldn't be any color changes on left of GetRouterOutlet.

**Screenshots**
![image](https://user-images.githubusercontent.com/29121464/129910842-bb7068cc-5f06-4941-bbce-e1b4cfafd434.png)

**Flutter Version:**
2.2

**Getx Version:**
4.3.8

**Describe on which device you found the bug:**
Chrome
Version 92.0.4515.131 (Official Build) (x86_64)

**Comment by gorkemsari** [comment]
@ahmednfwela Do you have any idea?

**Comment by ahmednfwela** [comment]
this is an issue only on macos, https://github.com/flutter/flutter/issues/86317
since I don't have a macos I can't reproduce the issue without getx.
if you can figure out what's the problem outside of getx, that would be helpful

**Comment by gorkemsari** [comment]
I have defined "defaultTransition: Transition.fade" then problem solved. I think it is about left transitions.

![image](https://user-images.githubusercontent.com/29121464/129918023-e2af58fa-5fce-4357-8961-6d6d9d846d01.png)

**Comment by Mateusvaz89** [comment]
add in your main ThemeData:    pageTransitionsTheme: const PageTransitionsTheme(builders: {
            TargetPlatform.iOS: FadeUpwardsPageTransitionsBuilder(),
            TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
          }),
