### ISSUE TITLE
Function isPrepared is Error or Not?

### ISSUE THREAD

**Issue by tianchouczl** [jonataslaw/getx#1789]
https://github.com/jonataslaw/getx/blob/16dc728a7a096acc57aa7c214c335ff8d6ff1fbb/lib/get_instance/src/get_instance.dart#L471-L482

`if (!builder.isInit) {
      return true;
    }`
maybe return false?

**Comment by jonataslaw** [comment]
If the dependency has not yet been initialized, but is in the registered dependency pool, return true
