### ISSUE TITLE
Build project cause error 'dart:html'

### ISSUE THREAD

**Issue by kingmaster772** [jonataslaw/getx#1799]
Does it come with a new version of this plugin? Because this happens after upgrading the version.

```
/C:/FlutterSDK/flutter2.2.2/.pub-cache/hosted/pub.dartlang.org/get-4.3.8/lib/get_connect/sockets/src/sockets_html.dart:4:8: Error: Not found: 'dart:html'
import 'dart:html';
```

I've been trying to do `flutter clean`, 'Invalidate Cache/Restart', switching channel between stable and beta, reinstall dependency and does nothing

**Comment by jonataslaw** [comment]
I think you must be doing some wrong import somewhere.

**Comment by kingmaster772** [comment]
I just accidentally fix this issue by running `flutter clean` in 2-3 times, remove `get: ^4.1.4`, running `pub get`, re-insert `get: ^4.1.4` and finally `flutter run`. Anyway thanks for your response.
