### ISSUE TITLE
PageRoute argument for CustomTransition

### ISSUE THREAD

**Issue by seel-channel** [jonataslaw/getx#1818]
**Is your feature request related to a problem? Please describe.**
I'm using the Transition.cupertino but I don't like its box shadow. I created my own Cupertino transition but I can't use it as CustomTransition.buildTransition(), because I need the PageRoute argument (It doesn't have the RoutePage argument, it only has BuildContext)

**Describe the solution you'd like**
Add PageRoute argument to buildTranstion method of CustomTransition.

```dart
abstract class CustomTransition {
  Widget buildTransition(
    PageRoute route,
    BuildContext context,
    Curve? curve,
    Alignment? alignment,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget child,
  );
}
```

**Comment by roiskhoiron** [comment]
i have same error for buildTransition with red coution, how to fix it

**Comment by appinteractive** [comment]
Amy workarounds for this? I'm also searching for ways to get custom transitions working.

**Comment by jonataslaw** [comment]
If you have context access, I assume it's possible to access your route, have you tested this?

` final pageRoute = ModalRoute.of(context);`

**Comment by seel-channel** [comment]
I just tested now. But it doesn't work. I couldn't covert ModelRoute to PageRoute because It's a abstract class

**Comment by jonataslaw** [comment]
final pageRoute = ModalRoute.of(context) as PageRoute;
