### ISSUE TITLE
TextEditingController  is not reinitialized after disposed TextEditingController

### ISSUE THREAD

**Issue by anypwx** [jonataslaw/getx#1825]
**Describe the bug**
There is a certain chance that an error will be reported. The content of the error is that the controller has been disposed, causing the Textfield to fail to input after disposed TextEditingController . In other words, TextEditingController  is not reinitialized

**Exception log**

The following assertion was thrown while handling a gesture:
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:234:12)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:309:5)
#4      TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:185:11)

**Reproduction code

```dart
class LoginController extends BaseController {
  final tabIndex = 1.obs;
  final isPwdShow = false.obs;
  final phoneController = TextEditingController();
  final codeController = TextEditingController();
  final accountController = TextEditingController();
  final pwdController = TextEditingController();

  final ac = FocusNode();
  final pw = FocusNode();

  final userEnterpriseList = <UserEnterpriseList>[].obs;
  final checkEnterprise = UserEnterpriseList().obs;

  @override
  void onInit() {
    getEnterpriseList();
    super.onInit();
  }

  @override
  void onReady() {
    super.onReady();
  }

  @override
  void onResumed() {
    super.onResumed();
  }

  @override
  void onInactive() {
    super.onInactive();
  }

  @override
  void onPaused() {
    super.onPaused();
  }

  @override
  void onClose() {
    super.onClose();
    disposeWidget();
  }

  void disposeWidget() {
     phoneController.dispose();
    codeController.dispose();
    accountController.dispose();
    pwdController.dispose();

    ac.dispose();
    pw.dispose();
  }
}
```

**Expected behavior**
call Get.back  

**Flutter Version:**
    • Flutter version 2.2.3 at F:\flutter_sdk\flutter_windows_1.22.6-stable\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Getx Version:**
get: ^4.3.4

**Describe on which device you found the bug:**
A6 (mobile) • KS05550091603469 • android-arm64  • Android 10 (API 29)

**Comment by anypwx** [comment]
> **Describe the bug**
> There is a certain chance that an error will be reported. The content of the error is that the controller has been disposed, causing the Textfield to fail to input after disposed TextEditingController . In other words, TextEditingController is not reinitialized
> **Exception**
> The following assertion was thrown while handling a gesture:
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:234:12)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:309:5)
#4      TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:185:11)
> 
> **Reproduction code
> 
> ```dart
> class LoginController extends BaseController {
>   final tabIndex = 1.obs;
>   final isPwdShow = false.obs;
>   final phoneController = TextEditingController();
>   final codeController = TextEditingController();
>   final accountController = TextEditingController();
>   final pwdController = TextEditingController();
> 
>   final ac = FocusNode();
>   final pw = FocusNode();
> 
>   final userEnterpriseList = <UserEnterpriseList>[].obs;
>   final checkEnterprise = UserEnterpriseList().obs;
> 
>   @override
>   void onInit() {
>     getEnterpriseList();
>     super.onInit();
>   }
> 
>   @override
>   void onReady() {
>     super.onReady();
>   }
> 
>   @override
>   void onResumed() {
>     super.onResumed();
>   }
> 
>   @override
>   void onInactive() {
>     super.onInactive();
>   }
> 
>   @override
>   void onPaused() {
>     super.onPaused();
>   }
> 
>   @override
>   void onClose() {
>     super.onClose();
>     disposeWidget();
>   }
> 
>   void disposeWidget() {
>      phoneController.dispose();
>     codeController.dispose();
>     accountController.dispose();
>     pwdController.dispose();
> 
>     ac.dispose();
>     pw.dispose();
>   }
> }
> ```
> 
> **Expected behavior**
> call Get.back
> 
> **Flutter Version:**
> • Flutter version 2.2.3 at F:\flutter_sdk\flutter_windows_1.22.6-stable\flutter
> • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
> • Engine revision 241c87ad80
> • Dart version 2.13.4
> • Pub download mirror https://pub.flutter-io.cn
> • Flutter download mirror https://storage.flutter-io.cn
> 
> **Getx Version:**
> get: ^4.3.4
> 
> **Describe on which device you found the bug:**
> A6 (mobile) • KS05550091603469 • android-arm64 • Android 10 (API 29)

**Comment by maares** [comment]
@anypwx could you please add min reprod. code

**Comment by anypwx** [comment]
> @anypwx could you please add min reprod. code

Im call dispose on here in contorller

'''
@override
  void onClose() {
    super.onClose();
    disposeWidget();
  }

  void disposeWidget() {
     phoneController.dispose();
    codeController.dispose();
    accountController.dispose();
    pwdController.dispose();

    acFocusNode.dispose();
    pwFocusNode.dispose();
  }

'''

go to login page after call signOut
'''
static void signOut() async {
     await SpUtil.cleanAccountInfo();
     await WebSocketManager.instance.logout();
     // await Get.delete<IndexController>();
     PageUtil.pushAndRemoveAllPages(null, "/login");
   }
'''

this's route.
'''
  getPages: [
                          GetPage(
                            name: '/',
                            page: () => WelcomePage(), //欢迎页
                            binding:
                                BindingsBuilder.put(() => WelcomeController()),
                          ),
                          GetPage(
                            name: '/login',
                            page: () => LoginPage(), //登录页
                            binding:
                                BindingsBuilder.put(() => LoginController()),
                          ),
                          GetPage(
                            name: '/index',
                            page: () => IndexPage(), //首页
                            binding:
                                BindingsBuilder.put(() => IndexController()),
                          )
]
'''

When I log out frequently and jump to the login page, there is a certain chance that the Textfield on the login page cannot be entered, the focus is not obtained, and there is no response when I click

**Comment by RuizeMT** [comment]
@FlorianHeuse Try to use the predicate parameter so the destination wouldn't be remove

Get.offAllNamed(routeName, predicate: (route) => Get.currentRoute == routeName);

**Comment by AtiaDjaber** [comment]
same problem with me

**Comment by anypwx** [comment]
> @anypwx Try to use the predicate parameter so the destination wouldn't be remove
> 
> Get.offAllNamed(routeName, predicate: (route) => Get.currentRoute == routeName);

I solved it  : Get.offAllNamed(routeName, predicate: ModalRoute.withName(routeName));

**Comment by anypwx** [comment]
> same problem with me

use it,   Get.offAllNamed(routeName, predicate: ModalRoute.withName(routeName));

**Comment by AristideNestor** [comment]
Same issue after using `Get.offAllNamed(routeName);`
After disposing controller on a previous page

Provided solutions did not solve it
