### ISSUE TITLE
Can Obx return a nullable widget?

### ISSUE THREAD

**Issue by MoonyDevs** [jonataslaw/getx#1829]
Hello all, 

Thank you for the framework.

I would ask if it would be possible to make Obx, Getx builder etc return a nullable widget?

My use case if for the leading attribute of AppBar, in some case I want to show a leading and after some update I want to hide it or vice-versa. 

Thank you,

**Comment by jonataslaw** [comment]
No widget can return a nullable widget.
Obx just like any other widget, cannot do this.

**Comment by JarvanMo** [comment]
Hi @MoonyDevs, how to handle this case? I have the same issue with Obx.

**Comment by sulthanalihsan** [comment]
Hi, @jonataslaw any solution for this question ?
