### ISSUE TITLE
Getting error when calling Get.reset() to clear GetxService

### ISSUE THREAD

**Issue by manikantag** [jonataslaw/getx#1844]
**Describe the bug**
Getting `Null check operator used on a null value` error when calling `Get.reset()` to clear `AuthService` on logout.

Exception is thrown from `route_middleware.dart`:

```dart
  // redirect all pages that needes redirecting
  GetPageRoute<T> getPageToRoute<T>(GetPage rou, GetPage? unk) {
    while (needRecheck()) {}
    final _r = (isUnknown ? unk : rou)!;  // <-------- This non-null check is causing the error
```

**Stack trace**
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building Builder:
Null check operator used on a null value

The relevant error-causing widget was
GetMaterialApp
lib/test.dart:7
When the exception was thrown, this was the stack
#0      PageRedirect.getPageToRoute
package:get/…/routes/route_middleware.dart:228
#1      GetPage.createRoute
package:get/…/routes/get_route.dart:186
#2      NavigatorState.restoreState
package:flutter/…/widgets/navigator.dart:3419
#3      RestorationMixin._doRestore
package:flutter/…/widgets/restoration.dart:984
#4      RestorationMixin.didChangeDependencies
package:flutter/…/widgets/restoration.dart:970
...

```

**Reproduction code**

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(GetMaterialApp.router(
    title: 'Test',
    initialBinding: BindingsBuilder.put(() => AuthService(), permanent: true),
    getPages: [
      GetPage(
        name: '/',
        page: () => LoginScreen(),
        binding: BindingsBuilder.put(() => LoginController()),
      ),
      GetPage(
        name: '/home',
        page: () => HomeScreen(),
        binding: BindingsBuilder.put(() => HomeController()),
      ),
    ],
  ));
}

class AuthService extends GetxController {
  Rx<bool> isAuthenticated = false.obs;
  Rx<int> authCounter = 0.obs;

  void doLogin() {
    isAuthenticated.value = true;
  }

  void doLogout() {
    isAuthenticated.value = false;
    Get.rootDelegate.offNamed('/');
    Get.reset();
    // Get.deleteAll(force: true);
  }
}

class LoginController extends GetxController {
  final authService = Get.find<AuthService>();

  bool isLoggedin() => authService.isAuthenticated.value == true;

  void login() {
    authService.doLogin();
    Get.rootDelegate.offNamed('/home');
  }
}

class LoginScreen extends GetView<LoginController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Obx(
          () => controller.isLoggedin()
              ? Text('Already logged in -> Logout (state not cleared)')
              : ElevatedButton(
                  onPressed: controller.login,
                  child: Text(
                    'Login (authCounter: ${controller.authService.authCounter.value})',
                  ),
                ),
        ),
      ),
    );
  }
}

class HomeController extends GetxController {
  AuthService _authService = Get.find<AuthService>();

  final Rx<int> homeCounter = 0.obs;
  late final Rx<int> authCounter;

  @override
  void onInit() {
    authCounter = _authService.authCounter;
    super.onInit();
  }

  void increment() {
    homeCounter.value++;
    _authService.authCounter.value++;
  }

  void logout() => _authService.doLogout();
}

class HomeScreen extends GetView<HomeController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Obx(
        () => Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Auth counter: ${controller.authCounter.value}'),
              Text('Home counter: ${controller.homeCounter.value}'),
              ElevatedButton(
                onPressed: controller.increment,
                child: Text('Increment auth counter'),
              ),
              ElevatedButton(
                onPressed: controller.logout,
                child: Text('Logout'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**To Reproduce**
1. Run the app
2. Click 'Login' button
3. Click 'Logout' button

**Expected behavior**
Services & controllers should be cleared and app should route to Login page

**Screenshots**
![image](https://user-images.githubusercontent.com/317299/132646937-e83b5bb9-ea7d-42ed-a0ac-c810364ad0e6.png)

**Flutter Version:**
```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (2 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Getx Version:**
4.3.8

**Describe on which device you found the bug:**
Android emulator

**Comment by manikantag** [comment]
As a workaround, I changed the `AuthService` to `AuthController extends GetxController` instead of extending `GetxService`.

Tried to reset the state using Get.deleteAll() (came to know from this PR: https://github.com/jonataslaw/getx/pull/1545)

But the problem with `Get.deleteAll()` is the controllers are not re-initialised after logout. I'm setting them via `Get.put()`. I'm using `BindingBuilder`

![image](https://user-images.githubusercontent.com/317299/132729058-4a73dede-e2b8-400c-94bf-0d214eac55c2.png)

So, I'm not able to use neither `get.reset()` not `Get.deleteAll()`.

Any hints/workarounds are appreciated.

**Comment by jonataslaw** [comment]
If you want to reload the dependency, you should not delete it, but use reload.

Neither Get.delete nor Get.reset, I think what you are looking for is Get.reload

**Comment by manikantag** [comment]
Hi, thanks for the suggestion.

I've modified `doLogout()` like below:

```
  void doLogout() {
    isAuthenticated.value = false;
    Get.rootDelegate.offNamed('/');
    Get.reloadAll(force: true);
  }
```

I can see that reload working in logs. But the `AuthService` state is still there after restart  (`Rx<int> authCounter = 0.obs;`).

I've updated the code in the issue description to show authCounter value in the button label.

<img src="https://user-images.githubusercontent.com/317299/132733597-9bbb62ec-c1e6-4c40-aa04-0b697cd1d899.gif" height="600">

**Comment by manikantag** [comment]
Logs when I click `Logout` button:

```
[GETX] Instance "AuthService" was reloaded.
[GETX] Instance "GetMaterialController" was reloaded.
[GETX] Instance "HomeController" was reloaded.
[GETX] GOING TO ROUTE /
[GETX] REMOVING ROUTE /home
[GETX] Instance "AuthService" has been created
[GETX] Instance "AuthService" has been initialized
[GETX] Instance "LoginController" has been created
[GETX] Instance "LoginController" has been initialized
[GETX] "HomeController" deleted from memory
```

It says, `AuthService` is reloaded, but again it is creating. Is that expected?

**Comment by manikantag** [comment]
I tried `Get.reload<AuthService>()` as well. Still `authCounter` is not reset after logout.

**Comment by AmineLAHRIM** [comment]
same problem i faced @jonataslaw

**Comment by manikantag** [comment]
@jonataslaw Can you please give me hints on how to fix this? I can submit a PR if I'm able to figure it out. 

Because of this issue, users are not able to use the same device with multiple users (as `Rx<AppUser>` variable still holding previous signed-in user).

**Comment by kingofzg** [comment]
I also have this problem @jonataslaw

**Comment by manikantag** [comment]
Ok, I spend sometime to workaround the issue, but only succeeded half.

I was able to reset the state in controller by re-assigning them to different value either in logout or in `onInit()` method. But if I reset the variables in `onReady()` it is not working. Same thing with any async code.

In my case, I'm setting the `Rx<AppUser` to either `Rx<Teacher>` or Rx<Student>` depending on the logged in user. Auth is managed using Firebase Auth. As Firebase Auth notifies the app using async handlers (which is `auth.userChanges().listen(...)`), I'm assigning the logged in user obs in the Firebase auth event callback. That is not resetting the `Rx` variable in Auth service after logout and login.

Code to reproduce this: https://gist.github.com/manikantag/18a0cab5ea2423e321aae62e50a3e00d
Used `Future.delayed` to simulate the Auth event callback.

Steps:
1. Click 'Teacher Login'
2. Increment counts
3. Click 'Logout'
4. Click 'Student Login' ---> we should see logged in user as 'Student', but it is coming as 'Teacher'

I've spent around a week after this issue, and I can't find a fix. Without this working, we can't go forward. After wasting a week on this, we decided to use other state management solution other than Getx. If someone wants to debug the issue, I think the above Gist is a good starting point.

As we plan to stop using Getx, I can close this issue if @jonataslaw wants me to. Thanks

**Comment by manikantag** [comment]
Please don't get me wrong. Getx is good state management solution, it's just we don't have time to put on this issues and project is anyway in early phase.

**Comment by manikantag** [comment]
If I set the logged-in user (Student or Teacher) using `currentUser.value = Teacher()` or `currentUser.value = Student()`, everything is working fine. But when I reassign directly like `currentUser = Teacher().obs` or `currentUser = Student()`, then the state is not changed. 

If I understood it right, `Obx` creates a listener in `initState()`:

```dart
class _ObxState extends State<ObxWidget> {
  final _observer = RxNotifier();
  ...

  @override
  void initState() {
    super.initState();
    subs = _observer.listen(_updateTree, cancelOnError: false);  // <----- HERE
  }
```

When I reassigned to new obs, I'm assuming new listener is not registered for this Obx. If I'm correct, is there a way to register new listener?

**Comment by manikantag** [comment]
Or, is there any way to get all the subscriptions of `Rx` variable and register them to another `Rx` variable?

Here, I assume `Obx` subscribes to `Rx` for value changes. So, I'm thinking if registering all the Obx observers to new `Rx`, everything should work fine. Please suggest.
