### ISSUE TITLE
RouterReportManager  memory leak

### ISSUE THREAD

**Issue by wangronghui01** [jonataslaw/getx#1854]
Now we find that Getx has a memory leak problem. The RouterReportManager uses global when managing dependencies_ Routeskey: when a route is obtained by get.find, a value will be inserted into the map. The key of the map uses the getpageroute object. However, getpageroute will be re created every time the re route enters, so the map.containskey comparison must be inconsistent, because the getpageroute object does not find any place to rewrite hashcode or equals. I don't know if it's my usage.

example:

```dart
static void appendRouteByCreate(GetLifeCycleBase i) {
    _routesByCreate[_current] ??= HashSet<Function>();
    // _routesByCreate[Get.reference]!.add(i.onDelete as Function);
    _routesByCreate[_current]!.add(i.onDelete);
  }

  static void reportRouteDispose(Route disposed) {
    if (Get.smartManagement != SmartManagement.onlyBuilder) {
      WidgetsBinding.instance!.addPostFrameCallback((_) {
        _removeDependencyByRoute(disposed);
      });
    }
  }

  static void reportRouteWillDispose(Route disposed) {
    final keysToRemove = <String>[];

    _routesKey[disposed]?.forEach(keysToRemove.add);

    /// Removes `Get.create()` instances registered in `routeName`.
    if (_routesByCreate.containsKey(disposed)) {
      for (final onClose in _routesByCreate[disposed]!) {
        // assure the [DisposableInterface] instance holding a reference
        // to onClose() wasn't disposed.
        onClose();
      }
      _routesByCreate[disposed]!.clear();
      _routesByCreate.remove(disposed);
    }

    for (final element in keysToRemove) {
      GetInstance().markAsDirty(key: element);

      //_routesKey.remove(element);
    }

    keysToRemove.clear();
  }
```

**Flutter Version:**
flutter 2.5.0

**Getx Version:**
Getx ^4.3.8

**Comment by jonataslaw** [comment]
In fact the route is added in Route.install, and it is removed in Route.dispose.
I can't envision a situation where Route could change its object without calling dispose.

**Comment by wangronghui01** [comment]
`static void _removeDependencyByRoute(Route routeName) {
    final keysToRemove = <String>[];

    _routesKey[routeName]?.forEach(keysToRemove.add);

    /// Removes `Get.create()` instances registered in `routeName`.
    if (_routesByCreate.containsKey(routeName)) {
      for (final onClose in _routesByCreate[routeName]!) {
        // assure the [DisposableInterface] instance holding a reference
        // to onClose() wasn't disposed.
        onClose();
      }
      _routesByCreate[routeName]!.clear();
      _routesByCreate.remove(routeName);
    }

    for (final element in keysToRemove) {
      final value = GetInstance().delete(key: element);
      if (value) {
        _routesKey[routeName]?.remove(element);
      }
    }

    keysToRemove.clear();
  }`

_ Routeskey [routename] the key will always be kept, and it is not judged whether the value is empty, so the memory address referenced by the key will always survive.

**Comment by wangronghui01** [comment]
_ Routeskey [routename] the key will always be kept, and it is not judged whether the value is empty, so the memory address referenced by the key will always survive.

**Comment by wangronghui01** [comment]
`static void _removeDependencyByRoute(Route routeName) {
    final keysToRemove = <String>[];

    _routesKey[routeName]?.forEach(keysToRemove.add);

    /// Removes `Get.create()` instances registered in `routeName`.
    if (_routesByCreate.containsKey(routeName)) {
      for (final onClose in _routesByCreate[routeName]!) {
        // assure the [DisposableInterface] instance holding a reference
        // to onClose() wasn't disposed.
        onClose();
      }
      _routesByCreate[routeName]!.clear();
      _routesByCreate.remove(routeName);
    }

    for (final element in keysToRemove) {
      final value = GetInstance().delete(key: element);
      if (value) {
        _routesKey[routeName]?.remove(element);
      }
    }

    keysToRemove.clear();
  }`

_ Routeskey [routename] the key will always be kept, and it is not judged whether the value is empty, so the memory address referenced by the key will always survive.

**Comment by wangronghui01** [comment]
> 实际上路由是在Route.install中添加的，在Route.dispose中被删除了。
> 我无法想象 Route 可以在不调用 dispose 的情况下更改其对象的情况。

`static void _removeDependencyByRoute(Route routeName) {
final keysToRemove = [];

_routesKey[routeName]?.forEach(keysToRemove.add);

/// Removes `Get.create()` instances registered in `routeName`.
if (_routesByCreate.containsKey(routeName)) {
  for (final onClose in _routesByCreate[routeName]!) {
    // assure the [DisposableInterface] instance holding a reference
    // to onClose() wasn't disposed.
    onClose();
  }
  _routesByCreate[routeName]!.clear();
  _routesByCreate.remove(routeName);
}

for (final element in keysToRemove) {
  final value = GetInstance().delete(key: element);
  if (value) {
    _routesKey[routeName]?.remove(element);
  }
}

keysToRemove.clear();
}`
_ Routeskey [routename] the key will always be kept, and it is not judged whether the value is empty, so the memory address referenced by the key will always survive.

**Comment by yiiim** [comment]
I also have this problem, the GetPageRoute object will recreate a new instance every time, map.containskey comparison must be inconsistent, the key of the map will get a new key every time a new page is pushed, the key keeps growing
