### ISSUE TITLE
Please someone add a RxStatus.loadingMoreError()

### ISSUE THREAD

**Issue by henriqueArrazao** [jonataslaw/getx#1856]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a RxStatus.loadingMoreError() inside the class "RxNotifier"

**Describe alternatives you've considered**
I added a "isLoadingMoreError" variable inside the GetXController

**Comment by henriqueArrazao** [comment]
don't worry i will do it

**Comment by henriqueArrazao** [comment]
https://github.com/jonataslaw/getx/pull/1860/files

**Comment by subzero911** [comment]
What is the meaning of this status?
Controller can be in loading state, which finishes with either success or failure. What a "loadingMoreErrors" state? Looks like it's your custom logic not applicable to most projects.

**Comment by henriqueArrazao** [comment]
It's useful when using "controller.obx((_) => {}, onError: (_) {}, etc...)", if I set state "isError" the listview (inside "onSucess:") will not remain in screen so I can't just show a little message at the bottom of the "onSuccess" screen (same behavior as RxStatys.loadingMore()), but with RxStatus.loadingMoreError() it is possible.

**Comment by henriqueArrazao** [comment]
> What is the meaning of this status?
> Controller can be in loading state, which finishes with either success or failure. What a "loadingMoreErrors" state? Looks like it's your custom logic not applicable to most projects.

It's useful when using "controller.obx(() => {}, onError: () {}, etc...)", if I set state "isError" the listview (inside "onSucess:") will not remain in screen so I can't just show a little message at the bottom of the "onSuccess" screen (same behavior as RxStatys.loadingMore()), but with RxStatus.loadingMoreError() it is possible.
