### ISSUE TITLE
Rx Nullable

### ISSUE THREAD

**Issue by henriqueArrazao** [jonataslaw/getx#1875]
Example:
Rx< String? > rx = RxString(null);

The most necessary times is when we need to store an object like "loggedUser", it is very necessary a nullable option.

**Comment by larsvombruch** [comment]
Simply use this:

    Rxn<String> rx = Rxn<String>();

**Comment by hpassos2b** [comment]
> Simply use this:
> 
> ```
> Rxn<String> rx = Rxn<String>();
> ```

Is this somewhere in the documentation? How did you find this?

**Comment by larsvombruch** [comment]
> > Simply use this:
> > ```
> > Rxn<String> rx = Rxn<String>();
> > ```
> 
> Thank you man, this is what I needed, is this somewhere in the documentation? How did you find this?

I just came across this feature when I was looking for that exact problem on Stackoverflow. I believe that this is not well documented
