### ISSUE TITLE
Can't change height of child widget when using Get.bottomSheet

### ISSUE THREAD

**Issue by padgithub** [jonataslaw/getx#1921]
**Describe the bug**
I have set the height of the child view but it only shows the maximum half of the screen.

**Reproduction code
```dart
Get.bottomSheet(
            Container(
              height: 900,
              color: Colors.red,
            ),
          );
```

**To Reproduce**
1. Click on action
2. See error

**Expected behavior**
Height child = 900

**Screenshots**
![simulator_screenshot_960B1B6E-7BCF-4232-BC6F-E507486B07BF](https://user-images.githubusercontent.com/33429444/137154237-a3a388d8-00f5-4c92-a054-81809b8bdc9e.png)

**Flutter Version:**
2.2.3

**Getx Version:**
4.3.8

**Describe on which device you found the bug:**
iPhone 12 Pro Max

**Comment by minhx3** [comment]
Me too. please

**Comment by binoytv9** [comment]
Just pass isScrollControlled: true to the Get.bottomSheet.

```
Get.bottomSheet(
            Container(
              height: 900,
              color: Colors.red,
            ),
        isScrollControlled: true,
   );
```

**Comment by padgithub** [comment]
> Just pass isScrollControlled: true to the Get.bottomSheet.
> 
> ```
> Get.bottomSheet(
>             Container(
>               height: 900,
>               color: Colors.red,
>             ),
>         isScrollControlled: true,
>    );
> ```

Thanks you. it worked
