### ISSUE TITLE
Start app from external link cause dark screen

### ISSUE THREAD

**Issue by alejandrogiubel** [jonataslaw/getx#1929]
**Describe the bug**
Start app from external link cause dark screen .

**Reproduction code**

example:

```dart
runApp(GetMaterialApp.router(
    title: 'My App',
    debugShowCheckedModeBanner: false,
    // initialRoute: token !=  null ? '/home' : '/login',
    theme: appThemeData,
    getPages: AppPages.pages,
    // home: token !=  null ? const HomePage() : const LoginPage(),
    initialBinding: token !=  null ? HomeBinding() : LoginBinding(),
    translationsKeys: AppTranslation.translations,
    defaultTransition: Transition.cupertino,
    routeInformationParser: GetInformationParser(
      initialRoute: '/home',
    ),
    routerDelegate: GetDelegate(),
  ));
```

**To Reproduce**
1. Just open the app from an external link

**Expected behavior**
Normal execution of the app

**Screenshots**

**Flutter Version:**
2.5.2

**Getx Version:**
4.3.8

**Describe on which device you found the bug:**
samsung Galaxy A30 and Android Emulator Pixel 3

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by isiyemijoe** [comment]
Add this to your GetMaterialApp declaration " unknownRoute: route == "pin_login" //pin_will be the name of a route you want to navigate to like a login screen
