### ISSUE TITLE
弹出输入法后，defaultDialog会提示底部溢出一些像素

### ISSUE THREAD

**Issue by liziliang123** [jonataslaw/getx#1951]
弹出输入法后，defaultDialog会提示底部溢出一些像素

**Comment by yuyaohongzheng** [comment]
![image](https://user-images.githubusercontent.com/10897314/139808708-c2284074-f4a2-4dce-8c37-fdf6edde2fbf.png)

**Comment by liziliang123** [comment]
@yuyaohongzheng 我说的是Getx的defaultDialog方法，不是系统自带的dialog，Getx的defaultDialog使用scrollview也有溢出

**Comment by yuyaohongzheng** [comment]
open Get.defaultDIalog source, find ,and add to fix it

**Comment by liziliang123** [comment]
@yuyaohongzheng it also dosent work  , I use Column mainAxisSize: MainAxisSize.min,to fix it

**Comment by liziliang123** [comment]
@yuyaohongzheng thanks
