### ISSUE TITLE
Binding not working in Get.to

### ISSUE THREAD

**Issue by parmarravi** [jonataslaw/getx#1953]
I have a Screen in which i have done a reveal animation

```
  userController.setUserOnboard(true);
    final Route page = RevealRoute(
      page: SchedulerHomeScreen(0),
      maxRadius: 800,
      centerAlignment: Alignment.center,
      centerOffset: Offset.zero,
    );
    Get.to(page,binding: HomeBinding(),);
```

The below code does not work as it throws the error that the controller is not attached.

SImilar to this issue i have dummy project to check for the problem and i found out that manually adding binding is not working 

i am attaching the repo
[https://github.com/parmarravi/GetxBindingBug](https://github.com/parmarravi/GetxBindingBug
)

![image](https://user-images.githubusercontent.com/7616089/139863442-977829a3-6972-495e-8796-94ec1db912f9.png)

**Comment by jonataslaw** [comment]
Get.to(()=>
read previous logs

**Comment by parmarravi** [comment]
I was searching for the error in the controller and binding.  The log does not show the error is with the calling function.
 
Is it possible to add multiple bindings to this?

**Comment by jonataslaw** [comment]
The log shows that the error is in the calling function, or you are using a legacy version of GetX.
There are at least 30 previous versions the log is shown when you use Get.to without the function.

**Comment by parmarravi** [comment]
This does not work Same error

```
  final Route page = RevealRoute(
      page: SchedulerHomeScreen(0),
      maxRadius: 800,
      centerAlignment: Alignment.center,
      centerOffset: Offset.zero,
    );
    //
    Get.to(() => page, binding: HomeBinding());


```

This works
    Get.to(() => SchedulerHomeScreen(0), binding: HomeBinding());


RevealRoute  class 

class RevealRoute extends PageRouteBuilder {
  final Widget page;
  final Alignment centerAlignment;
  final Offset centerOffset;
  final double minRadius;
  final double maxRadius;

  RevealRoute({
    required this.page,
    this.minRadius = 0,
    required this.maxRadius,
    required this.centerAlignment,
    required this.centerOffset,
  })  : assert(centerOffset != null || centerAlignment != null),
        super(
        /// We could override pageBuilder but it's a required parameter of
        /// [PageRouteBuilder] and it won't build unless it's provided.
        pageBuilder: (
            BuildContext context,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
            ) {
          return page;
        },
      );

  @override
  Widget buildTransitions(
      BuildContext context,
      Animation<double> animation,
      Animation<double> secondaryAnimation,
      Widget child,
      ) {
    return ClipPath(
      clipper: CircularRevealClipper(
        fraction: animation.value,
        centerAlignment: centerAlignment,
        centerOffset: centerOffset,
        minRadius: minRadius,
        maxRadius: maxRadius,
      ),
      child: child,
    );
  }
}

**Comment by jonataslaw** [comment]
You are creating the page before Binding, it must be created later for this to work
The function delays the creation of the constructor, this is its usefulness.

    Get.to(() => RevealRoute(
      page: SchedulerHomeScreen(0),
      maxRadius: 800,
      centerAlignment: Alignment.center,
      centerOffset: Offset.zero,
    ), binding: HomeBinding());

**Comment by parmarravi** [comment]
Checkout this error 

======== Exception caught by gesture ===============================================================
The following message was thrown while handling a gesture:
Unexpected format,
you can only use widgets and widget functions here

Is it because of 

class SchedulerHomeScreen extends GetView<SchedulerHomeController> {
  String TAG = "SchedulerHomeScreen";

  SchedulerHomeScreen(int index, {Key? key}) : super(key: key) {
    controller.changePage(index);
  }

**Comment by jonataslaw** [comment]
Look at how you type your widget and you'll know where the error is.

**Comment by parmarravi** [comment]
I have replaced it with a basic widget, same issue but. 
I think this error is related to RevealRoute that cant be inserted in Get.to as a page route

**Comment by jonataslaw** [comment]
Hey, look at your code one more time.

`class SchedulerHomeScreen extends GetView {`

In case you haven't noticed, you're using controller.changePage(index); but the controller doesn't have a type, because you didn't type GetView<Controller>.

**Comment by parmarravi** [comment]
OPPS i haven't updated the log 

The file is 
class SchedulerHomeScreen extends GetView<SchedulerHomeController> {


controller is default 


If i pass any other view that is extended from StatelessWidget then also it throws the same issue. 


Cant, I pass the custom route page in Get.to ?  Like that CircularReveal

**Comment by jonataslaw** [comment]
Actually look what the log says, you can only pass widgets or widget functions, if RevealRoute isn't a widget, it's a Route, you can't pass it through Get.to.

**Comment by parmarravi** [comment]
correct. Any way I can make Circular Reveal Transition and add it to Get.to?

**Comment by parmarravi** [comment]
I was able to add circular reveal by editing the internal code file. Can you add a way to add a custom transition from outside? 

 ```
 case Transition.ciruclarReveal:
          return CircularRevealTransition().buildTransitions(
              context,
              route.curve,
              route.alignment,
              animation,
              secondaryAnimation,
              route.popGesture ?? Get.defaultPopGesture
                  ? CupertinoBackGestureDetector<T>(
                  gestureWidth: route.gestureWidth?.call(context) ??
                      _kBackGestureWidth,
                  enabledCallback: () => _isPopGestureEnabled<T>(route),
                  onStartPopGesture: () => _startPopGesture<T>(route),
                  child: child)
                  : child);
```

**Comment by jonataslaw** [comment]
You can to use CustomTransitions

**Comment by parmarravi** [comment]
Just did the custom transition but it does not feel natural like the one in the transitions of the main file. That Animation looks much more natural.

This animation in custom have some jerking effect
