### ISSUE TITLE
Getx not initialized with fcm firebase background service when app is terminated

### ISSUE THREAD

**Issue by MySwastik** [jonataslaw/getx#1965]
Senario is , I am pushing anotication with routing payload , it work fine when app is open or in background but when the app is terminated at this time it show null values after clcik n notication it navigate to particular route all getx data show null value.

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
 StreamBuilder<DocumentSnapshot>(
                    stream: FirebaseFirestore.instance.doc('Vendors/${authController.user!.uid}').snapshots(),
                    builder: (context, mainsnapshot) {
                      if(mainsnapshot.data ==null){
                        return SizedBox(height: 20,width: 20,child: Loader(),);
                      }
```

**Expected behavior**
Here my authcontroller which is initial binding it is showing null value.

**Flutter Version:**
2.5

**Getx Version:**
4.3.8

**Describe on which device you found the bug:**
Android.

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by maares** [comment]
@MySwastik there´s no reproductive code, please add.

Just a heads up, when app is closed as FirebaseBase states, there should be a global method outside the Main, which will load when FCM triggers, then you need to put or raise all dependencies including Firebase.Ini...()

This is something I do on my current project

Main
```

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await ServicesSer().dependencies(); //<-- firebase dependency and other stuff

  runApp(
    GetMaterialApp.router(

```
Dependencies
```

class ServicesSer extends Bindings {
  @override
  Future<void> dependencies() async {
    if (GetPlatform.isWeb) {
      FacebookAuth.instance.webInitialize(
        appId: "...",
        cookie: true,
        xfbml: true,
        version: "v9.0",
      );
    }

    //storageCtrl user preferences
    await Get.putAsync<StorageCtrl>(() async {
      await GetStorage.init();
      final storageCtrl = StorageCtrl();
      await storageCtrl.storageCtrlInit();
      return storageCtrl;
    }, permanent: true);

    //notifications custom ctrl to handle the incoming pending notifications
    await Get.putAsync<NotificationsCtrl>(() async {
      final notificationsCtrl = NotificationsCtrl();
      await notificationsCtrl.notificationsInit();
      return notificationsCtrl;
    }, permanent: true);

    //firebase messaging init <--- here
    await Get.putAsync<FirebaseMessageSer>(() async {
      await Firebase.initializeApp();
      final firebaseMessengerSer = FirebaseMessageSer();
      await firebaseMessengerSer.firebaseMessageSerInit();
      return firebaseMessengerSer;
    }, permanent: true);

    //user preferences
    await GetStorage.init();

    /// other services
    ....
    print('ServicesSer has finished');
  }
}

```

```

import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:get/get.dart';

import '../../../utils/ctrls/notifications_ctrl.dart';
import '../../../utils/utils.dart';
import '../services_bindings.dart';

class FirebaseMessageSer extends GetxService {
  Utils utils = Utils();

  @override
  Future<void> onInit() async {
    super.onInit();
  }

  @override
  void onReady() {
    super.onReady();
  }

  @override
  void onClose() {
    super.onClose();
  }

  Future<void> firebaseMessageSerInit() async {
    await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
      alert: false,
      badge: false,
      sound: false,
    );
    ;

    FirebaseMessaging.instance.getInitialMessage().then((message) async {
      print('getInitialMessage');
    });

    FirebaseMessaging.onMessage.listen((message) async {
      print('onMessage');
      final notificationsCtrl = Get.find<NotificationsCtrl>();
      notificationsCtrl.showNotification(message: message);
    });

    FirebaseMessaging.onMessageOpenedApp.listen((message) async {
      print('onMessageOpenedApp');
      final notificationsCtrl = Get.find<NotificationsCtrl>();
      notificationsCtrl.showNotification(message: message);
    });

    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler); <--here when app is killed or in background

    print(await FirebaseMessaging.instance.getToken());
  }
}
// here when app is on background or killed
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print('Handling a background message ${message.messageId}');
  await ServicesSer().dependencies();
  final notificationsCtrl = Get.find<NotificationsCtrl>();
  notificationsCtrl.showNotification(message: message);
}

```

**Comment by MySwastik** [comment]
@maares  This is working. 
 Thanks.

**Comment by dmlben** [comment]
Hi, it's working for foreground, but i got error message for background : Failed assertion: line 12 pos 7: '_debugInitialized': Global OverlaySupport Not Initialized !
how you initialize your controller : await notificationsCtrl.notificationsInit(); ?

**Comment by jonex41** [comment]
@maares this is not working when app is terminated and opened through notification, my Get.back(), is not working, snackbar too is not showing, please help

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_controller@1226359576' has not been initialized.
#0 SnackbarController._controller (package:get/get_navigation/src/snackbar/snackbar_controller.dart)
https://github.com/jonataslaw/getx/issues/1 SnackbarController._removeEntry (package:get/get_navigation/src/snackbar/snackbar_controller.dart:314:7)
https://github.com/jonataslaw/getx/issues/2 SnackbarController.close (package:get/get_navigation/src/snackbar/snackbar_controller.dart:55:5)
https://github.com/jonataslaw/getx/issues/3 _SnackBarQueue._closeCurrentJob (package:get/get_navigation/src/snackbar/snackbar_controller.dart:370:29)
https://github.com/jonataslaw/getx/issues/4 SnackbarController.closeCurrentSnackbar (package:get/get_navigation/src/snackbar/snackbar_controller.dart:340:26)
https://github.com/jonataslaw/getx/issues/5 GetNavigation.closeCurrentSnackbar (package:get/get_navigation/src/extension_navigation.dart:1124:30)
https://github.com/jonataslaw/getx/issues/6 hideLoader. (package:pick3d/src/utils/utils.dart:87:17)
https://github.com/jonataslaw/getx/issues/7 new Future.delayed. (dart:async/future.dart:424:39)
https://github.com/jonataslaw/getx/issues/8 Timer._createTimer. (dart:async-patch/timer_patch.dart:18:15)
https://github.com/jonataslaw/getx/issues/9 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
https://github.com/jonataslaw/getx/issues/10 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
https://github.com/jonataslaw/getx/pull/11 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
2023-04-01 09:00:21.956 5958-6019 flutter com.app.pick3Di E [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_controller@1226359576' has not been initialized.
#0 SnackbarController._controller (package:get/get_navigation/src/snackbar/snackbar_controller.dart)
https://github.com/jonataslaw/getx/issues/1 SnackbarController._removeEntry (package:get/get_navigation/src/snackbar/snackbar_controller.dart:314:7)
https://github.com/jonataslaw/getx/issues/2 SnackbarController.close (package:get/get_navigation/src/snackbar/snackbar_controller.dart:55:5)
https://github.com/jonataslaw/getx/issues/3 _SnackBarQueue._closeCurrentJob (package:get/get_navigation/src/snackbar/snackbar_controller.dart:370:29)
https://github.com/jonataslaw/getx/issues/4 SnackbarController.closeCurrentSnackbar (package:get/get_navigation/src/snackbar/snackbar_controller.dart:340:26)
https://github.com/jonataslaw/getx/issues/5 GetNavigation.closeCurrentSnackbar (package:get/get_navigation/src/extension_navigation.dart:1124:30)
https://github.com/jonataslaw/getx/issues/6 showLoader. (package:pick3d/src/utils/utils.dart:64:17)
https://github.com/jonataslaw/getx/issues/7 new Future.delayed. (dart:async/future.dart:424:39)
https://github.com/jonataslaw/getx/issues/8 Timer._createTimer. (dart:async-patch/timer_patch.dart:18:15)
https://github.com/jonataslaw/getx/issues/9 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
https://github.com/jonataslaw/getx/issues/10 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
https://github.com/jonataslaw/getx/pull/11 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
