### ISSUE TITLE
Can't get work TextEditingController with debounce 

### ISSUE THREAD

**Issue by bubnenkoff** [jonataslaw/getx#1967]
I asked on SO, but did not get an answer https://stackoverflow.com/questions/69741183/how-to-listen-changes-inside-textcontroller

The question is simple. I have got TextField linked with contoller:
```
          child: TextField(
            textAlign: TextAlign.center,

            maxLines: 120,  
            controller: ctrl.txtList.value,
          )),
```          

But I can't get work debounce work inside it:
```
class Controller extends GetxController{

  final txtList = TextEditingController().obs;

  @override
  void onInit() {
    debounce(txtList, (_) { 
      print("debouce$_");
      }, time: Duration(seconds: 1));
    super.onInit();
  }

}
```

I tried different variants txtList/txtList.value/txtList.value.text/... noting do not work.

**Comment by YassineChe** [comment]
Hello!
Did you solve it ?

**Comment by rfmanuj** [comment]
Hi @YassineChe the answer is in the StackOverflow question.

@bubnenkoff please close this issue.
