### ISSUE TITLE
How to remove last two screen

### ISSUE THREAD

**Issue by webaddicted** [jonataslaw/getx#1981]
For skip two screen like - `A-B-C-D-F` screen in my stack and I want to go to `B` by removing all upper screen in stack then final stack is `A-B.`

**In Screen B**

    Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(
                        settings: RouteSettings(name: "Foo"),
                        builder: (BuildContext context) => Third()),
                  );

**And In Screen F**

    Navigator.popUntil(context, ModalRoute.withName("Foo"));

It working perfectly fine **But is there any option we can achieve this in GetX.**

**Comment by binoytv9** [comment]
Check this
https://stackoverflow.com/questions/64684952/flutter-getx-routing-history

I think you need to use Get.offUntil

**Comment by webaddicted** [comment]
@binoytv9  Did you actually try this. I already try this. 
If we use

`   Get.offUntil(
                              MaterialPageRoute(builder: (context) => Second()),
                              (Route<dynamic> route) => false);

it open second page and remove all screen and my first screen is also close in this case. But i dont what to remove first screen.

Please share only those solution which you actully use.`

**Comment by Shreemanarjun** [comment]
Use Get.close(2);

**Comment by webaddicted** [comment]
@Shreemanarjun ,

This is not right way to do. we can also do with help of `Get.back()` multiple time.
If I have number of other screen then we face problem. In case other screen add or remove then I also need to change number.
Do you have any other option like I give example of `Navigation`.

**Comment by iamisathya** [comment]
+1

**Comment by nauhalf** [comment]
any update ?

**Comment by jonataslaw** [comment]
To close to pages on version 4: `Get.close(4);`

To close page until other page (similar with popUntil):
`Get.until((route) => route.settings.name == Routes.Feed);`

**Comment by webaddicted** [comment]
Hi @jonataslaw ,

Thanks for this solution.

**Comment by yashrajodiya** [comment]
hi @iamisathya nice
