### ISSUE TITLE
How to implement such routing，Local navigation？

### ISSUE THREAD

**Issue by Dboy233** [jonataslaw/getx#2016]
### How to use GetX to do routing like this？？？
![20200527065220725](https://user-images.githubusercontent.com/37604230/143824558-7962d73b-94d7-4662-bb9d-00cf9b0df48f.gif)

**Comment by MedwinCorreo** [comment]
can you try get.arguments ?

**Comment by ahmednfwela** [comment]
this can be achieved with nav2 api, keep an eye on https://github.com/jonataslaw/getx/pull/2032

**Comment by Dboy233** [comment]
I using'Navigator' to complete this function...

At first I tried to use'GetMaterialApp' in a partial widget, thinking that'GetX' would create a local route to manage. Found that this is not possible.

**Comment by ahmednfwela** [comment]
this is specifically what navigation 2 and `GetRouterOutlet` was made for

see this example: https://github.com/Bdaya-Dev/getx/tree/master/example_nav2

**Comment by Dboy233** [comment]
> this is specifically what navigation 2 and `GetRouterOutlet` was made for
> 
> see this example: https://github.com/Bdaya-Dev/getx/tree/master/example_nav2

Thanks, I didn't find this before. 👌
