### ISSUE TITLE
easy_localization doesn't work properly with GetMaterialApp  [Bug + Feature Request]

### ISSUE THREAD

**Issue by rei-codes** [jonataslaw/getx#2026]
easy_localization doesn't instantly change the language when I use GetMaterialApp instead of MaterialApp I have to restart the app to see changes.

you may think why I use easy_localization instead of GetX's localization feature?
That's because: I need to use nested JSON in my project and GetX doesn't support nested objects as far as I know.
```
For example:

// en.json
{
  "home-page": {
      "hello" : "Hello!",
    },
}

// does not work because Translations class wants Map<String, String>, not Map<String, dynamic>
Text('home-page.hello'.tr) // I hope this feature will add in the near future 
```

**Comment by calvingit** [comment]
Hey bro, i think you ask too much of GetX.

**Comment by SchabanBo** [comment]
You can use this [tool](https://github.com/SchabanBo/qlevar_local_manager) to create your locals (it supports nested nodes). and it will [export](https://github.com/SchabanBo/qlevar_local_manager#getx) a class for you. wich you could use with GetX Locals. [here](https://github.com/SchabanBo/qlevar_local_manager/releases/tag/1.1.0) is the last release.

**Comment by Xardas365** [comment]
> 
Hello, I suggest you can use [auto_localized](https://github.com/marcinsiedlik/auto_localized) library with GetX. Auto_localized can support nested objects and generating file from source lang files (YAML and JSON supported).

Nested json objects for easier translation [more information here](https://github.com/marcinsiedlik/auto_localized/issues/9).

GetMaterialApp can by wrapped AutoLocalizedApp like that:

`void main() {
  runApp(FlutterBase());
}

class FlutterBase extends StatelessWidget {
  const FlutterBase({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return AutoLocalizedApp(
      child: GetMaterialApp(
        supportedLocales: AutoLocalizedData.supportedLocales,
        localizationsDelegates: AutoLocalizedData.localizationsDelegates,
        locale: Get.deviceLocale,
        fallbackLocale: Get.fallbackLocale,
        title: R.appTitle,
        getPages: AppPages.routes,
        initialRoute: Routes.home,
        defaultTransition: Transition.fade,
      ),
    );
  }
}`

**Comment by AmarchandK** [comment]
I have found a possible solution.

In case you are using GetMaterialApp you should when changing the current language call  Get.updateLocale() to inform GetMaterialApp about the language change

final _newLocale = Locale('ar', 'EG')
await context.setLocale(_newLocale); // change `easy_localization` locale
Get.updateLocale(_newLocale); // change `Get` locale direction
