### ISSUE TITLE
Page transition animation on Flutter web even with Transition.noTransition

### ISSUE THREAD

**Issue by rignaneseleo** [jonataslaw/getx#2035]
Hi,
I have the following code: 
```
return GetMaterialApp(
      title: 'Hearth Backoffice',
      ...
      routes: {
        "/": (context) => SplashScreen(),
        "/home": (context) => MinDashboardPage(),
        "/home2": (context) => DashboardPage(),
        "/login": (context) => LoginPage(),
        "/signup": (context) => SignUpPage(),
        "/mail": (context) => MailPage(),
      },
      defaultTransition: Transition.noTransition,
      transitionDuration: Duration(seconds: 0),
    );
```

but whenever I call `Get.toNamed("/home")` or `Get.toNamed("/login")` from Chrome the navigator runs the page change with the page transition animation (right to left animation) which is really annoying. 

The following values in the `GetMaterialApp` do not seem to have any effect:
```
defaultTransition: Transition.noTransition,
transitionDuration: Duration(seconds: 0),
```

How do I completely get rid of the page transition in the whole app?

**Comment by jonataslaw** [comment]
You must use `getPages`, not `routes`, `routes` will use the **platform transition**

**Comment by rignaneseleo** [comment]
Worked, thanks!
