### ISSUE TITLE
getx controller not call onInit onReady onClose

### ISSUE THREAD

**Issue by StitchC** [jonataslaw/getx#2038]
hello, i'm new talent in flutter and use getx start to my project, but lately i face a problem make me so confuse, i hope you can tell me some ideas and help me solve this problem.

i use GetMaterialApp and register some route

```dart
void main() async {
  // 启动APP
  runApp(
    GetMaterialApp(
      initialRoute: '/',
      getPages: [
          GetPage(name: '/path/a', page: () => PageA()),
          GetPage(name: '/path/b', page: () => PageB()),
          GetPage(name: '/path/c', page: () => PageC()),
      ],
      translations: I18n(),
      locale: ui.window.locale,
      builder:
          EasyLoading.init(builder: (context, widget) {
        return Scaffold(
          body: GestureDetector(
            child: widget,
            onTap: () {
              FocusScopeNode currentFocus = FocusScope.of(context);
              if (!currentFocus.hasPrimaryFocus &&
                  currentFocus.focusedChild != null) {
                FocusManager.instance.primaryFocus!.unfocus();
              }
            },
          ),
        );
      }),
    ),
  );
}
```

in my app, the pageA user do something on it, and will route to pageB, and pageB. in pageB user will tap some item on listView and  route to pageC. when user complete something in pageC, pageC will back to pageB with call **"Get.back"** and then the pageB back to the pageA with call **"Get.back"** too!

the problem is, when user route to pageB from pageA again, sometime the pageB will not fetchData anymore and leave the old data on the page, because i fetch the http remote data from GetController onInit lifecycle. i try to print some log, i found there are no output in my console. i don't know what problem it is! 

here is my cod of pageB

view file:

```dart
class PageB extends StatelessWidget {
    final PageBLogic logic = Get.put(PageBLogic());
    
    Widget build(BuildContext context) {
        return GetBuilder<PageBLogic>(
            builder: (logic) => Scaffold(
               // ...sth code 
           )
        );
    }
}
```

logic file:
```dart
// use SingleGetTickerProviderMixin because i need to set tabBarController
class PickingListDetailLogic extends GetxController with SingleGetTickerProviderMixin {
    final state = PickingListDetailState();

    late TextEditingController scanController;

    TabController? tabController;



  @override
  void onReady() {
    super.onReady();
    Log.info('===========picking detail ready');
    this.load();
  }

  @override
  void onClose() {
    try {
      scanController.dispose();
      if (tabController != null) {
        tabController!.dispose();
      }
    } catch (err) {
      Log.error('=====picking detail close error ${err.toString()}');
    }

    Log.info('========picking detail close');
    super.onClose();
  }

  @override
  void onInit() async {
    Log.info('=======picking detail init');
    Log.info('====== init params ${Get.arguments["pickingListId"].toString()}');
    state.id = int.parse(Get.arguments["pickingListId"].toString());
    state.skuInPicking = {};
    scanController = TextEditingController();
    super.onInit();
  }

}

```

i have any problem on use getx? or anything can lead this problem occur ? i hope you can tell me

**Expected behavior**
onInit, onReady, onClose will call

**Flutter Version:**
2.14.4

**Getx Version:**
4.3.0

**Describe on which device you found the bug:**
Android 9
the pda terminal

**Minimal reproduce code**
as previous i told

**Comment by StitchC** [comment]
anybody can give me some reply ?

**Comment by allasca** [comment]
> anybody can give me some reply ?

@StitchC  try use get_cli, it's much simpler and you will understand better. if you do 
```
get create page:login 
```
in get_cli, it will auto make LoginView:
```dart
class LoginView extends GetView<LoginController> {
  @override
  Widget build(BuildContext context) {
...
print(controller.text.value) // from login controller
...
```
and auto create login controller
```dart
class LoginController extends GetxController {
var text = 'from login controller'.obs;

  @override
  void onInit() {
    super.onInit();
  }

on dispose
on delete
on ready
in here
```

**Comment by cyz1901** [comment]
> 有人可以给我一些答复吗？

I think you can explicitly call the controller of other pages on other pages

like 
A->B->C(you can get `BController` and use `await bController.fetchDataInBpage()`)->B->A

**Comment by StitchC** [comment]
this problem i found that, when i pop the page (use Get.back()) some error were emit, and when i go into the same page, every lifecycle were not call anymore. 

and the way to make the error emit is my focusNode instance
when the page destroy, still has some reference the focusNode, so went some wrong in the lifecycle callback and let the issue shown in the end.

there are not the problem with getx framework

ps: the app log file is very very important

**Comment by Farazmicm** [comment]
cant call onInit  method in getx
