### ISSUE TITLE
I have error in new version of getx

### ISSUE THREAD

**Issue by abbasihamed** [jonataslaw/getx#2053]
I use any version of getx, it gives me the following error

/home/hamed/develpment/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.0/lib/get_connect/http/src/http.dart:60:11: Error: No named parameter with the name 'findProxy'.
          findProxy: findProxy,
          ^^^^^^^^^
/home/hamed/develpment/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.0/lib/get_connect/http/src/http/html/http_request_html.dart:13:3: Context: Found this candidate, but the arguments don't match.
  HttpRequestImpl({
  ^^^^^^^^^^^^^^^

**Comment by Macacoazul01** [comment]
Its happening also on get: 4.5.1, 4.5.0, 4.3.8 and older versions

**Comment by Macacoazul01** [comment]
Duplicate of #2052 with details

**Comment by ChamikaAshen** [comment]
happened to me too. Using Flutter 2.8 
Get 4.6.0

**Comment by abbasihamed** [comment]
> Duplicate of #2052 with details

**Comment by abbasihamed** [comment]
> Its happening also on get: 4.5.1, 4.5.0, 4.3.8 and older versions

Yes, I tried it but it did not work

**Comment by Macacoazul01** [comment]
It's strange that nobody noticed it before. Maybe it's related to flutter 2.8.0

**Comment by abbasihamed** [comment]
> It's strange that nobody noticed it before. Maybe it's related to flutter 2.8.0

I don't know, I have no problem with my previous projects, but when I create a new project, it gives an error

**Comment by jonataslaw** [comment]
I'll take a look at this

**Comment by Macacoazul01** [comment]
Can confirm it's everything ok on mobile with version 4.6.0

**Comment by jonataslaw** [comment]
Fixed on lastest version
