### ISSUE TITLE
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/root/get_cupertino_app.dart:252:17: Error: No named parameter with the name 'useInheritedMediaQuery'.                 useInheritedMediaQuery: useInheritedMediaQuery,

### ISSUE THREAD

**Issue by akazi-michael-chukwuemeka** [jonataslaw/getx#2071]
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      useInheritedMediaQuery: true,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, this.title}) : super(key: key);

  final String? title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title!),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by jkfrancis06** [comment]
Have the save issue

**Comment by Mouslim2021** [comment]
Same problem for me

**Comment by ameya730** [comment]
I am facing this issue as well. I just started a new project today and if I even import <<import 'package:get/get.dart';>>, I get this warning 
AppData/Local/Pub/Cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/root/get_cupertino_app.dart:252:17: Error: No named parameter with the name 'useInheritedMediaQuery'.
                useInheritedMediaQuery: useInheritedMediaQuery,

**Comment by Danial-Barazandeh** [comment]
I started my new project and I have the same problem. all of my old projects work fine, my get is 4.6.1 and my flutter, dart, and android studio is the latest version.

**Comment by shadowsum07** [comment]
i had the same issue , resolved it by updating get 4.3.8 version manually  , in pubspec.yaml and pubspec.lock and inside .dart/libraries/Dart_Packages.xml file

**Comment by PhantomK520** [comment]
> i had the same issue , resolved it by updating get 4.3.8 version manually , in pubspec.yaml and pubspec.lock and inside .dart/libraries/Dart_Packages.xml file

I have encountered same issue, This worked for me as well.

**Comment by jaimin-grubbrr** [comment]
getting same error  ```Error: No named parameter with the name 'useInheritedMediaQuery'```

**Comment by jonataslaw** [comment]
Just update Flutter or use version 4.5.1 of GetX
The version 4.6.0 or higher complies with the latest version of Flutter:
https://pub.dev/packages/get/changelog#460

**Comment by nekooooo0203** [comment]
Is this not a breaking change?
