### ISSUE TITLE
Get.Snackbar not working GetMaterialApp.router

### ISSUE THREAD

**Issue by NguyenNhan99** [jonataslaw/getx#2088]
**Describe the bug**
I'm using auto router and I want to show snackbar but it doesn't seem to work.
Please help me with this problem

example:

```dart
GetMaterialApp.router(
        debugShowCheckedModeBanner: false,
        theme: theme.data,
        darkTheme: AppTheme.light().data,
        themeMode: themeMode,
        localizationsDelegates: [
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales:S.delegate.supportedLocales,
        routeInformationParser: appRouter.defaultRouteParser(),
        routerDelegate: appRouter.delegate(),
      )
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flutter Version:**
Enter the version of the Flutter you are using

**Getx Version:**
get: ^4.5.1

**Describe on which device you found the bug:**
ex: Moto z2 - Android.

**Minimal reproduce code**

**Comment by Dr-Usman** [comment]
@NguyenNhan99  @jonataslaw  Sir any update please, I'm facing the same issue..

**Comment by Attri-242** [comment]
Any update?
