### ISSUE TITLE
Binary body is encoded when request with GetConnect

### ISSUE THREAD

**Issue by robertzhaodev** [jonataslaw/getx#2117]
**Describe the bug**
I'm using GetConnect to upload images to AWS S3 with pre-signed url. But the file affter uploading cannot be opened.
It works fine if I use http package.

**Reproduction code**
This is my request:

```dart
print('Uploading to S3. File mime $fileMime');
var response = await GetConnect().put(
  preSignedUrl,
  file.readAsBytesSync(),
  contentType: fileMime,
  uploadProgress: (percent) {
    print(percent);
    onProcess(percent);
  },
);

if(!response.isOk) {
  print('Error - ${response.bodyString}');
  return null;
} else {
  print(' S3 upload successfully');
}
```

After searching on google and looking at the code I found that GetConnect is encoded the contents of my binary:
```dart
// File name: lib/get_connect/http/src/http.dart
Future<Request<T>> _requestWithBody<T>(
    String? url,
    String? contentType,
    dynamic body,
    String method,
    Map<String, dynamic>? query,
    Decoder<T>? decoder,
    Progress? uploadProgress,
  ) async {
    List<int>? bodyBytes;
    Stream<List<int>>? bodyStream;
    final headers = <String, String>{};

    if (sendUserAgent) {
      headers['user-agent'] = userAgent;
    }

    if (body is FormData) {
      bodyBytes = await body.toBytes();
      headers['content-length'] = bodyBytes.length.toString();
      headers['content-type'] =
          'multipart/form-data; boundary=${body.boundary}';
    } else if (contentType != null &&
        contentType.toLowerCase() == 'application/x-www-form-urlencoded' &&
        body is Map) {
      var parts = [];
      (body as Map<String, dynamic>).forEach((key, value) {
        parts.add('${Uri.encodeQueryComponent(key)}='
            '${Uri.encodeQueryComponent(value.toString())}');
      });
      var formData = parts.join('&');
      bodyBytes = utf8.encode(formData);
      headers['content-length'] = bodyBytes.length.toString();
      headers['content-type'] = contentType;
    } else if (body is Map || body is List) {
      var jsonString = json.encode(body);

      // my file content is encoded here
      bodyBytes = utf8.encode(jsonString);
      headers['content-length'] = bodyBytes.length.toString();
      headers['content-type'] = contentType ?? defaultContentType;
    } else if (body is String) {
      bodyBytes = utf8.encode(body);
      headers['content-length'] = bodyBytes.length.toString();
      headers['content-type'] = contentType ?? defaultContentType;
    } else if (body == null) {
      headers['content-type'] = contentType ?? defaultContentType;
      headers['content-length'] = '0';
    } else {
      if (!errorSafety) {
        throw UnexpectedFormat('body cannot be ${body.runtimeType}');
      }
    }

    if (bodyBytes != null) {
      bodyStream = _trackProgress(bodyBytes, uploadProgress);
    }

    final uri = _createUri(url, query);
    return Request<T>(
      method: method,
      url: uri,
      headers: headers,
      bodyBytes: bodyStream,
      contentLength: bodyBytes?.length ?? 0,
      followRedirects: followRedirects,
      maxRedirects: maxRedirects,
      decoder: decoder,
    );
  }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/44677489/148729692-d07d512a-7a50-413e-915f-467b44857c1b.png)

**Flutter Version:**
2.8.0 stable

**Getx Version:**
4.5.1

Sorry for my English not good

**Comment by thomasgi1** [comment]
We have the same issue, when uploading a PDF file using GetConnect. Currently GetConnect does not offer any way to pass the body without any transformation (utf8 encode, JSON encode etc.).

**Comment by inyong1** [comment]
> **Describe the bug** I'm using GetConnect to upload images to AWS S3 with pre-signed url. But the file affter uploading cannot be opened. It works fine if I use http package.
> 
> **Reproduction code** This is my request:
> 
> ```dart
> print('Uploading to S3. File mime $fileMime');
> var response = await GetConnect().put(
>   preSignedUrl,
>   file.readAsBytesSync(),
>   contentType: fileMime,
>   uploadProgress: (percent) {
>     print(percent);
>     onProcess(percent);
>   },
> );
> 
> if(!response.isOk) {
>   print('Error - ${response.bodyString}');
>   return null;
> } else {
>   print(' S3 upload successfully');
> }
> ```
> 
> After searching on google and looking at the code I found that GetConnect is encoded the contents of my binary:
> 
> ```dart
> // File name: lib/get_connect/http/src/http.dart
> Future<Request<T>> _requestWithBody<T>(
>     String? url,
>     String? contentType,
>     dynamic body,
>     String method,
>     Map<String, dynamic>? query,
>     Decoder<T>? decoder,
>     Progress? uploadProgress,
>   ) async {
>     List<int>? bodyBytes;
>     Stream<List<int>>? bodyStream;
>     final headers = <String, String>{};
> 
>     if (sendUserAgent) {
>       headers['user-agent'] = userAgent;
>     }
> 
>     if (body is FormData) {
>       bodyBytes = await body.toBytes();
>       headers['content-length'] = bodyBytes.length.toString();
>       headers['content-type'] =
>           'multipart/form-data; boundary=${body.boundary}';
>     } else if (contentType != null &&
>         contentType.toLowerCase() == 'application/x-www-form-urlencoded' &&
>         body is Map) {
>       var parts = [];
>       (body as Map<String, dynamic>).forEach((key, value) {
>         parts.add('${Uri.encodeQueryComponent(key)}='
>             '${Uri.encodeQueryComponent(value.toString())}');
>       });
>       var formData = parts.join('&');
>       bodyBytes = utf8.encode(formData);
>       headers['content-length'] = bodyBytes.length.toString();
>       headers['content-type'] = contentType;
>     } else if (body is Map || body is List) {
>       var jsonString = json.encode(body);
> 
>       // my file content is encoded here
>       bodyBytes = utf8.encode(jsonString);
>       headers['content-length'] = bodyBytes.length.toString();
>       headers['content-type'] = contentType ?? defaultContentType;
>     } else if (body is String) {
>       bodyBytes = utf8.encode(body);
>       headers['content-length'] = bodyBytes.length.toString();
>       headers['content-type'] = contentType ?? defaultContentType;
>     } else if (body == null) {
>       headers['content-type'] = contentType ?? defaultContentType;
>       headers['content-length'] = '0';
>     } else {
>       if (!errorSafety) {
>         throw UnexpectedFormat('body cannot be ${body.runtimeType}');
>       }
>     }
> 
>     if (bodyBytes != null) {
>       bodyStream = _trackProgress(bodyBytes, uploadProgress);
>     }
> 
>     final uri = _createUri(url, query);
>     return Request<T>(
>       method: method,
>       url: uri,
>       headers: headers,
>       bodyBytes: bodyStream,
>       contentLength: bodyBytes?.length ?? 0,
>       followRedirects: followRedirects,
>       maxRedirects: maxRedirects,
>       decoder: decoder,
>     );
>   }
> ```
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/44677489/148729692-d07d512a-7a50-413e-915f-467b44857c1b.png)
> 
> **Flutter Version:** 2.8.0 stable
> 
> **Getx Version:** 4.5.1
> 
> Sorry for my English not good

Maybe you have to use MutlipartFormData. So, it will enter to this logic
` if (body is FormData) {
      bodyBytes = await body.toBytes();
      headers['content-length'] = bodyBytes.length.toString();
      headers['content-type'] =
          'multipart/form-data; boundary=${body.boundary}';
    }`

**Comment by robertzhaodev** [comment]
I solved this problem by removing all GetX packages from my project and reverting back to BloC. :D

**Comment by pravindodia** [comment]
Is there any solution for this issue ?

**Comment by pravindodia** [comment]
I did this alternatively for now
GetConnect should have native method for this
```dart
HttpRequestBase httpRequestBase = platform.HttpRequestImpl(
        allowAutoSignedCert: allowAutoSignedCert,
        trustedCertificates: trustedCertificates,
        withCredentials: withCredentials,
        findProxy: findProxy,
      );
      final dataLength = fileBytes.length;
      Request request = Request(
          url: Uri.parse(
              'https://pm.rultech.com/uploads.json?filename=$fileName'),
          contentLength: dataLength,
          decoder: (data) => data,
          headers: {
            'content-length': "$dataLength",
            'content-type': 'application/octet-stream',
            Map<String, String>.from(GetStorage().read(header)).keys.first:
                Map<String, String>.from(GetStorage().read(header)).values.first
          },
          method: "POST",
          bodyBytes: Stream.value(fileBytes));

```

**Comment by inyong1** [comment]
> Is there any solution for this issue ?
Use FormData as Your request body

**Comment by pravindodia** [comment]
> > Is there any solution for this issue ?
> > Use FormData as Your request body
@inyong1 
Cannot use Form data as the server does not accept formdata

**Comment by inyong1** [comment]
> I solved this problem by removing all GetX packages from my project and reverting back to BloC. 👎

There is no relation between getConnect and Bloc. 
getconnect is a networking management and bloc is a state management
If you want, You can compare it with http or dio for example

**Comment by pravindodia** [comment]
@inyong1 Regardless, Getx needs to update GetConnect to support binary data since some servers won’t function properly with the current options. GetConnect should be adaptable enough to handle all types of servers. Hopefully, this issue is resolved in the newer Getx packages.
