### ISSUE TITLE
GetBuilder id supports apply multiple ids

### ISSUE THREAD

**Issue by sleepreading** [jonataslaw/getx#2124]
This case is very common:
```
update(['loginStatus', 'news']);
```

But GetBuilder doesn't support multiple ids(We don't wanna catch every id, just care about some of them .)

**Comment by jakobleck** [comment]
Please explain. The situation is: You can assign an ID to a GetBuilder and you can call update with a list of IDs to update more than one GetBuilder possibly. Why would you want to attach more than one ID to a GetBuilder?

**Comment by sleepreading** [comment]
> Please explain. The situation is: You can assign an ID to a GetBuilder and you can call update with a list of IDs to update more than one GetBuilder possibly. Why would you want to attach more than one ID to a GetBuilder?

Sorry for my poor English:
Sometimes event like 'login status' would affect the whole page(let's call A).
A may look like this:
```

// <-- not sure to add this GetBuilder. but think about there someone login with the same userid, and the old one was kicked out.
//     so we need to update the whole page, not just the id1.
//     !! In fact, the login status event will affect every page(not just A). but each page should have a small and specific 'GetBuilder', So I'm confused here.
GetBuilder<XController>(
id: "id0"
builder: (v){
return Column(
  crossAxisAlignment: CrossAxisAlignment.start,
  children: [
    GetBuilder<Controller>(
      id: "id1",
      builder: (v) {
        return Text(
          "xxxxxx",  // <-- this value comes from a standalone api call.
          style: TextStyle(
            fontSize: 10.ft,
          ),
        );
      },
    ),
    SizedBox(height: 30),
    Center(child: XxView()),
    SizedBox(height: 100),
  ],
);
}
)
```

**Comment by sleepreading** [comment]
I switch to `Provider`, and use Consumer2<...> to do this.

**Comment by saviourdog** [comment]
need too
