### ISSUE TITLE
Nested Navigation isn't working correctly in Nav 2.0, when it comes to more than 3 nested Pages 

### ISSUE THREAD

**Issue by wilz05** [jonataslaw/getx#2134]
If I want to navigate to 3 nested pages it works well 

- /A/B/C (like from A-> B, B->C ) while using  Get.rootDelegate.toNamed method
- /A/B/C/D (like from A-> B, B->C works till here, from C to D it does not work ), lets say I have only static files without parameters

**Reproduction code
````
GetPage(
          preventDuplicates: true,
          name: "/home",
          page: () => HomeView(),
          bindings: [
            HomeBinding(),
          ],
          title: "Home",
          children: [
            GetPage(
                middlewares: [
                  EnsureAuthMiddleware(),
                ],
                title: "Dashboard",
                name: "/dashboard",
                page: () => DashboardView(),
                binding: DashboardBinding(),
                children: [
                   GetPage(
                    title: "page C",
                    name: "/pageC",
                    middlewares: [
                      EnsureAuthMiddleware(),
                    ],
                    page: () => PageC(),
                    binding: PageCBinding(),
                    children: [
                      GetPage(
                        title: "PageD",
                        name: "/pageD",
                        page: () => PageD(),
                        binding: PageDBinding(),
                      ),
                    ],
                  ),
                ]),
            

           
 

````
 **To Reproduce**

``` 
// until pageC If I write below code it navigates 
           InkWell(
                onTap: () {
                  Get.rootDelegate.toNamed('/home/dashboard/pageC');
                }

// If I am in PageC then  call the below code 
           Get.rootDelegate.toNamed('/home/dashboard/pageC/pageD'); // this code seems to be not working..


```
 

**Flutter Version:**
 2.8.1 

**Getx Version:**
^4.6.1

**Describe on which device you found the bug:**
ex: Simulators iOS 15.2... Android api 30

I am not sure whether I am using proper navigator 2.0 methods correctly.

**Comment by CoderJerry** [comment]
Yes, I am also facing the same issue.

**Comment by wilz05** [comment]
@ahmednfwela Is it a default behavior or... , could you please help me out with the above ?

**Comment by ahmednfwela** [comment]
I will have to see a complete reproduction code to help

**Comment by wilz05** [comment]
@ahmednfwela
[example_nav2_nested.zip](https://github.com/jonataslaw/getx/files/7940651/example_nav2_nested.zip)
please find the attachment. example file uses getx version 4.6.1. Please look for goto PageC button inside the dashboard screen.



And 
I have tried to clone the latest [Getx Link](https://github.com/jonataslaw/getx) repo,  nav2 example it has some issues while pressing bottom bars. it does not respond.

**Comment by ahmednfwela** [comment]
it's because of an issue that has been brought up multiple times, you forgot to specify `anchorRoute`
![image](https://user-images.githubusercontent.com/63286031/151199245-13862e57-6a16-4089-9efe-c1a6de19ce23.png)

@jonataslaw your implementation is causing problems for long routes, please revert it to my implementation here https://github.com/jonataslaw/getx/pull/1652/commits/360c76c12da951d75073b0afec16fcc611664f64

**Comment by wilz05** [comment]
@ahmednfwela  thank you so much for the above will give a try..  please check the [example_nav2](https://github.com/jonataslaw/getx/tree/master/example_nav2) project. it does not work correctly.
