### ISSUE TITLE
Get.defaultDialog not updating variable!!

### ISSUE THREAD

**Issue by ashokavarthanan** [jonataslaw/getx#2159]
import 'package:flutter/material.dart';
	import 'package:get/get.dart';

	class DemoDatePage extends StatelessWidget {
	  const DemoDatePage({Key? key}) : super(key: key);
	  @override
	  Widget build(BuildContext context) {
		return GetBuilder<DemoDatePageController>(
		  init: DemoDatePageController(),
		  builder: (S) => Scaffold(
			appBar: AppBar(
			  title: const Text('DEMO-DATE'),
			  actions: <Widget>[
				IconButton(
				  onPressed: () {
					Get.defaultDialog(
					  title: "ChangeDate.",
					  content: Row(
						children: [
						  Text("${S.selectedDate.toLocal()}".split(' ')[0]),
						  IconButton(
							icon: const Icon(Icons.date_range_sharp),
							color: Colors.red,
							onPressed: () async {
							  DateTime? picked = await showDatePicker(
								  context: context,
								  initialDate: S.selectedDate,
								  firstDate: DateTime(2015, 8),
								  lastDate: DateTime(2101));
							  S.changeDate(picked);
							},
						  ),
						],
					  ),
					);
				  },
				  icon: const Icon(Icons.add_sharp),
				),
			  ],
			),
			body: Text("${S.selectedDate.toLocal()}".split(' ')[0]),
		  ),
		);
	  }
	}

	class DemoDatePageController extends GetxController {
	  DateTime selectedDate = DateTime.now();
	  @override
	  // ignore: must_call_super
	  Future<void> onInit() async {}

	  @override
	  // ignore: must_call_super
	  void dispose() {}

	  changeDate(val) {
		selectedDate = val;
		update();
	  }
	}

when Change the date the date was changed in **body** 
But **Not Changing**  `Get.defaultDialog` 
Update: Code.

**Comment by ashokavarthanan** [comment]
can you solve this?

**Comment by RizaldiWiratama** [comment]
i think u should wrap Row in a GetBuilder again

so it will be 

```
Get.defaultDialog(
  title: "ChangeDate.",
  content: GetBuilder(
     init : DemoDatePageController(),
     builder : (S)=> Row(
       ...
     ) 
  )
)
```

**Comment by ashokavarthanan** [comment]
Problem Solved .
So "**GetBuilder**" inside again using "**GetBuilder**".

Thanks .
