### ISSUE TITLE
GetPlatform returning wrong platform.

### ISSUE THREAD

**Issue by fjvgallego** [jonataslaw/getx#2184]
**Describe the bug**
GetPlatform returns true for GetPlatform.isAndroid when using a web app on an Android Device.
This may also happen on an iOS device.

**Reproduction code
```dart
import 'package:get/get.dart';

void main() => runApp(MaterialApp(home: Home()));

class Home extends StatelessWidget {
  final count = 0.obs;
  @override
  Widget build(context) => Scaffold(
      appBar: AppBar(title: Text("counter")),
      body: Center(
        child: GetPlatform.isWeb ? Text("Web") : Text("Android"),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => count.value++,
      ));
}
```

**To Reproduce**
1. Open a browser from an Android device.
2. Access a Flutter web app.
3. Debug and check that GetPlatform returns true for GetPlatform.Android instead for GetPlatform.Web

**Expected behavior**
Despite being on an Android device, if a Flutter app is accessed through any browser, GetPlatform should return true for GetPlatform.isWeb.

NOTE: The kIsWeb variable from the **foundation** package works as I've just explained.

**Flutter Version:**
2.10.1

**Getx Version:**
4.6.1

**Describe on which device you found the bug:**
Xiaomi Mi 10 Lite

**Comment by fuhrthom** [comment]
It is behaving as it should. Please read the documentation, there it says:

„ //All platforms are supported independently in web!
//You can tell if you are running inside a browser
//on Windows, iOS, OSX, Android, etc.“

**Comment by philos3** [comment]
static bool get isWeb => GetPlatform.isWeb;
static bool get isAndroid => !isWeb && GetPlatform.isAndroid;
static bool get isIOS => !isWeb && GetPlatform.isIOS;

**Comment by jonataslaw** [comment]
I don't see how this could be a bug.
You are using an android device, so `isAndroid` should be `true`.
I think this is a feature, not a bug.
If you want, you can use `GetPlatform.isAndroid && !GetPlatform.isWeb` to limit `GetPlatform` to not tracking the web. Is it reasonable for you?

**Comment by jonataslaw** [comment]
Exactly

**Comment by fjvgallego** [comment]
No problem then, I misunderstood it at first. Thank you!
