### ISSUE TITLE
middlewares: being executed even after a redirection

### ISSUE THREAD

**Issue by Martichou** [jonataslaw/getx#2194]
**Describe the bug**
If a middleware using redirectDelegate returned a different
route using return RouteDecoder.fromRoute for example, the
middlewares executions stack continued and we ended up with
middleware being executed on the wrong route.

**Reproduction code**

example:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class LoggedMiddleware extends GetMiddleware {
  @override
  // ignore: overridden_fields
  int? priority;

  LoggedMiddleware({required this.priority});

  @override
  Future<GetNavConfig?> redirectDelegate(GetNavConfig route) async {
    print("LoggedMiddleware... current: " + route.currentPage!.name);
    print("Redirecting to login");
    return GetNavConfig.fromRoute(Routes.login);
  }
}

class DummyMiddleware extends GetMiddleware {
  @override
  // ignore: overridden_fields
  int? priority;

  DummyMiddleware({required this.priority});

  @override
  Future<GetNavConfig?> redirectDelegate(GetNavConfig route) async {
    print("DummyMiddleware... current: " + route.currentPage!.name);
    return route;
  }
}

abstract class Routes {
  static const home = '/home';
  static const login = '/login';
}

final appPages = [
  // Login page - NOT LOGGED
  GetPage(
      name: Routes.login,
      page: () => const LoginPage(),
      middlewares: [DummyMiddleware(priority: 0)]),
  // Home page - LOGGED & HasCpe & IsActivated
  GetPage(name: Routes.home, page: () => const HomePage(), middlewares: [
    LoggedMiddleware(priority: 0),
    DummyMiddleware(priority: 1),
  ]),
];

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp.router(
      title: 'redir',
      debugShowCheckedModeBanner: false,
      getPages: appPages,
      color: Colors.red,
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(48),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: const [
            Text("HOME", style: TextStyle(fontSize: 24)),
          ],
        ),
      ),
    );
  }
}

class LoginPage extends StatelessWidget {
  const LoginPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(48),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: const [
            Text("LOGIN", style: TextStyle(fontSize: 24)),
          ],
        ),
      ),
    );
  }
}
```

**To Reproduce**
1. Run the flutter web-server (not sure if same on Android/IOS): `flutter run -d web-server`
2. Navigate to the `webpage/home` and observe the console
3. You'll see something like:
```
LoggedMiddleware... current: /home
Redirecting to login
DummyMiddleware... current: /login
```

**Expected behavior**
We can expect that the DummyMiddleware won't be runned in this case no? As we already changed route with the LoggedMiddleware. Because in the current state, the DummyMiddleware is being runned on the login page even if the DummyMiddleware is not defined on the login route.

**Flutter Version:**
```
Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (7 days ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2
```

**Getx Version:**
```
get: ^4.6.1
```
And I think it's the same on Master. I've made a workaround for my project, not sure if it would be ok to open a PR, you can check it here: https://github.com/Martichou/getx/commit/9f86ca02d9042ee2260117d7c225cec1edf96d92.

**Describe on which device you found the bug:**
Web browser.

**Comment by stefandevo** [comment]
@Martichou pls post the PR
@jonataslaw can you have a look at it?

**Comment by jonataslaw** [comment]
@Martichou  Could you please do a PR?
@ahmednfwela  would also be nice your input here since you introduced this feature

**Comment by Martichou** [comment]
The PR is posted, any comments are welcome ! :)

**Comment by ahmednfwela** [comment]
actually this was an intended behavior
lets say you are on route A and redirect to Route B
but route B can only be entered if you are logged in, so you redirect again to route C

**Comment by ahmednfwela** [comment]
that's why the middleware redirection should be based on a condition

**Comment by jonataslaw** [comment]
Thanks for your PR. 

Let me see if I understood:
Is the complaint about the rest of the middleware running after a redirect?
I understand useCase, but I'm intrigued if it wouldn't break the middlewares' priority order.

**Comment by eliasjtg** [comment]
I'm awaiting for this PR, i have the same issue

**Comment by Martichou** [comment]
@eliasjtg From the author perspective this seems to be a "feature" and not a bug. They closed the PR I've opened a while ago.

Thus I have personally migrated to another library that handle middlewares as I want (it's [AutoRoute](https://pub.dev/packages/auto_route), fairly easy to use, you may want to check it too).

**Comment by eliasjtg** [comment]
@Martichou  The whole GetX route and middleware issue should be seriously reviewed by the development team, some things have been hell.

1._ Asynchronous middlewares leave the screen black
2._ Middlewares are supposed to be executed in order.

I have a middleware that verifies that it is authenticated and a second one that consumes an api where it should be logged in because I already went through the previous middleware, and both are executed, it doesn't make sense...

**Comment by Martichou** [comment]
@eliasjtg That was also one of my issue back then. And is the reason why I opened [this PR](https://github.com/jonataslaw/getx/pull/2204).  

I'm not sure they intend to fix this issue, nor if they consider this to be an issue as they seems to be very quiet about it.
I won't waste more time trying to get this fixed in Getx as I got it working perfectly with AutoRoute :)

**Comment by eliasjtg** [comment]
I'm installing your package, thanks you for your help!
