### ISSUE TITLE
Example program "example" problem with Android version 6.0.1

### ISSUE THREAD

**Issue by brianoh** [jonataslaw/getx#2203]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
Error Message:
A error occurred. Handshake exception: Handshake error in client (OS error: CERTIFICATE_VERIFY_FAIED: Certificate has expired (handshake.cc 393).
This is a known problem with Flutter/Android for Android Version 6.0.1. There is a known fix for it, but I don't know how to apply that fix to GetX code.

**Reproduction code
The code is in file home_api_provider.dart:
 @override
  void onInit() {
    httpClient.defaultDecoder =
        (val) => CasesModel.fromJson(val as Map<String, dynamic>);
    httpClient.baseUrl = 'https://api.covid19api.com';
    super.onInit();
  }

example:

```
Not applicable, error message is above and program is part of package.

An example of the code posted elsewhere to fix the problem is as follows:
class PostHttpOverrides extends HttpOverrides{
  @override
  HttpClient createHttpClient(SecurityContext context){
    return super.createHttpClient(context)
      ..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
  }
}
```

**To Reproduce**
Run the example program on an Android device running Android Version 6.0.1.
**Expected behavior**
I expect the same behavior as on a later Android API. IE: for the Http Get to work.
The "example" program works fine on eg. Android 11.

**Screenshots**
Not needed, error message is above.
**Flutter Version:**
Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (2 days ago) • 2022-02-18 19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2

**Getx Version:**
5.0.0-beta.18

**Describe on which device you found the bug:**
Moto G (3rd generation)

**Minimal reproduce code**
The code is in the program "example" in GetX package, which provides Covid-19 information by country.
The has been described on StackOverflow and elsewhere, but I don't know how to implement the fix (above) in the GetX code.

**Comment by Shreemanarjun** [comment]
#1383 Please refer this.

**Comment by brianoh** [comment]
@Shreemanarjun: Thanks for the advice. What does "refer" mean? I presume that if this is not an GetX issue then I should be able to make it work because that appears to be possible with non-GetX. Is it possible to get this to work on an Android 6 version? Further guidance on this would be appreciated, because I presume that Flutter programs should still work with Android-6. I accept that it's not a bug per se, but it's not an enhancement and it needs a work-around. Regards.

**Comment by Shreemanarjun** [comment]
@jonataslaw  @brianoh Please close this issue.

**Comment by brianoh** [comment]
Unfriendly and unhelpful!

**Comment by Msangi21** [comment]
@brianoh Please have you found the solution?
That error happened to me also and Up to know I don't know to fix it with getx
