### ISSUE TITLE
Operand of null-aware 

### ISSUE THREAD

**Issue by oeng-hok-leng** [jonataslaw/getx#2220]
I got this warning when I try to use get package.

Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/src/extension_navigation.dart:357
- 'SchedulerBinding' is from 'package:flutter[/src/scheduler/binding.dart]()' ('.[./../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart]()').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^

: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/src/extension_navigation.dart:468
- 'SchedulerBinding' is from 'package:flutter[/src/scheduler/binding.dart]()' ('.[./../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart]()').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^

: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/snackbar/snackbar.dart:452
- 'SchedulerBinding' is from 'package:flutter[/src/scheduler/binding.dart]()' ('.[./../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart]()').
package:flutter/…/scheduler/binding.dart:1
    SchedulerBinding.instance!.addPostFrameCallback(
                     ^

: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
../…/rx_flutter/rx_disposable.dart:20
- 'SchedulerBinding' is from 'package:flutter[/src/scheduler/binding.dart]()' ('.[./../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart]()').
package:flutter/…/scheduler/binding.dart:1
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^

: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
../…/rx_flutter/rx_notifier.dart:130
- 'SchedulerBinding' is from 'package:flutter[/src/scheduler/binding.dart]()' ('.[./../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart]()').
package:flutter/…/scheduler/binding.dart:1
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^

: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/simple/get_controllers.dart:90
- 'WidgetsBinding' is from 'package:flutter[/src/widgets/binding.dart]()' ('.[./../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart]()').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addObserver(this);
                   ^

: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/simple/get_controllers.dart:96
- 'WidgetsBinding' is from 'package:flutter[/src/widgets/binding.dart]()' ('.[./../../../../Development/flutter/packages/flutter/lib/src/widgets/binding.dart]()').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.removeObserver(this);
                   ^

**Comment by arjundevlucid** [comment]
Which versionaof getx and flutter you are using?

**Comment by xdawn97** [comment]
I've got this sort of warnings too.
@arjundevlucid
@jonataslaw 

### Log Information
<details><summary><b>Warnings</b></summary>

```

../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart(357,24): warning G1E0FE241: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [D:\Users\xdawn\IdeaProjects\cygnus_lab\build\windows\flutter\flutter_assemble.vcxproj]
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart(468,24): warning G1E0FE241: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [D:\Users\xdawn\IdeaProjects\cygnus_lab\build\windows\flutter\flutter_assemble.vcxproj]
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/snackbar/snackbar.dart(452,22): warning G1E0FE241: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [D:\Users\xdawn\IdeaProjects\cygnus_lab\build\windows\flutter\flutter_assemble.vcxproj]
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_disposable.dart(20,22): warning G1E0FE241: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null. [D:\Users\xdawn\IdeaProjects\cygnus_lab\build\windows\flutter\flutter_assemble.vcxproj]
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_notifier.dart(130,22): warning G1E0FE241: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null. [D:\Users\xdawn\IdeaProjects\cygnus_lab\build\windows\flutter\flutter_assemble.vcxproj]
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart(90,20): warning G1E0FE241: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\Users\xdawn\IdeaProjects\cygnus_lab\build\windows\flutter\flutter_assemble.vcxproj]
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart(96,20): warning G1E0FE241: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\Users\xdawn\IdeaProjects\cygnus_lab\build\windows\flutter\flutter_assemble.vcxproj]
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/router_report.dart(53,22): warning G1E0FE241: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\Users\xdawn\IdeaProjects\cygnus_lab\build\windows\flutter\flutter_assemble.vcxproj]
Debug service listening on ws://127.0.0.1:62875/0zOIscnB91E=/ws
Syncing files to device Windows...
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/snackbar/snackbar.dart:452:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(
                     ^
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/router_report.dart:53:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:90:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:96:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_notifier.dart:130:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_disposable.dart:20:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:357:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
../../Documents/PUB_CACHE/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:468:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutter/packages/flutter/lib/src/scheduler/binding.dart').


```
</details>

### My Current Environment Info
<details><summary><b>Flutter Doctor</b></summary>

```
✅  Flutter (Channel master, 2.11.0-0.0.pre.752, on Microsoft Windows [Version 10.0.22000.527], locale zh-CN)
    • Flutter version 2.11.0-0.0.pre.752 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a786f65700 (23 hours ago), 2022-03-03 03:01:22 -0500
    • Engine revision 993285f64d
    • Dart version 2.17.0 (build 2.17.0-165.0.dev)
    • DevTools version 2.11.1

✅ Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\xdawn\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

✅  Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

✅  Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32126.317
    • Windows 10 SDK version 10.0.19041.0

✅ Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

✅ IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.2
    • Flutter plugin version 64.1.4
    • Dart plugin version 213.5744.122

✅ Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.527]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.50

✅  HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><b>SystemInfo</b></summary>

```
主机名:           C00517-V
OS 名称:          Microsoft Windows 11 专业版
OS 版本:          10.0.22000 暂缺 Build 22000
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
初始安装日期:     2022/2/15, 9:44:21
系统启动时间:     2022/3/1, 1:44:16
系统制造商:       Microsoft Corporation
系统型号:         Virtual Machine
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 165 Stepping 3 GenuineIntel ~2304 Mhz
BIOS 版本:        Microsoft Corporation Hyper-V UEFI Release v4.0, 2019/11/1
Windows 目录:     C:\Windows
系统目录:         C:\Windows\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     11,263 MB
可用的物理内存:   1,008 MB
虚拟内存: 最大值: 23,343 MB
虚拟内存: 可用:   6,845 MB
虚拟内存: 使用中: 16,498 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
Hyper-V 要求:     已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。
```

</details>

### Expected

How can I fix all the warnings?

**Comment by Coder-Manuel** [comment]
Hello am also getting this warning and i can't build my app.
Am using get version 4.6.1 and flutter version 2.11.0-0.0.pre.751.

@arjundevlucid 
I presume `SchedulerBinding.instance` and `WidgetsBinding.instance` are no longer nullable in the latest flutter version.
Can you provide a hotfix to address the issue ?

**Comment by xdawn97** [comment]
## ✅  Issue Solved on My Computer

@oeng-hok-leng @Coder-Manuel 

I have googled further more. It seems that the nullabilities for packages depends on versions.
When I switched flutter channel from <strong>``MASTER``</strong> to <strong>``STABLE``</strong>, the warnings cleared.</br>
### My current version info:
> `Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.527], locale zh-CN) `
`get 5.0.0-beta.45`
</br>
However, there're known bugs for current stable flutter version to incoperate with my Intellij.
Maybe, some null-aware operators in GetX could be updated tracking chages for offical flutter revisions.
@jonataslaw @arjundevlucid

**Comment by Coder-Manuel** [comment]
@oeng-hok-leng 
I have a PR that addresses this issue.
You can take a look.

#2229 

Regards.

**Comment by oeng-hok-leng** [comment]
> ems that the nullabili

My current

**Comment by oeng-hok-leng** [comment]
> I've got this sort of warnings too. 😿 @arjundevlucid @jonataslaw
> 
> ### pubspec.yaml
> PubSpec
> ### Log Information
> Warnings
> ### My Current Environment Info
> Flutter Doctor
> SystemInfo
> ### Expected
> How should I fix all the warnings? 🆘



> Which version of getx and flutter you are using?
my current version of getx is 4.5.1

**Comment by oeng-hok-leng** [comment]
> @oeng-hok-leng, @jasonlaw I have a PR that addresses this issue. You can take a look.
> 
> #2229
> 
> Regards.

Thank You for helping me to solve this problem. I solved already by using @xdawn97 solution

**Comment by oeng-hok-leng** [comment]
> ## ✅ Issue Solved on My Computer
> @oeng-hok-leng @Coder-Manuel
> 
> I have googled further more. It seems that the nullabilities for packages depends on versions. When I switched flutter channel from **`MASTER`** to **`STABLE`**, the warnings cleared. It seems that some symbols in master branch turn to be **unnullable**, comparing to current stable branch.
> 
> ### My current version info:
> > `Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.527], locale zh-CN) `
> > `get 5.0.0-beta.45`
> 
> 
> However, there're known bugs for current stable flutter version to incoperate with my Intellij. Maybe, some null-aware operators in GetX could be updated tracking chages for offical flutter revisions. @jonataslaw @arjundevlucid

Thank You so much 😘
