### ISSUE TITLE
Restart app using getx

### ISSUE THREAD

**Issue by DevendraFlutterDev** [jonataslaw/getx#2226]
I am using getx for state management. My Project is Multi-language so I want to restart App. 

for restart, I am using Get.reset() but it's not working.

I used some plugins like restart_app: ^1.1.0 and flutter_phoenix: ^1.0.0 but it's not working when I use getx
without getx plugins are working.

**Comment by DevendraFlutterDev** [comment]
How can I restart my app using getx

**Comment by arjundevlucid** [comment]
you have to use 3rd party plugin like phoneix(app level restart) or restart app(device level).


Here is an example of Phoneix 
```dart
///Starting of flutter app
void main() {
  runApp(
    Phoenix(child: const MyApp()),
  );
}


ElevatedButton(
              onPressed: () {
//TODO:[Call this method to restart app in applicationlevel ]
                Phoenix.rebirth(context);
              },
              child: const Text('Restart App'),
            )



```

**Comment by arjundevlucid** [comment]
If issue fixed please close the issue.

**Comment by DevendraFlutterDev** [comment]
**Phoenix is not working with GetMaterialApp.**

I want to use contextless navigation so I am using GetMaterialApp but Phoenix or any plugins are not working with GetMaterialApp. It is working with MaterialApp.

Controllers are deleting but the app is not restarting.

Here is a demo application please check.
[https://github.com/DevendraFlutterDev/restartappusinggetx.git](url)

**Comment by Shreemanarjun** [comment]
Please mention which flutter and get version are you using.

**Comment by DevendraFlutterDev** [comment]
Flutter - Channel stable, 2.10.3
get: 4.6.1

**Comment by Shreemanarjun** [comment]
Can you share what ypu have tried? Phoneix used material app. And shared demo url is not public.

**Comment by DevendraFlutterDev** [comment]
I am using GetMaterialApp and demo URL is public.

**Comment by Shreemanarjun** [comment]
```dart
class SecondPageView extends GetView<SecondPageController> {
  const SecondPageView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SecondPageView'),
        centerTitle: true,
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () async {
                    //[Please try this]
            await Get.deleteAll(force: true);
            Phoenix.rebirth(Get.context!);
            Get.reset();
          },
          child: const Text(
            'Restart',
            style: TextStyle(fontSize: 20),
          ),
        ),
      ),
    );
  }
}


````

**Comment by Shreemanarjun** [comment]
@DevendraFlutterDev Please check this.

**Comment by DevendraFlutterDev** [comment]
Yes, It's working,
Thank you so much.

**I am requesting that please create a restart feature independently in GetX.**

**Comment by Mahmoudtarek59** [comment]
There is a problem in route after restart app

**Comment by mannanyumyapps** [comment]
I am using getx after get.updatelocale language change i press the next button to navigate next screen it will navigate for a second and get back to first screen

**Comment by phawadshah** [comment]
> class SecondPageView extends GetView<SecondPageController> {
>   const SecondPageView({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('SecondPageView'),
>         centerTitle: true,
>       ),
>       body: Center(
>         child: ElevatedButton(
>           onPressed: () async {
>                     //[Please try this]
>             await Get.deleteAll(force: true);
> 
> ///You can use normal context here within widget.
>             Phoenix.rebirth(Get.context!);
>             Get.reset();
>           },
>           child: const Text(
>             'Restart',
>             style: TextStyle(fontSize: 20),
>           ),
>         ),
>       ),
>     );
>   }
> }

Thank you for this, this is working as expected but the problem is it clears all the dependencies (bindings) and controllers from the memory  but if you have asynchronous bindings then how will you manage that. Initialising that is out of scope.

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await InitialBindings().initInitials();
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);
  PaintingBinding.instance.imageCache.clear();
  await DefaultCacheManager().emptyCache();

  runApp(
    Phoenix(child: const MyApp()),
  );
}

**Comment by phawadshah** [comment]
@Shreemanarjun @jonataslaw @Mahmoudtarek59 @arjundevlucid @DevendraFlutterDev 

Any help??

**Comment by Shreemanarjun** [comment]
Try this [https://pub.dev/packages/terminate_restart](plugin)
