### ISSUE TITLE
 FilterChip **not update**!

### ISSUE THREAD

**Issue by ashokavarthanan** [jonataslaw/getx#2230]
//  rpc is Controller.
           Container(
            height: 200,
            child: Obx(
              () => ListView(
                children: [
                  for (int i = 0; i < rpc.allPlayers.length; i++)
                    FilterChip(
                      selected: rpc.allPlayers[i].isSelect,
                      label: Text(rpc.allPlayers[i].player,
                          style: const TextStyle(color: Colors.white)),
                      avatar: const FlutterLogo(),
                      elevation: 10,
                      pressElevation: 5,
                      shadowColor: Colors.teal,
                      backgroundColor: Colors.black54,
                      selectedColor: Colors.blue,
                      onSelected: (bool selected) {
                        print(selected);
                        rpc.allPlayers[i].isSelect = selected;
                      },
                    ),
                ],
              ),
            ),
          ),

when select **not update**!
when **Hot reload** then update.
how to solve?
Thanks.

**Comment by Shreemanarjun** [comment]
Please wrap your FilterChip widget over obx

**Comment by ashokavarthanan** [comment]
> Please wrap your FilterChip widget inside obx

Sorry still not working..
but **setstate** method working.
**Getx** not working.

**Comment by Shreemanarjun** [comment]
Can you share your controller code?

**Comment by ashokavarthanan** [comment]
ya please wait

**Comment by Shreemanarjun** [comment]
rpc.allPlayers.refresh() use this whenever any change within.

**Comment by ashokavarthanan** [comment]
The method 'refresh' isn't defined for the type 'List'.

**Comment by Shreemanarjun** [comment]
Please mention getx and flutter version

**Comment by ashokavarthanan** [comment]
Oh ... Thanks for help!!!
now Works. when Use " **rpc.refresh();**"
But Show alert.
The member 'refresh' can only be used within instance members of subclasses of 'package:get/get_state_manager/src/simple/list_notifier.dart'.

**Comment by Shreemanarjun** [comment]
Please mention getx and flutter vesrion

**Comment by ashokavarthanan** [comment]
[√] Flutter (Channel unknown, 2.5.3, on Microsoft Windows [Version 10.0.19041.329], locale en-IN)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository unknown
    • Framework revision 18116933e7 (5 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\ANDROID_SDK_HOME\Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = C:\ANDROID_SDK_HOME\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components     

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.65.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • SM J710F (mobile) • 5203bac95ee3b37b • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19041.329]      
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 99.0.4844.51

**Comment by ashokavarthanan** [comment]
get: ^4.6.1

**Comment by Shreemanarjun** [comment]
RxList<Player> allPlayers = <Player>[].obs;

**Comment by ashokavarthanan** [comment]
when using `RxList allPlayers = [].obs;` Got error **Model class**
when using `RxList<Player> allPlayers = <Player>[].obs;`
not woring

**Comment by ashokavarthanan** [comment]
Container(
		height: height * .3,
		child: ListView(
		  children: [
			for (int i = 0; i < rpc.allPlayers.length; i++)
			  Obx(
				() => FilterChip(
				  selected: rpc.allPlayers[i].isSelect,
				  label: Text(rpc.allPlayers[i].player,
					  style: const TextStyle(color: Colors.white)),
				  avatar: const FlutterLogo(),
				  elevation: 10,
				  pressElevation: 5,
				  shadowColor: Colors.teal,
				  backgroundColor: Colors.black54,
				  selectedColor: Colors.blue,
				  onSelected: (bool selected) {
					print(selected);
					rpc.allPlayers[i].isSelect = selected;
					// using this works
					rpc.refresh();
				  },
				),
			  ),
		  ],
		),
	  ),

**Comment by Shreemanarjun** [comment]
```dart

class PlayerModel {
  int id;
  String player;
  bool isSelect = false;
  PlayerModel({
    required this.id,
    required this.player,
    required this.isSelect,
  });

  PlayerModel copyWith({
    int? id,
    String? player,
    bool? isSelect,
  }) {
    return PlayerModel(
      id: id ?? this.id,
      player: player ?? this.player,
      isSelect: isSelect ?? this.isSelect,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'player': player,
      'isSelect': isSelect,
    };
  }

  factory PlayerModel.fromMap(Map<String, dynamic> map) {
    return PlayerModel(
      id: map['id']?.toInt() ?? 0,
      player: map['player'] ?? '',
      isSelect: map['isSelect'] ?? false,
    );
  }

  String toJson() => json.encode(toMap());

  factory PlayerModel.fromJson(String source) =>
      PlayerModel.fromMap(json.decode(source));

  @override
  String toString() =>
      'PlayerModel(id: $id, player: $player, isSelect: $isSelect)';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is PlayerModel &&
        other.id == id &&
        other.player == player &&
        other.isSelect == isSelect;
  }

  @override
  int get hashCode => id.hashCode ^ player.hashCode ^ isSelect.hashCode;
}

class RpcController extends GetxController {
  RxList<PlayerModel> allplayers = <PlayerModel>[].obs;
  @override
  void onInit() {
    allplayers.add(PlayerModel(
      id: 1,
      player: 'John',
      isSelect: false,
    ));
    super.onInit();
  }
}

class RpcView extends GetView<RpcController> {
  const RpcView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('RpcView'),
        centerTitle: true,
      ),
      body: SizedBox(
        height: 200,
        child: Obx(() => ListView(
              children: [
                for (var i = 0; i < controller.allplayers.length; i++)
                  FilterChip(
                      label: Text(controller.allplayers[i].player),
                      selected: controller.allplayers[i].isSelect,
                      selectedColor: Colors.blue,
                      onSelected: (bool selected) {
                        controller.allplayers[i].isSelect = selected;
                     ///TODO:Please make sure refresh the list
                        controller.allplayers.refresh();
                      })
              ],
            )),
      ),
    );
  }
}
```

**Comment by Shreemanarjun** [comment]
I think it will fix your problem without warning. If fixed close the issue.

**Comment by ashokavarthanan** [comment]
> I think it will fix your problem without warning. If fixed close the issue.

ya.. its working now without alert. 
Thanks again.
