### ISSUE TITLE
Get Connect error

### ISSUE THREAD

**Issue by CoderAssets** [jonataslaw/getx#2251]
This error was thrown while building the app...
Please I even tried changing get to beta and the problem is the same.
It just happened suddenly.

[flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-5.0.0-beta.50/lib/get_connect/sockets/src/sockets_html.dart:4:8](): Error: Not found: 'dart:html'
import 'dart:html';
       ^
/[C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-5.0.0-beta.50/lib/get_connect/sockets/src/sockets_html.dart:11:3](): Error: Type 'WebSocket' not found.
  WebSocket? socket;
  ^^^^^^^^^
/[C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-5.0.0-beta.50/lib/get_connect/sockets/src/sockets_html.dart:11:3](): Error: 'WebSocket' isn't a type.
  WebSocket? socket;
  ^^^^^^^^^
/[C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-5.0.0-beta.50/lib/get_connect/sockets/src/sockets_html.dart:37:16](): Error: The method 'WebSocket' isn't defined for the class 'BaseWebSocket'.
- 'BaseWebSocket' is from 'package:get/get_connect/sockets/src/sockets_html.dart' ('/[C:/flutter_windows_v1.5.4-hotfix.2-stable/flutter/.pub-cache/hosted/pub.dartlang.org/get-5.0.0-beta.50/lib/get_connect/sockets/src/sockets_html.dart]()').
package:get/…/src/sockets_html.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'WebSocket'.

**Comment by RaphaelArabeyre** [comment]
Can you send me the code ?
As tu bien importer ‘http’ et 'web_socket_channel/web_socket_channel.dart’ ?

**Comment by CoderAssets** [comment]
> Can you send me the code ? As tu bien importer ‘http’ et 'web_socket_channel/web_socket_channel.dart’ ?

code is huge but i didnot have any problem before but now while compiling i get this error.Maybe I dont know how getconnect works but there is simple api calls nothing related to web socket. 
there is screenshot whiel running build
![image](https://user-images.githubusercontent.com/57485183/158771925-94b91585-6eec-4b37-97d3-cf5eed250de7.png)

**Comment by RaphaelArabeyre** [comment]
Have you already make `flutter clean` and `flutter pub get` ?

**Comment by CoderAssets** [comment]
> import 'package:http/http.dart' as http;

i am using get_connect so it is already imported.

**Comment by CoderAssets** [comment]
> So you don't need to import 'dart:html'. Try to remove `import 'dart:html';` form `lib/get_connect/sockets/src/sockets_html.dart`

get connect is a library provided by getx for http requests. I don't think I need to do that. thats where I am getting problem,  with get connect from getx

**Comment by RaphaelArabeyre** [comment]
Ah ok sorry, I through `sockets_html.dart` was your file.

Someone have same probelme [HERE](https://gitanswer.com/build-project-cause-error-dart-html-978674132).
And he fix it whit : " running `flutter clean` in 2-3 times, remove `get: ^4.1.4`, running `pub get`, re-insert `get: ^4.1.4` and finally `flutter run` ".

**Comment by CoderAssets** [comment]
> Ah ok sorry, I through `sockets_html.dart` was your file.
> 
> Someone have same probelme [HERE](https://github.com/jonataslaw/getx/issues/1799#issuecomment-905183675). And he fix it whit : " running `flutter clean` in 2-3 times, remove `get: ^4.1.4`, running `pub get`, re-insert `get: ^4.1.4` and finally `flutter run` ".

I tried but no luck thanks for the info though.

**Comment by CoderAssets** [comment]
Hay, thats me posting the same problem. Maybe the problem is with flutter or something I have no idea.

**Comment by CoderAssets** [comment]
Turns out it was some import problem. Guys be aware even importing websockets and api realted packages!!!
