### ISSUE TITLE
Hero widget can not work

### ISSUE THREAD

**Issue by Liberations** [jonataslaw/getx#2276]
page A has a image wrapr with Hero .
page B has a image wrap with Hero .

Get.to(B());

Hero not effect.

**Comment by Liberations** [comment]
Hero tag must different every widget.

**Comment by yichaosun** [comment]
hi bro, have you solve the problem?

**Comment by hojjat-faryabi** [comment]
Hi. any solution?

**Comment by akashkahalkar** [comment]
Check this out
https://stackoverflow.com/questions/74965038/using-hero-animation-with-getx-flutter

**Comment by fabianogadenz** [comment]
Getx breaks the rescue behavior from the InheritedWidget context where Hero works. I solved it by migrating all my routes to Flutter default Navigator.
