### ISSUE TITLE
When the getx new version releasing 

### ISSUE THREAD

**Issue by pranay289** [jonataslaw/getx#2285]
I am suffering from routing problems in flutter web so I saw that `get: ^[5.0.0-beta.51]` beta  version routing working fine.
and also I have observed some changes one that is the `bindings:` are removed from `GetMaterialApp` can anyone explain me how  can I  achive `DI (Dependency Injection)` things. 
Thank you

**Comment by Interscope19** [comment]
this is not an issue, use the discord channel to stay tunned for the update as u say the beta is a place to test so asking about it is meaningless
