### ISSUE TITLE
The member 'value' can only be used within instance members of subclasses of 'package:get/get_rx/src/rx_types/rx_iterables/rx_list.dart'.

### ISSUE THREAD

**Issue by SittiphanSittisak** [jonataslaw/getx#2302]
Dart Analysis will show 
`The member 'value' can only be used within instance members of subclasses of 'package:get/get_rx/src/rx_types/rx_iterables/rx_list.dart`
 when I am using the ".value" for RxList<int>. 
It will error if I used the RxList(List or Uint8List) without using ".value" in the Image.memory. How to fix the description in the Dart Analysis with still using ".value"?

**Comment by Shreemanarjun** [comment]
Use . toList()

**Comment by SittiphanSittisak** [comment]
Hi, thank you for your answer.
I try to use .toList() and get error "Expect Uint8List but got one of type List<int>".

Then I try to use ` Image.memory(Uint8List.fromList(img), ...`, then it's work. (When img is `RxList<int>`)
For this function, I can use `img` or `img.toList()` instead `img.value`.

PS.
`img.toList()` generate image slower than `img`.
