### ISSUE TITLE
[4.6.1]  cannot run app

### ISSUE THREAD

**Issue by WingCH** [jonataslaw/getx#2311]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
cannot run getx official example in `4.6.1` verion
 
**Reproduction code**

**To Reproduce**
1. clone [getx](https://github.com/jonataslaw/getx) repo
2. check out `origin/4.6.1`branch
3. update getx dependency version to `get: 4.6.1` in `pubspec.yaml` 
4. Run the example, there will be an error
```
../../../.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/routes/route_middleware.dart:199:50: Error: The method 'call' isn't defined for the class 'GetPage<dynamic>?'.
 - 'GetPage' is from 'package:get/get_navigation/src/routes/get_route.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/routes/get_route.dart').
Try correcting the name to the name of an existing method, or defining a method named 'call'.
    final _r = (isUnknown ? unknownRoute : route)()!;
```

**Expected behavior**
can run app normally

**Screenshots**
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/19588517/163506963-8fea2ee7-5f75-406f-af3b-a4faa5704070.png">

**Flutter Version:**
```
 Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-arm, locale zh-Hant-HK)
    • Flutter version 2.10.4 at /Users/wingch/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

```

**Getx Version:**
4.6.1

**Describe on which device you found the bug:**
MacBook Pro

**Minimal reproduce code**

**Comment by debojyoti452** [comment]
- Check your routes middleware array must not be const.
- Update you `analysis_options.yaml` 
-

```yaml
linter:
  rules:
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables
```

**Comment by WingCH** [comment]
thanks for your help
1. The example project doesn't seem to use routes middleware
2. i have tried follow your solution update `analysis_options.yaml` , but seems not work , the problem still here  

Also, I found that version 4.6.0 works fine, only version 4.6.1 has this problem.

**Comment by WingCH** [comment]
The problem does not appear in the latest version should be solved
