### ISSUE TITLE
Where did BindingBuilder go in v5?

### ISSUE THREAD

**Issue by shkvoretz** [jonataslaw/getx#2322]
Quick questions:
Where did BindingBuilder go in v5?
A lot of my stuff uses it 

` 
Get.to<dynamic>(
      () => LocationArchivedViewPage(),
      binding: BindingsBuilder.put(() => LocationEditorController(l)),
    );
`

**Comment by jonataslaw** [comment]
You now have `Binds`, and you can use `Bind.put`, or `Bind.lazyPut`. BindingBuilder is unnecessary in version 5

**Comment by shkvoretz** [comment]
Thanks, Jonny!

**Comment by joseignaciopergolesi** [comment]
@jonataslaw  When is version 5 stable released?
