### ISSUE TITLE
example_nav2 - how to make login page without appbar and drawer

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#2343]
Hi @ahmednfwela ,

May I know what needs to change to make the login page without the appbar and drawer?
Basically, I would like to route to login page (without the rootview content) if not authenticated.

Thanks in advance.

**Comment by ahmednfwela** [comment]
just change it to become a root route (in the same level as /)

**Comment by jasonlaw** [comment]
Thank @ahmednfwela!
Just a note, the drawer needs to move inside the home view, as well as the participatesInRootNavigator flag.
