### ISSUE TITLE
Is it possible to create bottom sheets scoped to current page only?

### ISSUE THREAD

**Issue by suneeltechnew** [jonataslaw/getx#2344]
I am facing issue with bottom sheets.

Assume, we have page-A and page-B.
in page-A I have a bottom sheet which will appear after API call or after some time.

issue is that, if I navigate immediately to page-B from page-A, after API call, the bottom sheet is appearing in page-B but it should appear in page-A only.

Please let use if we have any method to implement this.
Thanks in advance ♥

**Comment by athulnanda123** [comment]
try a Get.back() just before navigation

**Comment by suneeltechnew** [comment]
@athulnanda123 , thanks for the reply.
but my requirement is that, I want to show bottom sheet when user navigates back to the previous page.

**Comment by athulnanda123** [comment]
@suneeltechnew  Ok, try this, Wrap B with a WillpopScope, then inside onwillpop-> 
onWillPop: () async {
Get.back()
controller.launchBottomSheet(); ->code to launch bottomsheet, create a function in the controller which returns a bottom sheet with its values.
}.

**Comment by suneeltechnew** [comment]
@athulnanda123 , it's working as expected. thank you.
