### ISSUE TITLE
Flutter 3 / Downgrade to Flutter 2 problems

### ISSUE THREAD

**Issue by jonataslaw** [jonataslaw/getx#2356]
If you are using the latest version of Flutter (3.0.0) you just need to use the latest version of GetX, and that's ok.
However, in large projects we know that it is not always possible to update on the same day, there are many plugins that still do not support flutter 3. The latest version compatible with Flutter 2 is version 2.6.1.

If you downgraded, or just didn't update, and you're facing compilation errors like:

Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?

You can just use the version constraint (remove ˆ).
Updating `get: ˆ4.6.1` to `get: 4.6.1` in your pubspec, everything will be ok.

**Comment by Gerfaut** [comment]
Why not using the recommended solution here (https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code) to keep it working for both Flutter 2 & 3 and avoid such a breaking change? Any advice against that?

Thanks!

**Comment by arjundevlucid** [comment]
You can use it for a temporary fix before PR https://github.com/jonataslaw/getx/pull/2360
https://github.com/arjundevlucid/getx

**Comment by Abbasi233** [comment]
You saved my life bro thanksss!

**Comment by Gerfaut** [comment]
> You can use it for a temporary fix before PR #2360 https://github.com/arjundevlucid/getx

Didn't see the PR was already ready! Great job!
Thanks 👍

**Comment by jonataslaw** [comment]
This problem have been fixed, please, take a look for the latest version (get 4.6.5)
Thanks @arjundevlucid
