### ISSUE TITLE
Can't assign Rx<Map>.

### ISSUE THREAD

**Issue by SittiphanSittisak** [jonataslaw/getx#2417]
for the example:
```
static Rx<Map<String, String>> ex= <Map<String, String>>{
    '50': "50",
    '100': "100",
    '150': "150",
    '250': "250",
  }.obs;
```
but this work:
```
static RxMap<String, String> ex= <String, String>{
    '50': "50",
    '100': "100",
    '150': "150",
    '250': "250",
  }.obs;
```

I use `Rx<Map>` because it can use like `ex.value` and doesn't warn from dart analysis and work with Obx.

**Comment by N0Noorz** [comment]
in Android studio, you will get this error
![image](https://user-images.githubusercontent.com/21277899/176101025-02b14851-47f2-45d3-844e-bba143a4112f.png)

**Comment by SittiphanSittisak** [comment]
Hi, not long ago. I just gained new knowledge about Rx.
This is a way can assign Rx<Map>.
```
static Rx<Map<String, String>> ex = Rx<Map<String, String>>({
    '50': "50",
    '100': "100",
    '150': "150",
    '250': "250",
  });
```
