### ISSUE TITLE
"You are trying to use contextless navigation without a GetMaterialApp" while using GetMaterialApp

### ISSUE THREAD

**Issue by jose-azevedo** [jonataslaw/getx#2438]
I was using GetX for months without problems when today I started to receive this error everytime I try to start the app, even though I am indeed using `GetMaterialApp`.

![image](https://user-images.githubusercontent.com/66346043/176780358-6725a52c-636c-41ee-983e-0b78409635aa.png)

Here it is my `main` function:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get_storage/get_storage.dart';

import 'app/app.dart';
import 'app/config/dependencies.dart';
import 'app/utils/file_utilities.dart';

void main() async {
  await GetStorage.init();

  await clearCacheDirectory();

  // Here I just instantiate a GetxController class with Get.put
  // This class doesn't try to navigate anywhere when initializing 
  initializeDependencies();

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  runApp(const App());
}

```
And the `App` widget:

```dart
import 'package:elf_boilerplate_app/app/pages/home_page.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'config/app_theme.dart';
import 'config/pages.dart';
import 'controllers/user_controller.dart';
import 'utils/keyboard.dart';

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: hideKeyboard,
      child: GetMaterialApp(
        debugShowCheckedModeBanner: false,
        locale: const Locale('pt', 'BR'),
        title: 'Espresso Labs',
        theme: AppTheme.themeData,
        getPages: pages,
        initialRoute: Get.find<UserController>().initialPage,
        navigatorKey: Get.key, // I tried adding this line to solve the problem but it didn't worked 

        routingCallback: (_) => hideKeyboard(),
      ),
    );
  }
}
```

get: 4.6.5
flutter: 3.0.2
dart: 2.17

**Comment by Sergelenchimeg** [comment]
Is there any solution to handle this error? Share, please.

**Comment by jose-azevedo** [comment]
After hours of debugging I realized the app was indeed trying to navigate before running the `GetMaterialApp` constructor. It happened because I was storing some "faulty" user status on local storage that determined which HomePage the user should be redirected.
I tried to delete this issue since it wasn't a problem with the package, but I didn't found a way to do it so I closed it.

**Comment by fahmidul** [comment]
> After hours of debugging I realized the app was indeed trying to navigate before running the `GetMaterialApp` constructor. It happened because I was storing some "faulty" user status on local storage that determined which HomePage the user should be redirected. I tried to delete this issue since it wasn't a problem with the package, but I didn't found a way to do it so I closed it.
Sorry, I didn't get you. "I tried to delete this issue since it wasn't a problem with the package, but I didn't found a way to do it so I closed it." What does it mean? can you please explain it a little?

**Comment by fahmidul** [comment]
> After hours of debugging I realized the app was indeed trying to navigate before running the `GetMaterialApp` constructor. It happened because I was storing some "faulty" user status on local storage that determined which HomePage the user should be redirected. I tried to delete this issue since it wasn't a problem with the package, but I didn't found a way to do it so I closed it.

Sorry, I didn't get you. "I tried to delete this issue since it wasn't a problem with the package, but I didn't found a way to do it so I closed it." What does it mean? can you please explain it a little?

**Comment by edinsonjohender** [comment]
I had this problem and as Jose mentions, it is due to applying a redirect before the main widget starts, so you can either add a `WidgetsFlutterBinding.ensureInitialized(); `or a `delay` in the function you are executing and ready.
