### ISSUE TITLE
Can't show snackbar (Get.snackbar) on store (GetxController ) init

### ISSUE THREAD

**Issue by Altereyo** [jonataslaw/getx#2443]
When i trying to show snackbar on store init, it throws exceprion

My code:
```
class AppStore extends GetxController {
  AppStore() {
    Get.snackbar('a', 'b');
  }
}
```

Exception:
  _E/flutter ( 6692): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
  E/flutter ( 6692): #0      SnackbarController._configureOverlay (package:get/get_navigation/src/snackbar/snackbar_controller.dart:91:50)
  E/flutter ( 6692): #1      SnackbarController._show (package:get/get_navigation/src/snackbar/snackbar_controller.dart:331:5)
  E/flutter ( 6692): #2      GetQueue._check (package:get/get_utils/src/queue/get_queue.dart:42:47)
  E/flutter ( 6692): #3      GetQueue.add (package:get/get_utils/src/queue/get_queue.dart:29:5)
  E/flutter ( 6692): #4      _SnackBarQueue._addJob (package:get/get_navigation/src/snackbar/snackbar_controller.dart:357:31)
  E/flutter ( 6692): #5      SnackbarController.show (package:get/get_navigation/src/snackbar/snackbar_controller.dart:63:27)
  E/flutter ( 6692): #6      ExtensionSnackbar.snackbar (package:get/get_navigation/src/extension_navigation.dart:465:18)
  E/flutter ( 6692): #7      new AppStore (package:my_app/stores/app_store.dart:20:9)
  E/flutter ( 6692): #8      new App (package:my_app/main.dart:42:28)
  E/flutter ( 6692): #9      main (package:my_app/main.dart:37:10)
  E/flutter ( 6692): <asynchronous suspension>_

**Comment by jonataslaw** [comment]
onReady(){
 Get.snackbar('a', 'b');
}

**Comment by Altereyo** [comment]
Thanks!
