### ISSUE TITLE
Cannot send request through GetConnect's post method

### ISSUE THREAD

**Issue by 0xj0hn** [jonataslaw/getx#2510]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
I sent a data through post method of GetConnect but the server couldn't receive the data.

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**
- Client Sample Code:
![image](https://user-images.githubusercontent.com/50566073/185750587-29dbc313-0a05-4f24-9c0a-60e3c7504042.png)
![image](https://user-images.githubusercontent.com/50566073/185750480-8b2f8ce5-a5b6-48ad-ac0d-29f4ca27eb61.png)
![image](https://user-images.githubusercontent.com/50566073/185750504-08714716-b20c-4efa-a6c4-98e3847fa3f0.png)
- Server Sample Code:
![image](https://user-images.githubusercontent.com/50566073/185750686-f0d7a63f-c7a3-4c2a-bd0f-52a44e3b5401.png)
- Response(client side):
![image](https://user-images.githubusercontent.com/50566073/185750796-15c32bb6-23f2-46aa-9630-03458b3f7d7a.png)

**To Reproduce**

**Expected behavior**
Getting "Our data: test" as a result.

**Flutter Version:**
2.8.0

**Getx Version:**
4.6.5

**Describe on which device you found the bug:**
Linux

**Comment by 0xj0hn** [comment]
I've fixed it using FormData. Why did I see something like this in the document? 
![image](https://user-images.githubusercontent.com/50566073/185751172-e71bf0d1-70f6-4a48-a4d8-bbe2d71e5255.png)

**Comment by saurabhunify** [comment]
I am facing this issue with get 4.6.5 version. But I downgraded to 4.3.1 then it is working fine. The reason why I downgraded to this specific version is that I used it earlier  in an app it used to work fine. Also the Get.changeTheme and Get.changeThemeMode methods not working in this latest(4.6.5) version. But donwgrading worked. 
@jonataslaw please resolve these issue. I love this plugin from the day I first used it but these minor bugs are creating problems in my apps. 
Thanks

**Comment by thiagocarvalhodev** [comment]
Dude, don't use it, please.
