### ISSUE TITLE
Snackbar error: Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by aljibbs** [jonataslaw/getx#2528]
**Describe the bug**
When I call Get.snackbar('title', 'body'), an exception is thrown.

**Error**
SnackbarController._configureOverlay (package:get/get_navigation/src/snackbar/snackbar_controller.dart:91:50)
#1      SnackbarController._show (package:get/get_navigation/src/snackbar/snackbar_controller.dart:331:5)
#2      GetQueue._check (package:get/get_utils/src/queue/get_queue.dart:42:47)
#3      GetQueue.add (package:get/get_utils/src/queue/get_queue.dart:29:5)
#4      _SnackBarQueue._addJob (package:get/get_navigation/src/snackbar/snackbar_controller.dart:357:31)
#5      SnackbarController.show (package:get/get_navigation/src/snackbar/snackbar_controller.dart:63:27)
#6      ExtensionSnackbar.snackbar (package:get/get_navigation/src/extension_navigation.dart:465:18)
#7      _MyHomePageState._incrementCounter (package:get_snackbar_test/main.dart:55:9)
#8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)

**To Reproduce**
1. Create new flutter project
2. Add the Get.snackbar('title', 'body') to the _incrementCounter() method of the default project
3. Click on the FloatingActionButton

**Expected behavior**
A snackbar is supposed to pop up

**Flutter Version:**
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (7 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

**Getx Version:**
^4.6.5

**Describe on which device you found the bug:**
iOS Simulator and Android emulators

**Minimal reproduce code**
```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    Get.snackbar("Test", "message");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

**Comment by jonataslaw** [comment]
You need change MaterialApp to GetMaterialApp

**Comment by aljibbs** [comment]
The solution solves it for this case but when I introduce middleware, the same error is thrown. It was working alright until I updated Flutter.

Below is another Test case.

`
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Get Snackbar Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      unknownRoute: GetPage(name: '/', page: () => const FirstPage()),
      initialRoute: '/',
      getPages: [
        GetPage(
          name: '/',
          page: () => const FirstPage(),
          middlewares: [AuthenticatedMiddleware()],
        ),
        GetPage(
          name: '/second',
          page: () => const SecondPage(),
        ),
      ],
    );
  }
}

class AuthenticatedMiddleware extends GetMiddleware {
  @override
  RouteSettings? redirect(String? route) {
    Get.snackbar("Test", "To second page");
    return null;
  }
}

class FirstPage extends StatefulWidget {
  const FirstPage({Key? key}) : super(key: key);

  @override
  State<FirstPage> createState() => _FirstPageState();
}

class _FirstPageState extends State<FirstPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('First Page'),
      ),
      body: Center(
        child: Text(
          'First page',
          style: Theme.of(context).textTheme.headline4,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Get.snackbar("Test", "message");
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Second"),
      ),
      body: Center(
        child: Text(
          'Second Page',
          style: Theme.of(context).textTheme.headline4,
        ),
      ),
    );
  }
}
`

**Comment by mugikhan** [comment]
I have this same error. @jonataslaw

**Comment by handika231** [comment]
> You need change MaterialApp to GetMaterialApp

I know this problem, when use try to using Snackbar outside GetMaterialApp Widget, you get a null error

**Comment by imprisonedmind** [comment]
In main.dart change MaterialApp → GetMaterialApp
