### ISSUE TITLE
Get.back() and Get.snackbar() not working while using GetMaterialApp

### ISSUE THREAD

**Issue by AgweBryan** [jonataslaw/getx#2553]
**Description of the bug**
When I try to go back to the previous screen after setting the leading property of my AppBar() to an IconButton() with an onTap property set to Get.back(), I get the error "Unhandled Exception: LateInitializationError: Field '_controller@541359576' has not been initialized."

Please refer to the below examples for the details with Screenshots and error description

example:

main.dart
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await DatabaseHelper.initDb();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    Get.put(DatabaseController());
    return GetMaterialApp(
      theme:
          ThemeData.dark().copyWith(scaffoldBackgroundColor: backgroundColor),
      home: NavigationTabs(),
    );
  }
}
```
add_note_screen.dart AppBar
```dart
  _appBar(BuildContext context) {
    return AppBar(
      leading: IconButton(
        onPressed: () => Get.back(),
        icon: Icon(
          Icons.arrow_back_rounded,
          color: textColor,
        ),
      ),
      title: Text(
        "Add new note",
        style: TextStyle(color: textColor),
      ),
      backgroundColor: Colors.transparent,
      elevation: 0,
      actions: [
        IconButton(
          onPressed: () => updateNoteFontSize(),
          icon: Icon(
            Icons.format_size_rounded,
            color: textColor,
          ),
        ),
        IconButton(
          onPressed: () => Get.to(() => AddNewCategory()),
          icon: Icon(
            Icons.create_new_folder_rounded,
            color: textColor,
          ),
        ),
        IconButton(
          onPressed: () => _showBottomSheet(context),
          icon: Icon(
            Icons.more_vert_rounded,
            color: textColor,
          ),
        )
      ],
    );
  }
```

**To Reproduce**
1. Create new flutter project
2. Install get package
3. Wrap app with GetMaterialApp widget
4. Create new screen with an AppBar
5. See examples
6. See error

**Expected behavior**
Get.back() should pop the current screen and go to the previous screen while Get.snackbar() should show a snackbar message

**Screenshots**
Error screenshot
![Screenshot (104)](https://user-images.githubusercontent.com/73445540/192075357-4dd5b550-975a-4b5a-b233-200d757716c2.png)

**Flutter Version:**
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (2 months ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

**Getx Version:**
Using the latest get package. A specific version is not specified in the yaml file

**Describe on which device you found the bug:**
Android Emulator - Pixel_4_API_30:5554

**Comment by AgweBryan** [comment]
It finally worked!. I reinstalled the app and it started working again.

**Comment by micodev** [comment]
@AgweBryan  close the issue please
