### ISSUE TITLE
Two Get.to() does not work with BlocProvider.value

### ISSUE THREAD

**Issue by Artem-Pronenko** [jonataslaw/getx#2556]
Two Get.to() does not work with BlocProvider.value

```dart
// does not work
Get.to(() => BlocProvider.value(
     value: bloc,
     child: Text('1'),
));

// works
Get.to(() => Text('1'));


// works
Navigator.push(context, MaterialPageRoute(builder: (_) => BlocProvider.value(
   value: bloc,
   child: Text('1'),
)));

// works
Get.back();
Get.to(() => BlocProvider.value(
    value: bloc,
    child: EditContact(contact: contact),
));

```

1. Get.toNamed(Routes.name)
2. PageView 
3. Get.to(() => bloc, child: CreateContact()))
4. Get.back()
5. Get.to(() => bloc, child: ViewContact()))
6. [ FAILURE (no error in debug) Get.to(() => bloc, child: EditContact())) ]

**Expected behavior**
Go to the Edit page

**What have I tried**
1. change `Get.to(() => Page())` to Get.to(Page())
2. change `to Get.off(() => Page())`
3. change to `Get.offAll(() => Page())` // That helped. But it doesn't work the way I want.

**Flutter Version:**
Flutter 3.0.0 • channel stable 
Framework • revision ee4e09cce0 (5 months ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

**Getx Version:**
get: ^4.6.5

**Describe on which device you found the bug:**
Pixel 4 API 30.

**Flutter doctor**
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.2006], locale ru-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.71.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by DarkArlekin** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/57257126/192533947-fcd8b9cf-b427-48a9-bdc9-6ebc54430c0e.png">

page.runtimeType returns the BlocProvider, and if prev you a page passing like you current variant, Get router think you duplicate routes, and ignore you request to push the page.

Use routeName param to say getx that this is a new route: 
```
Get.to(
  () => BlocProvider.value(
    value: bloc,
    child: EditContact(contact: contact),
  ),
  routeName: 'editContact',
);
```

if first don`t work as a bad resolve - add (preventDuplicates: false) in args Get.to
