### ISSUE TITLE
How to update dialog

### ISSUE THREAD

**Issue by i2863CookieZJ** [jonataslaw/getx#2558]
when i  click a item  of  listview in dialog,i want to change the state ,i try to update(), but it not works

**Comment by El-Mazouzi** [comment]
you can Wrap your dialog body with StatefulBuilder .

StatefulBuilder provide setState method.

Call it when Item is Clicked.

Example :
StatefulBuilder(
          builder: (context, setState) {
            return DialogBody();
          }),
