### ISSUE TITLE
Exception has occurred. ""AwesomeController" not found. You need to call "Get.put(AwesomeController())" or "Get.lazyPut(()=>AwesomeController())""

### ISSUE THREAD

**Issue by rehman20281** [jonataslaw/getx#2565]
NOTE: Exception has occurred.
```
AwesomeController" not found. You need to call "Get.put(AwesomeController())" or "Get.lazyPut(()=>AwesomeController())
```
example:

```dart

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:getx/controllers/AwesomeController.dart';

class MyApp extends GetView<AwesomeController> {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('${controller.title}')),
    );
  }
}

```
`Can anyone tell me why Getview is not working its showing this error , i have also this contoller`

```dart
import 'package:get/get.dart';

class AwesomeController extends GetxController {
  final String title = 'My Awesome View';
}

```

Help

**Comment by jakobleck** [comment]
Did you heed the Exception message, i.e. do you Get.put or lazyPut an instance of the controller somewhere before using the view?

**Comment by rehman20281** [comment]
> Did you heed the Exception message, i.e. do you Get.put or lazyPut an instance of the controller somewhere before using the view?

No I just you like that example, because i saw that example on getx package on pub.dev

**Comment by kauemurakami** [comment]
Where are your named routes? and the controller binding?

**Comment by vadimlukutin** [comment]
I was also have this issue

`======== Exception caught by widgets library =======================================================
The following message was thrown building AwesomeView(dirty):
"AwesomeController" not found. You need to call "Get.put(AwesomeController())" or "Get.lazyPut(()=>AwesomeController())"`

**Comment by rehman20281** [comment]
Thank you i got this and used

Can you tell me in simple words where we use get.put and where will use lazyput ?


And other question is that when we retrieve data by restapi then which will used for that , lazyput or put?
Kindly tell me. In simple words

**Comment by thearithchhie** [comment]
you should check status in your controller , (this is my error like this )

**Comment by vadimlukutin** [comment]
I was use clear sample from documentation.

**Comment by vadimlukutin** [comment]
`/// Sample:
class AwesomeController extends GetxController {
  final String title = 'My Awesome View';
}

class AwesomeView extends GetView<AwesomeController> {
  /// if you need you can pass the tag for
  /// Get.find<AwesomeController>(tag:"myTag");
  @override
  final String tag = "myTag";

  AwesomeView({Key? key}) : super(key: key){
    Get.put(HomePageController());
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20),
      child: Text(controller.title),
    );
  }
}`

But if add `Get.put(HomePageController());` code working correctly.

**Comment by rehman20281** [comment]
No that i know my question is that 

- When we use lazyPut and when we use only put?
- Where we use putasync?

Just i want to know in which situation we will use **lazyPut** and **put**

**Comment by d-apps** [comment]
> No that i know my question is that
> 
> * When we use lazyPut and when we use only put?
> * Where we use putasync?
> 
> Just i want to know in which situation we will use **lazyPut** and **put**

When you use **Get.put** the class is registered and ready (allocated in the memory) to be be used.

When you use **Get.lazyPut** the class is registered but is not allocated in the memory yet, it will be allocated when retrieved the first time, when you do:

Get.lazyPut(() => SomeController());

**// first time**
final SomeController controller = Get.find();

lazyPut might be useful when you have a heavy class (with a lot of code) and you won't need it right when your app is started for example.
