### ISSUE TITLE
CLOSE TO ROUTE

### ISSUE THREAD

**Issue by muhammednazil** [jonataslaw/getx#2574]
Did anyone have the solution for this?

When i call `Get.toNamed(Routes.CREATE_HEARING_DETAILS);` from one page and its redirecting, but after 10 sec its coming back.

Can anyone can help me?

**Comment by muhammednazil** [comment]
Starts from : 

`Get.toNamed(Routes.CREATE_HEARING_DETAILS);`

View :

```
class CreateHearingView extends GetView<CreateHearingController> {


  String selectedRelatedCase;






  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        elevation: 0,
        leading: BackButton(color: Colors.black,
          onPressed: () => Navigator.of(context).pop()),
        backgroundColor: Colors.white,
        title: Text(
            getTranslated(context, "create_hearing_txt").toString(),
            style: TextStyle(color: Colors.black)),
      ),
      body: Obx((){
        return SingleChildScrollView(
          child: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [

                 Padding(
                      padding: const EdgeInsets.fromLTRB(10, 10, 10, 5),
                      child: DropdownButtonFormField(
                        decoration: InputDecoration(
                          enabledBorder: OutlineInputBorder(
                            borderSide: BorderSide(color: Colors.grey, width:0.5),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderSide: BorderSide(color: Colors.grey, width: 0.5),
                          ),
                        ),
                        value: selectedRelatedCase,
                        items: controller.listRelatedCase.value.map<DropdownMenuItem<dynamic>>((dynamic value) {
                          return DropdownMenuItem<dynamic>(
                            value: value[1],
                            child: Text(
                              value[1],
                            ),
                          );
                        }).toList(),
                      ),
                    ),
}

```

What should i do?

**Comment by muhammednazil** [comment]
After creating the controller one api is calling after the response it get closed why>?

**Comment by muhammednazil** [comment]
<img width="653" alt="Screen Shot 2022-10-16 at 1 45 07 PM" src="https://user-images.githubusercontent.com/39647764/196031020-38a1e68b-f9b3-4f13-a6c2-629af11372e2.png">

**Comment by muhammednazil** [comment]
Again i am stuck on this

**Comment by jonataslaw** [comment]
Please, give me a minimal, reproducible example

**Comment by muhammednazil** [comment]
Here I am calling the page called HEARING DETAILS with an argument "caseId".

`        GestureDetector(

            onTap: () => {

             Get.toNamed(Routes.HEARING_DETAILS, arguments: widget.hearingId)

        }`

Next on the controller of the page Hearing Details, I am calling the API function in onInit()

`  @override
  void onInit() async {
    caseId.value = Get.arguments;
    if(caseId.value != null){
      getHearingDetail(caseId.value);
    }
    super.onInit();
  }`

Next after getting the response it automatically close to the pervious page.

**Comment by zcl947694252** [comment]
I also encountered this problem only when I executed it for the first time. Is there a solution

**Comment by nashihu** [comment]
me too. the client told me that the app is going back automatically

at first it's strage, i thought they accidentally click back from android system button.

but when i intentionally stay in one page, it is really going back automatically after some period of time

here the logs after clearing all logs and stay on the page doing nothing

```

I/flutter ( 9292): GetXLog: CLOSE TO ROUTE /detail
I/flutter ( 9292): ProfileController onClose called
I/flutter ( 9292): GetXLog: "ProfileController" onDelete() called
I/flutter ( 9292): GetXLog: "ProfileController" deleted from memory
I/flutter ( 9292): HomeController onClose called
I/flutter ( 9292): GetXLog: "HomeController" onDelete() called
I/flutter ( 9292): GetXLog: "HomeController" deleted from memory
I/flutter ( 9292): GetXLog: "PageSingleSelectionController" onDelete() called
I/flutter ( 9292): GetXLog: "PageSingleSelectionController" deleted from memory
I/flutter ( 9292): NavigationController onClose called
I/flutter ( 9292): GetXLog: "NavigationController" onDelete() called
I/flutter ( 9292): GetXLog: "NavigationController" deleted from memory
W/WindowOnBackDispatcher( 9292): sendCancelIfRunning: isInProgress=falsecallback=io.flutter.embedding.android.FlutterActivity$1@a8cb437
```

i'm using `get: 4.6.6` and flutter 3.22.0

**Comment by nashihu** [comment]
nvm, turns out i have unhandler timer running on the background
