### ISSUE TITLE
GETX not Updating Image.memory() With with RX<Uint8list> 

### ISSUE THREAD

**Issue by Saleque474** [jonataslaw/getx#2605]
GETX not Updating Image.memory() With with RX<Uint8list> 

Here is the code .

My Controller
```dart
import 'dart:async';
import 'dart:convert';

import 'package:camera/camera.dart';
import 'package:flutter/foundation.dart';
import 'package:get/get.dart';
import 'package:opencv_4/factory/pathfrom.dart';
import 'package:opencv_4/opencv_4.dart';

import 'main.dart';

class ImageScreenController extends GetxController {
  RxString _imgStr =
      "".obs; //utf8.decode(); Image.memory(base64decode(string_value_here))
  RxString get imgStr => _imgStr;
  late CameraController controller;
  late Timer timer;
  Rx<Uint8List> _bytes = Uint8List.fromList([1]).obs;
  Rx<Uint8List> get bytes => _bytes;
  RxInt no = 0.obs;
  @override
  void onInit() {
    controller = CameraController(cameras[0], ResolutionPreset.low);
    controller.initialize().then((_) {
      // update();

      // Timer.periodic(Duration(milliseconds: 10), (timer) async {
      //   await update();
      // });
      updatei();
    }).catchError((Object e) {
      if (e is CameraException) {
        switch (e.code) {
          case 'CameraAccessDenied':
            print('User denied camera access.');
            break;
          default:
            print('Handle other errors.');
            break;
        }
      }
    });
    super.onInit();
    //Change value to name2
  }

  @override
  void onClose() {
    timer.cancel();
    controller.dispose();
    super.onClose();
  }

  updatei() async {
    while (true) {
      no += 1;
      XFile value = await controller.takePicture();
      Uint8List? bytes_ = await Cv2.bilateralFilter(
        pathFrom: CVPathFrom.GALLERY_CAMERA,
        pathString: value.path,
        diameter: 20,
        sigmaColor: 75,
        sigmaSpace: 75,
        borderType: Cv2.BORDER_DEFAULT,
      );
      _bytes = bytes_!.obs;
      update();
    }
  }
}

```
The widget

```dart
import 'dart:async';
import 'dart:typed_data';

import 'dart:convert';
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:opencv_4/factory/pathfrom.dart';
import 'package:opencv_4/opencv_4.dart';

import 'image_controller.dart';
import 'main.dart';

/// CameraApp is the Main Application.
class CameraApp extends StatefulWidget {
  /// Default Constructor
  const CameraApp({Key? key}) : super(key: key);

  @override
  State<CameraApp> createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  String pathOfImg = "";
  Uint8List? byte;
  @override
  void initState() {
    Timer.periodic(Duration(milliseconds: 100), (timer) {
      // if (mounted) setState(() {});
    });
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    ImageScreenController imageScreenController =
        Get.put(ImageScreenController());

    return Scaffold(
      floatingActionButton: FloatingActionButton(onPressed: () {
        imageScreenController.update();
        setState(() {});
      }),
      body: Center(
          child: Obx(() => Image.memory(imageScreenController.bytes.value))),
    );
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // final CameraController? cameraController = controller;

    // // App state changed before we got the chance to initialize.
    // if (cameraController == null || !cameraController.value.isInitialized) {
    //   return;
    // }

    // if (state == AppLifecycleState.inactive) {
    //   cameraController.dispose();
    // } else if (state == AppLifecycleState.resumed) {
    //   // onNewCameraSelected(cameraController.description);
    // }
  }
}

```

When I am running it , it is not updating my Screen Images . GetX should update the bytes variable and show me the new Image. New bytes are generated successfully but getX still do not update image in my screen . If I run setState((){}); then I can see my Image. Why? What is the reason behind this getX not updating . why the variable not updating?

**Screenshots**
![image](https://user-images.githubusercontent.com/56844858/200094060-b7aed998-a6f1-4950-9040-30ba6c37456c.png)
after refresh
![image](https://user-images.githubusercontent.com/56844858/200094087-cef61b26-2156-47ff-8279-38eea25bdbfa.png)

update should work without refresh.

**Flutter Version:**
3.3.4

**Getx Version:**
(get: ^4.6.5)

**Describe on which device you found the bug:**
Android Oreo 7

**Comment by minhdangoz** [comment]
You should check whether imageScreenController.bytes null or not before using.
var bytes = Uint8List(0).obs;

Obx(() =>bytes.isNotEmpty && bytes.length > 0? Image.memory(imageScreenController.bytes.value) : Container() )

**Comment by Saleque474** [comment]
> You should check whether imageScreenController.bytes is null or not before using. var bytes = Uint8List(0).obs;
> 
> Obx(() =>bytes.isNotEmpty && bytes.length > 0? Image.memory(imageScreenController.bytes.value) : Container() )

You just showed me, checking for bytes, It shouldn't be null. But I am not talking about null. I am talking about Obx not changing any state when the bytes is changed with the new value. The screen remains the same all the time.

**Comment by minhdangoz** [comment]
Rx<Uint8List> _bytes = Uint8List.fromList([1]).obs;
which caused image data invalid, when bytes changed you will get widget update dear.
Just do as I recommended and see

**Comment by Saleque474** [comment]
No state update also with your idea.
![image](https://user-images.githubusercontent.com/56844858/200179670-3141045b-ddea-4de1-bcda-bcfcd623a815.png)

**Comment by jonataslaw** [comment]
You are assigning a new Obx to a variable. 
Obx rule number 1: never assign a new obx to a variable. 

Wrong:
_bytes = bytes_!.obs;

Right: 
_bytes.value = bytes_!

**Comment by Saleque474** [comment]
> You are assigning a new Obx to a variable. Obx rule number 1: never assign a new obx to a variable.
> 
> Wrong: _bytes = bytes_!.obs;
> 
> Right: _bytes.value = bytes_!

Thank You. It's working now.
