### ISSUE TITLE
Get.height and Get.width don't update on window resize

### ISSUE THREAD

**Issue by zbejas** [jonataslaw/getx#2614]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
When using `Get.height`, widgets don't refresh when window is resized.

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
Container(
            padding: const EdgeInsets.only(
              top: 0,
              bottom: 0,
              left: 50,
              right: 50,
            ),
            color: Get.theme.cardColor,
            height: Get.height, //MediaQuery.of(context).size.height,
            child: ...
          )
```

**To Reproduce**
Use `Get.height` or `Get.width`in any widget and resize window on desktop.

**Expected behavior**
Widgets rebuild.

Can be fixed using `MediaQuery.of(context).size.height` at the moment.
Tried using this to rebuild the page but Get.height doesn't update.
```dart
  @override
  void onWindowResize() {
    setState(() {});
  }
```

**Screenshots**

**Flutter Version:**
3.0.5

**Getx Version:**
4.6.5

**Describe on which device you found the bug:**
Linux desktop

**Comment by mohamed-amen** [comment]
Did you try this?:

``` Dart
// Equivalent to : MediaQuery.of(context).size.height,
// but immutable.
Get.height
Get.width

// Gives the current context of the Navigator.
Get.context

// Gives the context of the snackbar/dialog/bottomsheet in the foreground, anywhere in your code.
Get.contextOverlay

// Note: the following methods are extensions on context. Since you
// have access to context in any place of your UI, you can use it anywhere in the UI code

// If you need a changeable height/width (like Desktop or browser windows that can be scaled) you will need to use context.
context.width
context.height
```
Look at the last comment
