### ISSUE TITLE
the Get.context is error at run time

### ISSUE THREAD

**Issue by tospery** [jonataslaw/getx#2619]
the reason is _CastError (Null check operator used on a null value
![error](https://user-images.githubusercontent.com/3716286/202380535-f5e2e1d1-f7b9-4e6b-b5d7-58e6963d8151.png)
this is demo: https://github.com/tospery/flutter_demo

**Comment by jonataslaw** [comment]
If the context were null, it would not execute the line below. Using GetMaterialApp the context is never null.

I don't know the lib you are using, but depending on how it executes the code it can give problems with the navigation context.

Try Get.overlayContext

**Comment by tospery** [comment]
> If the context were null, it would not execute the line below. Using GetMaterialApp the context is never null.
> 
> I don't know the lib you are using, but depending on how it executes the code it can give problems with the navigation context.
> 
> Try Get.overlayContext

I have used GetMaterialApp，the code at: https://github.com/tospery/flutter_demo
Can you help me to find the reason? thanks

**Comment by jonataslaw** [comment]
Did you try Get.overlayContext?

**Comment by tospery** [comment]
> Get.overlayContext

use Get.overlayContext is success, thanks your reply.

**Comment by tospery** [comment]
> Did you try Get.overlayContext?

use Get.overlayContext is success, thanks your reply.
