### ISSUE TITLE
allowAutoSignedCert doesn't seem to allow connection with self signed certificates when toggled

### ISSUE THREAD

**Issue by zbejas** [jonataslaw/getx#2658]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
I set the allowAutoSignedCert option to read from a setting in init. Users still report handshake errors despite having the setting enabled. I am not sure if I am implementing this wrong, or if it just doesn't work. I have also asked them to import the certificates to their devices, but that doesn't help.

**Reproduction code**
Code for init, ServerData is connection data, SettingsController gets user settings.
```dart
  void init(ServerData serverData) {
    apiToken.value = serverData.token;
    apiBaseUrl.value = serverData.baseUrl;
    apiEndpoint.value = serverData.endpoint ?? '';
    apiLocalUrl.value = serverData.localUrl ?? '';

    _mainHeaders = {
      'Content-Type': 'application/json',
      'X-API-Key': apiToken.value,
    };

    // Set global timeout
    httpClient.timeout = const Duration(seconds: 15);

    final SettingsController settingsController = Get.find();

    // Allow self-signed certificates
    allowAutoSignedCert = settingsController.allowAutoSignedCerts.value;
  }
```
Also, I use this to toggle from the settings. 
```dart
set updateAutoSignedCert(bool value) => allowAutoSignedCert = value;
```

**To Reproduce**
1. Use allowAutoSignedCert
2. Toggle it on or off
3. Get handshake error both times

**Expected behavior**
Not getting a handshake error when set to true.

**Flutter Version:**
Enter the version of the Flutter you are using: 3.3.8

**Getx Version:**
Enter the version of the Getx you are using: 4.6.5

**Describe on which device you found the bug:**
Android devices

**Minimal reproduce code**
Provide a minimum reproduction code for the problem
```dart
  void init() {
    // Allow self-signed certificates
    allowAutoSignedCert = true; // or false
  }
```
```dart
set updateAutoSignedCert(bool value) => allowAutoSignedCert = value;
```

**Comment by Evgentret** [comment]
Try to move allowAutoSignedCert=true; to constructor

**Comment by zbejas** [comment]
> Try to move allowAutoSignedCert=true; to constructor

I have removed the old methods and added:
```dart
  @override
  bool get allowAutoSignedCert {
    final SettingsController settingsController = Get.find();
    return settingsController.allowAutoSignedCerts.value;
  }
```

And it worked. Thank you so much for your help.
