### ISSUE TITLE
Error: The argument type 'BuildContext?' can't be assigned to the parameter type 'BuildContext' because 'BuildContext?' is nullable and 'BuildContext' isn't.

### ISSUE THREAD

**Issue by sahanpasindu** [jonataslaw/getx#2659]
**Describe the bug**
When I run a newly created Getx project, I get this error. This is just a simple default counter app.

`Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/v3/y_zty5cn46n2bg3tpcf2kyjr0000gn/T/flutter_tools.RmZjKi/flutter_ios_build_temp_dirdafpks/temporary_xcresult_bundle
: Error: The argument type 'BuildContext?' can't be assigned to the parameter type 'BuildContext' because 'BuildContext?' is nullable and 'BuildContext' isn't.
../…/src/extension_navigation.dart:77
- 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../../../DevSDKs/flutter/packages/flutter/lib/src/widgets/framework.dart').
package:flutter/…/widgets/framework.dart:1
        assert(debugCheckHasMaterialLocalizations(context));
                                                  ^
    Failed to package /Users/nirmal/Documents/Developments/Personal/TestingProjects/Flutter/mvvm_api.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    Result bundle written to path:
    	/var/folders/v3/y_zty5cn46n2bg3tpcf2kyjr0000gn/T/flutter_tools.RmZjKi/flutter_ios_build_temp_dirdafpks/temporary_xcresult_bundle`

![SCR-25660111-7a0](https://user-images.githubusercontent.com/26884480/211685358-7f7115a5-5d23-4187-b540-360ec2c582d0.png)

**Reproduction code

```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

**Flutter Version:**
Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm)

**Getx Version:**
^4.6.5

**Describe on which device you found the bug:**
iPhone 14 Pro (iOS 16.1)

**Comment by Evgentret** [comment]
This is not all code for reproduction. All works ok with part of code you provided, so maybe something wrong wit your MyHomePage. Show all code.

**Comment by sahanpasindu** [comment]
> This is not all code for reproduction. All works ok with part of code you provided, so maybe something wrong wit your MyHomePage. Show all code.

My bad. Update the comment.

**Comment by Evgentret** [comment]
Code is fully working. I even create new project and ran it on my env - it similar to yours, except iOS on emulator (mine 16.0), my flutter version is also same as yours. Did you tried this on different emulators or android, for example? Just wondering.

**Comment by sahanpasindu** [comment]
> Code is fully working. I even create new project and ran it on my env - it similar to yours, except iOS on emulator (mine 16.0), my flutter version is also same as yours. Did you tried this on different emulators or android, for example? Just wondering.

I tried, but I'm getting errors there as well. Error is like this.

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
lib/main.dart:1
: Error: The argument type 'BuildContext?' can't be assigned to the parameter type 'BuildContext' because 'BuildContext?' is nullable and 'BuildContext' isn't.
../…/src/extension_navigation.dart:77
- 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../../../DevSDKs/flutter/packages/flutter/lib/src/widgets/framework.dart').
package:flutter/…/widgets/framework.dart:1

    assert(debugCheckHasMaterialLocalizations(context));
                                              ^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/nirmal/Documents/DevSDKs/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/nirmal/Documents/DevSDKs/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by sahanpasindu** [comment]
I found the solution. I ran ```flutter pub cache repair``` command, everything is working fine
