### ISSUE TITLE
ModalBottomSheetRoute error after upgrading to flutter 3.7.0

### ISSUE THREAD

**Issue by ahmadhassan7** [jonataslaw/getx#2684]
I've recently upgraded my flutter version to 3.7.0 and immediately I start to get ModalBottomSheetRoute error in my project which don't even uses [modal_bottom_sheet](https://pub.dev/packages/modal_bottom_sheet) package or any other sort of bottom sheet package. Please note that the project still works perfectly fine upon downgrading to 3.3.10 again but it should be working on 3.7.0. Also, I do have my other projects working on 3.7.0 perfectly fine but none of them are working which uses `GetX`. I've searched `showModalBottomSheet`, `bottom_sheet` and `modal_bottom_sheet` type of keywords in my project but there are 0 results found against them

I tried to clean and rebuilding my `.pub-cache` but no luck. 

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
main.dart:1
: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
material_with_modal_page_route.dart:4
import '../modal_bottom_sheet.dart';

^^^^^^^^^^^^^^^^^^^^^
: Error: Member not found: 'FirebaseAppPlatform.verifyExtends'.
firebase_app.dart:18
    FirebaseAppPlatform.verifyExtends(_delegate);
                        ^^^^^^^^^^^^^
: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
material_bottom_sheet.dart:28
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
: Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
material_bottom_sheet.dart:50

 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;
         ^
: Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
bar_bottom_sheet.dart:102
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
: Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
bar_bottom_sheet.dart:125
 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;
         ^

Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/Users/macm2/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1151

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/macm2/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1
Exited
```

**Flutter Version:**
3.7.0

**Getx Version:**
4.6.5

**Describe on which device you found the bug:**
Pixel 6 emulator and Poco x3 nfc

**Comment by Mapk26** [comment]
You're probably using a lib depending on modal_bottom_sheet,
you can try to import:

modal_bottom_sheet: ^3.0.0-pre

**Comment by ahmadhassan7** [comment]
> You're probably using a lib depending on modal_bottom_sheet, you can try add in your pubspec:
> 
> modal_bottom_sheet: ^3.0.0-pre

Thought so but I didn't found any trace of modal_bottom_sheet from any dependency in the project. I also tried adding it as overriding dependency but that didn't worked too

**Comment by alok2811** [comment]
Are you using country code picker 

> > You're probably using a lib depending on modal_bottom_sheet, you can try add in your pubspec:
> > modal_bottom_sheet: ^3.0.0-pre
> 
> Thought so but I didn't found any trace of modal_bottom_sheet from any dependency in the project. I also tried adding it as overriding dependency but that didn't worked too

if you are using country_code_picker lib in your project change it with country_picker its uses an old version of modal_bottom_sheet and its conflicts by class Name.

**Comment by ahmadhassan7** [comment]
> Are you using country code picker
> 
> > > You're probably using a lib depending on modal_bottom_sheet, you can try add in your pubspec:
> > > modal_bottom_sheet: ^3.0.0-pre
> > 
> > 
> > Thought so but I didn't found any trace of modal_bottom_sheet from any dependency in the project. I also tried adding it as overriding dependency but that didn't worked too
> 
> if you are using country_code_picker lib in your project change it with country_picker its uses an old version of modal_bottom_sheet and its conflicts by class Name.

This resolved the issue

**Comment by devsirius44** [comment]
Thanks @alok2811
