### ISSUE TITLE
get_storage 2.0.3 depends on get ^4.0.0 

### ISSUE THREAD

**Issue by RamSakamuri** [jonataslaw/getx#2699]
Because get_storage 2.0.3 depends on get ^4.0.0 and no versions of get_storage match >2.0.3 <3.0.0, get_storage ^2.0.3 requires get ^4.0.0.
So, because xxxxxx depends on both get_storage ^2.0.3 and get ^5.0.0-release-candidate, version solving failed.

**Comment by ameur-gh-intj** [comment]
I have the same problem @jonataslaw

**Comment by RamSakamuri** [comment]
@ameur-gh-intj  seems below is the work around

  get_storage:
    git:
      url: https://github.com/yutae/get_storage
      ref: master

**Comment by ameur-gh-intj** [comment]
> @ameur-gh-intj  seems below is the work around
> 
>   get_storage:
>     git:
>       url: https://github.com/yutae/get_storage
>       ref: master

thanks man 👌

**Comment by jonataslaw** [comment]
Fixed!
