### ISSUE TITLE
"xxxLogic" not found

### ISSUE THREAD

**Issue by shuwen-hh** [jonataslaw/getx#2703]
I used the get.find<myLogic>() method somewhere, however, sometimes it gets and sometimes it says that this logic cannot be found

**Comment by agostinofiscale** [comment]
I think you should provide more information to help @jonataslaw or whatever can to help you with this

**Comment by shuwen-hh** [comment]
I have two pages, after jumping from the first page to the second page, I refresh the data of the first page by fetching the logic of the first page through the get.find() method, but sometimes it gets and sometimes it doesn't. My first page already called get.put().

**Comment by shuwen-hh** [comment]
[GETX] "DrawMainLogic" deleted from memory
[GETX] "DrawMainLogic" onDelete() called
[GETX] "DrawMainLogic" deleted from memory

I looked at the log and found this, why was this logic deleted.

**Comment by shuwen-hh** [comment]
Get.toNamed(RouteConfig.drawDevice)

I use this to push new pages.
Now I find that it seems that I opened the first page multiple times at the same time, which has a chance of causing the controller of the first page to be created and deleted multiple times and then finally stop in the deleted state.

**Comment by jonataslaw** [comment]
if you push a route to the same page, the controller will be deleted and recreated (since you would have the same screen if it didn't).
I'm glad you solved your problem.
Is there anything else, or can I close this issue?

**Comment by shuwen-hh** [comment]
Okay, thank you
