### ISSUE TITLE
how to use  Get.to() to navigate to the same page

### ISSUE THREAD

**Issue by gkdgo** [jonataslaw/getx#2712]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**
I need to navigate to a same page not only once , they have different content and I wish it can back to the previous pages step by step 

**Describe the solution you'd like**
make Get.to(() =>Page( id: index)) possible to push the same page in router stack , may copy the page?

**Describe alternatives you've considered**
I tried to use Navigator.push it works ,but the next page will cover the previous page's content

**Comment by jonataslaw** [comment]
Try adding: preventDuplicates: false.

**Comment by gkdgo** [comment]
> Try adding: preventDuplicates: false.

thanks it works , but it has the same problem as Navigator.push  'the next page will cover the previous page's content'
