### ISSUE TITLE
Documentation on how to use nested with bottomnarbar in getX

### ISSUE THREAD

**Issue by crazidev** [jonataslaw/getx#2738]
please any clear documentation on how to implement nested navigation using getx without bottomnavbar, and a keepalive feature to preserve nested screens state

**Comment by felix0324324** [comment]
Same question here.🥲
Seems still missing some related bottombar example

**Comment by jackwill99** [comment]
@crazidev @felix0324324 @andim27 

Hay dude here are the useful tips. I also solved this issue by this ways now!

https://github.com/jonataslaw/getx/issues/799

https://github.com/jonataslaw/getx/issues/552#issuecomment-686158966

https://gist.github.com/roipeker/e89e197a2dcd03802a74d214b450ab87

**Comment by crazidev** [comment]
Thanks for this
