### ISSUE TITLE
RxList does not automatically update the interface after changing a member's data

### ISSUE THREAD

**Issue by LoveHeiZhu** [jonataslaw/getx#2743]
My usage scenario ( Gex 4.6.5 ) :
RxList dataList = [{'test':1, 'testData':'str1'}, {'test':2, 'testData':'str2'}].obs;

The dataList is called in view.dart and wrapped with the OBX function.
For example, the interface is not automatically refreshed after changing the value of a member of the dataList in controller.dart.
Example :
dataList[1]['testData']='NewString';
updata();

This didn't work, so I used the following dumb method when I had no other way to do it. :
dataList[1]['testData']='NewString';
dataList.add(dataList[0]);
dataList.removeAt(dataList.length-1);//Cause the interface to refresh by manually changing the number of dataList members
updata();

Is there a better way to do this? If not this would be a bug submission, expect RxList to support automatic interface refresh after member content change, or RxList to add a manual notification function to facilitate users to manually notify Gex framework when changing data of RxList members but not the number of members. rxList.changeData() ?

**Comment by felix0324324** [comment]
dataList

> My usage scenario ( Gex 4.6.5 ) : RxList dataList = [{'test':1, 'testData':'str1'}, {'test':2, 'testData':'str2'}].obs;
> 
> The dataList is called in view.dart and wrapped with the OBX function. For example, the interface is not automatically refreshed after changing the value of a member of the dataList in controller.dart. Example : dataList[1]['testData']='NewString'; updata();
> 
> This didn't work, so I used the following dumb method when I had no other way to do it. : dataList[1]['testData']='NewString'; dataList.add(dataList[0]); dataList.removeAt(dataList.length-1);//Cause the interface to refresh by manually changing the number of dataList members updata();
> 
> Is there a better way to do this? If not this would be a bug submission, expect RxList to support automatic interface refresh after member content change, or RxList to add a manual notification function to facilitate users to manually notify Gex framework when changing data of RxList members but not the number of members. rxList.changeData() ?

dataList.refresh() ?

**Comment by LoveHeiZhu** [comment]
> dataList
> 
> > My usage scenario ( Gex 4.6.5 ) : RxList dataList = [{'test':1, 'testData':'str1'}, {'test':2, 'testData':'str2'}].obs;
> > The dataList is called in view.dart and wrapped with the OBX function. For example, the interface is not automatically refreshed after changing the value of a member of the dataList in controller.dart. Example : dataList[1]['testData']='NewString'; updata();
> > This didn't work, so I used the following dumb method when I had no other way to do it. : dataList[1]['testData']='NewString'; dataList.add(dataList[0]); dataList.removeAt(dataList.length-1);//Cause the interface to refresh by manually changing the number of dataList members updata();
> > Is there a better way to do this? If not this would be a bug submission, expect RxList to support automatic interface refresh after member content change, or RxList to add a manual notification function to facilitate users to manually notify Gex framework when changing data of RxList members but not the number of members. rxList.changeData() ?
> 
> dataList.refresh() ?

Thanks, this is a good solution to my problem
