### ISSUE TITLE
get ^5.0.0-release-candidate-4 will prevent WillPopScope's behavior

### ISSUE THREAD

**Issue by gkdgo** [jonataslaw/getx#2755]
**Describe the bug**
GetMaterialApp in ^5.0.0-release-candidate-4 will prevent WillPopScope's behavior

**Reproduction code

example:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

Future<void> main() async {
  return runApp(const GetMaterialApp(home: MyApp(),));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: WillPopScope(
        onWillPop: () async {
          return false;
          // return !(await homeNavigatorKey.currentState!.maybePop());
        },
        child:Text('data'),
      ),
    );
  }
}

```

**To Reproduce**
1 run main
2 click **device's back button** 
the app will close unexpectedly

**Expected behavior**
WillPopScope should prevent the back action
works rightly in ^4.6.5

**Screenshots**

**Flutter Version:**
3.7.3
**Getx Version:**
^5.0.0-release-candidate-4

**Describe on which device you found the bug:**
Android

btw I spend almost while afternoon to find the bug 😂 😓

**Comment by N0Noorz** [comment]
use BackButtonListener
see: https://github.com/flutter/flutter/pull/79642

**Comment by gkdgo** [comment]
> use BackButtonListener see: [flutter/flutter#79642](https://github.com/flutter/flutter/pull/79642)

Thank u ,it works for me , so this is not a bug right? could you please tell me more?

**Comment by N0Noorz** [comment]
> > use BackButtonListener see: [flutter/flutter#79642](https://github.com/flutter/flutter/pull/79642)
> 
> Thank u ,it works for me , so this is not a bug right? could you please tell me more?

Navigator 2.0 
new Router API

**Comment by gkdgo** [comment]
got it , thanks!

**Comment by Adityapalmzn12** [comment]
I am also facing same issue WillPopScope not working 
get: ^4.6.6
any one help me out this
