### ISSUE TITLE
Unable to mock RxBool field in GetxController using Mockito "_TypeError (type 'Null' is not a subtype of type 'RxBool')"

### ISSUE THREAD

**Issue by lepresk** [jonataslaw/getx#2762]
i'm facing issue to mock GetXController that contains RxBool field, the mock throw `_TypeError (type 'Null' is not a subtype of type 'RxBool')` exception
See the code bellow 

```dart
import 'package:get/get.dart';
import 'package:mockito/mockito.dart';

class TestController extends GetxController {
  RxBool isLoading = false.obs;
}

class MockTestController extends Mock implements TestController {}

void main() {
  group('TestController', () {
    late MockTestController testControllerMock;

    setUp(() {
      testControllerMock = MockTestController();
    });

    test('should show loading indicator', () {
      // Given
      when(testControllerMock.isLoading).thenReturn(true.obs);

      // When
      // ... code to test loading indicator ...

      // Then
      // ... assertion that loading indicator is shown ...
    });
  });
}
```

When I run my test, the exception is throwed at the line `class MockTestController extends Mock implements TestController {}`

I've also tried with `class MockTestController extends GetxController with Mock implements TestController {}` the same error occure

**Flutter Version:**
3.7.8 • channel stable

**Getx Version:**
4.6.5

**Mockito version**
5.4.0

**Comment by Pify** [comment]
have you tried to use @GenerateMocks([TestController]) instead of class MockTestController extends Mock implements TestController {} ?

**Comment by lepresk** [comment]
i'll try, thanks 👍
