### ISSUE TITLE
 return to home page refresh problem

### ISSUE THREAD

**Issue by giantss** [jonataslaw/getx#2776]
scenes： Use the `Get.toNamed()` method from the home page to push to the third page. At this time, use `Get.close(2)` to return to the home page, and the data on the home page needs to be refreshed。

expected ： Return to the home page Refresh the home page data.

May I ask how to achieve the expected effect using getx?

**Comment by abehbatre** [comment]
may you can try this sample 

```dart
  /// Page A
  Future<void> goSomePage() async {
    await Get.toNamed(Routes.USER_DETAIL)?.then((isNeedRefresh) {
        if(isNeedRefresh) {
          // do something here ...
        }
      },
    );
  }

  /// Page B
  void goBack() {
    Get.back(result: true);
  }
```

**Comment by giantss** [comment]
@abehbatre   thanks,
My problem description above may not be clear enough, look at this diagram. 
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/13778798/232945203-e44427c1-80c8-479e-a8fd-076cf6b63558.png">

**Comment by giantss** [comment]
@jasonlaw Can Getx achieve such a refresh?

**Comment by giantss** [comment]
Use `Get.find<MyController>()` can solve
