### ISSUE TITLE
[QUES] Why Get.to(HomePage) adds class name 'HomePage' to the URL?

### ISSUE THREAD

**Issue by hansaliyad1** [jonataslaw/getx#2782]
Hey Community,

Using Get for the first time and I already love it. I'm navigating between screens using Get.to(). I don't use named routes. When I called Get.to(HomePage), it added the "HomePage" class name to the URL. Is it supposed to do that? How can I avoid adding the class name to the URL? As you can see in the image below, I called Get.to("ResponsiveLayout") and it added it to the URL. I would really appreciate any suggestions. Thank you!

![image](https://user-images.githubusercontent.com/9779007/234696044-cea9624c-9e91-4d9b-83c3-71dabdf89461.png)

**Comment by JohnF17** [comment]
Hello, well i believe that is a correct behaviour, if you think about it what should it use when its told to navigate to an unnammed page 🤷‍♂️, it has got to use something 😅(although i do agree, changing it to kebab-case would have been great, _might do a PR for it, we'll see🤔_), anyhow to avoid that "issue" the simplest way is to use named routes, they are simple and give you proper url paths (_if you set them correctly ofcourse_) 🙂, so hear me out (or rather read this out)
Somewhere in your file structure create this file
- app_route_names.dart
```
class AppRouteName{
  static const String introduction = "/";  // this is the initial page route // if you face issues just change this to any path like '/intro'
  static const String home = "/home";
  static const String responsiveLayout = "/responsive-layout";  // kebab-case
}
```
then modify your GetMaterialApp like this 

```
return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: "My App",
      themeMode: ThemeMode.light,
      theme: AppTheme.light,  // Set your theme here or do it like the 'AppRouteName' class and set it there
      darkTheme: AppTheme.dark,
      initialRoute: AppRouteName.introduction ,  // Set your initial page route here // if not set it defaults to using '/'
      getPages: [  // Put all your pages here
        GetPage(
          name: AppRouteName.home,  // Put the AppRouteName here
          page: () => const HomeScreen(),  // Give it the page to navigate to
          binding: HomeScreenBindings(),  // Set your controller bindings you want attached to this page
          transitionDuration: const Duration(milliseconds: 300),  // You can set transition duration times or set custom transitions
        ),
        GetPage(
          name: AppRouteName.introduction ,
          page: () => const IntroductionScreen(),
          transitionDuration: const Duration(milliseconds: 300),
        ),
        GetPage(
          name: AppRouteName.responsiveLayout ,
          page: () => const ResponsiveLayoutScreen(),
          transitionDuration: const Duration(milliseconds: 300),
        ),
      ],
      initialBinding: InitialBindings(),  // Your controller initial bindings when the app first starts up
      translations: LanguageTranslations(),  // Maybe your language translations 
      onInit: () async {}  // An initial callback you might want when the app first launches
 );
```

And when navigating all you have to do is simply call 
```
Get.toNamed(AppRouteName.home);
```
Hope it helps, cheers!👍

**Comment by hansaliyad1** [comment]
Thank you for confirming this. I will close this.
