### ISSUE TITLE
多次进入同一面，controller 怎么使用？（How to use the controller when entering the same page multiple times?）

### ISSUE THREAD

**Issue by helloDolin** [jonataslaw/getx#2787]
如题：getx 默认不允许跳转栈中存在的页面，需要设置 preventDuplicates 参数为 false 才可以，但是 controller 要怎么设置？

**Comment by ahmed-moha** [comment]
can you please write english ?

**Comment by helloDolin** [comment]
> can you please write english ?

ok

For example: getx does not allow jumping pages in the stack by default, you need to set the preventDuplicates parameter to false, but how to set the controller? I use obs and I get an error

**Comment by ahmed-moha** [comment]
yes i have seen that error before i used statefull widget screen instead of waiting controller i used initState with Afterlayout package i hope it helps little

**Comment by JarvisHot** [comment]
override 
String? get tag
`String? get tag => Get.arguments['tag'];
Get.toNamed(Routes.xxx,arguments: {"tag":"your unique tag"});
`

**Comment by good-good-study** [comment]
@helloDolin 
利用GetX框架支持的路由查询参数
https://github.com/jonataslaw/getx/blob/master/documentation/zh_CN/route_management.md#%E5%8A%A8%E6%80%81%E7%BD%91%E9%A1%B5%E9%93%BE%E6%8E%A5

例如：

```
Navigator:
/// 商品详情
void onGoods(Goods goods) {
    Get.toNamed(
      '${AppRoute.goods}?${Keys.id}=${goods.id}',
      preventDuplicates: false,
    );
}

```

```
Controller:
@override
void onInit() {
    id = Get.parameters[Keys.id]!;
    super.onInit();
 }
```

```
Page:
/// 商品详情
class GoodsPage extends StatefulWidget {
  const GoodsPage({Key? key}) : super(key: key);

  @override
  State<GoodsPage> createState() => _GoodsPageState();
}

class _GoodsPageState extends State<GoodsPage> {
  late GoodsController controller;

  @override
  void initState() {
    super.initState();
    var tag = Get.parameters[Keys.id];
    controller = Get.put(GoodsController(), tag: tag);
  }

  @override
  Widget build(BuildContext context) => ContentView(controller: controller);
}
```

**Comment by helloDolin** [comment]
谢谢大家的回复，我这个问题解决方案如下代码：
controller：
`class DetailController extends GetxController {
  RxInt count = 0.obs;

  void add() {
    count.value++;
    update();
  }

  @override
  void onInit() {
    print('DetailController init');
    super.onInit();
  }
}`

Page：
`import 'package:flutter/material.dart';
import 'package:get/get.dart';

import 'detail_controller.dart';

class DetailPage extends StatefulWidget {
  const DetailPage({super.key, this.id = -1});

  final int id;

  @override
  State<DetailPage> createState() => _DetailPageState();
}

class _DetailPageState extends State<DetailPage> {
  late DetailController controller;

  @override
  void initState() {
    super.initState();
    controller = Get.put(DetailController(), tag: widget.id.toString());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('detail'),
      ),
      body: Center(
        child: Column(
          children: [
            Text(widget.id.toString()),
            const SizedBox(
              height: 20,
            ),
            GetBuilder(
              init: controller,
              tag: widget.id.toString(),
              builder: (controller) => Text(controller.count.value.toString()),
            ),
            TextButton(
                onPressed: () {
                  controller.add();
                },
                child: const Text('+'))
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Get.to(
            () => DetailPage(
              id: widget.id + 1,
            ),
            preventDuplicates: false,
          );
        },
        child: const Text('detail'),
      ),
    );
  }
}
`

主要细节是在 get put 时，controller 加上 tag
用 GetBuilder 时，tag 与之对应
然后每个页面产生新的 controller 

控制台打印信息：
push：
[GETX] Instance "DetailController" has been created with tag "1"
[GETX] Instance "DetailController" with tag "1" has been initialized
[GETX] GOING TO ROUTE /DetailPage

[GETX] Instance "DetailController" has been created with tag "2"
[GETX] Instance "DetailController" with tag "2" has been initialized
[GETX] GOING TO ROUTE /DetailPage

[GETX] Instance "DetailController" has been created with tag "3"
[GETX] Instance "DetailController" with tag "3" has been initialized

pop：
[GETX] "DetailController3" onDelete() called
[GETX] "DetailController3" deleted from memory

[GETX] "DetailController2" onDelete() called
[GETX] "DetailController2" deleted from memory

[GETX] "DetailController1" onDelete() called
[GETX] "DetailController1" deleted from memory

**Comment by helloDolin** [comment]
When put controller we should use tag，and use GetBuilder

**Comment by anypwx** [comment]
牛鼻！！！！解决了困扰我一上午的问题， 原来不仅仅ctr要tag  布局里的GetBuild也要加上同样的tag。我说为啥我得ctr实例是不同的，但调用update(ids)，Getbuild不起作用。第一次进入页面是可以的正常的；后面的每一次进入相同的详情页面，对应的Getbuild不生效。 加上tag 就好了。谢谢楼主
