### ISSUE TITLE
Argument are not passed in nestedKey

### ISSUE THREAD

**Issue by mamirix** [jonataslaw/getx#284]
Get.toNamed(myRoute, arguments: myArgs, id: 2);

inspecting Get after executing above statement, the arguments property is null.

removing the :id
Get.toNamed(myRoute, arguments: myArgs);

the argument property is  correctly assigned "myArgs"

**Comment by loicgeek** [comment]
@mamirix yes! It is the expected behavior, i you want to pass multiple values, use a map

**Comment by jonataslaw** [comment]
Are you passing the settings property to the route?
onGenerateRoute is from Flutter, not from Get, if you are using it, you must follow the Flutter script, which is to pass the settings property to the route.

**Comment by Denilson-source** [comment]
check the issue #179 is the same question.

**Comment by jonataslaw** [comment]
> check issue #179 there will be a answer on how to work with params on nested navigator.

@Denilson-source Thanks for linking this, I wasn't finding it.
Related to https://github.com/jonataslaw/getx/issues/179
Closing it.
