### ISSUE TITLE
Get.changeTheme not worink in physical device

### ISSUE THREAD

**Issue by maremaFnx** [jonataslaw/getx#2851]
Hi guys! I'm trying to change theme using Get, so, at a virtual device works as well, but, into a physical device, don't worked as the expected. 
I read some solutions, and the people used "await Get.forceAppUpdate();". But not worked for me.

The code below shows the method who i use to update de colors of app.

```dart
 static Future<void> changeTheme() async {
    try {
      final authService = Get.find<AuthService>();
      final data = await authService.getLoginData();
      final theme = data != null ? createCustomTheme(data) : defaultTheme;
      Get.changeTheme(theme);
      await Get.forceAppUpdate();
    } catch (e) {
      print(e);
    }
  }
```

**Flutter Version:**
3.10.6

**Getx Version:**
4.6.5

**Device:**
Samsung A54 - Android API 32 - **NOT WORKING**
Virtual device - Android API 32 - **WORKING**

**IMPORTANT:**
I'm using "Theme.of(context)" inside the widgets.

**Comment by WMOH-DEV** [comment]
same here 
it works with me on android 8 but 9+ has some issue
