### ISSUE TITLE
GetX Controller in Stack

### ISSUE THREAD

**Issue by aashish7745** [jonataslaw/getx#2853]
I'm using GetX Controller on Screen A and navigating to Screen B which is also the same screen with different data but the same Controller, (its a concept of navigating inside and inside the user's profile in social media app - reference: Instagram)

The issue is when I navigate from Screen A to Screen B, Screen B data is fetched from the API which is totally fine, then when we click the back button it returns back to Screen A, but the Screen A data is replaced with Screen B data

Initialized controller like

```
 final ProfileViewController userProfileController =
      Get.put(ProfileViewController());
```
Navigating to a Screen like

`Get.to(() => ScreenB());`

**Comment by aashish7745** [comment]
any update?

**Comment by asimbilal0001** [comment]
@aashish7745 did tags do the job ?

**Comment by aashish7745** [comment]
@Dabbit-Chan Yes it works. Thanks @asimbilal0001 for the help.
