### ISSUE TITLE
Is getx dead?

### ISSUE THREAD

**Issue by omidFdisk** [jonataslaw/getx#2862]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by jakobleck** [comment]
Duplicate of https://github.com/jonataslaw/getx/issues/2834 ?!

**Comment by astheras** [comment]
pls do not die, i have started to learn bloc. it's just a disaster for me

**Comment by jonataslaw** [comment]
Definitely not!
