### ISSUE TITLE
⚠️⚠️ Nativephp -  Error in ubuntu version

### ISSUE THREAD

**Issue by rehman20281** [jonataslaw/getx#2865]
php artisan native:serve
Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…

> NativePHP@1.0.0 dev /home/ar/Downloads/nativephp.com-main/vendor/nativephp/electron/resources/js
> electron-vite dev --watch

vite v4.4.9 building for development...

watching for file changes...

build started...
✓ 4 modules transformed.
out/main/index.js  0.55 kB
built in 108ms.

build the electron main process successfully

-----

vite v4.4.9 building for development...

watching for file changes...

build started...
"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
✓ 1 modules transformed.
out/preload/index.js  0.70 kB
built in 21ms.

build the electron preload files successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...

```Error: Command failed: /home/ar/Downloads/nativephp.com-main/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config
/home/ar/Downloads/nativephp.com-main/vendor/nativephp/electron/resources/js/resources/php/php: 1: Syntax error: "(" unexpected

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 2,
  killed: false,
  signal: null,
```

How to resolve this error in linux? 
@mpociot

**Comment by XeroDays** [comment]
Whats going on man!
