### ISSUE TITLE
Add method to prevent loading of duplicate route names

### ISSUE THREAD

**Issue by esDotDev** [jonataslaw/getx#289]
It would be nice if there was an option to prevent reloading of the same route name if args have not changed. That way we don't need to always guard at the UI level, we can just rely on the router to be smart enough to ignore non-changes.

Apologies if this already exists.

**Comment by jonataslaw** [comment]
> It would be nice if there was an option to prevent reloading of the same route name if args have not changed. That way we don't need to always guard at the UI level, we can just rely on the router to be smart enough to ignore non-changes.
> 
> Apologies if this already exists.

Hi, I didn't quite understand what you mean, maybe there is already a similar function, but I need to understand directly what this is about.
If you have multiple routes with the same name, only the first one will be inserted in the stack. It doesn't matter if you put 2, or 100, the route is called only when onGenerateRoute is called, and at that point the route is "fabricated".
You can define two routes for the same name, one with arguments and one without (but only two), doing so

GetPage (name: '/page/' [...]
GetPage (name: '/page/:id', page: ()=> OtherPage())

**Comment by esDotDev** [comment]
Just trying to avoid this sorta thing: https://i.imgur.com/M9mMzc5.gifv 

Seems like it might be nice to have an option to just skip the transiton/load if we're on the same page we're requesting.

A web browser typically seems to do this by default. ie, if I'm scrolled down a page and submit the same url, it knows to just put me in the same spot I was previously, it doesn't reload the page fresh (well it does, but it tried it's best to hide it).

I know I could do this by just having each btn check the Get.current and not fire, but thought this might make a nice App/Page level feature?

**Comment by esDotDev** [comment]
You can see this behavior on this page here. If I'm scrolled down on issue /289, and submit, it stays where you are. But I change to 288, and a new route is loaded from scratch.

**Comment by jonataslaw** [comment]
Now I get it.
Well, I think that by default he should have this behavior, because a total blocking of that could bring other side effects, and if the dev wants to stack 60 routes of it, one on top of the other, I must guarantee him that right. It is something that can be a security, but it is also something that can bring more issues.
Even snackbars and dialogs, when they opened an issue about duplicating them, I recommended using a Get.isDialogOpen.
I think that maybe this solution should be applied with Get.currentRoute, it is not so elegant, but maybe that is very specific.
I don't know, do you think this is really necessary?

**Comment by esDotDev** [comment]
I agree with on by default, just thinking it would be nice as a option, cause I think it's a very common use case. Also was just curious if maybe it existed and I was missing it.

At the end of the day, this is really no problem:
```
void handleNavClick(String name)
  {
    if(name == Get.currentRoute) return;
    Get.toNamed(name);
  }
```
But also, this is maybe nice:
`Get.toNamed(name, force: false);`

**Comment by ghprod** [comment]
:+1: from me, since I saw so many apps just load the same page multiple time because some lagging (User click multiple times in slow network)

**Comment by jonataslaw** [comment]
>  from me, since I saw so many apps just load the same page multiple time because some lagging (User click multiple times in slow network)

Really, as navigation is imperative, touching a button twice during a laggy can lead to duplication of pages, thanks for that argument, it really makes me think of creating something that prevents this.

**Comment by jonataslaw** [comment]
Added on 3.0
