### ISSUE TITLE
GetRoot is not part of the three

### ISSUE THREAD

**Issue by han1548772930** [jonataslaw/getx#2901]
get: 
    git: 
      url: 'https://github.com/jonataslaw/getx.git'

![微信截图_20230904103417](https://github.com/jonataslaw/getx/assets/83765419/57923dea-91b5-460e-9213-f4eec33d6544)
![微信截图_20230904103708](https://github.com/jonataslaw/getx/assets/83765419/8a9000b0-4cbb-41fa-bd9f-972998ffee62)

```dart
theme: ThemeData(
              useMaterial3: false,
              colorScheme: lightColorScheme,
              extensions: const <ThemeExtension<dynamic>>[
                ExtBaseColorTheme.light,
                ExtWooColorTheme.light,
              ],
              fontFamily: "Montserrat",
              appBarTheme: const AppBarTheme(
                systemOverlayStyle: SystemUiOverlayStyle.dark,
                backgroundColor: Colors.transparent,
                elevation: 0,
                iconTheme: IconThemeData(
                  color: Color(0xFF5F84FF),
                ),
                titleTextStyle: TextStyle(
                  color: Color(0xFF4D4D4D),
                  fontSize: 24,
                  fontWeight: FontWeight.w600,
                ),
              ),
            )
```
It is normal in version 4.6.5 but using the latest error

**Comment by han1548772930** [comment]
There's something wrong with this.
![微信截图_20230904135119](https://github.com/jonataslaw/getx/assets/83765419/72169a18-8455-4ca3-bb45-73e94491434e)

**Comment by jonataslaw** [comment]
What is your flutter version?
I could not reproduce this error.

Could you please give me a reproduction code, or repair your cache?

**Comment by han1548772930** [comment]
> 你的颤振版本是什么？ 我无法重现这个错误。
> 
> 您能给我一个复制代码，或者修复您的缓存吗？

flutter 3.13.2
