### ISSUE TITLE
Version 5 beta, WillPopScope doesnt work when navigating back with android buttons

### ISSUE THREAD

**Issue by gauravmehta13** [jonataslaw/getx#2903]
**Describe the bug**
WillPopScope is not  working when navigating back with android buttons, works when using navigator.pop context

**Reproduction code**

```dart
 WillPopScope(
          onWillPop: state.onPlaceOrderPopFlow,
          child: Center());
```

**To Reproduce**
1. go back using android navigation gestures or buttons
2. page will be closed and willpopscope doesnt get called
=

**Flutter Version:**
3.13.2

**Getx Version:**
Master github
 get:
    dependency: "direct main"
    description:
      path: "."
      ref: HEAD
      resolved-ref: a8d9f7b2ad27faa9b363cc1788026057eae04381
      url: "https://github.com/jonataslaw/getx.git"
    source: git
    version: "5.0.0-release-candidate-4"

**Comment by jonataslaw** [comment]
I don't think you should use WillPopScope. Try the new Flutter widget BackButtonListener, it might work for your usecase

**Comment by gauravmehta13** [comment]
Works fine thanks, I see this is mentioned [here](https://github.com/jonataslaw/getx/issues/2755) as well.
