### ISSUE TITLE
大神, 请教一个问题, 请看这里。Big Brother, ask a question, please look here

### ISSUE THREAD

**Issue by WangYiOS** [jonataslaw/getx#2907]
大神，你好， 

咨询问题如下：BottomNavigationBar上的Item界面，A界面,B界面, 

点击登录按钮后，使用路由方法 Get.offAllNamed("/routername"); 

跳转到：A界面,B界面,没有重新加载控制器onInit方法， 

如何让A界面,B界面,重新加载控制器onInit方法，（我的需求是：登录前和登录后的界面数据不一样）， 

我翻了3个小时，没找到解决办法，求大神告诉我思路，办法， 

祝你开心快乐每一天！

======================

God, hello,

The consultation questions are as follows: Bottomnavigation Bar Item interface, A interface,B interface,

After clicking the login button, use the route method Get.offAllNamed("/routername").

Switch to: Interface A, interface B, there is no controller reload onInit method,

How to make interface A, interface B, reload controller onInit method, (my needs are: interface data is different before and after login),

I flipped for 3 hours, did not find a solution, asking the great God to tell me the idea, the way,

I wish you happy and happy every day!

**Comment by WangYiOS** [comment]
@ramees-nuhman 

大佬，我按照你的指示，仍然无法加载出控制器的onInit,Get.offAllNamed("/routername")之后无法加载出控制器的onInit，只显示了created，没有initialized。

Boss, I still cannot load the controller's onInit according to your instructions. After Get.offAllNamed("/routername"), the controller's onInit cannot be loaded. Only created is displayed, and initialized is not displayed.


![Snip20230909_9](https://github.com/jonataslaw/getx/assets/17872114/5e0f3ca1-c10a-4d21-9b9c-71d3d35019b8)
![Snip20230909_10](https://github.com/jonataslaw/getx/assets/17872114/18850b32-f706-41ef-8105-50fcae3b2748)
![Snip20230909_11](https://github.com/jonataslaw/getx/assets/17872114/7b4e8ced-a866-408c-8f8d-0bb2212d8988)

**Comment by ramees-nuhman** [comment]
Show oninit code

**Comment by WangYiOS** [comment]
@ramees-nuhman 
谢谢你耐心的帮助 
Thank you for your patient help

下面是我得界面代码，请查看 
Below is my interface code, please check

A 视图 
A view
![078DAC73-5B15-49D9-9183-E13BEACA0F7F](https://github.com/jonataslaw/getx/assets/17872114/70973dc9-a902-4ea1-8e94-638ec6af6959)
![61DC49D2-6726-43F0-8E48-B5FB98776FC5](https://github.com/jonataslaw/getx/assets/17872114/9039426f-9f1b-406b-bb00-cdbe108c6ef1)
![1EABEC12-06AF-464B-8A76-E85CD67948CB](https://github.com/jonataslaw/getx/assets/17872114/d073e7a3-11f4-4ecb-9d66-94ec36e8c602)


B 视图
B view
![E6EF46D3-619E-445F-A289-C015FBB72399](https://github.com/jonataslaw/getx/assets/17872114/44221158-2c75-451f-93eb-71eb1800646e)
![0265B4A0-D9EE-4F2E-8234-389F90C94069](https://github.com/jonataslaw/getx/assets/17872114/431bf864-2d04-4691-96ce-2604e9a05633)
![5409E379-5DF6-4B2B-9FB1-4477F9AAE7B5](https://github.com/jonataslaw/getx/assets/17872114/e120e927-1645-44bb-b801-c2300ca527e6)

A 视图 和 B 视图 的路由绑定
Route binding in view A and view B
![1CDCDFFC-5121-4737-A431-696CE57378BD](https://github.com/jonataslaw/getx/assets/17872114/50d5b858-4ea7-4881-88b0-8d121572032a)

**Comment by ramees-nuhman** [comment]
In oninit method 
Add update(); at last

**Comment by pennyfine** [comment]
把 A,B 页面的 controller 的放到 BottomNavigationBar 所在的页面的构造函数里：
Get.putLazy(controllerA);
Get.putLazy(controllerB);
因为 BottomNavigationBar 跳转的时候不会发生路由跳转，所以不会销毁 controller ，所以也不会重新构造 controller
Tab + PageView 好像也是这种情况

或者用 Get.deleteAll() 手动删除所有 controller

**Comment by WangYiOS** [comment]
@pennyfine 

谢谢大佬的解释，删除控制器，方法试了，会有界面异常，
最后按照大佬你得思想，跳转时，我手动刷新了对应控制器的onInit方法，让界面重新加载，感谢大佬的提示，
谢谢！祝你快乐每一天

**Comment by WangYiOS** [comment]
@ramees-nuhman    

大佬，你好，
我使用 手动刷新控制器的onInit方法，解决了这个场景的问题

Hey, boss,
I solved this scenario using the onInit method of manually refreshing the controller

**Comment by WangYiOS** [comment]
目前我整理的解决方案如下：

@pennyfine   这是我目前的方案，解决了项目登录和退出的界面请求，大佬请过目



问题描述：

在tabbar上 有 A，B,C,D,E 五个界面，登录前和登录后，五个界面的数据，是不一样的，登录状态更改，那么五个界面就需要请求网络，进行数据初始化，

应用在启动的时候，五大控制器，懒加载进行初始化，

使用路由跳转方法：Get.offAllNamed(WYRouteNames.tabbar)

无法做到ABCDE五大界面从新加载控制器的onInit方法，理由是：没有销毁 controller ，所以也不会重新构造 controller的onInit方法

该问题解决方案如下：

A，B,C,D,E，五大控制器增加一个属性，用来控制，重新加载控制器的onInit，

在BottomNavigationBar组件中(原生叫Tabbar)，点击时，进行判断是否需要重新加载该控制器的onInit，代码如下：

![Snip20230911_19](https://github.com/jonataslaw/getx/assets/17872114/dae01b41-b4b1-4766-8c71-30555f7ccb2f)
![Snip20230911_20](https://github.com/jonataslaw/getx/assets/17872114/b74ad24e-d8f9-4581-87a8-f12f2cd80098)
![Snip20230911_21](https://github.com/jonataslaw/getx/assets/17872114/aefa5531-74cb-4bb1-ab94-2bedd30cc6c8)

**Comment by pennyfine** [comment]
写了个简单的Demo试了一下，能考一下


`import 'package:get/get.dart';

class ControllerIndex extends GetxController {
  var selectedIndex = 0.obs;
}

class ControllerA extends GetxController {
  var name = 'controller A';
  @override
  void onInit() {
    print('a init');
    super.onInit();
  }
}

class ControllerB extends GetxController {
  var name = 'controller B';
  @override
  void onInit() {
    print('b init');
    super.onInit();
  }
}`



`import 'package:flutter/material.dart';
import 'package:get/get.dart';
import './controllers.dart';

const List<NavigationDestination> appBarDestinations = [
  NavigationDestination(
    tooltip: '',
    icon: Icon(Icons.widgets_outlined),
    label: 'Components',
    selectedIcon: Icon(Icons.widgets),
  ),
  NavigationDestination(
    tooltip: '',
    icon: Icon(Icons.format_paint_outlined),
    label: 'Color',
    selectedIcon: Icon(Icons.format_paint),
  ),
];

class ExIndex extends GetView<ControllerIndex> {
  ExIndex({super.key}) {
    Get.put(ControllerIndex());
    Get.lazyPut(() => ControllerA());
    Get.lazyPut(() => ControllerB());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(actions: [
          InkWell(
            onTap: () {
              Get.offAll(() => ExIndex());
            },
            child: const Text('restart'),
          )
        ]),
        body: Obx(() {
          if (controller.selectedIndex.value == 0) {
            return const ExPageA();
          } else {
            return const ExPageB();
          }
        }),
        bottomNavigationBar: Obx(() => NavigationBar(
              selectedIndex: controller.selectedIndex.value,
              onDestinationSelected: (index) {
                controller.selectedIndex.value = index;
              },
              destinations: appBarDestinations,
            )));
  }
}

class ExPageA extends GetView<ControllerA> {
  const ExPageA({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text(controller.name),
    );
  }
}

class ExPageB extends GetView<ControllerB> {
  const ExPageB({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text(controller.name),
    );
  }
}
`

**Comment by pennyfine** [comment]
输出结果：
```
[GETX] GOING TO ROUTE /ExIndex
[GETX] REMOVING ROUTE /ExIndex
[GETX] Instance "ControllerIndex" has been created
[GETX] Instance "ControllerIndex" has been initialized
flutter: a init
[GETX] Instance "ControllerA" has been created
[GETX] Instance "ControllerA" has been initialized
[GETX] "ControllerIndex" onDelete() called
[GETX] "ControllerIndex" deleted from memory
[GETX] "ControllerA" onDelete() called
[GETX] "ControllerA" deleted from memory
[GETX] "ControllerB" deleted from memory
flutter: b init
[GETX] Instance "ControllerB" has been created
[GETX] Instance "ControllerB" has been initialized
```

**Comment by WangYiOS** [comment]
@pennyfine   

谢谢你大佬，我今天理解了你的思路，

在tabbar构造函数里，从新加载各个控制器，

现在控制器，都会重新加载了，

非常感谢你，留下个联系方式，

我请你喝一杯冰吸生椰拿铁！！！！

**Comment by pennyfine** [comment]
刚看到，不用客气，我断断续续用flutter 三四年了，有啥解决不了的问题，尽管问吧


| |
penny
|
|
***@***.***
|
签名由网易邮箱大师定制


在2023年09月22日 ***@***.***> 写道：

@pennyfine

谢谢你大佬，我今天理解了你的思路，

在tabbar构造函数里，从新加载各个控制器，

现在控制器，都会重新加载了，

非常感谢你，留下个联系方式，

我请你喝一杯冰吸生椰拿铁！！！！
