### ISSUE TITLE
You need to call Get.put(XXController) or Get.lazyPut(xxController)

### ISSUE THREAD

**Issue by dazeGitHub** [jonataslaw/getx#2924]
卧槽，GetX 真特么沙比，沙比库，我在路由 Binding 类里边都先把 XXController put 进去了, 就为了解决这个沙比问题，结果还找不到 XXController，你特么是沙比吧？？史上最垃圾的库，我特么受不了了，卧槽，大沙比，我不喷我都对不起你，事倍功半，真垃圾

**Comment by LianYangCn** [comment]
This is a meaningless issue and can be closed.

**Comment by liuchuancong** [comment]
使用git仓库可以解决

**Comment by bymoye** [comment]
你确定不是你的使用问题？调试会吗？日志会看吗？ 如果不会那么请不要在这里发表垃圾言论。

**Comment by chirag-chopra** [comment]
I am also facing this issue...

**Comment by itzhu** [comment]
我用的4.6.5版本，确实会有这个问题，在page快速打开或关闭的时候，会出现打开page，controller用的上一次界面打开的controller.然后这个controller会执行onclose方法，接下来后面的界面就会找不到这个controller了。 就是controller的周期和page周期不同，controller延迟的结束，和page复用controller，导致实际界面打开，这个controller已经close的错误。

**Comment by itzhu** [comment]
4.6.5，打开page执行onInit,关闭不会执行onClose。再次打开执行onClose。 这个时候，这个page的子page就找不到这个controller了。升级到4.6.6就好了。

**Comment by Amdian** [comment]
我遇到了一个问题，就是我已经在父视图那里put进去了，但不知道为什么，我本地调试也没有任何错误，控制台也没有任何错误，但是线上就是会出现灰色界面，并不是每次进去都是灰色界面，但是频率非常的高

**Comment by LianYangCn** [comment]
如果使用方法没有问题的话,那么有可能是这个 bug 造成 #2883 
If there are no issues with the usage, then it's possible that this bug is causing #2883.

**Comment by LianYangCn** [comment]
升级到 4.5.6 或这 5.0 RC5 应该可以解决Upgrading to 4.5.6 or 5.0 RC5 should resolve the issue.

**Comment by wd-wd** [comment]
> 4.6.5，打开page执行onInit,关闭不会执行onClose。再次打开执行onClose。 这个时候，这个page的子page就找不到这个controller了。升级到4.6.6就好了。

我升级到4.6.6还是会有这个问题，请问你真的没有这个问题了吗
