### ISSUE TITLE
How Many GetX Controller Can I Initialize?

### ISSUE THREAD

**Issue by davie1989** [jonataslaw/getx#2941]
First of all, thanks for this awesome package. I am currently using it as a state manager for a very large application. Which suggests that this application will use lots of GetX controllers.

This is not an issue really. Just that I have no other way of asking.

I am wondering how many controllers I can safely initialized and or put into memory so my app will still be very performant.

Thanks.

**Comment by mohsinnaqvi0606** [comment]
There is no fixed limit to creating controllers at once. 
Regarding performance, It can be varied over different devices/platforms.
Some devices have low RAM and others have high RAM specs.

In short, there is no fixed limit for controllers

**Comment by inyong1** [comment]
> First of all, thanks for this awesome package. I am currently using it as a state manager for a very large application. Which suggests that this application will use lots of GetX controllers.
> 
> This is not an issue really. Just that I have no other way of asking.
> 
> I am wondering how many controllers I can safely initialized and or put into memory so my app will still be very performant.
> 
> Thanks.

![image](https://github.com/jonataslaw/getx/assets/5109308/a2c6a905-840e-4cc4-91bb-7ff075db661d)
In my app there are 91 controller and still growing

**Comment by davie1989** [comment]
Thanks everyone for the helpful and timely reply. Then I have nothing to worry about regarding how many controllers I can have. Thanks again.
