### ISSUE TITLE
Get.until not work 5.0.0-release-candidate-5

### ISSUE THREAD

**Issue by Adrift001** [jonataslaw/getx#2948]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
void main() => runApp(MaterialApp(home: Home()));

class Home extends StatelessWidget {
  final count = 0.obs;
  @override
  Widget build(context) => Scaffold(
      appBar: AppBar(title: Text("counter")),
      body: Center(
        child: Obx(() => Text("$count")),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => count.value++,
      ));
}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flutter Version:**
Enter the version of the Flutter you are using

**Getx Version:**
Enter the version of the Getx you are using

**Describe on which device you found the bug:**
ex: Moto z2 - Android.

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by ElvistLui** [comment]
Same question. Did you fix it?

**Comment by Adrift001** [comment]
> Same question. Did you fix it?

rollback 4.6.6

**Comment by eddyuan** [comment]
Same issue here, and it's preventing me fron upgrading

**Comment by synstin** [comment]
Same here, which is why I can't use version 5.
@jonataslaw

**Comment by jonataslaw** [comment]
Attaching a reproduction code makes it quicker to fix the problem.

**Comment by jonataslaw** [comment]
Just one question, do you talk about removing `Get.until`?
I believe `Get.offUntil` is what you are looking for.

**Comment by synstin** [comment]
@jonataslaw 
This issue is the same as https://github.com/jonataslaw/getx/issues/3178
After testing it on version 9, it works correctly. 
I believe we can close the issue. 
Thank you.

**Comment by jonataslaw** [comment]
This is fixed now, so, closing this issue
