### ISSUE TITLE
Deleting multiple controllers by a common ancestor

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/getx#295]
You have the delete api

```
      Get.delete<DatabaseService>();
      Get.delete<NotificationService>();
      Get.delete<StorageService>();
```

But I would like to delete them by their common ancestor

`Get.delete<AuthenticatedService>(overrides: true);`

**Comment by jonataslaw** [comment]
Sorry, this feature request doesn't make any sense to me, and it can trigger problems with the controllers' self-disposal. I think that something should only be excluded explicitly, and I don't agree with that approach.

If you want to delete a dependency chain excluding only one, use Get.lazyPut and inject dependencies before the return:

```dart
Get.lazyPut<Controller>((){
  Api api = Api();
  Service service = Service();
  return Controller(api, service);
}
```

Get.delete<Controller>() will delete all dependencies inside of funcion.

Therefore, this feature will not be implemented.
Closing this.
