### ISSUE TITLE
Get or GetX with BottomNavigationBar

### ISSUE THREAD

**Issue by cassianogr** [jonataslaw/getx#296]
Please, 
I'm beginning with Get and my initial problem is to create a BottomNavigationBar. I 'm trying create with Statelwess Widget and using Get for control the indexes. Its happening error when to clock on options.
Is it possible ?
Anyone did it anytime 

```dart
class ProfileScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GetBuilder<ProfileController>(
        init: ProfileController(),
        builder: (s) => IndexedStack(
          index: s.selectedIndex,
          children: <Widget>[
            Body(),
            Body(),
            Body(),
          ],
        ),
      ),
      bottomNavigationBar: SuperFaBottomNavigationBar(),
    );
  }
}

class SuperFaBottomNavigationBar extends StatelessWidget {
  const SuperFaBottomNavigationBar({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetBuilder<ProfileController>(
      init: ProfileController(),
      builder: (s) => BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            title: Text('Inicio'),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.search),
            title: Text('Pesquisa'),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            title: Text('Perfil'),
          ),
        ],
        currentIndex: s.selectedIndex,
        selectedItemColor: Colors.amber[800],
        onTap: (index) => s.onItemTapped(index),
        /* currentIndex: Get.find<ProfileController>().selectedIndex,
        selectedItemColor: Colors.amber[800],
        onTap: Get.find<ProfileController>().onItemTapped, */
      ),
    );
  }
}

class ProfileController extends GetController {

  final _selectedIndex = 0.obs;
  set selectedIndex(value) => this._selectedIndex.value = value;
  get selectedIndex => this._selectedIndex.value;

  onItemTapped(int index) {
    this.selectedIndex(index);
    update();
  }
}
```

**Comment by jonataslaw** [comment]
Hi, you can't put init twice. Why are you putting a GetBuilder in the bottomBar?
You just need to wrap indexedStack in a GetBuilder, and that's it.

**Comment by Denilson-source** [comment]
I guess this do exactly what you want

```dart
class BottomNavigationPageController extends GetxController {
  static BottomNavigationPageController get to => Get.find();

  final currentIndex = 0.obs;

  List<Widget> pages = [
    Tab1(),
    Tab2(),
    Tab3(),
  ];

  Widget get currentPage => pages[currentIndex.value];

  void changePage(int _index) {
    currentIndex.value = _index;
  }
}
```

```dart
class BottomNavigationPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return obx(
      () => Scaffold(
        body: BottomNavigationPageController.to.currentPage,
        bottomNavigationBar: BottomNavigationBar(
          currentIndex: BottomNavigationPageController.to.currentIndex.value,
          onTap: BottomNavigationPageController.to.changePage,
          items: [
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              title: Container(),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              title: Container(),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              title: Container(),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by Kypsis** [comment]
Hijacking this a little, but how would you add transition effects and/or router to BottomNavigationBar?

**Comment by Denilson-source** [comment]
> Hijacking this a little, but how would you add transition effects and/or router to BottomNavigationBar?

you say transition between tabs or each tab having multiple pages? for the second case you can use nested navigation. for transition between tabs on bottomNavibationBar I guess you can't add a transition effect.

**Comment by Kypsis** [comment]
Transition animations between tabs on BottomNavigationBar. Or implementing routing instead of programmatic thisPage[isIndex] type of solution. It's not only transition animations that are missing with BottomNavigationBar, but also Android back button handling. Routing would solve a lot of that. Was wondering if there's an elegant solution to that with Get.

**Comment by Denilson-source** [comment]
I searched a lot and found no way to do tabs navigation as routes. For android back button, which action do you want? if is for trancking the tabs like a stack you can do exactly that, save the index on a stack every time change route, and poping it when press the back button, but i guess this is not a good aproach.

**Comment by jonataslaw** [comment]
You made 2 mistakes when creating your model, one was to try to access a set as if it were a method, and another was to initialize the same controller 2 times. Here is an example of your code working:

```dart
class ProfileScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GetBuilder<ProfileController>(
        init: ProfileController(),
        builder: (s) => IndexedStack(
          index: s.selectedIndex,
          children: <Widget>[
            Center(
              child: Text(s._selectedIndex.string),
            ),
            Center(
              child: Text(s._selectedIndex.string),
            ),
            Center(
              child: Text(s._selectedIndex.string),
            ),
          ],
        ),
      ),
      bottomNavigationBar: SuperFaBottomNavigationBar(),
    );
  }
}

class SuperFaBottomNavigationBar extends StatelessWidget {
  const SuperFaBottomNavigationBar({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetBuilder<ProfileController>( // init only first time
      builder: (s) => BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            title: Text('Inicio'),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.search),
            title: Text('Pesquisa'),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            title: Text('Perfil'),
          ),
        ],
        currentIndex: s.selectedIndex,
        selectedItemColor: Colors.amber[800],
        onTap: (index) => s.onItemTapped(index),
        /* currentIndex: Get.find<ProfileController>().selectedIndex,
        selectedItemColor: Colors.amber[800],
        onTap: Get.find<ProfileController>().onItemTapped, */
      ),
    );
  }
}

class ProfileController extends GetxController {
  final _selectedIndex = 0.obs;
  set selectedIndex(value) => this._selectedIndex.value = value;
  get selectedIndex => this._selectedIndex.value;

  onItemTapped(int index) {
    this.selectedIndex = index; // The set method is accessed this way, you have confused it with methods.
    update();
  }
}

```

**Comment by jonataslaw** [comment]
Well, as it was misuse, and I presented the corrected and compile example, I am closing this. If you encounter a problem with Get, you can open another issue.

**Comment by iampapagray** [comment]
> I guess this do exactly what you want
> 
> ```dart
> class BottomNavigationPageController extends GetxController {
>   static BottomNavigationPageController get to => Get.find();
> 
>   final currentIndex = 0.obs;
> 
>   List<Widget> pages = [
>     Tab1(),
>     Tab2(),
>     Tab3(),
>   ];
> 
>   Widget get currentPage => pages[currentIndex.value];
> 
>   void changePage(int _index) {
>     currentIndex.value = _index;
>   }
> }
> ```
> 
> ```dart
> class BottomNavigationPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return obx(
>       () => Scaffold(
>         body: BottomNavigationPageController.to.currentPage,
>         bottomNavigationBar: BottomNavigationBar(
>           currentIndex: BottomNavigationPageController.to.currentIndex.value,
>           onTap: BottomNavigationPageController.to.changePage,
>           items: [
>             BottomNavigationBarItem(
>               icon: Icon(Icons.home),
>               title: Container(),
>             ),
>             BottomNavigationBarItem(
>               icon: Icon(Icons.home),
>               title: Container(),
>             ),
>             BottomNavigationBarItem(
>               icon: Icon(Icons.home),
>               title: Container(),
>             ),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

I have given this a try as I am a similar dilemma. However, even though the nabber indicates a page change, the new page isn't reflected on the body of the scaffold. Any help?

**Comment by pranavo72bex** [comment]
well, i have one problem -- how can i recreate the controller for  List<Widget> pages = [
    Tab1(),
    Tab2(),
    Tab3(),
  ];

for example, Tab1() controller created initially starting the app , when we click to Tab2() its controller created but Tab1() controller is still alive and cannot update again when I click on Tab1().
 second problem --
and how we can use navigation instead of the List of widgets ?? to update the body of bottomnaviationbar??
