### ISSUE TITLE
Do you have some example on how to use getx internationalization?

### ISSUE THREAD

**Issue by Nipodemos** [jonataslaw/getx#297]
i've noticed that you already have code for translation, but i did not saw any examples.

I'm not very good in understand your source code and apply that, can you give us a little example?

if you have time, can you please explain how to use all those new methods in GetUtils?

**Comment by jonataslaw** [comment]
Localizations:
![translations](https://user-images.githubusercontent.com/35742643/85917701-d2a31480-b832-11ea-97a2-df21eee13693.png)

**Comment by stefandevo** [comment]
I tried the example but it is not updating after pushing the button. Is this a bug or a typo in the sample code @jonataslaw ?

```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      locale: Locale('nl', 'BE'),
      translationsKeys: {
        'nl_BE': {'title': 'Hallo van GetX'},
        'en_US': {'title': 'Hello from GetX'}
      },
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('title'.tr),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('title'.tr),
            RaisedButton(
              child: Text('Switch to English'),
              onPressed: () {
                print('switching to EN');
                Get.updateLocale(Locale('en', 'US'));
              },
            )
          ],
        ),
      ),
    );
  }
}

```

**Comment by ghprod** [comment]
maybe need to call `Get().getController.restartApp();` after `updateLocale` ?

**Comment by jonataslaw** [comment]
Currently Flutter has transformed the home into a constant, making it have a permanent state. You can change the MaterialApp as many times as you like, they put home inside a const, which prevents the update when the parent rebuilds. If you create another class for your text widget, it changes, because the child of home will not be a constant unless you do: child: const TextWidget (). This was introduced at 1.17, lol, and does not happen with named routes. I will force the update of the home when the locale is changed, and update now, with Stefan's PRs for GetUtils.

**Comment by jonataslaw** [comment]
> maybe need to call `Get().getController.restartApp();` after `updateLocale` ?

This in this current update is necessary, but it will not be more, because I will update how things work.

**Comment by Nipodemos** [comment]
closing since i get what i wanted 😄 thank you @jonataslaw

**Comment by Kaival-Patel** [comment]
.tr not working giving the error, any solution>?

**Comment by adnankhan74444** [comment]
Need Help:

import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      locale: Locale('nl', 'BE'), // want to get locally
      translationsKeys: {
        'nl_BE': {'title': 'Hallo van GetX'},
        'en_US': {'title': 'Hello from GetX'}
      },
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('title'.tr),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('title'.tr),
            RaisedButton(
              child: Text('Switch to English'),
              onPressed: () {
                print('switching to EN');
                Get.updateLocale(Locale('en', 'US'));
              },
            )
          ],
        ),
      ),
    );
  }
}

I want to save Local in local storage when ever application killed and back to forground it will get that local which already set before killing the application.

**Comment by Nandan-Wewhare** [comment]
> Need Help:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:get/get.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return GetMaterialApp(
>       locale: Locale('nl', 'BE'), // want to get locally
>       translationsKeys: {
>         'nl_BE': {'title': 'Hallo van GetX'},
>         'en_US': {'title': 'Hello from GetX'}
>       },
>       home: MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('title'.tr),
>       ),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: <Widget>[
>             Text('title'.tr),
>             RaisedButton(
>               child: Text('Switch to English'),
>               onPressed: () {
>                 print('switching to EN');
>                 Get.updateLocale(Locale('en', 'US'));
>               },
>             )
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> I want to save Local in local storage when ever application killed and back to forground it will get that local which already set before killing the application.

any updates on this?
