### ISSUE TITLE
PopScope not working（3.16.0 not fit）

### ISSUE THREAD

**Issue by ersha80** [jonataslaw/getx#2973]
for the new flutter version 3.16.0. The new widget PopScope, which is the instead of WillPopScope.

if call Get.dialog inside the onPopInvoked, will cause assertion error

E/flutter ( 5800): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5238 pos 12: '!_debugLocked': is not true.
E/flutter ( 5800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 5800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 5800): #2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5238:12)
E/flutter ( 5800): #3      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:5204:9)
E/flutter ( 5800): <asynchronous suspension>
E/flutter ( 5800):

**Comment by gustavobrian** [comment]
yes,  please! solutions?

**Comment by jonataslaw** [comment]
You can put the dialog inside a Get.asap((){});
Or Future((){})
Or microtask((){})

Etc, I think is it not a bug or error, is just a description that you are calling something during build

**Comment by Christyansoft** [comment]
the onPopInoked method is called always that pop is tried, so we should prevents that pop was called twice, to fix this use:
```PopScope(
      canPop: false,
      onPopInvoked: (bool didPop) {
        if (didPop) {
          return;
        }
        //DO SOMETHING
      },```

**Comment by faithomotoso** [comment]
Wrap the call after an ensureInitialized like this
``` dart
WidgetsFlutterBinding.ensureInitialized()
            .addPostFrameCallback((timeStamp) {
          Get.dialog(...);
        });
```

**Comment by ridteam168** [comment]
> the onPopInoked method is called always that pop is tried, so we should prevents that pop was called twice, to fix this use:
> 
> ```
>       canPop: false,
>       onPopInvoked: (bool didPop) {
>         if (didPop) {
>           return;
>         }
>         //DO SOMETHING
>       },```
> ```

really saved me, thanks

**Comment by effmuhammad** [comment]
> the onPopInoked method is called always that pop is tried, so we should prevents that pop was called twice, to fix this use:
> 
> ```
>       canPop: false,
>       onPopInvoked: (bool didPop) {
>         if (didPop) {
>           return;
>         }
>         //DO SOMETHING
>       },```
> ```

really saved me, thanks

**Comment by FlawLessx** [comment]
> the onPopInoked method is called always that pop is tried, so we should prevents that pop was called twice, to fix this use:
> 
> ```
>       canPop: false,
>       onPopInvoked: (bool didPop) {
>         if (didPop) {
>           return;
>         }
>         //DO SOMETHING
>       },```
> ```

thanks, never had this problem if using other package

**Comment by shixiwen000** [comment]
CupertinoPageRoute by default prioritizes handling the system back gesture (swipe-to-go-back), which may bypass the logic of WillPopScope or PopScope. (From ChatGPT), so transition of page can't be set to Transition.cupertino.

It's work for me.
