### ISSUE TITLE
Can get.to specify context?

### ISSUE THREAD

**Issue by stoneLee81** [jonataslaw/getx#2999]
My parent page is not full screen, and the child pages opened in the parent page also want to be the same size as the parent page.
when I used Navigator.of(context).push to open, it's ok. Because I used parent's context to open, but when I used get.to to open child page, it's full page. Can get.to specify context so that the child page has the same size as the parent page?

**Comment by chooyan-eng** [comment]
@stoneLee81 
Does this page help you?

https://github.com/jonataslaw/getx/blob/master/documentation/en_US/route_management.md#nested-navigation

It seems you can't specify `context`, but you can do a similar thing with `nestedKey`.
