### ISSUE TITLE
Reactive variable observation issues

### ISSUE THREAD

**Issue by Abhi12Rathore** [jonataslaw/getx#3005]
Let's say I have created some reactive variables and initialised some value to it. Coincidentally if we assign the same value again to it, I am supposed to get an event update in the listen method

var apiErrorMessage="Some Message".obs;

let's say, we get some message from API like "Error, something went wrong" and I have updated the variable and get the update in the listen block

apiErrorMessage.value="Error, something went wrong";

controller.apiErrorMessage.listen{(value)
// updated values
}

But if I hit the API again and get the same response and If I follow the same steps for updating the value with the same message, I do not get any update in the listen block.

**Comment by inyong1** [comment]
```apiErrorMessage.value="Any value";
apiErrrorMessage.refresh();```

to maksure listener called nomater the value changed or not

**Comment by Abhi12Rathore** [comment]
@inyong1 Thanks for sharing the update on the raised concern and again thanks for the Quick response
