### ISSUE TITLE
any suggestions to support deferred for GetMaterialApp?

### ISSUE THREAD

**Issue by stoneLee81** [jonataslaw/getx#3013]
When I want use deferred to reduce the size of compiled main.dart.js for web, I found GetMaterialApp conflicting, these are part code:

import 'package:flutter/material.dart' deferred as material
    show MaterialApp;

I have to use material.MaterialApp because the function 'GetMaterialApp' isn't defined. Are there any methods or suggestions to resolve this conflict?

**Comment by kibugenzaKing** [comment]
GetMaterialApp isn't defined in flutter/ material.dart because it is a different package.
