### ISSUE TITLE
Hot reload deleting the current controller from memory

### ISSUE THREAD

**Issue by bajajsahil** [jonataslaw/getx#302]
**Describe the bug**
While doing the development, we do hot reload a lot of time. But after reloading, the controllers which are used on the current page are getting deleted from memory. Due to this, an exception for null is coming and every time I need to do the complete restart.

I/flutter ( 8237): [GET] onClose of AuthController called
I/flutter ( 8237): [GET] AuthController deleted from memory

E/flutter ( 8237): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception:  AuthController not found. You need call put<AuthController>(AuthController()) before

**To Reproduce**
I am using the GetMaterial APP with Get Routes and Get Bindings.

**Expected behavior**
The current screen controller should not get deleted while doing the hot reload.

**Screenshots**

**Flutter Version:**
1.17.4

**Get Version:**
2.14.1

**Describe on which device you found the bug:**
ex: Pixel 3 API-29, Android Emulator.

**Minimal reproduce code**
class AuthBinding implements Bindings {
  @override
  void dependencies() {
    Get.lazyPut<AuthController>(() => AuthController());
  }
}

**Comment by ghprod** [comment]
Try changing this 

`Get.lazyPut(() => AuthController());`

into

`Get.lazyPut<AuthController>(() => AuthController());`

**Comment by michael-ottink** [comment]
I think this should be in the docs, I know it unerstand it needs to look easy. But spcifying the type like that is usefull in many cases. For instance if you do Get.to<MyType>() you can do Get.untill((route) => route is MyType) which is amazing!

**Comment by bajajsahil** [comment]
> Try changing this
> 
> `Get.lazyPut(() => AuthController());`
> 
> into
> 
> `Get.lazyPut<AuthController>(() => AuthController());`

Hi @ghprod I did this way only. Somehow git is removing the <AuthController>. PFB screenshot.

![image](https://user-images.githubusercontent.com/19187821/85926393-de3b1d80-b8bc-11ea-9681-ed2ca50600cf.png)

**Comment by jonataslaw** [comment]
The controller is only removed with one device.
hot restart is a setState, which has no connection with the exclusion of a controller.
I would guess that the problem lies in something like:
- You are placing the GetMaterialApp inside an InheritedWidget.
- You are using a Tabbar or anything like that that makes pages available in a hot refill if you don't have keepAlive.

**Comment by Nipodemos** [comment]
@bajajsahil when you post code, it is nice to use the code tag
how to use: put three of these \```
in beginning and three in the end
those are not quotes, those are grave accent

How to write:
![image](https://user-images.githubusercontent.com/11494727/85927118-719f2f00-b87a-11ea-9e3f-6ddf28c92d76.png)

how it gets:
```
class AuthBinding implements Bindings {
@override
void dependencies() {
Get.lazyPut<AuthController>(() => AuthController());
}
}
```

if you indent your code it helps get prettier too.
```
class AuthBinding implements Bindings {
  @override
  void dependencies() {
    Get.lazyPut<AuthController>(() => AuthController());
  }
}
```

and lastly, if you put the name of the language you are writing in front of the first three grave accents, you get syntax highlight
How to do:
![image](https://user-images.githubusercontent.com/11494727/85927101-4d435280-b87a-11ea-82c3-6c4a84597b4f.png)


how it gets:
```dart
class AuthBinding implements Bindings {
  @override
  void dependencies() {
    Get.lazyPut<AuthController>(() => AuthController());
  }
}
```

**Comment by bajajsahil** [comment]
Thanks, @Nipodemos, I will take care of that going forward.

@jonataslaw I am using a FormKey in the AuthCard widget and AuthCard widget is included inside AuthScreen(main route widget) for which we have binding defined.

```dart
class AuthCard extends StatelessWidget {
  final GlobalKey<FormState> _formKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
          ..................
  }
}
```

After commenting out the the form key, then controllers are not deleting from the memory. Looks like this is the issue. Do you agree with this?
If this is the issue, shall I move this FormKey in controller class?

**Comment by jonataslaw** [comment]
You can't put GlobalKeys, variables or anything in the view, put it on your Controller and everything should work fine.

**Comment by bajajsahil** [comment]
It worked. Thanks, @jonataslaw

**Comment by bajajsahil** [comment]
Hi @jonataslaw , When I am putting the GlobalKey in the controller, then the controller is not getting deleted from memory. Below is the code snippet of the controller.

```dart
class AuthController extends RxController {
	final GlobalKey<FormState> formKey = GlobalKey();
	..............
	
	void auth() async {
		//auth code
		.................
		
		//Auth successfull. Navigate to home
		Get.offAllNamed(HomeScreen.routeName);
	}
}

Thanks in advance.

**Comment by Nipodemos** [comment]
@bajajsahil since the problem is different, it is recommended for you to create another issue

**Comment by bajajsahil** [comment]
Raised a new defect #316 and closing this one.
