### ISSUE TITLE
Changed default transition in 3.x?

### ISSUE THREAD

**Issue by binaris-no** [jonataslaw/getx#303]
Got a little surprise while moving from 2.14.1 to 3.0.1.
At least when seen on iOS simulator, the typical page sliding transition is now one with fading (for all pages).
Was this change intentional? Is this the new default?

**Comment by jonataslaw** [comment]
Please upgrade to 3.1.0

If you want native updates by default, try setting defaultTransition: Transitions.native in your GetMaterialApp.
Let me know if it works for you.

**Comment by binaris-no** [comment]
Thanks, 3.1.0 returns things to the expected behaviour / as before. Also with 3.1.0 I don't have to set any default transition manually.
