### ISSUE TITLE
Flutter Web App With Getx Don't Work in Some hosting Like Firebase Hosting

### ISSUE THREAD

**Issue by najm-flutter** [jonataslaw/getx#3034]
Hello,

There is an issue that concerns me, which is that the Flutter web application does not work on most hosting platforms. Instead, it only displays a white page. An example of this is Firebase hosting, where the application screen remains white. Here is a link for reference: https://menasa-naspa.web.app/.

However, the application works well on 000webhost hosting. Here is a link demonstrating its functionality: http://almlak.000webhostapp.com/menasa_naspa.

I use  Getx
I would like to know the reason behind this issue.

**Comment by TarishAhmed** [comment]
The website [https://menasa-naspa.web.app/](https://menasa-naspa.web.app/) seems to work fine, consider closing the issue. If its resolved.
