### ISSUE TITLE
get or put

### ISSUE THREAD

**Issue by asarkar1990** [jonataslaw/getx#305]
If there are multiple screens where I need the same controller. How to make sure if I am seeing this screen for the first time or nor?
As per the docs:
```
GetBuilder<Controller>(
  init: Controller(), // INIT IT ONLY THE FIRST TIME
  builder: (_) => Text(
    '${_.counter}',
  ),
)
```
// INIT IF ONLY THE FIRST TIME

How would I know if its first time or not? It would nice if there is something like :

`getOrCreate()`

**Comment by jonataslaw** [comment]
It depends on the architecture of your project. If you don't know how to do this, just use Bindings, and start your controllers there.

**Comment by asarkar1990** [comment]
Suppose I have 
FirstScreen() , SecondScreen(), ThirdScreen()
And in my app, it is possible to navigate to 1 to 2, 1 to 3
and I need a controller in both 2nd and 3rd screen.
How can I achieve this?

**Comment by jonataslaw** [comment]
on FirstScreen:
```dart
GetBuilder<Controller>(
  init: Controller(),
```
It's done.

**Comment by asarkar1990** [comment]
Ok. It's like I need to put it one level upper in the widget tree. 
Would not it be nice if we can query if the controller has an active instance or not?

**Comment by jonataslaw** [comment]
> Ok. It's like I need to put it one level upper in the widget tree.
> Would not it be nice if we can query if the controller has an active instance or not?

https://github.com/jonataslaw/getx#bindings

**Comment by jonataslaw** [comment]
There is some api for this, you can use GetInstance ().IsRegistred<Controller>();

But I do not recommend it, if you need to check if a controller is registered, it is because you are doing something wrong. Use Bindings if you need to know where Controllers are starting.

**Comment by asarkar1990** [comment]
ok. Using Get for first time. We try to understand it better. 
Thank you for this aweseome framework.

**Comment by jonataslaw** [comment]
> ok. Using Get for first time. We try to understand it better.
> Thank you for this aweseome framework.


I understand, Get really has different approaches and in the beginning you will have several questions until you understand how everything works. I will provide links to community communication channels so that answering questions will be easier soon.

**Comment by jonataslaw** [comment]
Well, I believe that this is already resolved.
Closing it.
