### ISSUE TITLE
GetxController dispose is not working

### ISSUE THREAD

**Issue by mazenshawky** [jonataslaw/getx#3051]
**Bug description**
When a class extends GetxController to manage a screen, the issue arises when navigating away from the screen. Despite execution of the onDelete method for the controller, the code added to the dispose method doesn't seem to be executed as expected.

This situation occurs when popping out of the screen, leading to the controller being deleted from memory without executing the intended code within the dispose method override. 

**Reproduction code
```dart
@override
  void dispose() {
    print('I am disposed');
    super.dispose();
  }
```

**To Reproduce**
1. In getPages add ScreenOne and ScreenTwo
2. For ScreenTwo binding use a class that extends Bindings and add this to dependencies function
Get.lazyPut<ScreenTwoController>(() => ScreenTwoController());
3. In ScreenTwoController dispose add a print fuction
4. Navigate from ScreenOne to ScreenTwo and go back, Notice that the print didn't execute even though onDelete is called and the controller is deleted from memory

Note: Trying Getx navigation doesn't fix the problem as well

**Expected behavior**
print 'I am disposed'

**Flutter Version:**
3.19.0

**Getx Version:**
4.6.6

**Comment by jonataslaw** [comment]
This class is not what you are looking for. I believe you are looking for `onClose`. Dispose does nothing.

**Comment by mazenshawky** [comment]
> This class is not what you are looking for. I believe you are looking for `onClose`. Dispose does nothing.

Yes, this solves it, thanks.

**Comment by jonataslaw** [comment]
I'm glad I helped you. I'm closing this issue.
