### ISSUE TITLE
PosScope in IOS while using Getx Route management.

### ISSUE THREAD

**Issue by atish-pun** [jonataslaw/getx#3071]
**Describe the bug**
When using Getx route management, PopScope with the value of canPop set to false works as expected on Android, but doesn't prevent pop on iOS.

**Reproduction code

```dart
void main() => runApp(MaterialApp(home: Home()));

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(context) => Scaffold(
        appBar: AppBar(title: const Text("Home")),
        body: Center(
          child: ElevatedButton(
              onPressed: () => Get.to(() => const PageOne()),
              child: const Text("Navigate to another page")),
        ),
      );
}

class PageOne extends StatelessWidget {
  const PageOne({super.key});

  @override
  Widget build(context) => PopScope(
        canPop: false,
        onPopInvoked: (didPop) => print("didPop"),
        child: Scaffold(
          appBar: AppBar(title: const Text("Page One")),
          body: const Center(
            child: Text("Page One"),
          ),
        ),
      );
}
```

**To Reproduce**
1. Go to the 'Home page'.
2. Click on 'Navigate to another page'
3. Use swipe back gesture in IOS
4. see error

**Expected behavior**
When canPop of PopScope is set to false and used swipe back gesture in IOS, the page should not get popped to the previous page.

**Flutter Version:**
3.19.0

**Getx Version:**
4.6.6

**Describe on which device you found the bug:**
IOS devices.

**Comment by atish-pun** [comment]
@ttb-inc Getx route has the option of popGesture so you can simply make it false for IOS to avoid popping back to the previous page. But, onPopInvoked will not be called in iOS if canPop and popGesture are false as it's one of the issues of flutter.

**Comment by ttb-inc** [comment]
> @ttb-inc Getx route has the option of popGesture so you can simply make it false for IOS to avoid popping back to the previous page. But, onPopInvoked will not be called in iOS if canPop and popGesture are false as it's one of the issues of flutter.

Thank you for your help.
Let's check the package.
Thanks a lot.

**Comment by ttb-inc** [comment]
I checked.
The popGesture arguments in GetPage(...) and Get.to(...) don't work.
Also, Get.toNamed(...) doesn't have a popGesture argument.

I'm using get: ^4.6.6.

Thanks.

**Comment by atish-pun** [comment]
@ttb-inc Hello, you have to set both keys i.e. canPop and popGesture of PopScope and GetPage respectively to false. This should solve the issue for iOS in the case of Getx. You can simply put the popGesture false for which the navigation is done. For eg-> Get.to(popGesture:false, ()=>yourPage()). 

For Get.toNamed(...), you have to set popGesture value inside GetPage of routes where you have registered all the named routes. For eg-> 
<img width="721" alt="Screen Shot 2024-04-13 at 9 32 13 AM" src="https://github.com/jonataslaw/getx/assets/75410315/b9302548-d2e5-4d0b-9f00-b6349f0f936a">

**Comment by ttb-inc** [comment]
> @ttb-inc Hello, you have to set both keys i.e. canPop and popGesture of PopScope and GetPage respectively to false. This should solve the issue for iOS in the case of Getx. You can simply put the popGesture false for which the navigation is done. For eg-> Get.to(popGesture:false, ()=>yourPage()).
> 
> For Get.toNamed(...), you have to set popGesture value inside GetPage of routes where you have registered all the named routes. For eg-> <img alt="Screen Shot 2024-04-13 at 9 32 13 AM" width="721" src="https://private-user-images.githubusercontent.com/75410315/322173179-b9302548-d2e5-4d0b-9f00-b6349f0f936a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTc1MjEsIm5iZiI6MTcxMzAxNzIyMSwicGF0aCI6Ii83NTQxMDMxNS8zMjIxNzMxNzktYjkzMDI1NDgtZDJlNS00ZDBiLTlmMDAtYjYzNDlmMGY5MzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE0MDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYWQ2MmFjZTYxN2U0MTcxOTcwZDUzY2JkZTJkMDI2MDkxODI3MzllYTFlNmI3ZGU5MzM4NDVmYTliMjcwMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vqaH2XpSWXqTzRo7HrAGT9LBtqQZJ1eMfXIRdZQ49F8">

Hi,
Thank you so much for your response.
It's working fine.

I was using Transition in GetPage(...) and Go.to(...).
This is why it didn't work.
If I don't use Transition, it works fine.

Your answer helped me a lot.
Thank you very much.

**Comment by 86linksrain** [comment]
I set   popGesture: false both GetMaterialApp() and GetPage(),but it not work....I don't know why.....
<img width="350" alt="image" src="https://github.com/jonataslaw/getx/assets/62991463/4ca68593-8c3f-4091-91a9-4a5f3e75db14">
<img width="592" alt="image" src="https://github.com/jonataslaw/getx/assets/62991463/950cf654-44ea-4858-b3c9-a2091c2098ff">

**Comment by wxd79** [comment]
> I set popGesture: false both GetMaterialApp() and GetPage(),but it not work....I don't know why..... <img alt="image" width="350" src="https://private-user-images.githubusercontent.com/62991463/339966181-4ca68593-8c3f-4091-91a9-4a5f3e75db14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTI2OTUsIm5iZiI6MTcyNjE5MjM5NSwicGF0aCI6Ii82Mjk5MTQ2My8zMzk5NjYxODEtNGNhNjg1OTMtOGMzZi00MDkxLTkxYTktNGE1ZjNlNzVkYjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAxNTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMTNkNDM0MWZhYjgwYjgxOWQzYjdkNDU4ZDA2OGQzYWVkMTNjYTJlY2FmZTYxMWIyOGNkZmExODBiODI3ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-U_RTGl7MBMiWDAz6GRWAoQzoQMIkwjMZKriwLBawyA"> <img alt="image" width="592" src="https://private-user-images.githubusercontent.com/62991463/339966250-950cf654-44ea-4858-b3c9-a2091c2098ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTI2OTUsIm5iZiI6MTcyNjE5MjM5NSwicGF0aCI6Ii82Mjk5MTQ2My8zMzk5NjYyNTAtOTUwY2Y2NTQtNDRlYS00ODU4LWIzYzktYTIwOTFjMjA5OGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAxNTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNDA3ODkzYWZmOWUyNWViNzBkZWM5NDEzOTllYjg4YjE5MDhiMjVlNDc1ZjBhZmExYzdjMmQ0OTJjYWNiZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5TaR9shWVwrnLf2sxzwEAM_WuZiKgDufO-R549CHZ8A">

Me too.

Is anyone has the solution?
