### ISSUE TITLE
What purpose of using extension on Object? 

### ISSUE THREAD

**Issue by SHRJamal** [jonataslaw/getx#308]
I checked code and found that you have an extension on object 
`extension ObjectExtension on Object {
  Rx<Object> get obs => Rx(this);
}`

I suggest to make it as generic, it makes more sense:
`extension RxT<T> on T {
  Rx<T> get obs => Rx(this);
}`

**Comment by jonataslaw** [comment]
> I checked code and found that you have an extension on object
> `extension ObjectExtension on Object { Rx<Object> get obs => Rx(this); }`
> 
> I suggest to make it as generic, it makes more sense:
> `extension RxT<T> on T { Rx<T> get obs => Rx(this); }`

I think there is no semantic difference between the two approaches.
Do you think it gets clearer with <T>?

**Comment by SHRJamal** [comment]
when you .obs on non-primitive types, you lose the type.
when you do user.obs you get Rx<Object>, It should be Rx<User> instead.
With the solution, I gave it will solve this.

**Comment by SHRJamal** [comment]
I also have some other suggestions on code cleaning and recommend to add effective-dart lint rules. so that we have common rules for future contributions.
I can make pull request if you want. I like this packages and would love to contribute.

**Comment by jonataslaw** [comment]
![Screen Capture_select-area_20200628153031](https://user-images.githubusercontent.com/35742643/85955358-6a4c5400-b954-11ea-8a72-329fdb323975.png)
![Screen Capture_select-area_20200628153057](https://user-images.githubusercontent.com/35742643/85955361-7506e900-b954-11ea-92cd-b1413f04e8ec.png)

I was unable to reproduce this, but either way, I will consider it for the next update.

**Comment by SHRJamal** [comment]
<img width="380" alt="Screen Shot 2020-06-28 at 19 37 38" src="https://user-images.githubusercontent.com/31532251/85955570-52d29280-b977-11ea-88e8-5ec9cb247347.png">

Here it' s really doesn't, just think about it. that should not be allowed by dart anyway

**Comment by jonataslaw** [comment]
Dart behaving differently on different machines, lol.
Thank you for mentioning this, as it never happened on my side, it was never my concern, I am changing this and I will update it.

**Comment by Nipodemos** [comment]
don't know if it helps, but i am using Flutter 1.17.4 (stable channel) and it happens just like @SHRJamal showed.

![image](https://user-images.githubusercontent.com/11494727/85970467-f5533b80-b9a0-11ea-8af6-fd24edefb4d6.png)

**Comment by jonataslaw** [comment]
Changed on last version, thanks.
