### ISSUE TITLE
无法访问pub.dev

### ISSUE THREAD

**Issue by lengmianshi** [jonataslaw/getx#3083]
执行`get init` 报错：
 ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get

想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn

**Comment by whevether** [comment]
> 执行`get init` 报错： ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get
> 
> 想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn

你这个技术还是告别编程吧。 梯子不会? issues 里面问中文? 人家作者是国外的，又不是为你一个人服务, 为什么不去学学英文

**Comment by lengmianshi** [comment]
> > 执行`get init` 报错： ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get
> > 想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn
> 
> 你这个技术还是告别编程吧。 梯子不会? issues 里面问中文? 人家作者是国外的，又不是为你一个人服务, 为什么不去学学英文

你动动脑子好吗？没梯子我能上github？梯子能解决我也不会来发问了。我知道使用移动网络可以有访问pub.dev，我不想这么麻烦。再者，像pip、yum、apt-get之类的工具都可以灵活配置镜像源，get作者把源链接写死了，你觉得很合理？

用中文发问怎么了？又不是没有翻译软件？如果get作者是俄国人，你是不是也去学个俄语？

**Comment by whevether** [comment]
> > > 执行`get init` 报错： ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get
> > > 想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn
> > 
> > 
> > 你这个技术还是告别编程吧。 梯子不会? issues 里面问中文? 人家作者是国外的，又不是为你一个人服务, 为什么不去学学英文
> 
> 你动动脑子好吗？没梯子我能上github？梯子能解决我也不会来发问了。我知道使用移动网络可以有访问pub.dev，我不想这么麻烦。再者，像pip、yum、apt-get之类的工具都可以灵活配置镜像源，get作者把源链接写死了，你觉得很合理？
> 
> 用中文发问怎么了？又不是没有翻译软件？如果get作者是俄国人，你是不是也去学个俄语？

感情你就是大爷。都得迁就你。你是想让人家作者去学中文。   你可真行。 既然这么屌。那你代码也用中文呀。 这么多国内的都可以就你不行。菜比还不让说了是吗?

**Comment by lengmianshi** [comment]
> > > > 执行`get init` 报错： ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get
> > > > 想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn
> > > 
> > > 
> > > 你这个技术还是告别编程吧。 梯子不会? issues 里面问中文? 人家作者是国外的，又不是为你一个人服务, 为什么不去学学英文
> > 
> > 
> > 你动动脑子好吗？没梯子我能上github？梯子能解决我也不会来发问了。我知道使用移动网络可以有访问pub.dev，我不想这么麻烦。再者，像pip、yum、apt-get之类的工具都可以灵活配置镜像源，get作者把源链接写死了，你觉得很合理？
> > 用中文发问怎么了？又不是没有翻译软件？如果get作者是俄国人，你是不是也去学个俄语？
> 
> 感情你就是大爷。都得迁就你。你是想让人家作者去学中文。 你可真行。 既然这么屌。那你代码也用中文呀。 这么多国内的都可以就你不行。菜比还不让说了是吗?

你用中文提问很自卑吗？

**Comment by whevether** [comment]
> > > > > 执行`get init` 报错： ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get
> > > > > 想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn
> > > > 
> > > > 
> > > > 你这个技术还是告别编程吧。 梯子不会? issues 里面问中文? 人家作者是国外的，又不是为你一个人服务, 为什么不去学学英文
> > > 
> > > 
> > > 你动动脑子好吗？没梯子我能上github？梯子能解决我也不会来发问了。我知道使用移动网络可以有访问pub.dev，我不想这么麻烦。再者，像pip、yum、apt-get之类的工具都可以灵活配置镜像源，get作者把源链接写死了，你觉得很合理？
> > > 用中文发问怎么了？又不是没有翻译软件？如果get作者是俄国人，你是不是也去学个俄语？
> > 
> > 
> > 感情你就是大爷。都得迁就你。你是想让人家作者去学中文。 你可真行。 既然这么屌。那你代码也用中文呀。 这么多国内的都可以就你不行。菜比还不让说了是吗?
> 
> 你用中文提问很自卑吗？
第一：github 是全球平台的代码平台，不是你一个人玩的。
第二:  人家作者是外国人。为了你一个菜的抠脚的菜比去学中文?  你自己时间没关系，耽误人家时间也没关系吗,
第三： 看你提问的水平看出你代码水平也就停留在百度了。听话还是乖乖去面向百度编程吧。别出来丢人了.
你倒是又菜又蠢。既然这么菜你去玩百度呀。那上面全是中文。

**Comment by lengmianshi** [comment]
> > > > > > 执行`get init` 报错： ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get
> > > > > > 想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn
> > > > > 
> > > > > 
> > > > > 你这个技术还是告别编程吧。 梯子不会? issues 里面问中文? 人家作者是国外的，又不是为你一个人服务, 为什么不去学学英文
> > > > 
> > > > 
> > > > 你动动脑子好吗？没梯子我能上github？梯子能解决我也不会来发问了。我知道使用移动网络可以有访问pub.dev，我不想这么麻烦。再者，像pip、yum、apt-get之类的工具都可以灵活配置镜像源，get作者把源链接写死了，你觉得很合理？
> > > > 用中文发问怎么了？又不是没有翻译软件？如果get作者是俄国人，你是不是也去学个俄语？
> > > 
> > > 
> > > 感情你就是大爷。都得迁就你。你是想让人家作者去学中文。 你可真行。 既然这么屌。那你代码也用中文呀。 这么多国内的都可以就你不行。菜比还不让说了是吗?
> > 
> > 
> > 你用中文提问很自卑吗？
> > 第一：github 是全球平台的代码平台，不是你一个人玩的。
> > 第二:  人家作者是外国人。为了你一个菜的抠脚的菜比去学中文?  你自己时间没关系，耽误人家时间也没关系吗,
> > 第三： 看你提问的水平看出你代码水平也就停留在百度了。听话还是乖乖去面向百度编程吧。别出来丢人了.
> > 你倒是又菜又蠢。既然这么菜你去玩百度呀。那上面全是中文。

智商感人，你以为我不认识英文，我提的问题，哪块英文有提解决方案？
外国人是你爹吗，要这么孝着，人家翻译下怎么了？
还有，我是来提问，顺带给个优化建议的，你却说要让人家来迁就我，真是大孝子，什么都为你爹着想……
算了，不想和你废话，别回复了

**Comment by tiedgourdes** [comment]
> 执行`get init` 报错： ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get
> 
> 想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn

笑死我他吗，你到底知不知道什么是issue，还搞开发，真不建议你这种人上github

你把你的傻逼问题提在这里就像是当众拉屎一样

你怎么不联系政府让他们把防火墙给你关了？实在不行联系运营问问呢亲

我赞同 @whevether 说的，你这技术还是别搞了

**Comment by lengmianshi** [comment]
> > 执行`get init` 报错： ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get
> > 想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn
> 
> 笑死我他吗，你到底知不知道什么是issue，还搞开发，真不建议你这种人上github
> 
> 你把你的傻逼问题提在这里就像是当众拉屎一样
> 
> 你怎么不联系政府让他们把防火墙给你关了？实在不行联系运营问问呢亲
> 
> 我赞同 @whevether 说的，你这技术还是别搞了

我问的问题牵扯到什么技术了？谁规定issue就只能贴一堆大段源码、堆栈异常，就不能是其他问题？
假设yum只能使用国外源，你难受不，你是不是也请求zf把防火墙关了？
gitgub很高大上吗？
动不动开骂，真替国人素质感到悲哀

**Comment by ZaneCode6574** [comment]
> > > 执行`get init` 报错： ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get
> > > 想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn
> > 
> > 
> > 笑死我他吗，你到底知不知道什么是issue，还搞开发，真不建议你这种人上github
> > 你把你的傻逼问题提在这里就像是当众拉屎一样
> > 你怎么不联系政府让他们把防火墙给你关了？实在不行联系运营问问呢亲
> > 我赞同 @whevether 说的，你这技术还是别搞了
> 
> 我问的问题牵扯到什么技术了？谁规定issue就只能贴一堆大段源码、堆栈异常，就不能是其他问题？ 假设yum只能使用国外源，你难受不，你是不是也请求zf把防火墙关了？ github很高大上吗？ 动不动开骂，真替国人素质感到悲哀

楼上有点过激了，但是我也赞同这并不是一个“issue”

因为本质上，作者的代码、源没有任何问题，问题的来源是你自己，你无法访问到某个域名，而原因是因为中国屏蔽了这个域名

你把这个问题提出来，让作者给你解决，不合理。你应该自己解决这种问题。

你可以fork一个自己修改地址，也可以自己设置代理

**Comment by lengmianshi** [comment]
> > > > 执行`get init` 报错： ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = pub.dev, port = 61253, uri=https://pub.dev/api/packages/get
> > > > 想问下，如果修改get的镜像源，如改为https://pub.flutter-io.cn
> > > 
> > > 
> > > 笑死我他吗，你到底知不知道什么是issue，还搞开发，真不建议你这种人上github
> > > 你把你的傻逼问题提在这里就像是当众拉屎一样
> > > 你怎么不联系政府让他们把防火墙给你关了？实在不行联系运营问问呢亲
> > > 我赞同 @whevether 说的，你这技术还是别搞了
> > 
> > 
> > 我问的问题牵扯到什么技术了？谁规定issue就只能贴一堆大段源码、堆栈异常，就不能是其他问题？ 假设yum只能使用国外源，你难受不，你是不是也请求zf把防火墙关了？ github很高大上吗？ 动不动开骂，真替国人素质感到悲哀
> 
> 楼上有点过激了，但是我也赞同这并不是一个“issue”
> 
> 因为本质上，作者的代码、源没有任何问题，问题的来源是你自己，你无法访问到某个域名，而原因是因为中国屏蔽了这个域名
> 
> 你把这个问题提出来，让作者给你解决，不合理。你应该自己解决这种问题。
> 
> 你可以fork一个自己修改地址，也可以自己设置代理

非常感谢！
