### ISSUE TITLE
Get.off(Login());

### ISSUE THREAD

**Issue by ghenry** [jonataslaw/getx#309]
Hi, 

In #223 and the main docs, Get.Off is supposed to clear the navigation stack, but I discovered today that if `isLogged` changes after a few page navigations and you then do logout, I can click back on my android navigation bar and see all my last pages. Should this be get off all? 

```
void checkLogged(_) {
    if (isLogged.value) {
      Get.off(Home());
    } else {
      Get.off(Login());
    }
  }
```

Thanks.

**Comment by ghenry** [comment]
Let me upgrade to 3.1.0 and reconfirm and then if still there, I'll file a full proper bug report. Apologies.

**Comment by jonataslaw** [comment]
Hey, this is just an example, when it comes to hypothetically only having 1 page.
If you have more than one, use Get.offAll() instead of Get.off().

**Comment by ghenry** [comment]
Yep, switched to Get.offAll() and working as expected. Thanks!
