### ISSUE TITLE
Missing types of transitions

### ISSUE THREAD

**Issue by wailashraf71** [jonataslaw/getx#311]
After updating to 3.1.1 it shows an error when using **Tranistion.cupertino** and **Transition.size**.

**Comment by jonataslaw** [comment]
Version 3.0 removed the transition cupertino (If you want to use it on android, leftToRight should do the same thing), and transitions.size has also been removed.
You can create a custom transition and add with CustomTransitions now.
Transitions.native displays the native effect of each device, cupertino for iOS, and fade for android.

**Comment by ghenry** [comment]
I was using .size

What is that now?

Thanks.

**Comment by wailashraf71** [comment]
But **Transition.cupertino** and **Transition.leftToRight** are not the very same thing

**Comment by wailashraf71** [comment]
But **Transition.cupertino** and **Transition.leftToRight** are not the very same thing

**Comment by jonataslaw** [comment]
I put the two transitions back in the last update.
