### ISSUE TITLE
Flutter - get package: The getter 'backgroundColor' isn't defined for the class 'ThemeData'

### ISSUE THREAD

**Issue by wahyu-handayani** [jonataslaw/getx#3126]
I am using flutter ```3.22.2``` and installing ```get``` package with version ```4.6.5```. When I build my project, it is always stuck with error log:
```
Error (Xcode): ../../.pub-cache/hosted/pub.dev/get-4.6.5/lib/get_navigation/src/extension_navigation.dart:222:62:
Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.
```
Is there a way to solve this ?
I found related issues in this web https://www.reddit.com/r/flutterhelp/comments/1d4xf7k/comment/l7gjt3z/ but didn't find any solution yet. I also open my question in stackoverflow: https://stackoverflow.com/questions/78610954/flutter-get-package-the-getter-backgroundcolor-isnt-defined-for-the-class

**Comment by giantss** [comment]
+1

**Comment by wahyu-handayani** [comment]
Hi I found the solution for my question, I update get package into newest version (4.6.6) and it works for me

**Comment by HydronSid** [comment]
> Hi I found the solution for my question, I update get package into newest version (4.6.6) and it works for me

Right Solution. ....

**Comment by NhaPhan06** [comment]
> Hi I found the solution for my question, I update get package into newest version (4.6.6) and it works for me

What version??

**Comment by wahyu-handayani** [comment]
> > Hi I found the solution for my question, I update get package into newest version (4.6.6) and it works for me
> 
> What version??

the newest : 4.6.6
