### ISSUE TITLE
RxList extends List，not recommended

### ISSUE THREAD

**Issue by YueLiXing** [jonataslaw/getx#3133]
```
class TempService extends GetxService {
  final message = <String>[].obs;
  
  setMessage(List<String> newMessages) {
    message.value = newMessages;
  }
  
  Future<void> loadMessage() async {
    final temp = ['123'].obs;
    setMessage(temp);
  }
}
```

When you use it this way, there will be no error or warning prompts, but exceptions will occur at runtime because assigning the value of one Rx object to another Rx value。

**Comment by jonataslaw** [comment]
[How use Lists](https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#note-about-lists)

You SHOULD NEVER use `list.value = newValue`.

Use `AssignAll` (or assign) methods.
