### ISSUE TITLE
Lost Dependency

### ISSUE THREAD

**Issue by OptionSistemas** [jonataslaw/getx#315]
Hi.

In version 2.14.1, when I call test, 
`Get.offNamed("/home");`

don't lose your dependency on the login screen.

In version 3.1.2  it's losing.

I need the dependencies on the login screen and use them on other screens, but I no longer need the after login screen.

```
final CustomDio dio = Get.put(CustomDio(Get.put(Dio())));
final AppSettingsRepository appSettingsRepository = Get.put(AppSettingsRepository());
final TokenRepository tokenRepository = Get.put(TokenRepository());
final LoginRepository loginRepository = Get.put(LoginRepository());
final LoginController loginController = Get.put(LoginController());

```

In another screen I call the dependency, as in the example

`LoginController loginController = Get.find<LoginController>();`

Thanks.

**Comment by jonataslaw** [comment]
If you need a dependency on a page that no longer exists, you should mark it as permanent, something like this:

final LoginController loginController = Get.put(LoginController(), permanente:true);

**Comment by OptionSistemas** [comment]
100%. Thank you. Congratulations on the package. It is helping me a lot.
