### ISSUE TITLE
GlobalKey not letting the controller to get disposed

### ISSUE THREAD

**Issue by bajajsahil** [jonataslaw/getx#316]
**Describe the bug**
As discussed in the issue - #302  I have moved the GlobalKey inside the controller. But after moving the GlobalKey, the controller is not getting deleted from memory when I am navigating to another page using GetOff or GetoffAllNamed or GetOffAll or GetOffNamed.

**To Reproduce**
1. Add GetPage router with bindings defined.
2. Create a GlobalKey in the controller.
3. Use that GlobalKey in the Form widget
4. After submitting the form navigate to a different page with different bindings by removing the previous screen from the stack.
5. New controllers are getting created but previous page controllers are not getting deleted from memory.

**Expected behavior**
The controller should get deleted if navigation removed from the stack.

**Flutter Version:**
1.17.4

**Get Version:**
2.14.1

**Describe on which device you found the bug:**
Pixel3a-Android 29

**Minimal reproduce code**
```dart
GetPage(
  name: AuthScreen.routeName,
  page: () => AuthScreen(),
  binding: AuthBinding(),
),

class AuthBinding implements Bindings {
  @override
  void dependencies() {
    Get.lazyPut<AuthController>(() => AuthController());
  }
}

class AuthController extends RxController {
  static AuthController get to => Get.find();
  final GlobalKey<FormState> formKey = GlobalKey();
  ..............
	
  void auth() async {
    //auth code
	.................
		
	//Auth successful. Navigate to home
	Get.offAllNamed(HomeScreen.routeName);
  }
}

class AuthWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: Get.width * .75,
      padding: EdgeInsets.all(16.0),
      child: Form(
        key: AuthController.to.formKey,
        .......
  }
}
```
For the verification, I made the **key:null**, and observed that the controller was getting deleted from memory.

**Comment by jonataslaw** [comment]
First of all, update your version of Get, it would be very difficult to analyze a legacy version.

**Comment by bajajsahil** [comment]
It worked with the latest version - 3.1.2.

Closing this. Thanks
