### ISSUE TITLE
 Compatibility Issue Between GetX 5.0.0-release-candidate-6 and share_plus 10.0.1

### ISSUE THREAD

**Issue by fisforfaheem** [jonataslaw/getx#3162]
I am experiencing a version conflict when trying to use the GetX package (version 5.0.0-release-candidate-6) along with the share_plus package (version 10.0.1) in my Flutter project.

Error Message:

bash
Copy code
Because share_plus >=10.0.1 depends on web ^1.0.0 and get 5.0.0-release-candidate-6 depends on web >=0.4.0 <0.6.0, share_plus >=10.0.1 is incompatible with get 5.0.0-release-candidate-6.
And because no versions of get match >5.0.0-release-candidate-6 <6.0.0, share_plus >=10.0.1 is incompatible with get ^5.0.0-release-candidate-6.
So, because infrom_link_app depends on both get ^5.0.0-release-candidate-6 and share_plus ^10.0.1, version solving failed.
Steps to Reproduce:

Create a new Flutter project.
Add get: ^5.0.0-release-candidate-6 to pubspec.yaml.
Add share_plus: ^10.0.1 to pubspec.yaml.
Run flutter pub get.

Observed Behavior:
The version resolution fails due to incompatible dependencies between GetX and share_plus, specifically related to the web package version.

Workaround:
As a temporary solution, downgrading the share_plus package to version 10.0.0 resolves the issue:

bash
Copy code
flutter pub add share_plus:^10.0.0

Could you please provide guidance on how to resolve this dependency conflict without downgrading share_plus, or if there is a timeline for when these packages might be compatible?

**Comment by jonataslaw** [comment]
fixed in RC-8
