### ISSUE TITLE
Why GetX 5 removed `offAllNamed` `predicate`

### ISSUE THREAD

**Issue by Ssiswent** [jonataslaw/getx#3175]
![image](https://github.com/user-attachments/assets/da2817d6-86c5-47cd-935b-66cdf567bf9a)

If not use this, how can I do things like the old API?

![image](https://github.com/user-attachments/assets/4d5a2eb6-9114-4969-ae0e-21809839ec5c)

I tried to call `offNamedUntil` at new chat page, but not work as desired, when click back button in channel page, still go back to new chat page:

```dart
Get.offNamedUntil(
        Routes.channel,
        (route) => route.name == Routes.main,
        arguments: {'cid': data.cid},
      );
```

Screenshots:

newChat -> newGroupChat -> groupChatDetails -> channel:
![image](https://github.com/user-attachments/assets/e1478ed8-112e-433e-957d-5d167afc3f97)

Click back button in channel page:
![image](https://github.com/user-attachments/assets/c7607f35-a086-4bcb-8512-1ac2290aa2ea)

**Comment by jonataslaw** [comment]
Thanks for opening this issue.
Maybe Get.offUntil solves your use case. Could you confirm?
I removed the predicate for convention reasons, offAll will always remove the entire stack.

**Comment by Ssiswent** [comment]
> Thanks for opening this issue. Maybe Get.offUntil solves your use case. Could you confirm? I removed the predicate for convention reasons, offAll will always remove the entire stack.

Thanks for your reply, I tried `Get.offNamedUntil`, but the result is not as I desired.
You can see codes and outputs above, I described that in my issue.
![image](https://github.com/user-attachments/assets/17045ff2-b5ba-4fed-a266-8e4af1ed6f61)

**Comment by jonataslaw** [comment]
Could you try RC-10?
I think it is fixed right now.

**Comment by Ssiswent** [comment]
> Could you try RC-10?
> 
> I think it is fixed right now.
> 
> 

Let me try with RC-10 later, thank you.

**Comment by Ssiswent** [comment]
> Could you try RC-10? I think it is fixed right now.

Sry, I am using firebase_analytics, and get RC-10's dependency of web is conflict with that , do you know how to fix this?

```
Resolving dependencies... (2.3s)
Because firebase_analytics >=11.2.1 depends on firebase_analytics_web ^0.5.9+1 which depends on firebase_core_web ^2.17.4, firebase_analytics >=11.2.1
  requires firebase_core_web ^2.17.4.
And because firebase_core_web >=2.12.0 depends on web ^0.5.1 and get >=5.0.0-release-candidate-10 <5.0.0-release-candidate-2 depends on web ^1.0.0,
  firebase_analytics >=11.2.1 is incompatible with get >=5.0.0-release-candidate-10 <5.0.0-release-candidate-2.
So, because finnplay_chat depends on both get 5.0.0-release-candidate-10 and firebase_analytics ^11.2.1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on get: flutter pub add get:^4.6.6
```

**Comment by Ssiswent** [comment]
> > Could you try RC-10? I think it is fixed right now.
> 
> Sry, I am using firebase_analytics, and get RC-10's dependency of web is conflict with that , do you know how to fix this?
> 
> ```
> Resolving dependencies... (2.3s)
> Because firebase_analytics >=11.2.1 depends on firebase_analytics_web ^0.5.9+1 which depends on firebase_core_web ^2.17.4, firebase_analytics >=11.2.1
>   requires firebase_core_web ^2.17.4.
> And because firebase_core_web >=2.12.0 depends on web ^0.5.1 and get >=5.0.0-release-candidate-10 <5.0.0-release-candidate-2 depends on web ^1.0.0,
>   firebase_analytics >=11.2.1 is incompatible with get >=5.0.0-release-candidate-10 <5.0.0-release-candidate-2.
> So, because finnplay_chat depends on both get 5.0.0-release-candidate-10 and firebase_analytics ^11.2.1, version solving failed.
> 
> 
> You can try the following suggestion to make the pubspec resolve:
> * Consider downgrading your constraint on get: flutter pub add get:^4.6.6
> ```

I tried to add `dependency_overrides` to fix this, is this the best way now?
![image](https://github.com/user-attachments/assets/e8383562-8e0b-438b-9620-9d93492a0f06)

And as you said, RC-10 has fixed this issue, thanks!

**Comment by Gaurav-CareMonitor** [comment]
Hi @Ssiswent Please close the issue if its fixed.
