### ISSUE TITLE
firebase_messaging_web  issues : et >=5.0.0-release-candidate-8 depends on web ^1.0.0, get >=5.0.0-release-candidate-8 is incompatible with firebase_messaging_web ^3.8.12.

### ISSUE THREAD

**Issue by fisforfaheem** [jonataslaw/getx#3176]
Because firebase_messaging_web 3.8.12 depends on web ^0.5.1 and no versions of firebase_messaging_web match >3.8.12 <4.0.0, firebase_messaging_web ^3.8.12 requires web ^0.5.1.
And because get >=5.0.0-release-candidate-8 depends on web ^1.0.0, get >=5.0.0-release-candidate-8 is incompatible with firebase_messaging_web ^3.8.12.
And because firebase_messaging 15.0.4 depends on firebase_messaging_web ^3.8.12 and no versions of firebase_messaging match >15.0.4 <16.0.0, get >=5.0.0-release-candidate-8 is incompatible with firebase_messaging ^15.0.4.
So, because infrom_link_app depends on both firebase_messaging ^15.0.4 and get ^5.0.0-release-candidate-8, version solving failed.
exit code 1

**Comment by inyong1** [comment]
Its seem because firebase_messaging_web stil use old version of web (0.5.1)Maybe we have to wait updates for the firebase_messaging.

**Comment by fisforfaheem** [comment]
Any other solution? may use "any" as version instead of fixed...but that
still gives errors.

**Comment by jonataslaw** [comment]
I believe you should open this issue in the repository https://github.com/firebase/flutterfire which is responsible for the package that uses outdated dependencies.

Also, as a temporary workaround, you can use `dependency_overrides` in pubspec:

https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by jonataslaw** [comment]
Related: https://github.com/firebase/flutterfire/pull/13172
