### ISSUE TITLE
ScrollController attached to multiple scroll views

### ISSUE THREAD

**Issue by gogappi** [jonataslaw/getx#318]
**Describe the bug**
When a page which has GFCarousel is open and then the app is moved to memory and reopened the error **"ScrollController attached to multiple scroll views 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 111 pos 12: '_positions.length == 1'"**  appears in place of the GF Carousel. Once you scroll on it the error disappears.

**To Reproduce**
1. Open page which has a GF Carousel
2. Exit the app from that page
3. Let the app be in memory while you use other applications for a while.
4. Open the app by clicking the app launcher icon (not from memory)

**Expected behavior**
No such error.

**Screenshots**
![IMG-20200628-WA0052](https://user-images.githubusercontent.com/54227726/86085989-2b3a1200-babe-11ea-9efc-fc7b58daf935.jpg)

**Flutter Version:**
Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)

**Get Version:**
getflutter: ^1.0.10

**Describe on which device you found the bug:**
ex: Redmi K20 Pro, Samsung M40, Pixel 2 Emulator

**Minimal reproduce code**
Padding(
                padding: const EdgeInsets.only(top: Spacing.g2),
                child: GFCarousel(
                  activeIndicator: Colors.black,
                  enlargeMainPage: true,
                  enableInfiniteScroll: false,
                  passiveIndicator: Colors.white,
                  pagination: true,
                  height: 130,
                  items: _listOfWodgets,
                  onPageChanged: (index) {
                    setState(() {});
                  },
                ),
              )

**Comment by jonataslaw** [comment]
Please put this in the correct library.

**Comment by gogappi** [comment]
Really sorry. Thanks for the prompt response.
