### ISSUE TITLE
Erron on Get.toNamed in CupertinoPageScaffold

### ISSUE THREAD

**Issue by yeras-is** [jonataslaw/getx#319]
**Describe the bug**
There are multiple heroes that share the same tag within a subtree.

**To Reproduce**
```
I/flutter ( 5430): [GET] GetMaterialController has been initialized
I/flutter ( 5430): [GOING TO ROUTE] /init
I/flutter ( 5430): [GOING TO ROUTE] /notifications
I/flutter ( 5430): [BACK ROUTE] /notifications
I/flutter ( 5430): [GOING TO ROUTE] /notifications
I/flutter ( 5430): [BACK ROUTE] /notifications
I/flutter ( 5430): [GOING TO ROUTE] /notifications
I/flutter ( 5430): [BACK ROUTE] /notifications
I/flutter ( 5430): [GOING TO ROUTE] /notifications
```
**Flutter Version:**
environment:
  sdk: ">=2.7.0 <3.0.0"

**Get Version:**
get: ^3.1.1

**Describe on which device you found the bug:**
Pixel 2 XL API 22- Android.

**Minimal reproduce code**
```dart
class MainLayout extends StatelessWidget {
  var index = 'calendar';
  var pages = {
    'calendar':  GestureDetector(
      onTap: () => Get.toNamed('/notifications'),
      child: Icon(CupertinoIcons.bell)),
  };

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: CupertinoTabScaffold(
        tabBuilder: (BuildContext context, int index) {
          return pages[index] ?? Container();
        },
        tabBar: CupertinoTabBar(
          onTap: (value) {
            switch (value) {
              case 0:
                setState(() {index='calendar'});
                break;
              case 1:
                setState(() {index='tasks'});
                break;
            }
          },
          items: [
            BottomNavigationBarItem(
              icon: Icon(Icons.calendar_today),
              title: Text('calendar'),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.check_circle_outline),
              title: Text('tasks'),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by yeras-is** [comment]
![bug](https://user-images.githubusercontent.com/47042331/86106315-3d2dac00-bae2-11ea-9841-38595f5b65ab.gif)

**Comment by jonataslaw** [comment]
Before analyzing your code:
Did you add a heroTag to your floatingActionButton?
FloatingActionButton (
heroTag: 'button1',

If you have more than one FloatingActionButton (you must have a heroTag for each one.

Preliminarily, just looking at the error description looks like a FloatingActionButton without heroTag, which always gives an error when you use elements of the cupertino with it, or when you have more than one of them in the widget tree.

**Comment by yeras-is** [comment]
I've removed all FloatingActionButtons but error is still here

**Comment by yeras-is** [comment]
![untitled](https://user-images.githubusercontent.com/47042331/86158971-6cb4d680-bb2b-11ea-89a5-a88245d482a4.gif)

**Comment by yeras-is** [comment]
It looks like CupertinoNavigationBar  require unique hero tag. Thanks for great plugin ))
