### ISSUE TITLE
Using Transition.native on flutter 1.20 is doing a Fade transition on iOS

### ISSUE THREAD

**Issue by jlubeck** [jonataslaw/getx#320]
**Describe the bug**
Basically what the title says.
I'm using get 3.1.0 and I just updated Flutter to 1.20.0-2.0.pre. Now the native transitions on iOS are doing a Fade.

```
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.0-2.0.pre at /Users/jan/flutter
    • Framework revision 15a28159bc (7 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jan/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```

**Comment by jonataslaw** [comment]
Could you upgrade to the latest version and give a flutter clean? I am currently using the native transition on iOS, and it is working normally.

**Comment by jlubeck** [comment]
I just did that. Same issue.

Looking at the external packages folder, I see that it is downloading `get-3.1.2`

Any specific code I can check to make sure I really have the latest? 

Also, if I change Transition.native to any other one, it works as expected. But using native again, it uses fade.

**Comment by jlubeck** [comment]
Don't know if it makes a difference, but I'm using an iPad, not an iPhone

**Comment by jonataslaw** [comment]
> Don't know if it makes a difference, but I'm using an iPad, not an iPhone


https://github.com/jonataslaw/getx/issues/303

I think it makes no difference, since this recent issue works even on the emulator

**Comment by jlubeck** [comment]
Yes, I saw that issue. That's why I opened this one, because I had already updated to 3.1.2 and I was still having this issue. 

Can you please let me know what did you change on 3.1 that fixed that issue so that I can try to debug it?

**Comment by jonataslaw** [comment]
https://github.com/jonataslaw/getx/commit/6009b0adfdb91d6835719bf92c876cd9b3d190ab#diff-5392cfd81ba280448ccce2a97b3b3473

**Comment by jonataslaw** [comment]
Transitions.cupertino on last update will force the cupertino animation for you.

**Comment by jlubeck** [comment]
Yup, that worked. Thank you

**Comment by jlubeck** [comment]
By the way, just curious,  how come doing a pub upgrade gave me 3.1.4 but here the latest release is 3.1.2?
