### ISSUE TITLE
Get.changeTheme(); can't change the GetMaterialApp.darkTheme

### ISSUE THREAD

**Issue by CalmLuo** [jonataslaw/getx#3230]
Get.changeTheme();  Only GetMaterialApp.theme is changed, but the value of GetMaterialApp.darkTheme cannot be changed

**Comment by jonataslaw** [comment]
Could you please attach the reproduction code? I can't analyze this without it.

**Comment by CalmLuo** [comment]
I see. Thank you

![image](https://github.com/user-attachments/assets/874cc81b-b23e-4cd1-8b87-ffb91c4bf3ab)

![image](https://github.com/user-attachments/assets/c5fe8b57-fe8a-4433-ac6c-c7b745d569a2)

**Comment by CalmLuo** [comment]
I have solved the problem, can close, thank you
