### ISSUE TITLE
[beboro] flutter pub get --no-example Resolving dependencies... Because every version of get from git depends on web >=0.4.0 <0.6.0 and firebase_core_web >=2.18.0 depends on web ^1.0.0, get from git is incompatible with firebase_core_web >=2.18.0. And because firebase_core >=3.5.0 depends on firebase_core_web ^2.18.1, get from git is incompatible with firebase_core >=3.5.0. So, because beboro depends on both firebase_core ^3.6.0 and get from git, version solving failed.

### ISSUE THREAD

**Issue by fisforfaheem** [jonataslaw/getx#3247]
[beboro] flutter pub get --no-example
Resolving dependencies...
Because every version of get from git depends on web >=0.4.0 <0.6.0 and firebase_core_web >=2.18.0 depends on web ^1.0.0, get from git is incompatible with firebase_core_web >=2.18.0.
And because firebase_core >=3.5.0 depends on firebase_core_web ^2.18.1, get from git is incompatible with firebase_core >=3.5.0.
So, because beboro depends on both firebase_core ^3.6.0 and get from git, version solving failed.

**Comment by jonataslaw** [comment]
Hi, Could you please elaborate more?

This error doesn't make sense. It's saying that get depends on web version >=0.4.0 <0.6.0.

That's not true.

https://github.com/jonataslaw/getx/blob/master/pubspec.yaml#L15

Are you using a old version?

Try run:

flutter pub upgrade

**Comment by fisforfaheem** [comment]
Oh, I thought i was using the latest version, just checked now it's working
now. Thanks
