### ISSUE TITLE
GetStorage is available?

### ISSUE THREAD

**Issue by jhonattanS** [jonataslaw/getx#325]
I have update getx to the last version, cleaned my project (a.k.a flutter clean), but i not able to import 'GetStorage', i don't no if is a problem in my workspace or something else. In the docs the storage seems to be implemented.

thanks.

---
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.3 19D76, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

---

get: ^3.1.4
  sqflite: ^1.3.1
  sqlcool: ^4.3.1
  supercharged: ^1.6.0    
  flutter_icons: ^1.1.0
  google_fonts: ^1.1.0
  input_sheet: ^0.1.1
  simple_animations: ^2.2.1
  responsive_framework: ^0.0.7

**Comment by jonataslaw** [comment]
Hi, due to the problems that dart is facing with pana, I had to put it in a separate package.
https://pub.dev/packages/get_storage

**Comment by jhonattanS** [comment]
Thanks!
