### ISSUE TITLE
onClose() is automatically called while the controller is still in use.

### ISSUE THREAD

**Issue by khanhduy122** [jonataslaw/getx#3252]
I am developing a front-end chat application, I have a controller named ChatRoomController Put with the ChatRoomID tag, in this ChatRoom screen, I want when I click on Notification, it will replace this screen with a new controller Put with the new tag, everything works fine until I focus on the Textfield, the onClose function is called while the controller is still in use, the Controller still has the functions in the Controller still working normally, only the onClose is called Dispose all the controllers like TextEditingController, ScrollController, animationController, ... have been disposed. Any suggestions from everyone will help me a little

Thanks!

## handle when clicking on notification
I use parameter as tag

![image](https://github.com/user-attachments/assets/abd4eb33-3fd1-4b85-bbac-3c2870255a1e)

## Example

https://github.com/user-attachments/assets/7d48e2fb-4518-4226-bcdb-a5d7c87b6649

## Log

![z6024665946772_a1a00f5af017a27be32c157b0030a33c](https://github.com/user-attachments/assets/26f7b3dc-7940-4b2e-acc1-8d56b1c1f444)

**Comment by TMS-AnNT** [comment]
I'm so sorry, because I didn't pass in the tag in GetBuilder, that's why TextEditController got this error.

**Comment by khanhduy122** [comment]
I'm so sorry, because I didn't pass in the tag in GetBuilder, that's why TextEditController got this error.
