### ISSUE TITLE
Make GetView support multiple Controllers

### ISSUE THREAD

**Issue by Nipodemos** [jonataslaw/getx#328]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
some guy with the username arctekko told me about GetView, and i liked very much to see. But it does not support more than one controller. I think it should support more then one. I don't know how it would be made, but i think it would be nice

However, if it is not a good idea, let me know

**Comment by jonataslaw** [comment]
https://github.com/jonataslaw/getx/blob/master/lib/src/state/get_view.dart
This function already exists, but it is disabled, because I am wondering if "controller1" "controller2" is not ugly.

**Comment by Nipodemos** [comment]
🤔 
yeah, i'll have to agree with you, this doesn't sound like a good approach.
Guess the ideal with GetX is one controller per view right? although you can use more.

nevermind kkkkkkk, it not a good idea
