### ISSUE TITLE
Add "preventDuplicates" option into Global Settings

### ISSUE THREAD

**Issue by hhhai0304** [jonataslaw/getx#330]
Hi, I think we need to add "preventDuplicates" option into Global Settings.

In my case, I have a product detail page, and this page contains many other products (and there are many similar pages like this), so I need to add "preventDuplicates" every time Get.to(), this is quite inconvenient...

Does anyone agree with me? :)

**Comment by jonataslaw** [comment]
Hi, You do not need to set this manually every time, as the default value is true.
If you want duplicate routes (very difficult, I can't see use cases), you can define this manually.
There is also nothing to prevent you from creating a global function already configured with the value you want, so I believe that this resource request does not make much sense to me. Therefore, I am closing this feature request.
