### ISSUE TITLE
onClose() method is not called and onReady() is called in between of onInit() method

### ISSUE THREAD

**Issue by MickelAngel0** [jonataslaw/getx#333]
When an async operation is done on controller initialisation the screen remains empty.
It would have been better if Get had an option to show user some kind of feedback like CircularProgressIndicator so that user gets to know some kind of operation is being performed.
I expect this feature as
When a controller is being initialised and some async operation is done
Then till the operation is done some feedback should be given to user
Please add this feature.
Thank you.

**Comment by jonataslaw** [comment]
Hi, shouldn't that be done on your side?
I mean, just a bool with a GetX, Obx or even GetBuilder at the root would solve your problem, and you can use the loader that you think is best, the library doesn't need to cast it. Well, I don't know if that would be useful, adding an extra feature to something that could literally be solved with 3 lines.

```dart
class Controller extends GetxController{
var isInit = false; // add this

onInit()async {
// your async op
isInit.value = true; // and this
}
}
```

on Your widget:

```dart
class Any extends StatelessWidget{
@override
build(context){
return Obx(()=> controller.isInit.value? YourWidget() : CircularProgressIndicator()); // Obx like root 
}
```

**Comment by loicgeek** [comment]
@MickelAngel0  you have to handle it by yourself, it is pretty easy ,  your controller could hold three variable for each operation, opIsLoading, opSucess and opError , you could also add a errorMessage variable, with a try catch block, when starting set opLoading=true, on success opSucess=false and opLoading=false, on error opError =true , opLoading=false and errorMesage=message,  and with Obx you could show what you want depending on the value of those variables.

**Comment by MickelAngel0** [comment]
@loicgeek thank you for your help but as my current project is quite small so I don't need all this variables to be created 
But for my future projects I'll surely apply this method thank you again

@jonataslaw thank you the idea u mentioned did work and as I said my project is small so this idea was quite good for me 
Thank you

I need one more help from you all
I tried all methods onReady (), onInit() and onClose()
onInit() is working as expected no problem in that
But onReady() is called in between the onInit() method
Is this meant to work like this only ?
And for what was this onReady() meant for??

And for onClose() method 
When is this method called ??
Because in my project it was never called

What I did was initial line of every method I wrote print statement and in end of method also I wrote print statement

Please help.

**Comment by jonataslaw** [comment]
onInit is called when the Controller enters memory.
onReady is called after the end of the build method (it is safe for snackbars and dialogs, not onInit).
onClose is called when the controller is deleted. It is the ideal place to close streams.

**Comment by MickelAngel0** [comment]
@jonataslaw 
As u said onClose() is good for closing streams 
I tried to load data into box and save it in box 
Hive box
N after saving I tried to close the box
But it was not behaving as expected
Can you help please??

**Comment by Nipodemos** [comment]
@MickelAngel0 hive says that you don't need to close and reopen box in your app
you can leave it open during the application lifetime

i think you don't need to close hive when you close the app. But that i am not certain

**Comment by MickelAngel0** [comment]
@Nipodemos 
Yes you are right hive does work in that way
But the problem is 
I want to put my data into hive as soon as the app is closed 
But onClose() is not called 

So can you help ??

**Comment by jonataslaw** [comment]
> @jonataslaw
> As u said onClose() is good for closing streams
> I tried to load data into box and save it in box
> Hive box
> N after saving I tried to close the box
> But it was not behaving as expected
> Can you help please??
> 
> And as I mentioned earlier also
> onClose() is not called after closing the app
> And I'm using single controller
> My whole app is based on single controller
> So I wanted that when I close app
> Current data should b put in hive box and it should b closed
> Please help

onClose or dispose, Flutter does not support this.
I would personally do a PR on Flutter to add a callback on onDestroy on android and ApplicationWillTerminate on iOS, but one of the team members has already said that this function will not be implemented in Flutter, so I can't do anything.

**Comment by Nipodemos** [comment]
guess the solution then will be to update box whenever some value change, instead of update when the app is closed. It is harder, but it is the only option i can see

**Comment by MickelAngel0** [comment]
> > @jonataslaw
> > As u said onClose() is good for closing streams
> > I tried to load data into box and save it in box
> > Hive box
> > N after saving I tried to close the box
> > But it was not behaving as expected
> > Can you help please??
> > 
> > And as I mentioned earlier also
> > onClose() is not called after closing the app
> > And I'm using single controller
> > My whole app is based on single controller
> > So I wanted that when I close app
> > Current data should b put in hive box and it should b closed
> > Please help
> 
> onClose or dispose, Flutter does not support this.
> I would personally do a PR on Flutter to add a callback on onDestroy on android and ApplicationWillTerminate on iOS, but one of the team members has already said that this function will not be implemented in Flutter, so I can't do anything.

No
Flutter does support dispose
I'm statefulwidget there is override for for dispose 
And when I started flutter 
At that time also I did this printing line 
And dispose method is called 
I have seen this

**Comment by jonataslaw** [comment]
Dispose is not called when the application is closed.
It is called when the Widget leaves the stack.

If dispose is called, onClose is also called, the dispose of a view that contains a GetX/GetBuilder automatically calls onClose.

**Comment by MickelAngel0** [comment]
> Dispose is not called when the application is closed.
> It is called when the Widget leaves the stack.
> 
> If dispose is called, onClose is also called, the dispose of a view that contains a GetX/GetBuilder automatically calls onClose.

Yes 
You are right 
What i wanted was onClose() should be called when widget after the material app is disposed

But as mentioned it's problem with flutter only
So can't do anything
Anyways 
Thanks for help

**Comment by MickelAngel0** [comment]
> guess the solution then will be to update box whenever some value change, instead of update when the app is closed. It is harder, but it is the only option i can see

Yes currently using same idea 
Thanks for your help

**Comment by jonataslaw** [comment]
Well, since that has been clarified, I am closing this. Any problem you can open another issue.
