### ISSUE TITLE
Refresh with every frame

### ISSUE THREAD

**Issue by ialameh** [jonataslaw/getx#339]
Hi,

In my controller extending GetxController, I did an override for the init to receive information from a stream

  @override
  onInit() async {
    ever(user, (value) => print('printing the value ${value.toString()}'));
    user.value = await FirebaseAuth.instance.currentUser();
    user.bindStream(FirebaseAuth.instance.onAuthStateChanged);
    super.onInit();
  }

in my view, I had an input field and handed over its function to another class 
the input field is a textbox and the decoration was called from another class while sending a function from the controller to be executed when a buttonicon is pressed 
final AuthenticationService _ = AuthenticationService.to;

decoration: inputdecorator(
function: _.functionfromcontroller

in the inputdecorator class:

IconButton(
                icon: Icon(suffixIcon),
                onPressed: () => function,
              )

the function itself is a get:

get function => flipFieldVisibility;

this situation is causing the field to rebuild with every frame 30-60 times per second

I removed the call (used decoration.copywith ) and kept the function to be called within my view everything worked fine

Sam

**Comment by jonataslaw** [comment]
Hi, sorry, but I still couldn't understand your problem, and where does this relate to Getx.
Could you please be a little clearer and follow the issue opening model?
Erasing all questions and writing something without following the script is never a good idea, try to keep the model next time, please.

**Comment by ialameh** [comment]
I am sorry I was not able to reproduce the error. I think it was a mistake from my side
thank you for responding, I will be mindful next time when I post an issue

**Comment by jonataslaw** [comment]
Okay, so I'm closing this.
If you encounter problems do not hesitate to open another issue, and if you can reproduce a problem, you can reopen that issue.
