### ISSUE TITLE
Get.back() doesn't close dialog when button is pressed

### ISSUE THREAD

**Issue by beatc1234** [jonataslaw/getx#340]
```dart
 try {
      .....
    } catch (e) {
      Get.back(); //remove snackbar
      Get.defaultDialog(
        title: "Error",
        middleText: e.message,
        confirm: FlatButton(
          onPressed: () {
            Get.back();
            print('asdasd');
          },
          child: Text("Close"),
        ),
      );
      print(e);
    }
```

Only snackbar is closed but not the dialog. Tapping outside the dialog will close it but not the button.

**Comment by jonataslaw** [comment]
I try
```dart
 RaisedButton(
              child: Text('Next Route'),
              onPressed: () async {
                Get.snackbar('title', 'message');
                await Future.delayed(Duration(seconds: 1));
                Get.back(); //remove snackbar
                Get.defaultDialog(
                  title: "Error",
                  middleText: "e.message",
                  confirm: FlatButton(
                    onPressed: () {
                      Get.back();
                      print('asdasd');
                    },
                    child: Text("Close"),
                  ),
                );
              },
            ),
```
and 
```dart
 RaisedButton(
              child: Text('Next Route'),
              onPressed: () {
                Get.snackbar('title', 'message');
                Get.back(); //remove snackbar
                Get.defaultDialog(
                  title: "Error",
                  middleText: "e.message",
                  confirm: FlatButton(
                    onPressed: () {
                      Get.back();
                      print('asdasd');
                    },
                    child: Text("Close"),
                  ),
                );
              },
            ),
```
In both cases the dialog is closed with a click.
Please provide a case reproduction of the problem so that we can proceed with your issue, otherwise it will be closed.
Try not to delete the error template too next time.

**Comment by beatc1234** [comment]
That's weird. I called the dialog after submitted the form. Probably it got something to do with the form or the keyboard is active, Nevertheless, I just removed the button and moved on. Thanks for the help.

**Comment by beatc1234** [comment]
Btw, I just checked your get_main.dart and the `_routing.isDialog` is not set to true when `defaultDialog` is called hence maybe why I can't close the dialog when button is pressed.

**Comment by ibrahimbroachwala** [comment]
I am facing the same issue with Flutter v2.10. 

Get.back() doesn't close the dialog.

**Comment by MorosophDude** [comment]
`Get.back(closeOverlays: true);` worked for me. Tested on `get: ^4.6.1`

Suggested by [rahul12hisar](https://github.com/rahul12hisar) in https://github.com/jonataslaw/getx/issues/1091#issuecomment-895710031

**Comment by MonsterOfCode** [comment]
> `Get.back(closeOverlays: true);` worked for me. Tested on `get: ^4.6.1`
> 
> Suggested by [rahul12hisar](https://github.com/rahul12hisar) in [#1091 (comment)](https://github.com/jonataslaw/getx/issues/1091#issuecomment-895710031)

 With the same version it doesn't work, some other solution?

**Comment by MorosophDude** [comment]
> > `Get.back(closeOverlays: true);` worked for me. Tested on `get: ^4.6.1`
> > Suggested by [rahul12hisar](https://github.com/rahul12hisar) in [#1091 (comment)](https://github.com/jonataslaw/getx/issues/1091#issuecomment-895710031)
> 
> With the same version it doesn't work, some other solution?

Sorry, I totally forgot I had suggested this method on Github. For me it worked for a while but after the logic on button press got complex [client needed validation and message was to be shown in toast - I used Get.snackbar()] this method was not reliable any more. So, I dug into implementation for `Get.back(closeOverlays: true);` and found this:

`navigator?.popUntil((route) => !Get.isDialogOpen! && !Get.isBottomSheetOpen!);`

Hope this helps you as well.

**Comment by TahaMsv** [comment]
> Get.back(closeOverlays: true);
This works for me.

**Comment by rodrigorslima** [comment]
> I'm facing the same problem
> 
> When I remove Get.snackbar, Get.back() closes the dialog. But when showing the snack and calling Get.back(), it does not work
> 
> The solution worked for me is calling **Get.close(1);**

this worked

**Comment by bienvu27** [comment]
Hope this helps you:
Navigator.of(context, rootNavigator: true).pop();

**Comment by Koma-Chen** [comment]
> Hope this helps you: Navigator.of(context, rootNavigator: true).pop();

It works,thanks.

**Comment by asadamatic** [comment]
As a workaround, I had to add a delay after calling `Get.closeAllSnackbars`.

```
Get.closeAllSnackbars();
await Future.delayed(Duration(seconds: 1));
Get.back();
```

### Better Solution
I didn't want to use a delay, and another work around for me was to call `Get.closeAllSnackbars` before calling `Get.snackbar` , to prevent stacking snackbars.

**Comment by hamzabilalgaya5** [comment]
> I'm facing the same problem
> 
> When I remove Get.snackbar, Get.back() closes the dialog. But when showing the snack and calling Get.back(), it does not work
> 
> The solution worked for me is calling **Get.close(1);**

This solution really worked for me. Thanks I was using a snackbar and dialog box simultaneously and encountered this error but this solution resolved my problem.

**Comment by Naimehossein77** [comment]
> Hope this helps you: Navigator.of(context, rootNavigator: true).pop();

Thanks buddy. I was using Getx Routing GetPages which was popping the screens instead of dialog. This solution only worked for the scenario

**Comment by diukawsar** [comment]
> Get.close(1)

Its working in 2025-03-19



but is the bug fixed in any version?

**Comment by Samama007** [comment]
> As a workaround, I had to add a delay after calling `Get.closeAllSnackbars`.
> 
> ```
> Get.closeAllSnackbars();
> await Future.delayed(Duration(seconds: 1));
> Get.back();
> ```
> 
> ### Better Solution
> I didn't want to use a delay, and another work around for me was to call `Get.closeAllSnackbars` before calling `Get.snackbar` , to prevent stacking snackbars.

WELL DONE!
