### ISSUE TITLE
Annotate isDarkMode and isPlatformDarkMode types

### ISSUE THREAD

**Issue by Grohden** [jonataslaw/getx#341]
latest GetX version. 

I'm switching from `pedantic` to `effective_dart`, and I got a  unneeded cast warning from dart analysis, removing the cast caused the following warning:

<img width="1315" alt="Screen Shot 2020-07-03 at 17 09 36" src="https://user-images.githubusercontent.com/7496871/86495567-46bc4b80-bd50-11ea-846a-67d5b69457da.png">

So to avoid this warning I have to make a cast.. and then get a `cast not needed` warning... and so on. (I wanna head pat dart analysis, good job on this one boy).

Since these getters are public would be nice to have them typed.

Btw, there are other fields to annotate that I can think of too:
`currentRoute`
`previousRoute`

**Comment by jonataslaw** [comment]
Thanks for point this. 
It was fixed in the last update.

https://github.com/jonataslaw/getx/commit/08b10f4d340f829c05d52e2c903e452abfb32315#diff-9ee040dd5ee06195d8d527bacfbe1509
