### ISSUE TITLE
Opening a page from inside a TabBarView has weird behavior 

### ISSUE THREAD

**Issue by jlubeck** [jonataslaw/getx#342]
When navigating from inside a TabBarView to a different page (other than the ones in the tab bar itself) it is expected that the new page would transition with the default animation replacing the current tab. You can check the Facebook or Twitter apps for this behavior.

Worst case scenario, it should at least open as a completely new page (no longer seeing the tabBar) with the default transition

It is currently doing something strange where it begins transitioning, but you see a black screen, and the it opens from the bottom behaving like a modal. 

Here is the full replication code. And screenshots showing 4 states of the animation to show what I'm describing

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      getPages: [
        GetPage(
          name: '/home',
          page: () => MyHomePage(),
        ),
        GetPage(
          name: '/page1',
          page: () => Page1(),
        ),
      ],
      initialRoute: '/home',
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(context) {
    return DefaultTabController(
      length: 2,
      child: Scaffold(
        backgroundColor: Colors.grey,
        body: TabBarView(
          children: <Widget>[
            Center(
              child: RaisedButton(
                child: Text('Page 1'),
                onPressed: () {
                  Get.toNamed('/page1');
                },
              ),
            ),
            Center(
              child: Text('Page 2'),
            ),
          ],
        ),
        bottomNavigationBar: Container(
          child: BottomAppBar(
            child: TabBar(
              labelColor: Colors.blue,
              tabs: <Widget>[
                Container(
                  child: Tab(icon: Icon(Icons.language)),
                ),
                Container(
                  child: Tab(icon: Icon(Icons.image)),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Container(
        child: Center(
          child: Text('Page 1 internal'),
        ),
      ),
    );
  }
}

```

<img width="333" alt="Screen Shot 2020-07-03 at 5 25 38 PM" src="https://user-images.githubusercontent.com/3067603/86498120-681e3700-bd52-11ea-87e0-c16c7e48ca88.png">
<img width="336" alt="Screen Shot 2020-07-03 at 5 25 45 PM" src="https://user-images.githubusercontent.com/3067603/86498121-694f6400-bd52-11ea-9cfb-39381ba47d05.png">
<img width="334" alt="Screen Shot 2020-07-03 at 5 25 54 PM" src="https://user-images.githubusercontent.com/3067603/86498122-694f6400-bd52-11ea-8ae7-61f2742e2d21.png">
<img width="331" alt="Screen Shot 2020-07-03 at 5 26 00 PM" src="https://user-images.githubusercontent.com/3067603/86498123-69e7fa80-bd52-11ea-8478-7de4c2719d69.png">

**Comment by jonataslaw** [comment]
Fix on 3.2.2

**Comment by jlubeck** [comment]
Hey! This seems to be fixed, but how come the animation for the transition is waaay slower than normal transitions? Is it using something different than the default transition? Let me know if you need me to create a video to show you

**Comment by jonataslaw** [comment]
> Hey! This seems to be fixed, but how come the animation for the transition is waaay slower than normal transitions? Is it using something different than the default transition? Let me know if you need me to create a video to show you

The default transition time of the Flutter I believe is 300ms

Get's default transition time is 400ms

Perhaps that gave that impression.
You can configure this globally in your GetMaterialApp

**Comment by jlubeck** [comment]
I'm sorry you are right... I though I was using Get.to everywhere but seems like I wasn't and there is the difference.

Thanks again!

**Comment by bcbcbcbcbcl** [comment]
@jonataslaw I'm using version ^4.1.4 but this issue still exist in iOS. Any workaround? Thanks in advance.
