### ISSUE TITLE
GetController or GetxController?

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#343]
I am confused, the document refer all to GetxController, but the example code using GetController.
What is the different between these 2? Which one should we use?

**Comment by jonataslaw** [comment]
The sample code for the repository is from version 2.0 that still used Get controller.
In version 3 you must use GetxController

**Comment by peekpt** [comment]
@jonataslaw is it possible to have more than one instance of the same type controller?

Example: 
In a browser the state controller will be the same kind for every page you open.

**Comment by Nipodemos** [comment]
@peekpt you don't need multiple instances of your controller

you can use the same single instance in the entire app, using dependency injection
and what do you mean the same state controller for every page? you mean that in all pages you gonna use the exact same data displaying the exact same thing?

or you gonna use the controller to show different data in every page? if that's the case, use one controller per page

**Comment by peekpt** [comment]
@jon

**Comment by Nipodemos** [comment]
well, i did not understand yet but i am deviating from the subject.
@jonataslaw can you confirm if what he asked is possible on get? as far as i know, it is not

**Comment by jonataslaw** [comment]
There are several ways to do this.

The first:
`Controller controller = Controller (); // without Get.put()`

The second, if you are injecting dependency directly on the widget:

```dart
GetBuilder<Controller>( // or GetX
init: Controller(),
global: false, // remembering that this will make the controller available only within GetBuilder
builder: (controller) => Text(controller.name)
[...]
```

The third is using tags:

```dart
Controller c1 = Get.put (Controller(), tag: 'ct1');
Controller c2 = Get.put (Controller(), tag: 'ct2');
Controller c3 = Get.put (Controller(), tag: 'ct3');
```

There is still a longer way using abstractions and override: true, but it is not documented because I am not sure if I will keep the api, so I will not explain about it here.

**Comment by peekpt** [comment]
@jasonlaw https://www.reddit.com/r/FlutterDev/comments/hmjff1/people_who_are_you_using_getx_how_do_you_feel/?utm_source=ifttt
I will delete this post once you put a icon reaction

**Comment by jonataslaw** [comment]
Example updated. Closing this
