### ISSUE TITLE
Add replace api for lists

### ISSUE THREAD

**Issue by Vladvsemogusch** [jonataslaw/getx#348]
If I want to update an item in a list, curently the only option is to remove and insert modified version into the same position. 
I think the better approach would be adding replace functionality to lists or notifyItemsUpdated of some sort.

**Comment by jonataslaw** [comment]
Could it be clear which dart list API are you talking about?

**Comment by Vladvsemogusch** [comment]
RxList
For example i have rxlist in my controller. In UI i'm building a GridView based on the list through Obx. On gridView item tap i want to change a list item state which in turn will update the grid view through Rx

**Comment by jonataslaw** [comment]
According to your description, you want to change the ownership of an item on the list.
In this case, the list items must be reactive for this change to happen, and you must have an Obx inside and one outside your GridView. One encapsulating the gridview for when the quantity changes (the only thing that matters for a ListView / GridView is the lenght property, regardless of whether items are changed or not, since only the size of the list affects a ListView / GridView) and another encapsulating the widget that will be changed.

**Comment by Vladvsemogusch** [comment]
That's a lot of obx. Wouldn't it be better if grid view would just react to item replace and not every item listening to corresponding rxlist item each preformance wise?

**Comment by Vladvsemogusch** [comment]
I wrapped each grid view item in obx and when i do 
`model.property = true; `
it doesnt rebuild. But it started rebuilding items when scrolled when I scroll to middle and return to start of the list it rebuilds items it has already built.

**Comment by Vladvsemogusch** [comment]
Ok, i figured i need to reassign it whole 
```
Rxlist<Rx<Model> list;
list[5].value = list[5].value.copyWith(property1: 42);
```
Then it works. Not very elegant though.

**Comment by Vladvsemogusch** [comment]
Also why Rx<E> doesn't have notify method?

**Comment by jonataslaw** [comment]
> model.property = true;



> I wrapped each grid view item in obx and when i do
> `model.property = true; `
> it doesnt rebuild. But it started rebuilding items when scrolled when I scroll to middle and return to start of the list it rebuilds items it has already built.

This will definitely not update a model property.
Either you make a reactive model, or you use the update as in:
https://pub.dev/packages/get#-example-tab-

**Comment by Vladvsemogusch** [comment]
Thank you. I made a model property which I want to listen to reactive instead of the whole model. Now everything works as expected. It's a bit confusing what I want to make reactive. Need some architectural practice :)

**Comment by jonataslaw** [comment]
Over time you understand the dynamics well.
Well, based on your comment, I'm closing this.

**Comment by gurupras** [comment]
Could you please explain how to correctly solve this? I'm running into the same issue and I'm toying with the idea of `RxList<Rx<Cls>>` as well, which doesn't feel right :confused:
