### ISSUE TITLE
The method 'put' isn't defined for the type 'GetImpl'.

### ISSUE THREAD

**Issue by yiss** [jonataslaw/getx#350]
I'm jsut getting started with Get when I try to use : `final GlobalController globalController = Get.put(GlobalController());` I get `The method 'put' isn't defined for the type 'GetImpl'.` any why is that ?

**Comment by jonataslaw** [comment]
Import this: 

`import 'package:get/get.dart';`

Since Get works with separate Containers for routes, state management, and dependency management, if you only import routes, it will not activate dependency injection. If you import "get/get.dart" you will get all functions.

**Comment by yiss** [comment]
Works perfectly, thank you!
