### ISSUE TITLE
Get.offAll with predicate example (not bug)

### ISSUE THREAD

**Issue by evdinursan** [jonataslaw/getx#353]
Hi,

First of all, congratulations and many thanks for this package - it's wonderful and easy to use (at least, after you got a grip of the main features).

Second of all, after implementing an application with default state management, I decided to switch the entire application to the GetX architecture and I think that I reduced the number of the code lines to less then 65% from the initial code-base; more then this, I switched from named navigation to standard navigation in GetX (without names) and everything works great, except one thing (more then sure that this has nothing to do with GetX, but with my limited knowledge - but I thought that maybe this would help someone else also.

So, initially, I had this piece of code:

```
Navigator.pushNamedAndRemoveUntil(context, "/orderConfirmationScreen",
          ModalRoute.withName("/captionScreen"),
          arguments: orderStatus);
```

and then, according to my GetX understanding, it had to be translated to the following piece of code:

`Get.offAll(OrderConfirmationScreen(orderStatus));`

but, I don't understand how to construct the predicate attribute in order to stop the deletion at the CaptionScreen() level - please, take in consideration that I'm not using the the named navigation anymore. 

Thank you very much.
Evdin

**Comment by jonataslaw** [comment]
Hi, in theory this would only work with named routes, but maybe you can explore some Get apis to try this out.
I haven't tested it and I don't know if it works, it's just a guess seeing your code:

```dart
   Get.offAll(OrderConfirmationScreen(orderStatus),
        predicate: (_) =>
            Get.currentRoute == '/${CaptionScreen().runtimeType}');
```

If that doesn't work, I think that maybe only named routes can solve your problem.
If you are using a very old version of Get, this will not work. Please update to the latest or penultimate version before doing this.

**Comment by evdinursan** [comment]
I will test it and I will come back as soon as possible. Many thanks for taking the time to answer my question. Btw - I'm updating your library almost daily :-)

Thank you again.

**Comment by jonataslaw** [comment]
Since it is not a bug description, and there has been no response for a long time, I consider this question to be closed.
For matters that do not involve bugs or feature requests, please look for platform channels as well.
