### ISSUE TITLE
Transition.native not working on android 

### ISSUE THREAD

**Issue by alexkharech** [jonataslaw/getx#354]
**Describe the bug**
Transition.native not working on android 

**To Reproduce**
1. set defaultTransition to Transition.native on GetMaterialApp
2. Go to 'any route'

**Expected behavior**
Native transition for any route

**Flutter Version:**
1.17.5

**Get Version:**
3.2.2

**Describe on which device you found the bug:**
Pixel 3 API 25 (android-x86 emulator)

**Minimal reproduce code**
```dart
GetMaterialApp(
  defaultTransition: Transition.native,
  ...
)
```
or without defaultTransition
```dart
GetMaterialApp(
  ...
)
```

**Comment by jonataslaw** [comment]
Fix on 3.3.0
