### ISSUE TITLE
Obx throw exception when used in dynamic widgets

### ISSUE THREAD

**Issue by Denilson-source** [jonataslaw/getx#360]
when using Obx() in a widget that can be destroyed and recreated like items in a ListView or Tabs it throws a exception after the widget is recreated and have a update on controller.

I looked the memory use in devtools and saw that everytime the widget is destroyed the obxx keep it instance and when recreated obxx create a new instance without dispose the previous.

am i using Obx() somehow wrongly?

> [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4180 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
E/flutter (12450): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (12450): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (12450): #2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4180:12)
E/flutter (12450): #3      Obxx.build.<anonymous closure> (package:get/src/rx/rx_obx.dart:18:63)
E/flutter (12450): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (12450): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (12450): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (12450): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (12450): #8      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (12450): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (12450): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (12450): #11     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (12450): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (12450): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (12450): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (12450): #15     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (12450): #16     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (12450): #17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (12450): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (12450): #19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (12450): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by jonataslaw** [comment]
Hi, you are using "obx" (lowercase) or "Obxx". This api is very very very experimental, and has not been documented because of that.

Use Obx() (capital and only one x)

**Comment by Denilson-source** [comment]
I don't believe that hours searching what was wrong and it was just a lowercase letter. haha

**Comment by agordeev** [comment]
Unfortunately, I get this error with `Obx`widget on `get-5.0.0-beta.36`

`ObserverComponent._safeRebuild` isn't safe :)

<img width="630" alt="Screenshot 2022-03-18 at 11 04 41" src="https://user-images.githubusercontent.com/2883524/158960916-145c1acd-657b-4942-a40c-ee4feb65ed7d.png">
