### ISSUE TITLE
Can we move support to Slack?

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/getx#361]
I know there are already other channels like `Gitter` and `Discord`, but I think these are not very broadly used.
I created a new Slack workspace for GetX. I think Slack is more used than the previous channels.
Of course we need @jonataslaw to be in this Slack too for all our support questions :-)

To sign up go to 

https://communityinviter.com/apps/getxworkspace/getx

Fill in your email and you will get an invite for the Slack workspace.

Of course it is pretty empty at the moment, but all suggestions for sub-channels and integrations are welcome.

If @jonataslaw has other plans to keep the "support" questions away from the Github issues, let me know.

**Comment by jonataslaw** [comment]
Hi Stefan, thank you for that!
I saw your email now and would already answer about it.
I will change the documentation to insert the Slack link you created, and I will enter the WorkSpace to answer your questions there.
Thank you so much for this.

**Comment by jonataslaw** [comment]
I added Slack to the readme today.
Thank you for that!
