### ISSUE TITLE
ControllerItensPedido deleted from memory...

### ISSUE THREAD

**Issue by EccusInformatica** [jonataslaw/getx#362]
```dart
Future<List<Map>> carregarPedido;
var db;

Future<List<Map>> fetchListListaItensPedido() async {
  db = await Connection.instance.db;
  return await db.rawQuery('select * from pedido');
}

class ControllerItensPedido extends GetController {
  static ControllerItensPedido get to => Get.find();
  void atualizarItensPedido() {
    carregarPedido = fetchListListaItensPedido();
    update();
  }
}
```

quando rodo o atualizarItensPedido() duas vezes seguidas...o mesmo apresenta:

 ControllerItensPedido not found. You need call put<ControllerItensPedido>(ControllerItensPedido()) before

na primeira vez está dando um close no Controller...
o que está errado ?????
abraços

**Comment by murilosandiego** [comment]
@EccusInformatica, você está utilizando binding?

**Comment by EccusInformatica** [comment]
nao...

estava usando o navigator para navegar entre telas...
passei a usar o Get.to... e sarou...

**Comment by murilosandiego** [comment]
Dentro do GetMaterialApp defina a propriedade smartManagement: SmartManagement.keepFactory
![image](https://user-images.githubusercontent.com/11686438/87044871-84e0c180-c1cd-11ea-9419-a333df2dd09d.png)

**Comment by Nipodemos** [comment]
vou entender "sarou" como o problema ter sido resolvido
@EccusInformatica mesmo assim vc deveria seguir a dica do @murilosandiego 

Fechando issue
