### ISSUE TITLE
[Question] How to use the sample code?

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#366]
In document we have this sample code snippet:
![image](https://user-images.githubusercontent.com/107820/87217285-0d03ca00-c37a-11ea-9a2f-b55f3e80b6d4.png)

May I know where should I pace the code? Inside a splash screen? Any complete example code? 

Thanks in advance.

**Comment by jonataslaw** [comment]
Please ask questions on the support channels described in the readme.
Github is restricted to issues and requests for resources.

But just to not leave you unanswered, you must have a controller for auth.
How and where will you start this controller, whether inside a splashScreen, or on a home page, in a Binding, that is what you want to choose, just remember to use Get.put (permanent: true) for instances like auth that will stay alive throughout the life cycle of the application.
Closing it
