### ISSUE TITLE
Extension on widgets for obx.

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/getx#367]
**Describe the solution you'd like**
Currently, we have an extension on `Object` so we can make any `Object` observable, is it possible to have an extension on widgets as a shorthand for Obx.
Example:
```dart
Obx(
    () => Text('${counter.val}'),
  );

// becomes

Text('${counter.val}').obx;
```

**Comment by jonataslaw** [comment]
It would be great to do that if the dart allowed it.
With dart, every parameter is serialized into a type the moment you create an instance, then

`Text('${counter.val}') == Text('0'); `

The only form in the Dart universe capable of maintaining types is to insert the instance into a function, so using extensions won't work, and the only way to do that is actually the current one.

**Comment by Prn-Ice** [comment]
Oh, I see, thanks for clarifying.
