### ISSUE TITLE
Ability to obtain the 'tag' set to the GetXController

### ISSUE THREAD

**Issue by nemoryoliver** [jonataslaw/getx#369]
**Is your feature request related to a problem? Please describe.**
I want to obtain the current tag set to the controller but I couldn't find the feature

**Describe the solution you'd like**
I wish I am able to obtain the tag set to the current controller something like Get.currentTag

**Comment by jonataslaw** [comment]
Hi, there is no "current tag" for a controller.
Tags are just a way of differentiating two instances of the same controller.

**Comment by Nipodemos** [comment]
i'm just curious, could you provide a sample case where this would be useful? Since you would need to type manually the tag anyway to get the correct instance from Get.find()

**Comment by jonataslaw** [comment]
Well, in view of the impossibility of this feature, I am closing this.
