### ISSUE TITLE
[Feature Request]: Show progress indicator

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#370]
**Is your feature request related to a problem? Please describe.**
I like the simplicity of showing dialog from the package. I wish to have the similar feature for showing progress indicator.

**Describe the solution you'd like**
I am currently using BotToast for showing progress indicator, and here is how I use it, may be this can be a reference.
dismissFunc = Get.showProgressIndicator();
performLongAsyncProcess().whenComplete( () => dismiccFunc.call() );

Thanks in advance.

**Comment by GoldenSoju** [comment]
Would it be possible to also add the CupertinoActivityIndicator for iOS style support?

Link: [CupertinoActivityIndicator](https://api.flutter.dev/flutter/cupertino/CupertinoActivityIndicator-class.html)

**Comment by luis-cruzt** [comment]
Do you know when is this planned to be released?

**Comment by oleksii-pimenov** [comment]
I have ugly workaround for this. Put CupertinoActivityIndicator inside Visibility in all screens. And with help  of .obs manage it.

**Comment by oleksii-pimenov** [comment]
Or smthing like this
`  showSpiner() {
    return showDialog(
        context: Get.context,
        barrierDismissible: false,
        barrierColor: Colors.transparent,
        builder: (BuildContext context) {
          return Center(
            child: Container(
              child: CupertinoActivityIndicator(
                radius: 15,
              ),
            ),
          );
        });
  }

  hideSpinner() {
    Navigator.of(Get.context).pop();
  }`

**Comment by luis-cruzt** [comment]
I ended up using this package: https://pub.dev/packages/loader_overlay

**Comment by jasonlaw** [comment]
https://pub.dev/packages/flutter_easyloading

**Comment by BobFactory** [comment]
I ended up using something else. Although this adds the loader as a route and `Get.back` could potentially dismiss this. 

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

Route<dynamic>? _dialogRoute;

void showLoadingDialog() {
  /// Another loader is already running now.
  if (_dialogRoute != null) return;

  Get.dialog(
    const Center(child: CircularProgressIndicator()),
    barrierDismissible: false,
    name: "/loading_dialog",
  );

  _dialogRoute = Get.routing.route;
  if (_dialogRoute == null) {
    /// If the route is null, then
  }
}

void hideLoadingDialog() {
  if (_dialogRoute == null) return;

  try {
    Get.removeRoute(_dialogRoute!);
  } catch (e) {
    // Ignored to log. But log it to crashlytics.
  } finally {
    _dialogRoute = null;
  }
}

```
