### ISSUE TITLE
Documentation | Link not proper

### ISSUE THREAD

**Issue by NiranjanShah** [jonataslaw/getx#378]
Link to Route management goes to Dependency Management.

**Comment by Nipodemos** [comment]
I've looked for this error, but i could not find it. In none of the three languages. Could you point specificly where is the typo?

**Comment by NiranjanShah** [comment]
its not a typo, Under topics -> The Three pillars -> Route Management -> In depth Explanation. THIS takes to Dependency Management i/o Route Management.

**Comment by Nipodemos** [comment]
![lg9oLvsh1I](https://user-images.githubusercontent.com/11494727/87460367-278cac00-c5e3-11ea-826c-851bda293287.gif)

i just made that gif, it does lead to the correct page

**Comment by NiranjanShah** [comment]
Oh, sorry, as the line you are clicking is in the end of the Route Management paragraph, the confusion raised.

After in depth explanation and next visible topic is Dependency Management.

**Comment by Nipodemos** [comment]
no problem man, i understand. I'll see if anything can be done to be more intuitive, docs still has a lot to improve

**Comment by Nipodemos** [comment]
since it is solved, closing
