### ISSUE TITLE
Transition is too slow on iOS, also not fluent. 

### ISSUE THREAD

**Issue by ahmedmirza994** [jonataslaw/getx#382]
Route transition from one screen to another screen is too slow and not fluent on iOS.

` Get.to(
![video-to-gif-converter](https://user-images.githubusercontent.com/30725333/87509429-f798e380-c68a-11ea-8714-1a1b1fe6fd13.gif)

          CommentScreen(
            oidTargetEntity: classwork.oid,
            typeCode: 'CW',
            child: buildClassActivityScreenCard(classwork: classwork, withFooterVisible: false),
          ),
        )`

**Comment by jonataslaw** [comment]
Please, read the docs:
https://github.com/jonataslaw/getx#other-advanced-apis

You should set the default transition time if you think it is too slow or too fast.

```dart
GetMaterialApp(
  transitionDuration: Duration(miliseconds: 250), // or other duration than you prefer
  home: Home()
);
```

**Comment by ahmedmirza994** [comment]
@jonataslaw I used transitionDuration but it was not fluent and smooth.

**Comment by jonataslaw** [comment]
> @jonataslaw I used transitionDuration but it was not fluent and smooth.

https://github.com/jonataslaw/getx/blob/master/lib/src/routes/default_route.dart#L326

We use CupertinoTransitions from Flutter, the only thing that is changed is the duration of the transition, and that's it.

**Comment by masewo** [comment]
I experienced the same after migration from get 3.2.0 to get 3.10.2. Although I reduced the transitionDuration to 200 milliseconds it is not as fluent and smooth as it was before.

**Comment by ahmedmirza994** [comment]
@masewo I am still facing this issue, and I don't know why maintainers didn't fix this
