### ISSUE TITLE
Transition.noTransition is not handled in the GetPageRoute class

### ISSUE THREAD

**Issue by gary6lin** [jonataslaw/getx#383]
Hi, the Transition.noTransition is not working so I dig into the source code and found that it is not handled in the buildTransitions method. Where the NoTransition class is defined in default_transitions.dart but not used.

Can you please check into this issue? Thanks

**Comment by jonataslaw** [comment]
I'll fix it, thanks

**Comment by jonataslaw** [comment]
Fix on 3.4.0
