### ISSUE TITLE
TextEditingControllers

### ISSUE THREAD

**Issue by ialameh** [jonataslaw/getx#385]
I have created in my controller a generator for the texteditingcontrollers in the forms as such

```
var textEditingControllers = {};

....

..

 addTextEditingController({String textEditingControllerToken, snapshot}) {
//    textEditingControllers.value.clear();
  print('Adding controller called from $textEditingControllerToken with $textEditingControllers');
    if (textEditingControllers[textEditingControllerToken] == null)  {
      print('fetching new');
      String textValue = snapshot?.info(textEditingControllerToken) ?? ''; // value if obtained correctly and set as initial value in the text field through the controller
    Rx<TextEditingController> textEditingController = new TextEditingController(text: textValue).obs;
    textEditingControllers.putIfAbsent(textEditingControllerToken, () => textEditingController);
      print(textEditingController);
       } 
       
      return textEditingControllers[textEditingControllerToken];
  }
```

and in the textfield I am consuming the controller like this:

`controller: steps.addTextEditingController(textEditingControllerToken: IncomeDetails.AFTERTAXSALARY, snapshot: viewSnapshot).value,
`

where steps is my controller;
IncomeDetails.AFTERTAXSALARY is a String representing the text field
snapshot hold the initial data of the text field (and the controller is successfully updating the initial value)

when changing the value of the text in the controller like:
`
steps.textEditingControllers[textEditingControllerToken].value.text = result;
`

my page does not rebuild (the page is a dialog),

if I exit the dialog and open it again I can see the changes in the text field.

is there anything wrong implementing this controller. I can provide more code if needed

**Comment by jonataslaw** [comment]
Hi, try to use the onChange of your TextField/TextFormField and change the value from an RxString.
I think that using `Rx<TextEditingController>` will not work in any way, because it is a kind of reactive Controller that uses ValueNotifier, so you are not accessing or accessing its value directly.

**Comment by ialameh** [comment]
thank you, I will try that

**Comment by ialameh** [comment]
Here how it worked:
1- no observer (.obs)

in my controller :

```

var textEditingControllers = {};

.....
 addTextEditingController({String textEditingControllerToken, snapshot}) {
    if (textEditingControllers[textEditingControllerToken] == null)  {
      print('fetching new');
      String textValue = snapshot?.info(textEditingControllerToken) ?? ''; // value if obtained correctly and set as initial value in the text field through the controller
   TextEditingController textEditingController = new TextEditingController(text: textValue);
    textEditingControllers.putIfAbsent(textEditingControllerToken, () => textEditingController);
      print(textEditingController);
       } 
       
      return textEditingControllers[textEditingControllerToken];
  }


``` 

for each text field i am creating a controller at the time of building unless it does exits I am assigning its value

In page one, I am consuming the controller 

`controller: steps.addTextEditingController(textEditingControllerToken: IncomeDetails.AFTERTAXSALARY, snapshot: viewSnapshot).value,`

and requesting another page to do some calculations and send back a new value for the controller
`
GeneralDialog.show(child: PaymentFrequencyCalculator(IncomeDetails.FAMILYTAXBENEFIT));},
`

(A customised dialog the uses get from within it)

In the payment calculator, I am making updates on the controller
`
                      steps.textEditingControllers[textEditingController].text = result;
`

so this way I am able dynamically to create controllers and use them using a text value for each field.

last thing I am disposing the controllers by

      dispose: (temp) {
        steps.textEditingControllers.clear();
      },

**Comment by jonataslaw** [comment]
Okay, can I close then?
