### ISSUE TITLE
Performing Artithmetic on two obs variables

### ISSUE THREAD

**Issue by TJMusiitwa** [jonataslaw/getx#387]
I could potentially be approaching this in the wrong way however, I would like to seek clarity as to what I seem to be doing wrong.
_(Sorry to be using the bug request template to post this issue as there is no other template outside the 2 options and it is better to post it as a bug than a feature request😁)_

My initalised variables are as follows;
```dart
static var ticketType = ['Single', 'Daily', 'Weekly', 'Monthly'];
  RxList ticketValueList = [1300, 3500, 18000, 55000].obs;
  final type = RxInt();
  final RxDouble _ticketQuantity = 1.0.obs;
  var _ticketValue = RxInt();
  int get ticketCost => _ticketQuantity.value.toInt() * _ticketValue.value;
```

Used one of the variables to wire up my FilterChip in the following way;

```dart
Obx(
              () => Wrap(
                spacing: 6,
                runSpacing: 4,
                children: List<Widget>.generate(
                    ticketType.length,
                    (index) => FilterChip(
                          label: Text(ticketType[index]),
                          selected: type.value == index,
                          onSelected: (value) {
                            _ticketValue.value = value
                                ? ticketValueList.elementAt(index)
                                : ticketValueList.first;
                            type.value = value ? index : 0;
                            print(_ticketValue.value);
                          },
                        )),
              ),
            ),
```
Works no problem.

Then my slider was wired up as follows and works just as expected;

```dart
Obx(
              () => Slider.adaptive(
                  label: _ticketQuantity.value.toInt().toString(),
                  max: 10.0,
                  divisions: 10,
                  value: _ticketQuantity.value,
                  onChanged: (newValue) {
                    _ticketQuantity.value = newValue;
                    print(_ticketQuantity.value);
                  }),
            ),
```

My dilemma is that even after following the documentation in the #reactive-programming section from pub.dev attempting the multiplication of the two values`(with the int get ticketCost)` is not possible and returns an error **(unless I comment the ticketCost initialiser)** when trying to use it in my final text widget to output the value

```dart
Text(
                  "Ush.${ticketCost.toString()}",
                  style: Get.textTheme.headline3,
                ),
```

Please advise what I should change and what I should keep in mind to avoid such a problem from happening in the future.

**Comment by jonataslaw** [comment]
It looks like you're trying to multiply null values.
Dart is heading to be nullsafety, try to use variable.obs as much as you can, so that you won't have any breaks when the dart doesn't allow any more null values.

var _ticketValue = RxInt(0);
or 
var _ticketValue = 0.obs;

**Comment by TJMusiitwa** [comment]
Okay then, I will attempt this fix tomorrow(4 am where I live) and either update you or close the issue.
Thank you

**Comment by TJMusiitwa** [comment]
Thank you.. That worked out well for me...
