### ISSUE TITLE
Add some kind of "transitions" concept on Controllers

### ISSUE THREAD

**Issue by ldasilva-net** [jonataslaw/getx#388]
Hi! 

On others states managements with Reactive Event / Action approach like Redux or Bloc they have the possibility for catch all the state changes (in [bloc](https://bloclibrary.dev) lib they called [Transitions](https://bloclibrary.dev/#/coreconcepts?id=transitions) ) only listening on one specific place. On bloc for example, you can override `onTransition` function on every bloc you have or in a main listener (`BlocObserver`) all state changes for every bloc in your app.
This approach is beatiful for:

- Log / Analytics. You can put all log related logic there and don't mixed with other Business stuff.

- Know all what the user does on the app to replicate a bug for example.

With `Getx` we don't use the Event / Action approach, but, can we make some similar feature without the need of adding an `ever()` worker on all your `.obs` ? 
If `Getx` knows all the Observables fields for a Controller subscribed on a different Widgets, will it not be able to notify on one place (like an Controller function) when every Observable changes value? 

Example:

```dart
class TestController extends GetxController {
  final count1 = 0.obs;
  final count2 = 0.obs("COUNT_2"); // suggested way of add an constant name to a property

  @override
  void onTransition(GetxTransition transition) {
    // stuff
    /*
      transitions examples      

      Example 1
      {
        "property": "count1",
        "currentValue": 0,
        "nextValue": 1
      }

      Example 2
      {
        "property": "COUNT_2",
        "currentValue": 0,
        "nextValue": 1
      }
    */
    
  }

}
```

**Comment by jonataslaw** [comment]
This monolithic approach is possible, but this library is in a phase of reducing globals, and increasingly focusing on individual controls.
In the short term, I'm not sure I want to implement this, but a new Worker called "everAll" is in the testing phase, so it might be useful for you.
You will still need to manually add all the variables you want to listen in the list, but at least you will not have 40 "ever" on one screen.
I understand that approaches from other libs that had their rise phase years ago can make the migration process easier, but some things just don't quite match the GetX philosophy.

As much as it is useful to hear all variables from a controller, this would generate additional overhead if you have 50 variables, but you only need to listen to 5. So I think everAll will be as close as you will get to such a resource.

**Comment by ldasilva-net** [comment]
I understand... I'll be aware of the new worker `everAll` when released. 
Thanks @jonataslaw !

**Comment by jonataslaw** [comment]
everAll added on lastest version
