### ISSUE TITLE
Extensions structure update

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [jonataslaw/getx#389]
**Is your feature request related to a problem? Please describe.**
Saw there is just one file called extensions.dart. Putting all in one file may be hard to read as it increases

**Describe the solution you'd like**
I can PR create a directory named extensions and inside can have extensions according to its type like string.dart, double.dart, context.dart, orientation.dart and so on.

**Describe alternatives you've considered**
I will send a PR

**Comment by WilliamCunhaCardoso** [comment]
@jonataslaw but tell me what do you think about it

**Comment by jonataslaw** [comment]
Go ahead, you will be very welcome.

**Comment by jasonlaw** [comment]
> **Is your feature request related to a problem? Please describe.**
> Saw there is just one file called extensions.dart. Putting all in one file may be hard to read as it increases
> 
> **Describe the solution you'd like**
> I can PR create a directory named extensions and inside can have extensions according to its type like string.dart, double.dart, context.dart, orientation.dart and so on.
> 
> **Describe alternatives you've considered**
> I will send a PR

@WilliamCunhaCardoso when you are working on the string extension, could you pls adding the isNullOrBlank to it? There is already an existing one in GetUtils but not being extended for string data type. Thanks.

**Comment by WilliamCunhaCardoso** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > Saw there is just one file called extensions.dart. Putting all in one file may be hard to read as it increases
> > **Describe the solution you'd like**
> > I can PR create a directory named extensions and inside can have extensions according to its type like string.dart, double.dart, context.dart, orientation.dart and so on.
> > **Describe alternatives you've considered**
> > I will send a PR
> 
> @WilliamCunhaCardoso when you are working on the string extension, could you pls adding the isNullOrBlank to it? There is already an existing one in GetUtils but not being extended for string data type. Thanks.

Done :)

**Comment by WilliamCunhaCardoso** [comment]
Actually I don't even added it on String itself. I guess it was an export problem (as I modified it, maybe now it is fixed). I created a test for it and it is okay. You can check the PR. It is on WIP because I'm implementing tests on it. But feel free to dive feedbacks

**Comment by jonataslaw** [comment]
Closed by https://github.com/jonataslaw/getx/pull/393
