### ISSUE TITLE
Help - best approach to check authentication.

### ISSUE THREAD

**Issue by niypoo** [jonataslaw/getx#392]
I'm using provider and I'm able to call providerchangenotifer before material widget and able to handle if a user is auth or not to redirect him to which page , in GetX I can't wrap the GetMaterial by GetBuild as example so how can check auth state from controller and redirect !!

Is wrap route page by Getbuild is normal way !!?

**Comment by niypoo** [comment]
```.          
 GetPage(name: '/', page: () => GetBuilder<AuthenticationController>(builder: (authenticationController)=> authenticationController.isAuth ? HomePage() : AuthenticationPage()) , binding: HomeBinding()),
```

**Comment by Nipodemos** [comment]
this will not work because Get Builder would need to call update() somewhere

is this `uthenticationController.isAuth` async? if it's not, you can simply remove GetBuilder and it should work

```dart
GetPage(
    name: '/', 
    page: () { 
        final authenticationController = AuthenticationController();
        return (
            authenticationController.isAuth 
            ? HomePage() 
            : AuthenticationPage(),
        )
    ),
    binding: HomeBinding(),
),
```

to be honest i think it is not a good approach yet, but i don't know better, but i know there is better options

maybe @jonataslaw have a better way of doing this

**Comment by niypoo** [comment]
> this will not work because Get Builder would need to call update() somewhere
> 
> is this `uthenticationController.isAuth` async? if it's not, you can simply remove GetBuilder and it should work
> 
> ```dart
> GetPage(
>     name: '/', 
>     page: () { 
>         final authenticationController = AuthenticationController();
>         return (
>             authenticationController.isAuth 
>             ? HomePage() 
>             : AuthenticationPage(),
>         )
>     ),
>     binding: HomeBinding(),
> ),
> ```
> 
> to be honest i think it is not a good approach yet, but i don't know better, but i know there is better options
> 
> maybe @jonataslaw have a better way of doing this

yup I catch it  in document it's 
```
onInit(){
  ever(isLogged, fireRoute);
  isLogged.value = await Preferences.hasToken();
}

fireRoute(logged) {
  if (logged) {
   Get.off(Home());
  } else {
   Get.off(Login());
  }
}

```
but I put fireRoute content in `scheduleBiding.instance.addPostFrameCallback`  to avoid call named route on null

**Comment by jonataslaw** [comment]
> > this will not work because Get Builder would need to call update() somewhere
> > is this `uthenticationController.isAuth` async? if it's not, you can simply remove GetBuilder and it should work
> > ```dart
> > GetPage(
> >     name: '/', 
> >     page: () { 
> >         final authenticationController = AuthenticationController();
> >         return (
> >             authenticationController.isAuth 
> >             ? HomePage() 
> >             : AuthenticationPage(),
> >         )
> >     ),
> >     binding: HomeBinding(),
> > ),
> > ```
> > 
> > 
> > to be honest i think it is not a good approach yet, but i don't know better, but i know there is better options
> > maybe @jonataslaw have a better way of doing this
> 
> yup I catch it in document it's
> 
> ```
> onInit(){
>   ever(isLogged, fireRoute);
>   isLogged.value = await Preferences.hasToken();
> }
> 
> fireRoute(logged) {
>   if (logged) {
>    Get.off(Home());
>   } else {
>    Get.off(Login());
>   }
> }
> ```
> 
> but I put fireRoute content in `scheduleBiding.instance.addPostFrameCallback` to avoid call named route on null

This is the recommended approach for when the token is not in GetStorage, just change onInit to onReady to avoid the route being called with null.

If in doubt of use, please check the community's communication channels instead of opening an issue, they are appropriate for this.
Once that has been answered, I am closing.
