### ISSUE TITLE
Get.to() doesn't navigate to the another instance of current active widget

### ISSUE THREAD

**Issue by StasKalishenko** [jonataslaw/getx#395]
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
Current version of "get" (v.3.3.0) doesn't navigate to the same widget. I mean, if you open MyPage() and try to open another instance of MyPage(), using Get.to(MyPage()), nothing happens. And it works fine on "get" v.2.14.1 (we used it before).
I'm not sure what version of "get" broke it, but I reproduced it on v.3.2.0 and 3.3.0.

**To Reproduce**
1. Create default Flutter project
2. In pubspec.yaml add "get" package:
`get: ^3.3.0`
2. In main.dart replace MaterialApp() with GetMaterialApp()
3. Create new widget like this:
```
class MyPage extends StatelessWidget {

  MyPage({Key key}) : super(key: key);

  void _openPage() {
    var widget = MyPage();
    Get.to(widget);
  }

   @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(UniqueKey().toString()),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => this._openPage(),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```
4. In _MyHomePageState on onPressed() of floatingActionButton do the following:
`Get.to(MyPage());`
5. Run the app.
6. Tap the "floatingActionButton" several times.

Actually, after tap MyPage is opening, but only once. Next taps do nothing.

**Expected behavior**
Tap on "floatingActionButton" should open page but with different title.

**Flutter Version:**
1.17.5

**Get Version:**
3.3.0

**Describe on which device you found the bug:**
It was found on iPhone Xr (real device) and Android emulator (Pixel 3a (API 29))

**Minimal reproduce code**
Here is the full code:
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void _openPage() {
    var widget = MyPage();
    Get.to(widget);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => this._openPage(),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class MyPage extends StatelessWidget {

  MyPage({Key key}) : super(key: key);

  void _openPage() {
    var widget = MyPage();
    Get.to(widget);
  }

   @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(UniqueKey().toString()),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => this._openPage(),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by jonataslaw** [comment]
Hi, this is Get's security system to prevent double clicks from taking people to duplicate pages.
You can change this behavior by adding this to your Get.to:
`preventDuplicates:false`

**Comment by StasKalishenko** [comment]
Thank you. It works fine with `preventDuplicates:false`, but it's not obvious. It would be great to see it in documentation.
