### ISSUE TITLE
InitialBinding not working

### ISSUE THREAD

**Issue by ialameh** [jonataslaw/getx#398]
I have created several controllers and I wanted to use initialbinding so I did the following:

My bindings file

```
class AppBindings extends Bindings {
  @override
  dependencies() {
    print('printing from bindings');
    Get.lazyPut<AuthenticationService>(() => AuthenticationService());
    Get.lazyPut<StorageRepo>(() => StorageRepo());
    Get.lazyPut<DatabaseDao>(() => DatabaseDao());
  }
}

```

My main:

```

main()  {
  WidgetsFlutterBinding.ensureInitialized();

  try {
//    await getServices();
    runApp(LifeArms());
  } catch (e) {
//  print(e);
  }
}

class LifeArms extends StatelessWidget {
  // This widget is the root of your application.
  final AppDatabase appDatabase = Get.put<AppDatabase>(AppDatabase.instance);

  static final Rx<Database> dbInstance = Rx<Database>();

  @override
  Widget build(BuildContext context) {
    AppDatabase.instance.database.then((value) {
      return dbInstance.value = value;
    });

//  print('going into repo now');
        return GetMaterialApp(
//          smartManagement: SmartManagement.keepFactory,
          initialBinding: AppBindings(),
          title: 'Life Arms',
          theme: ThemeData(
            appBarTheme: AppBarTheme(
              iconTheme: IconThemeData(
                color: AppColors.accentText,
              ),
              color: AppColors.accentText,
            )
          ),
          initialRoute: HomeScreen.id,
          getPages: [
            ...pages
          ],
          home: HomeScreen(),
        );
  }
}


```

AppDatabase is being initialised without a problem, however the GetMaterialApp is not stepping into the AppBindings, is there anything wrong with the way I am putting this?

if I put 
```

  Widget build(BuildContext context) {
    AppDatabase.instance.database.then((value) {
      return dbInstance.value = value;
    });
  AppBindings().dependencies();
//  print('going into repo now');
        return GetMaterialApp(
//          smartManagement: SmartManagement.keepFactory,
//          initialBinding: AppBindings(),
          title: 'Life Arms',
          theme: ThemeData(
```

it works,

**Comment by jonataslaw** [comment]
InitialBinding works properly, what may be preventing you from using it, is your code having:
`home: Home();`

By the time MaterialApp is created, `Home()` has already been created, because in the dart every object is created before being sent by parameter unless it is inside a function.
In July 2020 I do not recommend using `home` anymore unless you do not depend on anything to initialize it, this is a problem that named routes have come to solve.

In most internationalization libraries, using home can prevent your application from being properly updated with a new language, and all this is because updating the parent (MaterialApp) does not necessarily mean updating the child.
GetPages is preferable.

**Comment by Nipodemos** [comment]
maybe some dependency you want to put is async? if it is you need to use `Get.putAsync()`

other thing: when you are using named routes, you don't need the `home:` parameter in the GetMaterialApp, just the the `initialRoute:` (which you alredy put) and it will show your HomeScreen

**Comment by jonataslaw** [comment]
Please:
1- Remove this: 
`home: HomeScreen(),`

2- Remove this:

```dart
    AppDatabase.instance.database.then((value) {
      return dbInstance.value = value;
    });
```
3- Remove this:

```dart
  final AppDatabase appDatabase = Get.put<AppDatabase>(AppDatabase.instance);

  static final Rx<Database> dbInstance = Rx<Database>();
```

Now:

```
main() async  {
  WidgetsFlutterBinding.ensureInitialized();
  final instance = await AppDatabase.instance.database;
  Get.put(instance);

```

Take your database instance with Get.find<Database>()

**Comment by joanofdart** [comment]
That's a bit of a code smell @jonataslaw, like I wrote in another thread, bindings sound as methods that should be doing that. It defies the purpose to have a binding that it ain't called before anything else imho.
What do you think?

**Comment by ialameh** [comment]
I have removed  home:HomeScreen() (was stupid mistake) and that fixed the initialBinding thing
Once initialBinding fixed, I moved the database  instance in to the AppBinding

    ```
final instance = await AppDatabase.instance.database;
    Get.put<AppDatabase>(AppDatabase.instance);
```
inside the AppDatabase class, I added



```
  static final Rx<Database> dbInstance = Rx<Database>();

  @override
  void onReady() async {
    Get.find<AppDatabase>().database.then((value) => dbInstance.value = value);
  }
```

with that done everything went smooth, 
if you feel this is correct, I am happy that you close this,

thank you so much for the support and such a great package

Sam

**Comment by jonataslaw** [comment]
Glad to know that you could solve your problem.
Closing it.
