### ISSUE TITLE
How To rebuild stateLessWidget when soft keyboard open

### ISSUE THREAD

**Issue by niypoo** [jonataslaw/getx#400]
I have a StatelessWidget that has a textField , I want change  AnimatedContainer height when user tap on textField to make textField show in top soft Keyboard 

but when tap on TextField the widget not rebuild what is wrong !

```
class CreateView extends StatelessWidget {

  final Size size = Get.mediaQuery.size;
  double softKeyboard = Get.mediaQuery.viewInsets.bottom ?? 0.0;

 @override
  Widget build(BuildContext context) {

return AnimatedContainer(
          height: 120 + softKeyboard,
        child:TextEditor
)

}

```

**Comment by jonataslaw** [comment]
Hi, Get.mediaQuery.size and Get.mediaQuery.viewInsets.bottom are immutables. 
Use context extensions:
context.mediaQuery rather Get.mediaQuery

**Comment by niypoo** [comment]
Thanks It's working
