### ISSUE TITLE
Feature/Bug Roadmap

### ISSUE THREAD

**Issue by joanofdart** [jonataslaw/getx#402]
I know I'm skipping through everything I should be writing but bear with me on this one.
- It would be amazing if we could see a Roadmap of what's next. I know @jonataslaw that you're alone on this, we are all thankful for your dedication and passion!

**Comment by joanofdart** [comment]
@jonataslaw @Nipodemos 
This was published on July 19.
What if we actually have a feature roadmap?

The way I see it right now is... "whatever is on our mind, goes in".

**Comment by jonataslaw** [comment]
I usually share on community channels what the next steps will be.
I have no plans to make a roadmap, but I will insert at least one list for the main features, and an estimate of when they will be ready

**Comment by joanofdart** [comment]
That's something at least : )

**Comment by jonataslaw** [comment]
However, I already say that until the Stable version of the CLI is released, the new features are only available to be voted on, and those with the most likes will be implemented first after the launch of the CLI.
She is a priority at the moment because of some other releases that involve her.

**Comment by Nipodemos** [comment]
i put that CLI feature on the high priority of the board, you guys can see [here](https://github.com/jonataslaw/getx/projects/1)

**Comment by Nipodemos** [comment]
i guess this issue can be closed now ❤️
