### ISSUE TITLE
error in Obx Example when you turn off the connection.

### ISSUE THREAD

**Issue by TheGhostDevlopper** [jonataslaw/getx#404]
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
error in Obx Example when you turn off the connection.
════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building Obx(dirty, state: _ObxState#12bfb):
The getter 'totalConfirmed' was called on null.
Receiver: null
Tried calling: totalConfirmed

The relevant error-causing widget was
    Obx 
package:get_state/…/views/home_view.dart:26
When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      HomePage.build.<anonymous closure> 
package:get_state/…/views/home_view.dart:41
#2      _ObxState.notifyChilds 
package:get/…/rx/rx_obx.dart:56
#3      _ObxState.build 
package:get/…/rx/rx_obx.dart:72
#4      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4648

**To Reproduce**
1. Go to 'setting and turn off internet connection'
2. recompile the app and you will get the error , 

**Expected behavior**
it's seem that Obx.value are not null and I don't know why ...
**Flutter Version:**
1.7.3

**Get Version:**
3.3

**Describe on which device you found the bug:**
Android

**Minimal reproduce code**
check the example in the package of get

**Comment by Amanvein** [comment]
i have a same issue
