### ISSUE TITLE
snackbar

### ISSUE THREAD

**Issue by mhmd15881** [jonataslaw/getx#410]
**Describe the solution you'd like**

snackbar title & message text styling font family etc.
snackbar alignment right to left for Arabic etc.

**Comment by jonataslaw** [comment]
For text style you can use the Flutter widget itself.
RTL text style is the responsibility of the dev who will implement it, this is totally outside the scope of Getx.
```dart
 Get.rawSnackbar(
                titleText: Text('text'), messageText: Text('message'));
```

**Comment by maltub9** [comment]
getx.Get.snackbar(
                                                  "", "",
                                                  titleText: globals.createText(
                                                      "ملاحظة", 12,
                                                      textAlign:
                                                          TextAlign.right), //
                                                  messageText:
                                                      globals.createText(
                                                          "تم الغاء الانتساب",
                                                          12,
                                                          textAlign:
                                                              TextAlign.right),
                                                  backgroundColor: Colors.green,
                                                );
