### ISSUE TITLE
Get.textTheme is immutable

### ISSUE THREAD

**Issue by IAFung** [jonataslaw/getx#411]
If i set `Text("this is a message", style: Theme.of(context).textTheme.headline6)`,
When I click to switch theme, the text will change state, but when I set it to `Text("this is a message", style: Get.textTheme.headline6)`,
When, clicking to switch themes does not work.
**Flutter Version:**
1.17.5

**Get Version:**
3.3.0

**Describe on which device you found the bug:**
iPhone 11 Pro Max Simulator

**Minimal reproduce code**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(
    GetMaterialApp(
      debugShowCheckedModeBanner: false,
      theme: AppTheme.normalTheme,
      home: TestView(),
    ),
  );
}

class TestView extends StatelessWidget {
  const TestView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
             //does not work
            // Text("this is a message", style: Get.textTheme.headline6),
            //work
            Text("this is a message",
                style: Theme.of(context).textTheme.headline6),
            RaisedButton(
              onPressed: () => Get.changeTheme(AppTheme.otherTheme),
              child: Text("Change Theme"),
            )
          ],
        ),
      ),
    );
  }
}

class AppTheme {
  static ThemeData normalTheme = ThemeData(
      textTheme: TextTheme(
          headline6: TextStyle(
              fontSize: 30, fontWeight: FontWeight.bold, color: Colors.pink)));
  static ThemeData otherTheme = ThemeData(
      buttonTheme: ButtonThemeData(buttonColor: Colors.green),
      canvasColor: Colors.amber,
      textTheme: TextTheme(
          headline6: TextStyle(
              fontSize: 15, fontWeight: FontWeight.bold, color: Colors.green)));
}
```

**Comment by jonataslaw** [comment]
Your code:
![Screen Capture_code-oss_20200721013912](https://user-images.githubusercontent.com/35742643/88013555-136d1100-caf3-11ea-87e5-bb9f33f8c61a.gif)

**Comment by jonataslaw** [comment]
From what I could see, and even testing with your code, everything works fine.
If you think there is a bug, please provide a reproduction case, or mention what the problem is in this video.
I recommend using flutter clean before building a project, sometimes caching old versions can cause strange behavior.

**Comment by IAFung** [comment]
```
 //does not work
            // Text("this is a message", style: Get.textTheme.headline6),
            //work
            Text("this is a message",
                style: Theme.of(context).textTheme.headline6),
```
if i use `Text("this is a message", style: Get.textTheme.headline6)` , it does not work. I don't want to use `context`,😁

**Comment by jonataslaw** [comment]
Thanks for the explanation, now I understand.
Get.context is immutable, so everyone else that inherits from it is also, like MediaQuery, Theme, etc. are also.
There are context extensions for some of these functions, I don't remember if you have textTheme, but I'll add that in the next update if I don't.

**Comment by jonataslaw** [comment]
context.theme added on 3.4.1

**Comment by PhamQuocHuy98** [comment]
@jonataslaw  I use context.theme to change theme but it rebuild widget many times. If I use Get.textTheme.headline6 and define style it does not work.
<img width="686" alt="Screenshot 2020-09-21 at 10 23 14" src="https://user-images.githubusercontent.com/29661199/93730804-7878dc00-fbf4-11ea-8d01-cd5f27408df8.png">
