### ISSUE TITLE
Move GetDynamicUtils extension out of the get.dart import 

### ISSUE THREAD

**Issue by roipeker** [jonataslaw/getx#414]
**Is your feature request related to a problem? Please describe.**
All those methods over dynamic type bloats the autocompletion hinting for any classType in most IDEs. 

**Describe the solution you'd like**
Maybe, don't export `'src/regex/get_utils_extensions.dart'`; in utils.dart directly to avoid exporting it with get.dart

**Describe alternatives you've considered**
Manually hide the import...  `import 'package:get/get.dart' hide GetDynamicUtils;`

**Comment by jonataslaw** [comment]
In the latest version, only the most useful extensions are listed.
Thanks
