### ISSUE TITLE
Navigator popUntill() Equivalent needed. 

### ISSUE THREAD

**Issue by manojeeva** [jonataslaw/getx#417]
**Is your feature request related to a problem? Please describe.**
Navigator popUntill method is used to just pop routes from the stack.
In Get offNamedUntill or offNamed or back or offAllNamed are removing some routes and pushing a new route to stack.
What if we need to only pop a few routes from the stack?

**Describe the solution you'd like**
We can have the same as the Navigator popUntill method to remove some routes.

**Describe alternatives you've considered**
 ```Navigator.of(context).popUntil((route) => route.settings.name == '/two');```
current flow
``` Get.offNamedUntil("/two", (route) => route.settings.name=='/two'); ```
changed to 
```     Get.offNamedUntil((route) => route.settings.name=='/two',optional(newroute)); ```
offNamedUntill method can be used. the predicate should be the first argument and 'newrouteName' should be optional If 'newrouteName'  is not supplied we can simply pop the routes using predicate

**Comment by jonataslaw** [comment]
Get.until();

**Comment by manojeeva** [comment]
> Get.until();
Thanks.
 Is it mentioned in doc or readme file? It will be nicer to see all the functionalities.
Can you refer to something to check all the functionality?

**Comment by Nipodemos** [comment]
@manojeeva yes is is 😄 
![image](https://user-images.githubusercontent.com/11494727/88300328-baab9d00-ccd9-11ea-855e-6ec03b0ea86a.png)

you can also type the method in vscode and read the docs about the method
![image](https://user-images.githubusercontent.com/11494727/88300791-41f91080-ccda-11ea-863b-36e6b948b34c.png)

i just noticed that there is an typo in docs,😅
