### ISSUE TITLE
tried to dispose texteditingcontroller on onClose, got TextEditingController was used after being disposed

### ISSUE THREAD

**Issue by cahyowhy** [jonataslaw/getx#420]
I tried to dispose texteditingcontroller on onClose method getxcontroller and got an error message
`A TextEditingController was used after being disposed.`. It seems the error was shown if i move to another screen.

Tried to wrap dispose method with future.delayed sometimes work
```
@override
  onClose() {
    super.onClose();
    try {
      Future.delayed(Duration(milliseconds: 351))
          .then((value) => pageController.dispose());
    } catch (e) {
      print(e);
    }
  }
```
And also it seems the dispose issue was not only on texteditingcontroller but also on scrollcontroller & pageController..

**Comment by jonataslaw** [comment]
What version of GetX are you using? Upgrade to the latest version, because this appears to be the behavior of old updates.
Please, when opening a bug, follow the bug creation report, or the issue will be closed.

**Comment by cahyowhy** [comment]
get: ^3.2.2

**Comment by jonataslaw** [comment]
This was fixed a long time ago, please update to the latest version, and the next time you open an issue, follow the model, it saves a lot of time.
Closing here.

**Comment by KeepFish** [comment]
@jonataslaw  Sorry, I had same issue in latest version.
get: ^3.4.0
Dart Version: 2.8.4
Page code: 
```
class SecondPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    final c = Get.put(SecondController());

    return Scaffold(
      appBar: AppBar(
        title: Text('SecondPage'),
      ),
      body: TextField(
        controller: c.con,
      )
    );
  }
}

```
SecondController:
```
class SecondController extends GetxController {

  MyTextEditingController con = MyTextEditingController();

  @override
  void onClose() {
    print('SecondController onClose');
    super.onClose();
  }
}

class MyTextEditingController extends TextEditingController {
  @override
  void dispose() {
    print('MyTextEditingController dispose');
    super.dispose();
  }
}
```
**Describe the bug:**
Push in SecondPage and pop back.
- `MyTextEditingController` `dispose` method doesn't called.
- When I call dispose in onClose like
```
@override
  void onClose() {
    con.dispose();
    print('SecondController onClose');
    super.onClose();
  }
```
`dispose` method called, but an exception throw.

```
flutter: The following assertion was thrown while finalizing the widget tree:
flutter: A MyTextEditingController was used after being disposed.
flutter: Once you have called dispose() on a MyTextEditingController, it can no longer be used.
```

But when I use `delay` is fine.
```
@override
  void onClose() {
    try {
      Future.delayed(Duration(milliseconds: 1))
          .then((value) => con.dispose());
    } catch (e) {
      print(e);
    }
    print('SecondController onClose');
    super.onClose();
  }
```
Do I have to do this?
Hope to get answer. Thanks.

**Comment by ruziyi** [comment]
I got the same error.

**Comment by bajajsahil** [comment]
@KeepFish I think you need to re-open the issue to make it visible to @jonataslaw.
