### ISSUE TITLE
update() ignored on GetX.

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/getx#429]
**Describe the bug**
I have a simple `GetxController` that runs a function `onInit` changes some data and the UI responds. When I use this with `GetBuilder` it works just fine but with `GetX` it almost seems as if the final `update()` call is ignored and the UI is not rebuilt.

**To Reproduce**
Try out the code snippet below.

**Expected behavior**
Same result from `GetX` and `GetBuilder`.

**Screenshots**
With GetBuilder:
![getbuilder](https://user-images.githubusercontent.com/48252841/88727089-d45c4280-d126-11ea-8606-a0be7eff91a7.gif)

With GetX:
![getx](https://user-images.githubusercontent.com/48252841/88727128-e5a54f00-d126-11ea-85a1-e3ee17b59a9d.gif)

**Flutter Version:**
1.17.3

**Get Version:**
3.4.1

**Minimal reproduce code**
```dart
class TestViewModel extends GetxController {
  String data = '';

  final RxString val = 'Hilo'.obs;

  bool loading = false;

  void setLoading(bool value) {
    loading = value;
    update();
  }

  @override
  Future<void> onInit() async {
    setLoading(true);
    data = await _fakeFetch();
    setLoading(false);
  }

  Future<String> _fakeFetch() async {
    await Future.delayed(Duration(seconds: 2));
    return 'Done';
  }
}
```

```dart
class TestView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetX<TestViewModel>(
      init: TestViewModel(),
      builder: (_) => Scaffold(
        appBar: AppBar(
          title: Text('${_.val.value} This is a test'),
        ),
        body: Container(
          child: Center(
              child:
                  _.loading ? CircularProgressIndicator() : Text('${_.data}')),
        ),
      ),
    );
  }
}
```

**Comment by jonataslaw** [comment]
Use MixinBuilder, Not GetX. 
GetX is only for Reactive State Manager.

**Comment by Prn-Ice** [comment]
Completely forgot about that thanks.
