### ISSUE TITLE
Default translation fallback

### ISSUE THREAD

**Issue by nemoryoliver** [jonataslaw/getx#430]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Hi Jonny,

Once again, thanks for your super awesome work on **Get**! I have been using it for my apps now and works awesome so far. My only wished feature right now is the ability to set a fallback translation.

Example I have these:

```
en_US = {'hi': 'Hi', 'hello': 'Hello there'}
es_ES = {'hi': 'Hola'}
```

 but **es_ES** does not have the 'hello' key. so if I use `'hello'.trArgs()` I wish that i will be able to return the fallback from the default **en_US** which is equal to **'Hello there'**. Right now the default behavior is that it will return the **key** `String` which is **'hello'**

**Comment by jonataslaw** [comment]
Added on https://github.com/jonataslaw/getx/pull/438
Thanks!
I'm closing this.

**Comment by nemoryoliver** [comment]
Thank you very much!
