### ISSUE TITLE
Custom translation trArgs() %s parameter

### ISSUE THREAD

**Issue by nemoryoliver** [jonataslaw/getx#432]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
I wish we are able to customize the **%s argument** to what we want. I use a Google Translate service and using **%s** causes problems when translating so I wish we are able to replace it with something like **@s**

**Comment by jonataslaw** [comment]
Sorry, you will have to use replace if you want to change the arguments.
I can't use @, because that would cause problems for functions like mentions and% s is a standard, so the problem is not with Getx but with its external service.

**Comment by nemoryoliver** [comment]
I understand. I think you're right. Thanks a lot!
