### ISSUE TITLE
docs in flutter.dev is outdated

### ISSUE THREAD

**Issue by Nipodemos** [jonataslaw/getx#434]
Since this is not a problem with get itself the template does not apply.

so, i visited today https://pub.dev/packages/get , and i noticed that is still with the old format where all documentation was in only one file, this is weird, can you take a look later on how to make flutter.dev up to date with github? @jonataslaw

**Comment by jonataslaw** [comment]
As there are no pages on pub.dev, like on github, I thought about leaving all the resources there, I still don't know if it's a good idea, but I have kept it that way for people to read extensively.
We need to discuss this.

**Comment by Nipodemos** [comment]
The idea on the readme in pub.dev is more to make a good first impression and to explain briefly what the package can do and why would the person want to install. In my opinion it should be as small as possible with a little bit of all that get can do. 
Take for example [Redux](https://pub.dev/packages/redux). It is a package that is very big, and yet their readme is small with links to larger documentations. 

We can have the argument that having all there helps to know that the package has a lot to offer, but i don't know if it is worth it

**Comment by Prn-Ice** [comment]
Its a lot harder to read when its one big file, I remember my first time, I got lost on occasion.

**Comment by jonataslaw** [comment]
Okay, I will accept this. Maybe I will remove the corona virus example, and leave just a standard example, leaving the link to GetxCommunity.
The example "counter" application will also be redone, to look like a "step by step".
The short syntax is already noticeable in the "Flutter made easy" banner, and there you can get a good idea of what the app offers.
I intend to include somewhere, very recurring examples like login and firebase. There are so many issues with this, that I think inserting it in the examples may be better. Well, I need opinions on all these topics, I often do things in the view of the creator of the package, not the developer who will see it, so any opinion is really welcome.

**Comment by Prn-Ice** [comment]
That will be awesome especially the examples repo.

**Comment by NiranjanShah** [comment]
I often do things in the view of the creator of the package, not the developer who will see it, so any opinion is really welcome.



Good finding and that is the fact with us human being.

I intend to include somewhere, very recurring examples like login and firebase.

Good Approach.

Also include service calls for list with incremental list loading (i.e fetch 10 records then list reaches to bottom, fetch other 10 records).


BTW, enjoying working in Flutter only due to this library, carry on the good work.

Regards,

Nirajan G Mandan

**Comment by jonataslaw** [comment]
Updated on pub.dev
Thanks
