### ISSUE TITLE
one or more of its instance fields aren't final

### ISSUE THREAD

**Issue by niypoo** [jonataslaw/getx#439]
I'm using StatelessWidget and I'm facing case that I have to define none-final Class so there is a  warring show up to me that say  

```
This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final

```

my code  

```
class TestWidget extends StatelessWidget {
  ItemGetXController controller;
  final bool disableAnimation;
  final String itemId;

  TestWidget({
    this.itemId,
    this.disableAnimation = false,
  }) {
     controller = Get.put(ItemGetXController(itemId:Itemid);
   }

   @override
  Widget build(BuildContext context) {
    return Text(controller.item.value.title)
  }

}
```

so this is a correct approach  and I should ignore this warring or there is another approach !?

**Comment by ghprod** [comment]
Hi, this issue is not related to GetX. You can use Discord/Slack/Telegram for this purpose.

Anyway regarding your problem, you need to define `disableAnimation` as final too.

**Comment by niypoo** [comment]
> Hi, this issue is not related to GetX. You can use Discord/Slack/Telegram for this purpose.
> 
> 
> 
> Anyway regarding your problem, you need to define `disableAnimation` as final too.

I know it's not issue but I want to know a best approach in this case

**Comment by niypoo** [comment]
I have edited the code to more explain the approach.

**Comment by ghprod** [comment]
Please upload your `ItemGetXController` too.. better if you can post minimal code to reproduce.

**Comment by ghprod** [comment]
Btw for `itemId` you can put with `arguments` route and get it via `Get.arguments` in your controller.

**Comment by jonataslaw** [comment]
Hi, if you are looking for help, or want to discuss using a tool, please use the platform channels. Your question will be resolved more quickly, and there will be no support issues here, making it easy for anyone looking for an issue/feature request.

Just so as not to leave you unanswered, all fields in a StatelessWidget class must be final.
