### ISSUE TITLE
Created an example project using GetX

### ISSUE THREAD

**Issue by delay** [jonataslaw/getx#440]
I just wanted to let you know I updated an auth project I made to make use of GetX instead of various other packages.  I wrote up a [medium article](https://medium.com/@jeffmcmorris/getx-flutter-firebase-auth-example-b383c1dd1de2) about the project and some of the changes created with GetX.  Link to [Github](https://github.com/delay/flutter_starter) code.  

Anyway I haven't found a lot of other project examples with GetX so thought I would let you know about it.  Thanks for making such a fantastic package!  I wasn't sure the best way to contact you about this so put it here. You can close this issue out.

**Comment by Nipodemos** [comment]
nice article! it has a lot of great examples of how to use getx to make things easier and better!

Thanks for that

**Comment by jonataslaw** [comment]
Hi, thanks for that!
Congratulations for the excellent article, and for the example.
Can I insert his link on GetxCommunity?

**Comment by ghenry** [comment]
Big thanks for this. Perfect timing for me too. Going to dig in this week and read it. Is it all done the recommend way? `getx_pattern` style? Will check it out :-)

**Comment by kauemurakami** [comment]
Nice job, congratulations ! 
if you want to do as Garry said, experiments the getx pattern, it's in my repositories.

**Comment by delay** [comment]
@jonataslaw Sure feel free to add it anywhere you think it might be helpful.

@ghenry I tried to do it in the best way as I understand GetX. I am not an expert on GetX so not sure if I did everything the optimal or preferred way.  Also since I was converting from using Provider and a stateful ui I am sure some of the code could be better optimized to the GetX way.

**Comment by ghprod** [comment]
@delay hi, sorry for out the topic.

which software to create this image? or manually using photoshop?

![image](https://user-images.githubusercontent.com/1922652/89153408-fb839b80-d58e-11ea-949f-9eb6c3ab2b06.png)

Thanks

**Comment by delay** [comment]
I used an iPad app called paste.

**Comment by jonataslaw** [comment]
@delay Your name is on the official Google page now.
Thanks for the article, and I'm closing this

https://flutter.dev/docs/development/data-and-backend/state-mgmt/options#getx
