### ISSUE TITLE
In Get.arguments change object to dynamic

### ISSUE THREAD

**Issue by aztecrabbit** [jonataslaw/getx#441]
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
When i input map to `Get.toNamed` arguments, thats not working to call that map.

```dart
print(Get.arguments['mapKey']);
```

Will throw error like this

```
The operator '[]' isn't defined for the type 'Object'. Try defining the operator '[]'.
```

**Expected behavior**
Working like if in type of dynamic. If i convert to dynamic, working as i expected.

```dart
dynamic arguments = Get.arguments;
print(arguments['mapKey']); // This working
```

**Flutter Version:**
1.17.4

**Get Version:**
3.4.1

My english is very bad, i'm sorry.

**Comment by ghprod** [comment]
You need to declare type first before get the map

```dart
Map<String, dynamic> arguments = Get.arguments;

print(arguments['key']);
```

**Comment by aztecrabbit** [comment]
Yes, but what i want is like this

```dart
print(Get.arguments['key']);
```

That possible if Get.arguments type changed from `Object` to `dynamic`

**Comment by roipeker** [comment]
[PR pushed](https://github.com/jonataslaw/getx/pull/603) and waiting for approval,
I doubt it will bring any breaking changes.
