### ISSUE TITLE
How to use GetX (or Obx) with Column instead of ListView

### ISSUE THREAD

**Issue by Andreigr0** [jonataslaw/getx#442]
I want to update a `Column` with its children when I'm changing the `.obs` `List`, but it's only allowed to use with a `ListView` like so:
```dart
Obx(
  () => ListView.builder(
    itemBuilder: (context, index) => Text('Person ${model.persons.elementAt(index)}'),
    itemCount: model.persons.length,
    shrinkWrap: true,
  ),
),
```
and I'm trying to update the `Column` like so:
```dart
Obx(
  () => Column(
    children: [
      for (final person in model.persons) ...[
        Text('Person: $person'),
      ],
    ],
  ),
),
```

Here is full source code to reproduce problem https://gist.github.com/Andreigr0/38954aeb098984366f8aad5359431e50

How could I solve the problem?

**Comment by jonataslaw** [comment]
` for (final person in model.persons.value)` (value is required only for this situation)

**Comment by Andreigr0** [comment]
I couldn't guess the solution would be that simple
Thanks
