### ISSUE TITLE
Back without closing Snackbar

### ISSUE THREAD

**Issue by Andreigr0** [jonataslaw/getx#443]
How could I navigate to previous screen with `Get.back()` function when `Snackbar` is opened?

If `Get.back()` call occurs earlier than call of `Get.snackbar()` it works as supposed to, but if it is called after `Get.snackbar()` it just closes it though default value is `Get.back(closeOverlays: false)`. 

And sometimes there are situations when it is needed to show a `Snackbar` and only then get back to previous screen. I think, it could be done if assign one Global key (`Get.nested`) to all routes and use it for navigation and without it for overlays such as `Snackbar`s, though it seems to be overhead

<details>
<summary>Source code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class GetBackScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Main'),
      ),
      body: Column(
        children: [
          RaisedButton(onPressed: () => Get.to(NestedScreen())),
        ],
      ),
    );
  }
}

class NestedScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Nested')),
      body: Column(
        children: [
          RaisedButton(
            onPressed: () {
              Get.back(closeOverlays: false);
              Get.snackbar('title', 'message');
            },
            child: const Text('Expected behaviour'),
          ),
          RaisedButton(
            onPressed: () {
              Get.snackbar('title', 'message');
              Get.back();
            },
            child: const Text('Just closes snackbar, but it should not'),
          ),
          RaisedButton(
            onPressed: () {
              Get.snackbar('title', 'message');
              Get.back(closeOverlays: true);
            },
            child: const Text('Closes both'),
          ),
        ],
      ),
    );
  }
}
```

</details>

**Comment by jonataslaw** [comment]
Sorry, that is not possible.
Maybe using Get.removeRoute, and removing the route below the snackbar, but I haven't tested it yet.
You must send your snackbar after Get.back () so that it is not closed.
closeOverlays, as described, closes all overlays before Get.back (), does not serve to close the route and maintain the snackbar, because this is currently not possible.

**Comment by FabioPagano** [comment]
Maybe Snackbar managed by ScaffoldMessenger, new in Flutter 2.0, can be of any help: https://flutter.dev/docs/release/breaking-changes/scaffold-messenger
