### ISSUE TITLE
Tried calling: dependOnInheritedWidgetOfExactType<_InheritedTheme>() on null.

### ISSUE THREAD

**Issue by f0rx** [jonataslaw/getx#446]
**Describe the bug**
I want to implement the RouteGuards, auto-nested navigation & all other features of the [auto_route](https://pub.dev/packages/auto_route) package using the [ExtendedNavigator ](https://github.com/Milad-Akarie/auto_route_library#navigation) helper. But I keep getting this error when I try to use `Get.context` or `Get.textTheme`.
```
The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<_InheritedTheme>()
```

**To Reproduce**

1. Declare Routes - router.dart
```dart
import 'package:auto_route/auto_route_annotations.dart';
import 'home_screen.dart';
import 'unknown_route.dart';

@AdaptiveAutoRouter(
  routes: <AutoRoute>[
    AdaptiveRoute(page: HomeScreen),
    AdaptiveRoute(path: "*", page: UnknownRoute),
  ],
  generateNavigationHelperExtension: true,
)
class $Router {}
```
2. Run build_runner - `flutter packages pub run build_runner build --delete-conflicting-outputs`
3. Init MaterialApp() - main.dart
**NB: The error doesn't show up if I remove `builder: ExtendedNavigator.builder(),`**
```dart
import 'package:flutter/material.dart';
import 'package:auto_route/auto_route.dart';
import 'router.gr.dart'; // Generated route file
import 'package:get/get.dart';
import 'unknown_route.dart';

void main() {
  runApp(MaterialApp(
    title: 'Flutter Demo',
    debugShowCheckedModeBanner: false,
    theme: ThemeData(
      primarySwatch: Colors.blue,
      visualDensity: VisualDensity.adaptivePlatformDensity,
    ),
    navigatorKey: Get.key,
    onGenerateRoute: Router(),
    builder: ExtendedNavigator.builder(
      router: Router(),
      onUnknownRoute: (RouteSettings settings) {
        return MaterialPageRoute(builder: (_) => UnknownRoute());
      },
    ),
  ));
}
```
4. Use `Get` in HomeScreen (home_screen.dart)
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Text("Flutter Demo", style: Get.textTheme.headline4.copyWith(fontWeight: FontWeight.w600))
      ),
    );
  }
}
```
I also get - `'package:flutter/src/widgets/media_query.dart': Failed assertion: line 812 pos 12: 'context != null': is not true.` when I try to access `Get.height` or `Get.width`.

5. `pubspec.yaml` file
```yaml
environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
     sdk: flutter
  cupertino_icons: ^0.1.3
  get: ^3.4.2
  auto_route: ^0.6.7

dev_dependencies:
  build_runner: any
  auto_route_generator: any
```

6. unknown_route.dart
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class UnknownRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text("Error"),
    );
  }
}
```

**Expected behavior**
- `Get.height` should return Device height (pixels),
- `Get.textTheme` should return App's TextTheme...
- `Get.context` should return current BuildContext.

**Screenshots**
![get-bug](https://user-images.githubusercontent.com/28307747/89355514-7940c780-d6b3-11ea-85bb-78d160366a74.png)

**Flutter Version:**
```
[√] Flutter (Channel beta, 1.20.0-7.2.pre, on Microsoft Windows [Version 10.0.16299.15], locale en-US)
    • Flutter version 1.20.0-7.2.pre at C:\src\flutter
    • Framework revision a2bde82fbd (2 weeks ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Anne\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Anne\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (3 available)
    • F103 Pro (mobile) • 192.168.43.14:5556 • android-arm64  • Android 6.0 (API 23)
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

**Get Version:**
`get: ^3.4.2`

**Describe on which device you found the bug:**
F103 Pro Android

**Comment by f0rx** [comment]
I tried the adding `Get` before MaterialApp as specified in #145, and I received the same error.
And according to the docs, `GetMaterialApp is necessary for routes, snackbars, internationalization, bottomSheets, dialogs, and high-level apis related to routes and absence of context.`

**Comment by jonataslaw** [comment]
You cannot use Getx and AutoRoute for navigation.
You can only use State and Dependency Management (only) if you are using something to delegate your routes.
There is no way to make this work, because inserting a builder will cancel Getx.

**Comment by f0rx** [comment]
Ok. The only solution would be to remove ExtendedNavigator helper in order to use GetX.

**Comment by hhstore** [comment]
> You cannot use Getx and AutoRoute for navigation.
> You can only use State and Dependency Management (only) if you are using something to delegate your routes.
> There is no way to make this work, because inserting a builder will cancel Getx.


- Same problem.
- It seems that `GetX` and `AutoRoute` can only choose one.
- I choose `GetX`.
- By the way, why aren't you allowed to create `Getx()` in the `builder`? Is there a design conflict?
