### ISSUE TITLE
Routing strage!

### ISSUE THREAD

**Issue by zl910627** [jonataslaw/getx#452]
First of all, thank you for your great library!
**Here is how to reproduct issue.**
1. define two pages [A, B] with names by `getPages` in app
2. on A page, show overlay (any one of dialog, bottom sheet and/or snackbar).
3. close overlay by `Get.back()` then move to B by `Get.toNamed`

**Expected.**
Stack will be A and B
**Current**
Page A has been removed and B pushed.
Here is some log for above issue.

![image](https://user-images.githubusercontent.com/53897531/89642344-403c6900-d8e6-11ea-8bb1-3bd84b71f223.png)

Thank you

**Comment by jonataslaw** [comment]
Could you edit the question with a reproduction case?

**Comment by zl910627** [comment]
on A page
```Dart
Get.dialog(~~~);
Fututre.delay(Duration(seconds: 3), () {
    Get.back(); // dismiss dialog
    Get.toNamed('/b');
});
```

**Comment by zl910627** [comment]
My bad, I am sorry.

**Comment by Nipodemos** [comment]
> My bad, I am sorry.

what happened? how did you solved this issue? it would be nice if you tell us
