### ISSUE TITLE
Prevent race condition - cancel previously request with rx operator

### ISSUE THREAD

**Issue by sokolej79** [jonataslaw/getx#459]
Is it possible when using getX as state management and when calling some http method in controller (action) to cancel previously http request and prevent race conditions.
Something like rx switchmap operator with redux epics or bloc pattern override actions delegete and return observable with switchmap, debounce, distinct untilChanged...

Scenario:  Many tabs and many filters: all-users, my only.... 
Each tab loads  different data from server based on tab ( view) and filter, but same shape of List<model>.
It could happen race condition from one tab to another or when tap filter multiple times to quick,  another example would be search and load data from server.
 What is best  getX strategy, solution to prevent this, can we use low level rx operators?

**Comment by jonataslaw** [comment]
Hi, next time you have questions about the use, please try our official support channels. It will certainly be quicker to solve your problem, and note that Github is for feature requests or bug descriptions.
Read about the Workers, they will certainly give you a north to follow.
No user action that needs to be intercepted, changed, or canceled should be performed directly on an Rx, on the contrary, it should have an Rx responsible for receiving the event, delegating that event to a worker, and handling that event within a Worker.
As this does not follow the issue opening guidelines, I am closing, but if you want you can ask other questions that I will answer. Note that this may take longer than in a support channel, with an active community, which will likely discuss this more quickly with you.
