### ISSUE TITLE
A way to hide url page name in web

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/getx#462]
Is it possible to hide the name of the page in the browser window (url)?
It seems that the name is always set automatically:
https://github.com/jonataslaw/getx/blob/8d84630d3c60ed853fe13bd97c54265a75238c96/lib/src/navigation/extension_navigation.dart#L56

I want my flutter web to navigate but still want the `#` in the browser url field.
I do not want to use named routes either.

is this possible?

https://demo.invoiceninja.com/#/ for example is working that way. You can navigate around without the browser url changes.

**Comment by jonataslaw** [comment]
I never thought that anyone could need this.
I will insert in the future the ability to disable this for all routes.

**Comment by jonataslaw** [comment]
Added on https://github.com/jonataslaw/getx/commit/b2ed3c7fdc4f43c5778010791ac15d72bbb28690

**Comment by smedasn** [comment]
any news on this?

**Comment by toandk** [comment]
> is there any guide on how to disable named routes on web?
> 
> because just setting the route name to an empty string does not work --> routeName: "",

My solution is bellow:

`main.dart:`

```dart
setUrlStrategy(XDPathUrlStrategy());
runApp(const MyApp());
```

```dart
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

class XDPathUrlStrategy extends HashUrlStrategy {
  /// Creates an instance of [PathUrlStrategy].
  ///
  /// The [PlatformLocation] parameter is useful for testing to mock out browser
  /// interactions.
  XDPathUrlStrategy([
    super.platformLocation,
  ]) : _basePath = stripTrailingSlash(extractPathname(checkBaseHref(
          platformLocation.getBaseHref(),
        )));

  final String _basePath;

  @override
  String prepareExternalUrl(String internalUrl) {
    if (internalUrl.isNotEmpty && !internalUrl.startsWith('/')) {
      internalUrl = '/$internalUrl';
    }
    return '$_basePath/';
  }
}
```

**Comment by djackowski** [comment]
@toandk works like a charm, thanks!
