### ISSUE TITLE
Binding not behaving as expected

### ISSUE THREAD

**Issue by caestrada** [jonataslaw/getx#464]
**Describe the bug**
If I `extend`  a class with  **GetWidget<AuthController>**, binding works. 
If I use **Get.find<AuthController>()**, binding will not work.

**To Reproduce**
1. Create a main class that uses **initialBinding**, and pass the binding class:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      home: Login(),
      initialBinding: AuthBinding(),
    );
  }
}
```

Here is a copy of the **binding** class:
```dart
class AuthBinding implements Bindings {
  @override
  void dependencies() {
    Get.lazyPut<AuthController>(() => AuthController());
  }
}
```

2. I **SEE** the error if I use **Get.find** in the Login class
```dart

class Login extends StatelessWidget {
  AuthController authController = Get.find<AuthController>();

  ...
  RaisedButton(
    child: Text('Login'),
    onPressed: () {
      authController.login(emailController.text, passwordController.text);
    },
   ),
  ...
}
  
```

3. I do **NOT** see the error if i use **GetWidget**
```dart
class Login extends GetWidget<AuthController> {
  ...
  RaisedButton(
    child: Text('Login'),
    onPressed: () {
      controller.login(emailController.text, passwordController.text);
    },
   ),
  ...
}

```

**Expected behavior**
I expect to have the class lazy loaded when i use **Get.find**.

**Screenshots**
Here is a snipped of the error i get:
<img width="628" alt="Screen Shot 2020-08-11 at 7 48 14 PM" src="https://user-images.githubusercontent.com/5117122/89960117-0cc24d00-dc0c-11ea-9680-7d4bfaf049bc.png">

**Flutter Version:**
version: 1.0.0+1

**Get Version:**
get: ^3.4.3

**Describe on which device you found the bug:**
iOS Simulator

**Minimal reproduce code**
See above.

**Comment by ghenry** [comment]
I think this is because you are using lazyput. Use put in your bindings if
not using getwidget or getview. May be wrong.

**Comment by caestrada** [comment]
Hey @ghenry, thanks you for your response. 
On the [example](https://pub.dev/packages/get/example) on the documentation the author uses the following snipped:
```
class SampleBind extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<ControllerX>(() => ControllerX());
  }
}
```
Yes I could just instantiate the class but then that defeats the dependency injection. I could be wrong. 
I'll dig a bit deeper into the code later on today. But what I saw at a quick glance yesterday was that both **GetWidget** and **Get.find** use the same underlying **find** method in the **get_instance** class. So that's why i wonder, why the difference in behavior.

```
/// Find a instance from required class
S find<S>({String tag, FcBuilderFunc<S> instance}) {
  String key = _getKey(S, tag);
  ...
}
```

**Comment by ghenry** [comment]
What about Getview?

**Comment by jonataslaw** [comment]
This is a recurring problem caused by "home".
You see, when you do this "()" you are closing your instance, and everything will remain exactly as it was at the exact moment the compiler went through that line.

If you, for example, did:

```dart
initialRoute: '/',
getPages: [name: '/', route: () => Home()]
```

the problem would be solved, because you are putting Home() inside a function, to be used in due time.

The Flutter should look like this:

```dart
MaterialApp (
home: () => Home(),
```

But due to an engineering error, they ended up not doing this, which culminated in an early closure of the instance.

The biggest problem here is that initialBinding will be passed by parameter, and the dependencies function will be called to initialize the dependency. However, `Home()`, will already be sent by parameter in a closed way. Soon, it will point to a memory space that does not exist.

GetView solves this problem using a get instead of an instance.

If you do, it will also work:
```dart
AuthController get authController => Get.find<AuthController>();
```

Because the get method is only called when you actually access it.

**Comment by caestrada** [comment]
Got it. 
Using **get** works! I'll be using named routes later on. 

Awesome work @jonataslaw

**Comment by ghenry** [comment]
>
> If you do, it will also work:
>
> AuthController get authController => Get.find<AuthController>();
>
> Because the get method is only called when you actually access it.
>
>
Which is different to doing this in your view?

AuthController c = Get.find();

**Comment by caestrada** [comment]
> If you do, it will also work: AuthController get authController => Get.find<AuthController>(); Because the get method is only called when you actually access it.
> Which is different to doing this in your view? AuthController c = Get.find();

Yes it is different. But as mentioned by @jonataslaw,  I think once I move to named routes i would be able to use the `AuthController c = Get.find();`. 
Thank you @ghenry .

**Comment by thisisRinzin** [comment]
I have this code:

`class HomeBinding implements Bindings {
  @override
  void dependencies() {
    Get.put(() => HomeController(
        HomeRepository(HomeProvider(client: Get.find<Client>()))));
  }
}

class AppPages {
  static final routes = [
    GetPage(name: Routes.HOME, page: () => HomeView(), binding: HomeBinding())
  ];
}

void main() async {
  final client = await initClient();
  Get.lazyPut<Client>(() => client);
  runApp(Ispot());
}

class Ispot extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      initialRoute: Routes.HOME,
      getPages: AppPages.routes,
    );
  }
}
`
but I get the error "HomeController not found. You need call put<HomeController>(HomeController()) before"
