### ISSUE TITLE
Transition animation curve behaviour

### ISSUE THREAD

**Issue by gary6lin** [jonataslaw/getx#465]
Hi,

I have set the 'curve' property in GetPageRoute and GetPageRoute and GetPage but it seems not working as expected.

So I dig into the source code and found that the curve is not used for most of the transitions. Is this the intended behaviour or something that has been missed out?

In addition to this, it would be great if we can set the transition curve globally.

Thanks :)

**Comment by jonataslaw** [comment]
Yes, most transitions do not use this property.
However, you can create CustomTransitions with it.

**Comment by gary6lin** [comment]
> Yes, most transitions do not use this property.
> However, you can create CustomTransitions with it.

But if I set the CustomTransitions globally on the GetMaterialApp, I won't be able to use the preset Transitions because the buildTransition() checks for the customTransition property first. I will have to set the customTransition for each route if I don't want to use the global default.

Are we able to improve this?

Thanks

**Comment by roipeker** [comment]
Fixed in this [PR](https://github.com/jonataslaw/getx/pull/565/commits/a7d193b04431c82e5bafb9331275a6880229e794)
