### ISSUE TITLE
Request for official listing on Flutter.dev

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/getx#467]
Just as a reference, I opened an issue to include GetX on the official Flutter.dev page:

https://github.com/flutter/website/issues/4478

**Comment by Nipodemos** [comment]
whoa, anyone can do this? nice

**Comment by stefandevo** [comment]
Yep. 
Pr created. 

https://github.com/flutter/website/pull/4479

**Comment by NiranjanShah** [comment]
gr8, eager to see GetX listed in Official Flutter listing.

Regards,

**Comment by jonataslaw** [comment]
Added https://flutter.dev/docs/development/data-and-backend/state-mgmt/options#getx
Thanks @stefandevo 
That was a big step.
