### ISSUE TITLE
Build context is null when testing a Widget

### ISSUE THREAD

**Issue by mawippel** [jonataslaw/getx#469]
I'm having the following issue when **testing** a Widget that uses `Get.height` or any other method that depends on `context`.

When testing a Widget that uses `Get.height`, it tries to get `MediaQuery.of(context).size.height`, but the context is null. With the null context, an assertion is thrown by `MediaQuery`:
```
'package:flutter/src/widgets/media_query.dart': Failed assertion: line 806 pos 12: 'context != null': is not true.
```
 
**Expected behavior**
A Build Context should be provided so that `MediaQuery` doesn't fail when asserting that `context != null`.

**Screenshots**
Here's my test:

![image](https://user-images.githubusercontent.com/37195917/90266258-15906a00-de2a-11ea-8886-e8c96e66117c.png)

Here's my Widget:

![image](https://user-images.githubusercontent.com/37195917/90265484-0a890a00-de29-11ea-9f94-a700ec60e4ed.png)

**Flutter Version:**
1.17.1

**Get Version:**
`get: ^3.4.4`

**Comment by jonataslaw** [comment]
Without a GetMaterialApp the context will always be null.

**Comment by mawippel** [comment]
I wrapped my `CustomTextField` in a `GetMaterialApp` in the test, but i'm having the following issue now:

```
No Material widget found.
TextField widgets require a Material widget ancestor.
```

**Comment by jonataslaw** [comment]
To test Material widget you must follow 3 steps:
1 Have MaterialApp
2 Have an ancestor that is Material (use Scaffold or wrap it in a Material widget).
3 In this case, you would just replace the MaterialApp with GetMaterialApp in a standard test.

**Comment by mawippel** [comment]
Ok! I got it working, ty so much.
