### ISSUE TITLE
Add docs: GetxService, GetView and GetWidget

### ISSUE THREAD

**Issue by jonataslaw** [jonataslaw/getx#470]
This is just a temporary roadmap about the documentation, which I checked now and there are some undocumented points that I think are essential for productivity with Getx.

- GetxService (And the respective difference between Get.lazyPut's fenix mode, and Get.put's permanent mode).
- GetView (StatelessWidget with easy controller acess);
- GetWidget (StatelessWidget with easy controller acess and cache, perfect for use with Get.create());

**Comment by Redcdiver** [comment]
Hi Jonny
can you please tell me how i can use GetxService with Auth as long you recommended to for doing so?
i had a lot of problems with Auth handling with GetxController and new firebaseauth package.
