### ISSUE TITLE
A TextEditingController was used after being disposed.

### ISSUE THREAD

**Issue by bajajsahil** [jonataslaw/getx#471]
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
A TextEditingController was used after being disposed.
Once you have called dispose() on a TextEditingController, it can no longer be used.

This was fixed in the earlier release and now it started coming again.

**To Reproduce**
1. Create a controller using GetxController
2. Define a TextEditingController variable
3. Dispose it in onClose()
4. Observe the console logs

**Expected behavior**
Should get disposed without any error

**Screenshots**

**Flutter Version:**
1.20.1

**Get Version:**
3.4.4

**Describe on which device you found the bug:**
ex: Samsung S9

**Minimal reproduce code**
```dart
class Controller extends GetxController {

  var fieldController = new TextEditingController();

  @override
  void onClose() {
    fieldController.dispose();
  }
  
  .....
}
```

**Comment by jonataslaw** [comment]
I don't understand your issue.
You say it was fixed and it didn't happen again, so what's the reason for the issue?
In addition, the reproduction code is a code that can be reproduced instantly.
Please answer this and edit the question, otherwise it will not be possible to proceed with this issue.

**Comment by bajajsahil** [comment]
@jasonlaw Sorry, there was a typo. "This was fixed in the earlier release and **_now_** it started coming again". I am facing this issue again in 3.4.4 version. As far as I remember it was fixed in 3.4.1 release. 

Let me know if it clears to you.

**Comment by jonataslaw** [comment]
This was a bug introduced by the latest version of Flutter.
I already fixed this in 3.4.6

**Comment by bajajsahil** [comment]
Thanks @jonataslaw

**Comment by lazicah** [comment]
I am facing this same issue now. 

A TextEditingController was used after being disposed.
      Once you have called dispose() on a TextEditingController, it can no longer be used.

**Comment by ProshutinskiiFromK** [comment]
Me too!

But I use one controller with two screens. Is it legal? If so, I would like to understand, what was happened

`@override
  void onInit() {
    super.onInit();
    nameController = TextEditingController(text: 'Smth')
      ..addListener(update);
    update();
  }

  @override
  void onClose() {
    nameController.dispose();
    super.onClose();
  }`

**Comment by AjanBikliqi** [comment]
Does anyone have the solution for this im  getting this error when using Get.back

**Comment by tianxiawoyougood** [comment]
4.6.5遇到了同样问题

**Comment by JasonYHZ** [comment]
Flutter Version:
3.10.2

Get Version:
4.6.7

Describe on which device you found the bug:
ex: Iphone 11 ios 16.4

I have the same problem.

Please open this question

**Comment by jiangxkwj** [comment]
Flutter 3.32.4
get: ^4.7.2
encounter the same problem.

**Comment by yogithesymbian** [comment]
same problem after get off all
