### ISSUE TITLE
can we use MultiGetBuilder()?

### ISSUE THREAD

**Issue by Ditway** [jonataslaw/getx#472]

**Comment by Nipodemos** [comment]
This function does not exist, but now that you've mentioned it, maybe it would be nice to have.
The need to nest a getbuilder inside another for use two different controllers data on a same widget is weird. When is three controller things start to get messy

but how this getBuilder should be done?
with a `controllers:` argument that accept an array of controllers? I don't know if it's nice to have something like 
```dart
ListTile(
  title: Text(controller[0].title),
  subtitle: Text(controller[1].timeAgo()) // or whatever method your controller has
  leading: Icon(controller[3].getIcon())
)
```
but as a matter of fact i can't thing of a better way

**Comment by jonataslaw** [comment]
To return a List of controllers, it would be necessary to redo GetBuilder, and GetX to return a List of Controllers instead. For those who only use a controller, this would not make sense.
My official recommendation is that:
Have only one controller per view.
Use a getter for other controllers in your controller if you need information from more than one, or use a GetX<OtherController>() to access that controller instance.
This feature request is denied for now, but if anyone has a good idea about it, I’m going to consider a feature like this again.
