### ISSUE TITLE
Translate the documentation in french

### ISSUE THREAD

**Issue by adamako** [jonataslaw/getx#476]
I want to help to translate the documentation in french

**Comment by Nipodemos** [comment]
Hello! i a fellow translator myself i appreciate very much for your interest! Jonatas already liked 😸 
If you have any doubts of how some thing work or want to ask some tips just let me know! i'm in slack and discord

**Comment by adamako** [comment]
@Nipodemos Okay no problem. 

On slack I was asking some clarification about getX and MVVM but I have not gotten a response yet 😅

**Comment by Nipodemos** [comment]
You got me on that one, I have no idea what MVVM is like 😅 and I don't know how to apply it to GetX and flutter

**Comment by adamako** [comment]
Great 👍🏽

**Comment by Jojoooo1** [comment]
Can help for french traduction if needed.

**Comment by Victor-Dev77** [comment]
Hi, I'm French also, but I don't think we just need to translate the current documentation into French. But rather of improving the documentation again because there have been a lot of changes in Getx

**Comment by jonataslaw** [comment]
Since I do not speak French, and no one from the community has spoken out to start the translation, I am closing here.
If any of you are interested in this, please open a PR.
