### ISSUE TITLE
Remove unnecessary url promotion

### ISSUE THREAD

**Issue by joanofdart** [jonataslaw/getx#477]
Can you please remove this from the package?

![image](https://user-images.githubusercontent.com/43426084/90445400-e6a31e00-e0df-11ea-9751-d94f5bb8a8e0.png)

No offence but running this code arbitrary without our concent is quite rubbish @jonataslaw and I've asked before but my request was ignored.

**Comment by jonataslaw** [comment]
You must be using a very old version. Update your dependencies.
