### ISSUE TITLE
Is there any way to prevent direct link on flutter web?

### ISSUE THREAD

**Issue by unmaskedd** [jonataslaw/getx#479]
title pretty much

Basically if my '/ ' is HomePage()

and I have a  '/route2' if  a user where to go to my.app/#/route2

I want to prevent that I want it to either go to '/ ' or just prevent it

**Comment by joanofdart** [comment]
https://github.com/jonataslaw/getx/issues/391 theres already an issue for route guards

**Comment by jonataslaw** [comment]
Duplicate of https://github.com/jonataslaw/getx/issues/391
Closing
