### ISSUE TITLE
Can I dynamic add property to contoller

### ISSUE THREAD

**Issue by SegmentControl** [jonataslaw/getx#483]
**Is your feature request related to a problem? Please describe.**
In home page,there have some tabs,and tab count does not fixed;every tab have a list and list data get by home_controller.what method can i manager the dynamic obs property.

**Describe the solution you'd like**
I want to add obs property value by dynamic or other method

**Comment by jonataslaw** [comment]
Please ask support questions on the appropriate platform channel.
This channel is for description of bugs and (real) feature requests only.
To learn how to do something, you must follow some community support channel, and they will help you more quickly.
Closing it.
