### ISSUE TITLE
Provide Get.size so someone won't have to call Get.width and Get.height separately

### ISSUE THREAD

**Issue by MrCsabaToth** [jonataslaw/getx#486]
**Is your feature request related to a problem? Please describe.**
My current code is `final size = MediaQuery.of(context).size;` and I can replace that with `final size = Size(Get.width, Get.height);`

**Describe the solution you'd like**
I'd like to just have `final size = Get.size;`

**Describe alternatives you've considered**
Instantiating the `Size` myself, but that's unnecessary weight lifting. There's also a way of `Get.mediaQuery.size`, maybe that's sufficient.

**Comment by MrCsabaToth** [comment]
I decided that `Get.mediaQuery.size` is sufficient.

**Comment by Nipodemos** [comment]
just as a small reminder, when you use `Get.width` and such, those values will be static, which means they won't change (even if you resize your window on web for example). The best way to have realiable info about that is use the extensios on context:

`context.height`
`context.width` and so on

**Comment by MrCsabaToth** [comment]
@Nipodemos interesting, I should check that!

**Comment by MrCsabaToth** [comment]
So along the line of @Nipodemos's advice there's `context.mediaQuerySize`
