### ISSUE TITLE
Add reversed.toRxList() to RxList<E>?

### ISSUE THREAD

**Issue by d-apps** [jonataslaw/getx#495]
I have a List.obs of objects and I needed to reverse the order of the objects, Flutter's List has this option which makes easy to reverse the order but when creating .obs Lists it doesn't have.

![image](https://user-images.githubusercontent.com/20110433/90986752-94d51a80-e55b-11ea-8000-fd354fe4b40b.png)

As workaround we need clone to a temporary List of objects, reverse, then copy to the observable List:

```
    final products = <Product>[].obs;
    products.addAll(await getProducts());

    var tempList = <Product>[];
    tempList.addAll(products.value);
    tempList = tempList.reversed.toList();
    products.clear(); 
    products.addAll(tempList);
```

But, is it possible to add it to RxList?

```
 final products = <Product>[].obs;
`products = products.reversed.toListRx(); // or something like this...`
```

**Comment by jonataslaw** [comment]
The reverse list is likely to be implemented in the future, but there is a much simpler way for you to do it:

```dart
final products = <Product>[].obs;
products.assignAll(products.value.reversed);

// maybe products.assignAll(List.from(products.value.reversed));
```

**Comment by d-apps** [comment]
> The reverse list is likely to be implemented in the future, but there is a much simpler way for you to do it:
> 
> ```dart
> final products = <Product>[].obs;
> products.assignAll(products.value.reversed);
> 
> // maybe products.assignAll(List.from(products.value.reversed));
> ```

The first didn't work but the second worked fine, thanks.

`products.assignAll(List.from(products.value.reversed));`

**Comment by djade007** [comment]
@d-apps If you're using a list view. You can simply set the `reverse` attribute to `true`. No need to reverse the actual list again.

`ListView(
      ......
     reverse: true,
);`

**Comment by jonataslaw** [comment]
> The first didn't work but the second worked fine, thanks.
> 
> `products.assignAll(List.from(products.value.reversed));`

Based on your comment, I am closing this

**Comment by d-apps** [comment]
> @d-apps If you're using a list view. You can simply set the `reverse` attribute to `true`. No need to reverse the actual list again.
> 
> `ListView( ...... reverse: true, );`

It doesn't work, it only invert where the list will start, actually I didn't about this behavior.

![image](https://user-images.githubusercontent.com/20110433/91070309-f43f3300-e60c-11ea-9268-b32a96a422ac.png)

**Comment by djade007** [comment]
> > @d-apps If you're using a list view. You can simply set the `reverse` attribute to `true`. No need to reverse the actual list again.
> > `ListView( ...... reverse: true, );`
> 
> It doesn't work, it only reverse where the list will start, actually I didn't know about this behavior.
> 

To insert a new item to the bottom the list you can do:
`_products.value.add(0, {product})`

In addition: for animating new items added, you can use https://flutter.dev/docs/catalog/samples/animated-list

**Comment by malithkuruppu** [comment]
I have a list of observable defined so:
 `RxList userList = <UserViewModel>[].obs;`

I am try to map the list of users to userList like so:
```
var users = await ServiceManager().fetchUserList();
 this.userList = users.map((user) => UserViewModel(user: user)).toList();
```

But this gives me a error:
```
A value of type 'List<UserViewModel>' can't be assigned to a variable of type 'RxList<dynamic>'.
Try changing the type of the variable, or casting the right-hand type to 'RxList<dynamic>'.
```

So I cast the right-hand type as Rxlist like so:
`this.userList = users.map((user) => UserViewModel(user: user)).toList() as RxList;`

But at run-time I get the following error:
```
Exception has occurred.
_CastError (type 'List<UserViewModel>' is not a subtype of type 'RxList<dynamic>' in type cast)
```

How I do I fix this problem?

**Comment by djade007** [comment]
@malithkuruppu 
You may need to review the documentation again, but this should solve your issue.
`this.userList.assignAll(users.map((user) => UserViewModel(user: user)).toList())`
