### ISSUE TITLE
In StatelessWidget - onClose is not called when I leave the screen.

### ISSUE THREAD

**Issue by AlyssonPHN** [jonataslaw/getx#497]
I have a screen A and B using StatelessWidget, each with a controller, if I close screen B with Get.back () the controller of screen B does not call onClose.
Only calls onClose when using StatefulWidget.

**Comment by jonataslaw** [comment]
Please open the issue following the script for opening the issue, don't forget to insert the problem reproduction code, device and more details.
Closing this for disrespecting the issue opening standards.
