### ISSUE TITLE
RxList can't be assign to List

### ISSUE THREAD

**Issue by ziasultan2** [jonataslaw/getx#498]
Hi dear thank you for this awesome package. It reduce my development time by around 30%

**Is your feature request related to a problem? Please describe.**
A value of type RxList<Restaurant> can't be assigned to a variable of type List<Restaurant>
Try changing the type of the variable, or casting the right-hand type to 'List<Restaurant>'

  List<Restaurant> restaurantList = List<Restaurant>().obs;

**Describe the solution you'd like**
What is the solution for this problem and
Can you make it auto casting so that we don't need to face this problem or whatever you think will better.

**Comment by jonataslaw** [comment]
Use 
RxList restaurantList = List().obs;

To indicate that a type is a reactive variable, we use "Rx" before it.

String => RxString 
int = RxInt 
double - RxDouble 
Map = RxMap 
List = RxList 
bool = RxBool.

**Comment by ziasultan2** [comment]
Thank you dear for your reply. It solves the issues.

**Comment by jonataslaw** [comment]
Once it has been resolved, I am closing it.
