### ISSUE TITLE
How to use `getx` with `meteorify` ?

### ISSUE THREAD

**Issue by Navyroot** [jonataslaw/getx#499]
Hi all bro , I'm new for flutter. Can you explain me `getx` use  with `meteorify` (`subscribe`,`call method`) ?

**Comment by jonataslaw** [comment]
Wow bro, unfortunately I don't know this package, and here is not the place for it.
Try to join some of our community channels to see if anyone can help you, here is reserved for issues and requests for resources, so I'm closing here.

**Comment by Navyroot** [comment]
Yes , thank bro .
