### ISSUE TITLE
The operator 'unary-' isn't defined for the type 'RxInt

### ISSUE THREAD

**Issue by jpkontreras** [jonataslaw/getx#500]
```
class ListController extends GetxController {
int _selected = -1.obs;
  int get selected => _selected;
}
```

**Comment by jonataslaw** [comment]
int _selected = -1.obs;
  int get selected => _selected.value;
}

**Comment by jpkontreras** [comment]
hi @jonataslaw the issue persists
It seems that Rx int is not implementing the negative sign 

The use case is selecting an index of an array and showing it using obx 


Im using android studio 
 Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.6 19G2021, locale es-CL)
    • Flutter version 1.21.0-9.1.pre at /Users/juliocontreras/flutter
    • Framework revision be9bc8cb39 (6 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

**Comment by jonataslaw** [comment]
I believe that it is not possible to overwrite the unary operator in the dart.
Not even overwriting `int operator -()` will be possible, you will have to use parentheses to do this:

```dart
  RxInt _selected = (-1).obs;
  int get selected => _selected.value;
```
And thanks for the remark
