### ISSUE TITLE
Any thought on adding online/offline support into GetX?

### ISSUE THREAD

**Issue by aktxyz** [jonataslaw/getx#502]
You have come up with a very slick way to do so many fundamental/common things in Flutter ... would love to see what kind of easy way you come up with to add a connectivity check

**Comment by joanofdart** [comment]
I think one of the first key points we need in getx is a clear "Whats the next thing?"
We as a community still don't know what's being developed/done and what's the next step or what would it the best convenient path for the library to take.

**Comment by Nipodemos** [comment]
You mean like the [Connectivity package](https://pub.dev/packages/connectivity)?
In my opinion that package is good enough.

@jonataslaw Are you wanting to develop something like this for GetX? if yes, i'll put it in the roadmap, if not, i'm closing this issue.

**Comment by jonataslaw** [comment]
I understand that this can be an important resource that the onusuario would like to be facilitated, however, this is definitely in the niche of resources that we want to explore for now. Perhaps in the future, when we have the time and resources for that, we will be able to support it. So I'm closing this, but if I include something related to it in the future, I'll let you know by mentioning it in the issue. Thank you
