### ISSUE TITLE
[Feature Request]: Adding Persistent Bottom Sheet.

### ISSUE THREAD

**Issue by Nipodemos** [jonataslaw/getx#503]
@GoldenSoju suggested on [a comment in issue #201 ](https://github.com/jonataslaw/getx/issues/201#issuecomment-662974044)

One favor I would like to ask for:

### Adding Persistent Bottom Sheet.

At the moment "Get.bottomSheet()" returns a Modal Bottom Sheet, but I was wondering if you could also add the Persistent Bottom Sheet ?

**Modal:** https://api.flutter.dev/flutter/material/showModalBottomSheet.html
**Persistent:** https://api.flutter.dev/flutter/material/showBottomSheet.html

Modal Bottom Sheet makes the rest of the screen inactive but
I would need the behavior of the Persistent Bottom Sheet where the user can interact with the rest of the screen when the bottom sheet is shown. 

Obs: i am separating feature request in different issues so they can be put in the projects board
@jonataslaw if you don't plan to make this feature, tell me so this issue can be closed and removed from the roadmap
this can be checked [here](https://github.com/jonataslaw/getx/projects/1?add_cards_query=is%3Aopen)

**Comment by jonataslaw** [comment]
It is an easy feature to implement, it will be implemented in the short term, after this roadmap:

https://github.com/jonataslaw/get_cli

**Comment by jonataslaw** [comment]
Adding to projects sounds incredible to me, and it will become more organized than a simple roadmap. Thank you.

**Comment by mohak852** [comment]
@jonataslaw I wanna contribute to this getx should i try to solve this issue

**Comment by Nipodemos** [comment]
@mohak852 every contribution is very welcomed ❤️

**Comment by roipeker** [comment]
> @jonataslaw I wanna contribute to this getx should i try to solve this issue

Any progress?

**Comment by jonataslaw** [comment]
Added https://github.com/jonataslaw/getx/pull/604
