### ISSUE TITLE
[docs]: add more examples of no-context navigation

### ISSUE THREAD

**Issue by Nipodemos** [jonataslaw/getx#505]
We have one or two examples, but we need more in order to be easier for users to understand and use

**Comment by evandrmb** [comment]
Did you saw this?
https://github.com/jonataslaw/getx/blob/master/documentation/en_US/route_management.md

**Comment by Nipodemos** [comment]
Yes I did
Tô be honest this issue is more a reminder that the docs need to get better, but is already there

**Comment by evandrmb** [comment]
If i'm not mistaken @jonataslaw said that there's some features that are not in the docs. A part from that maybe what we need are just more samples in the examples repo?

**Comment by jonataslaw** [comment]
I think it can be closed
