### ISSUE TITLE
Get.snackbar, adding styling and properties to the Text.

### ISSUE THREAD

**Issue by DarkHeros09** [jonataslaw/getx#511]
Hi

i was playing/experimenting with Get.snackbar, and i noticed that i couldn't center the text message of the snack bar which is always aligned on the left, also i couldn't change the text message styling.

i really like the Get.snackbar because it doesn't need a context, and I'd like to see these features being added.

Thank you.

**Comment by jonataslaw** [comment]
Hi, there are already these options, please follow this issue:
https://github.com/jonataslaw/getx/issues/410

**Comment by DarkHeros09** [comment]
Thank you
