### ISSUE TITLE
can't open named route again.

### ISSUE THREAD

**Issue by niypoo** [jonataslaw/getx#514]
**Describe the bug**
**I noticed that in get 3.3.0 this issue not exist** but newer it's exist ,
When Open bottom sheet and go to named route event  Get.to the first time the new route will open but when close new route and tap on button to open it again not open and don't show any error in catch error

but when open the same route from route with same condition it's working normal.

**To Reproduce**
1. open bottom sheet.
2. tap on create button to navigate to Create Page,
3. close Create Page,
4. tap on create button again 
5. no nothing show.

**Flutter Version:**
Flutter 1.20.2 • channel stable

**Get Version:**
^3.5.1

**Describe on which device you found the bug:**
IOS-Android

**Minimal reproduce code**
routes.dart
```
GetPage(
        name: '/shoppinglist',
        page: () => ShoppingListView(),
        binding: ShoppingListBinding()),
```

bottom sheet .dart

```

GetX(
      init: ShoppingListPickerController(),
      initState: (_) =>
          ShoppingListPickerController.to.currentContext = context,
      builder: (controller) => SafeArea(
        child: Column(
          children: <Widget>[
            BottomSheetAppBarWidget(
              title: LocaleService.tra('Lists'),
              subtitle: LocaleService.tra('Choose a Shopping list'),
              icon: MdiIcons.formatListText,
              actionButtons: <Widget>[
                FlatButton(
                  child: Text(
                    LocaleService.tra('New'),
                    style: Get.textTheme.subtitle1.copyWith(
                      color: Get.theme.primaryColor,
                    ),
                  ),
                  onPressed: () async {
                    try {
                      print('A');
                      await Get.toNamed('/shoppinglist');
                      print('B'); --> at first time its wait for Get.toNamed response @ but in second time it's printed with A
                    } catch (e) {
                      print('Error $e');
                    }
                  },
                ),
              ],
            ),
```

**Comment by jonataslaw** [comment]
Get.toNamed('/shoppinglist', preventDuplicates:false);

**Comment by niypoo** [comment]
thanks it's working.

**Comment by Nipodemos** [comment]
Just to add some context to people that may see this issue in the future:
GetX by default does not let you go to a route that you are already at (If the screen you want to show is already the one showing, why would you open it again?). This helps you when you accidentally call the push method twice or the user press the button to the next screen too fast several times.

But since it may have use cases when you want to porpusely open the same screen again, GetX have a option `preventDuplicates` that you can change when pushing the new route

**Comment by Darksoulsong** [comment]
I've got a use case for opening the same route again, I'd like to refresh the same route with fresh arguments. I'm using preventDuplicates: false, the route gets opened alright, but the controller's onInit method doesn't get called a second time.

How can I accomplish this?

**Comment by seekcx** [comment]
@Nipodemos This is not right. It is very common to open the same page with different parameters.

**Comment by Nipodemos** [comment]
ok I've edited

**Comment by Darksoulsong** [comment]
I have a use case where I need to open the same route twice, and I'm using `Get.toNamed` with `preventDuplicates: false`, and it works... until I hit the back button and the page is removed. When I try to navigate again I receive this message:

`"FooController" not found. You need to call "Get.put(FooController())" or "Get.lazyPut(()=>FooController())"`

It seems my controller has been removed and can't be recreated anymore.

How can I sort this out?

**Comment by agueroveraalvaro** [comment]
You can check this response:
[https://stackoverflow.com/a/67907133/5869217](url)
