### ISSUE TITLE
Getx with New FirebaseAuth

### ISSUE THREAD

**Issue by Redcdiver** [jonataslaw/getx#520]
**Is your feature request related to a problem? Please describe.**
it can't use Getx with firebase user stream binding to go to homeSreen when authenticated or loginScreen if not logged inn.
**Describe the solution you'd like**

example code please.

**Comment by ghprod** [comment]
Hi, please share your code to see what you have done. Otherwise, you can browse issues to get some example, I've written it one too.

**Comment by jonataslaw** [comment]
If you are looking for sample code or something similar, please join one of our community channels, you will be answered faster, and it will certainly be the appropriate place.
This space is destined exclusively to issues and requests for resources.

As this is neither an issue nor a resource request, I am closing this.

**Comment by Redcdiver** [comment]
> If you are looking for sample code or something similar, please join one of our community channels, you will be answered faster, and it will certainly be the appropriate place.
> This space is destined exclusively to issues and requests for resources.
> 
> As this is neither an issue nor a resource request, I am closing this.

thank you for closing my problem and thank you for the advice
Sorry : i am totally new here on GIT 
what channels ? where are the links? how i can subscribe to these channels?
i was watching a video on you tube from 3h the man was struggling with the Auth control too.
i think your package is great but it is to advance for me as i count on resources and documentation .
i am sorry for asking the author for support .
i am sorry to waist your time.

**Comment by jonataslaw** [comment]
https://github.com/jonataslaw/getx#communication-and-support-channels
Slack, telegram and discord

**Comment by Nipodemos** [comment]
don't worry man, GetX can be quite challenging to learn at first, because it has a lot of things and it is very different of other know packages.
But don't give up! Life in flutter becomes way easier with GetX

**Comment by Redcdiver** [comment]
> don't worry man, GetX can be quite challenging to learn at first, because it has a lot of things and it is very different of other know packages.
> But don't give up! Life in flutter becomes way easier with GetX

Nipodemos.

thank you to your message.
i agree with you, learning something new can be challenging  when you have no reference nor recommendation from the official author.
i was trying to get the right technique from the source like always. there is a mess in resources specially on youtube including wrong information and techniques.
i like flutter and Dart i think i should stick to the thing which has available resources and support. i can understand that beginners questions are stupid some times :)
 my apologies again to the Author  of the Package
