### ISSUE TITLE
App Freezes after printing " [GETX] GOING TO ROUTE <class-name> " and there's nothing printed in consol.

### ISSUE THREAD

**Issue by abdullah-alamin-inme** [jonataslaw/getx#532]
**Bug discription**
I was using get: ^2.5.0 then updated to 3.5.0,
everything was working fine, but after I added a new route 
```Get.to(UserDetailsPage());``` app is freezing and I can't go anywhere or interact with anything in app!.
I tried to follow my code but nothing to be causing the issue specially I'm just moving to normal Widget that has no complexity or anything that might cause the freeze.
I used flutter performance tools to analyze my widget tree and figure what is causing the lag but nothing was helping. 
last thing I see in my terminal/consol is ```[GETX] GOING TO ROUTE  /UserDetailsPage``` then nothing gets printed.
I tried using ```toNamed("UserDetailsPage");``` also same happens.

**To Reproduce**
Since it is just usual use of the package ```Get.to(. . .)``` I will paste my code snippet and hope we can figure out the issue.

**Flutter Version:**
I was using latest stable version but thought issue was from Flutter engine so I reverted back to Flutter version ```1.17.5``` on mac

**Get Version:**
previously ```2.5.0``` currently ```3.5.0``` problem was there and still.

**Describe on which device you found the bug:**
Samsung Galaxy S10 plus, Android 10

**Minimal reproduce code**

 main.dart
```
  @override
  Widget build(BuildContext context) {
    return MyInheritedWidget(
      child: GetMaterialApp(
        showPerformanceOverlay: true,
        debugShowCheckedModeBanner: false,
        getPages: <GetPage>[
          GetPage(
            name: '/UserDetailsPage',
            page: () => UserDetailsPage(),
          ),
          GetPage(
            name: '/LoginPage',
            page: () => LoginPage(),
          ),
          GetPage(
            name: '/',
            page: () => (widget.isLogged ?? false) ? Chats() : LoginPage(),
          ),
          GetPage(
            name: '/Chats',
            page: () => Chats(),
          ),
          GetPage(
            name: '/ChatViewController',
            page: () => ChatViewController(),
          ),
        ],
        // routes: {
        //   'LoginPage': (context) => LoginPage(),
        //   'Chats':     (context) => Chats(),
        //   'ChatViewController': (context) => ChatViewController(),
        //    'UserDetailsPage':   (context) => UserDetailsPage(),
        // },
        navigatorKey: Get.key,
        title: 'AdminApp',
        theme: ThemeData(
          primarySwatch: Colors.indigo,
          buttonColor: Colors.indigoAccent,
        ),
        home: widget.isLogged ? Chats() : LoginPage(),
      ),
    );
  }
```

this code snippet represents the block where I call **Get.to(UserDetailsPage());**
```
. . .
 AppBar(
       actions:[
      FutureBuilder(
          future: ...,
         buider:(context, snapshot){
             return (_chatObject.userID1 != "1") ?
                             IconButton(
                                  icon: Icon(Icons.info),
                                  onPressed: () async {
                                    await Get.to(UserDetailsPage());  // here it freezes immediatly.
                                  },
                                )
       : SizedBox() 
          },      
        ),
      ],
),
```

And this is class ```UserDetailsPage.dart``` where Get.to() goes to.

```
class UserDetailsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            NameAndAvatar(),  //just couple of Containers and Texts
            UserData(),      //just couple of Containers and Texts
          ],
        ),
      ),
    );
  }
}
```

I tried solving this by various ways but couldn't find any clue that's why I expect the plugin is reason. but even if it is causing issue or not you guys are doing awsome work there and I would like to thank you for your time &help.
regards.

**Comment by Nipodemos** [comment]
Please, follow the issue template. It helps us get all the information needed to understand your issue better.
Don't forget to add a piece of code that we can reproduce in our computers that has the error that you are mentioning

**Comment by ghprod** [comment]
Please next time follow the template and provide us an executable minimal reproduce code.

**Comment by abdullah-alamin-inme** [comment]
Just a sec guys I'm trying to explain, I just pressed enter by mistake and it notifies all of u.
plus thanks for the quick reply.

**Comment by jonataslaw** [comment]
This does not seem to me to be related to Getx.
Look at the breakpoints to see if there is no exception paused, probably the next page has something that is throwing an exception.
To make sure of this, it's easy, simply browse using:

```dart
await Navigator.push(
    context,
    MaterialPageRoute(builder: (context) => UserDetailsPage()),
  );
```
If the problem persists, Getx is not the reason for your problem.

I also recommend that you remove this from your code:
`navigatorKey: Get.key,`

This is not necessary since 3.0

And that you give your project a `flutter clean` and build it again.
Often making large updates like this, the flutter can cache small pieces of code, and cause problems like this.

**Comment by abdullah-alamin-inme** [comment]
Thanks for your time everyone, I managed to fix this issue by chance.
The reason is that there were ListView with length null, and it was taking tooooo long to build and that caused huge memory leak so app wasn't able to render the UI elemnts. it was more like internall deadlock.
readon why I thought your package is the reason for the freeze because it was the last thing to be printed in console and all what I could see in the break points or profile wasn't related to my code. 

Thanks I'm closing this issue now.

**Comment by IMRISHABH08** [comment]
> Thanks for your time everyone, I managed to fix this issue by chance. The reason is that there were ListView with length null, and it was taking tooooo long to build and that caused huge memory leak so app wasn't able to render the UI elemnts. it was more like internall deadlock. readon why I thought your package is the reason for the freeze because it was the last thing to be printed in console and all what I could see in the break points or profile wasn't related to my code.
> 
> Thanks I'm closing this issue now.

@abdullah-alamin-inme  

I am facing exactly the same issue! Can you please ellobrate how can I handle this issue!



Widget newOrder(BuildContext context, TextStyles textstyle,
      AllOrdersList? dataList, HomeState homeData) {
    return ListView.builder(
        itemCount: dataList?.orderData.length,
        itemBuilder: (context, index) {
          return GestureDetector(
            onTap: () {
              // Navigator.push(context, MaterialPageRoute(builder: (context) {
              //   return OrderDetails(
              //       dataList?.orderData == null
              //           ? 1
              //           : dataList?.orderData[index]?.orderId,
              //       homeData.allOrders?.orderData[index]?.orderStatus ?? 2);
              // }));
              Get.to(() => OrderDetails(
                  dataList?.orderData == null
                      ? 1
                      : dataList?.orderData[index]?.orderId,
                  homeData.allOrders?.orderData[index]?.orderStatus ?? 2));
            },
            child: detailedNewWidget(
                textstyle, dataList?.orderData[index], homeData, context),
          );
        });
  }



My itemLenght won't become null !

**Comment by IMRISHABH08** [comment]
> `Widget newOrder(BuildContext context, TextStyles textstyle,
      AllOrdersList? dataList, HomeState homeData) {
    return ListView.builder(
        itemCount: dataList?.orderData.length,
        itemBuilder: (context, index) {
          return GestureDetector(
            onTap: () {
              // Navigator.push(context, MaterialPageRoute(builder: (context) {
              //   return OrderDetails(
              //       dataList?.orderData == null
              //           ? 1
              //           : dataList?.orderData[index]?.orderId,
              //       homeData.allOrders?.orderData[index]?.orderStatus ?? 2);
              // }));
              Get.to(() => OrderDetails(
                  dataList?.orderData == null
                      ? 1
                      : dataList?.orderData[index]?.orderId,
                  homeData.allOrders?.orderData[index]?.orderStatus ?? 2));
            },
            child: detailedNewWidget(
                textstyle, dataList?.orderData[index], homeData, context),
          );
        });
  }
>
