### ISSUE TITLE
about  named route values

### ISSUE THREAD

**Issue by libexdui** [jonataslaw/getx#537]
```dart
GetObserver()
String current;
String previous;
value.previous = '${route?.settings?.name}'; // String -> 'null'
value.current = '${previousRoute?.settings?.name}';  // String -> 'null'
```
i want to be like this:
```dart
value.current = route?.settings?.name ?? ''; // String -> ''
value.current = route?.settings?.name; // String -> null
```
just `''` or `null` . what ever , 'null' maybe is a named route page

**Comment by jonataslaw** [comment]
That makes sense.
I will update this soon, but please don't use such large letters.

**Comment by libexdui** [comment]
> I will update this soon, but please don't use such large letters.

sorry about that :D, this is my first issues report , you know ... 2333333...

**Comment by jonataslaw** [comment]
Change on 3.7
