### ISSUE TITLE
GetX Extension for IntelliJ?

### ISSUE THREAD

**Issue by cliffordh** [jonataslaw/getx#538]
I use IntelliJ as my primary IDE. It would be great if the extension was ported to IntelliJ. Extension support is a big driver of usage within the community and I believe this would help drive adoption of GetX.

Thank you.

**Comment by ghenry** [comment]
I'd be interested in helping with this but I've never done one before. Have you? Are there good resources to read with an example one anywhere that you know of?

Thanks.

**Comment by ghenry** [comment]
Seems to be kotlin:

https://github.com/JetBrains/intellij-platform-plugin-template

**Comment by CpdnCristiano** [comment]
@ghenry The plugin can be done in kotlin or java

**Comment by CpdnCristiano** [comment]
I started a project
https://github.com/CpdnCristiano/getx_intellij_snippets/tree/master

**Comment by CpdnCristiano** [comment]
![Captura de Tela 2020-09-01 às 08 05 58](https://user-images.githubusercontent.com/54460776/91842211-054dfc80-ec2a-11ea-9f49-f781a4e8590b.png)

**Comment by CpdnCristiano** [comment]
[
![Captura de Tela 2020-09-01 às 08 06 05](https://user-images.githubusercontent.com/54460776/91842252-1a2a9000-ec2a-11ea-8d82-97eccd0543af.png)
](url)

**Comment by CpdnCristiano** [comment]
@roipeker  was very important for the beginning

**Comment by ghenry** [comment]
Nice work all! What do you have planned?

**Comment by CpdnCristiano** [comment]
I will wait for the approval of the [jetbrains](https://plugins.jetbrains.com/plugin/14984-getx-snippets/), and making some improvements

**Comment by ghenry** [comment]
Just tried to install it following your instructions at https://github.com/CpdnCristiano/getx_intellij_snippets but it says it's incompatible with this version. I'm running Android Studio:

Android Studio 3.6.3
Build #AI-192.7142.36.36.6392135, built on April 14, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.7.11-200.fc32.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 12
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: com.bloc.intellij_generator_plugin, com.thoughtworks.gauge, com.perl5, com.vladsch.idea.multimarkdown, org.jetbrains.kotlin, com.google.services.firebase, Dart, io.flutter, org.sylfra.idea.plugins.linessorter

**Comment by CpdnCristiano** [comment]
I'm working on a new update..

**Comment by ghenry** [comment]
Anything I can help with?

**Comment by CpdnCristiano** [comment]
@ghenry 
New version [**click here**](https://github.com/CpdnCristiano/getx_intellij_snippets/raw/master/plugin/getx_snippets-1.0.2.jar)
funcional na 4.0

**Comment by Nipodemos** [comment]
@CpdnCristiano let us know when this goes to intellij store 😄

**Comment by CpdnCristiano** [comment]
@Nipodemos.
Warning yes, but do not continue, there is already another guy who started first, he is also waiting for approval.
[repository](https://github.com/cjamcu/getx-snippets-intelliJ/)

**Comment by CpdnCristiano** [comment]
it was approved guys
![image](https://user-images.githubusercontent.com/54460776/91918636-dff8d700-ec99-11ea-931a-c31e6259b11c.png)

**Comment by jonataslaw** [comment]
Thanks!
Now we need to update the readme with the link.
But I think it can be closed now.
Thanks to everyone involved, you are awesome!

**Comment by ghenry** [comment]
Should it not be GetX?
