### ISSUE TITLE
RxList value is protected

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#540]
I see the value interface in RxList has been changed to "protected".
Is this something intentional or bug?
What is the equivalent way to get the value?

  @protected
  List<E> get value {
    if (getObs != null) {
      getObs.addListener(subject.stream);
    }
    return _list;
  }

**Comment by Nipodemos** [comment]
@jasonlaw hello! you don't need .value anymore for lists and for maps and sets
simply use the list variable directly

@jonataslaw This is a breaking change, we need to make some message to teach how to adapt to that change

**Comment by jonataslaw** [comment]
I think the documentation was clear about not using .value in lists and maps.
However, I think this may have caused breaking for users who have not read this information.
I don't know if the @protected annotation allows messages like @deprecated, if it does I will insert a note asking to remove the ".value" from the code.

**Comment by alexkharech** [comment]
> I think the documentation was clear about not using .value in lists and maps.
> However, I think this may have caused breaking for users who have not read this information.
> I don't know if the @Protected annotation allows messages like @deprecated, if it does I will insert a note asking to remove the ".value" from the code.


i get the following error when accessing directly without ".value"
get 3.6.2
```
[Get] the improper use of a GetX has been detected. 
      You should only use GetX or Obx for the specific widget that will be updated.
      If you are seeing this error, you probably did not insert any observable variables into GetX/Obx 
      or insert them outside the scope that GetX considers suitable for an update 
      (example: GetX => HeavyWidget => variableObservable).
      If you need to update a parent widget and a child widget, wrap each one in an Obx/GetX.
```

**Comment by jonataslaw** [comment]
Please, read note on:
https://github.com/jonataslaw/getx/commit/4b61419e30ef353479b41917214389bae8b52222

I recommend you upgrade to 3.7, use a clean Flutter, and definitely, you will only have problems with lists (like the error above) if you are not using any of its properties.
list.value was serving as a workaround to circumvent the above message (which only appears if you are doing something wrong), and for code security, it is now protected to avoid inconsistency in the code.
However, version 3.6.2 was a transition version, which required some additional steps in some cases, in the current version you literally need to exclude the ".value" and everything will work normally.
Please update the library, and if the problem persists, open an issue with the code you are using, and we can help you use Getx correctly, or do it on discord/telegram/slack, if I have it online I try to help you.
