### ISSUE TITLE
about update()

### ISSUE THREAD

**Issue by libexdui** [jonataslaw/getx#545]
**update() without ids?.**
I thought update() is notify to every listener,  that i saw  it sent to every one without listener ids;

fake bloc:
>Future getInfo() async {
>    memberA= null;
>    memberB= [];
>    update( withIds : true ); // i need a clear state and notify to every member on this class
>
>    //load A, (sync  base information) 
>    memberA = await dio.get(A);
>    update( withIds : false );   // notify , without Ids
>
>   //load B, (async  extent information).
>    dio.get(B).then((v) {
>     memberB = v;
>      update(['B']);
>    });
>  }

=================================
fake view:
>CustomScrollView(
>slivers: [
>GetBuilder<bloc> ((b)=> b.memberA.a),  // show base infomation (on other class)
>GetBuilder<bloc> ((b)=> b.memberA.b), //show base infomation  (on other class)
>GetBuilder<bloc> ((b)=> b.memberB.x, id:'B' ), //other async call to show extent infomation (on other class)
>]
>)

=================================
so i want to be like this ： 

>void update({List<String> ids, bool condition = true, **bool withIds = false**}) {
>    if (!condition) return;
>    if (ids == null) {
>      _updaters.forEach((rs) => rs(() {}));
>      **if (withIds) _updatersIds.forEach((e) => e.call(() {}));**
>    } else {
>      ids.forEach((e) => _updatersIds[e]?.call(() {}));
>    }
>  }`

=================================

emmm,i'm so sorry about md format...   :(

**Comment by jonataslaw** [comment]
```dart
update(['id']) // Only update GetBuilder that has that unique Id.
update(): // updates all listeners that have no id.
update(['id1', 'id2', 'id3']) // update all Ids of array
```
If you want to update everyone who has an ID, simply insert all Ids into the array.
I think that if this is a resource request, for now there is no interest in implementing it, that may change in the future if there is commotion in the community for this, but for now, I am closing this.

**Comment by Nipodemos** [comment]
While you're here, let me teach one or two things about markdown:

if you want to paste code, you can do it like this:

![image](https://user-images.githubusercontent.com/11494727/91885906-e584fb80-ec5e-11ea-8009-a56cd29b27df.png)


and it will be like this:
```dart
CustomScrollView(
slivers: [
GetBuilder ((b)=> b.memberA.a), // show base infomation (on other class)
GetBuilder ((b)=> b.memberA.b), //show base infomation (on other class)
GetBuilder ((b)=> b.memberB.x, id:'B' ), //other async call to show extent infomation (on other class)
]
)
```
\```dart
your code goes here
\```
three ticks in the beginning ( \` ) with the name of the language
and three ticks in the end ( \` ) 


if you put a bunch of = under some text, it will become a title

how you writed:
```
this is a title
===================
```
what it becomes:

this is a title
===================

that's why in the other issue from you, the letters got very big

if you want to learn all of markdown, you read see here: https://guides.github.com/features/mastering-markdown/

hope it helps somehow 😄

**Comment by libexdui** [comment]
> 当你在这里，让我教一两件关于马克减少的事情：
> 
> 如果要粘贴代码，可以这样操作：
> 
> ![image](https://user-images.githubusercontent.com/11494727/91885906-e584fb80-ec5e-11ea-8009-a56cd29b27df.png)
> 
> 这将是这样的：
> 
> ```dart
> CustomScrollView(
> slivers: [
> GetBuilder ((b)=> b.memberA.a), // show base infomation (on other class)
> GetBuilder ((b)=> b.memberA.b), //show base infomation (on other class)
> GetBuilder ((b)=> b.memberB.x, id:'B' ), //other async call to show extent infomation (on other class)
> ]
> )
> ```
> 
> ''dart
> 你的代码转到这里
> '''
> 三个滴答声在开头 （ '） 与语言
> 的名称和三个滴答声在结束 （ ）
> 
> 如果你把一堆 + 放在一些文本下， 它将成为一个标题
> 
> 您如何写作：
> 
> ```
> this is a title
> ===================
> ```
> 
> 它变成什么：
> 
> # 这是一个标题
> 这就是为什么在另一个问题从你， 字母得到了非常大的
> 
> 如果你想学习所有的标记， 你读看这里： https://guides.github.com/features/mastering-markdown/
> 
> 希望它以某种方式帮助😄

:D thank you!

**Comment by libexdui** [comment]
> While you're here, let me teach one or two things about markdown:
> 
> if you want to paste code, you can do it like this:
> 
> ![image](https://user-images.githubusercontent.com/11494727/91885906-e584fb80-ec5e-11ea-8009-a56cd29b27df.png)
> 
> and it will be like this:
> 
> ```dart
> CustomScrollView(
> slivers: [
> GetBuilder ((b)=> b.memberA.a), // show base infomation (on other class)
> GetBuilder ((b)=> b.memberA.b), //show base infomation (on other class)
> GetBuilder ((b)=> b.memberB.x, id:'B' ), //other async call to show extent infomation (on other class)
> ]
> )
> ```
> 
> ```dart
> your code goes here
> ```
> three ticks in the beginning ( ` ) with the name of the language
> and three ticks in the end ( ` )
> 
> if you put a bunch of = under some text, it will become a title
> 
> how you writed:
> 
> ```
> this is a title
> ===================
> ```
> 
> what it becomes:
> 
> # this is a title
> that's why in the other issue from you, the letters got very big
> 
> if you want to learn all of markdown, you read see here: https://guides.github.com/features/mastering-markdown/
> 
> hope it helps somehow 😄

:D thank you!

**Comment by libexdui** [comment]
> ```dart
> update(['id']) // Only update GetBuilder that has that unique Id.
> update(): // updates all listeners that have no id.
> update(['id1', 'id2', 'id3']) // update all Ids of array
> ```
> 
> If you want to update everyone who has an ID, simply insert all Ids into the array.
> I think that if this is a resource request, for now there is no interest in implementing it, that may change in the future if there is commotion in the community for this, but for now, I am closing this.

i do not think so , because ids(listener) & listener are not same object , and GetX  do update() with these object in the same method, 
i also think there be have these method to define: 
```dart
update()  //for listener
updateIds( [ ids] ) // for ids' listener , if ids is null , just all of ids 
updateAll()  // for all .
```
i know how to make it right ( i just won't to define an value to save all of ids or enter more Ids , they are so easy to overlook if the project is on a team , and that is not a good solution ), and i want to GetX easily .
you should reconsider about this...
