### ISSUE TITLE
Keep BottomNavigationBar when push to new screen with Get.to()

### ISSUE THREAD

**Issue by stjfk** [jonataslaw/getx#552]
Hi,

I know, it's not a getx problem.
But is something like this possible with getx?

for example: https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf

**Comment by roipeker** [comment]
No widget (yet) to deal with nested navigators, the "key" (pun intended) is to use  `Navigator( key: Get.nestedKey(int) ...` and any **GetX** navigation command using the same id (int) that you use to create the nestedKey.

I put together a [demo](http://roi-getx-subnav-colors.surge.sh/) as reference.
[source](https://gist.github.com/roipeker/e89e197a2dcd03802a74d214b450ab87),

Hope you find it useful.

**Comment by stjfk** [comment]
Thanks, very useful.

I will try as soon as possible.

**Comment by stjfk** [comment]
Hi again, I'm moving on your reference.
But I can't access the list (for runtimeType etc) under Navigator. Can I access?

![1](https://user-images.githubusercontent.com/70009860/98441003-60f6a380-210d-11eb-83e2-655e2fd48d3d.png)

> No widget (yet) to deal with nested navigators, the "key" (pun intended) is to use `Navigator( key: Get.nestedKey(int) ...` and any **GetX** navigation command using the same id (int) that you use to create the nestedKey.
> 
> I put together a [demo](http://roi-getx-subnav-colors.surge.sh/) as reference.
> [source](https://gist.github.com/roipeker/e89e197a2dcd03802a74d214b450ab87),
> 
> Hope you find it useful.

**Comment by tuanbs** [comment]
> No widget (yet) to deal with nested navigators, the "key" (pun intended) is to use `Navigator( key: Get.nestedKey(int) ...` and any **GetX** navigation command using the same id (int) that you use to create the nestedKey.
> 
> I put together a [demo](http://roi-getx-subnav-colors.surge.sh/) as reference.
> [source](https://gist.github.com/roipeker/e89e197a2dcd03802a74d214b450ab87),
> 
> Hope you find it useful.

I tried this example but found 2 issues. Firstly, it loads all 3 tabs in parralle at the beginning. Secondly, tapping the status bar doesn't scroll to top on iOS which is an important feature. Any idea or workaround?
