### ISSUE TITLE
Get arguments object on the child object from Get.to(widgetPage, arguments)

### ISSUE THREAD

**Issue by shariful2011** [jonataslaw/getx#553]
I am using your package(Version 3.5.1) which is an awesome package. I have no problem with your package, but I am stuck I don't know what to do here. I wanna navigate to a page with an argument param I belive which is an object type and wanna pass that object to that page's(Get.to()) object which is a type of PassModel.

Here is how I want to navigate
```
Get.to(
PasswordForm(),
arguments: _list,
);
```
Here is the object

```
final PassModel _list = PassModel();
_allPass().forEach((element) {
if (element.hostname == suggestionList[index]) {
_list.hostname = element.hostname;
_list.id = element.id;
}
});
```
How can I get this object from PasswordForm?

**Comment by shariful2011** [comment]
I solved my issue using final PassModel _passdata = Get.arguments; on the PasswordForm.

**Comment by Nipodemos** [comment]
Glad you found it :D
