### ISSUE TITLE
Rx >>= operator should be changed to <<=

### ISSUE THREAD

**Issue by kranfix** [jonataslaw/getx#558]
## Problem

The current api por a Rx object could be confused for emit a new value in a Rx implementation  
https://github.com/jonataslaw/getx/blob/d942581e47f797647ee7e95a7554a540d0ca0117/lib/src/state_manager/rx/rx_core/rx_impl.dart#L25  
 

```dart
// Currently
counter >>= 3; // Is counter injecting data to a const value?

// Should be
counter <<= 3; // A const value is injected to counter
```

Regardless of whether the feature is completed or tested, the operator should be according to its intention.

**Comment by jonataslaw** [comment]
@roipeker What do you think?
How did you implement this feature, I'll let you answer that

**Comment by roipeker** [comment]
@jonataslaw, @kranfix I implemented the << feature based on "votes" :D , it was marked as experimental, and since most of devs are already using `rx.value` or `rx()` ... I didn't touch it again.
I definitly agree with the `<<` operator, makes more "sense" (although still looks very strange).

**Comment by kranfix** [comment]
I know that it's strange in Flutter, but as an old C++ dev, the << operator is very clear.

```C++
std::cout << "some value" << endl;
```

Where `cout` is a `stream` object.

**Comment by kranfix** [comment]
On the other hand, this discussion it not about whether that feature should exist (I would like to), but also whether the operator is best meanwhile or later.

**Comment by kranfix** [comment]
@roipeker If you are agree, will you update it or do you prefer me to send a PR?
