### ISSUE TITLE
[Feature Request] Translation String extension conflict

### ISSUE THREAD

**Issue by fabriciovergara-mooov** [jonataslaw/getx#567]
First of all, thanks for awesome this package! 

**Is your feature request related to a problem? Please describe.**
When using  [easy_localization](https://github.com/aissat/easy_localization/blob/661327d9a2338ac1342380381967b4021ebe773b/lib/src/public_ext.dart#L62) there is conflict with String extension .tr() when just import [route manager](url).

Even though GetX has a translation feature, my current project require a more robust solution due to requirement to support plural and gender modifiers, plus unified translation json file shared with web-frontend

**Describe the solution you'd like**
Move public translation utilities to another index file and keep route manager file exclusive for routing.

```dart
import 'package:get/route_manager.dart';
import 'package:get/translation_manager.dart';
```

**Comment by sleepingkit** [comment]
Same request... I can't update the GetX package if this isn't fixed.

**Comment by Nipodemos** [comment]
fixed in https://github.com/jonataslaw/getx/commit/cfacb4a33f1e9b9a5f17401fd115966180d5422a
