### ISSUE TITLE
Transition.size broken since 3.6.0

### ISSUE THREAD

**Issue by QuentinSc** [jonataslaw/getx#570]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
Hello, just jump from 3.2 to 3.8. A transition doesn't work anymore (Transition.size)
This bug seems present since the 3.3 release

**To Reproduce**
1. Use Get.to(YourPage(). transition: Transition.size) to navigate whre you want
2. You get a flutter error 'curve != null': is not true
**Expected behavior**
Navigation with the size transition on the page I specified

**Screenshots**
![image](https://user-images.githubusercontent.com/16439299/92332365-c8489680-f07d-11ea-8988-7c4ac3cea96d.png)

**Flutter Version:**
1.20.3

**Getx Version:**
3.3

**Describe on which device you found the bug:**
Android Q Emulator 

**Minimal reproduce code**
 Get.to(YourPage(). transition: Transition.size)

**Comment by roipeker** [comment]
This [PR](https://github.com/roipeker/getx/commit/1379a02da68b73174e50434466ca986f67e89d09) fixes the issue and adds optional parameters to most navigation methods (and `Get.dialog()`).
