### ISSUE TITLE
barrier dismissible option for defaultDialog

### ISSUE THREAD

**Issue by ThomasLilley** [jonataslaw/getx#572]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**
Get.dialog has the barrier dismissible option but defaultDialog does not, which means its not very useful for dialogs requiring a user response

**Describe the solution you'd like**
barrier dismissible param added to defaultDialog

**Describe alternatives you've considered**
using Get.dialog and trying to match design of defaultDialog

**Comment by jonataslaw** [comment]
Added on 3.10
