### ISSUE TITLE
HELP: Routes Middleware observer the method update was called on null

### ISSUE THREAD

**Issue by changalberto** [jonataslaw/getx#575]
I'm getting this error following the exact Routes Middleware example in the readme.
![image](https://user-images.githubusercontent.com/24946/92436467-60bc4500-f16a-11ea-9c7e-59003b04d49d.png)

![image](https://user-images.githubusercontent.com/24946/92436511-7598d880-f16a-11ea-8c72-02011bbfa709.png)

**Comment by jonataslaw** [comment]
Fix on 3.10

**Comment by pzehle** [comment]
No this is not fixed, it is just broken and not working.
