### ISSUE TITLE
How to use multiple navigators with Getx?

### ISSUE THREAD

**Issue by Ditway** [jonataslaw/getx#577]
Anyone can tell me?
thank you.
in stackoverflow:
https://stackoverflow.com/questions/46502751/how-to-use-multiple-navigators

**Comment by unacorbatanegra** [comment]
Don't use this channel to ask for suport questions.
This is only for a features / bugs.
Ask in the group of telegram / discord.

**Comment by eduardoflorence** [comment]
Discord invite: https://discord.com/invite/9Hpt99N

**Comment by jonataslaw** [comment]
Duplicate of https://github.com/jonataslaw/getx/issues/552
As it is not an issue, nor a resource request, I am closing this.
See the @roipeker comment for a reference of example usage and source code: https://github.com/jonataslaw/getx/issues/552#issuecomment-686158966
