### ISSUE TITLE
GetUtils.regex not found after update to   get: ^3.8.0

### ISSUE THREAD

**Issue by Eng-MohamedGadala** [jonataslaw/getx#582]
**Describe the bug**
  GetUtils.regex not found after update to   get: ^3.8.0

**Flutter Version:**
Flutter 1.21.0-9.2.pre • channel beta

**Getx Version:**
get: ^3.8.0

**Minimal reproduce code**
  final RegExp p1 = RegExp(GetUtils.regex.passwordEasy);

**Comment by eduardoflorence** [comment]
It was removed in version 3.6.2, as it was a code that belonged to another lib.
Watch this [commit](https://github.com/jonataslaw/getx/commit/892b7504642acd1174a4153283c5b140ec0edf76).
You can do this:
```dart
final RegExp p1 = RegExp(r'^\S{8,}$');
```

Commit reference above:
```dart
// Password (Easy) Regex
// Allowing all character except 'whitespace'
// Minimum character: 8
Pattern passwordEasy = r'^\S{8,}$';
```
