### ISSUE TITLE
Cannot access arguments for nested navigators

### ISSUE THREAD

**Issue by AcnoSaga** [jonataslaw/getx#584]
As of Get 3.10.1, there seems to be no way to access currentRoute and arguments etc. for nested naviagtors. Can we have an API to select navigator by id for these things (as we do when we navigate)?

**Comment by rizalashidiq97** [comment]
I have this issue as well .

**Comment by rizalashidiq97** [comment]
@mention https://github.com/jonataslaw/getx/issues/179

**Comment by rizalashidiq97** [comment]
closed#179

**Comment by rizalashidiq97** [comment]
closed #179

**Comment by rizalashidiq97** [comment]
#179

**Comment by rizalashidiq97** [comment]
GH-179

**Comment by rizalashidiq97** [comment]
#179

**Comment by rizalashidiq97** [comment]
#179

**Comment by jonataslaw** [comment]
Duplicate of https://github.com/jonataslaw/getx/issues/179
Thanks @rizalashidiq97
