### ISSUE TITLE
close.then function

### ISSUE THREAD

**Issue by hkndzdr** [jonataslaw/getx#597]
Is there a 'close.then function' as in the default snackbar? After the snack bar is closed, I have to redirect to a different page.

**Comment by unacorbatanegra** [comment]
Don't use this channel to ask for support question, use the telegram/discord/slack group.

**Comment by jonataslaw** [comment]
Please, read https://pub.dev/packages/get/changelog#380
This will answer your question.
And please ask support questions only on the platform channels. These spaces are for issues and resource requests.
