### ISSUE TITLE
Is it possible to use Get package for apps that use CupertinoApp()?

### ISSUE THREAD

**Issue by intraector** [jonataslaw/getx#599]
GetX package readme says:

-  Step 1: Add "Get" before your MaterialApp, turning it into GetMaterialApp

  `  void main() => runApp(GetMaterialApp(home: Home()));`

-     Note: This step in only necessary if you gonna use route management (Get.to(), Get.back() and so on). If you not gonna use it then it is not necessary to do step 1

I'm creating an app for iOS and therefore I use CupertinoApp() widget instead of MaterialApp(). And I want to use route management as well.

[Is it possible to use Get package for apps that use CupertinoApp() ?](https://stackoverflow.com/questions/63856123/is-it-possible-to-use-get-package-for-apps-that-use-cupertinoapp)

**Comment by roipeker** [comment]
Its partially possible. You will lose the shortcuts for Routes(dialogs, snackbars, navigation), auto memory management of dependency injection, translation capabilities. But you can use the rest of the cool stuffs, State management will still work with dependency injection and GetBuilder/GetX, and Observables are independent as well, and most Extension methods are also standalone. So you can definetly use it, but only some parts of the lib. Btw, it would be awesome to have some feedback the usage of GetX in a CupertinoApp!

**Comment by yeras-is** [comment]
copying my response from stackoverflow
> You could set "Cupertino like" configs in Get.config. E.g. I've made app that uses Cupertino transition

**Comment by Nipodemos** [comment]
But don't you need a `CupertinoApp()` in the widget tree to be able to use cupertino widgets?
tbh I don't know

**Comment by yeras-is** [comment]
You dont need a ```CupertinoApp()```  to use ```CupertinoTabScaffold``` or ```CupertinoPageScaffold```. I've used it in ```GetMateruialApp``` and it works. Material Widgets in this case should be wrapped with ```Material```

**Comment by jonataslaw** [comment]
I've been on Flutter since the launch of the alpha version in 2017. I never used CupertinoApp, and for me it's just syntactic sugar.
GetMaterialApp will allow you to use all elements of iOS, as mentioned by the kook, CupertinoTabScaffold, CupertinoPageScaffold, and CupertinoDialog, as well as CupertinoBottomSheet, all work with GetMaterialApp.
If anyone has a good reason for this, we will add a CupertinoApp in the future, but for now, I personally do not think it is necessary.

**Comment by intraector** [comment]
With CupertinoApp we don't have to think about proper screen transitions or scroll physics, it works as intented on target platform without additional efforts.

**Comment by puntodamar** [comment]
i'm currently using getx with [Flutter Platform Widget](https://pub.dev/packages/flutter_platform_widgets) and I can use `Get.off()` with CupertinoApp

**Comment by Nipodemos** [comment]
> With CupertinoApp we don't have to think about proper screen transitions or scroll physics, it works as intented on target platform without additional efforts.

To be honest that transition thing is an issue that are here for ages, from time to time shows up a new issue regarding transitions.

If CupertinoApp solves this then it would be nice

**Comment by vimmerru** [comment]
> i'm currently using getx with [Flutter Platform Widget](https://pub.dev/packages/flutter_platform_widgets) and I can use `Get.off()` with CupertinoApp

Could you explain how to you use this? I am trying to do it right now and see problems. Any Cupertino scaffolds and widgets don't have theme data applied inside of GetMaterialApp.

**Comment by vimmerru** [comment]
> I've been on Flutter since the launch of the alpha version in 2017. I never used CupertinoApp, and for me it's just syntactic sugar.
> GetMaterialApp will allow you to use all elements of iOS, as mentioned by the kook, CupertinoTabScaffold, CupertinoPageScaffold, and CupertinoDialog, as well as CupertinoBottomSheet, all work with GetMaterialApp.
> If anyone has a good reason for this, we will add a CupertinoApp in the future, but for now, I personally do not think it is necessary.

It works, but i don't see any obvious way how to configure theme data, transitions and etc... Especially it looks like headache for cross-platform solutions like https://pub.dev/packages/flutter_platform_widgets. 

It looks like real blocker to use Get for routing and DI as seems it forces material that a lot of people don't want. It would be nice to at least provide obvious documentation how to use it with any app wrapper.

**Comment by intraector** [comment]
> It looks like real blocker to use Get for routing and DI as seems it forces material that a lot of people don't want. It would be nice to at least provide obvious documentation how to use it with any app wrapper.

I do agree. Had to switch back to Provider. And I've got memory leaks issues as well, so I suggest you to make sure all your Getxcontrollers are really removed from memory whenever they're not in use anymore.

**Comment by vimmerru** [comment]
> I've been on Flutter since the launch of the alpha version in 2017. I never used CupertinoApp, and for me it's just syntactic sugar.
> GetMaterialApp will allow you to use all elements of iOS, as mentioned by the kook, CupertinoTabScaffold, CupertinoPageScaffold, and CupertinoDialog, as well as CupertinoBottomSheet, all work with GetMaterialApp.
> If anyone has a good reason for this, we will add a CupertinoApp in the future, but for now, I personally do not think it is necessary.

@roipeker 

Feedback is poor:

1. No any information or instructions are present
2. It is very strange that non-ui library depends on platform-specific UI
3. No obvious way to use Routing and DI without GetMaterialApp. No any information what part of library will work, what not.
4. If use GetMaterialApp with Cupertino widgets it isn't obvious how to use themes and customize platform-specific behavior

**Comment by roipeker** [comment]
No idea why you quote me, but:
1- agree
2- GetX HAS a UI part, all dialogs, snackbars etc works around the MaterialApp navigation.
3- the autosetup of getx around GetMaterialApp provides several lib features, like navigation, translation, theme access, etc. it would be great to abstract that away and have a way to deal with cupertino app or widgetApp... but the change is huge in the core, and that would mean asking the user to do a major setup himself, which is super dangerous.
4- I have no experience on that, so cant provide feedback.

You can use Getx only for state management and DI.
If u use GetBuilder with GetxControllers, u will have a lifecycle as u mount/unmount widgets

**Comment by vimmerru** [comment]
> 2- GetX HAS a UI part, all dialogs, snackbars etc works around the MaterialApp navigation.

Routing can be considered as part of UI, but it is definitely different from platform-specific widgets and behavior.  I believe Navigator isn't designed to be always part of MaterialApp and with Navigator.of you can get app-agnostic access to this widget. 

>  but the change is huge in the core, and that would mean asking the user to do a major setup himself, which is super dangerous.

Something like `Get.setupRoutes()` called in right place can be much more welcome.

> You can use Getx only for state management and DI.

I am not sure that DI features will correctly work without routing. For state management it looks great, but all other features add some feeling of unreliability.

**Comment by puntodamar** [comment]
> > i'm currently using getx with [Flutter Platform Widget](https://pub.dev/packages/flutter_platform_widgets) and I can use `Get.off()` with CupertinoApp
> 
> Could you explain how to you use this? I am trying to do it right now and see problems. Any Cupertino scaffolds and widgets don't have theme data applied inside of GetMaterialApp.

I injected it directly for each widgets. for example : 
`return PlatformSlider(
  onChanged: (bool value) {},
  value: value,
  material: (_, __)  => MaterialSliderData(...),
  cupertino: (_, __) => CupertinoSliderData(...)
);`

PS :
this is just a hobby project of mine to learn flutter.

**Comment by puntodamar** [comment]
PS : this is just a hobby project of mine to learn flutter.

**Comment by vimmerru** [comment]
Just though that in CupertinoTabScaffold you usually have new instance of Navigator to maintain independent stack for each tab. As i understand it will be impossible to support with current routing approach.

**Comment by roipeker** [comment]
> Just though that in CupertinoTabScaffold you usually have new instance of Navigator to maintain independent stack for each tab. As i understand it will be impossible to support with current routing approach.

You can always create your own navigator assign a GlobalKey (Get.addKey(int)) and use Get.to and other shortcuts with it. Yet there will be no Get observer to remove controllers from DI (nor bindings). So u will have to manually manage that.

**Comment by puntodamar** [comment]
> > i'm currently using getx with [Flutter Platform Widget](https://pub.dev/packages/flutter_platform_widgets) and I can use `Get.off()` with CupertinoApp
> 
> Could you explain how to you use this? I am trying to do it right now and see problems. Any Cupertino scaffolds and widgets don't have theme data applied inside of GetMaterialApp.

Update : 

try this setup : 
```
  runApp(
      GetMaterialApp(
    theme: ColorHelper.materialThemeData(),
    localizationsDelegates: [
      DefaultMaterialLocalizations.delegate,
      DefaultCupertinoLocalizations.delegate,
      DefaultWidgetsLocalizations.delegate,
    ],
    home: PlatformApp(
      localizationsDelegates: [
        DefaultMaterialLocalizations.delegate,
        DefaultCupertinoLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
      ],
      material: (_, __) =>
          MaterialAppData(theme: ColorHelper.materialThemeData()),
      cupertino: (_, __) =>
          CupertinoAppData(theme: ColorHelper.cupertinoThemeData()),
    ),
    // debugShowCheckedModeBanner: false,
    initialRoute: SplashScreenExample.routeName,
    getPages: []
```

**Comment by vimmerru** [comment]
> try this setup

@puntodamar Unfortunately it can't work as Navigator that Get uses placed under PlatformApp.

**Comment by vimmerru** [comment]
@roipeker FYI: As you requested Cupertino app experience with get here is my notes. I tried building basic boilerplates few days. My final decision about Get is the following:

1. Flutter has a lot of bugs/strange behavior related to using of Cupertino widgets inside of Material app related theming, localization, routing and etc... Some bad looking workarounds exists, but present on SO only.
2. GetX support most of functionality for Material apps only. Example theming, routing, DI .
3. Obx widget and related Rx approach looks suitable for mid-sized apps.
4. Custom Rx wrappers without hope to be language/community standard look unreliable.

So i decided to use get short term for GetX-based state management and avoid any other futures as they add a lot of limitations to app. Long term i would prefer custom get-like solution based on native streams. Thin wrapper over native routing looks fine enough, For DI here are some acceptable options starting from provider that give much more feeling of control.

**Comment by eduardoflorence** [comment]
GetX version 3.17.0 added GetCupertinoApp (https://pub.dev/packages/get/changelog)
I will close this issue, because the requested feature already exists.
