### ISSUE TITLE
We should make an flutter app using getx.

### ISSUE THREAD

**Issue by mohak852** [jonataslaw/getx#605]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**
We should make a flutter app using getx where we should help people in learning flutter with getx. We should add getx docs and some other useful articles and we should make this offline.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by Nipodemos** [comment]
there is already the example app that is pretty good in my opinion. There are also some articles and some videos mentioned in the documentation as well. If you want to make a Gist with some app code using GetX or a repo with examples, we will be more than glad to put the links of it in the docs as well.

As this is not an issue, i'm closing it
