### ISSUE TITLE
[Feature Request]: Open Drawer via Get.drawer (like Get.snackbar etc.)

### ISSUE THREAD

**Issue by GoldenSoju** [jonataslaw/getx#614]
When I add a drawer to a scaffold, it opens easily and without problems via Gestures (sliding from left to right),
but when I want to open it on a button click without having an AppBar, I would have to change it to a StatefulWidget.

So it would be great to be able to open the drawer everywhere, just like it is possible with e.g. snackbars or other widgets at the moment thanks to GetX.

(In case you decide to add drawers to GetX, please note that there is also an endDrawer widget (which opens from the right side). Maybe you want to add it, too.)

**Comment by jonataslaw** [comment]
Drawer depends on a ScaffoldState, while the Getx context provides a NavigatorState.
So it would not be possible to create this resource, even because there is another solution available: Create a globalKey in your controller, and attach it to your Scaffold. You can open and close the drawer directly from your globalKey

**Comment by matthewkooshad** [comment]
@jonataslaw could you give an example of this: "Create a globalKey in your controller, and attach it to your Scaffold. You can open and close the drawer directly from your globalKey" please?

**Comment by jonataslaw** [comment]
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  Get.put(Controller());
  runApp(GetMaterialApp(home: Home()));
}

class Controller extends GetxController {
  var scaffoldKey = GlobalKey<ScaffoldState>();

  void openDrawer() {
    scaffoldKey.currentState.openDrawer();
  }

  void closeDrawer() {
    scaffoldKey.currentState.openEndDrawer();
  }
}

class Home extends GetView<Controller> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      key: controller.scaffoldKey,
      drawer: Drawer(
        child: ListView(
          padding: EdgeInsets.zero,
          children: <Widget>[
            DrawerHeader(
              child: Text('Drawer Header'),
              decoration: BoxDecoration(
                color: Colors.blue,
              ),
            ),
            ListTile(
              title: Text('Item 1'),
              onTap: controller.closeDrawer,
            )
          ],
        ),
      ),
      body: Center(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          RaisedButton(
            onPressed: controller.openDrawer,
            child: Text('open drawer'),
          )
        ],
      )),
    );
  }
}

```

**Comment by matthewkooshad** [comment]
@jonataslaw i think this var scaffoldKey = GlobalKey<ScaffoldState>(); part leads me to an issue of Multiple widgets used the same GlobalKey. Because, i have the drawer used on all of the pages in the app. i tried various other Get.key related approaches, but i wasn't able to do openDrawer methods unless using GlobalKey<ScaffoldState>(). can you point me in the right direction to use this same Drawer on all of my pages?

**Comment by engmsaleh** [comment]
@matthewkooshad I have used a workaround by making a delegate method from all my views into the main container controller and making them fire the drawer from there

as a code snippet, I have my main container is `IndexStack`
```
 return Scaffold(
        key: controller.pagesViewScaffoldKey,
        drawer: DrawerView(),
        body: IndexedStack(
          index: controller.currentTabIndex,
          children: [
            NotificationsView(
              onSideMenuPressed: () {
                controller.openDrawer();
              },
            ),
            DiaryView(
              onSideMenuPressed: () {
                controller.openDrawer();
              },
            ),
            HomeView(
              onSideMenuPressed: () {
                controller.openDrawer();
              },
            ),
            OrdersView(
              onSideMenuPressed: () {
                controller.openDrawer();
              },
            ),
            SettingsView(
              onSideMenuPressed: () {
                controller.openDrawer();
              },
            ),
          ],
        ),
```
and this indexed stack has also the Drawer Widget 

Inside the controller for the *container* 
```
 var pagesViewScaffoldKey = GlobalKey<ScaffoldState>();

  void openDrawer() {
    pagesViewScaffoldKey.currentState?.openDrawer();
    update();
  }
```
Inside each of the child's views ... ex. *NotificationsView* 

```
  VoidCallback onSideMenuPressed;
  NotificationsView({required this.onSideMenuPressed});
```
