### ISSUE TITLE
How do i use settings along with Get.to

### ISSUE THREAD

**Issue by narendra02031997** [jonataslaw/getx#619]
For using firebase analytics i need to pass **RouteSettings** when moving to another page like in normal way we can achieve by following commands.
  Navigator.push(
          context,
          MaterialPageRoute(
              builder: (context) => HSectionScreen1(),
              **settings: RouteSettings(name: 'Home Page')**)); 
now in getx how do i pass this **RouteSettings** with **Get.to**

Please reply as soon as possible.

Thank you

**Comment by roipeker** [comment]
So, i know the sample covers the arguments... and u seems to care about the name, but when not using namedRoutes (using `GetMaterialApp.getPages:[GetPage()...]`), if you see the GETX logs, the RouteSettings.name takes the name from the Widget's class `runtimeType`.

In the sample below:
```bash
[GETX] GOING TO ROUTE /_Page2
```

So, you might wanna rename your pages widgets classes, or use what u suggested:

``dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class SampleRoutesApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(home: _Home());
  }
}

class _Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Home')),
      body: Center(
        child: FlatButton(
          child: Text('Go to Page 2'),
          onPressed: () {
            final arg = MyRouteData(name: 'cool arg for my route');

            // option 1
            navigator.push(MaterialPageRoute(
              builder: (_) => _Page2(),
              settings: RouteSettings(arguments: arg, name: 'my-route-2'),
            ));

            // option 2
//            Get.to(_Page2(), arguments: arg); // this will use the route name "_Page2"
          },
        ),
      ),
    );
  }
}

class MyRouteData {
  final String name;
  MyRouteData({this.name});
}

class _Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final arg = Get.arguments as MyRouteData;
    print('Current route name: ${Get.currentRoute}');
    return Scaffold(
      appBar: AppBar(title: Text('Page 2')),
      body: Center(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text('My argument is:'),
          Text(arg.name, style: Get.textTheme.headline3),
        ],
      )),
    );
  }
}

```

**Comment by narendra02031997** [comment]
> So, i know the sample covers the arguments... and u seems to care about the name, but when not using namedRoutes (using `GetMaterialApp.getPages:[GetPage()...]`), if you see the GETX logs, the RouteSettings.name takes the name from the Widget's class `runtimeType`.
> 
> In the sample below:
> 
> ```shell
> [GETX] GOING TO ROUTE /_Page2
> ```
> 
> So, you might wanna rename your pages widgets classes, or use what u suggested:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:get/get.dart';
> 
> class SampleRoutesApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return GetMaterialApp(home: _Home());
>   }
> }
> 
> class _Home extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text('Home')),
>       body: Center(
>         child: FlatButton(
>           child: Text('Go to Page 2'),
>           onPressed: () {
>             final arg = MyRouteData(name: 'cool arg for my route');
> 
>             // option 1
>             navigator.push(MaterialPageRoute(
>               builder: (_) => _Page2(),
>               settings: RouteSettings(arguments: arg, name: 'my-route-2'),
>             ));
> 
>             // option 2
> //            Get.to(_Page2(), arguments: arg); // this will use the route name "_Page2"
>           },
>         ),
>       ),
>     );
>   }
> }
> 
> class MyRouteData {
>   final String name;
>   MyRouteData({this.name});
> }
> 
> class _Page2 extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     final arg = Get.arguments as MyRouteData;
>     print('Current route name: ${Get.currentRoute}');
>     return Scaffold(
>       appBar: AppBar(title: Text('Page 2')),
>       body: Center(
>           child: Column(
>         mainAxisAlignment: MainAxisAlignment.center,
>         children: [
>           Text('My argument is:'),
>           Text(arg.name, style: Get.textTheme.headline3),
>         ],
>       )),
>     );
>   }
> }
> ```

Thanks a lot
