### ISSUE TITLE
when i close bottom sheet, my controller also gets removed from memory

### ISSUE THREAD

**Issue by rustiever** [jonataslaw/getx#622]
**Describe the bug**
In HomePage im initialising the controller, then im using same controller in my custom widget. I'm using GetViewwidget to get access of controller. I have bottom sheet which will fire for button, then when i use Get.back(), my controller gets removed from memory even though the page not popped

**Expected behavior**
My controller should not be removed

**Flutter Version:Flutter 1.20.0 • channel beta**

**Getx Version:3.10.2 **

**Minimal reproduce code**
code was too big so i explained the scenario

**Comment by jonataslaw** [comment]
If the controller is being used for the first time on its bottomSheet, it is expected that when you close the bottomSheet it will be disposed. At least, this is the expected behavior.
Please, next time you open an issue, enter a reproduction code, or it will be closed briefly.

**Comment by Jojoooo1** [comment]
can't believe i did not see it coming, thanks a lot.

**Comment by rustiever** [comment]
@jonataslaw but it is not the case, HomePage() => FeedWidget() => CommentWidget() 
in the comment widget if i open and close my bottomsheet my controller gets removed, if this is the expected behaviour(removing controller) then how to make my controller persist. I could add the code but that is very huge.

**Comment by jonataslaw** [comment]
I don't think it's possible to have a use case for you to want your controller persistent. I have an application with the same dynamics, and I don't use persistent controllers. You must add something like fenix: true to lazyPut for the controller to be recreated, not to want a persistent controller for something ephemeral like a bottomSheet.

**Comment by Nipodemos** [comment]
you can make a pseudo code that represents what you are doing

you said you have three widgets, so a simple code that create three screens, initializes a controller in the first screen, use it's data in the second, open a bottom sheet and the close it.

If you do a simple code that has all these steps and the same error happens, it will be easier to understand the issue and trying to solve it
