### ISSUE TITLE
GetUtils::capitalize method!

### ISSUE THREAD

**Issue by zl910627** [jonataslaw/getx#624]
```
static String capitalize(String s, {bool firstOnly = false}) {
    if (isNullOrBlank(s)) return null;
    if (firstOnly) return capitalizeFirst(s);

    var lst = s.split(' ');
    var newStr = '';
    for (var s in lst) {
      newStr += capitalizeFirst(s);
    }
    return newStr;
  }
```

This method omits spaces between words once capitalized.
I think below function block is right one.

```
static String capitalize(String s, {bool firstOnly = false}) {
  if (isNullOrBlank(s)) return null;
  if (firstOnly) return capitalizeFirst(s);
  return s.split(' ').map(capitalizeFirst).join(' ');
}
```
 
Thank you.

**Comment by Nipodemos** [comment]
You are correct!
But that was already fixed here: https://github.com/jonataslaw/getx/commit/8c72e01212fdc433a60e0411403c8836f03c3138

The thing is that was done like just three days ago, and jonatas did not lauch the update yet
Wait just a bit until he launches the new version and the error will be gone

Just as a reminder, that commit came with a breaking change
* `capitalize` don't have the parameter `firstOnly` anymore, that's `string.capitalizeFirst` is made for
* now `capitalize` is not a function, is a getter (at least when is used as a extension from a string)

Before:
```dart
String name = "nipodemos";
name.capitalize(name);
```
now:
```dart
String name = "nipodemos";
name.capitalize;
```

**Comment by zl910627** [comment]
Main prob.
Sometime AS or VSCode does not find or autocomplete `extension` methods, so that I prefer to use static methods from Util class.

**Comment by Nipodemos** [comment]
the utils class still works, the only difference is not having the `firstOnly` parameter, and it works

**Comment by zl910627** [comment]
![image](https://user-images.githubusercontent.com/53897531/93865182-8d3e9800-fcf8-11ea-895d-f39a9adfaaad.png)
I think above code is not optimized one.

```Dart
static String capitalize(String s) {
  if (isNullOrBlank(s)) return null;
  return s.split(' ').map(capitalizeFirst).join(' ');
}
```

I think above code is better.
Thank you.

**Comment by Nipodemos** [comment]
i have never thought about the code speed when wrote that 😅 
That was the way that came to my mind at the time

Your alternative is so simple and clean that I am embarassed for not thinking that myself hahahahah. 
Do you mind make a Pull Request with this change? If you don't know how to do I can make it myself later

**Comment by zl910627** [comment]
Please check below PR.
https://github.com/jonataslaw/getx/pull/638
Thank you.
