### ISSUE TITLE
[ANDROID] On user logout app navigates to initialRoute instead of route given by authChanged()

### ISSUE THREAD

**Issue by pa2codes** [jonataslaw/getx#626]
**Describe the bug**
I am using Firebase Auth and GetX to handle my login/logout navigation.
Whenever a User logs out it should navigate the user to the authentication ('/authenticate') screen. However this is not working for Android devices (iOS works fine).

In my main.dart I define initialRoute for my GetMaterialApp:
   
```
   ...     
      supportedLocales: S.delegate.supportedLocales,
      initialRoute: '/',
      getPages: MyAppRoutes.routes,
    );
```

```
class MyAppRoutes {
  EcouAppRoutes._(); //this is to prevent anyone from instantiating this object
  static final routes = [
    GetPage(
      name: '/',
      page: () => AppStart(),
    ),
    GetPage(
      name: '/authenticate',
      page: () => Register(),
    ),
    GetPage(
      name: '/home',
      page: () => Home(),
    ), ....
```

My AuthController provides the onAuthChanged() event

```
  //reroute if User auth status changed
  Future handleAuthChanged(isLoggedIn) async{
    print("handleAuthchanged called");
    if (isLoggedIn == false){
      Get.offAllNamed('/authenticate');
    }
  }
```

On iOS user gets forwarded to '/authenticate', but on Android user gets forwarded to '/authenticate' and then '/' (check screenshot).

**To Reproduce**
1. add InitialRoute to your GetMaterialApp
2. Create app routes and provide this class to getPages
3. Create handler for authentication events from Firebase and forward on logout to specific route
4. Try user logout

**Expected behavior**
I expect the app to route to '/authenticate' without routing afterwards to initialRoute

**Screenshots**
![grafik](https://user-images.githubusercontent.com/62615295/93479380-87157980-f8fc-11ea-8017-2a190bad3042.png)

**Flutter Version:**
1.20.3

**Getx Version:**
get: '^3.7.0'

**Describe on which device you found the bug:**
Android sdk 28

**Minimal reproduce code**
see above

**Comment by jonataslaw** [comment]
Hi, GetX is a package dart, so there will be no difference in behavior on android / ios.
If you are having different behaviors, it is not related to this package, use Flutter clean, or another solution to prevent bugs from Flutter/dart.
Furthermore, there is no reproduction code in this issue, so there will be no way to help you.
Enter a reproducible code or this issue will be closed

**Comment by pa2codes** [comment]
Hi, thanks for your fast reply! I am sorry!! The Flutter clean did it.
