### ISSUE TITLE
Add child parameter in Obx,GetX, GetBuilder 

### ISSUE THREAD

**Issue by rizalashidiq97** [jonataslaw/getx#634]
Is Obx, GetX and GetBuilder has "child" parameter so that the child widget won't rebuild when parent widget changes? I have widget that I want to rebuild only the parent widget.
if not , is there a plan to add one?

**Comment by jonataslaw** [comment]
Only Widget functions can rebuild. GetX has a `builder:(_)=>` and Obx has a function `Obx(()=>)
`
Não tem como adicionar parametro Widget para eles, porque eles precisam estar em uma função.
Bem, como isso não é uma issue, estou fechando.
