### ISSUE TITLE
SingleGetTickerProviderMixin gone after updating to 3.11.1

### ISSUE THREAD

**Issue by tneotia** [jonataslaw/getx#639]
**Describe the bug**
My app had a SingleGetTickerProviderMixin on my controller to pass a vsync parameter to a TabBarController. Once I updated the package the mixin is no longer available, don't know if this is intended or not - maybe it was overlooked in the refactoring process?

**To Reproduce**
1. Create a controller and try to add the above mixin, an error will be displayed.

**Expected behavior**
The mixin should be there as was in previous versions

**Screenshots**

**Flutter Version:**
1.20.1 - pre

**Getx Version:**
3.11.1

**Describe on which device you found the bug:**
ex: Not device related

**Minimal reproduce code**
```
class SampleController extends GetxController with SingleGetTickerProviderMixin {}
```
observe the error from the IDE on Get 3.11.1.

**Comment by jonataslaw** [comment]
This PR solves it https://github.com/jonataslaw/getx/pull/632 
Today it will go to pub.dev

**Comment by tneotia** [comment]
Sorry, didn't see that... looking forward to the update. 

Btw, thanks for this amazing package, my entire app has been transformed as a result!

**Comment by jonataslaw** [comment]
Added again at 3.12
Thanks for reporting this
