### ISSUE TITLE
Get.updateLocal.. Getx auto change Direction to RTL how to stop that

### ISSUE THREAD

**Issue by ahmaddarwesh** [jonataslaw/getx#643]
Hi, I using **Getx** package from 2 month and everything is perfect.

but after last update the **Getx** change the Direction automatically when update local to `Local('ar')`
How I can stop that, because I do that manually by my design.. I don't want that happens

**Get version**
 get: ^3.11.1

**Comment by Nipodemos** [comment]
Hello
Please provide a minimal reproduce code for your issue, so it can be possible to replicate the problem locally

**Comment by ahmaddarwesh** [comment]
@Nipodemos 

**First simply I create my Translator class** 

```
class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'hello_msg':'Hello'
    },
    'ar': {
      'hello_mag':'مرحباً'
    }
  };
}

```

**Then I used it in my GetMaterialApp**
```
GetMaterialApp(
          translations: Messages(),
         ......
)
```

note: I don't use any property  in **GetMaterialApp** like :
`supportedLocales` 
`local`
`fallbackLocale`
Just used `translations`
.
.

**then when user change language to Arabic for example I call this**

` Get.updateLocale(Locale('ar'));`

and after user choosing the language I changing the font like this

```
        Get.changeTheme(
          ThemeData(
            fontFamily: Get.locale.toLanguageTag() == 'en' ? Barlow : Almarai,
          ),
        );
```

**Comment by jonataslaw** [comment]
isn't 'ar' a RTL language?

**Comment by ahmaddarwesh** [comment]
@jasonlaw 
Yes it is, but I don't want to change My Ui to RTL Direction automatically.

**Comment by jonataslaw** [comment]
Ok, I'm going to insert some option in GetMaterialApp for you to disable this behavior, since it must be the default.

**Comment by ahmaddarwesh** [comment]
@jonataslaw 
Thanks a lot for your help.
When you insert this option how I can get it?
Do I need to update package or do something else?

**Comment by Nipodemos** [comment]
@ahmaddarwesh you'll need to wait until jonatas releases the new version to everyone
You can check periodically [here](https://pub.dev/packages/get/versions)
