### ISSUE TITLE
Transition duration

### ISSUE THREAD

**Issue by omartinma** [jonataslaw/getx#649]
Hi,

I'm trying to set a transition duration for the whole app. I saw the property "transitionDuration" inside GetMaterialApp and I'm using it like that:
`transitionDuration: Duration(milliseconds: 100),`

But still transitions between screens are really slow when doing this:
`Get.to(
      NewScreen(
        isEditing: true,
      ),
      // duration: Duration(milliseconds: 100),
    );`

Else if I set the parameter duration here the transition is right. Is there any bug or am i understanding wrong the parameter transitionDuration?

I'm using last version 3.11.1 with Flutter 1.20.2.

Thanks!

**Comment by ahmaddarwesh** [comment]
after you set **transitionDuration** in **GetMaterialApp** you need to restart app because in **main.dart** cannot be affected by changes until you restart your app.

**Comment by omartinma** [comment]
Any update on this? Is a bug or am i doing something wrong? Can I help with anything?

**Comment by jonataslaw** [comment]
It's fixed on master, I'll update to pub.dev when it done.
