### ISSUE TITLE
Get.put() global singleton

### ISSUE THREAD

**Issue by XuJin186** [jonataslaw/getx#650]
Hi
When I use ` Get.put()` to get the controller, I found that the controller is a global singleton. When I enter the interface again next time, the original data still exists and is not cleared.
What I want to achieve is that the next time I enter this interface again, all data will be restored to default values

**Comment by XuJin186** [comment]
If I use `Get.create(()=>Controller())` where do you think this should be placed?

**Comment by Nipodemos** [comment]
Get.put is not global, it is attached to the route where you declared it.

So if for example you used Get.put() in the home screen, the singleton will exist as long as that screen still exist. Even when you change to other screens, you did not close the home screen yet (so it is possible to simply tab the back button and come back to the screen) 

the instance will be disposed when you explicitly remove the route

Get.create is for a very specific case, unless you know what you are doing, don't use it

**Comment by XuJin186** [comment]
I think the logic should be like this. As long as you exit or close the route, you must judge all dependencies. If this dependency is still in use, it will not be deleted. If not, it should be deleted immediately.

**Comment by jonataslaw** [comment]
Maybe Get.create + GetWidget is what you are looking for. Please respect our issue templates next time, the platform channels are appropriate for support issues, not github issues.
As this does not respect the issue opening procedure, I am closing.

**Comment by ghenry** [comment]
Or GetxService?

**Comment by XuJin186** [comment]
When I use Get.to(Demo()), I find that the path and dependencies are messy. When I use name routing, it’s good.   You can try it or I can write a demo and upload it

**Comment by XuJin186** [comment]
This is the log when I use
**[GETX] "GetMaterialController" has been initialized
[GETX] "Demo1Controller" has been initialized
[GETX] GOING TO ROUTE /Demo1
[GETX] CLOSE TO ROUTE /Demo1
[GETX] "Demo2Controller" has been initialized
[GETX] GOING TO ROUTE /Demo2
[GETX] CLOSE TO ROUTE /Demo2
[GETX] GOING TO ROUTE /Demo1
[GETX] CLOSE TO ROUTE /Demo1
[GETX] "Demo2Controller" onClose() called
[GETX] "Demo2Controller" deleted from memory
[GETX] "Demo2Controller" has been initialized
[GETX] GOING TO ROUTE /Demo2
[GETX] CLOSE TO ROUTE /Demo2
[GETX] GOING TO ROUTE /Demo1
[GETX] CLOSE TO ROUTE /Demo1
[GETX] "Demo2Controller" onClose() called
[GETX] "Demo2Controller" deleted from memory
[GETX] "Demo2Controller" has been initialized
[GETX] GOING TO ROUTE /Demo2
[GETX] CLOSE TO ROUTE /Demo2
[**]
[getDemo.zip](https://github.com/jonataslaw/getx/files/5288057/getDemo.zip)

**Comment by ghenry** [comment]
Please go to Discord or Slack etc. Thanks! :-)

**Comment by ghprod** [comment]
> When I use Get.to(Demo()), I find that the path and dependencies are messy. When I use name routing, it’s good. You can try it or I can write a demo and upload it

Please note, by using a new instance of WIdget, that's mean you are bypassing dependencies initialization.

That's why if you want to get the full power of Getx, then use named routes.

**Comment by XuJin186** [comment]
I have uploaded the DEMO. You can check it out. I think this is a bug. Maybe my English is not very good.

**Comment by ghprod** [comment]
> I have uploaded the DEMO. You can check it out. I think this is a bug. Maybe my English is not very good.

I think you should open a new issue with a template filled
