### ISSUE TITLE
Multiple Instance of a controller

### ISSUE THREAD

**Issue by Presheda** [jonataslaw/getx#652]
so far I know Get does not allow creating multiple instances of the controller and that has worked fine for me so far.

but I'm in a rare situation where I need to have multiple instances of the same controller.  Is there a way I can do this?

**Comment by Nipodemos** [comment]
Hello
This place is for issues and features requests only. If you want help with GetX you can use discord(english, spanish, portuguese), slack(english) or telegram(portuguese)

Just for completition, here is the answer:
For each instance you want to declare, you can define a tag for each one. A tag is a string that has to be unique.
Example:
```dart
Get.put(Controller(), tag: 'item 1 controller');
```

And if you want to use the controller:

```dart

// option 1: using Get.find()
Controller controller = Get.find(tag: 'item 1 controller');

// option 2: using GetBuilder
GetBuilder<Controller>(
tag: 'item 1 controller',
builder: () => YourWidget()
)

// option 3: using GetX
GetX<Controller>(
tag: 'item 1 controller',
builder: () => YourWidget()
)

**Comment by TarunNagaSai** [comment]
who can i create multiple dynamic instances of a getx controller.
