### ISSUE TITLE
The Arabic language isn't working properly.

### ISSUE THREAD

**Issue by mikeamir** [jonataslaw/getx#654]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
**Note: This bug happens only when the app starts with Locale('ar') in its locale property, but if the locale was changed later with Get,updateLocale(Locale('ar')) everything still works.**
When using translations, the Arabic language isn't working properly. Whenever the app locale changes to Locale('ar'), first, when the app starts, I get this warning "This application's locale, ar, is not supported by all of its
localization delegates.", second, all TextFields don't work and they output this error: "No MaterialLocalizations found.
TextField widgets require MaterialLocalizations to be provided by a Localizations widget ancestor."

**To Reproduce**

**Expected behavior**
Everything work just fine like when the locale is Locale('en')

**Screenshots**

**Flutter Version:**
1.20.4 : Stable Channel

**Getx Version:**
3.11.1

**Describe on which device you found the bug:**
Pixel 2 API R Emulator - Android.

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jonataslaw** [comment]
If do you uses Material Components (timePicker, datePicker), you need of MaterialDelegates. Otherwise, just ignore the message.

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
```
```dart
GetMaterialApp(
 localizationsDelegates: [
      GlobalMaterialLocalizations.delegate, // uses `flutter_localizations`
      GlobalWidgetsLocalizations.delegate,
      GlobalCupertinoLocalizations.delegate,
    ],
 supportedLocales: <Locale> [Locale ('en', 'UK'), Locale ('ar')]
```

**Comment by mikeamir** [comment]
> If do you uses Material Components (timePicker, datePicker), you need of MaterialDelegates. Otherwise, just ignore the message.
> 
> ```yaml
> dependencies:
>   flutter:
>     sdk: flutter
>   flutter_localizations:
>     sdk: flutter
> ```
> 
> ```dart
> GetMaterialApp(
>  localizationsDelegates: [
>       GlobalMaterialLocalizations.delegate, // uses `flutter_localizations`
>       GlobalWidgetsLocalizations.delegate,
>       GlobalCupertinoLocalizations.delegate,
>     ],
>  supportedLocales: <Locale> [Locale ('en', 'UK'), Locale ('ar')]
> ```

Oh, It seems like my problem was that I didn't have flutter_localizations in my pubspec.yaml.
Now it works fine. Thanks a lot

**Comment by jonataslaw** [comment]
As this has been resolved, I am closing

**Comment by ayberkcal** [comment]
I've faced same issue almost 1 year later. I think this case should mentioned in documentation.
