### ISSUE TITLE
Misaligned routes and dependencies

### ISSUE THREAD

**Issue by XuJin186** [jonataslaw/getx#659]
**Describe the bug**
When using Get.to() Get uses the current path when registering dependencies, not the path you want to go

**To Reproduce**
1. Run the project
2. Click the Demo1 button
3. `  void _registerRouteInstance<S>({String tag}) {
    _routesKey.putIfAbsent(_getKey(S, tag), () => Get.reference);
  }`  检查Get.reference的值
4. See Get.reference is /, it should be /Demo1

**Expected behavior**
`  void _registerRouteInstance<S>({String tag}) {
    _routesKey.putIfAbsent(_getKey(S, tag), () => Get.reference);
  }`
Get.reference When it should /Demo1
**Screenshots**
![微信截图_20200928092123](https://user-images.githubusercontent.com/43058612/94381500-33acf200-016c-11eb-8a95-cbc849712644.png)
![微信截图_20200928092157](https://user-images.githubusercontent.com/43058612/94381502-360f4c00-016c-11eb-93bf-fa71c82bced2.png)

**Flutter Version:**
10.0.18363.1082

**Getx Version:**
get: ^3.11.1

**Describe on which device you found the bug:**
Emulator

**Minimal reproduce code**
```dart
void main() {
  runApp(App());
}

class App extends StatelessWidget {
  App({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      home: Home(),
    );
  }
}



class Home extends StatelessWidget {
  Home({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Home"),
      ),
      body: Column(
        children: [
          RaisedButton(
            onPressed: () {
              Get.to(Demo1());
            },
            child: Text("Demo1"),
          ),
          RaisedButton(
            onPressed: () {
              Get.to(Demo2());
            },
            child: Text("Demo2"),
          )
        ],
      ),
    );
  }
}


class Demo1Controller extends GetxController {}

class Demo1 extends StatelessWidget {
  final Demo1Controller _demo1controller = Get.put(Demo1Controller());
  Demo1({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Demo1"),
      ),
    );
  }
}

class Demo2Controller extends GetxController {}

class Demo2 extends StatelessWidget {
  final Demo2Controller _demo1controller = Get.put(Demo2Controller());
  Demo2({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Demo2"),
      ),
    );
  }
}
```

**Comment by jonataslaw** [comment]
The problem it on:

```dart
return GetMaterialApp(
      home: Home(), // It's close home instance
    );
```
As I mentioned in past issues, the MaterialApp home should not receive a Widget, but a widget function.
Because of this Flutter engineering error, when closing a home instance, you are automatically calling the class's constructor, even before the MaterialApp class's constructor.

There are two ways to resolve this:
1: Using a getter instead of a final instance:
 Demo1Controller get  _demo1controller => Get.put(Demo1Controller());

2: Using named routes. You can use named routes only for the first widget, if you don't want to use named routes for the entire app:
```dart
return GetMaterialApp(
      getPages: [GetPage(name:'/': page:()=> Home())],
    );
```

**Comment by XuJin186** [comment]
> 问题就在：
> 
> ```dart
> return  GetMaterialApp（
>       home ： Home（），//它是封闭的home实例 
>     ）;
> ```
> 
> 正如我在过去的问题中提到的那样，MaterialApp主页不应接收小部件，而应接收小部件功能。
> 由于存在Flutter工程错误，因此在关闭宿主实例时，即使在MaterialApp类的构造函数之前，您也会自动调用该类的构造函数。
> 
> 有两种解决方法：
> 1：使用吸气剂代替最终实例：
> ` Demo1Controller get _demo1controller => Get.put(Demo1Controller());`
> 
> 2：使用命名路由。如果您不想为整个应用程序使用命名路由，则只能将命名路由用于第一个小部件：
> 
> ```dart
> return  GetMaterialApp（
>       getPages ： [ GetPage（name ：'/' ： page ：（）=>  Home（））]，
>     ）;
> ```

Thank you for your reply, I have tested the solution you mentioned, and it did not achieve the expected effect

**Comment by XuJin186** [comment]
The first one is OK, the second one is not OK

**Comment by Nipodemos** [comment]
@XuJin186 Can you tell us exactly what happened when you used the second option?
It was the exact same problem? It was a different one?

**Comment by XuJin186** [comment]
> @XuJin186 Can you tell us exactly what happened when you used the second option?
> It was the exact same problem? It was a different one?

Yes

**Comment by Nipodemos** [comment]
> > @XuJin186 Can you tell us exactly what happened when you used the second option?
> > It was the exact same problem? It was a different one?
> 
> Yes

I made three questions, to which one are you answering yes?

**Comment by XuJin186** [comment]
The second solution is the same as the previous error

**Comment by XuJin186** [comment]
Because the oral complaint may be unclear, I also provided the test code. Please copy it and run it to see what I said.

**Comment by eduardoflorence** [comment]
For me it worked when all routes are named and I replaced `Get.to` with` Get.toNamed`. In this case the controllers have been removed from memory
```dart
getPages: [
  GetPage(name: '/', page: () => Home()),
  GetPage(name: '/demo1', page: () => Demo1()),
  GetPage(name: '/demo2', page: () => Demo2()),
],
```
@jonataslaw this seems to be a very serious problem, because when we don't use the named routes, the controllers are not removed from memory in the `removeDependencyByRoute` method

**Comment by eduardoflorence** [comment]
I remembered the solution now, which was already mentioned in another issue:
@XuJin186, you must put `Get.put` inside the statelessWidget build method:
```dart
  @override
  Widget build(BuildContext context) {
    final Demo2Controller _demo1controller = Get.put(Demo2Controller()); // <- here
    return Scaffold(
      appBar: AppBar(
        title: Text("Demo2"),
      ),
    );
  }
```

**Comment by eduardoflorence** [comment]
My answer was based on this comment from @jonataslaw:
https://github.com/jonataslaw/getx/issues/384#issuecomment-661919495

**Comment by XuJin186** [comment]
> My answer was based on this comment from @jonataslaw:
> [#384 (comment)](https://github.com/jonataslaw/getx/issues/384#issuecomment-661919495)

Thank you very much for your reply

**Comment by eduardoflorence** [comment]
You're welcome @XuJin186, can this issue be closed?

**Comment by XuJin186** [comment]
> You're welcome @XuJin186, can this issue be closed?

I use named routes now, so I don’t know if it can solve the problem. There must be a solution. We are only pursuing the best solution.

**Comment by Nipodemos** [comment]
Since both @jonataslaw  and @eduardoflorence provided solutions and @XuJin186 started to using them, i'll close this
