### ISSUE TITLE
GetTests is not present in pub package

### ISSUE THREAD

**Issue by jamie1192** [jonataslaw/getx#660]
Changelog for `3.11.0` states "Added GetTests, a set of tools to help you create unit tests using Getx".. yet it does not exist/is not available from the GetX package?

**Comment by jonataslaw** [comment]
https://pub.dev/packages/get_test

**Comment by jamie1192** [comment]
Thanks. Probably would make more sense to specify that it's a separate package as it currently implies it is part of the current GetX package.
