### ISSUE TITLE
[GetTest] Bump Mockito version constraints 

### ISSUE THREAD

**Issue by jamie1192** [jonataslaw/getx#661]
Currently, get_test has set the version constraints for Mockito to `">=3.0.0 <4.0.0"`. Version `4.1.0` added `Fake` classes, which we currently depend on, so we're currently unable to use get_test in our project.

Can the version constraints please be updated to (ideally) support the latest Mockito version rather than being a whole major release behind.

**Comment by trevorplant** [comment]
:+1:

**Comment by jonataslaw** [comment]
Fix on get 3.12.1
