### ISSUE TITLE
Can't export Get class and Material class in same file

### ISSUE THREAD

**Issue by salehahmedZ** [jonataslaw/getx#664]
**Describe the bug**
Can't export Get class and Material class in same file

**To Reproduce**

```dart

//this will conflict 
export 'package:flutter/material.dart';
export 'package:get/get.dart';

```
**Expected behavior**

**Screenshots**
![screenshot](https://i.ibb.co/CQxH2R1/2020-09-29-08-47-52-Window.jpg)
**Flutter Version:**
Enter the version of the Flutter you are using

**Getx Version:**
^3.12.1

**Describe on which device you found the bug:**
all devices

**Minimal reproduce code**
```dart

//this will conflict 
export 'package:flutter/material.dart';
export 'package:get/get.dart';

```

**Comment by Devjone** [comment]
try

```dart
export 'package:get/get.dart' hide VoidCallback;
```

**Comment by salehahmedZ** [comment]
> try
> 
> ```dart
> export 'package:get/get.dart' hide VoidCallback;
> ```

Thanks that solved the issue
