### ISSUE TITLE
native ios transition "feel" for navigation

### ISSUE THREAD

**Issue by jtkeyva** [jonataslaw/getx#672]
when using Get.to the transition doesn't have the "personality" of native ios transitions or the standard flutter navigation feel for that matter. it just slides over and slides out pretty abruptly without any easing or elastic feeling.

i've tried both
`
Get.to(SignUp(), transition: Transition.cupertino);
`
`
Get.to(SignUp(), transition: Transition.native);
`

i feel this is a big deal to keep the overall experience smooth and silky as expected from an ios app. maybe i'm missing something?
thanks!

**Comment by jtkeyva** [comment]
oh and even more so, sometimes the transitions get "stuck" half way through a swipe? i've never seen that before with flutter.

**Comment by jonataslaw** [comment]
Please open an issue following the issue opening script
