### ISSUE TITLE
Get.reset Not working

### ISSUE THREAD

**Issue by TheGhostDevlopper** [jonataslaw/getx#675]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
I try Get.reset() but it's not working

**To Reproduce**
1. call function Get.reset()

**Expected behavior**
to reset all value of my controller 

**Flutter Version:**
  flutter 2.20.4

**Getx Version:**
  get: ^3.12.1

**Describe on which device you found the bug:**
  IOS/ Android

**Comment by jonataslaw** [comment]
Hi, Get.reset is working properly on the tests, and also on my applications. Please provide a reproduction code if you think something is not working properly.

https://github.com/jonataslaw/getx/blob/master/packages/get_instance/test/get_instance_test.dart

**Comment by TheGhostDevlopper** [comment]
thank you for your response, yeah that's true it's work I  made a mistake in my code structure.
