### ISSUE TITLE
Place to discuss best practices when using Get

### ISSUE THREAD

**Issue by qbait** [jonataslaw/getx#678]
It's not exactly a feature, sorry for making a bit of a mess.
Your documentation is great. However, after reading it, I still have some questions about the best practices using Get.
What's the best place to ask such questions? I can't see many questions on the Slack Flutter channel. On `StackOverflow`, there are only 5 questions with `flutter-get` tag.
Shall we create a place where the community can discuss best practices? Or am I missing something and such a place already exists?

**Comment by roipeker** [comment]
@qbait Yep, seems like you are missing the channels, please, [join Discord or Telegram](https://github.com/jonataslaw/getx#community-channels).

**Comment by qbait** [comment]
Thank you @roipeker. I've just registered to all of the channels :)
