### ISSUE TITLE
[Feature request]: Use multiple GetMaterialApp in app

### ISSUE THREAD

**Issue by definev** [jonataslaw/getx#682]
I have an app has two seperate part: menu and content.
I don't want rewrite menu so i use two the blue MaterialApp inside the red GetMaterialApp.
![Screenshot_1601989013 (1)](https://user-images.githubusercontent.com/62325868/95205077-17b1ec00-080f-11eb-9b5a-59dd874e8a3e.png)

I think you should add List<GetInterface> GetStack; and add GetInterface to GetStack from interface param in GetMaterialApp.

**Comment by roipeker** [comment]
@definev, after reading the comment a couple of times, i think i understand what you mean, yet i don't see any benefit on the request itself. Why would u want a separate GetMaterialApp? In my basic understanding, what you have is just Widgets, nesting multiple MaterialApps is unnecessary, most of times, and overkilling, memory-wise.
Beyond that i don not understand the `GetStack` / `GetInterface` concept in `GetMaterialApp`, would you mind explain that further?

**Comment by definev** [comment]
Sorry for my bad english. I just want to use dependency injection in the second GetMaterialApp.
You can watch this video for more detail:
!(https://vimeo.com/user124600632/review/465659463/4cb8d19fa2)

**Comment by Nipodemos** [comment]
> Sorry for my bad english. I just want to use dependency injection in the second GetMaterialApp.
> You can [watch this video](https://vimeo.com/user124600632/review/465659463/4cb8d19fa2)
>  for more detail
> 

The link is broken

**Comment by definev** [comment]
https://drive.google.com/file/d/1ZWn25KVb33LhuWq4W_ZGApXMGp4sIb7F/view?usp=sharing

**Comment by Nipodemos** [comment]
Why is a part of your screen is an entirely new MaterialApp? What technical problem that you've faced that required this solution?

**Comment by yhsj0919** [comment]
I think you wants to use Navigator widget，you can see[https://github.com/jonataslaw/getx/blob/92e0ea0df686c29415c81d0d6213bbc652096324/documentation/zh_CN/route_management.md#%E5%B5%8C%E5%A5%97%E5%AF%BC%E8%88%AA](url)

**Comment by benyaminbeyzaie** [comment]
> @definev, after reading the comment a couple of times, i think i understand what you mean, yet i don't see any benefit on the request itself. Why would u want a separate GetMaterialApp? In my basic understanding, what you have is just Widgets, nesting multiple MaterialApps is unnecessary, most of times, and overkilling, memory-wise. Beyond that i do not understand the `GetStack` / `GetInterface` concept in `GetMaterialApp`, would you mind explain that further?

The reason for multiple MaterialApps is that we don't want to rebuild the menu with routing! So for some routing we just handle them in nested MaterialApp. I have achieved that goal using Material app widget but can't do with GetMaterialApp. Do you have a better idea to not reload the menu with routing? thanks. @roipeker
