### ISSUE TITLE
[Feature Request] OnReady callback for GetMaterialApp

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#684]
**Is your feature request related to a problem? Please describe.**
I want to precache my images upon starting the app, with flutter **precacheImage** function. If we try to call the function inside the **initState()**, it may throw an error "dependOnInheritedWidgetOfExactType< MediaQuery>() or dependOnInheritedElement() was called before _MyHomePageState.initState() completed". So we have to call precacheImage(theImage.image, context) inside **didChangeDependencies()** which is called after the initState.

**Describe the solution you'd like**
A callback, could be **didChangeDependencies**, after the initState.

Thanks

**Comment by Nipodemos** [comment]
There is a `onReady()` function that is called after the first render in the screen, maybe it will solve your problem

```dart

class Controller extends GetxController {
  
  @override
  void onReady() {
    // here
  }

}
````

**Comment by jasonlaw** [comment]
Hi, I need it in GetMaterialApp. It currently has onInit and onDispose but not onReady. Thanks.

**Comment by jonataslaw** [comment]
This has already been implemented
