### ISSUE TITLE
The getter 'getxController' isn't defined for the class

### ISSUE THREAD

**Issue by niypoo** [jonataslaw/getx#688]
After update from `get: ^3.10.2`  to `get: ^3.12.1`

but when downgrade to `3.10.2` again it's work

this error appearing when try run 

```
Error: The getter 'getxController' isn't defined for the class '_GetImpl'.
 - '_GetImpl' is from 'package:get_core/src/get_main.dart' ('/Users/mahmoudnabhan/flutter/.pub-cache/hosted/pub.dartlang.org/get_core-3.12.0/lib/src/get_main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'getxController'.
      Get.getxController.restartApp();
          ^^^^^^^^^^^^^^
```

**Comment by eduardoflorence** [comment]
After upgrading to version 3.12.1, run the following commands:
```
flutter clean
flutter pub get
```

There was an internal division of packages and therefore it is necessary to execute the above commands. Restart your code editor as well.

**Comment by niypoo** [comment]
> After upgrading to version 3.12.1, run the following commands:
> 
> ```
> flutter clean
> flutter pub get
> ```
> 
> There was an internal division of packages and therefore it is necessary to execute the above commands. Restart your code editor as well.

I did and it's not working I do even clear vscode cache , I did every thing I know but not working !

**Comment by eduardoflorence** [comment]
Sorry, now I have done an analysis in the source code and it looks like `getxController` has been replaced by `rootController` in version `3.12.1`. You can do a test like this:
```dart
Get.rootController.restartApp()
```

**Comment by niypoo** [comment]
> Sorry, now I have done an analysis in the source code and it looks like `getxController` has been replaced by `rootController` in version `3.12.1`. You can do a test like this:
> 
> ```dart
> Get.rootController.restartApp()
> ```

thank you 👍

**Comment by Nipodemos** [comment]
@jonataslaw i think you forgot to put this in changelog

**Comment by niypoo** [comment]
I'm facing another issue when exciting function with new `rootController.restartApp()`
the app refresh but stay in splash screen not going to home route as usual 

this is my function

```


Future<void> changeLocale(String languageKey) async {
      Locale newLocale = Locale(languageKey);
      await localizationDelegate.changeLocale(newLocale);
      Get.updateLocale(newLocale);
      currentLocale = newLocale;
      update();
      Get.rootController.restartApp();
  }


```

**Comment by Nipodemos** [comment]
Hey @niypoo , for better organization, i suggest you to create a new issue, since what you are having now is indeed a new issue. And please follow the issue template, it help us help you
