### ISSUE TITLE
How to obs an enum ?

### ISSUE THREAD

**Issue by demos77** [jonataslaw/getx#689]
I try to obs an enum variable but it's seem impossible.

```
enum Status { NotLoggedIn, Authenticating, LoggedIn }

class AuthController extends GetxController {
  Status _loggedInStatus = Status.NotLoggedIn.obs;
}
```

**Comment by jonataslaw** [comment]
Check example
https://github.com/jonataslaw/getx/blob/master/getx/example/lib/pages/home/presentation/controllers/home_controller.dart#L15

Please, use platform channels to suporte questions.

**Comment by std-c** [comment]
resolve it? @demos77
