### ISSUE TITLE
Get.previousArguments is missing

### ISSUE THREAD

**Issue by eduardoflorence** [jonataslaw/getx#692]
**Describe the bug**
Get.previous Arguments is demonstrated in the readme, but does not exist in the current version. 

**Reproduction code**
```dart
Get.previousArguments // The getter 'previousArguments' isn't defined for the type '_GetImpl'
```

**Expected behavior**
I did a check and saw that it was removed in version 2.10.0, as it existed until version 2.6.0. If it is depreciated, we need to remove it from the readme.

**Flutter Version:**
1.22.0

**Getx Version:**
3.12.1

**Comment by jonataslaw** [comment]
Thanks for noticing this.
It really should be removed from readme
