### ISSUE TITLE
GetXController's Filter RxList data

### ISSUE THREAD

**Issue by IsmailAlamKhan** [jonataslaw/getx#693]
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
I want to search an Rx<List<ExampleModel>> based on user data coming from firebase.

**Reproduction code
This is my Controller
```
class AgentController extends GetxController {
  Rx<List<AgentModel>> agentList = Rx<List<AgentModel>>();
  List<AgentModel> get agentData => agentList.value;

  @override
  void onInit() {
    agentList.bindStream(AdminDatabase().agentStream());
  }
}
```

**To Reproduce**
1. TextController on change search the list and query

**Expected behavior**
Show data as per the search charecter.

**Flutter Version:**
Flutter (Channel master, 1.23.0-8.0.pre.147, on Microsoft Windows [Version 10.0.19041.508], locale en-US)

**Getx Version:**
3.12.1,

**Describe on which device you found the bug:**
Web

**Comment by eduardoflorence** [comment]
Please, is this a bug or a question on how to do it?

**Comment by Nipodemos** [comment]
We are trying to make things organized here. So the issues page is only for issues and feature requests. For questions and general stuff about GetX, you should go to [Community Channels](https://github.com/jonataslaw/getx#community-channels). I recommend Discord, the people are more active there
Telegram is active too, but the main language is portuguese
