### ISSUE TITLE
rootController.restartApp() hanging on initialRoute

### ISSUE THREAD

**Issue by niypoo** [jonataslaw/getx#694]
when user the  rootController.restartApp() after change locale the app refresh but staying  in initialRoute screen not going to home route as usual or like open app first time .

DEBUG console
```
Another logs ---
[GETX] GOING TO ROUTE /splash
... no more logs
```

that is my function that should change the locale and it's workin without this issue when I was using `Get.getxController.restartApp();`
```
Future<void> changeLocale(String languageKey) async {
      Locale newLocale = Locale(languageKey);
      await localizationDelegate.changeLocale(newLocale);
      Get.updateLocale(newLocale);
      currentLocale = newLocale;
      update();
      Get.rootController.restartApp();
  }
```

my main GetMaterialApp

```
GetMaterialApp(
        initialBinding: InitializationBiniding(),
        debugShowCheckedModeBanner: false,
        theme: ThemeController.to.lightTheme,
        darkTheme: ThemeController.to.darkTheme,
        themeMode: ThemeMode.system,
        initialRoute: '/splash',
        getPages: Routes.routes,
        transitionDuration: Config.duration300,
        defaultTransition: Transition.native,
        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          LocalesController.to.localizationDelegate
        ],
        supportedLocales: LocalesController.to.supportedLocales(),
        locale: LocalesController.to.currentLocale,
      ),
```

I'm using last version of get
and using flutter 
Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (9 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

**Comment by jonataslaw** [comment]
Restart app does not play the app for the initial route, it only gives a "setState" in the MaterialApp.
Get.updateApp () and Get.forceUpdateApp () are the two apis that should be used, one to update all dirty widgets, and the second to update all widgets below MaterialApp, including const widgets.

**Comment by mozaffari** [comment]
Get.appUpdate();
    Get.forceAppUpdate();

> Get.updateApp () and Get.forceUpdateApp ()
