### ISSUE TITLE
Get.context is null during unit tests

### ISSUE THREAD

**Issue by papmodern** [jonataslaw/getx#695]
I am using mobx for state management and before adding get package to my project, I was passing the context to each action I needed to. Now by the help of Get.context, I remove all the context inputs from my actions. But during tests, this context is empty and it seems Get won't initialize itself correctly.

It would be great if there was a tool to initialize Get before tests, if it exists, I couldn't find it through the docs.

 I think we need a separated section in docs related to testing. The ways that we can solve the anti-pattern dependency handling of Get in our tests.

**Comment by ghenry** [comment]
Try this way? https://github.com/jonataslaw/getx/issues/418#issuecomment-694085362

**Comment by ghenry** [comment]
Are you using getmateralapp?

**Comment by papmodern** [comment]
> Are you using getmateralapp?

I am writing unit test. Just initiating a class and testing methods.

**Comment by jonataslaw** [comment]
Get.context is null if you don't have a GetMaterialApp to provide the context.

Add something like:
await tester.pumpWidget(GetMaterialApp(home: Scaffold()));
or use the "getTest" from get_test package to made tests without worrying about the context.

As this is expected behavior, I am closing.
