### ISSUE TITLE
Navigation Features (Parameters & Transitions)

### ISSUE THREAD

**Issue by halimpuckjava** [jonataslaw/getx#696]
hi

i suggest to add :

1.  navigation with parameters
2.  add transitions to navigation (enter when go, leave when back)

**Comment by eduardoflorence** [comment]
This resources already exists.

See [here](https://github.com/jonataslaw/getx/blob/master/documentation/en_US/route_management.md).

**Comment by Nipodemos** [comment]
Closing since this feature already exists
