### ISSUE TITLE
Obx updates on every observable 

### ISSUE THREAD

**Issue by brianschardt** [jonataslaw/getx#698]
Is there functionality where Obx will only rebuild on certain observable changes and not all nested observables?

**Comment by d-apps** [comment]
> Is there functionality where Obx will only rebuild on certain observable changes and not all nested observables?

Is it possible to you provide an example in code?

If you only want that Obx trigger when certain observable change you should only use that specific obs inside the Obx I guess.

**Comment by jonataslaw** [comment]
Using Obx only the variables that have been changed that will be reconstructed, example:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  Get.lazyPut(() => Controller());
  runApp(GetMaterialApp(home: Home()));
}

class Controller extends GetxController {
  final count1 = 0.obs;
  final count2 = 0.obs;
  final nestedCount = 0.obs;

  @override
  onReady() {
    count1(100);
    count2(300);
    nestedCount(500);
  }
}

class Home extends GetView<Controller> {
  const Home({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Obx(() {
              print("count1 value: ${controller.count1}");
              return Text('${controller.count1}');
            }),
            Obx(() {
              print("count2 value: ${controller.count2}");
              return Column(
                children: [
                  Text('${controller.count2}'),
                  Obx(() {
                    print("nestedCount value: ${controller.nestedCount}");
                    return Text('${controller.nestedCount}');
                  }),
                ],
              );
            }),
          ],
        ),
      ),
    );
  }
}

```

```
out:
flutter: count1 value: 0
flutter: count2 value: 0
flutter: nestedCount value: 0
flutter: count1 value: 100
flutter: count2 value: 300
flutter: nestedCount value: 500
```

Note that Flutter can still give a "setState" on widget's children (which has nothing to do with Obx, but with hashcode of widgets) if you don't use const widgets, so try whenever possible to create const constructors for your widgets, and they won't be rebuilt by cascade by Flutter, because the hashcode will not change

**Comment by Nipodemos** [comment]
Since this is not an issue and it was already answered, i'm closing.

@brianschardt , for question we recommend going to the [Community Channels](https://github.com/jonataslaw/getx/blob/master/README.md#community-channels). 

Here is for issues and feature requests only.
