### ISSUE TITLE
need a getter of GetInstance._singl

### ISSUE THREAD

**Issue by qiushui95** [jonataslaw/getx#699]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**
in some page , I need to change configs if it has been registered.(lazyPut)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by jonataslaw** [comment]
Sorry, _singl is private because it is a static variable.
It is not correct to expose static variables which depend on the core of the application, because you can break it if you do not know what you are doing, so I will not expose this api.

**Comment by qiushui95** [comment]
@jonataslaw I just want a method like 

`
  List<S> findIsInstance<S>() {
    final result = <S>[];
    for (var element in _singl.values) {
      if (element is S) {
        result.add(element.getDependency() as S);
      }
    }
    return result;
  }
`

**Comment by Nipodemos** [comment]
What's your use-case? maybe there is another way of doing it.
can you explain exactly what you want??

**Comment by qiushui95** [comment]
@Nipodemos  I hava a base config class。In every page ，I lazyPut extends class。In setting page，need to change the config of all page.
thx,my English is terrible.

**Comment by qiushui95** [comment]
I write a [example](https://github.com/qiushui95/flutter_get_demo/blob/558bd1465ce0a304813f7394d4fac01cd918a640/lib/page/main_page.dart#L53)
