### ISSUE TITLE
Error when navigating to the same route by calling Get.offAndToNamed

### ISSUE THREAD

**Issue by BobFactory** [jonataslaw/getx#700]
**Describe the bug**
First off sincere thanks to you guys for making this, I have been using this for 2 weeks now and it feels so good with all the features combined. Simple and easy to use once you get the hang of it.  

Coming to the issue, I am creating a note-taking application wherein you can create a duplicate of a note. 
So let's assume the current route is `/add_edit_route` and when I navigate to the same route again using the
`Get.offAndToNamed("/add_edit_route", arguments: note, );`, I get the following error: 

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<ScaffoldState>#0abec]
This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- GetBuilder<AddEditController>(state: _GetBuilderState<AddEditController>#69269)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2881:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2906:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:915:18)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```
I tried assigning a `key: UniqueKey()`  to the  `GetBuilder` but that also didn't work. I also tried doing `assignId: true` and `id: UniqueKey().toString()`, but that also didn't work.

**Reproduction code**

Main Note Screen

```dart
class NoteScreen extends StatelessWidget {
 static const ROUTE_NAME = "/add_edit_note";

  @override
  Widget build(context) {
    return GetBuilder<AddEditController>(
      assignId: true, 
      id: UniqueKey().toString(), //Tried without this also and it didn't work.
      builder: (controller) => Scaffold(
        key: controller.scaffoldKey,
        backgroundColor: controller.selectedColorDark,
        body: Center(child: RaisedButton( child: Text("navigate", onPressed: contoller.copy)));
}
}
```

Controller 

```dart

class AddEditController extends GetxController{
  NotesModel existingNote;

@override
  void onInit() {
   existingNote = Get.arguments;
   print("route arguments $existingNote");
}


copy() {
  //Some other logic to modify the existing note object to make it look like a new note.
   Get.offAndToNamed(NoteScreen.ROUTE_NAME, arguments: existingNote, );
}
}
```

**Steps to reproduce the behavior**

1. Go to 'NoteScreen'
2. Click on 'navigate' button
4. See an error in the logs.

**Expected behavior**
The previous exiting route of `NoteScreen` should be removed from the memory and a new controller should be assigned to it since it is pushed again to the stack.

**Screenshots**
![image](https://user-images.githubusercontent.com/26218176/95649780-e3834780-0afc-11eb-96ca-652144321d38.png)

**Flutter Version:**
```
Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (11 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

```

**Getx Version:**
`get: ^3.10.2`

**Describe on which device you found the bug:**
Pixel 3 - Android.

**Comment by BobFactory** [comment]
FYI: I am using GetBuilder as my base widget in the build method here because my controller contains my scaffold key and a background-color which are necessary for the scaffold as they keep changing and I re-render the screen using update() method.

**Comment by BobFactory** [comment]
After a little more digging around I found that the main error causing element was the **ScaffoldKey** that I am passing. 
If I remove the key the route works. 
But I am not sure if the controller recreated. Instead, it seems the controller is still the old one, with the previous values. I am using the Bindings API by the way.

**Comment by leobispo** [comment]
I am facing the same issue.

After an investigation I found the offAndToNamed is calling pushNamedAndRemoveUntil and this method does not call Route.dispose -> GetPageRoute.dispose for the removed widgets.

Because of that the Controller is not closed for the widget causing the problem (You cannot have 2 widgets in the tree with the same GlobalKey).

A workaround would be instead of calling offAndToNamed you can do a while () { Get.back(); } (it is a bit more costly but should do the work).

Another issue I found related to the injection systems is: the dispose method is not called synchronously. So if you have several pops and then push a widget that was previously in the tree, the controller will be duplicated.

**Comment by leobispo** [comment]
I filled an Issue to the Flutter team.

https://github.com/flutter/flutter/issues/67817

Lets see what they reply.

**Comment by eduardoflorence** [comment]
@leobispo, offAndToNamed call popAndPushNamed.

@BobFactory try Get.offNamed.

**Comment by BobFactory** [comment]
@eduardoflorence I tried to use Get.offNamed. The problem with this is that routing with Get does not implicitly allow navigation to the same route, the navigation doesn't take effect. The only way possible is by setting ` preventDuplicates: false `. But that would mean that there will be a duplicate route in the stack, which is not what I am looking for. 

I want the current route to render from the beginning. I want the associated Controller to call onInit() when that happens. Is it possible for me to manually cause a route re-render?

**Comment by Nipodemos** [comment]
@BobFactory as @eduardoflorence said, use `Get.offNamed()` with `preventDuplicates: false`.

Since you are using the function that removes the current route and push a new one, you won't have problems of duplicating routes.

**Comment by BadalAc** [comment]
Another issue I found related to the injection systems is: the dispose method is not called synchronously. So if you have several pops and then push a widget that was previously in the tree, the controller will be duplicated. @leobispo  .Did u get any solution.
