### ISSUE TITLE
Illegal characters

### ISSUE THREAD

**Issue by rupamking1** [jonataslaw/getx#702]
How ca i fix Illegal characters error ? 
<img width="431" alt="Screenshot_1" src="https://user-images.githubusercontent.com/57300218/95677326-629e7b80-0be2-11eb-8ac7-bd7d7219790e.png">

**Comment by eduardoflorence** [comment]
This has nothing to do with GetX,
I believe you should have copied this source code from another location and the space character has been replaced by the character 160, just delete each space you see and type space again

**Comment by rupamking1** [comment]
Thank Yooooooouuuuu for helping me 😇

**Comment by jonataslaw** [comment]
> This has nothing to do with GetX,
> I believe you should have copied this source code from another location and the space character has been replaced by the character 160, just delete each space you see and type space again

As mentioned by Eduardo, this is a character conversion error that happened when you copy content from a website, and paste it directly into your IDE. As this is not related to Getx, I am closing.
