### ISSUE TITLE
routeObserver for better tracking

### ISSUE THREAD

**Issue by saswatsaubhagya** [jonataslaw/getx#703]
Hello, as flutter material widget gives the opportunity to observe the route is there any specific feature in for that in get.

**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by jonataslaw** [comment]
Hi, look to doc:
https://github.com/jonataslaw/getx/blob/master/documentation/en_US/route_management.md#middleware

**Comment by Nipodemos** [comment]
wow!
i've never had saw that before! That's a very nice thing
