### ISSUE TITLE
AnimationController vsync: this Not Working on onInit()

### ISSUE THREAD

**Issue by rupamking1** [jonataslaw/getx#704]
AnimationController vsync: this Not Working on onInit()

<img width="672" alt="Screenshot_1" src="https://user-images.githubusercontent.com/57300218/95748281-63eda800-0cb7-11eb-948c-ae0ca179ba0a.png">

**Comment by djade007** [comment]
Simply Restart your IDE, that should fix it.
You can choose Invalidate Cache and Restart option

**Comment by daveMcelf** [comment]
To use vsync, You may need to use `SingleGetTickerProviderMixin` with your class. You can declare your class like and it should work:

```
class Controller extends GetxController with SingleGetTickerProviderMixin { 
...
}
```

**Comment by rupamking1** [comment]
@daveMcelf Thank Yoooooouuuu For Helping Me its Now working
