### ISSUE TITLE
Dialog is visible even though the Future is finished

### ISSUE THREAD

**Issue by sashker** [jonataslaw/getx#706]
Hello.

I'm showing the Dialog widget using Get.dialog() function:
```
var result = await Get.dialog(MyDialog());
await doHeavyStuff();
```

Within the MyDialog I do:
```
onTap: () {
  Get.back(result: data);
}
```

I expect to get back to dismiss dialog, get back to the screen and then start executing the function. In fact, when I tap on the button, the MyDialog is on the screen until _doHeavyStuff()_ is done.

**Expected behavior**
Destroy a dialog and then starting executing other instructions

**Flutter Version:**
1.23.0-14.0.pre.121

**Getx Version:**
3.13.0

**Describe on which device you found the bug:**
Samsung A50

**Comment by daveMcelf** [comment]
I can't seem to reproduce this behavior that you have mentioned. Below is my code snippet and it works as expected; 
when tapped =>  dialog is close  => start doHeavyProcess() => Finish.
```
void testing() async {
    var result = await Get.dialog(
      Material(
        child: InkWell(
          onTap: () {
            Get.back(result: 1);
          },
          child: Container(),
        ),
      ),
    );
    print("dialog closed");
    await Future.delayed(Duration(seconds: 3)); 
    print("done heavy process");
  } 
```

Tested on GetX version: 3.13.2
Flutter: 1.20.4

**Comment by sashker** [comment]
I can confirm that your code is working on the new project with the same versions of Flutter and GetX I specified.
I assume, my code blocks somewhere else, and it's not related to GetX.

Thanks a lot for your time and help!
