### ISSUE TITLE
Erro ao utilizar o Get com package responsive_framework

### ISSUE THREAD

**Issue by ElvisHotz** [jonataslaw/getx#709]
**Erro ao fazer navegação de tela utilizando Get .**

**Describe the bug**
Estou utilizando um package para responsividade da tela responsive_framework. Se removo ele funciona perfeitamente, 
teria como verificar o que pode ser que esta acontecendo de incompatibilidade de packages

**Eu utilizo desta forma no main.dart

example:

```dart
void main() async {
  await GetStorage.init();
  SystemChrome.setPreferredOrientations(
    [
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ],
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      builder: (context, widget) => ResponsiveWrapper.builder(
        BouncingScrollWrapper.builder(context, widget),
        maxWidth: 1200,
        minWidth: 450,
        defaultScale: true,
        breakpoints: [
          ResponsiveBreakpoint.resize(450, name: MOBILE),
          ResponsiveBreakpoint.autoScale(800, name: TABLET),
          ResponsiveBreakpoint.autoScale(1000, name: TABLET),
          ResponsiveBreakpoint.resize(1200, name: DESKTOP),
          ResponsiveBreakpoint.autoScale(2460, name: "4K"),
        ],
        background: Container(
          color: Color(0xFFF5F5F5),
        ),
      ),
      smartManagement: SmartManagement.full,
      debugShowCheckedModeBanner: false,
      title: 'Next app vendas',
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
      theme: Themes.light,
      initialBinding: InitialBinding(),
    );
  }
}
```

**To Reproduce**
1. Instalar o package responsive_framework, fazer as alterações no main conforme o package responsive_framework orienta , criar duas navegações, fazer navegação entre telas utilizando o Get, no meu caso 
executo esta logica. 
 if (!logged) {
      Get.offAllNamed('/login');
    } else {
      Get.offAllNamed(Routes.HOME);
    } 

2. Quando ele faz a chamada Get.offAllNamed('/login') da erro e nao navega para a pagina

**Expected behavior**
Navegar para a pagina Login

**Flutter Version:**
Flutter 1.22.1

**Getx Version:**
get: 3.13.2

**Comment by eduardoflorence** [comment]
Please provide a complete code so that we can only copy, paste and execute to reproduce the problem.
Your code is missing the InitialBinding and AppPages, for example

**Comment by ElvisHotz** [comment]
ok, here attached the sources this.
[app_teste.zip](https://github.com/jonataslaw/getx/files/5380036/app_teste.zip)

**Comment by jonataslaw** [comment]
Duplicate of https://github.com/jonataslaw/getx/issues/446#issuecomment-669175117 (See comment)
