### ISSUE TITLE
Controller controller = Get.put(Controller());  Sometime not working 

### ISSUE THREAD

**Issue by rupamking1** [jonataslaw/getx#711]
1. This program is not working-
<img width="427" alt="Screenshot_2" src="https://user-images.githubusercontent.com/57300218/96107572-33e21700-0efa-11eb-9952-3262f3a88142.png">

2. but this program is working-
<img width="425" alt="Screenshot_1" src="https://user-images.githubusercontent.com/57300218/96107313-e82f6d80-0ef9-11eb-9613-e1e55222b9bc.png">

How to use ThemeX themeX = Get.put(ThemeX()); in this program.

**Comment by jonataslaw** [comment]
Please read the documentation to get a sense of how state management works.
You need a GetBuilder if you are using update, and in addition Get.changeTheme() does what you are trying to do as well.
As this is not an issue, I am ending this.
If you want help with usage, join a platform channel, github is only for issues and requests for resources. Make sure that what you are facing is a problem before opening an issue.
