### ISSUE TITLE
GetWidget with Get.create doesn´t keep the controller after rebuilt

### ISSUE THREAD

**Issue by eduardoflorence** [jonataslaw/getx#712]
**Describe the bug**
I'm doing a test application where each item in a ListView is a GetWidget linked to a controller created by Get.create. It works as expected (one instance for each one), but if I add an element to the list, it recreates all controllers

**Reproduction code**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(
    debugShowCheckedModeBanner: false,
    initialRoute: '/home',
    defaultTransition: Transition.fade,
    getPages: [
      GetPage(
        name: '/home',
        page: () => HomePage(),
      ),
      GetPage(
        name: '/shop',
        page: () => ShopPage(),
        binding: ShopBinding(),
      ),
    ],
  ));
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('HOME')),
      body: Center(
        child: RaisedButton(
          color: Colors.blue,
          onPressed: () => Get.toNamed('/shop'),
          child: Text(
            'Go to Shop',
            style: TextStyle(color: Colors.white, fontSize: 16),
          ),
        ),
      ),
    );
  }
}

class ShopBinding extends Bindings {
  @override
  void dependencies() {
    Get.put(ShopController());
    Get.create(() => ShopItemController());
  }
}

class ShopController extends GetxController {
  final total = 0.obs;
  final list = ['item 1', 'item 2', 'item 3'].obs;
  void increment() => total.value += 1;
  void addLista() => list.add('item ${(list.length + 1).toString()}');
}

class ShopPage extends GetView<ShopController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('SHOP')),
      body: Column(
        children: [
          Obx(() => Text('Total: ${controller.total}')),
          Flexible(
            child: Obx(
              () => ListView.builder(
                itemCount: controller.list.length,
                itemBuilder: (context, item) {
                  String produto = controller.list[item];
                  return ShopItem(produto: produto);
                },
              ),
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          controller.addLista();
        },
      ),
    );
  }
}

class ShopItemController extends GetxController {
  final quantity = 0.obs;
  ShopController shop = Get.find<ShopController>();
  void increment() {
    quantity.value += 1;
    shop.total.value += 1;
  }
}

class ShopItem extends GetWidget<ShopItemController> {
  ShopItem({Key key, this.produto}) : super(key: key);

  final String produto;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Text(produto),
        SizedBox(width: 10),
        Obx(() => Text('Qty: ${controller.quantity.toString()}')),
        SizedBox(width: 10),
        RaisedButton.icon(
          onPressed: () => controller.increment(),
          icon: Icon(Icons.add),
          label: Text('add'),
        )
      ],
    );
  }
}
```

**To Reproduce**
1. Click on 'Go to Shop.'
2. Click on 'add' for each item
3. Click on 'FloatingButton +' to add an item
4. See that all controls are recreated

**Expected behavior**
The list is already started with three items, so when adding a new item I expected that only a new controller would be created and the controllers initially created would be used

**Flutter Version:**
1.22.1 channel stable
Dart 2.10.1

**Getx Version:**
3.13.2

**Describe on which device you found the bug:**
Samsung Galaxy A01 - Android.

**Comment by eduardoflorence** [comment]
Hi @jonataslaw,
I tested the code above again with version 3.15.0, but the problem persists.

**Comment by yulkin2002** [comment]
I have a similar issue but with GetView, I have a view `class OfferingListView extends GetView<MyTalentsController> {...}`
I get this error, when widget rebuilds
"MyTalentsController" not found. You need to call "Get.put(MyTalentsController())" or "Get.lazyPut(()=>MyTalentsController())"

**Comment by lightlitebug** [comment]
I had a similar experience. I tested with the following three cases.

1. GetWidget + Get.create + Obx

- Doesn't keep the controller state
- Initialize all items if a new item is added to the list.

2. StatelessWidget + Get.create + GetBuilder

- keep the controller state
- keep the existing items' state even if a new item is added to the list

3. StatelessWidget + Get.create + Obx

- Doesn't keep the controller state
- Initialize all items if a new item is added to the list.

 Only the second case give a desired behavior. So... what is the correct usage of Get.create?

GetX version: 3.22.1
Flutter version: 1.22.4
Dart version: 2.10.4

**Comment by eduardoflorence** [comment]
Can you show example code working with `StatelessWidget + Get.create + GetBuilder`?

**Comment by lightlitebug** [comment]
As I mentioned above, I tested 3 cases.
Here is my source code.

https://github.com/lightlitebug/getwidget_test

I built 3 pages named as '/get-widget-cart', '/get-builder-cart', '/get-stateless-cart'.
Among these '/get-builder-cart' is the case for `StatelessWidget + Get.create + GetBuilder.`

**Comment by lightlitebug** [comment]
I think this is an important issue, but the problem mentioned above is still not resolved. I wonder if there is another approach that GetX recommends offiically, or if I am not sure of the exact method. Or can we just use stateful widgets to solve it?

**Comment by eduardoflorence** [comment]
Hi @lightlitebug, the problem has been solved and is now available on the master branch, soon to be released in the next version. GetWidget has been completely redesigned.

**Comment by lightlitebug** [comment]
Oh, I'm really looking forward to it. Thanks for your hard work.
