### ISSUE TITLE
GetUtils.isPhoneNumber not working perfectly 

### ISSUE THREAD

**Issue by IlyesBenarroum** [jonataslaw/getx#716]
Regex need an update! 
I think something like this would be better r"^(?:[+0]9)?[0-9]{10}$"
GetUtils.isPhoneNumber is accepting 2 digits.

**Comment by eduardoflorence** [comment]
This is an extremely difficult function to be assertive.
Each country has more than one phone number format and they are different from other countries, there is no standard.

**Comment by IlyesBenarroum** [comment]
okay thank you but i think it's better to not implement it or just make it little but better

**Comment by eduardoflorence** [comment]
Hi @IlyesBenarroum,
In GetX 3.15.0, GetUtils.isPhoneNumber was improved and no longer accepts just 2 digits
