### ISSUE TITLE
ConnectionState functionality in GetBuilder to handle waiting time

### ISSUE THREAD

**Issue by drosa88** [jonataslaw/getx#719]
First of all: I really love your package and want to say you a big thanks for your good work!

**Is your feature request related to a problem? Please describe.**
From FutureBuilder StreamBuilder we know the ConnectionState. So we can wait until the data has been loaded. I would love this functionality also for GetBuilder. I will show you the problem in a code example.

I have an app for creating virtual guestbooks. I created a variable in a controller on which I want to save the current guestbook when the user clicks to one on the ListView:

`final currentGuestbook = Guestbook().obs`

When a user clicks on an specific guestbook in my ListView I update the variable:

`guestbookController.currentGuestbook.value = guestbook;`

And here in the detail screen I want to retrieve the object from guestbookController.currentGuestbook:

```
Obx(() {
  return Positioned(
      bottom: Get.height / 15,
      child: Container(
        alignment: Alignment.center,
        width: Get.width,
        child: Text(
          guestbooksController
              .currentGuestbook.value.title, // Here
          textAlign: TextAlign.center,
          style: Get.theme.textTheme.headline1.copyWith(
              color: Get.theme.colorScheme.onPrimary),
        ),
      ));
}),
```

The problem: For 1-2 seconds the page shows me an error because the `value.title` is not defined. After 1-2 seconds it shows the correct value.

**Describe the solution you'd like**
What about a ConnectionState functionality to be sure that the values from the controller are loaded as well? How we know that from FutureBuilder or StreamBuilder.

If such a functionality already exists - I'm sorry. I read the entire documentation and I don't found anything like this.

Thanks in advance for reading.

**Comment by eduardoflorence** [comment]
Hello @drosa88 , in my opinion this would not be possible. FutureBuilder watches only one stream, while GetBuilder, Getx and Obx can watch multiple streams (.obs).
You have to create your own "ConnectionState" for each .obs you want to watch.
See an example here (`enum Status`):
https://github.com/jonataslaw/getx/blob/master/example/lib/pages/home/presentation/controllers/home_controller.dart

**Comment by subzero911** [comment]
> See an example here (enum Status):

It looks ugly.
Why not to create some extension for Future<T> which will keep its status? So I can use a `Future<CasesModel> cases.obs` syntax. And some analogue of FutureBuilder (maybe `ObxFutureBuilder` is a good name) which can check the status of the observed Future. See also my issue https://github.com/jonataslaw/getx/issues/722, I raised the same problem.

**Comment by eduardoflorence** [comment]
Hi @drosa88 and @subzero911,
   Wow, this new feature was created using StateMixin, released in version 3.15.0 of GetX.
   In the example that exists in the package repository, you will see how to use it.

**Comment by jonataslaw** [comment]
You don't need this, just use StateMixin or GetNotifier for that purpose, it's very easy and simple:

```dart
// Use StateMixin<YourModel>
class HomeController extends GetxController with StateMixin<CasesModel> {
  HomeController({this.homeRepository});

  /// inject repo abstraction dependency
  final IHomeRepository homeRepository;

  /// When the controller is initialized, make the http request
  @override
  void onInit() {
    super.onInit();
    // show loading on start, data on success
    // and error message on error with 0 boilerplate
    homeRepository.getCases().then((data) {
      change(data, status: RxStatus.success());
    }, onError: (err) {
      change(null, status: RxStatus.error(err.toString()));
    });
  }
}
```

on View:

```dart
controller.obx((state) => Text(state.name))
```

By default, a CircularProgressIndicator is showed on loading, and Text Widget is showed on error. You can made custom widgets:

```dart
controller.obx((state) => Text(state.name), onError: Text('your message'), onLoading: Text('loading...'))
```

You can use any widget on `onError` and `onLoading`

To change Status: `change('your new data', status: RxStatus.success())`
To send a error message:  `change(state, status: RxStatus.error('your error message'))`

Loading And Error are auto, change `onError` and `onLoading` only if you need custom widgets

Well, I'm closing it

**Comment by mtkgeek** [comment]
Hi, how exactly do i know what state change controller.obx is listening to if i have more than one method. Using your example, say we have two methods i the repository
` 
@override
  void onInit() {
    super.onInit();
    
    homeRepository.getCases().then((data) {
      change(data, status: RxStatus.success());
    }, onError: (err) {
      change(null, status: RxStatus.error(err.toString()));
    });

homeRepository.getFalseCases().then((data) {
      change(data, status: RxStatus.success());
    }, onError: (err) {
      change(null, status: RxStatus.error(err.toString()));
    });
  }
`
what state would `controller.obx((state) => Text(state.name))` be referring to in my view.

**Comment by subzero911** [comment]
@mtkgeek it seems to me that StateMixin is for a single network call only. So 1 controller - 1 state.
For 2 or more states you would use the same workaround with ConnectionState for each of network calls.
