### ISSUE TITLE
Remove Stream After Binding

### ISSUE THREAD

**Issue by eazhary** [jonataslaw/getx#721]
Great Package, It allows for super fast development thanks.

I am using bindStream to attach a firebase document (related to today's date)  to an obs. When the date changes (after midnight) I bind the next days document to the obs... now I need to remove the binding to  yesterday's document. Or have a way to clear all the bindings before I bind a new stream...

Is there a way I can do this ?.. 

something like

```
void unbindAll() {
    _subscriptions.forEach((observable, subscription) => subscription.cancel());
    _subscriptions.clear();
}
```

**Comment by jonataslaw** [comment]
If you initialize bindStream in onInit (and only in it, in onReady this is prohibitive) it will be removed in the obs.close() method that does exactly what you entered in the code.
If you need to close a stream that for some reason cannot be closed automatically, you can use onClose for this.
As this issue does not follow the issue opening guidelines, I am closing it.
