### ISSUE TITLE
Need some ObservableFuture analogue.

### ISSUE THREAD

**Issue by subzero911** [jonataslaw/getx#722]
I came from MobX. We have ObservableFuture there. It's a special type of future which I can subscribe and observe its status outside of the controller/store.
Example: https://mobx.netlify.app/examples/github-repos
We can check its status manually with `fetchReposFuture.status == FutureStatus.pending`, or we have a special ObserverFuture widget (https://pub.dev/packages/mobx_widget), it is an analogue to FutureBuilder which can consume ObservableFuture and have several callbacks (OnData, OnError, OnPending etc.).
I haven't found such a functionality in Get. Need some extension to make a Future<T> observable. Thanks in advance.

**Comment by thomas9987567** [comment]
Are you looking something like this? https://pub.dev/packages/states_rebuilder

**Comment by loicgeek** [comment]
Track you status with 03 variables in your controller, isLoadingProducts, successLoadingProducts, and errorLoading products that is all.

**Comment by roipeker** [comment]
Check the new StateMixin in v3.15

https://pub.dev/packages/get/changelog

**Comment by jonataslaw** [comment]
You don't need this, just use StateMixin or GetNotifier for that purpose, it's very easy and simple:

```dart
// Use StateMixin<YourModel>
class HomeController extends GetxController with StateMixin<CasesModel> {
  HomeController({this.homeRepository});

  /// inject repo abstraction dependency
  final IHomeRepository homeRepository;

  /// When the controller is initialized, make the http request
  @override
  void onInit() {
    super.onInit();
    // show loading on start, data on success
    // and error message on error with 0 boilerplate
    homeRepository.getCases().then((data) {
      change(data, status: RxStatus.success());
    }, onError: (err) {
      change(null, status: RxStatus.error(err.toString()));
    });
  }
}
```

on View:

```dart
controller.obx((state) => Text(state.name))
```

By default, a CircularProgressIndicator is showed on loading, and Text Widget is showed on error. You can made custom widgets:

```dart
controller.obx((state) => Text(state.name), onError: Text('your message'), onLoading: Text('loading...'))
```

You can use any widget on `onError` and `onLoading`

To change Status: `change('your new data', status: RxStatus.success())`
To send a error message:  `change(state, status: RxStatus.error('your error message'))`

Loading And Error are auto, change `onError` and `onLoading` only if you need custom widgets

**Comment by RodBr** [comment]
I'm using this with a "Dummy" class in the mixin just to handle cases where I don't want the widget tree to build until I return data from an async call.
`controller.obx((_) => Text(controller.name.value), onError: Text('your message'), onLoading: Text('loading...'))`
Seems to work ok.
