### ISSUE TITLE
Neumorphic apps support

### ISSUE THREAD

**Issue by subzero911** [jonataslaw/getx#723]
In order to use **Get**, we should swap `MaterialApp` to `GetMaterialApp`.
But we use https://pub.dev/packages/flutter_neumorphic in our application. It is a modern UI Kit for creating bevels, shadows and volume effects. It requires using `NeumorphicApp` as a root widget (it has a `materialTheme` parameter, so it doesn't ruin your current project, just adds new cool widgets).
But it makes impossible to use `GetMaterialApp`. Please, add the `flutter_neumorphic` support. Thanks in advance.

**Comment by jonataslaw** [comment]
I have no plans to add this feature to Getx, and more, you can create the content of the MaterialApp wrapper manually, or require the theme repository to create an InheritedWidget for the themes or similar solution.
I'm closing this.

**Comment by subzero911** [comment]
Sorry, I didn't understand.
> or require the theme repository to create an InheritedWidget for the themes or similar solution.

There's no any "theme repository" or InheritedWidget here.
Neumorphic claims that your root widget is NeumorphicApp.
GetX claims that your root widget is GetMaterialApp.
They can't co-exist.
