### ISSUE TITLE
Transition property for Get.toNamed()

### ISSUE THREAD

**Issue by emmanuel-montoya** [jonataslaw/getx#728]
Hello guys, 

I've been using your library for the last 6 months. It's really cool. 

I wonder if you have considered to add the "transition" property for "toNamed()" method?
It would really improve the quality and variety of the screen transitions as I'm using  GetPage() to navigate.

Example: 

Get.to(SplashPage(), transition: Transition.zoom);

Get.toNamed(RoutePaths.SPLASH_SCREEN, transition: Transition.zoom);

Thanks and Regards

**Comment by eduardoflorence** [comment]
For Get.toNamed you must configure the transition in GetPage. Example:
```dart
GetPage(
  name: RoutePaths.SPLASH_SCREEN,
  page: () => SplashScreen(),
  transition: Transition.zoom
),
```

**Comment by emmanuel-montoya** [comment]
awesome :O Thanks a lot!
