### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by muhammadsaddamnur** [jonataslaw/getx#730]
I don't know whether this feature already exists or not.
but I have this question. how do you make a step like the image below with getx?

<img src="https://media3.giphy.com/media/md3UZkxFqZ5u8uX3H4/giphy.gif"/>

I'm on a product detail page, that page has product suggestions. when I tap the product suggestion I navigate to the same page (product detail page) but with different data. I want when I press the back button, the previous data is still there.

how does getx handle these cases?

**Comment by eduardoflorence** [comment]
Just have different controllers for the main screen and details screen

**Comment by eduardoflorence** [comment]
Currently the github for this project is to report bugs or request new features. For questions of use, use the appropriate channels for this:
https://github.com/jonataslaw/getx#community-channels

**Comment by jonataslaw** [comment]
Please use the platform channels to answer questions, this channel is for bug reports or (REAL) resource requests only.
