### ISSUE TITLE
List Bug

### ISSUE THREAD

**Issue by Webhst** [jonataslaw/getx#732]
Hello , first of all thank you for this package , is amazing !

**Describe the bug**
when you equal a list to a RxList then if you do list = RxList.value and modify list , will modify RxList.

In the example we have three lists , when you save the RxList on a List temp , then if you do 

RxList listSaved = RxList(['one', 'two', 'three']);
RxList showList = RxList();

List temp = listSaved.value;
showList.value = temp.where((numbers) => numbers.contains(value)).toList();

is modifying the value of listSaved.value.

**Reproduction code
example:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: ListPage(),
    );
  }
}

class ListPage extends StatelessWidget {
  RxList listSaved = RxList(['one', 'two', 'three']);
  RxList showList = RxList();

  @override
  Widget build(BuildContext context) {
    
    showList = listSaved;

    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(20.0),
        child: Obx(
          () => Column(
            children: [
              TextField(
                decoration: InputDecoration(
                  labelText: 'Search',
                ),
                onChanged: (value) {
                  List temp = listSaved.value;
                  showList.value = temp
                      .where((numbers) => numbers.contains(value))
                      .toList();
                },
              ),
              SizedBox(
                height: 20,
              ),
              Expanded(
                flex: 2,
                child: ListView.builder(
                  itemBuilder: (context, index) {
                    return ListTile(title: Text(showList[index]));
                  },
                  itemCount: showList.length,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**To Reproduce**
1. Click on 'Search input'
2. Write for a number on the list
3. If you delete the number and want to write again the RxList is empty.

**Expected behavior**
When you write for a number and then delete the word should appears all the numbers with the original RxList. RxList should not be modified.

**Getx Version:**
  get: ^3.13.2

**Comment by jonataslaw** [comment]
Hi, but what bug presented? This is the standard behavior of OOP languages.
If you want a new list, you must use List.from(yourRxList.value).

**Comment by Webhst** [comment]
Hi , i tried List.from(yourRxList.value) but still deleting the values of the RxList listSaved , the problem is that when i do the .where function with the List temp = listSaved.value , is modifying listSaved , is this a expected behavior ? why temp.where is filtering listSaved too ? im wondering because listSaved is a RxList.

**Comment by jonataslaw** [comment]
Well, let's keep this away from Getx, your question has nothing to do with him.
I believe this example will help you understand how dart and OOP languages work.

```dart
void main() {
List a = [1,2,3];
List b = a;
b.removeAt(0);
print (a.toString());
// out: [2, 3]
}
```

**Comment by Webhst** [comment]
Ohhh i see , so if thats the case , why 

void main() {
List a = [1,2,3];
List b = List.from(a); // with this 
b.removeAt(0);
print (a.toString());
// out: [2, 3]
}
is removing on List a , is there a way to not modify List a ?

**Comment by jonataslaw** [comment]
> is removing on List a , is there a way to not modify List a ?

Sorry, but this is not happening.
I just ran your code, obviously fixing some problems like accessing protected methods (is your analyzer off?) And I see everything working perfectly.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: ListPage(),
    );
  }
}

class Foo extends GetxController {
  @override
  void onInit() {
    showList.assignAll(listSaved);
    super.onInit();
  }

  final listSaved = RxList(['one', 'two', 'three']);
  final showList = RxList();

  void filterList(String value) {
    List temp = List.from(listSaved)
        .where((numbers) => numbers.contains(value))
        .toList();

    showList.assignAll(temp);
    print("listSaved: ${listSaved.string}");
    print("showList: ${showList.string}");
  }
}

class ListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(20.0),
        child: GetX(
          init: Foo(),
          builder: (controller) => Column(
            children: [
              TextField(
                decoration: InputDecoration(
                  labelText: 'Search',
                ),
                onChanged: controller.filterList,
              ),
              SizedBox(
                height: 20,
              ),
              Expanded(
                flex: 2,
                child: ListView.builder(
                  itemBuilder: (context, index) {
                    return ListTile(title: Text(controller.showList[index]));
                  },
                  itemCount: controller.showList.length,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

![Screen Capture_select-area_20201022141158](https://user-images.githubusercontent.com/35742643/96906844-c5103b00-1470-11eb-9d6b-7cc2e4229db6.png)

**Comment by Webhst** [comment]
That works perfect ! , yes i think the analyzer is on are you saying for .value ? , well this approach works like a charm ! I really appreciate your help , thank you :)

**Comment by jonataslaw** [comment]
I marked the "value" property as protect, your analyzer should display a warning if you used it.
But anyway, once your problem has been solved, I'm closing it.
