### ISSUE TITLE
BottomNavigationBarItem uses .tr to report an error

### ISSUE THREAD

**Issue by lzdtech** [jonataslaw/getx#735]
BottomNavigationBarItem uses .tr to report an error，code show as below.

```
class HomeView extends GetView<HomeController> {
  HomeView(int index) {
    controller.changePage(index);
  }

  @override
  Widget build(BuildContext context) {
    return Obx(
      () => Scaffold(
        appBar: AppBar(
          title: LocaleKeys.system_home.tr,
        ),
        body: controller.currentPage,
        bottomNavigationBar: BottomNavigationBar(
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: LocaleKeys.system_home.tr,
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.sports_baseball),
              label: "123"+LocaleKeys.system_planet.tr,
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.add),
              label: LocaleKeys.system_issue,
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.messenger),
              label: LocaleKeys.system_message,
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.people),
              label: LocaleKeys.system_my,
            ),
          ],
          currentIndex: controller.currentIndex.value,
          selectedItemColor: Colors.blue,
          onTap: controller.changePage,
        ),
      ),
    );
  }
}
```

`
lib/app/modules/home/views/home_view.dart:20:33: Error: Not a constant expression.
              label: LocaleKeys.system_homes.tr,
                                ^^^^^^^^^^^^
lib/app/modules/home/views/home_view.dart:24:39: Error: Not a constant expression.
              label: "123"+LocaleKeys.system_planet.tr,
                                      ^^^^^^^^^^^^^
lib/app/modules/home/views/home_view.dart:17:18: Error: Constant evaluation error:
          items: const <BottomNavigationBarItem>[
                 ^
lib/app/modules/home/views/home_view.dart:20:46: Context: Extension operations can't be used in constant expressions.
              label: LocaleKeys.system_homes.tr,
                                             ^
`

**Comment by jonataslaw** [comment]
Please read the dart documentation, and a little OOP to find out what const are.
If you use a const construct, all elements must be const.

```dart
const <BottomNavigationBarItem>[ // are you using const
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: LocaleKeys.system_home.tr, // TR isn't const
            ),
```
