### ISSUE TITLE
Using custom object as Obs

### ISSUE THREAD

**Issue by omartinma** [jonataslaw/getx#739]
Hi,

I would like to know your thoughts when using custom objects and forms.

As I see we have 2 choices for this, the simplest is making all the object obs doing:
`customClass.obs` or make every field obs that would be really painful.

The problem comes when i want to update single properties of my object. As I understood, making all the object obs will make every property obs as well, so If i update a single property, then every part where I have GetX/Obx should be updated but this is not the case. I just made it work calling customClass.refresh() what I consider the same of using just update() and GetBuilder.

Am I missing something here or we are missing a better way to this kind of scenarios? Or should we not use GetX/Obx for forms?

Thanks.

**Comment by sheepdreamofandroids** [comment]
Why is it really painful to make every field observable?

**Comment by omartinma** [comment]
> Why is it really painful to make every field observable?

Doing so I see 2 alternatives:
1-Creating an obs in the controller itself, so meaning i case of create/edit i need to map manually the field of the controller with the field of the model.
2-Inside of my class make every field obs. In this case, first, i need to mix my model class with something not related with my model like obs meaning I have more dependencies to handle on different parts of my app. Also when parsing values or saving in DB i need to handle specific logic for obs.value for each value. In case of big models can be really painful. 

Anyway, the debate is not that. If make a custom class observable is supported by the framework I guess is for a reason :)

**Comment by sheepdreamofandroids** [comment]
You can wrap any class in an Rx. I'm not sure what you mean by "making a custom class observable".
In the end what you observe are either events saying that the whole instance changed (by using a Rx<CustomClass>) or that the individual fields of the class changed (by wrapping each field).
You say that making your model observable is 'unrelated'. That is your choice, not a given.
I'm not sure what problem arises related to the DB but you might be able to make your own subclass of Rx to fix that.

**Comment by omartinma** [comment]
> You can wrap any class in an Rx. I'm not sure what you mean by "making a custom class observable".
> In the end what you observe are either events saying that the whole instance changed (by using a Rx) or that the individual fields of the class changed (by wrapping each field).
> You say that making your model observable is 'unrelated'. That is your choice, not a given.
> I'm not sure what problem arises related to the DB but you might be able to make your own subclass of Rx to fix that.

Exactly, wrap the whole class with observable doing MyClass().obs. Doing reference to the documentation:

"
final user = User(name: 'John', last: 'Doe', age: 33).obs;

// `user` is "reactive", but the properties inside ARE NOT!
// So, if we change some variable inside of it...
user.value.name = 'Roi';
// The widget will not rebuild!,
// `Rx` don't have any clue when you change something inside user.
// So, for custom classes, we need to manually "notify" the change.
user.refresh();

// or we can use the `update()` method!
user.update((value){
  value.name='Roi';
});

print( user );
"

So what is the point of having this? I mean, what it is the benefit of having the whole class wrap in obs if the properties inside are not observable? Dont you think if quite weird to have this?

**Comment by jonataslaw** [comment]
Note that this is definitely not the appropriate place to ask questions, this was notified to you when you clicked on the issue form. Please use the community channels for this.
An observable object is one that generates one notifies its listeners when its object receives a new instance. When creating an Observable Model, you must either create the properties you want to be reactive with a .obs, or using the update method, which will make a copy of your current class, and update only the changed property (in the case of mutable classes ) or a new object (in the case of immutable classes).
The documentation is clear enough about that, including examples.
Well, as this question shouldn't even be here, I'm closing. Please do not use this channel for questions of use again, however if you find a bug or have a request for resources, open an issue, otherwise, look for a suitable channel for it like Discord, Telegram, Slack, or even StackOverflow.

**Comment by omartinma** [comment]
> Note that this is definitely not the appropriate place to ask questions, this was notified to you when you clicked on the issue form. Please use the community channels for this.
> An observable object is one that generates one notifies its listeners when its object receives a new instance. When creating an Observable Model, you must either create the properties you want to be reactive with a .obs, or using the update method, which will make a copy of your current class, and update only the changed property (in the case of mutable classes ) or a new object (in the case of immutable classes).
> The documentation is clear enough about that, including examples.
> Well, as this question shouldn't even be here, I'm closing. Please do not use this channel for questions of use again, however if you find a bug or have a request for resources, open an issue, otherwise, look for a suitable channel for it like Discord, Telegram, Slack, or even StackOverflow.

Sorry but my issue it was not a question, it is pointing something that is not clear in the documentation because it is saying the 2 ways are equivalent when it is not(https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#where-obs-can-be-used)

**Comment by GanongLS** [comment]
> > Note that this is definitely not the appropriate place to ask questions, this was notified to you when you clicked on the issue form. Please use the community channels for this.
> > An observable object is one that generates one notifies its listeners when its object receives a new instance. When creating an Observable Model, you must either create the properties you want to be reactive with a .obs, or using the update method, which will make a copy of your current class, and update only the changed property (in the case of mutable classes ) or a new object (in the case of immutable classes).
> > The documentation is clear enough about that, including examples.
> > Well, as this question shouldn't even be here, I'm closing. Please do not use this channel for questions of use again, however if you find a bug or have a request for resources, open an issue, otherwise, look for a suitable channel for it like Discord, Telegram, Slack, or even StackOverflow.
> 
> Sorry but my issue it was not a question, it is pointing something that is not clear in the documentation because it is saying the 2 ways are equivalent when it is not(https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#where-obs-can-be-used)

I agree with you, i still don't understand what is the benefit doing all object with .obs and if it's can't be read, then all of syntactic sugar offered by package will be wasted.

**Comment by ghprod** [comment]
> > > Note that this is definitely not the appropriate place to ask questions, this was notified to you when you clicked on the issue form. Please use the community channels for this.
> > > An observable object is one that generates one notifies its listeners when its object receives a new instance. When creating an Observable Model, you must either create the properties you want to be reactive with a .obs, or using the update method, which will make a copy of your current class, and update only the changed property (in the case of mutable classes ) or a new object (in the case of immutable classes).
> > > The documentation is clear enough about that, including examples.
> > > Well, as this question shouldn't even be here, I'm closing. Please do not use this channel for questions of use again, however if you find a bug or have a request for resources, open an issue, otherwise, look for a suitable channel for it like Discord, Telegram, Slack, or even StackOverflow.
> > 
> > 
> > Sorry but my issue it was not a question, it is pointing something that is not clear in the documentation because it is saying the 2 ways are equivalent when it is not(https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#where-obs-can-be-used)
> 
> I agree with you, i still don't understand what is the benefit doing all object with .obs and if it's can't be read, then all of syntactic sugar offered by package will be wasted.

Usually, I use `copyWith` with reactive class and update them inside the controller

Something like this

```dart
class Controller extends GetxController {
  final Rx<User> _user = Rx<User>();

  submit() {
    _user.value = userModel.copyWith(...);
  }
}
```

**Comment by Lakhankumawat** [comment]
> > > Note that this is definitely not the appropriate place to ask questions, this was notified to you when you clicked on the issue form. Please use the community channels for this.
> > > An observable object is one that generates one notifies its listeners when its object receives a new instance. When creating an Observable Model, you must either create the properties you want to be reactive with a .obs, or using the update method, which will make a copy of your current class, and update only the changed property (in the case of mutable classes ) or a new object (in the case of immutable classes).
> > > The documentation is clear enough about that, including examples.
> > > Well, as this question shouldn't even be here, I'm closing. Please do not use this channel for questions of use again, however if you find a bug or have a request for resources, open an issue, otherwise, look for a suitable channel for it like Discord, Telegram, Slack, or even StackOverflow.
> > 
> > 
> > Sorry but my issue it was not a question, it is pointing something that is not clear in the documentation because it is saying the 2 ways are equivalent when it is not(https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#where-obs-can-be-used)
> 
> I agree with you, i still don't understand what is the benefit doing all object with .obs and if it's can't be read, then all of syntactic sugar offered by package will be wasted.

I agree with all you guys in documentation as @jonataslaw  specified i don't see any explanation for custom class objects .

**Comment by wiztensai** [comment]
i use freezed package to make sealed class state for combine with getx. 

method refresh() works!

```
var state = const ManageOrderState.initial().obs;
final List<String> _tabs = [];
state.value = ManageOrderState.update(_tabs);
state.refresh();
```
