### ISSUE TITLE
Get.width doesn't work on Linux and Windows

### ISSUE THREAD

**Issue by martin-robert-fink** [jonataslaw/getx#741]
**Describe the bug**
Using Get.width works fine on devices and MacOS, but does not work on Linux and Windows (for now, had to change back to using MediaQuery.

**Reproduction code**
See Below

**To Reproduce**
Build on Device (Android/iOS) or MacOS - works fine; build for Windows/Linux, does not work.
The state management parts of GetX seem to work just fine on Windows/Linux.

**Expected behavior**
Get.width returns device/window width on all platforms

**Flutter Version:**
Enter the version of the Flutter you are using
1.24.0-3.0.pre (Dev Channel)

**Getx Version:**
Enter the version of the Getx you are using
3.13.2

**Describe on which device you found the bug:**
Windows 10, Ubuntu Linux

**Minimal reproduce code**
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:auto_size_text/auto_size_text.dart';

class AppTitle extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      child: Container(
        width: Get.width * .8,
        alignment: Alignment.center,
        child: AutoSizeText(
          'Application Title',
          textScaleFactor: 1.0,
          style: Theme.of(context).textTheme.headline1,
          minFontSize: 14,
          maxLines: 1,
        ),
      ),
    );
  }
}
```

**Comment by jonataslaw** [comment]
You needed to use GetMaterialApp in previous versions for it to work.
I believe that in 3.15 none of this is needed anymore, because the direct API of dart is accessed. 
I can't reproduce in 3.15, but if you have problems, don't hesitate to open another issue.

**Comment by martin-robert-fink** [comment]
Thanks.  I was using GetMaterialApp, but 3.15 did indeed fix the problem.  Now works on Windows and Linux.  Thanks again.
