### ISSUE TITLE
unknownRoute cant work 

### ISSUE THREAD

**Issue by echomartha** [jonataslaw/getx#743]
**Expected behavior**
to handle not found route

**Screenshots**
![image](https://user-images.githubusercontent.com/71472725/97129311-81237b80-1779-11eb-9a4b-5fe991c77107.png)

**Flutter Version:**
1.23.0-18.1.pre

**Getx Version:**
get: ^3.15.0

**Describe on which device you found the bug:**
device : flutter web.

**Minimal reproduce code**
this is my code
```
GetMaterialApp(
          debugShowCheckedModeBanner: false,
          localizationsDelegates: context.localizationDelegates,
          unknownRoute: GetPage(
            name: DrawerMainMenuScreen.route,
            page: () => DrawerMainMenuScreen(),
          ),
          supportedLocales: context.supportedLocales,
          locale: context.locale,
          navigatorKey: NavigationService.navigationKey,
          title: 'Chaca Shop',
          initialRoute: DrawerMainMenuScreen.route,
          theme: ThemeData(......),
          getPages: [.....]
```

**Comment by eduardoflorence** [comment]
@echomartha I did a test now with version 3.15 of GetX and it is working without errors.
Please do the commands below:
```
flutter clean
flutter pub cache repair
flutter pub get
```
If it doesn't work, provide a code with more details so that we can more easily reproduce the problem (copy, paste and run)

**Comment by jonataslaw** [comment]
I was able to test and confirm that this feature is working correctly, in addition, the error has no relation to Getx, since there is no "_get" variable in this framework.
Since this question is invalid, I am ending it.
