### ISSUE TITLE
Get.Back() not closing open Dialog

### ISSUE THREAD

**Issue by altafkhan8719** [jonataslaw/getx#750]
void register() async {
    Get.dialog(Center(child: CircularProgressIndicator()),
        barrierDismissible: false);
    String url = "api/users";
    UserRequestModel userRequestModel = UserRequestModel();
    userRequestModel.fullname = fullNameTextController.text;
    userRequestModel.actionId = 0;
    userRequestModel.userId = 0;
    userRequestModel.statusId = 0;
    userRequestModel.username = emailTextController.text;
    userRequestModel.password = conFirmPasswordTextController.text;
    userRequestModel.isLoggedInByEmail = true;

    HttpDio dio = HttpDio();
    await dio.httpPost(url, userRequestModel.toJson()).then((response) {
   
      if (response != null) {
        UserResponseModel userResponseModel =
            UserResponseModel.fromJson(response.data);
      } else {
        HttpDio.httpError("error".tr);
      }
     
      Get.back();
    
    }).catchError((onError) {
      HttpDio.httpError(onError.toString());

    });
  }

**Comment by komangsidhiartha** [comment]
Hello @altafkhan8719 , 

did you find the solution to this problem?

We are facing the same issue right now

**Comment by eduardoflorence** [comment]
@altafkhan8719, I did the test now with the code below and it is working normally.
Please provide more details of your code and the versions of Flutter and Getx you are using.
Important: `Get.back` should be in `whenComplete` and not `then`, because the dialog needs to be closed on success and error

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(
    home: HomePage()
  ));
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('HOME')),
      body: Center(
        child: RaisedButton(
          onPressed: () => register(),
          child: Text('Register'),
        ),
      ),
    );
  }
}

void register() async {
  Get.dialog(
    Center(child: CircularProgressIndicator()),
    barrierDismissible: false,
  );

  await Future.delayed(Duration(seconds: 3)).then((response) {
    Get.back();
  });
}
```
