### ISSUE TITLE
InitialRoute rebuilt on input

### ISSUE THREAD

**Issue by DevonJerothe** [jonataslaw/getx#751]
I am trying to create a simple login page and authentication. When the user opens the app it will auto log them in and then move to the home screen when its a success or send to the logIn Screen. This works fine until I activate any textfield after logging in. If I activate the keyboard, or hot reload, the app rebuilds the initial route and rechecks. I get sent back to the home screen. 

the initial route should only be built once, or when update() is called. Am I missing something here?

I'm changing over from Bloc. This was working with a BlocBuilder. 

GetMaterialApp Example:
```dart
return GetBuilder<SettingsController>(
      init: SettingsController(),
      initState: (_) {
        Get.put(AuthController(), permanent: true);
        Get.put(ContactController(), permanent: true);
        Get.put(AlertsController(), permanent: true);
      },
      builder: (c) => GetMaterialApp(
          navigatorKey: _nav,
          debugShowCheckedModeBanner: false,
          onGenerateTitle: (context) => I18n.of(context).title,
          localizationsDelegates: [
            I18n.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate
          ],
          supportedLocales: I18n.delegate.supportedLocales,
          localeResolutionCallback:
              I18n.delegate.resolution(fallback: Locale('en', 'US')),
          theme: c.settings.darkMode ? AppColors.dark : AppColors.light,
          darkTheme: c.settings.useSystemDark ? AppColors.dark : null,
          // home: LogInCheck(),
          initialRoute: r.Router.initialRoute,     
          getPages: r.Router.getPages(),
        ),
    );
```

Initial Route Example: (Get)
```dart
class LogInCheck extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SizeConfig().init(context);
    return GetBuilder<AuthController>(
      initState: (_) {
        AuthController.to.checkAutoLogIn(SettingsController.to.settings);
      },
      builder: (a) {
        if (a.loggedIn) {
          return AppNavDrawer();
        }
        return LoginScreen();
      },
    );
  }
}
```

**Flutter Version:**
stable 1.22.2

**Getx Version:**
3.12.1

**Describe on which device you found the bug:**
IOS and Android

**Comment by eduardoflorence** [comment]
Please provide a code that allows you to reproduce the problem just by copying and pasting in our editor. This makes it much faster to help you. It is important to follow the guidelines for opening an issue

**Comment by DevonJerothe** [comment]
Unfortunately that is very difficult to do with the current application. Upon further debugging the issue seemed to be coming from 

```dart
SizeConfig().init(context);
```

closing this issue.
