### ISSUE TITLE
Private _RxImpl exposes public interfaces.

### ISSUE THREAD

**Issue by vimmerru** [jonataslaw/getx#752]
**Describe the bug**
Some public interfaces of Rx classes are defined in `_RxImpl<T>` instead of `RxInterface<T>`. Example, is `StreamSubscription<T> listen` call. It is obvious bad practice and causes some issues like impossibility to add any extension methods to RxInterface based on `listen`.

**Expected behavior**
All public methods of Rx classes should be defined on public interfaces.

**Flutter Version:**
Not matter

**Getx Version:**
^3.13.2

**Comment by eduardoflorence** [comment]
In GetX 3.15.0, `StreamSubscription<T> listen` is in` RxInterface<T> `

https://github.com/jonataslaw/getx/blob/3.15.0/lib/get_rx/src/rx_core/rx_interface.dart

**Comment by vimmerru** [comment]
@eduardoflorence 

**RxInterface**

`StreamSubscription<T> listen(ValueCallback<T> callback);`

**_RxImpl**

`StreamSubscription<T> listen(void Function(T) onData,
          {Function onError, void Function() onDone, bool cancelOnError}) =>
      stream.listen(onData, onError: onError, onDone: onDone);`

Quite different interfaces

**Comment by vimmerru** [comment]
@jonataslaw Why invalid? Interface changed in _RxImpl. RxInterface has method with the same name, but it is different method than i am talking a about.

**Comment by jonataslaw** [comment]
Closing this question, as it is an old version, and the description has no correlation with the current version.
Upgrade to version 1.16 or higher.
