### ISSUE TITLE
[Feature Request] Support CupertinoPageRoute swipe to back android and ios. 

### ISSUE THREAD

**Issue by nguyenlinhnttu** [jonataslaw/getx#753]
First I want to thank you for the effort to bring us this amazing library, it's really time saving!

I want to know if is it possible to support CupertinoPageRoute for android and ios .

Such as: 
Get.toNamed('/country', route: Router.Cupertino);

Swipe back is nice feature, android user very like it.

Thanks.

**Comment by jonataslaw** [comment]
`popGesture: true` made it
