### ISSUE TITLE
Warning when using Get.changeTheme() if there is a FloatingActionButton

### ISSUE THREAD

**Issue by trongnghiapix** [jonataslaw/getx#758]
When i was following the document for changing theme, I got this warning:

> flutter: Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead. See https://flutter.dev/go/remove-fab-accent-theme-dependency. This feature was deprecated after v1.13.2.

Notable it only appears if there is a FAB. If floatingActionButton property of Scaffold is removed, it won't show up anymore.

**Reproduce code**
```dart
void main() => runApp(GetMaterialApp(home: Home()));

class Home extends StatelessWidget {
  @override
  Widget build(context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          child: Text('Change Theme'),
          onPressed: () {
            Get.changeTheme(Get.isDarkMode ? ThemeData.light() : ThemeData.dark());
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.highlight),
        onPressed: () {
          Get.changeTheme(Get.isDarkMode ? ThemeData.light() : ThemeData.dark());
        },
      ),
    );
  }
}
```

**Flutter Version:**
1.22.2

**Getx Version:**
3.15.0

**Comment by jonataslaw** [comment]
I believe that your own comment and the warning itself answer your question.
"Notable it only appears if there is a FAB. If floatingActionButton property of Scaffold is removed, it won't show up anymore"
This is a warning that the ThemeData.accentIconTheme property used in FloatingActionButton has been deprecated.
This has nothing to do with Getx, and FloatingActionButton is a property of Flutter, not Getx.
As this question should not be here, I am closing.
