### ISSUE TITLE
RxBool value change does not trigger UI re-build

### ISSUE THREAD

**Issue by maares** [jonataslaw/getx#761]
Hi, not sure it's a bug or not, does Rx type have different behaviour?

**To Reproduce**
N/A

**Expected behavior**
RxBool type does not trigger UI changes when modifying its value. RxString does trigger UI re-build (testing purposes )

**Screenshots**

![myVideo-1](https://user-images.githubusercontent.com/37770669/97908314-d3026d80-1d46-11eb-9429-230b71345f40.gif)

**Flutter Version:**
Flutter 1.24.0-7.0.pre.41 • channel master • https://github.com/flutter/flutter.git
Framework • revision 72267a6cd0 (3 days ago) • 2020-10-31 13:23:02 +0900
Engine • revision 3460519398
Tools • Dart 2.12.0 (build 2.12.0-3.0.dev)

**Getx Version:**
^3.15.0

**Describe on which device you found the bug:**
ex: Pixel 2 - Android. / Iphone 12 PRO Max

**Minimal reproduce code**
```
import 'package:get/get.dart';

class BuilderController extends GetxController {

  RxString rxString = ''.obs;
  RxBool rxBool = false.obs;

  void onReady() {
    Future.delayed(Duration(seconds: 5), () {
      rxBool = true.obs;
      rxString.value = 'This does change';
    });
    super.onReady();
  }
}

class BuilderView extends GetView<BuilderController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Obx(() => Text(controller.isBuilderDone.value.toString())),
      ),
      body: Obx(() => Text(controller.asd.value)),
    );
  }
}
```

**Comment by ben-xx** [comment]
```
  void onReady() {
    Future.delayed(Duration(seconds: 5), () {
      rxBool.value = true; // <== try this ===========
      rxString.value = 'This does change';
    });
    super.onReady();
  }
```

**Comment by eduardoflorence** [comment]
You can use:
```dart
rxBool.value = true;
```
Or:
```dart
rxBool.toggle();  // A shortcut for flag.value = !flag.value;
```

**Comment by maares** [comment]
Hi guys, thanks for the reply, removing the .obs when changing the value did the trick. I did not even see it.

Thanks again, closing the issue, sorry for the noob mistake!
