### ISSUE TITLE
Error: No named parameter with the name 'shadowThemeOnly'.

### ISSUE THREAD

**Issue by worldofsites** [jonataslaw/getx#762]
```
Launching lib\main.dart on sdk gphone x86 in debug mode...
lib\main.dart:1
/C:/Frameworks/flutter/.pub-cache/hosted/pub.dartlang.org/get-3.15.0/lib/get_navigation/src/extension_navigation.dart:235:37: Error: No named parameter with the name 'shadowThemeOnly'.
    final theme = Theme.of(context, shadowThemeOnly: true);
                                    ^^^^^^^^^^^^^^^
/C:/Frameworks/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
/C:/Frameworks/flutter/.pub-cache/hosted/pub.dartlang.org/get-3.15.0/lib/get_navigation/src/extension_navigation.dart:431:43: Error: No named parameter with the name 'shadowThemeOnly'.
      theme: Theme.of(key.currentContext, shadowThemeOnly: true),
                                          ^^^^^^^^^^^^^^^
/C:/Frameworks/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.24.0-7.0.pre.69, on Microsoft Windows [Version 10.0.19041.572], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

• No issues found!
```

pubspec.yaml:
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^3.15.0
```

Related to that line:   https://github.com/flutter/flutter/blob/b77088319acfd6189fb2b4cb37342de251e31201/packages/flutter/lib/src/material/theme.dart#L119

Changed by @goderbauer in that commit: https://github.com/flutter/flutter/commit/0490fd75aa5d59a7f2a4dae4c62543fc6e7b33cf#

**Comment by sashker** [comment]
I have the same issue
Flutter (Channel master, 1.24.0-7.0.pre.75, on Mac OS X 10.15.7 19H2 darwin-x64, locale ru)

**Comment by Kerwit** [comment]
I have the same issue
Flutter (Channel master, 1.24.0-7.0.pre.75, on Microsoft Windows [VersiÃ³n 10.0.18363.1139], locale es-ES)

**Comment by jonataslaw** [comment]
I will need to create another branch for this, and probably upload a beta version from Getx to the pub. However the master changes easily, I am waiting for the update to be consolidated in the dev.

**Comment by yoseptara** [comment]
> I will need to create another branch for this, and probably upload a beta version from Getx to the pub. However the master changes easily, I am waiting for the update to be consolidated in the dev.

how long it will take time?

**Comment by sefaozdemir44** [comment]
I have the same issue.

**Comment by shariful2011** [comment]
I have the same issue. How much time will it take to fix the issue?

**Comment by UsamaElgendy** [comment]
same issue .

**Comment by eduardofcr** [comment]
I have the same issue

**Comment by jonataslaw** [comment]
Fix on 3.16.1

**Comment by bksubhuti** [comment]
snapd of flutter has same issue nov 29

**Comment by jonataslaw** [comment]
Look for previous comment, it's fixed.

**Comment by bksubhuti** [comment]
I only got snapd yesterday.. so why would update fix it?

**Comment by jonataslaw** [comment]
> I only got snapd flutter version yesterday.. so why would update fix it?

In addition to updating Flutter, you need to update your dependencies.
Use the flutter pub upgrade command, and if you experience using constraints, update the package version to the most current version.

**Comment by lukee1234** [comment]
Just switched to beta channel, just did pub get and pub upgrade.
All the dependencies are up to date (did pub outdated).
Facing the same issue.

Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 6.1.7601], locale it-IT)
    • Flutter version 1.24.0-10.2.pre at C:\src\flutter
    • Framework revision 022b333a08 (13 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

**Comment by r4matero** [comment]
Update your dependencies, to the latest version, had the same issue but worked after updating all the dependencies.

**Comment by bksubhuti** [comment]
there are no dependencies with snapd  .  That is why we have snap
Bhante Subhuti

https://AmericanMonk.org
https://withmetta.net

**Comment by mesabo** [comment]
in my case in put only get: in pubspec otherwise get: ^xxxx

**Comment by sajanyamaha** [comment]
> > I will need to create another branch for this, and probably upload a beta version from Getx to the pub. However the master changes easily, I am waiting for the update to be consolidated in the dev.
> 
> how long it will take time?
> 
> And does anyone know which function in this package that caused this problem?

Package is get: ^3.26.0
https://pub.dev/packages/get/install
