### ISSUE TITLE
Animations with SingleTickerProviderStateMixin on Getx 

### ISSUE THREAD

**Issue by kakdeykaushik** [jonataslaw/getx#767]
Cannot use animation Mixins which requires `stateful` widget like `SingleTickerProviderStateMixin`. Using these Mixins throws error `SingleTickerProviderStateMixin' can't be mixed onto 'Object' because 'Object' doesn't implement 'State<StatefulWidget>'`

**Comment by jonataslaw** [comment]
Hi, use SingleGetTickerProviderMixin:

```dart
class Controller extends GetxController with SingleGetTickerProviderMixin{
}
```

**Comment by eduardoflorence** [comment]
See example: https://github.com/jonataslaw/getx/issues/733#issuecomment-717550205

**Comment by myndsol-naveen** [comment]
```
class Controller extends GetxController with GetSingleTickerProviderStateMixin{
}
```

As per update in _get_ package. Hope that helps.

**Comment by NaveenNirban** [comment]
``` class Controller extends GetxController with GetSingleTickerProviderStateMixin{```
``` } ``` 


As per update in `get` package. Hope that helps.

**Comment by RafaRuiz** [comment]
It would be great if we could integrate this in the `GetWidget` side and file to maintain and keep the controllers UI-agnostic.
