### ISSUE TITLE
Parameters for nested navigation with dynamic routes

### ISSUE THREAD

**Issue by zzterrozz** [jonataslaw/getx#768]
Hi @jonataslaw

[https://github.com/jonataslaw/getx/issues/179#issuecomment-638492983](https://github.com/jonataslaw/getx/issues/179#issuecomment-638492983)
Any chance to have an implementation of parameters for nested navigation with dynamic routes please ?

**Comment by Azzeccagarbugli** [comment]
@jasonlaw do you any updates about this?

**Comment by Azzeccagarbugli** [comment]
@jonataslaw do you have any news about this?

**Comment by jonataslaw** [comment]
Use PageRedirect(settings: settings, unknownRoute: unknownRoute).page(); inside of onGenerateRoute, or to use new GetRouterOutlet
