### ISSUE TITLE
Get.until() transition

### ISSUE THREAD

**Issue by brandedgames** [jonataslaw/getx#769]
**Is your feature request related to a problem? Please describe.**
A transition with duration for the Get.until() api would be usefull since other routing api's have this also. And there is inconsistency in Get apps in terms of routing transitions.

**Describe the solution you'd like**
  Get.until((route) => route.isFirst, duration: Duration(seconds: 1), transition: Transition.fadeIn);

**Comment by jonataslaw** [comment]
Get.until is the same as Navigator.popUntil, there is no way to define transitions for pop events.
As this feature will not be implemented, I am closing this.
