### ISSUE TITLE
How to correctly set Translation keys from a dynamic  Map?

### ISSUE THREAD

**Issue by NoldyNayoan** [jonataslaw/getx#770]
Hi,
How to correctly set Translation keys from a dynamic  Map?
I have tried the following code, but the code produces error : 

"The following NoSuchMethodError was thrown building GetMaterialApp:
The getter 'keys' was called on null.
Receiver: null
Tried calling: keys"

// main.dart
`
  void main() async {
        runApp(App());
}

Future loadTranslations() async {
  final api = TranslationApi();
  Map<String, Map<String, String>> map = await api.getTranslationListMock();
  Get.find`<`TextTranslations`>`().map = map;
}`

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
       Get.put(TextTranslations());
       loadTranslations();
   return GetMaterialApp(
     translationsKeys: Get.find `<`TextTranslations`>` ().map,
     translations: TextTranslations(),
     builder: (context, child) {
      ...
      }
);
}

// TextTranslations.dart
class TextTranslations extends Translations {
  Map<String, Map<String, String>> map;

  @override
  Map<String, Map<String, String>> get keys => map;
}
`
the Map value in translationsKeys: Get.find'<'TextTranslations'>'().map, IS NULL. Any idea how to fix this? Thanks.

**Comment by eduardoflorence** [comment]
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() async {
  Get.put(TextTranslations());
  await TranslationApi.loadTranslations();
  runApp(App());
}

class App extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      translationsKeys: Get.find<TextTranslations>().keys,
      translations: Get.find<TextTranslations>(),
      home: Container(
        child: Text('hello'.tr)
      ),
    );
  }
}


class TextTranslations extends Translations {
  Map<String, Map<String, String>> map;

  @override
  Map<String, Map<String, String>> get keys => map;
}

class TranslationApi {
  getTranslationListMock() {
    return {
      'en_US': {
        'hello': 'Hello World',
      },
      'de_DE': {
        'hello': 'Hallo Welt',
      }
    };
  }

  static Future loadTranslations() async {
    final api = TranslationApi();
    Map<String, Map<String, String>> map = await api.getTranslationListMock();
    Get.find<TextTranslations>().map = map;
  }
}
```

**Comment by NoldyNayoan** [comment]
Hi, thank  you so much for the corrected code. I have tried it and It's working!. 
Many thanks again....

**Comment by eduardoflorence** [comment]
You're welcome, I'm happy to contribute. As it was resolved I will close this issue
