### ISSUE TITLE
Adjust to Null Safety

### ISSUE THREAD

**Issue by hiuryanderson** [jonataslaw/getx#775]
I'm not able to compile using the --enable-experiment = non-nullable option in the new version of Dart;

Adjust the code for null safety compilation.

**Comment by jonataslaw** [comment]
![image](https://user-images.githubusercontent.com/35742643/98451957-b3de5400-2129-11eb-8458-ecd884b85e9d.png)

Since null security is stable, we will update.
Maybe I will create a development branch with null-safety, but for now the flutter/dart team recommends not using it in packages - yet.
