### ISSUE TITLE
 How can I access the widgets under the Navigator

### ISSUE THREAD

**Issue by stjfk** [jonataslaw/getx#776]
Hi, I'm using the following code block shared by @roipeker

https://github.com/jonataslaw/getx/issues/552#issuecomment-686158966

```
class _TabNav extends GetView<RootController> {
  final ScreenModel model;
  _TabNav(this.model);

  @override
  Widget build(BuildContext context) {

    return Navigator(
      key: Get.nestedKey(model.navKey),
      onGenerateRoute: (settings) =>
          MaterialPageRoute(
            builder: (_) => model.body
          ),
    );
  }
}

```

But I can't access the widgets (for runtimeType etc) that appear under the Navigator. How can i access?

![widget tree](https://user-images.githubusercontent.com/70009860/98470014-ea80a100-21f3-11eb-8dad-a092aae2781a.jpg)

**Comment by jonataslaw** [comment]
Hi, Navigator is a Flutter widget.
Please open the issue in the appropriate repository.
