### ISSUE TITLE
 Undefined class GetStorage  error

### ISSUE THREAD

**Issue by xyzbilal** [jonataslaw/getx#778]
Hi I am trying to implement GetStorage but I am gettin error. I previously using hive but I want to reduce app size so decided to replace hive with GetStorage but I am getting the error shown in picture.any Idea will be appreciated. 
![Ekran Resmi 2020-11-09 11 51 59](https://user-images.githubusercontent.com/18241412/98523056-80650c00-2286-11eb-9a63-f1c663cadc65.png)

**Comment by eduardoflorence** [comment]
GetStorage is a separate package from GetX.
https://pub.dev/packages/get_storage
Did you add it to your pubspec?

**Comment by xyzbilal** [comment]
Hi @eduardoflorence , 
I didnt know that is a seperate package. it really looks great package.thanks for comment.
