### ISSUE TITLE
throws exception when using Layout Builder as a child for GetX

### ISSUE THREAD

**Issue by amirc901** [jonataslaw/getx#780]
**Describe the bug**

if i use a layout builder as a child for GetX or Obx it throws exceptions that says

 [Get] the improper use of a GetX has been detected.        You should only use GetX or Obx for the specific widget that will be updated.       If you are seeing this error, you probably did not insert any observable variables into GetX/Obx        or insert them outside the scope that GetX considers suitable for an update        (example: GetX => HeavyWidget => variableObservable).       If you need to update a parent widget and a child widget, wrap each one in an Obx/GetX.

I think this is because I am using Observable.value inside the layout builder which doesn't add a listener to getObs until the layout builder lays out the widget and it causes the if (!_observer.canUpdate) (in GetX class line 116)  to be true and it throws the exception

```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final AppController appController = Get.put(AppController());
  final HomePageController controller = Get.put(HomePageController());



  @override
  Widget build(BuildContext context) {
    print(Get.find<HomePageController>().count);
    return Scaffold(
      body: Container(
        child: Column(
          children: [
            Expanded(
              child: Center(
                child: GetX<HomePageController>(
                  builder: (controller) => LayoutBuilder(
                    builder: (context, _) {
                      print("Count Build");
                      return Text("Count ${controller.count}");
                    },
                  ),
                ),
              ),
            ),
            Expanded(
              child: Center(
                child: GetX<HomePageController>(
                  builder: (controller) => LayoutBuilder(
                    builder: (context, _) {
                      print("Title Build");
                      return Text("Title ${controller.name}");
                    },
                  ),
                ),
              ),
            ),
            CountButton(),
            RaisedButton(
              child: Text("Change the Title"),
              onPressed: () {
                HomePageController homeController = Get.find();

                homeController.name.value =
                    "${DateTime.now().millisecondsSinceEpoch}";
              },
            )
          ],
        ),
      ),
    );
  }
}

class CountButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RaisedButton(
      child: Text("Count++"),
      onPressed: () {
        HomePageController controller = Get.find();
        var newValue = controller.increment();
        print(newValue);
      },
    );
  }
}

class AppController extends GetxController {
  RxString title = "App Title".obs;
}

class HomePageController extends GetxController {
  RxInt count = 0.obs;
  RxString name = "Amir".obs;

  increment() {
    count.value++;
    update();
  }
}

```

**Flutter doctor output

 Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18362.1139], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[!] VS Code (version 1.50.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 3 categories.

**Getx Version:**
^3.15.0

**Comment by eduardoflorence** [comment]
This is expected behavior. To contribute to the performance of your App, a forced exception is thrown. You must use the Getx widget (or GetBuilder, Obx) to wrap the internal widget that has the observable.

```dart
Expanded(
  child: Center(
    child: LayoutBuilder(
      builder: (context, _) {
        print("Count Build");
        return GetX<HomePageController>(
          builder: (controller) =>
              Text("Count ${controller.count}"),
        );
      },
    ),
  ),
),
```

**Comment by jonataslaw** [comment]
As pointed out by eduardoflorence, this is the default behavior to avoid unnecessary reconstructions of widgets.
Closing this.
