### ISSUE TITLE
 Get.focusScope.requestFocus(FocusNode()); Not Work

### ISSUE THREAD

**Issue by babakoto** [jonataslaw/getx#783]
I want close Soft input keybord  in TextField 
I'm using GetMaterial in my main .
everything works ( Get.to() , 
Get.back etc ... ) 
 except **Get.focusScope**
 Get.focusScope.requestFocus(FocusNode()); 

![image](https://user-images.githubusercontent.com/44688702/98728613-04f47f00-239a-11eb-95fc-f99a8af616a8.png)

dependencies:
  get: ^3.16.1

**Comment by eduardoflorence** [comment]
To close the keyboard use:
```dart
Get.focusScope.unfocus()
```

**Comment by eduardoflorence** [comment]
@babakoto cant this issue closed?

**Comment by babakoto** [comment]
@eduardoflorence  thanks , yes

**Comment by gromoo** [comment]
nice
