### ISSUE TITLE
Version 3.16.2 - Changes in work with Streams

### ISSUE THREAD

**Issue by psycura** [jonataslaw/getx#787]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
I turn an Rx value to a stream by using `.steam`
In version 3.15.0 everything work ok, i can listen to this stream, and it will work whenever i set new value to my Rx value.
But in version 3.16.2 it seem to be broken

**Reproduction code
example:

I declare the Rx value like this:
```dart
  Rx<BleCommandItemModel> _bleCommand = Rx<BleCommandItemModel>();

  BleCommandItemModel get bleCommand => _bleCommand.value;

  Stream<BleCommandItemModel> get bleCommandStream => _bleCommand.stream;

  set bleCommand(BleCommandItemModel value) => _bleCommand.value = value;
```

Then in other place:

```dart
  /// ### Initialize handler for [bleCommandStream] ###
  /// On every new command, that added to the [bleCommandStream] run [_sendCommandHandler]
  void initCommandsHandler() {
    Log.info(tag, 'initCommandsHandler');
    bleCommandStream.asyncMap((command) async {
      if(command!=null){
        Log.info(tag, 'New commands added $command');
        await _sendCommandHandler(command);
      }
    }).listen(null);
  }

```

and finally the method where i assign new value to the bleCommand
```dart
bool addCommand(
    ProtoEnums_PacketType packetType, {
    Uint8List payload,
    BleRequestState stateForUpdateOnSend,
    Function onSuccessCb,
    Function onErrorCb,
  }) {
    Log.info(tag, 'addCommand $packetType');

    var task = BleCommandItemModel(...);

    Log.info(tag,
        "adding command: ${task.toString()} (id: ${task.transactionNum.toString()})");

    bleCommand = task;

    return true;
  }
```

So the issue is that bleCommandStream.asyncMap work only at first time, and than, when i try to send next command, .asyncMap not fired.
Revert back to 3.15.0 solve the issue

**Comment by jonataslaw** [comment]
Hi, I was unable to reproduce your code, but I suspect what may be happening. Could you make these changes and see if it works?
If positive or negative, let me know that I will make an update to fix this.

```dart
class YourClass{
  YourClass(){
  bleCommandStream = _bleCommand.stream;
  }

  Stream<BleCommandItemModel> bleCommandStream;
}

```

Thanks

**Comment by psycura** [comment]
Do you mean to initialize stream within class constructor?
But this class is the GetxController, so should i do it in the onInint?

**Comment by jonataslaw** [comment]
> Do you mean to initialize stream within class constructor?
> But this class is the GetxController, so should i do it in the onInint?

Hi, I'm not recommending you do this, just asking you to check the behavior with this test, as I couldn't reproduce your code, I need to know if a new instance of GetStreamTransformation is being created when you use a getter (because I tried to reproduce without a getter and I couldn't, if the problem is in using a getter for you, I can solve it in the update that will be done in 40 minutes).

**Comment by psycura** [comment]
Hello, and sorry for the late response.

Solution, that you proposed, doesn't help much, however i did a different tests with simply logic, to make possible provide you a reproducible code, and found out that this issue happen to me only in this specific case, so i removed asyncMap and use only listen for this stream, and this works ok now.

Thank you, for support
