### ISSUE TITLE
Any sample for GetStream

### ISSUE THREAD

**Issue by IsmailAlamKhan** [jonataslaw/getx#788]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

**Is your feature request related to a problem? Please describe.**
No sample or documentation for GetStream.

**Describe the solution you'd like**
Provide some samples or documentation for GetStream.

**Comment by eduardoflorence** [comment]
```dart
void main() {
  var controller = GetStream();
  var stream = controller.stream;
  stream.listen((data) {
    print('$data');
  });
  controller.add('test');  // print 'test'
}
```

**Comment by eduardoflorence** [comment]
Currently the github for this project is to report bugs or request new features. For questions of use, use the appropriate channels for this:
https://github.com/jonataslaw/getx#community-channels
