### ISSUE TITLE
Way to set value of RxList<T>() to non-null list

### ISSUE THREAD

**Issue by jeiea** [jonataslaw/getx#792]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR FEATURE REQUESTS**

> [Discord question](https://discord.com/channels/722900883784073290/727262559496831098/776744888666423306)

**Is your feature request related to a problem? Please describe.**
I want to represent loading state by `RxList<int>()`.
But `RxList<int>().assignAll([])` throws `NoSuchMethodError: The setter 'length=' was called on null.`.
It seems the only solution is `RxList<int>().value = []`, but it is deprecated.
We can set `RxList<int>([])`'s value to null by `.nil()` but there's no reverse of it. It's unnatural.

**Describe the solution you'd like**
- Make `.assign()` and `.assignAll()` replace existing `null` value.
or
- Cancel the deprecation of `value`.

**Describe alternatives you've considered**
Remove `.nil()` and document `RxList` is not for nullable value.

**Comment by jonataslaw** [comment]
`RxList<int>()` made a empty list, not null list, since 1.16 
`RxList<int>(null)` made a null list 

From dart docs, the correct way to inicialize a list, is using literals 
```
final list = []; 
final listInt = <int>[]; 
```

on Getx, the correct way to initialize a list is using .obs;

`final list = [].obs; `

With Getx, you can use non literal sintaxe only when you wanna initialize a variable with null. 

`final list = List(null); `

initialize `List()` will work, but it is against effective dart design.

**Comment by jeiea** [comment]
Then, what is a desirable way to do `RxList<int>(null).assignAll([])`?
It will probably throw an error.

**Comment by Nipodemos** [comment]
can't you simply make `RxList<int>([])` ?

**Comment by jeiea** [comment]
I planned to regard `RxList<T>(null)` as not loaded state, `RxList<T>([])` as loaded but empty state. Currently there no desirable way to do this state transition with `RxList`.
If you meant I should use separate `RxBool`, I think we also should document `RxList<T>(null)` is not assumed usage.

**Comment by jonataslaw** [comment]
I think I got it, your request is to allow assign and assignAll to work with null lists.
Yeah, that would make the API similar to the dart setter.
I think you're right about that.
I will implement this feature.

**Comment by jeiea** [comment]
As a side note, it may be desirable to make something new like `RxNullableList`, for future null safety.
I can't sure there is a way to check `Rx<T>` having `null`. If not, it is also necessary.

**Comment by jonataslaw** [comment]
> As a side note, it may be desirable to make something new like `RxNullableList`, for future null safety.
> I can't sure there is an existing api to check whether `RxNullableList<T>` has `null`. If not, it is also necessary.

The nullable behaviour will chance (probably) until release, so, maybe it will not be necessary. 
ValueNotifier (Flutter) depends on this, and we will follow the same way

**Comment by jonataslaw** [comment]
Fix on last version
