### ISSUE TITLE
An optional condition to check if the controller was initialized

### ISSUE THREAD

**Issue by drosa88** [jonataslaw/getx#793]
**Is your feature request related to a problem? Please describe.**

I currently have many problems in my app with the following state scenario:

For example I have a GetxController `UserController`. I need this controller in different Widgets, so I initialize it with `Get.put()` in the first widget and for the other child widgets I'll call it with `Get.find()`. That's great.

But: I have some widgets that sometimes load before the controller got initialized and sometimes after. So I get many `"
UsersController" not found.` errors. Maybe there exists some workaround for this problem? 

**Describe the solution you'd like**

I think that a condition would be useful to check if a controller already got initialized inside the app.. or something like a fallback. And it not, it should be initialize.

Example:

`UsersController usersController = Get.find(fallback: "Some fallback to init the controller if not found");`

or something like

```
if (usersController.wasNotInit) {
	usersController = Get.put(UsersController);
} else {
	..... Get.find()
}
```

If there already are solutions to solve this issue, I'm sorry for this thread. But in this case I would really appreciate your way to handle this.

Best regards

**Comment by jonataslaw** [comment]
You can use isRegistered to check dependencies already registered, and isPrepared if you are using lazyPut.

```dart
if(!Get.isRegistered<UsersController>()){
usersController = Get.put(UsersController);
}
```

If you don't already use Bindings, I recommend that you switch to a cleaner architecture, and this problem will certainly not occur.

Another way to avoid any problem like this is to initialize the dependencies like `Get.lazyPut(() => Controller(), fenix: true); `this way whenever a dependency is not registered, one will be created and delivered.

**Comment by drosa88** [comment]
Great. Thank you!!
