### ISSUE TITLE
Variables are not reliably reset

### ISSUE THREAD

**Issue by drosa88** [jonataslaw/getx#795]
**Is your feature request related to a problem? Please describe.**

Since a few weeks I'm dealing with a problem. To make it easier to understand, I will show you what it is all about:

In my app an user can post an entry to a guestbook. For this entry he can write simple text and in an additional step he can paint a picture. The user can switch back and forth between the steps. To save the current state of the painted image, I save the controller of this (`PaintingImageController()`) into a variable in a GetxController. That works well, if I set `permanent: true` to the `Get.put()`

After sending the entry, I want to reset the `PaintingImageController()` in the GetxController, because for the next entry it should be empty again. So I call something like `entriesController.currentPainting.value = PaintingImageController()`. If I call `print(currentPainting)` after this it shows me an empty `PaintingImageController()`. Great.  But: if I want to add a new entry, I get the old `PaintingImageController` data again. What's going wrong? :-) 

My current workaround for this is the following:

```
@override
  void initState() {
    if (widget.comesFromOutside == true) {
      if (Get.isRegistered<EntriesController>()) {
        Get.delete<EntriesController>(force: true).then((value) async {
          Get.put(EntriesController(), permanent: true)
          entriesController.checkGuestbookForUserEntries(
              guestbooksController.currentGuestbook.value.id);
        });
      }
    }
    _getUserID();
    super.initState();
  }
```

After sending the entry and going to the next page I delete the GetxController from memory and add it again. In this case it works in general without UI crashes or bugs. But I get a small `Controller not found` error.

**Describe the solution you'd like**

The possibility to force reset some variables in the controller would be great.

For example:

`entriesController.currentPainting.update(someNewData, {force: true})`

Would this be possible? Otherwise: Does exist a better solution for this inside getx which I don't found?

By the way: thanks again for your good work!

**Comment by jonataslaw** [comment]
Hi, technically it is impossible to programmatically reset a variable from controller.
Apparently, your problem is with the asynchronous of your project, you must be requesting the object before it has been deleted, and that is why you are returning to the old value.

**Comment by drosa88** [comment]
Thanks for your answer @jonataslaw.
I found another way to handle it. For this steps to create a new entry I´ve registered a new unique controller with a specific tag with `permanent: true`. After saving the entry I just delete the tagged controller with `force:true`. In addition I rewrote my entire app for using bindings. So the controller will automatically give me the right controller after I delete the tagged controller manually. It works well. I hope that this is a good way to work with getx.

Well. I think you can close this topic :)
