### ISSUE TITLE
Add simple http and socket support to Getx

### ISSUE THREAD

**Issue by jonataslaw** [jonataslaw/getx#797]
In 2020 it is practically impossible to create an application that does not have at least an api / sockets connection.
GetServer is an http and websocket server, which has many things ready and made easy, such as the creation of chat rooms, the possibility of sending personalized events and listening to them, and this requires some customization at the client level.
As much as the person uses another server as a backend, such as node.js, or go, they will need an http client, and eventually sockets for real-time communication.
It is possible today to add these packages, but some extra configuration may be necessary.
The purpose of this feature is to provide built-in, an easy http client and websocket, which allows the configuration of resources in a simple way, and which is extensible.
Sockets must have the ability to:

- Send messages,
- Receive messages,
- Send events eg socket.send (Event.join, 435)
- Receive events eg socket.on (Event.joined, (data) => print (data));
- Connect, disconnect, reconnect, intercept errors, ping.

The http client must be able to do operations:
- GET,
- POST (files via multipart, json and text)
- PUT (files via multipart, json and text)
- DELETE
- Intercept requests
- Intercept response
- Automatic reconnection in case of expired token
- Cache driver for easy connection with GetStorage.
With the creation of the client, you must create an isolate, so that the json coding occurs in the background, to prevent janks
- Response.data must return a dynamic or a Map, not a String, and ready for use, without the need to use jsonDecode (which will be done internally by an isolate).
Possibility to define the type of token, and directly pass a string function that retrieves it.
- Ability to define the base url.
- Run on android, ios, web, linux, mac and windows.
- Ability to enable and disable secure traffic.

Both solutions must be written in a few lines of code in order not to increase the size of the library, and be extremely lightweight for Flutter web. If this objective does not occur, this resource will be aborted.

**Comment by jonataslaw** [comment]
Implemented on 3.20

**Comment by leeyisoft** [comment]
Is there a fully functional demo of this feature, and where is the code？
