### ISSUE TITLE
Expected a value of type 'UserController', but got one of type 'UserController'

### ISSUE THREAD

**Issue by shariful2011** [jonataslaw/getx#798]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
After adding, deleting or updating a list that is connected to the current user which is stored in UserController I get an error "Expected a value of type 'UserController', but got one of type 'UserController' ". I am getting this error after updating to 3.16.0. 

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

``` 
final youtubeListByUser = <YoutubeLinksModel>[].obs;
final list = <YoutubeLinksModel>[].obs;

void getYoutubeLink(UserModel user) {
    youtubeListByUser.assignAll(
      list.where(
        (ele) => ele.uid == user?.id,
      ),
    );
  }

if (UserController.to.currentuser.value != null) {
      ever(UserController.to.currentuser, (UserModel user) {
        getYoutubeLink(user);
      });
      ever(list, (_) {
        getYoutubeLink(UserController.to.currentuser.value);
  });
}
```

**To Reproduce**
1. add, update or delte something from the list.
2. See error in console.

**Expected behavior**
This is not an error I am passing the same type of argument but got this error. 

**Screenshots**

**Flutter Version:**
[√] Flutter (Channel master, 1.24.0-8.0.pre.147, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.1)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.51.1)
[√] Connected device (4 available)

• No issues found!

**Getx Version:**
3.17.1

**Describe on which device you found the bug:**
Flutter for web on Chrome.

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by eduardoflorence** [comment]
@shariful2011, it is important to provide code that we can reproduce as in the example below. I was unable to reproduce the problem you mentioned in this issue. Modify the code below to look like yours and see if you can reproduce the problem.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  Get.put(UserController());
  Get.put(YoutubeController());
  runApp(GetMaterialApp(home: HomePage()));
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('HOME')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            RaisedButton(
              onPressed: () => Get.find<YoutubeController>().addList(),
              child: Text('ADD'),
            ),
            RaisedButton(
              onPressed: () => Get.find<UserController>().changeUser(),
              child: Text('Change User'),
            ),
          ],
        ),
      ),
    );
  }
}

class UserModel {
  int id;
  String name;
  UserModel({this.id, this.name});

  @override
  String toString() => 'UserModel(id: $id, name: $name)';
}

class UserController extends GetxController {
  Rx<UserModel> currentuser = UserModel().obs;

  static UserController get to => Get.find();

  void changeUser() {
    currentuser(UserModel(id: 2, name: 'Peter'));
  }

  @override
  void onInit() {
    currentuser(UserModel(id: 1, name: 'john'));
    super.onInit();
  }

}

class YoutubeLinksModel {
  int uid;
  String url;
  YoutubeLinksModel({this.uid, this.url});

  @override
  String toString() => 'YoutubeLinksModel(uid: $uid, url: $url)';
}

class YoutubeController extends GetxController {
  final youtubeListByUser = <YoutubeLinksModel>[].obs;
  final list = <YoutubeLinksModel>[].obs;

  void getYoutubeLink(UserModel user) {
    print(user);
    youtubeListByUser.assignAll(
      list.where(
        (ele) => ele.uid == user?.id,
      ),
    );
  }

  void addList() {
    list.add(YoutubeLinksModel(uid: 1, url: 'youtube.com/xxx'));
    list.add(YoutubeLinksModel(uid: 2, url: 'youtube.com/yyy'));
  }

  @override
  void onInit() {
    if (UserController.to.currentuser.value != null) {
      ever(UserController.to.currentuser, (UserModel user) {
        getYoutubeLink(user);
        print('ever1:$youtubeListByUser');
      });
      ever(list, (_) {
        getYoutubeLink(UserController.to.currentuser.value);
        print('ever2:$youtubeListByUser');
      });
    }
    super.onInit();
  }
}

```

**Comment by shariful2011** [comment]
I found out that this error ocurrs when there is a change in the list even if I don't update it from client or not connected to my UserController. I am using cloudfirestore streams to bindstreams in my RxList. Here is how I am binding streams `  todayList.bindStream(AdminDatabase().getLatestLinks());` Here is the AdminDatabase().getLatestLinks() stream.
```
 Stream<List<YoutubeLinksModel>> getLatestLinks() {
    return _firestore
        .collection('youtube_links')
        .where('dateCreated', isGreaterThanOrEqualTo: DateTime.now())
        .snapshots()
        .map((QuerySnapshot query) {
      List<YoutubeLinksModel> retVal = List();
      query.docs.forEach((element) async {
        retVal.add(
          YoutubeLinksModel.fromDocumentSnapshot(
            documentSnapshot: element,
          ),
        );
      });
      return retVal;
    });
  }
```

**Comment by shariful2011** [comment]
Here is the error that I am getting.
```
    at _ForwardingStreamSubscription.new.[_handleData] (http://localhost:55340/dart_sdk.js:33899:37)
    at _RootZone.runUnaryGuarded (http://localhost:55340/dart_sdk.js:35997:11)
    at _BroadcastSubscription.new.[_sendData] (http://localhost:55340/dart_sdk.js:29902:22)
    at _BroadcastSubscription.new.[_add] (http://localhost:55340/dart_sdk.js:29851:26)
    at _SyncBroadcastStreamController.new.[_sendData] (http://localhost:55340/dart_sdk.js:30547:34)
    at _SyncBroadcastStreamController.new.add (http://localhost:55340/dart_sdk.js:30346:24)
    at http://localhost:55340/packages/cloud_firestore_web/src/interop/utils/utils.dart.lib.js:469:22
    at Object._checkAndCall (http://localhost:55340/dart_sdk.js:4410:16)
    at Object.dcall (http://localhost:55340/dart_sdk.js:4415:17)
    at Array.ret (http://localhost:55340/dart_sdk.js:56523:21)
    at next (https://www.gstatic.com/firebasejs/8.0.0/firebase-firestore.js:1:271663)
    at https://www.gstatic.com/firebasejs/8.0.0/firebase-firestore.js:1:223088
```

**Comment by eduardoflorence** [comment]
There does not seem to be a bug related to Getx. Isolate the problem in your code by removing unnecessary parts and post it here so that we can only copy, paste and run or provide a repository.
In `getLatestLinks` make a mock, as we do not have access to your firestore (build retVal manually)

**Comment by shariful2011** [comment]
Hello sorry for late response I was a bit busy you said build retVal manually but I can't build it mannually as it returns a type of Stream<List<YoutubeLinksModel>> but if I build it mannually retVal becomes a List<YoutubeLinksModel>.

**Comment by shariful2011** [comment]
I am closing this issue as I figured out it is a problem of Flutter web, not GetX.

**Comment by mhbdev** [comment]
> I am closing this issue as I figured out it is a problem of Flutter web, not GetX.

Are you sure about that?
