### ISSUE TITLE
Persistent Bottom Bar

### ISSUE THREAD

**Issue by arcas0803** [jonataslaw/getx#799]
How to use get navigator to implement a persistent bottom bar to navigate through different pages with route manager properties (transitions, get back ...).

I'm trying to use a Navigator widget, but the key is in use.
```
return Scaffold(
        body: Navigator(
          key: Get.key,
          initialRoute: '/',
          onGenerateRoute: (RouteSettings settings) {
            WidgetBuilder builder;
            // Manage your route names here
            switch (settings.name) {
              case '/':
                builder = (BuildContext context) => IntervalView();
                break;
              case '/page1':
                builder = (BuildContext context) => SettingsView();
                break;
              case '/page2':
                builder = (BuildContext context) => MoreView();
                break;
              default:
                throw Exception('Invalid route: ${settings.name}');
            }
            // You can also return a PageRouteBuilder and
            // define custom transitions between pages
            return MaterialPageRoute(
              builder: builder,
              settings: settings,
            );
          },
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        floatingActionButton: CentralFab(),
        bottomNavigationBar: BottomNavBar());
  }
```

Flutter Version:
1.22

Getx Version : 3.15

**Comment by eduardoflorence** [comment]
Hi @arcas0803, see if this can help you:

https://github.com/jonataslaw/getx/issues/552#issuecomment-686158966

**Comment by arcas0803** [comment]
Thanks @eduardoflorence i'm working on it.
But the real problem with the example is that I can't use the properties of routes in GetX. Bindings, get back, middleware(i don't know if it works, I will discover).
What I was looking for is using the getx router system with the persistent bottom bar.

**Comment by eduardoflorence** [comment]
You can use bindings with `GetPageRoute`. See an example:

https://github.com/jonataslaw/getx/issues/298#issuecomment-650658609

If possible, add more parts of your code so that we can understand what you want and the steps to reproduce

**Comment by jonataslaw** [comment]
Navigator need a NestedKey. 
Never use Get.key tô nestedNavigator. 

key: nestedKey(1),

To navigator: Get.toNamed('/',id: 1)

Please read the docs and example to nestedNavigators

**Comment by arcas0803** [comment]
Ok, here is my come for the home view:
```
class HomeView extends GetView<HomeController> {
  final _navigatorKey = GlobalKey<NavigatorState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Navigator(
          key: _navigatorKey,
          initialRoute: Routes.WORKOUTS,
          onGenerateRoute: (RouteSettings settings) {
            WidgetBuilder builder;
            // Manage your route names here
            switch (settings.name) {
              case '/':
                return GetPageRoute(
                    settings: settings,
                    binding: WorkoutsBinding(),
                    page: () => WorkoutsView());
                break;
              case Routes.WORKOUTS:
                return GetPageRoute(
                    settings: settings,
                    binding: WorkoutsBinding(),
                    page: () => WorkoutsView());
                break;
              case Routes.INTERVAL:
                return GetPageRoute(
                    settings: settings,
                    binding: IntervalBinding(),
                    page: () => IntervalView());
                break;

              default:
                throw Exception('Invalid route: ${settings.name}');
            }
          },
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        floatingActionButton: CentralFab(),
        bottomNavigationBar: BottomNavBar());
  }
}
```
It's not working, maybe because I use a the wrong Key.
I'm using GetX Pattern so I have a:
-AppPages with all getPage
- App Routes with all my Routes

In GetMaterialApp:
```
GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: "Application",
      initialRoute: Routes.SPLASH,
      getPages: AppPages.routes,
      locale: localeOption(ui.window.locale),
      translations: Literals(),
      theme: appTheme,
    ),
```
The BottomBar just throw a Get.ToNamed().
I just don´t know if the new navigator in the HomeView will work as the navigator on the GetMaterialApp.

**Comment by arcas0803** [comment]
I'm going to use widgets for the pages inside the bottom bar and pages for the pages that don't need it.
You can close this.
Thanks.

**Comment by eduardoflorence** [comment]
@arcas0803, I am putting here a complete example of using `Navigator` with` bottomNavigationBar` to be useful for questions and other issues. In this example we have a main navigation and the bottomNavigationBar navigation:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(
    debugShowCheckedModeBanner: false,
    initialRoute: '/home',
    defaultTransition: Transition.fade,
    getPages: [
      GetPage(
        name: '/home',
        page: () => HomePage(),
        binding: HomeBinding(),
      ),
      GetPage(
        name: '/another',
        page: () => AnotherPage(),
      ),
    ],
  ));
}

class HomeBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => HomeController());
  }
}

class HomeController extends GetxController {
  static HomeController get to => Get.find();

  var currentIndex = 0.obs;

  final pages = <String>['/browse', '/history', '/settings'];

  void changePage(int index) {
    currentIndex.value = index;
    Get.toNamed(pages[index], id: 1);
  }

  Route onGenerateRoute(RouteSettings settings) {
    if (settings.name == '/browse')
      return GetPageRoute(
        settings: settings,
        page: () => BrowsePage(),
        binding: BrowseBinding(),
      );

    if (settings.name == '/history')
      return GetPageRoute(
        settings: settings,
        page: () => HistoryPage(),
        binding: HistoryBinding(),
      );

    if (settings.name == '/settings')
      return GetPageRoute(
        settings: settings,
        page: () => SettingsPage(),
        binding: SettingsBinding(),
      );

    return null;
  }
}

class HomePage extends GetView<HomeController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Navigator(
        key: Get.nestedKey(1),
        initialRoute: '/browse',
        onGenerateRoute: controller.onGenerateRoute,
      ),
      bottomNavigationBar: Obx(
        () => BottomNavigationBar(
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.search),
              label: 'Browse',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.history),
              label: 'History',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.settings),
              label: 'Settings',
            ),
          ],
          currentIndex: controller.currentIndex.value,
          selectedItemColor: Colors.pink,
          onTap: controller.changePage,
        ),
      ),
    );
  }
}

class BrowsePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Browse')),
      body: Center(
        child: Container(
          child: Text(Get.find<BrowseController>().title.value),
        ),
      ),
    );
  }
}

class HistoryPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('History')),
      body: Center(
        child: Container(
          child: Text(Get.find<HistoryController>().title.value),
        ),
      ),
    );
  }
}

class SettingsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Settings')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              child: Text(Get.find<SettingsController>().title.value),
            ),
            RaisedButton(
              child: Text('Another Page'),
              onPressed: () => Get.toNamed('/another'),
            ),
          ],
        ),
      ),
    );
  }
}

class BrowseController extends GetxController {
  final title = 'Browser'.obs;
}

class HistoryController extends GetxController {
  final title = 'History'.obs;
}

class SettingsController extends GetxController {
  final title = 'Settings'.obs;
}

class BrowseBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => BrowseController());
  }
}

class HistoryBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => HistoryController());
  }
}

class SettingsBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => SettingsController());
  }
}

class AnotherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('Another Page')), body: Container());
  }
}
```

**Comment by arcas0803** [comment]
@eduardoflorence  Thanks for the example. If you are gone put these example on the docs, try to implement the onBack method with:
```
Scaffold(
    body: WillPopScope(
      onWillPop: () async {
        if (_navigatorKey.currentState.canPop()) {
          _navigatorKey.currentState.pop();
          return false;
        }
        return true;
      },
      child: Navigator(
        // ...
      ),
    ),
```

**Comment by aligitshow** [comment]
> 
> 
> @arcas0803, I am putting here a complete example of using `Navigator` with `bottomNavigationBar` to be useful for questions and other issues. In this example we have a main navigation and the bottomNavigationBar navigation:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:get/get.dart';
> 
> void main() {
>   runApp(GetMaterialApp(
>     debugShowCheckedModeBanner: false,
>     initialRoute: '/home',
>     defaultTransition: Transition.fade,
>     getPages: [
>       GetPage(
>         name: '/home',
>         page: () => HomePage(),
>         binding: HomeBinding(),
>       ),
>       GetPage(
>         name: '/another',
>         page: () => AnotherPage(),
>       ),
>     ],
>   ));
> }...
> ```
@eduardoflorence Thanks for example.
Is it possible that `the back button` appears only in details pages (not in main pages)?
Thanks again

**Comment by eduardoflorence** [comment]
> @eduardoflorence Thanks for example.
> Is it possible that `the back button` appears only in details pages (not in main pages)?
> Thanks again

Hi @aligitshow, use `automaticallyImplyLeading` property of the Appbar. See an example:

```dart
class BrowsePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Browse'), automaticallyImplyLeading: false,),   // Here
      body: Center(
        child: Container(
          child: Text(Get.find<BrowseController>().title.value),
        ),
      ),
    );
  }
}
```

**Comment by aligitshow** [comment]
Thanks @eduardoflorence 
By using `automaticallyImplyLeading` property `back button` disappear but if you click `Browse` item in `bottom navbar` in the `Browse` page its navigate to the `Browse` page again!
 My goal is `bottom navbar` appears only in main pages like Home, About, Settings. ... and `back button` appears in detail pages with best and correct way of navigation in Getx.

**Comment by tuanbs** [comment]
> @arcas0803, I am putting here a complete example of using `Navigator` with `bottomNavigationBar` to be useful for questions and other issues. In this example we have a main navigation and the bottomNavigationBar navigation:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:get/get.dart';
> 
> void main() {
>   runApp(GetMaterialApp(
>     debugShowCheckedModeBanner: false,
>     initialRoute: '/home',
>     defaultTransition: Transition.fade,
>     getPages: [
>       GetPage(
>         name: '/home',
>         page: () => HomePage(),
>         binding: HomeBinding(),
>       ),
>       GetPage(
>         name: '/another',
>         page: () => AnotherPage(),
>       ),
>     ],
>   ));
> }
> 
> class HomeBinding extends Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut(() => HomeController());
>   }
> }
> 
> class HomeController extends GetxController {
>   static HomeController get to => Get.find();
> 
>   var currentIndex = 0.obs;
> 
>   final pages = <String>['/browse', '/history', '/settings'];
> 
>   void changePage(int index) {
>     currentIndex.value = index;
>     Get.toNamed(pages[index], id: 1);
>   }
> 
>   Route onGenerateRoute(RouteSettings settings) {
>     if (settings.name == '/browse')
>       return GetPageRoute(
>         settings: settings,
>         page: () => BrowsePage(),
>         binding: BrowseBinding(),
>       );
> 
>     if (settings.name == '/history')
>       return GetPageRoute(
>         settings: settings,
>         page: () => HistoryPage(),
>         binding: HistoryBinding(),
>       );
> 
>     if (settings.name == '/settings')
>       return GetPageRoute(
>         settings: settings,
>         page: () => SettingsPage(),
>         binding: SettingsBinding(),
>       );
> 
>     return null;
>   }
> }
> 
> class HomePage extends GetView<HomeController> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Navigator(
>         key: Get.nestedKey(1),
>         initialRoute: '/browse',
>         onGenerateRoute: controller.onGenerateRoute,
>       ),
>       bottomNavigationBar: Obx(
>         () => BottomNavigationBar(
>           items: const <BottomNavigationBarItem>[
>             BottomNavigationBarItem(
>               icon: Icon(Icons.search),
>               label: 'Browse',
>             ),
>             BottomNavigationBarItem(
>               icon: Icon(Icons.history),
>               label: 'History',
>             ),
>             BottomNavigationBarItem(
>               icon: Icon(Icons.settings),
>               label: 'Settings',
>             ),
>           ],
>           currentIndex: controller.currentIndex.value,
>           selectedItemColor: Colors.pink,
>           onTap: controller.changePage,
>         ),
>       ),
>     );
>   }
> }
> 
> class BrowsePage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text('Browse')),
>       body: Center(
>         child: Container(
>           child: Text(Get.find<BrowseController>().title.value),
>         ),
>       ),
>     );
>   }
> }
> 
> class HistoryPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text('History')),
>       body: Center(
>         child: Container(
>           child: Text(Get.find<HistoryController>().title.value),
>         ),
>       ),
>     );
>   }
> }
> 
> class SettingsPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text('Settings')),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: [
>             Container(
>               child: Text(Get.find<SettingsController>().title.value),
>             ),
>             RaisedButton(
>               child: Text('Another Page'),
>               onPressed: () => Get.toNamed('/another'),
>             ),
>           ],
>         ),
>       ),
>     );
>   }
> }
> 
> class BrowseController extends GetxController {
>   final title = 'Browser'.obs;
> }
> 
> class HistoryController extends GetxController {
>   final title = 'History'.obs;
> }
> 
> class SettingsController extends GetxController {
>   final title = 'Settings'.obs;
> }
> 
> class BrowseBinding extends Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut(() => BrowseController());
>   }
> }
> 
> class HistoryBinding extends Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut(() => HistoryController());
>   }
> }
> 
> class SettingsBinding extends Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut(() => SettingsController());
>   }
> }
> 
> class AnotherPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>         appBar: AppBar(title: Text('Another Page')), body: Container());
>   }
> }
> ```

If there's a list in the page, tapping the status bar to scroll to top (on iOS) doesn't work with this example. Any idea or workaround? Thanks in advance.

**Comment by hariantara** [comment]
I am able to handle this part by using this tricky part. The tricky part was in Second File (Home Screen Tab)

[https://imgflip.com/gif/6t8y6z](url)

### 1. Here is Bottom Nav Widget File ###
```
class MainHomeView extends GetView<MainHomeController> {
  MainHomeView({Key? key}) : super(key: key);

  final MainHomeController mainHomeController = Get.put(MainHomeController());

  @override
  Widget build(BuildContext context) {
    return GetBuilder<MainHomeController>(builder: (controller) {
      return Scaffold(
        body: SafeArea(
            child: Obx(
                () => IndexedStack(index: controller.tabIndex.value, children: [
                      Navigator(
                        key: Get.nestedKey(1),
                        initialRoute: Routes.HOME,
                        onGenerateRoute: ((settings) {
                          if (settings.name == Routes.HOME) {
                            return GetPageRoute(
                                settings: settings,
                                page: () => HomeView(),
                                binding: HomeBinding());
                          } else if (settings.name == Routes.CHOOSE_CAMP) {
                            return GetPageRoute(
                                settings: settings,
                                page: () => const ChooseCampView(),
                                binding: ChooseCampBinding());
                          } else {
                            return GetPageRoute(
                                settings: settings,
                                page: () => LoginView(),
                                binding: LoginBinding());
                          }
                        }),
                      ),
                      // HomeView(),
                      const DiscrepancyReportView(),
                    ]))),
        bottomNavigationBar:
            GetBuilder<MainHomeController>(builder: (controller) {
          return BottomNavigationBar(
            currentIndex: controller.tabIndex.value,
            backgroundColor: Colors.white,
            unselectedItemColor: Colors.black,
            selectedItemColor: Colors.redAccent,
            showSelectedLabels: false,
            showUnselectedLabels: false,
            onTap: (value) => controller.changeTabIndex(value),
            type: BottomNavigationBarType.fixed,
            items: [
              _bottomNavigationItems(icon: CupertinoIcons.home, label: 'Home'),
              _bottomNavigationItems(
                  icon: CupertinoIcons.person, label: 'Profile'),
            ],
          );
        }),
      );
    });
  }

  _bottomNavigationItems({required IconData icon, required String label}) {
    return BottomNavigationBarItem(
      icon: Icon(icon),
      label: label,
    );
  }
}
```

### 2.  Here is Home Tab Widget File (it has button that will navigate into nested part) ###
```
class HomeView extends GetView<HomeController> {
  HomeView({Key? key}) : super(key: key);

  final HomeController homeController = Get.put(HomeController());

  @override
  Widget build(BuildContext context) {
    return GetBuilder<HomeController>(builder: (controller) {
      return Scaffold(
          body: Container(
              color: Colors.red,
              width: double.infinity,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  const Text(
                    'HomeView is working',
                    style: TextStyle(fontSize: 20),
                  ),
                  GestureDetector(
                    onTap: () {
                      // Navigator.of(context)
                      //     .push(MaterialPageRoute(builder: (context) {
                      //   return const ChooseCampView();
                      // }));
                      Get.toNamed(Routes.CHOOSE_CAMP,
                          id: 1,
                          arguments:
                              'Test Argument'); // ------->>>>>> id is the tricky part to keep bottom nav stay when home tab navigate to another nested screen
                    },
                    child: const Text('Go To Another Stack Screen'),
                  )
                ],
              )));
    });
  }
}
```

**Comment by bb-renittojose** [comment]
> Navigator need a NestedKey. Never use Get.key tô nestedNavigator.
> 
> key: nestedKey(1),
> 
> To navigator: Get.toNamed('/',id: 1)
> 
> Please read the docs and example to nestedNavigators

Hi @jonataslaw this approach is working but the only problem is when we use Get.toNamed that route is getting added to the back stack, which is not the expected behaviour for the BottomNaviagation Bar.

**Comment by Sumit258000** [comment]
> @arcas0803, I am putting here a complete example of using `Navigator` with `bottomNavigationBar` to be useful for questions and other issues. In this example we have a main navigation and the bottomNavigationBar navigation:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:get/get.dart';
> 
> void main() {
>   runApp(GetMaterialApp(
>     debugShowCheckedModeBanner: false,
>     initialRoute: '/home',
>     defaultTransition: Transition.fade,
>     getPages: [
>       GetPage(
>         name: '/home',
>         page: () => HomePage(),
>         binding: HomeBinding(),
>       ),
>       GetPage(
>         name: '/another',
>         page: () => AnotherPage(),
>       ),
>     ],
>   ));
> }
> 
> class HomeBinding extends Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut(() => HomeController());
>   }
> }
> 
> class HomeController extends GetxController {
>   static HomeController get to => Get.find();
> 
>   var currentIndex = 0.obs;
> 
>   final pages = <String>['/browse', '/history', '/settings'];
> 
>   void changePage(int index) {
>     currentIndex.value = index;
>     Get.toNamed(pages[index], id: 1);
>   }
> 
>   Route onGenerateRoute(RouteSettings settings) {
>     if (settings.name == '/browse')
>       return GetPageRoute(
>         settings: settings,
>         page: () => BrowsePage(),
>         binding: BrowseBinding(),
>       );
> 
>     if (settings.name == '/history')
>       return GetPageRoute(
>         settings: settings,
>         page: () => HistoryPage(),
>         binding: HistoryBinding(),
>       );
> 
>     if (settings.name == '/settings')
>       return GetPageRoute(
>         settings: settings,
>         page: () => SettingsPage(),
>         binding: SettingsBinding(),
>       );
> 
>     return null;
>   }
> }
> 
> class HomePage extends GetView<HomeController> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Navigator(
>         key: Get.nestedKey(1),
>         initialRoute: '/browse',
>         onGenerateRoute: controller.onGenerateRoute,
>       ),
>       bottomNavigationBar: Obx(
>         () => BottomNavigationBar(
>           items: const <BottomNavigationBarItem>[
>             BottomNavigationBarItem(
>               icon: Icon(Icons.search),
>               label: 'Browse',
>             ),
>             BottomNavigationBarItem(
>               icon: Icon(Icons.history),
>               label: 'History',
>             ),
>             BottomNavigationBarItem(
>               icon: Icon(Icons.settings),
>               label: 'Settings',
>             ),
>           ],
>           currentIndex: controller.currentIndex.value,
>           selectedItemColor: Colors.pink,
>           onTap: controller.changePage,
>         ),
>       ),
>     );
>   }
> }
> 
> class BrowsePage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text('Browse')),
>       body: Center(
>         child: Container(
>           child: Text(Get.find<BrowseController>().title.value),
>         ),
>       ),
>     );
>   }
> }
> 
> class HistoryPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text('History')),
>       body: Center(
>         child: Container(
>           child: Text(Get.find<HistoryController>().title.value),
>         ),
>       ),
>     );
>   }
> }
> 
> class SettingsPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text('Settings')),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: [
>             Container(
>               child: Text(Get.find<SettingsController>().title.value),
>             ),
>             RaisedButton(
>               child: Text('Another Page'),
>               onPressed: () => Get.toNamed('/another'),
>             ),
>           ],
>         ),
>       ),
>     );
>   }
> }
> 
> class BrowseController extends GetxController {
>   final title = 'Browser'.obs;
> }
> 
> class HistoryController extends GetxController {
>   final title = 'History'.obs;
> }
> 
> class SettingsController extends GetxController {
>   final title = 'Settings'.obs;
> }
> 
> class BrowseBinding extends Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut(() => BrowseController());
>   }
> }
> 
> class HistoryBinding extends Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut(() => HistoryController());
>   }
> }
> 
> class SettingsBinding extends Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut(() => SettingsController());
>   }
> }
> 
> class AnotherPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>         appBar: AppBar(title: Text('Another Page')), body: Container());
>   }
> }
> ```

@eduardoflorence Thanks for help. I am using [Persistent bottom bar](https://pub.dev/packages/persistent_bottom_nav_bar_v2). Any suggestion or help how can I integrate this will using getX because this plugin itself have scaffold in his plugin. Please help how can I navigate inside pages while bottom bar is persistent. Thanks. @jonataslaw

**Comment by Sumit258000** [comment]
> I am able to handle this part by using this tricky part. The tricky part was in Second File (Home Screen Tab)
> 
> ![hippo](https://camo.githubusercontent.com/04e3b3ff72e91aaac5dc1320e9b0c0065fde0ab331a942bdd0ae1959d16ed644/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f675269416d676151757130433372396a4a522f67697068792e676966) [ ![hippo](https://camo.githubusercontent.com/04e3b3ff72e91aaac5dc1320e9b0c0065fde0ab331a942bdd0ae1959d16ed644/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f675269416d676151757130433372396a4a522f67697068792e676966) ](https://camo.githubusercontent.com/04e3b3ff72e91aaac5dc1320e9b0c0065fde0ab331a942bdd0ae1959d16ed644/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f675269416d676151757130433372396a4a522f67697068792e676966) [ ](https://camo.githubusercontent.com/04e3b3ff72e91aaac5dc1320e9b0c0065fde0ab331a942bdd0ae1959d16ed644/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f675269416d676151757130433372396a4a522f67697068792e676966)
> 
> ### 1. Here is Bottom Nav Widget File
> ```
> class MainHomeView extends GetView<MainHomeController> {
>   MainHomeView({Key? key}) : super(key: key);
> 
>   final MainHomeController mainHomeController = Get.put(MainHomeController());
> 
>   @override
>   Widget build(BuildContext context) {
>     return GetBuilder<MainHomeController>(builder: (controller) {
>       return Scaffold(
>         body: SafeArea(
>             child: Obx(
>                 () => IndexedStack(index: controller.tabIndex.value, children: [
>                       Navigator(
>                         key: Get.nestedKey(1),
>                         initialRoute: Routes.HOME,
>                         onGenerateRoute: ((settings) {
>                           if (settings.name == Routes.HOME) {
>                             return GetPageRoute(
>                                 settings: settings,
>                                 page: () => HomeView(),
>                                 binding: HomeBinding());
>                           } else if (settings.name == Routes.CHOOSE_CAMP) {
>                             return GetPageRoute(
>                                 settings: settings,
>                                 page: () => const ChooseCampView(),
>                                 binding: ChooseCampBinding());
>                           } else {
>                             return GetPageRoute(
>                                 settings: settings,
>                                 page: () => LoginView(),
>                                 binding: LoginBinding());
>                           }
>                         }),
>                       ),
>                       // HomeView(),
>                       const DiscrepancyReportView(),
>                     ]))),
>         bottomNavigationBar:
>             GetBuilder<MainHomeController>(builder: (controller) {
>           return BottomNavigationBar(
>             currentIndex: controller.tabIndex.value,
>             backgroundColor: Colors.white,
>             unselectedItemColor: Colors.black,
>             selectedItemColor: Colors.redAccent,
>             showSelectedLabels: false,
>             showUnselectedLabels: false,
>             onTap: (value) => controller.changeTabIndex(value),
>             type: BottomNavigationBarType.fixed,
>             items: [
>               _bottomNavigationItems(icon: CupertinoIcons.home, label: 'Home'),
>               _bottomNavigationItems(
>                   icon: CupertinoIcons.person, label: 'Profile'),
>             ],
>           );
>         }),
>       );
>     });
>   }
> 
>   _bottomNavigationItems({required IconData icon, required String label}) {
>     return BottomNavigationBarItem(
>       icon: Icon(icon),
>       label: label,
>     );
>   }
> }
> ```
> 
> ### 2. Here is Home Tab Widget File (it has button that will navigate into nested part)
> ```
> class HomeView extends GetView<HomeController> {
>   HomeView({Key? key}) : super(key: key);
> 
>   final HomeController homeController = Get.put(HomeController());
> 
>   @override
>   Widget build(BuildContext context) {
>     return GetBuilder<HomeController>(builder: (controller) {
>       return Scaffold(
>           body: Container(
>               color: Colors.red,
>               width: double.infinity,
>               child: Column(
>                 mainAxisAlignment: MainAxisAlignment.center,
>                 crossAxisAlignment: CrossAxisAlignment.center,
>                 children: [
>                   const Text(
>                     'HomeView is working',
>                     style: TextStyle(fontSize: 20),
>                   ),
>                   GestureDetector(
>                     onTap: () {
>                       // Navigator.of(context)
>                       //     .push(MaterialPageRoute(builder: (context) {
>                       //   return const ChooseCampView();
>                       // }));
>                       Get.toNamed(Routes.CHOOSE_CAMP,
>                           id: 1,
>                           arguments:
>                               'Test Argument'); // ------->>>>>> id is the tricky part to keep bottom nav stay when home tab navigate to another nested screen
>                     },
>                     child: const Text('Go To Another Stack Screen'),
>                   )
>                 ],
>               )));
>     });
>   }
> }
> ```

With this it does not navigating to next page. @hariantara @jonataslaw . Is there any perfect example of persistant bottom nav bar that should appear all across the app.

**Comment by heshesh2010** [comment]
> > @arcas0803, I am putting here a complete example of using `Navigator` with `bottomNavigationBar` to be useful for questions and other issues. In this example we have a main navigation and the bottomNavigationBar navigation:
> > ```dart
> > import 'package:flutter/material.dart';
> > import 'package:get/get.dart';
> > 
> > void main() {
> >   runApp(GetMaterialApp(
> >     debugShowCheckedModeBanner: false,
> >     initialRoute: '/home',
> >     defaultTransition: Transition.fade,
> >     getPages: [
> >       GetPage(
> >         name: '/home',
> >         page: () => HomePage(),
> >         binding: HomeBinding(),
> >       ),
> >       GetPage(
> >         name: '/another',
> >         page: () => AnotherPage(),
> >       ),
> >     ],
> >   ));
> > }
> > 
> > class HomeBinding extends Bindings {
> >   @override
> >   void dependencies() {
> >     Get.lazyPut(() => HomeController());
> >   }
> > }
> > 
> > class HomeController extends GetxController {
> >   static HomeController get to => Get.find();
> > 
> >   var currentIndex = 0.obs;
> > 
> >   final pages = <String>['/browse', '/history', '/settings'];
> > 
> >   void changePage(int index) {
> >     currentIndex.value = index;
> >     Get.toNamed(pages[index], id: 1);
> >   }
> > 
> >   Route onGenerateRoute(RouteSettings settings) {
> >     if (settings.name == '/browse')
> >       return GetPageRoute(
> >         settings: settings,
> >         page: () => BrowsePage(),
> >         binding: BrowseBinding(),
> >       );
> > 
> >     if (settings.name == '/history')
> >       return GetPageRoute(
> >         settings: settings,
> >         page: () => HistoryPage(),
> >         binding: HistoryBinding(),
> >       );
> > 
> >     if (settings.name == '/settings')
> >       return GetPageRoute(
> >         settings: settings,
> >         page: () => SettingsPage(),
> >         binding: SettingsBinding(),
> >       );
> > 
> >     return null;
> >   }
> > }
> > 
> > class HomePage extends GetView<HomeController> {
> >   @override
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> >       body: Navigator(
> >         key: Get.nestedKey(1),
> >         initialRoute: '/browse',
> >         onGenerateRoute: controller.onGenerateRoute,
> >       ),
> >       bottomNavigationBar: Obx(
> >         () => BottomNavigationBar(
> >           items: const <BottomNavigationBarItem>[
> >             BottomNavigationBarItem(
> >               icon: Icon(Icons.search),
> >               label: 'Browse',
> >             ),
> >             BottomNavigationBarItem(
> >               icon: Icon(Icons.history),
> >               label: 'History',
> >             ),
> >             BottomNavigationBarItem(
> >               icon: Icon(Icons.settings),
> >               label: 'Settings',
> >             ),
> >           ],
> >           currentIndex: controller.currentIndex.value,
> >           selectedItemColor: Colors.pink,
> >           onTap: controller.changePage,
> >         ),
> >       ),
> >     );
> >   }
> > }
> > 
> > class BrowsePage extends StatelessWidget {
> >   @override
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> >       appBar: AppBar(title: Text('Browse')),
> >       body: Center(
> >         child: Container(
> >           child: Text(Get.find<BrowseController>().title.value),
> >         ),
> >       ),
> >     );
> >   }
> > }
> > 
> > class HistoryPage extends StatelessWidget {
> >   @override
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> >       appBar: AppBar(title: Text('History')),
> >       body: Center(
> >         child: Container(
> >           child: Text(Get.find<HistoryController>().title.value),
> >         ),
> >       ),
> >     );
> >   }
> > }
> > 
> > class SettingsPage extends StatelessWidget {
> >   @override
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> >       appBar: AppBar(title: Text('Settings')),
> >       body: Center(
> >         child: Column(
> >           mainAxisAlignment: MainAxisAlignment.center,
> >           children: [
> >             Container(
> >               child: Text(Get.find<SettingsController>().title.value),
> >             ),
> >             RaisedButton(
> >               child: Text('Another Page'),
> >               onPressed: () => Get.toNamed('/another'),
> >             ),
> >           ],
> >         ),
> >       ),
> >     );
> >   }
> > }
> > 
> > class BrowseController extends GetxController {
> >   final title = 'Browser'.obs;
> > }
> > 
> > class HistoryController extends GetxController {
> >   final title = 'History'.obs;
> > }
> > 
> > class SettingsController extends GetxController {
> >   final title = 'Settings'.obs;
> > }
> > 
> > class BrowseBinding extends Bindings {
> >   @override
> >   void dependencies() {
> >     Get.lazyPut(() => BrowseController());
> >   }
> > }
> > 
> > class HistoryBinding extends Bindings {
> >   @override
> >   void dependencies() {
> >     Get.lazyPut(() => HistoryController());
> >   }
> > }
> > 
> > class SettingsBinding extends Bindings {
> >   @override
> >   void dependencies() {
> >     Get.lazyPut(() => SettingsController());
> >   }
> > }
> > 
> > class AnotherPage extends StatelessWidget {
> >   @override
> >   Widget build(BuildContext context) {
> >     return Scaffold(
> >         appBar: AppBar(title: Text('Another Page')), body: Container());
> >   }
> > }
> > ```
> 
> @eduardoflorence Thanks for help. I am using [Persistent bottom bar](https://pub.dev/packages/persistent_bottom_nav_bar_v2). Any suggestion or help how can I integrate this will using getX because this plugin itself have scaffold in his plugin. Please help how can I navigate inside pages while bottom bar is persistent. Thanks. @jonataslaw

+1
