### ISSUE TITLE
Wrong read system locale getter

### ISSUE THREAD

**Issue by luis-cruzt** [jonataslaw/getx#800]
**Describe the bug**
The documentation says:
`To read the system locale, you could use Get.deviceLocale`

But the only way to read the system locale is with:

`locale: Get.locale,`

**Reproduction code
Go to system locale section of [the documentation.](https://pub.dev/packages/get#system-locale)

**To Reproduce**
1. Go to system locale section of [the documentation.](https://pub.dev/packages/get#system-locale)
2. See error

**Expected behavior**
`Get.deviceLocale` should work.

**Flutter Version:**
1.22.4

**Getx Version:**
3.15.0

**Describe on which device you found the bug:**
Android and iOS

**Minimal reproduce code**
Not applies.

**Comment by eduardoflorence** [comment]
Hi @luis-cruzt, `Get.deviceLocale` was released in version 3.16.2 of GetX and you are using version 3.15.0
