### ISSUE TITLE
Hello. What is it?

### ISSUE THREAD

**Issue by Hopheylalal** [jonataslaw/getx#802]
The following assertion was thrown building FutureBuilder<DocumentSnapshot>(dirty, state: _FutureBuilderState<DocumentSnapshot>#a9c6c):
setState() or markNeedsBuild() called during build.

This GetBuilder<DataController> widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: GetBuilder<DataController>
  state: _GetBuilderState<DataController>#ce1fc
The widget which was currently being built when the offending call was made was: FutureBuilder<DocumentSnapshot>
  dirty
  state: _FutureBuilderState<DocumentSnapshot>#a9c6c
The relevant error-causing widget was: 
  FutureBuilder<DocumentSnapshot> file:///Users/alexander/AndroidStudioProjects/migrant_app/lib/chat/chat_room.dart:95:22
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4318:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4333:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1289:15)
#3      GetStateUpdaterMixin.getUpdate (package:get/get_state_manager/src/simple/get_state.dart:22:18)
#4      ListNotifier.refresh (package:get/get_state_manager/src/simple/list_notifier.dart:22:14)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
A RenderFlex overflowed by 99650 pixels on the right.
The relevant error-causing widget was: 
  AppBar file:///Users/alexander/AndroidStudioProjects/migrant_app/lib/chat/chat_room.dart:73:15
════════════════════════════════════════════════════════════════════════════════════════════════════
[GETX] GOING TO ROUTE /ProfileCommon
I/flutter (12712): null

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building FutureBuilder<DocumentSnapshot>(dirty, state: _FutureBuilderState<DocumentSnapshot>#6dce6):
setState() or markNeedsBuild() called during build.

This GetBuilder<DataController> widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: GetBuilder<DataController>
  state: _GetBuilderState<DataController>#ce1fc
The widget which was currently being built when the offending call was made was: FutureBuilder<DocumentSnapshot>
  dirty
  state: _FutureBuilderState<DocumentSnapshot>#6dce6
The relevant error-causing widget was: 
  FutureBuilder<DocumentSnapshot> file:///Users/alexander/AndroidStudioProjects/migrant_app/lib/common_profile/profile_user_widget_common.dart:40:12
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4318:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4333:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1289:15)
#3      GetStateUpdaterMixin.getUpdate (package:get/get_state_manager/src/simple/get_state.dart:22:18)
#4      ListNotifier.refresh (package:get/get_state_manager/src/simple/list_notifier.dart:22:14)
...

**Comment by jonataslaw** [comment]
It means that you are calling the build method before it is completed.
This only occurs if you perform things that are considered bad practices, such as logic within the build method.
Builder methods must be pure, you must not call functions or perform setters from it.
This is not related to Getx, besides being a question, something that is not allowed in this space, therefore, I am closing this.
