### ISSUE TITLE
Improper use of Getx detected

### ISSUE THREAD

**Issue by guiiamorim** [jonataslaw/getx#808]
Hi, I'm having a strange issue with GetX on an application that I'm developing. I'm using a controller to keep track of the internet connection of the device, everything works fine, but in one button I'm trying to change the behavior of the `onPressed` function based on that status, but it gives me the error of `improper use of a GetX has been detected`. But if I do a hot reload the error disappears and the button shows just fine and the behavior of the function gets changed. If I restart the application the error comes back and goes away with another hot reload. Bellow is a piece of my code:

`Container(
                  height: 80.0,
                  child: Padding(
                    padding: EdgeInsets.all(8.0),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [
                        GetX<ConnectionController>(
                          builder: (conn) => RaisedButton(
                            onPressed: () async {
                              if (conn.connectionStatus.value ==
                                  DataConnectionStatus.connected) {
                                SnackBar snack = await c.save();
                                Scaffold.of(context).showSnackBar(snack);
                              } else {
                                SnackBar msg = SnackBar(
                                  content: conn.disconnectedSnack.content,
                                  duration: Duration(seconds: 10),
                                  action: SnackBarAction(
                                    label: 'Salvar Offline',
                                    onPressed: () async {
                                      SnackBar snack = await c.save(offline: true);
                                      Scaffold.of(context).showSnackBar(snack);
                                    },
                                  ),
                                );
                                Scaffold.of(context).showSnackBar(msg);
                              }
                            },
                            child: Text(
                              'Salvar',
                              style: TextStyle(color: Colors.white),
                            ),
                            color: Color(0xFF00b3c9),
                          ),
                        ),
                        FlatButton(
                          child: Text('Cancelar'),
                          onPressed: () {},
                        ),
                      ],
                    ),
                  ),
                )`

Note that this variable `c` is another controller that I have instantiated in the widget, I don't know if that can cause trouble, I've searched other similar questions and even some issues here on GitHub, but couldn't figure it out. Sorry if this isn't the best place to look for help but as I'm not sure if it's a bug I'm opening this issue.

**Comment by eduardoflorence** [comment]
There is no need to use a GetX in the View, as it will not be changed if the observable is changed. In `onPressed`, before `if`, do this:
```dart
final ConnectionController conn = Get.find<ConnectionController>();
```

**Comment by guiiamorim** [comment]
Oh I see, it worked like a charm! I didn't get that it's only meant to be used when something on the view is changed. Anyways, thank you very much for the response, congrats for the awesome package.
