### ISSUE TITLE
GetPage page function won't work if returned null

### ISSUE THREAD

**Issue by min-wai** [jonataslaw/getx#811]
Current GetPage implementation always expects a widget to be returned. It's usually fine when you have to condition-check based on, say, box value and return whether Home or Login widget like in the documentation.
But what if we like to return a certain widget or null when conditions are not met? Like for example, I create an online course app and my app has course lessons shown on Home page, but I want to allow going to a specific lesson only if conditions have been met.

**Comment by eduardoflorence** [comment]
See if this example can help you:

https://github.com/jonataslaw/getx/issues/391#issuecomment-684598230

**Comment by min-wai** [comment]
Yes! This is awesome. Thanks!
