### ISSUE TITLE
GetxControllers don't get disposed after upgrading to V3.20.0

### ISSUE THREAD

**Issue by ahmednfwela** [jonataslaw/getx#831]
**Describe the bug**
SmartManagement doesn't dispose the GetxControllers like it used to before `V3.20.0`

**Reproduction code**
any simple project created by get_cli with 2+ routes and navigation
e.g.
https://github.com/jonataslaw/getx/tree/master/example

**To Reproduce**
1. Navigate from route A to route B
2. Call Get.back on route B

**Expected behavior**
Controller should get disposed

**Flutter Version:**
1.22.4

**Getx Version:**
3.20.0

**Comment by eduardoflorence** [comment]
The problem is really happening in version 3.20.0 and it doesn't happen with version 3.17.1.
I believe it is related to `GetView`. In the code below the problem happens, but if we replace `GetView<LoginController>` with `StatelessWidget` the problem does not happen:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(
    initialRoute: '/home',
    getPages: [
      GetPage(
        name: '/home',
        page: () => HomePage(),
      ),
      GetPage(
        name: '/login',
        page: () => LoginPage(),
        binding: LoginBinding(),
      ),
    ],
  ));
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('HOME')),
      body: Center(
        child: RaisedButton(
          onPressed: () => Get.toNamed('/login'),
          child: Text('Login'),
        ),
      ),
    );
  }
}

class LoginBinding extends Bindings {
  @override
  void dependencies() {
    Get.put(LoginController());
  }
}

class LoginController extends GetxController {
}

class LoginPage extends GetView<LoginController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Login')),
      body: Container(),
    );
  }
}
```

**Comment by jonataslaw** [comment]
I just fixed it on lastest release, and added tests to this feature so that this problem never occurs again in the future.
