### ISSUE TITLE
waiting for the data from the next route is not working when we pass arguments

### ISSUE THREAD

**Issue by mohanhari** [jonataslaw/getx#834]
To navigate to the next route, and receive or update data as soon as you return from it is not working if we give an argument or parameter. is this an expected behaviour?. If use the below code the 'data' variable is taking the argument or parameter value (i.e) in the below code its taking 'test' as the value. if we don't pass arguments or parameter it's working fine.

**Reproduction code
var data = await Get.toNamed('/next_page/test')
or
var data = await Get.toNamed('/next_page', arguments:'test)
or 
var data = await Get.toNamed("/next_page?name=test")

**Expected behavior**
It should not take the argument or parameter value instead it should wait for the data until the next route is closed

**Flutter Version:**
Flutter version 1.22.4

**Getx Version:**
get: 3.17.1

**Comment by eduardoflorence** [comment]
Hi @mohanhari, I did a test and what you say is not happening. Please provide a code so that we can reproduce your problem (imports, controllers e views).

**Comment by jonataslaw** [comment]
Without a problem reproduction code, it will not be possible to proceed with this issue. Closing it.
