### ISSUE TITLE
Get.to(.., popgesture: true) make hang in Android

### ISSUE THREAD

**Issue by wonpyohong** [jonataslaw/getx#835]
**Describe the bug**
movie: https://youtu.be/XKu27VtS_AY

Get.to(.., popgesture: true) make hang in Android

iOS: good
Android (Galaxy S9, Galaxy S10)
  - back button -> good
  - left to right gesture to pop screen -> hang. I cannot touch anything. only back button is working. However after back button, i cannot touch anything again in first screen.

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

Future<void> main() async {
  runApp(
    GetMaterialApp(
      home: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          child: Text("Go to Other"),
          onPressed: () => Get.to(Other(), popGesture: true) 
        )
      )
    );
  }
}

class Other extends StatelessWidget {
  @override
  Widget build(context){
    return Scaffold(body: Center(child: Text('other')));
  }
}
```

**To Reproduce**
1. Execute code
2. left to right gesture to pop screen like iPhone (in Android Phone)

**Expected behavior**

**Screenshots**
movie: https://youtu.be/XKu27VtS_AY

**Flutter Version:**
1.22.4

**Getx Version:**
3.21.1

**Describe on which device you found the bug:**
Android Galaxy S9, Android Galaxy S10

**Minimal reproduce code**
I already written above

**Comment by eduardoflorence** [comment]
Hi @wonpyohong,
Replace this:
```dart
onPressed: () => Get.to(Other(), popGesture: true) 
```
With:
```dart
onPressed: () => Get.to(Other(), popGesture: true, transition: Transition.cupertino) 
```

**Comment by wonpyohong** [comment]
@eduardoflorence thanks!!!! it works
