### ISSUE TITLE
[GetConnect] FormData always exception with "FormData need a Map"

### ISSUE THREAD

**Issue by jasonlaw** [jonataslaw/getx#838]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
When transforming a map into FormData, it always throw an exception "FormData need a Map".

**Reproduction code
Just pass a map into FormData, the error will be thrown.
example:

```dart
final Map<String, dynamic> data = {};
data["somefield"] = "some value";

final formData = FormData( data );
```

Please notes that even with/without the MultipartFile entry, it is always throw the error.

**Expected behavior**
The FormData should except the map.

**Screenshots**
As you may see in the screen shot below, I have the proper map but it still throw error.
![image](https://user-images.githubusercontent.com/107820/100678146-775bec00-33a7-11eb-81ec-8a779ce0d543.png)

The error is in UrlEncode function.
![image](https://user-images.githubusercontent.com/107820/100678287-c9047680-33a7-11eb-8087-07f11bd5bc93.png)

**Flutter Version:**
1.22.4

**Getx Version:**
3.21.2

**Describe on which device you found the bug:**
ex: Emulator - Android.

**Comment by jonataslaw** [comment]
Fix on last update
