### ISSUE TITLE
[GetConnect] request doesnt return text/plain 

### ISSUE THREAD

**Issue by xyzbilal** [jonataslaw/getx#844]
Hi,
I am trying to receive get request response as plain because I am saving some response as plain text in Hive but my request always returns List<dynamic> (because my backend sends it list). 
I tried to save response body as it is to hive. but at this time I am getting the error of 
`InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>` while decoding from hive. 
I was using dio package and it has option that I can indicate response type but now I want to simplfy because I already use Get in my project and want to remove dio package. 

What I tried to solve the issue is first;
- I set `this.defaultContentType ="text/plain";` it didnt work,
- I set header  
` final headers = {
      "Content-Type": "text/plain",
      "Authorization": "Bearer $token",
      "Accept": "text/plain"
    };`
it didnt work,
then I defined contentType:'text/plain' in method and again it didnt work. my code chunk is below. what should I do. 

```
 await get(url,headers: headers,contentType: 'text/plain').then((value) {
                response = value;
                print(response.body.runtimeType);
              }).catchError((e) {
                error = e;
              });
```
everything works fine with json but plain text. here is my whole function. 
```

 Future<Response> requests(Method method,String suffix, {
    Map<String, dynamic> params,
    ResType resType,
    bool isPublic,
    bool isMerkez,
    String filePath,
    Function(dynamic, dynamic) onReceiveProgress,
    Function function,
  }) async {
  
    final api = isPublic != null && isPublic ? '' : '/api/';
    final url =
        isMerkez != null && isMerkez ? suffix : institute.url + api + suffix;

    final token = institute.token;

    Response response;
    var error;
   
    String accept =
        resType == ResType.plain ? "text/plain" : "application/json";

    this.defaultContentType = accept;

    final headers = {
      "Content-Type": accept,
      "Authorization": "Bearer $token",
      "Accept": accept
    };

    switch (method) {
      case Method.GET:
        await get(url, headers: headers, contentType: 'text/plain')
            .then((value) {
          response = value;
          print(response.body.runtimeType);
        }).catchError((e) {
          error = e;
        });
        break;
      case Method.PUT:
        await put(url, params, headers: headers).then((value) {
          response = value;
        }).catchError((e) {
          error = e;
        });
        break;
      case Method.POST:
        await post(url, params, headers: headers).then((value) {
          response = value;
        }).catchError((e) {
          error = e;
        });
        break;
      case Method.DELETE:
        await delete(url, headers: headers, query: params).then((value) {
          response = value;
        }).catchError((e) {
          error = e;
        });
        break;
      case Method.DOWNLOAD:
        get(
          url,
          headers: headers,
        ).then((response) async {
          await getApplicationDocumentsDirectory().then((path) async {
            File file = new File('$path/file');

            response.bodyBytes.listen((value) {
              file.writeAsBytesSync(value);
            });
          });
        });

        break;
      default:
        break;
    }

    return response;
  }


```

additionaly adding download method to package like dio would be great for Getx. thanks for everything.

**Comment by eduardoflorence** [comment]
Hi @xyzbilal, update GetX to version 3.21.3, it resolves this issue.

**Comment by jonataslaw** [comment]
Just a side note, as I understand it, you are trying to set the contentType of the response in the request. contentType from reader is the type you are sending the request to, not the one you will receive.
As for your issue, I assume that you are using the previous version that was trying to turn anything into json before returning it in the reply. I believe that in the current version you should receive a String in this case.
Anyway, I am wondering if it would not be better to convert to json only if the contentType returned by the server is: "application/json". It seems like this makes sense, but we will be delegating the backend the ability to define what we are going to receive.
Perhaps this option + the ability to be able to change this contentType on the front may be ideal.

**Comment by xyzbilal** [comment]
> Hi @xyzbilal, update GetX to version 3.21.3, it resolves this issue.

thank you for your response but I already use latest version. I had not tried to save with json encoding of response.body. I 
tried it and solved  my problem. 

```
Future<void> getDepartments() async {
    if (!box.containsKey(BoxKeys.departments)||box.get(BoxKeys.departments)==null) {
       Response response = await Network().requests(Method.GET, Links.departments);

        if (response.statusCode == 200) {
          departments = departmentsFromJson(response.body);
          box.put(BoxKeys.departments, jsonEncode(response.body));
        }

    } else {
      departments = departmentsFromJson(box.get(BoxKeys.departments));
    
    }
  
  }
```
but it would be great if I can choose response type as string or json. 
thanks again

**Comment by saschaernst** [comment]
I was able to fix it by removing the Exception type from the catch clause.

Instead of
```dart
try {
    if (request.decoder == null) {
      body = bodyToDecode as T;
    } else {
      body = request.decoder(bodyToDecode);
    }
  } on Exception catch (_) {
    body = stringBody as T;
  }
```

I changed it to
```dart
try {
    if (request.decoder == null) {
      body = bodyToDecode as T;
    } else {
      body = request.decoder(bodyToDecode);
    }
  } catch (_) {
    body = stringBody as T;
  }
```

Now I can load a String like this:
```dart
final response = await GetConnect().get<String>(somePath);
```

Could that be a viable solution to just load strings or am I missing something?

**Comment by jonataslaw** [comment]
In the last version, if the server sends content with contentType other than application / json, a string will be returned, not a json. That way, I think this can already be closed
