### ISSUE TITLE
Parent widget is not getting an updated value of controller, but child widget does

### ISSUE THREAD

**Issue by yulkin2002** [jonataslaw/getx#845]
I have 2 screens in my app that leverage the same controller.
Screen 2 (MyTalentDetail) updates the controller value and Screen 1 (MyTalentProfileScreen  - which consists of a parent and child widgets ) receives the updated value;
The issue is that the child widget on Screen 1 receives the updated value inside Obx, but for some reason the Parent does not. It seems to have something to do with the scaffold, as the child is simply a view and the parent contains scaffold.

STEPS to Reproduce:
user navigates to MyTalentDetail screen, edits data, and clicks on the save button which triggers _myTalentController.talentDataChanged.value to be set to true. User is taken back to MyTalentProfileScreen . where the child widget(MyTalentScreenBody) has the updated value of talentDataChanged, but the parent does not

Expected behaviour is that both parent and child widgets on screen 1 receive the updated talentDataChanged value

Code:
```
class MyTalentProfileScreen extends StatelessWidget {

  final MyTalentsController talentController = Get.put(MyTalentsController());

  final LanguagesController langCtrlr = Get.put(LanguagesController());
  final ContactInfoController contactCtrlr = Get.put(ContactInfoController());

  @override
  Widget build(BuildContext context) {
 
    return Scaffold(
        appBar: AppBar(
          automaticallyImplyLeading: false,
          backgroundColor: kAppBGColour,
          title: Center(
            child: Text(
              'My Talent Profile',
              style: kGreyTextStyle18,
            ),
          ),
        ),
        body: SingleChildScrollView(
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: 10.0),
            child: Column(
              children: [
                MyTalentScreenBody(),
              ],
            ),
          ),
        ),
        bottomNavigationBar:
     
            Obx(() {
          print('MyTalentProfileScreen Obx talentController.talentDataChanged.value: ${talentController.talentDataChanged.value}');
          return talentController.showSpinner.value
              ? CircularProgressIndicator()
              : SaveCancelNavBar( ... );
        })
        
        );
  }
}

class MyTalentScreenBody extends StatelessWidget {
  final MyTalentsController controller = Get.find<MyTalentsController>();
  final LanguagesController langCtrlr = Get.put(LanguagesController());
  final ContactInfoController contactCtrlr = Get.put(ContactInfoController());

  final StoredUserData storedUserData = StoredUserData();

  List<Widget> getCategoryTiles() {... }

  List<Widget> getTalentTiles(String selectedCategory) {...}

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context).copyWith(dividerColor: Colors.white);
    return Obx(() {
      print('MyTalentProfileBody Obx talentController.talentDataChanged.value: ${controller.talentDataChanged.value}');
      return controller.showSpinner.value
          ? CircularProgressIndicator()
          : Column(...);
    });
  }
}

class MyTalentDetail extends StatelessWidget {
  final MyTalentsController _myTalentController = Get.put(MyTalentsController());

  final _formKey = GlobalKey<FormState>();

  final FocusNode summaryFocusNode = FocusNode();



  @override
  Widget build(BuildContext context) {

    return Scaffold(
        appBar: AppBar(
          automaticallyImplyLeading: false,
          backgroundColor: kAppBGColour,
          title: Center(
            child: Text(
              _myTalentController.talentName.value,
              style: kDarkPurple1TextStyle18,
            ),
          ),
        ),
        body:
            SingleChildScrollView(...),
        bottomNavigationBar:
          AddDeleteCancelNavBar(
          saveButtonText: 'Add Talent',
          onPressedSave: () {

            if (this._formKey.currentState.validate()) {
              _myTalentController.talentDataChanged.value = true;

              Get.back();
            }
          },
          onPressedDelete: () {
            _myTalentController.talent.value = Talent(offerings: []);
            _myTalentController.talentSummaryController.value.clear();
            _myTalentController.offeringFieldsController.value.clear();
            _myTalentController.rateFieldsController.value.clear();
            _myTalentController.offeringDescriptionController.value.clear();
            _myTalentController.talentDataChanged.value = true;

          
            _myTalentController.talent.value = Talent(offerings: []);
            Get.back();

         
          },
        )
     
        );
  }
}

class MyTalentsController extends GetxController {
...
 var talentDataChanged = false.obs;
...
}
```

I am on Getx 3.16.2
Flutter 1.22.4 • channel stable 
Dart 2.10.4

**Comment by jonataslaw** [comment]
Why are you using Put from the same controller in two locations?

```dart
class MyTalentProfileScreen extends StatelessWidget {
  final MyTalentsController talentController = Get.put(MyTalentsController());
```
```dart
class MyTalentDetail extends StatelessWidget {
  final MyTalentsController _myTalentController = Get.put(MyTalentsController());
```

**Comment by yulkin2002** [comment]
is that a problem?

**Comment by eduardoflorence** [comment]
The correct location for Get.put is within the build method. For example:

```dart
class MyTalentProfileScreen extends StatelessWidget {
  // Not here
  @override
  Widget build(BuildContext context) {
    final MyTalentsController talentController = Get.put(MyTalentsController());

    final LanguagesController langCtrlr = Get.put(LanguagesController());
    final ContactInfoController contactCtrlr = Get.put(ContactInfoController());
 
    return Scaffold(...
```

**Comment by yulkin2002** [comment]
ah, thank you! that solved the issue! to confirm is it still a problem using Get.put for the same controller in two locations within build method?

**Comment by jonataslaw** [comment]
Yep, you had 2 different controllers. 

-----------------------------------------------------------
It may be necessary to include in the docs that controllers need to be declared:

in the build method 
or class scope by getters

Unless named routes are being used.

It will prevent 100% errors like it

**Comment by yulkin2002** [comment]
> 
> 
> Yep, you had 2 different controllers.
> 
> It may be necessary to include in the docs that controllers need to be declared:
> 
> in the build method
> or class scope by getters
> 
> Unless named routes are being used.
> 
> It will prevent 100% errors like it

Yes, it would be very helpful. Could you give an example on the proper way to declare them in the class scope by getters?

**Comment by jonataslaw** [comment]
> > Yep, you had 2 different controllers.
> > It may be necessary to include in the docs that controllers need to be declared:
> > in the build method
> > or class scope by getters
> > Unless named routes are being used.
> > It will prevent 100% errors like it
> 
> Yes, it would be very helpful. Could you give an example on the proper way to declare them in the class scope by getters?

```dart
class MyTalentProfileScreen extends StatelessWidget {
  MyTalentsController get talentController => Get.put(MyTalentsController());
```

As it's explained, I'm closing

**Comment by yulkin2002** [comment]
> 
> 
> > > Yep, you had 2 different controllers.
> > > It may be necessary to include in the docs that controllers need to be declared:
> > > in the build method
> > > or class scope by getters
> > > Unless named routes are being used.
> > > It will prevent 100% errors like it
> > 
> > 
> > Yes, it would be very helpful. Could you give an example on the proper way to declare them in the class scope by getters?
> 
> ```dart
> class MyTalentProfileScreen extends StatelessWidget {
>   MyTalentsController get talentController => Get.put(MyTalentsController());
> ```
> 
> As it's explained, I'm closing

is there a difference between using a getter to declare a controller and the following as per your docs: ```
 // Instantiate your class using Get.put() to make it available for all "child" routes there.
    final Controller c = Get.put(Controller());
```

**Comment by jonataslaw** [comment]
The difference is that according to the doc you should be using named routes, if you use common routes, you should use either in the build, or as a getter.
An even more recommended way is to use bindings and leave the view completely clean, with just widgets, but I don't like to be opinionated on how people are going to work, I just want to warn them to do it in a way that they won't encounter problems.
