### ISSUE TITLE
clear observable list

### ISSUE THREAD

**Issue by ziasultan2** [jonataslaw/getx#848]
Hi I'm trying to clearlist of observable data by using    cardList.value.clear()
  final cardList = List<Data>().obs;
 cardList.value.clear();

but it's not working. 
what is the process to clear observable list

**Comment by jonataslaw** [comment]
Please, read docs

**Comment by ziasultan2** [comment]
> Please, read docs

I didn't find any docs relate to clear the list. Please let me know the function to clear the list
Thank you

**Comment by jonataslaw** [comment]
https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#note-about-lists
Don't use .value with List, Map, and Sets.
