### ISSUE TITLE
You cannot add event to closed Stream & The getter 'x' was called on null

### ISSUE THREAD

**Issue by itsyaasir** [jonataslaw/getx#852]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
I'm fetching API from Unsplash , I currently have two views on the app , HomePage loads well of popular papers , while DetailsPage is supposed to load the full photo with some options , but whenever I clicked a photo on HomePage , it is supposed to direct me to DetailsPage , but I have these error , one is about getter "x" where x is a value in the api models was called on null , funny thing is that the API is loaded after that I tried using if..else statements to catch null so as to load Progress Indicator , it didn't work . After that when I click back button to HomePage and click again a photo I get the error about closed Stream .
I have asked in the Discord group , no one was able to help me. Please I require the assistance even I will take some clues . Thank you 
**Reproduction code
```dart
class DetailsPage extends GetView<DetailsController> {
//more codes
        children: [
          GetX<DetailsController>(
            initState: (state) {
              Get.find<DetailsController>().getPhotoDetails();
              print("getPhotoDetails initialized");
            },
            builder: (_) {
              return ImageWidget(
                imageUrl: "${_.photoDetails.urls.regular}",
                hashBlur: "${_.photoDetails.blurHash}",
                height: Get.height,
                width: Get.width,
              );
            },
          ),

```
I didn't want to clutter the issues by writing all my codes , but I have uploaded my code into [github](https://github.com/itsyaasir/mixspalsh_app/tree/alpha) , I have followed the getx pattern . hopefully you will understand my code well .But if you need me to write them here . I can
**To Reproduce**
1. Go to HomePage
2. Click on any photo on the popular section, some photos need to be clicked twice because of closed Stream
4. See error at the debug console [You cannot add event to closed Stream ,The getter 'x' was called on null]

**Expected behavior**
The photo is supposed to load fully , first comes the hashblur then the photo

**Screenshots**
This is my phone screenshot => https://paste.pics/AW1HL
This is my laptop screenshot => https://paste.pics/AW1O6
**Flutter Version:**
Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)

**Getx Version:**
  3.17.1

**Describe on which device you found the bug:**
Samsung S10+- Android.

**Minimal reproduce code**
```dart
GetX<DetailsController>(
            initState: (state) {
              Get.find<DetailsController>().getPhotoDetails();
              print("getPhotoDetails initialized");
            },
            builder: (_) {
              return ImageWidget(
                imageUrl: "${_.photoDetails.urls.regular}",
                hashBlur: "${_.photoDetails.blurHash}",
                height: Get.height,
                width: Get.width,
              );
            },
          ),
```

**Comment by eduardoflorence** [comment]
- In GetMaterialAPP, when you use the `getPages` property, you cannot use the` home` property. Create a route for `SplashWidget` and place it in `initialRoute`.
- Replace this:
```dart
set photoDetails(photoDetails) => this._photoDetailsModel.value = photoDetails;
```
With:
```dart
set photoDetails(photoDetails) { 
  this._photoDetailsModel.value = photoDetails;
  this._photoDetailsModel.refresh();
}
```

**Comment by eldadj** [comment]
Well, I just downloaded and ran the app, no errors. All images load

**Comment by itsyaasir** [comment]
> Well, I just downloaded and ran the app, no errors. All images load

Try clicking a photo which should take you to a new page . that's where the error is .

**Comment by itsyaasir** [comment]
> * In GetMaterialAPP, when you use the `getPages` property, you cannot use the` home` property. Create a route for `SplashWidget` and place it in `initialRoute`.
> * Replace this:
> 
> ```dart
> set photoDetails(photoDetails) => this._photoDetailsModel.value = photoDetails;
> ```
> 
> With:
> 
> ```dart
> set photoDetails(photoDetails) { 
>   this._photoDetailsModel.value = photoDetails;
>   this._photoDetailsModel.refresh();
> }
> ```

Ok am gonna try it now , thank you .

**Comment by itsyaasir** [comment]
> > * In GetMaterialAPP, when you use the `getPages` property, you cannot use the` home` property. Create a route for `SplashWidget` and place it in `initialRoute`.
> > * Replace this:
> > 
> > ```dart
> > set photoDetails(photoDetails) => this._photoDetailsModel.value = photoDetails;
> > ```
> > 
> > 
> > With:
> > ```dart
> > set photoDetails(photoDetails) { 
> >   this._photoDetailsModel.value = photoDetails;
> >   this._photoDetailsModel.refresh();
> > }
> > ```
> 
> Ok am gonna try it now , thank you .

I have changed what you suggested but it doesn't seem to fix the problems .

**Comment by itsyaasir** [comment]
I fixed the issues by handling null events better and I changed to controller.obx , Thanks for the help guys .
