### ISSUE TITLE
multiple open dialogs one close button

### ISSUE THREAD

**Issue by ash2osh** [jonataslaw/getx#853]
**Describe the bug**
when using `Get.until((_) => !Get.isDialogOpen);` with multiple dialogs open it **closes only one of them**

**Reproduction code

```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(child: Center(
        child: RaisedButton(onPressed: () async {
          for (var i = 0; i < 3; i++) {
            Future.delayed(Duration(seconds: 1), () {
              Get.defaultDialog(onConfirm: () => closeAllDialogs());
            });
          }
        }),
      )),
    );
  }

  closeAllDialogs() {
    Get.until((_) => !Get.isDialogOpen);
  }
}

```

**To Reproduce**
1. open multiple dialogs at same time
2. use `Get.until((_) => !Get.isDialogOpen);`

**Expected behavior**
All Dialogs closed

.

**Flutter Version:**
1.22.4

**Getx Version:**
 3.21.2

**Comment by AbdoTareq** [comment]
It happened to me if I have 2 dialog(one for progress & the other for entering user info) open & I use this code twice:
 if(Get.isDialogOpen)
     Get.back();

it closes only one dialog the progress

**Comment by ash2osh** [comment]
@jonataslaw 
can You Please clarify if this is a valid issue or i am just missing somthing ??

**Comment by rfmanuj** [comment]
@ash2osh @AbdoTareq 

Get.back() will only close one dialog.
Using it in a while loop will close all the dialogs:

Can you try this?
```
while(Get.isDialogOpen!){
      Get.back();
}
```

**Comment by ash2osh** [comment]
i can confir that this is working for the latest version
`Get.until((route) => !Get.isDialogOpen!);`
thanks for the reply 👍
