### ISSUE TITLE
Get.find<ErrorController>(); throws a controller not found exception 

### ISSUE THREAD

**Issue by yulkin2002** [jonataslaw/getx#855]
I am initializing my ErrorController as described below. AuthController intantiates a class that calls Get.find<ErrorController>() and it then throws an exception `"ErrorController" not found. You need to call "Get.put(ErrorController())" or "Get.lazyPut(()=>ErrorController())"`. Why?

```
class LandingScreen extends StatelessWidget {
  ErrorController get errorController => Get.put(ErrorController(), permanent: true);
  AuthController get authController => Get.put(AuthController(), permanent: true);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: kAppBGColour,
      body:  Obx(() {
                    return authController.isLoggedIn.value ? Text('logged in') : Container();})
)
...
}


class AuthController extends GetxController {
...

  final StoredUserData storedUserData = StoredUserData();

...

class StoredUserData {
...  
ErrorController _errorController = Get.find<ErrorController>();
...}
```

**To Reproduce**
run the app, and it throw exception

**Expected behavior**
app should run without throwing an exception

**Flutter Version:**
Framework • revision 1aafb3a8b9 (3 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

**Getx Version:**
 get: ^3.16.2

**Describe on which device you found the bug:**
Nokia 8 - Android

**Comment by jonataslaw** [comment]
```dart
class LandingScreen extends StatelessWidget {
  // it will perform put only when a variable on build request it
  ErrorController get errorController => Get.put(ErrorController(), permanent: true);
  AuthController get authController => Get.put(AuthController(), permanent: true);
```

```dart
class StoredUserData {
// find is calling ErrorController before build
ErrorController _errorController = Get.find<ErrorController>();

// try ErrorController get _errorController => Get.find<ErrorController>();
```

I don't see any problem with the one described, it's literally what your code does.
You need to understand how getters and variables in dart work.

getters are called only when the reference is called, it is just a shortcut to an address in memory.
Variables create the moment you close the class, addressing it in memory, so the moment you do Home (), the variable will find and store the value. If this is prior to a put, you will have an error.
If you transform a variable into getters, all that depend on it will also need to be a getter.
If you insert the put into the build method, your change from having problems is less.
If you use Bindings, you will not have a problem with this in any way.

As this is not an issue, I am closing.
