### ISSUE TITLE
ArgumentError (Invalid argument(s): No host specified in URI example/api/route

### ISSUE THREAD

**Issue by sc-ot** [jonataslaw/getx#865]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
Im extending my ApiService class from GetConnect to make api calls. If i use the baseUrl in htttpClient.baseUrl and only the route in the get method i get the exception: **No host specified in URI ('myExample/route)**. But if i make the get call like this: 

 Future<Response> getTest() => get('https://www.mybaseurl.de/api/v1/test/test');

My baseurl looks like this:  "https://test.backend.de/"

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart
class ApiService extends GetConnect {
  @override
  void onInit() {
    httpClient.baseUrl = "https://test.backend.de/";
    httpClient.addRequestModifier((request) {
      request.headers["X-Client"] = Constants.HEADER_X_CLIENT;
      request.headers["Authentication"] = Constants.HEADER_BEARER_TOKEN;
      request.headers["Content-Type"] = "application/json";
      return request;
    });
  }

  Future<Response> getMandate() => get('api/v1/test/test'); <- wont work
  // would work Future<Response> getMandate() => get('https://test.backend.de/api/v1/test/test'); <- works
}
```

**Comment by sc-ot** [comment]
onInit was never called. I created a standard constructor where i put all the configuration and removed it from onInit(). 
ApiService().getMandates() is now working. Can be closed.

**Comment by eduardoflorence** [comment]
In order to be called onInit you must first do a `Get.put(ApiService());`

**Comment by sc-ot** [comment]
Is it best pactrice to call an instance with Get.put(ApiService())? Doesn't this create an instance every time we want to use the api? I modified my class as a Singleton now, so we don't create an instance everytime i call ApiService()

**Comment by jonataslaw** [comment]
It is a good practice to insert your ApiService into a put because:
1- You will have the same httpClient instance, this will bring many benefits as keepAlive. Connections will be faster if you have a single client, and do not close it after each connection.
2- You will only have one instance of httpClient in memory, if you make an instance for each request, more memory will be used.
3- When it is no longer used or needed, you can close it, and free up resources.
