### ISSUE TITLE
When checking if List is Null it returns false even when it is null

### ISSUE THREAD

**Issue by Flucadetena** [jonataslaw/getx#870]
**Describe the bug**
When you create an observable List with an initial value of null and check if the value of the list is null, the condition returns "false", although it prints null. If you call "list.value" as it was done before, it works as expected

**Reproduction code
```
class ListController extends GetxController{
RxList<User> users = List<User>().obs..nil();

@override
onInit(){
print(users == null) // This will be false
print(users.value == null) //this will be true
}
```

**To Reproduce**
Simply call the Controller

**Expected behavior**
To return true every time

**Flutter Version:**
V. 1.22.4

**Getx Version:**
V. ^3.21.3

**Describe on which device you found the bug:**
Iphone 12 pro max, Emulator

**Comment by eduardoflorence** [comment]
For RxList use isEmpty method:
`print(users.isEmpty);`

**Comment by Flucadetena** [comment]
Hi @eduardoflorence Thanks for the answer. But that not only I think it is confusing, but it breaks. I throughs and error saying 
```
Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null
```

**Comment by eduardoflorence** [comment]
I'm reopening the problem for @jonataslaw to give a better explanation.

**Comment by Flucadetena** [comment]
Thanks @eduardoflorence :)

**Comment by jonataslaw** [comment]
nil just made the list value null, because in dart you can't make the object itself null.

As this api has been removed due to null-safety, this is being closed
