### ISSUE TITLE
Get.snackbar won't show up when there's an opened dialog

### ISSUE THREAD

**Issue by sooxt98** [jonataslaw/getx#874]

**Comment by eduardoflorence** [comment]
hi @sooxt98, Please provide a minimum code to reproduce the problem, as it is much faster so that we can help you.

**Comment by jonataslaw** [comment]
Closing for not respecting the issue opening form.

**Comment by sooxt98** [comment]
Thanks all, I think I knew why it doesn't work,because I'm using built in showDialog instead of Get.dialog which confuse the GetX
