### ISSUE TITLE
Get.context is not working?

### ISSUE THREAD

**Issue by pqtrong17** [jonataslaw/getx#876]
I have a class extends GetView, like this:
```
class OffRequestPage extends GetView<OffRequestController>
```
I called a function that use `context`:

```
Toast.show("Success", Get.context);
```
I tried `overlayContext` but also not working.
Then I get an error:
```
E/flutter ( 3052): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'insert' was called on null.
E/flutter ( 3052): Receiver: null
E/flutter ( 3052): Tried calling: insert(Instance of 'OverlayEntry')
E/flutter ( 3052): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
```
How do fix it?

**Comment by jonataslaw** [comment]
If the context wasn't working, navigation wouldn't work either.
Next time, try to open the issue in the appropriate repository, this error has nothing to do with GetX.

Looking just over the source of the package you are using, you can see that it is trying to access the overlayState through the Overlay's InheritedWidget, this is wrong, as it limits the scope of the overlay to below the widget tree.

Where is it:

```dart
overlayState = Overlay.of(context, rootOverlay: rootNavigator ?? false);
```
should be:
```
  final navigatorState =
        Navigator.of(context, rootNavigator: rootNavigator ?? false);
    overlayState = navigatorState.overlay;
```
And everything would work with any context :)
