### ISSUE TITLE
GetX handle application lifecycle

### ISSUE THREAD

**Issue by halimpuckjava** [jonataslaw/getx#877]
hi

1.  with GetX we can handle onInit(), onReady() events for application, but when user close application or pause or suspend or stop or resume it there is no handler to these events, so i suggest to more events handler to make GetX strong for flutter application lifecycle

2. onDispose() handler no fire when close application !!!!!

**Comment by jonataslaw** [comment]
Dispose is not called when the application closes, it is Flutter mate, onDestroy from android and ApplicationWillTerminate from ios do not call the dispose method of Flutter.

Relationed to https://github.com/flutter/flutter/issues/28134#issuecomment-540306801

**Comment by mjablecnik** [comment]
@jonataslaw So how can I handle the events like: pause, suspend or resume in GetX?
In this [article](https://medium.com/pharos-production/flutter-app-lifecycle-4b0ab4a4211a) is description how to handle it with stateful widget but with GetX I am using only stateless widget with controller which contains my state..

**Comment by mjablecnik** [comment]
Ok so now I discovered that I can extend GetxController with WidgetsBindingObserver and then use didChangeAppLifecycleState function same as in the article.. :)

example is here:
```
class HomeController extends GetxController with WidgetsBindingObserver {

  onInit() {
    super.onInit();
    WidgetsBinding.instance.addObserver(this);
  }

  onClose() {
    super.onClose();
    WidgetsBinding.instance.removeObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    print('state = $state');
  }
}
```

**Comment by Vinayak27Mobility** [comment]
Does this works with stateless widget? if the controller is tied to stateless widget?

**Comment by Vinayak27Mobility** [comment]
> @jonataslaw So how can I handle the events like: pause, suspend or resume in GetX?
> In this [article](https://medium.com/pharos-production/flutter-app-lifecycle-4b0ab4a4211a) is description how to handle it with stateful widget but with GetX I am using only stateless widget with controller which contains my state..

Does this works with stateless widget? if the controller is tied to stateless widget?

**Comment by Luk4s2** [comment]
Well GetX have it covered all u need to do is create class controller  and extend it with Super Controller then u need to initialize it in you main folder so will be available through whole app

 `class LifeCycleController extends SuperController {

  @override
  void onDetached() {}

  @override
  void onInactive() {}

  @override
  void onPaused() {}

  @override
  void onResumed() {}
}`

then initialize it in main like that 
`void main() {
  Get.put(LifeCycleController());
  runApp(MyApp());
}`

**Comment by mohsinnaqvi606** [comment]
**I need onResume method like android have.**
I have 4 screens in Bottom AppBar, I wants to perform some operations(Api calling) when coming back to screen _(only for third screen not for every screen)_

I have tried **WidgetsBindingObserver** but is works for whole App not for specific screen
