### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by riktamnandi** [jonataslaw/getx#878]
How can I run a function when variable changes ? GetX always wants a Widget in observer's return type

**Comment by SchabanBo** [comment]
I Think what you need is ever()
https://github.com/jonataslaw/getx/blob/master/documentation/en_US/state_management.md#workers

**Comment by xyzbilal** [comment]
as @SchabanBo  mentioned Workers are best solution.

**Comment by jonataslaw** [comment]
As informed, you must use Worker ever.
Please, when you need help, try to use the community channels, there you will be answered faster, and it is the right place.

**Comment by riktamnandi** [comment]
Thanks. I got helped from Discord channel. Any further discussion I will post there.
Anyway thanks :)
