### ISSUE TITLE
在使用导航时如何使上一个页面保持固定

### ISSUE THREAD

**Issue by aluo44** [jonataslaw/getx#880]
在使用导航时如何使上一个页面保持固定, 也就是说A页面保持不动, B页面从右边向左边推过来这样.
现在的情况是B页面从右边推过来,但是A页面也会向左滑动一点.

**Comment by jonataslaw** [comment]
Use transitions like transition: Transitions.fade, cupertino that has this animation on the previous route.
Please use English to open issues, you can use an internet translator for this, it makes it easier for people from different countries to help you.
