### ISSUE TITLE
Snackbar not showing inside Get.dialog / showDialog

### ISSUE THREAD

**Issue by sooxt98** [jonataslaw/getx#885]
MyView
``` dart
Get.dialog(FlatButton(onPress: () async {
  someController.work(); // my current workaround
}));
```

My Controller
``` dart
class SomeController extends GetxController {
    work() async {
      Get.snackbar('Error', 'Invalid format');
      return Get.snackbar('', '');
    }

    notWork() async {
      return Get.snackbar('Error', 'Invalid format');
    }
}
```

**Comment by eduardoflorence** [comment]
Hi @sooxt98,
I was unable to reproduce this behavior. It's working well for me. Here's how I tested it:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(home: HomePage()));
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final controller = Get.put(SomeController());
    return Scaffold(
      appBar: AppBar(title: Text('HOME')),
      body: Center(
        child: Container(
          color: Colors.yellow,
          child: FlatButton(
            child: Text('Open Dialog'),
            onPressed: () => Get.dialog(FlatButton(
              color: Colors.red,
              child: Text('Open Snack'),
              onPressed: () {
                controller.work();
              },
            )),
          ),
        ),
      ),
    );
  }
}

class SomeController extends GetxController {
  void work() async {
    Get.snackbar('Error', 'Invalid format');
  }
}
```

**Comment by sooxt98** [comment]
@eduardoflorence You have miss out the 'return' keyword 

Should be return Get.snack bar

**Comment by SchabanBo** [comment]
I don't understand,
Why would you want to return the Snackbar!!!
The Snackbar method is **Void**

**Comment by sooxt98** [comment]
The reason here is simple, assume that the work function is very complex and got lots of conditions, when some of it need to be returns first due to validation error , or invalid input; so in our case we show the snackbar and exit the our function with return;

**Comment by SchabanBo** [comment]
The Snackbar method is void, you cannot return it.
  https://github.com/jonataslaw/getx/blob/a69c21c8e477f19f293b16696caa9c3941ca616f/lib/get_navigation/src/extension_navigation.dart#L105
 And in this case you don't need to return anything, because there is no code after that. 
And when you need to. define the function as void

**Comment by jonataslaw** [comment]
Hey, is this discussion necessary?
I mean, one of the general programming principles is that a void method cannot be used as a return.
This is logical, since it returns nothing, then there will be no return. It is not something like null being returned, because even null is something.
void methods should also not be marked as async in the dart, instead you should use Future<void>. The compiler is smart enough today to do this implicitly in AOT, but you may experience problems with dart2js, or even in future versions if something changes.

And just one last side note, do "return;" in dart it's the same as leaving no return, you don't have to do that, because if the method is void, it won't return anything, and "return;" should only be used as a conditional to terminate the void method without executing all lines, eg:

```dart
void anything(bool foo) {
if(foo) return;
madeAnything();
}
```

**Comment by sooxt98** [comment]
Did you mean that the following code should work fine? Shen the work is defined as void func

class SomeController extends GetxController {
  void work() async {
    return Get.snackbar('Error', 'Invalid format');
  }
}

**Comment by jonataslaw** [comment]
```dart
class SomeController extends GetxController {
void work()  {
  Get.snackbar('Error', 'Invalid format');
 }
}
```

**Comment by sooxt98** [comment]
@jonataslaw Yes I'm using it to terminate stuff, but before that I need to show a snackbar

**Comment by jonataslaw** [comment]
If you want the snackbar to return a Future (in which case you can use return), you can use Get.showSnackbar instead of Get.snackbar. However, you will have to pass a GetBar widget to it, which is the widget that will be displayed.

**Comment by sooxt98** [comment]
@jonataslaw I think maybe I just use back my original workaround would me more cleaner. Or maybe showSnackBar should work fine also

**Comment by eduardoflorence** [comment]
@sooxt98 I modified the code, see if this works for you:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(home: HomePage()));
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final controller = Get.put(SomeController());
    return Scaffold(
      appBar: AppBar(title: Text('HOME')),
      body: Center(
        child: Container(
          color: Colors.yellow,
          child: FlatButton(
            child: Text('Open Dialog'),
            onPressed: () => Get.dialog(FlatButton(
              color: Colors.red,
              child: Text('Open Snack'),
              onPressed: () {
                controller.work(true);
              },
            )),
          ),
        ),
      ),
    );
  }
}

class SomeController extends GetxController {
  Future<void> work(bool foo) async {
    if (foo) {
      await Future.delayed(Duration(seconds: 1)); // simulation
      Get.snackbar('Error', 'Invalid format');
      return;
    } 
    print('not print');
  }
}
```

**Comment by sooxt98** [comment]
@eduardoflorence it wont work

**Comment by eduardoflorence** [comment]
For me it worked normally. What behavior do you expect and is not happening with this code that I put in?

**Comment by sooxt98** [comment]
@eduardoflorence ya ur code did work, mine original one doesnt; im still trying to find out why and extracting the error code out

**Comment by sooxt98** [comment]
@eduardoflorence ahhh i think i knew why, silly me! theres extra Get.back() after i calling the work func
![image](https://user-images.githubusercontent.com/13378059/101699679-8a14a600-3ab6-11eb-9222-2d54414dd797.png)

**Comment by sooxt98** [comment]
thanks all, thanks for helping me out XD
