### ISSUE TITLE
GetConnect onInit() - Unable to set the baseUrl/AddAuthenticator 

### ISSUE THREAD

**Issue by jnickzlim** [jonataslaw/getx#894]
I tried to follow Custom configuration document from https://pub.dev/documentation/get/latest/#getconnect  
to setup the base url and also add authenticator, but was unable to do so.

**To Reproduce**

```dart
class HomeProvider extends GetConnect {
  @override
  void onInit() {
    httpClient.baseUrl = "https://serverurl.com";

    httpClient.addAuthenticator((request) async {
      final token = "myBearerToken";
      request.headers['Authorization'] = "Bearer $token";
      return request;
    });
  }
  Future<Response> postTest(Map data) => post("/api/test" , data);
}
```

**Expected behavior**
Expect that the base url would be already set and also the authorization bearer token is also set at header, but it is not.

**Flutter Version:**
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (8 weeks ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)

**Getx Version:**
get:
    dependency: "direct main"
    description:
      name: get
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.22.2"

**Describe on which device you found the bug:**
iPhone 12 Pro Simulator

**Comment by jonataslaw** [comment]
You need to inject the dependency for onInit to be called.
As it is a failure of use, I am closing this issue.

**Comment by jnickzlim** [comment]
I am aware that GetxService / GetxController need Get.put or Get.lazyPut but did not know GetConnect need that too as at the documentation [GetConnect](https://github.com/jonataslaw/getx#getconnect) did not state anything about it.

It would be helpful to state that Get.put or Get.lazyPut is required for GetConnect.

Thank you for the clarification. =)

**Comment by eduardoflorence** [comment]
Hi @jnickzlim, `httpClient.addAuthenticator` "only" is called after a request (get/post/put/delete) that returns HTTP status code 401. It is useful when your token expires and you need to obtain a new token. It is necessary to use `httpClient.maxAuthRetries`, when using `addAuthenticator`.

To add a token to your `post`, use:
```dart
httpClient.addRequestModifier((request) {
  final token = "myBearerToken";
  request.headers['Authorization'] = "Bearer $token";
  return request;
});
```

**Comment by eduardoflorence** [comment]
I tested `httpClient.baseUrl` and does not return null

**Comment by jnickzlim** [comment]
@eduardoflorence Thank you for the info, i have change addAuthenticator to addRequestModifier however it's still the same where the baseUrl is null and the headers does not contain the value.

Run Console:
```
Unhandled Exception: Invalid argument(s): No host specified in URI /api/test
```

At my laravel backend telescope:
```json
{
    "host": "laravelbackend.localhost",
    "content-length": "0",
    "accept-encoding": "gzip",
    "content-type": "application/json; charset=utf-8",
    "user-agent": "getx-client"
}
```

Remark: I have already place Get.lazyPut at main.dart
```dart
void main() async {
   ...
   Get.lazyPut<AuthService>(() => AuthService());
   Get.lazyPut<HomeProvider>(() => HomeProvider());
   ...
   runApp(MyApp());
}
```

GetxService and GetxController are working, just can not get the baseUrl and headers for GetConnect to work...

My temporary work around would be to manually include the header and request with full path:
(Which defeat the purpose of using GetConnect...)

```dart
Future<Response> getReservations({@required startDate, @required endDate}) {
    final headers = {
      "Authorization": "Bearer ${AuthService.to.authToken}",
     };
  
    return get(
      'https://laravelbackend.localhost/reservation',
       headers: headers,
    );
  }
```

**Comment by jnickzlim** [comment]
Where did you print the baseUrl? At onInit or during the postMethod?

**Comment by diego-lipinski-de-castro** [comment]
I dont think this is clear enought in the documentation, i struggled 2 days to get this to work

**Comment by Invincible1996** [comment]
@jnickzlim I faced the same issue too .Did you find the solution? When I print baseUrl in onInit method is null.

**Comment by tonraj** [comment]
how to set httpClient.baseUrl? I updated the httpClient.baseUrl as set by getx cli and when I call in it any method it returns null.

**Comment by bookyo** [comment]
me too

**Comment by tonraj** [comment]
Make sure you have injected the dependency with Get.put and call it using Get.find<>() in order to get onInit() called. 

> @jnickzlim I faced the same issue too .Did you find the solution? When I print baseUrl in onInit method is null.



> me too

**Comment by dzungvu** [comment]
I faced the same problem too. What I've done to resolved this is:
Using binding in GetPage (from pages[]):
```dart
GetPage(
    name: HomeScreen.routeName,
    page: () => HomeScreen(),
    binding: HomeBinding(),
  ),
```
Small note: When use **binding** tag, you should not declare **home** tag in **GetMaterialApp** like this:  home: HomeScreen(),
Instead, you should use initialRoute with the home's route name
```dart
initialRoute: HomeScreen.routeName,
```

In main.dart, add this line before runApp:
```dart
WidgetsFlutterBinding.ensureInitialized();
```
This is to make sure that binding is running before your view start.
Then put the api provider inside HomeBinding like so:
```dart
class HomeBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => HomeController());
    Get.lazyPut(() => APIProvider());
  }
}
```
And this in case you use the provider:
```dart
APIProvider _apiProvider = GetInstance().find<APIProvider>();
```

**Comment by Williano** [comment]
Please Anyone with solutions to this? Anytime I start my app, I get no base api specified error. I have injected my BaseAPI but still.

**Comment by khari998** [comment]
> Please Anyone with solutions to this? Anytime I start my app, I get no base api specified error. I have injected my BaseAPI but still.

How are you instantiating your controllers?

**Comment by jeryRazakarison** [comment]
The last answer helped me.
in the onInit, the baseUrl property is set on httpClient. But in the sample, you call .get on `this`.
Doing httpClient.get(.... , instead of just get( worked.

**Comment by anonimeact** [comment]
i also got this error,
solved after following answer from @LukeStanyer .
and dont forget to find provider inside your controller like this, var movieProvider = Get.find<ItemMovieModelProvider>();

**Comment by kauemurakami** [comment]
I use a class that inherits from `WebRequest` which in turn, extends the `GetConnect`, with implements service we can retrieve the API with `Get.find<MyAPIRequest>()`.
```
const baseUrl = String.fromEnvironment('BASE_URL');

class MyAPIRequest extends WebRequest implements GetxService {
  Future<MyAPIRequest> init() async {
    print('initapi');
    // config the baseurl to httpClient
    httpClient.baseUrl = baseUrl ;
   ...
    return this;
  }
...
}
```
When trying to assign direct `httpClient.baseUrl = String.fromEnvironment('BASE_URL')`, he attributed null, but by creating a constant out of scope and using it I was able to assign the base url.
To inject use `await Get.putAsync(() =>MyAPIRequest().init());`

Using

class APPAPI {
  final myapirequest = Get.find<MyAPIRequest>();
  getExample()async{
    //url without base url
    final response = await myapirequest.httpClient.get('/v1/example')
  }
}
