### ISSUE TITLE
Get.offAllNamed and Bindings does not works and deletes controllers

### ISSUE THREAD

**Issue by Drolegc** [jonataslaw/getx#904]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
When I use Get.offAllNamed('/example'), the binding on that route is called, but after using some controller's functions, those controllers are deleted.
I can use the permanent flag, but that's not ideal

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

example:

```dart

Main

void main() {
  runApp(GetMaterialApp(
    getPages: [
      GetPage(name: "/page1",page: () => Page1(),binding: Page1Binding()),
      GetPage(name: "/page2",page: () => Page2(),binding: Page2Binding()),
    ],
    initialRoute: "/page1",
  ));
}

Bindings and Controllers

class Controller1 extends GetxController{
  String data = "Hello!";
}

class Page1Binding implements Bindings{
  @override
  void dependencies() {
    print("Dependencies 1");
    Get.put(Controller1(),permanent: true);
  }

}

class Page2Binding implements Bindings{
  @override
  void dependencies() {
    print("Dependencies 2");
    Get.put(Controller1());
  }

}

Pages

class Page1 extends StatelessWidget {

  final Controller1 _controller1 = Get.find();

  @override
  Widget build(BuildContext context) {
    print("${_controller1.data} - Data from controller and page1");
    return Scaffold(
      body: Container(
        child: Center(
          child: FlatButton(
            color: Colors.red,
            child: Text("Go to page 2"),
            onPressed: (){
              Get.toNamed("/page2");
            },
          ),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {

  final Controller1 _controller1 = Get.find();


  @override
  Widget build(BuildContext context) {
    print("${_controller1.data} - Data from controller and page2");

    return Scaffold(
      body: Container(
        child: Center(
          child: FlatButton(
            color: Colors.yellow,
            child: Text("Go to page 1 with offAllNamed"),
            onPressed: (){
              Get.offAllNamed("/page1");
            },
          ),
        ),
      ),
    );
  }
}

```

**To Reproduce**
1. Check the console to see the logs, Dependencies 1 should be called
2 . Click on 'Go to page 2'
3. Idem 1 but with Dependencies 2
4. Click on 'Go to page 1 with offAllNamed'
5. Check the console to see the logs, we should see that the smart management try to delete the controllers of page1

**Expected behavior**
The dependencies(controllers) of page1 should be called but not deleted

**Flutter Version:**
1.22.4

**Getx Version:**
3.22.2

**Describe on which device you found the bug:**
ex: Xioami Redmi 6a - Android.

**Comment by eduardoflorence** [comment]
Hi @Drolegc,
   The `Get.put` that is in Page2Binding does not create a second instance of the controller. For you to create it is necessary to use the tag property.

```dart
class Page2Binding implements Bindings{
  @override
  void dependencies() {
    print("Dependencies 2");
    Get.put(Controller1(), tag: 'instance2');
  }
}
```

**Comment by Drolegc** [comment]
> Hi @Drolegc,
> The `Get.put` that is in Page2Binding does not create a second instance of the controller. For you to create it is necessary to use the tag property.
> 
> ```dart
> class Page2Binding implements Bindings{
>   @override
>   void dependencies() {
>     print("Dependencies 2");
>     Get.put(Controller1(), tag: 'instance2');
>   }
> }
> ```

Hi @eduardoflorence !
In Page2Binding i want to use the same Controller as Page1Binding. 
The problem here is that Get.offAllNamed('/page1') delete the controllers, but if I use Get.affNamed('/page1') not

**Comment by jonataslaw** [comment]
use `Get.put(Controller1(), permanent:true); ` Get.offAll will remove ALL controllers of memory

**Comment by eduardoflorence** [comment]
> Olá @eduardoflorence !
> Em Page2Binding eu quero usar o mesmo controlador que Page1Binding.
> O problema aqui é que Get.offAllNamed ('/ page1') exclui os controladores, mas se eu usar Get.affNamed ('/ page1') não

Now I understand.

This is the expected behavior for Get.offAllNamed. It removes all routes (page 1 and page2) from memory and also its controllers. It should only be used when you don't want to keep any route in memory. For your use case, Get.offNamed is the most suitable.

**Comment by Drolegc** [comment]
Thank @eduardoflorence  and @jonataslaw 
I already use the permanent flag.

But, should not Get.offAllNamed do the same as Get.offNamed ? If Get.offNamed removes the controllers of the page, I expect Get.offAllNamed to do the same. with all the pages. Or at least, delete the controllers, and then call the bindings

**Comment by bbrazsilveira** [comment]
@Drolegc 

I had the same issue. In my case, Firebase wall firing auth event twice and my app was calling Get.offNamedAll twice as well, so it deletes all controllers including the new one.

**Comment by Suhailakl** [comment]
I have the same problem. When I call offAndToNamed after the signing page all controllers in the home route deletes automatically. I don't know why this is happening. I thought it would delete the controllers on the same page and won't delete the upcoming page. Something wrong.So, how can we delete all of the controllers and screen so far and push a new route?

**Comment by Drolegc** [comment]
> I have the same problem. When I call offAndToNamed after the signing page all controllers in the home route deletes automatically. I don't know why this is happening. I thought it would delete the controllers on the same page and won't delete the upcoming page. Something wrong. So, how can we delete all of the controllers and screen so far and push a new route?

@Suhailakl you have to set on true the permanent flag, and what I did was to create a static function on HomeBinding to delete those controllers
