### ISSUE TITLE
How to add global configuration (baseUrl, Authorization) to GetConnect/Provider 

### ISSUE THREAD

**Issue by limsocheat** [jonataslaw/getx#908]
If we have multiple providers generated with the model. 

How could we add a global configuration for baseUrl & Authorization? 
so we don't need to repeat it again.

```
import 'package:get/get.dart';
import 'package:nhameylov/utils/models/media_model.dart';

class MediaProvider extends GetConnect {
  @override
  void onInit() {
    httpClient.defaultDecoder = (map) => Media.fromJson(map);
    **httpClient.baseUrl = 'YOUR-API-URL';**
    **httpClient.addAuthenticator((request) async {
      final token = "myBearerToken";
      request.headers['Authorization'] = "Bearer $token";
      return request;
    });**
  }

  Future<Response<Media>> getMedia(int id) async => await get('media/$id');
  Future<Response<Media>> postMedia(Media media) async =>
      await post('media', media);
  Future<Response> deleteMedia(int id) async => await delete('media/$id');
}
```

**Comment by alyyasser** [comment]
i haven't use GetConnect yet, but maybe you can try something like this:

```dart
class GlobalConfig {
  GlobalConfig._();

  static String baseUrl = 'YOUR-BASE-URL';
  static RequestModifier authBuilder = (request) async {
    final token = "myBearerToken";
    request.headers['Authorization'] = "Bearer $token";
    return request;
  };
}
```

```dart
class MediaProvider extends GetConnect {
  @override
  void onInit() {
    httpClient.defaultDecoder = (map) => Media.fromJson(map);
    httpClient.baseUrl = GlobalConfig.baseUrl;
    httpClient.addAuthenticator(GlobalConfig.authBuilder);
  }
}
```

**Comment by pratamatama** [comment]
Not sure if this was a proper GetX approach but it works in my case, on my current app, what I did is creating a `BaseProvider` class that extend `GetConnect`.

```dart
class BaseProvider extends GetConnect {
  @override
  void onInit() {
    httpClient.baseUrl = EnvService.env.pull(EnvItems.apiUrl);
    httpClient.addRequestModifier(_requestModifier);
    // TODO: add authenticator
  }

  FutureOr<Request> _requestModifier(request) {
    final token = StorageService.box.pull(StorageItems.accessToken);

    request.headers['X-Requested-With'] = 'XMLHttpRequest';
    request.headers['Authorization'] = 'Bearer $token';

    return request;
  }
}
```

And then in my other provider I can just extend it, this way, I don't need to define each property all over the place and when I need to modify something inside `onInit`, I could just override it.

```dart
class AnnouncementProvider extends BaseProvider implements IBaseRestApi {
  /// Default decoder for paginated [Announcement]s.
  Paginated<Announcement> _decoder(dynamic json) {
    return Paginated<Announcement>.fromJson(json, Announcement.fromJson);
  }

  @override
  void onInit() {
    httpClient.defaultDecoder = _decoder;
    super.onInit();
  }

  @override
  Future index() {
    return get('announcements');
  }

  ...
  ...
}
```

**Comment by jonataslaw** [comment]
Both solutions mentioned above work, and can be used.
I personally like to create a base provider taking advantage of inheritance attributes, and sometimes I create a CustomGetConnect and inject it into each provider.
I am not going to insert global settings into the scope of Get for GetConnect, because we are wiping out GetX to depend as little as possible on global variables, leaving only things like loggers and smartManagement that are actually used by the entire package in almost every function.

**Comment by axu6705** [comment]
> Both solutions mentioned above work, and can be used.
> I personally like to create a base provider taking advantage of inheritance attributes, and sometimes I create a CustomGetConnect and inject it into each provider.
> I am not going to insert global settings into the scope of Get for GetConnect, because we are wiping out GetX to depend as little as possible on global variables, leaving only things like loggers and smartManagement that are actually used by the entire package in almost every function.

Can you provide a simple use case? Thanks!

**Comment by diego-lipinski-de-castro** [comment]
Im trying @pratamatama approach but my provider is not inheriting the base provider attributes, could you provide a full example on github?
