### ISSUE TITLE
Get.Snackbar() not showing on IOS devices

### ISSUE THREAD

**Issue by lauralarez** [jonataslaw/getx#910]
Hello! I have the following code:

`
Get.snackbar("Title", 
     "argument",
     margin: EdgeInsets.zero,
     snackPosition: SnackPosition.TOP,
     backgroundColor: Colors.black,
     colorText: Colors.white,
);
`

It is working fine with Android devices but when I tested it on an iPhone it never shows

Using get: ^3.22.2

**Comment by eduardoflorence** [comment]
Try `snackPosition: SnackPosition.BOTTOM` and remove `backgroundColor: Colors.black`

**Comment by eduardoflorence** [comment]
I tested it now on an iOS simulator and it worked with the parameters you provided.
You could provide a minimum code for testing and describe your environment (GetX and Flutter version)

**Comment by lauralarez** [comment]
Thanks for the help, turns out it was the code above it only working for android so on iOS wouldn't go past it.

Closing the issue.
