### ISSUE TITLE
No named parameter with the name 'allowSelfSigned'

### ISSUE THREAD

**Issue by cedteg** [jonataslaw/getx#911]
**Describe the bug**
Web can not build

**To Reproduce**
1. Update to 3.32.0
2. Build for web
3. See error

**Expected behavior**
web build compiled

**Screenshots**
![image](https://user-images.githubusercontent.com/40794239/102237440-f51a0e80-3ef4-11eb-9b3f-9df43604b6b8.png)

**Flutter Version:**
1.24.0-10.2.pre

**Getx Version:**
3.23.0

**Comment by cedteg** [comment]
@eduardoflorence 
Thanks for your quick reply.

Problem still exists.

**Comment by eduardoflorence** [comment]
Try:
```
flutter pub cache repair
flutter clean
flutter pub get
```

**Comment by cedteg** [comment]
Unfortunately not either

**Comment by cedteg** [comment]
With 3.22.2 it works fine

**Comment by jonataslaw** [comment]
Fix on get: ^3.23.1

**Comment by cedteg** [comment]
3.23.1 work fine.

Thanks you
