### ISSUE TITLE
[GetPage] toNamed not working when used with nested route

### ISSUE THREAD

**Issue by pratamatama** [jonataslaw/getx#912]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
The method `Get.toNamed('some/route')` does not work on nested route.

**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

<details>
<summary>main.dart</summary>

```dart
void main() {
  runApp(
    GetMaterialApp(
      title: 'GPR',
      debugShowCheckedModeBanner: false,
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
    ),
  );
}
```
</details>

<details>
<summary>app_pages.dart</summary>

```dart
import 'package:get/get.dart';

import 'page_a.dart';
import 'page_b.dart';
import 'page_c.dart';

part 'app_routes.dart';

class AppPages {
  static const INITIAL = Routes.PAGE_A;

  static final routes = [
    GetPage(
      name: Routes.PAGE_A,
      page: () => PageA(),
      children: [
        GetPage(
          name: Routes.PAGE_B,
          page: () => PageB(),
          children: [
            GetPage(
              name: Routes.PAGE_C,
              page: () => PageC(),
            ),
          ],
        ),
      ],
    ),
  ];
}
```
</details>

<details>
<summary>app_routes.dart</summary>

```dart
part of 'app_pages.dart';

abstract class Routes {
  // static const PAGE_A = '/a';
  // static const PAGE_B = '$PAGE_A/b';
  // static const PAGE_C = '$PAGE_B/c';

  static const PAGE_A = '/a';
  static const PAGE_B = '/a/b';
  static const PAGE_C = '/a/b/c';
}
```
</details>

<details>
<summary>page_a.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:getx_getpage_issue/app_pages.dart';

class PageA extends GetView {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('page A'),
            RaisedButton(
              child: Text('to page B'),
              onPressed: () => Get.toNamed(Routes.PAGE_B),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>page_b.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:getx_getpage_issue/app_pages.dart';

class PageB extends GetView {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('page B'),
            RaisedButton(
                child: Text('to page C'),
                onPressed: () => Get.toNamed(Routes.PAGE_C)),
          ],
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>page_c.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class PageC extends GetView {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('page C'),
            RaisedButton(child: Text('back'), onPressed: () => Get.back()),
          ],
        ),
      ),
    );
  }
}

```
</details>

**To Reproduce**
1. Make a new flutter project, add `get` on `pubspec.yaml`
2. Make each file mentioned above, and copy paste the content, adjust the `import 'package:getx_getpage_issue'` to yours
3. Run the app, click the button

**Expected behavior**
It should be redirected to page B, and then in page B, it should be able to go to page C, and so forth.

**Screenshots**
`Scenario 1` using `Routes.NAME`

<details>
<summary>click here to see</summary>

![DnQuWaa6GF](https://user-images.githubusercontent.com/42239243/102239391-64a9f100-3f29-11eb-95ac-6cecb99aa463.gif)
</details>

`Scenario 2` hardcoded.

<details>
<summary>click here to see</summary>

![aSMdZWi4vp](https://user-images.githubusercontent.com/42239243/102239776-ca967880-3f29-11eb-8477-131608e46b56.gif)
</details>

`Scenario 3` similar to `Scenario 1` but with `/a`, `/b`, `/c` independently instead of `/a`, `/a/b`, `a/b/c`

<details>
<summary>click here to see</summary>

![yvFFxBigKe](https://user-images.githubusercontent.com/42239243/102240996-0f6edf00-3f2b-11eb-938d-398c5f7ef419.gif)
</details>

**Flutter Version:**
```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (5 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

**Getx Version:**
`get: ^3.23.0`

**Describe on which device you found the bug:**
ex: Android 10 - (Xiaomi Redmi Note 7, codename: Lavender)

**Minimal reproduce code**
`onPressed: () => Get.toNamed(Routes.PAGE_B)`
or
`onPressed: () => Get.toNamed('/a/b')`
or
`onPressed: () => Get.toNamed('/b')`

**Comment by jonataslaw** [comment]
When you insert a nested page, to access it, you must enter the full path, as well as a browser URL.

so if "c" is a child of "b" which is a child of "a", you access it with Get.toNamed ('a/b/c')

**Comment by SchabanBo** [comment]
The library combines automatically the parents routes with the children routes.
So you defined this tree

- /a
   - /a/b
    - /a/b/c

And this tree is built
- /a
- /a/a/b
- /a/a/b/a/b/c

If you what a tree like you definition you have to define the routes like this.
-/a
  - /b
    - /c

**Comment by pratamatama** [comment]
> When you insert a nested page, to access it, you must enter the full path, as well as a browser URL.
> 
> so if "c" is a child of "b" which is a child of "a", you access it with Get.toNamed ('a/b/c')

so it needs some kind of `http://` prefix? @jonataslaw 



> If you what a tree like you definition you have to define the routes like this.
> -/a
> 
> * /b
>   
>   * /c

i think i did it already, you can see it on `scenario 3`'s image @SchabanBo

**Comment by SchabanBo** [comment]
@pratamatama i meant when you define the routes, not when you navigate.
i have replaced your routes with this
```dart
  static final routes = [
    GetPage(
      name: '/a',
      page: () => PageA(),
      children: [
        GetPage(
          name: '/b',
          page: () => PageB(),
          children: [
            GetPage(
              name: '/c',
              page: () => PageC(),
            ),
          ],
        ),
      ],
    ),
  ];
```
and tested it. and it works as expected

**Comment by pratamatama** [comment]
> @pratamatama i meant when you define the routes, not when you navigate.
> i have replaced your routes with this
> ```dart
>   static final routes = [
>     GetPage(
>       name: '/a',
>       page: () => PageA(),
>       children: [
>         GetPage(
>           name: '/b',
>           page: () => PageB(),
>           children: [
>             GetPage(
>               name: '/c',
>               page: () => PageC(),
>             ),
>           ],
>         ),
>       ],
>     ),
>   ];
> ```
> and tested it. and it works as expected

 @SchabanBo I don't get it, isn't it just the same as this?

```dart
// extracted from scenario 3
abstract class Routes {
    static const PAGE_A = '/a';
    static const PAGE_B = '/b';
}
...

GetPage(
    name: Routes.PAGE_A, // '/a'
    page: () => PageA(),
    children: [
        GetPage(
            name: Routes.PAGE_B,  // '/b'
            page: () => PageB(),
            children: [...],  // '/c'
        ),
    ],
),
```

**Comment by SchabanBo** [comment]
when you changed it in Scenario 3 you made it right in the tree but then you have navigated to the wrong route `/b` you should navigate to `/a/b`

**Comment by pratamatama** [comment]
> when you changed it in Scenario 3 you made it right in the tree but then you have navigated to the wrong route `/b` you should navigate to `/a/b`
> 
> 

aaaa... so this was the problem, I thought `Get.toNamed` will add the prefix under the hood. I see clear now

**Comment by pratamatama** [comment]
I've just tested it, works fine. Thanks for the support. Gonna close this issue now.
