### ISSUE TITLE
And still GetX uses or not  Streams?

### ISSUE THREAD

**Issue by ValeriusGC** [jonataslaw/getx#915]
I read that `PERFORMANCE: GetX is focused on performance and minimum consumption of resources. GetX does not use Streams or ChangeNotifier.`
But digging in the source illustrates something like that:
```
class GetStreamTransformation<T> extends Stream<T> { ...
```
What about that?

**Comment by jonataslaw** [comment]
I think the name of the class is clear enough, but in case you didn't understand the code, this is a class that turns GetStream into a Stream, in case you need one for some reason.
The project does not use dart streams, but if you use yourObs.stream, this class will transform voidCallbacks into streams.
