### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by ValeriusGC** [jonataslaw/getx#916]
trying to test in example raised error:

![Screenshot from 2020-12-16 13-48-03](https://user-images.githubusercontent.com/3320861/102325861-7d57ec80-3fa5-11eb-8f09-13a2d73e5c57.png)

**Comment by SchabanBo** [comment]
It works now :)

**Comment by jonataslaw** [comment]
Solved by https://github.com/jonataslaw/getx/pull/917
