### ISSUE TITLE
pageView can not find controller

### ISSUE THREAD

**Issue by TomVista** [jonataslaw/getx#921]
**Describe the bug**

pageView can not find controller

**Reproduction code**

It can't be described simply with sample code,please see this [getx_test](https://github.com/TomVista/getx_test)

**To Reproduce**
![421122](https://user-images.githubusercontent.com/42435611/102455440-9383ac80-407a-11eb-8f46-311101c4d7f4.gif)

**Expected behavior**
After ``get.offall`` , pageview ``HomeController`` is null,can not get HomeController

**Flutter Version:**
```
PS C:\WINDOWS\system32> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.685], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.52.0)
[√] Connected device (1 available)

• No issues found!
PS C:\WINDOWS\system32>
```

**Getx Version:**
`` 3.17.1 ``

**Describe on which device you found the bug:**
android emulated device x86 ,android sdk 28

**Comment by mozaffari** [comment]
This is not an issue with the GetX. this is what should GetX behave. Get.offAll removes any controller that where Lazy Loaded.

If you want to have to the HomeController anywhere any time then you have to Get.Put(HomeController());  somewhere like main.dart 
`Widget build(BuildContext context) {
Get.Put(HomeController());
    return GetMaterialApp(
.......`

**Comment by TomVista** [comment]
thanks,
