### ISSUE TITLE
translation keys generator from json

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [jonataslaw/getx#922]
**Is your feature request related to a problem? Please describe.**
It is not really efficient making the translation manually. Some apps or services have the ability to translate you JSON file to multiple languages. The problem is converting that code into dart code is so problematic and not efficient at all.

**Describe the solution you'd like**
creating a generator for converting JSON files into keys in dart.

**Describe alternatives you've considered**
I used another package for translation which is tbh honest so great. It is called [easy_localization](https://pub.dev/packages/easy_localization). I use it in a bunch of apps.

**Comment by eduardoflorence** [comment]
You could use get_cli and this new feature:
https://github.com/jonataslaw/get_cli#generate-locates
