### ISSUE TITLE
Getx throws error when we run the command flutter test --platform chrome. 

### ISSUE THREAD

**Issue by jaikrishnavj** [jonataslaw/getx#923]
Getx throws series of error in flutter web app. when we run the following command **flutter test --platform chrome.**

We used the following command because we cannot able to use the command **flutter test** as we have used html libraries, it asked to run the above command, when we run that, it is throwing lots of errors at the console.

When i remove the get package and run the above command(**flutter test --platform chrome.**), no issues, there seems to be an issue with the getx.

i have attached image for reference.

![Screenshot from 2020-12-17 15-42-45](https://user-images.githubusercontent.com/76090155/102474368-8f598e00-407e-11eb-8e6a-7f0492391390.png)

The below are the some of the errors,

 ('org-dartlang-app:///packages/get/get_connect/http/src/certificates/certificates.dart').
    List<TrustedCertificate> trustedCertificates,
                             ^^^^^^^^^^^^^^^^^^^
org-dartlang-app:///packages/get/get_connect/sockets/src/sockets_html.dart:92:19: Error: Optional parameter 'status' should have a default value because its type
'int' doesn't allow null.
  void close([int status, String reason]) {
                  ^^^^^^
org-dartlang-app:///packages/get/get_connect/sockets/src/sockets_html.dart:92:34: Error: Optional parameter 'reason' should have a default value because its type
'String' doesn't allow null.
  void close([int status, String reason]) {
                                 ^^^^^^
org-dartlang-app:///packages/get/get_navigation/src/dialog/dialog_route.dart:7:32: Error: Optional parameter 'pageBuilder' should have a default value because its
type 'Widget Function(BuildContext, Animation<double>, Animation<double>)' doesn't allow null.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('org-dartlang-app:///packages/flutter/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('org-dartlang-app:///packages/flutter/src/widgets/framework.dart').
 - 'Animation' is from 'package:flutter/src/animation/animation.dart' ('org-dartlang-app:///packages/flutter/src/animation/animation.dart').
    @required RoutePageBuilder pageBuilder,
                               ^^^^^^^^^^^
org-dartlang-app:///packages/get/get_navigation/src/dialog/dialog_route.dart:9:12: Error: Optional parameter 'barrierLabel' should have a default value because
its type 'String' doesn't allow null.
    String barrierLabel,
           ^^^^^^^^^^^^
org-dartlang-app:///packages/get/get_navigation/src/dialog/dialog_route.dart:12:29: Error: Optional parameter 'transitionBuilder' should have a default value
because its type 'Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)' doesn't allow null.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('org-dartlang-app:///packages/flutter/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('org-dartlang-app:///packages/flutter/src/widgets/framework.dart').
 - 'Animation' is from 'package:flutter/src/animation/animation.dart' ('org-dartlang-app:///packages/flutter/src/animation/animation.dart').
    RouteTransitionsBuilder transitionBuilder,
                            ^^^^^^^^^^^^^^^^^

**Comment by SchabanBo** [comment]
It seems like you use null safety, which not supported yet with getx

**Comment by jaikrishnavj** [comment]
No @SchabanBo First i have tried in my project, later i tried in the fresh project, where there were no code, i have included the getx in project file and imported the file, it throwed error.

i have included the simple project,

Note : the below project will execute the command flutter test without any issues, we are facing the issue only when we run the command flutter test --platform chrome. We are developing a web app.

The reason why i have gone to the command is because we have dart:html import in our code hence everywhere it is suggested to use that  command.

[simplesample.zip](https://github.com/jonataslaw/getx/files/5708874/simplesample.zip)

**Comment by jaikrishnavj** [comment]
With the latest version of get: ^3.23.1, it seems it is fixed.
