### ISSUE TITLE
class HomeController extends GetxController with StateMixin<CasesModel>,StateMixin<Country>  Cant work

### ISSUE THREAD

**Issue by wengxianxun** [jonataslaw/getx#926]
class HomeController extends GetxController with StateMixin<CasesModel>,StateMixin<Country>  Cant work

**Comment by ghprod** [comment]
Please add reproduction code

**Comment by Minsamin** [comment]
Can't use multiple StateMixin in single Controller ? Any Help ?

**Comment by eduardoflorence** [comment]
In my opinion you should have a controller for each StateMixin to separate the responsibilities. Using binding you can inject all the controllers you want for a single view.

**Comment by jonataslaw** [comment]
StateMixin controls the state of a controller. You CANNOT have more than one StateMixin on a controller.
