### ISSUE TITLE
How can I get this parameter in OnInit

### ISSUE THREAD

**Issue by lycstar** [jonataslaw/getx#927]
I need to use the parameter passed from the previous page in the OnInit method to request the network. How can I get this parameter in OnInit

**Comment by eduardoflorence** [comment]
In view:
`Get.to(AnotherPage(), arguments: 'myargument');`

In onInit of AnotherPage() controller:
`final arguments = Get.arguments;`

**Comment by lycstar** [comment]
@eduardoflorence so easy,thank you!
