### ISSUE TITLE
You are trying to use contextless navigation without  a GetMaterialApp or Get.key.

### ISSUE THREAD

**Issue by yaasoof** [jonataslaw/getx#931]
this error show after use LD player emulator
and i try your solve by wrap my project GetMaterialApp 
```
void main() async {
  await GetStorage.init();
  runApp(
      GetMaterialApp(home: HomePage()));
}
`

**Comment by thanhdang1709** [comment]
I am having the same problem

**Comment by jonataslaw** [comment]
Please respect the issue opening form, inserting a reproduction code for your problem.

**Comment by H7mosh** [comment]
i had the same issue
