### ISSUE TITLE
Trying to use contextless navigation

### ISSUE THREAD

**Issue by yaasoof** [jonataslaw/getx#932]
This error show after run app on emulator ld player
![FB_IMG_1608474849204](https://user-images.githubusercontent.com/25013814/102715981-74d31f00-42e1-11eb-916f-2dbcd1772473.jpg)
![FB_IMG_1608474853507](https://user-images.githubusercontent.com/25013814/102715993-8f0cfd00-42e1-11eb-8823-575cf1531102.jpg)

**Comment by eduardoflorence** [comment]
@yaasoof, only the code you provided does not cause this error. Please provide a more complete code (imports, widgets, controllers)

**Comment by yaasoof** [comment]
The seem code run in my physical device but in emulator dont work 
What mean Get.testmode and when we use it

**Comment by eduardoflorence** [comment]
`Get.testMode` is used only in tests, when we have navigation without context. You need to provide a minimum code so that we can reproduce the error

**Comment by yaasoof** [comment]
It's work after add get.testmode=true

**Comment by abdelrahmanelmarakby** [comment]
@yaasoof where to add this line
