### ISSUE TITLE
[GetConnect] ADD HTTP PATCH REQUEST

### ISSUE THREAD

**Issue by wquintanilhadasilva** [jonataslaw/getx#934]
I need to send a PATCH request to the server.

I have resources on the server that implement the PATCH verb to modify parts of a document.

Could you add this feature in the same way as POST and PUT?

Example:

`PATCH / groups / {group id} {"attributes": {"status": "active"}}
response: 200 OK`

`PATCH / groups / {group id} {"attributes": {"status": "deleted"}}
response: 406 Not Acceptable`

[MDN PATCH reference](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Methods/PATCH)

Thanks.

**Comment by jonataslaw** [comment]
Added on 3.24
