### ISSUE TITLE
isTrue/isFalse getters for RxBool instead of value

### ISSUE THREAD

**Issue by ibrahimyu** [jonataslaw/getx#935]
Tiny enhancement for code readability: for boolean values with .obs/RxBool

```
var useManualMode = false.obs;
```

We can't use RxBool for conditional statements, so we need to access it by value prop:

```
Obx(() => controller.useManualMode.value ? SomeWidget() : SomeWidget2();
```

No problem, but this would be much more readable:

```
Obx(() => controller.useManualMode.isTrue ? SomeWidget() : SomeWidget2();
Obx(() => controller.useManualMode.isFalse ? SomeWidget() : SomeWidget2();
```

**Comment by jonataslaw** [comment]
I like it
I'll implement on next update

**Comment by jonataslaw** [comment]
Added on 3.24
