### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by tyagiarpit383** [jonataslaw/getx#942]
Hello there, I am new to App development, please help me to resolve this issue,
 I am getting a "NoSuchMethodError"
![Screenshot_20201224-024712](https://user-images.githubusercontent.com/66261791/103038144-b2f76980-4593-11eb-8b4c-495eda20c930.jpg)

**Comment by jonataslaw** [comment]
Please search the community channels if you want help with development, this channel is for opening issues.

**Comment by tyagiarpit383** [comment]
Hey mate, Can't you help me with this?
i really need this to be solved urgently
