### ISSUE TITLE
Question - Do you have an example of using GetX Service for Authentication and data storage for Hive.. (Not an Issue)

### ISSUE THREAD

**Issue by rmControls** [jonataslaw/getx#946]
Hello,

Thank you for developing a great package... I really love it....

I am new to flutter and GetX....I would like to know is there a way or proper method to implement GetX for authentication, Storing Authenticated user data in database and making these service available in all the modules of the application....

I did research in google, stackoverflow and medium to see if there any example or solution which have combination of GetX, Hive[any database] and Authentication. but unfortunately not found any useful information....

Do you have any documentation or example for this type case??

I am sorry for posting my question here... I didn't find the right place to ask this question....

**Comment by eduardoflorence** [comment]
Hi @rmControls, use these channels: https://github.com/jonataslaw/getx#community-channels
Github is only for new features and bugs.
