### ISSUE TITLE
The problem of using name router

### ISSUE THREAD

**Issue by HanXiaoTeng** [jonataslaw/getx#947]
**Describe the bug**
If I use  "Get.toName("/next")" to jump to the next router, and the next router will be a routing jump from a third-party library， it is system router.Then there will be a problem with the jump animation of this route.But if I use "navigator.push(MaterialPageRoute(builder: (_) => NextPage()))" there is no such problem

**Reproduction code

example:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:wechat_assets_picker/wechat_assets_picker.dart';

void main() {
  runApp(GetMaterialApp(
    getPages: [GetPage(name: "/next", page: () => NextPage())],
    home: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("GetX_Demo"),
        ),
        body: Container(
          child: Center(
            child: RaisedButton(
              child: Text("Next Page"),
              //  

https://user-images.githubusercontent.com/14963226/103122677-3d3aed00-46bc-11eb-8aec-05ede3972c1c.mp4

navigator.push(MaterialPageRoute(builder: (_) => NextPage()))
              onPressed: () => Get.toNamed("/next"),
            ),
          ),
        ),
      ),
    );
  }
}

class NextPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Next"),
      ),
      body: Container(
        child: Center(
          child: RaisedButton(
            child: Text("Clicked"),
            onPressed: () {
              AssetPicker.pickAssets(context,
                  themeColor: Colors.red,
                  maxAssets: 1,
                  gridCount: 5,
                  pageSize: 100,
                  routeCurve: Curves.linear);
            },
          ),
        ),
      ),
    );
  }
}
```

**To Reproduce**
1. Click on 'Next Page'
2. Click on 'Clicked'
3. See error

**Expected behavior**
There should not be a right-to-left routing animation when jumping to a third-party routing

**Flutter Version:**
Version 1.22.5

**Getx Version:**
Version 3.24.0

**Describe on which device you found the bug:**
All Device

**Minimal reproduce code**
Get.toNamed("/next")

**Comment by HanXiaoTeng** [comment]
The problem video:

https://user-images.githubusercontent.com/14963226/103122703-58a5f800-46bc-11eb-9fbe-f0caee2a37b8.mp4

**Comment by jonataslaw** [comment]
Hey, if you're using an iPhone, the expected behavior is for the default transition to be cupertino.
MaterialPageRoute inserts the android fade transition on any device, be it android or ios.
If you want the default transition to be that of android, just define in your GetMaterialApp:

defaultTransition: Transition.fade,
