### ISSUE TITLE
how to use more controller with GetBuilder

### ISSUE THREAD

**Issue by dancheng99** [jonataslaw/getx#952]
**Reproduction code
```
GetPage(
        name: 'IndexPage',
        page: () => IndexPage(),
        transition: Transition.rightToLeft,
        binding: BindingsBuilder(() {
          Get.put(AController());
          Get.put(BController());
          ...more...
        })),


 GetBuilder<AController>(
                init: AController(), 

how to use BController() and more
```

**Comment by eduardoflorence** [comment]
Above GetBuilder (at the beginning of the page), you will have to find the other controller instances:
```dart
final controllerB = Get.find<BController>();
final controllerC = Get.find<CController>();
```

**Comment by dancheng99** [comment]
> Above GetBuilder (at the beginning of the page), you will have to find the other controller instances:
> 
> ```dart
> final controllerB = Get.find<BController>();
> final controllerC = Get.find<CController>();
> ```

i hope use GetBuilder<controllerB ,controllerC,...> ^^

**Comment by axu6705** [comment]
in controllerA
```js
BController get b => Get.find<BController>();
```
controller.b....

**Comment by dancheng99** [comment]
> in controllerA
> 
> ```js
> BController get b => Get.find<BController>();
> ```
> 
> controller.b....

thanks
