### ISSUE TITLE
Get.Theme return null at first build of widget.

### ISSUE THREAD

**Issue by micodev** [jonataslaw/getx#953]
I used the example of theme that I found at bottom of Get docs it was working just fine until it `get` updated

**Reproduction code**
```dart
GetMaterialApp(
          translations: Messages(),
          fallbackLocale: Get.deviceLocale,
          locale: Get.deviceLocale,
          theme: Themes.light,
          darkTheme: Themes.dark,
          themeMode: ThemeMode.light, 

```

**To Reproduce**
1. Navigate to Mainscreen
2. error raised  `The getter 'scaffoldBackgroundColor'`

![image](https://user-images.githubusercontent.com/17555698/103215567-c3f20300-4924-11eb-8dd1-14f4d2759b80.png)

**Flutter Version:**
1.22.5

**Getx Version:**
^3.23.1 also I tried with the latest

**Comment by jonataslaw** [comment]
Insert a valid reproduction code, or the issue will be closed
