### ISSUE TITLE
GetPage parameter cant not work

### ISSUE THREAD

**Issue by dancheng99** [jonataslaw/getx#955]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
GetPage 
        title:  how to use?
        popGesture: what is this?
        maintainState what is this?
        opaque what is this?

**Reproduction code
```
router.dart
 GetPage(
        name: 'RouterPage3',
        page: () => RouterPage3(),
        parameter:{'a':'aaa'},

RouterPage2.dart
 ElevatedButton(
                onPressed: () {
                  Get.toNamed("RouterPage3");
                },
                child: Text('RouterPage3')),

RouterPage3.dart
  ElevatedButton(
                  onPressed: () {
                    print(Get.arguments);
                    print(Get.parameters);
                  },
                  child: Text('Get.arguments')),

```

**To Reproduce**
 print(Get.arguments);  null
 print(Get.parameters); { }

**Expected behavior**

**Screenshots**

**Flutter Version:**

**Getx Version:**
Enter the version of the Getx you are using

**Describe on which device you found the bug:**
ex: Moto z2 - Android.

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jonataslaw** [comment]
https://github.com/jonataslaw/getx/blob/master/documentation/en_US/route_management.md
