### ISSUE TITLE
Wrong code in the documentation

### ISSUE THREAD

**Issue by dariocavada** [jonataslaw/getx#966]
**Describe the bug**
Just a minor bug in the code inside the documentation at the page:
https://github.com/jonataslaw/getx/blob/master/documentation/en_US/dependency_management.md

In the **Bindings Builder** section

If you copy the example it does not work...

to correct the problem do the following:

**from:**
`binding: BindingsBuilder(() => { `

**to:**
`binding: BindingsBuilder(() {`

just remove the `=>` from BindingsBuilder

example that works:

```dart
getPages: [
  GetPage(
    name: '/',
    page: () => HomeView(),
    binding: BindingsBuilder(() {
      Get.lazyPut<ControllerX>(() => ControllerX());
      Get.put<Service>(()=> Api());
    }),
  ),
  GetPage(
    name: '/details',
    page: () => DetailsView(),
    binding: BindingsBuilder(() {
      Get.lazyPut<DetailsController>(() => DetailsController());
    }),
  ),
];
```

**Comment by jonataslaw** [comment]
You're right, I'll fix this asap
