### ISSUE TITLE
onPressed: Get.back doesn't work

### ISSUE THREAD

**Issue by matthewkooshad** [jonataslaw/getx#968]
**ATTENTION: DO NOT USE THIS FIELD TO ASK SUPPORT QUESTIONS. USE THE PLATFORM CHANNELS FOR THIS. THIS SPACE IS DEDICATED ONLY FOR BUGS DESCRIPTION.**
**Fill in the template. Issues that do not respect the model will be closed.**

**Describe the bug**
onPressed: Get.back doesn't work

however, this works: onPressed: () => Get.back(),
but, this linter that i want to keep is catching it: https://dart-lang.github.io/linter/lints/unnecessary_lambdas.html
i don't want to use below to avoid the linter:
```
onPressed: () {
                          Get.back();
                        },
```
**Reproduction code
NOTE: THIS IS MANDATORY, IF YOUR ISSUE DOES NOT CONTAIN IT, IT WILL BE CLOSED PRELIMINARY)**

```dart
class BackNavButton extends StatelessWidget {
  final double iconSize;

  const BackNavButton({
    Key key,
    @required this.iconSize,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return IconButton(
      icon: Icon(
        backNavIcon,
        color: headerItemColor,
        size: iconSize * backNavIconSizer,
      ),
      onPressed: Get.back,
    );
  }
}
```

**To Reproduce**
1. try to use the onPressed
2. it will do nothing

**Expected behavior**
for it to go back

**Screenshots**
![image](https://user-images.githubusercontent.com/6706761/103415681-e3697580-4b48-11eb-9654-b53aaf4a5310.png)

**Flutter Version:**
Flutter 1.24.0-10.2.pre • channel beta •

**Getx Version:**
get: ^3.24.0

**Describe on which device you found the bug:**
Android.

**Minimal reproduce code**
see Reproduction code section.

**Comment by jonataslaw** [comment]
With the reproduction code bellow, I can confirm that the problem does not occur.
If you believe this is a bug, open the issue with the valid reproduction code.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(home: First()));
}

class First extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('fisrt page'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            RaisedButton(
              child: Text('Go to second'),
              onPressed: () {
                Get.to(Second());
              },
            ),
          ],
        ),
      ),
    );
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('second'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            IconButton(
              icon: Icon(
                Icons.arrow_back,
              ),
              onPressed: Get.back,
            ),
          ],
        ),
      ),
    );
  }
}


```

**Comment by matthewkooshad** [comment]
sorry for the false alarm. i tested it multiple times earlier, and 'Second ' widget example wasn't working for me. but, now it is! thanks for confirming it's not a problem!
