### ISSUE TITLE
permanent true 

### ISSUE THREAD

**Issue by hatemragab** [jonataslaw/getx#981]
when I declare permanent true to controller now on close not working how to know if the user off the view of the controller? when the user off the page Getx log => "HomeController" has been marked as permanent, SmartManagement is not authorized to delete it.

**Comment by hatemragab** [comment]
something like dispose in statefull wegets it possible in getView?

**Comment by SchabanBo** [comment]
I am not sure if I understoud this right. but i think you want to do somthing when the user closes a page.
you can do that by setting a `Middleware` to the page. and do you what you want to do when page closes  in the `OnPageDispose`

https://github.com/jonataslaw/getx#onpagedispose

**Comment by hatemragab** [comment]
let me try 

> I am not sure if I understoud this right. but i think you want to do somthing when the user closes a page.
> you can do that by setting a `Middleware` to the page. and do you what you want to do when page closes in the `OnPageDispose`
> 
> https://github.com/jonataslaw/getx#onpagedispose

**Comment by hatemragab** [comment]
> I am not sure if I understoud this right. but i think you want to do somthing when the user closes a page.
> you can do that by setting a `Middleware` to the page. and do what you want to do when page closes in the `OnPageDispose`
> 
> https://github.com/jonataslaw/getx#onpagedispose

where I can override onpagedispose can u drop a simple example  thanks

**Comment by SchabanBo** [comment]
```dart
class MyMiddleware extends GetMiddleware {
  @override
  void OnPageDispose() {
   // Do your work
  }
}
```
and use it 
```dart
 GetPage(
      name: '/getPage',
      page: () => GetPageExampleView(),
      title: 'Get Page Examples',
      middlewares: [
        MyMiddleware ()
      ]);
```

**Comment by eduardoflorence** [comment]
Adding:

```dart
class MyMiddleware extends GetMiddleware {
  @override
  void OnPageDispose() {
    if (Get.previousRoute = '/anotherpage') { ... }
  }
}
```

**Comment by hatemragab** [comment]
> ```dart
> class MyMiddleware extends GetMiddleware {
>   @override
>   void OnPageDispose() {
>    // Do your work
>   }
> }
> ```
> 
> and use it
> 
> ```dart
>  GetPage(
>       name: '/getPage',
>       page: () => GetPageExampleView(),
>       title: 'Get Page Examples',
>       middlewares: [
>         MyMiddleware ()
>       ]);
> ```

thanks bro it works
