### ISSUE TITLE
ReadMe support 

### ISSUE THREAD

**Issue by UsamaElgendy** [jonataslaw/getx#983]
I am writing this to request you for an extension on my YouTube course  

I. Explain getx package on 4 videos in Arabic language for the Middle east.

Can you add it in your doc for Arabic people … and thanks for this great and useful package 

Sincerely,

Usama Elgindy

Pesa Coder.     https://www.youtube.com/playlist?list=PLV1fXIAyjeuZ6M8m56zajMUwu4uE3-SL0

**Comment by eduardoflorence** [comment]
Hello @UsamaElgendy, would you be able to fork this repository and send a Pull Request with the Readme change?

**Comment by UsamaElgendy** [comment]
I made a pull request thanks
