### ISSUE TITLE
What is the best practice for the controller get argments?

### ISSUE THREAD

**Issue by seekcx** [jonataslaw/getx#986]
**Is your feature request related to a problem? Please describe.**

I have a page, it is possible to use Get.to or Get.toNamed to open it, but in the controller, only Get.argments can be used to get the parameters, which makes the parameters passed by Get.to unavailable. How can I access it? Get the parameters passed by Get.to in onInit?

```dart

/// screen.dart
class RegionScreen extends GetView<RegionController> {
  const RegionScreen({
    Key key,
    this.parent,
  }) : super(key: key);

  final int parent;

  // ...
}

/// constroller.dart
class RegionController extends GetxController {
  @override
  void onInit() {
    super.onInit();
    // !!!! Get the parameters here. !!!!!
    final parent = Get.argments['parent'];    
   
    fetchData(parent);
  }

  // ...
}

Get.to(RegionScreen(parent: 1)); // Cannot receive parameters.
Get.toNamed('/region', argments: { 'parent': 1 });  // Parameters can be received.
```

**Describe alternatives you've considered**
I don't know any alternatives.

**Comment by SchabanBo** [comment]
you are sending the parameter to `RegionScreen`  not to the `Get.to()`. Do something like this.
```dart
Get.to(RegionScreen(), argments: { 'parent': 1 });
```

**Comment by seekcx** [comment]
> you are sending the parameter to `RegionScreen` not to the `Get.to()`. Do something like this.
> 
> ```dart
> Get.to(RegionScreen(), argments: { 'parent': 1 });
> ```

Thanks, it finally works! I did not see that Get.to also has argments.
