### ISSUE TITLE
Unused controller initialization of route (Getx Binding)

### ISSUE THREAD

**Issue by papmodern** [jonataslaw/getx#987]
When there is no usage of controller inside the view, controller would not initialize at all.
Please don't tell me this is a feature!!!

**To Reproduce**
1- Write a binding GetPage with binding, controller and view classes
2- DO NOT use controller inside view (just extend GetView<Controller>)
3- Write some code inside onInit. 
4- The code would not execute!.

**Expected behavior**
I expect controller gets initialize 

**Flutter Version:**
1.24.0-10.2.pre • channel beta 

**Getx Version:**
3.24.0

**Describe on which device you found the bug:**
Android emulator api 28.

**Reproduction Code:**
```dart
void main() => runApp(
      GetMaterialApp(
        title: "MyApp",
        initialRoute: 'MyRoute',
        getPages: [
          GetPage(
            name: 'MyRoute',
            page: () => MyView(),
            binding: MyBinding(),
          ),
        ],
      ),
    );

class MyBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<MyController>(
      () => MyController(),
    );
  }
}

class MyController extends GetxController {
  @override
  void onInit() {
    print('It must be execute, but it won\'t');
  }

  @override
  void onReady() {}

  @override
  void onClose() {}
}

class MyView extends GetView<MyController> {
  @override
  Widget build(context) {
    return Material(child: Center(child: Text("No use of controller")));
  }
}
```

**Comment by SchabanBo** [comment]
Use `Get.put` instead of `Get.lazyPut` in you bindings.

**Comment by Suhailakl** [comment]
I'm facing the same issue
